var aa,g;var h;h||(h=typeof Module !== 'undefined' ? Module : {});var ba={},l;for(l in h)h.hasOwnProperty(l)&&(ba[l]=h[l]);h.arguments=[];h.thisProgram="./this.program";h.quit=function(a,b){throw b;};h.preRun=[];h.postRun=[];var ca=!1,da=!1,ea=!1,fa=!1,ha=!1;ca="object"===typeof window;da="function"===typeof importScripts;ea=(fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!ca&&!da;ha=!ca&&!ea&&!da;var m="";
if(ea){m=__dirname+"/";var ia,ja;h.read=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);a=ia.readFileSync(a);return b?a:a.toString()};h.readBinary=function(a){a=h.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(h.thisProgram=process.argv[1].replace(/\\/g,"/"));h.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});process.on("unhandledRejection",
p);h.quit=function(a){process.exit(a)};h.inspect=function(){return"[Emscripten Module object]"}}else if(ha)"undefined"!=typeof read&&(h.read=function(a){return read(a)}),h.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?h.arguments=scriptArgs:"undefined"!=typeof arguments&&(h.arguments=arguments),"function"===typeof quit&&(h.quit=function(a){quit(a)});else if(ca||da)da?
m=self.location.href:document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.lastIndexOf("/")+1):"",h.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},da&&(h.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),h.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},h.setWindowTitle=function(a){document.title=a};var la=h.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),r=h.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||la);for(l in ba)ba.hasOwnProperty(l)&&(h[l]=ba[l]);ba=void 0;function ma(a){var b=t[na>>2];a=b+a+15&-16;a>v.length&&p();t[na>>2]=a;return b}
"object"!==typeof WebAssembly&&r("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||p("Assertion failed: "+b)}function ra(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=w(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)t[a>>2]=0;for(b=d+c;a<b;)v[a++>>0]=0;return d}a.subarray||a.slice?y.set(a,d):y.set(new Uint8Array(a),d);return d}function sa(a){for(var b="";;){var c=y[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}}
var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?ua(y,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function wa(a){var b=va(a)+1,c=xa(b);A(a,v,c,b);return c}var buffer,v,y,ya,za,t,B,C,D,na=270736,Aa=h.TOTAL_MEMORY||16777216;5242880>Aa&&r("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Aa+"! (TOTAL_STACK=5242880)");
h.wasmMemory?oa=h.wasmMemory:oa=new WebAssembly.Memory({initial:Aa/65536,maximum:Aa/65536});oa&&(buffer=oa.buffer);Aa=buffer.byteLength;h.HEAP8=v=new Int8Array(buffer);h.HEAP16=ya=new Int16Array(buffer);h.HEAP32=t=new Int32Array(buffer);h.HEAPU8=y=new Uint8Array(buffer);h.HEAPU16=za=new Uint16Array(buffer);h.HEAPU32=B=new Uint32Array(buffer);h.HEAPF32=C=new Float32Array(buffer);h.HEAPF64=D=new Float64Array(buffer);t[na>>2]=5513648;
function Ba(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Xd;"number"===typeof c?void 0===b.wd?h.dynCall_v(c):h.dynCall_vi(c,b.wd):c(void 0===b.wd?null:b.wd)}}}var Ca=[],Da=[],Ea=[],Fa=[],Ga=[],Ha=!1;function Ia(){var a=h.preRun.shift();Ca.unshift(a)}var Ja=Math.abs,Ka=Math.sqrt,La=Math.ceil,Ma=Math.floor,Na=Math.min,Oa=0,Pa=null,Qa=null;h.preloadedImages={};h.preloadedAudios={};
function Ra(){var a=Sa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Sa="magnum-imgui.wasm";if(!Ra()){var Ta=Sa;Sa=h.locateFile?h.locateFile(Ta,m):m+Ta}function Ua(){try{if(h.wasmBinary)return new Uint8Array(h.wasmBinary);if(h.readBinary)return h.readBinary(Sa);throw"both async and sync fetching of the wasm failed";}catch(a){p(a)}}
function Va(){return h.wasmBinary||!ca&&!da||"function"!==typeof fetch?new Promise(function(a){a(Ua())}):fetch(Sa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Sa+"'";return a.arrayBuffer()}).catch(function(){return Ua()})}
function Wa(a){function b(a){h.asm=a.exports;Oa--;h.monitorRunDependencies&&h.monitorRunDependencies(Oa);0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa&&(a=Qa,Qa=null,a()))}function c(a){b(a.instance)}function d(a){return Va().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){r("failed to asynchronously prepare wasm: "+a);p(a)})}var e={env:a};Oa++;h.monitorRunDependencies&&h.monitorRunDependencies(Oa);if(h.instantiateWasm)try{return h.instantiateWasm(e,b)}catch(f){return r("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(h.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ra()||"function"!==typeof fetch)return d(c);fetch(Sa,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(c,function(a){r("wasm streaming compile failed: "+a);r("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}h.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:541,maximum:541,element:"anyfunc"});return Wa(b)};
var Ya=[function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?h.dynCall_ii.apply(null,[a].concat(e)):h.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(){var a=h.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?ra(Xa(a.id)):0},function(a){document.getElementById("canvas").style.cursor=sa(a)},function(a){a=z(a);return"undefined"!==typeof process&&a in process.env?ra(Xa(process.env[a])):0}];
Da.push({Xd:function(){Za()}});var E={};
function $a(a){if($a.Xc){var b=t[a>>2];var c=t[b>>2]}else $a.Xc=!0,E.USER=E.LOGNAME="web_user",E.PATH="/",E.PWD="/",E.HOME="/home/web_user",E.LANG="C.UTF-8",E.LANG=("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",E._=h.thisProgram,c=Ha?w(1024):ma(1024),b=Ha?w(256):ma(256),t[b>>2]=c,t[a>>2]=b;a=[];var d=0,e;for(e in E)if("string"===typeof E[e]){var f=e+"="+E[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=
0;e<a.length;e++){d=f=a[e];for(var k=c,n=0;n<d.length;++n)v[k++>>0]=d.charCodeAt(n);v[k>>0]=0;t[b+4*e>>2]=c;c+=f.length+1}t[b+4*a.length>>2]=0}function ab(a){h.___errno_location&&(t[h.___errno_location()>>2]=a)}function bb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function cb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function eb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function fb(){var a=Array.prototype.slice.call(arguments,0);return cb(a.join("/"))}function gb(a,b){return cb(a+"/"+b)}function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],output:[],dd:b};kb(a,lb)}
var lb={open:function(a){var b=ib[a.node.rdev];if(!b)throw new F(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.dd.flush(a.tty)},flush:function(a){a.tty.dd.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.dd.Od)throw new F(6);for(var e=0,f=0;f<d;f++){try{var k=a.tty.dd.Od(a.tty)}catch(n){throw new F(5);}if(void 0===k&&0===e)throw new F(11);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.dd.Cd)throw new F(6);
try{for(var e=0;e<d;e++)a.tty.dd.Cd(a.tty,b[c+e])}catch(f){throw new F(5);}d&&(a.node.timestamp=Date.now());return e}},mb={Od:function(a){if(!a.input.length){var b=null;if(ea){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(k){}}try{d=fs.readSync(e,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Xa(b,!0)}return a.input.shift()},Cd:function(a,b){null===b||10===b?(la(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(ua(a.output,0)),a.output=[])}},nb={Cd:function(a,b){null===b||10===b?(r(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(r(ua(a.output,0)),a.output=[])}},G={Wc:null,Tc:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(1);G.Wc||(G.Wc={dir:{node:{Yc:G.Oc.Yc,Vc:G.Oc.Vc,lookup:G.Oc.lookup,kd:G.Oc.kd,rename:G.Oc.rename,unlink:G.Oc.unlink,rmdir:G.Oc.rmdir,readdir:G.Oc.readdir,symlink:G.Oc.symlink},stream:{$c:G.Nc.$c}},file:{node:{Yc:G.Oc.Yc,Vc:G.Oc.Vc},stream:{$c:G.Nc.$c,read:G.Nc.read,write:G.Nc.write,Ed:G.Nc.Ed,Qd:G.Nc.Qd,
sd:G.Nc.sd}},link:{node:{Yc:G.Oc.Yc,Vc:G.Oc.Vc,readlink:G.Oc.readlink},stream:{}},Gd:{node:{Yc:G.Oc.Yc,Vc:G.Oc.Vc},stream:ob}});c=pb(a,b,c,d);16384===(c.mode&61440)?(c.Oc=G.Wc.dir.node,c.Nc=G.Wc.dir.stream,c.Mc={}):32768===(c.mode&61440)?(c.Oc=G.Wc.file.node,c.Nc=G.Wc.file.stream,c.Rc=0,c.Mc=null):40960===(c.mode&61440)?(c.Oc=G.Wc.link.node,c.Nc=G.Wc.link.stream):8192===(c.mode&61440)&&(c.Oc=G.Wc.Gd.node,c.Nc=G.Wc.Gd.stream);c.timestamp=Date.now();a&&(a.Mc[b]=c);return c},le:function(a){if(a.Mc&&
a.Mc.subarray){for(var b=[],c=0;c<a.Rc;++c)b.push(a.Mc[c]);return b}return a.Mc},me:function(a){return a.Mc?a.Mc.subarray?a.Mc.subarray(0,a.Rc):new Uint8Array(a.Mc):new Uint8Array},Jd:function(a,b){var c=a.Mc?a.Mc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Mc,a.Mc=new Uint8Array(b),0<a.Rc&&a.Mc.set(c.subarray(0,a.Rc),0))},be:function(a,b){if(a.Rc!=b)if(0==b)a.Mc=null,a.Rc=0;else{if(!a.Mc||a.Mc.subarray){var c=a.Mc;a.Mc=new Uint8Array(new ArrayBuffer(b));c&&
a.Mc.set(c.subarray(0,Math.min(b,a.Rc)))}else if(a.Mc||(a.Mc=[]),a.Mc.length>b)a.Mc.length=b;else for(;a.Mc.length<b;)a.Mc.push(0);a.Rc=b}},Oc:{Yc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Rc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ad=4096;b.blocks=Math.ceil(b.size/
b.ad);return b},Vc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.be(a,b.size)},lookup:function(){throw qb[2];},kd:function(a,b,c,d){return G.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=rb(b,c)}catch(f){}if(d)for(var e in d.Mc)throw new F(39);}delete a.parent.Mc[a.name];a.name=c;b.Mc[c]=a;a.parent=b},unlink:function(a,b){delete a.Mc[b]},rmdir:function(a,b){var c=rb(a,b),d;for(d in c.Mc)throw new F(39);
delete a.Mc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Mc)a.Mc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new F(22);return a.link}},Nc:{read:function(a,b,c,d,e){var f=a.node.Mc;if(e>=a.node.Rc)return 0;a=Math.min(a.node.Rc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.Mc||a.Mc.subarray)){if(f)return a.Mc=b.subarray(c,c+d),a.Rc=d;if(0===a.Rc&&0===e)return a.Mc=new Uint8Array(b.subarray(c,c+d)),a.Rc=d;if(e+d<=a.Rc)return a.Mc.set(b.subarray(c,c+d),e),d}G.Jd(a,e+d);if(a.Mc.subarray&&b.subarray)a.Mc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Mc[e+f]=b[c+f];a.Rc=Math.max(a.Rc,e+d);return d},$c:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Rc);if(0>b)throw new F(22);return b},Ed:function(a,
b,c){G.Jd(a.node,b+c);a.node.Rc=Math.max(a.node.Rc,b+c)},Qd:function(a,b,c,d,e,f,k){if(32768!==(a.node.mode&61440))throw new F(19);c=a.node.Mc;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.Rc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=w(d);if(!d)throw new F(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{re:d,Ud:a}},sd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(19);if(e&2)return 0;G.Nc.write(a,b,0,d,c,!1);return 0}}},H={qd:!1,de:function(){H.qd=
!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);H.Ld={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Fd:function(a){return Buffer.Xc?Buffer.from(a):new Buffer(a)},Tc:function(a){assert(fa);return H.createNode(null,"/",H.Nd(a.Bd.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new F(22);a=pb(a,b,c);a.Oc=H.Oc;a.Nc=H.Nc;return a},Nd:function(a){try{var b=
fs.lstatSync(a);H.qd&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new F(-c.Qc);}return b.mode},Uc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Tc.Bd.root);b.reverse();return fb.apply(null,b)},Wd:function(a){a&=-2656257;var b=0,c;for(c in H.Ld)a&c&&(b|=H.Ld[c],a^=c);if(a)throw new F(22);return b},Oc:{Yc:function(a){a=H.Uc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new F(-c.Qc);}H.qd&&!b.ad&&(b.ad=4096);H.qd&&!b.blocks&&(b.blocks=
(b.size+b.ad-1)/b.ad|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,ad:b.ad,blocks:b.blocks}},Vc:function(a,b){var c=H.Uc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new F(-d.Qc);}},lookup:function(a,b){var c=gb(H.Uc(a),b);c=H.Nd(c);return H.createNode(a,b,c)},kd:function(a,b,c,d){a=H.createNode(a,b,c,d);b=H.Uc(a);
try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new F(-e.Qc);}return a},rename:function(a,b,c){a=H.Uc(a);b=gb(H.Uc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new F(-d.Qc);}},unlink:function(a,b){a=gb(H.Uc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new F(-c.Qc);}},rmdir:function(a,b){a=gb(H.Uc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new F(-c.Qc);}},readdir:function(a){a=
H.Uc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new F(-b.Qc);}},symlink:function(a,b,c){a=gb(H.Uc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new F(-d.Qc);}},readlink:function(a){var b=H.Uc(a);try{return b=fs.readlinkSync(b),b=sb.relative(sb.resolve(a.Tc.Bd.root),b)}catch(c){if(!c.code)throw c;throw new F(-c.Qc);}}},Nc:{open:function(a){var b=H.Uc(a.node);try{32768===(a.node.mode&61440)&&(a.ld=fs.openSync(b,H.Wd(a.flags)))}catch(c){if(!c.code)throw c;throw new F(-c.Qc);
}},close:function(a){try{32768===(a.node.mode&61440)&&a.ld&&fs.closeSync(a.ld)}catch(b){if(!b.code)throw b;throw new F(-b.Qc);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.ld,H.Fd(b.buffer),c,d,e)}catch(f){throw new F(-f.Qc);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.ld,H.Fd(b.buffer),c,d,e)}catch(f){throw new F(-f.Qc);}},$c:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ld).size}catch(d){throw new F(-d.Qc);
}if(0>b)throw new F(22);return b}}},tb=null,ub={},vb=[],wb=1,xb=null,yb=!0,zb={},F=null,qb={};
function I(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Md:!0,Dd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Dd)throw new F(40);a=bb(a.split("/").filter(function(a){return!!a}),!1);var e=tb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=rb(e,a[d]);c=gb(c,a[d]);e.rd&&(!f||f&&b.Md)&&(e=e.rd.root);if(!f||b.yd)for(f=0;40960===(e.mode&61440);)if(e=Ab(c),c=hb(db(c),e),e=I(c,{Dd:b.Dd}).node,40<f++)throw new F(40);}return{path:c,node:e}}
function Bb(a){for(var b;;){if(a===a.parent)return a=a.Tc.Rd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Cb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%xb.length}function Db(a){var b=Cb(a.parent.id,a.name);a.ae=xb[b];xb[b]=a}function rb(a,b){var c;if(c=(c=Eb(a,"x"))?c:a.Oc.lookup?0:13)throw new F(c,a);for(c=xb[Cb(a.id,b)];c;c=c.ae){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Oc.lookup(a,b)}
function pb(a,b,c,d){Fb||(Fb=function(a,b,c,d){a||(a=this);this.parent=a;this.Tc=a.Tc;this.rd=null;this.id=wb++;this.name=b;this.mode=c;this.Oc={};this.Nc={};this.rdev=d},Fb.prototype={},Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Fb(a,b,c,d);Db(a);return a}
var Gb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Hb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Eb(a,b){if(yb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Ib(a,b){try{return rb(a,b),17}catch(c){}return Eb(a,"wx")}
function Jb(a){var b=4096;for(a=a||0;a<=b;a++)if(!vb[a])return a;throw new F(24);}function Kb(a,b){Lb||(Lb=function(){},Lb.prototype={},Object.defineProperties(Lb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Lb,d;for(d in a)c[d]=a[d];a=c;b=Jb(b);a.fd=b;return vb[b]=a}var ob={open:function(a){a.Nc=ub[a.node.rdev].Nc;a.Nc.open&&a.Nc.open(a)},$c:function(){throw new F(29);}};function kb(a,b){ub[a]={Nc:b}}
function Mb(a,b){var c="/"===b,d=!b;if(c&&tb)throw new F(16);if(!c&&!d){var e=I(b,{Md:!1});b=e.path;e=e.node;if(e.rd)throw new F(16);if(16384!==(e.mode&61440))throw new F(20);}b={type:a,Bd:{},Rd:b,$d:[]};a=a.Tc(b);a.Tc=b;b.root=a;c?tb=a:e&&(e.rd=b,e.Tc&&e.Tc.$d.push(b))}function Ob(a,b,c){var d=I(a,{parent:!0}).node;a=eb(a);if(!a||"."===a||".."===a)throw new F(22);var e=Ib(d,a);if(e)throw new F(e);if(!d.Oc.kd)throw new F(1);return d.Oc.kd(d,a,b,c)}function J(a){Ob(a,16895,0)}
function Pb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ob(a,b|8192,c)}function Qb(a,b){if(!hb(a))throw new F(2);var c=I(b,{parent:!0}).node;if(!c)throw new F(2);b=eb(b);var d=Ib(c,b);if(d)throw new F(d);if(!c.Oc.symlink)throw new F(1);c.Oc.symlink(c,b,a)}function Ab(a){a=I(a).node;if(!a)throw new F(2);if(!a.Oc.readlink)throw new F(22);return hb(Bb(a.parent),a.Oc.readlink(a))}
function Rb(a,b,c,d){if(""===a)throw new F(2);if("string"===typeof b){var e=Gb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=cb(a);try{f=I(a,{yd:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new F(17);}else f=Ob(a,c,0),e=!0;if(!f)throw new F(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new F(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Hb(b)||b&512)?21:Eb(f,Hb(b)):2))throw new F(c);if(b&512){c=f;var k;"string"===typeof c?k=I(c,{yd:!0}).node:k=c;if(!k.Oc.Vc)throw new F(1);if(16384===(k.mode&61440))throw new F(21);if(32768!==(k.mode&61440))throw new F(22);if(c=Eb(k,"w"))throw new F(c);k.Oc.Vc(k,{size:0,timestamp:Date.now()})}b&=-641;d=Kb({node:f,path:Bb(f),flags:b,seekable:!0,position:0,Nc:f.Nc,ie:[],error:!1},d);d.Nc.open&&d.Nc.open(d);!h.logReadFiles||b&1||(Sb||(Sb={}),a in Sb||(Sb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{zb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),zb.onOpenFile(a,f))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function Tb(a,b,c){if(null===a.fd)throw new F(9);if(!a.seekable||!a.Nc.$c)throw new F(29);if(0!=c&&1!=c&&2!=c)throw new F(22);a.position=a.Nc.$c(a,b,c);a.ie=[]}
function Ub(){F||(F=function(a,b){this.node=b;this.ce=function(a){this.Qc=a};this.ce(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},F.prototype=Error(),F.prototype.constructor=F,[2].forEach(function(a){qb[a]=new F(a);qb[a].stack="<generic error, no stack>"}))}var Vb;function Wb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Xb(a,b,c){a=gb("/dev",a);var d=Wb(!!b,!!c);Yb||(Yb=64);var e=Yb++<<8|0;kb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,k=0;k<e;k++){try{var n=b()}catch(R){throw new F(5);}if(void 0===n&&0===f)throw new F(11);if(null===n||void 0===n)break;f++;c[d+k]=n}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(x){throw new F(5);}e&&(a.node.timestamp=Date.now());return f}});
Pb(a,d,e)}var Yb,K={},Fb,Lb,Sb,Zb={},L=0;function M(){L+=4;return t[L-4>>2]}function $b(){var a=vb[M()];if(!a)throw new F(9);return a}function ac(){p()}var bc=0,cc=0,N=0,dc=0,ec=null,fc=null,hc=!1;function ic(){for(var a=O.length-1;0<=a;--a)jc(a);O=[];kc=[]}var kc=[];function lc(){if(mc&&nc.gd)for(var a=0;a<kc.length;++a){var b=kc[a];kc.splice(a,1);--a;b.te.apply(this,b.je)}}var mc=0,nc=null,O=[];
function oc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function jc(a){var b=O[a];b.target.removeEventListener(b.bd,b.Vd,b.nd);O.splice(a,1)}function pc(a){function b(b){++mc;nc=a;lc();a.pd(b);lc();--mc}if(a.od)a.Vd=b,a.target.addEventListener(a.bd,b,a.nd),O.push(a),hc||(Fa.push(ic),hc=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].bd==a.bd&&jc(c--)}
var qc={},rc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function sc(a){try{if(!a)return window;"number"===typeof a&&(a=rc[a]||z(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?h.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}
function tc(a){"number"===typeof a&&(a=z(a));return a&&"#canvas"!==a?"undefined"!==typeof uc&&vc[a]?vc[a]:sc(a):"undefined"!==typeof uc&&vc.canvas?vc.canvas:h.canvas}
function wc(a,b,c,d,e,f){bc||(bc=w(164));a={target:sc(a),gd:oc()?!1:!0,bd:f,od:d,pd:function(a){a=a||window.event;var c=bc;A(a.key?a.key:"",y,c+0,32);A(a.code?a.code:"",y,c+32,32);t[c+64>>2]=a.location;t[c+68>>2]=a.ctrlKey;t[c+72>>2]=a.shiftKey;t[c+76>>2]=a.altKey;t[c+80>>2]=a.metaKey;t[c+84>>2]=a.repeat;A(a.locale?a.locale:"",y,c+88,32);A(a.char?a.char:"",y,c+120,32);t[c+152>>2]=a.charCode;t[c+156>>2]=a.keyCode;t[c+160>>2]=a.which;xc(d,e,c,b)&&a.preventDefault()},nd:c};pc(a)}
function yc(a,b,c){D[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();t[a+8>>2]=b.screenX;t[a+12>>2]=b.screenY;t[a+16>>2]=b.clientX;t[a+20>>2]=b.clientY;t[a+24>>2]=b.ctrlKey;t[a+28>>2]=b.shiftKey;t[a+32>>2]=b.altKey;t[a+36>>2]=b.metaKey;ya[a+40>>1]=b.button;ya[a+42>>1]=b.buttons;t[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-ec;t[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-fc;if(h.canvas){var d=h.canvas.getBoundingClientRect();
t[a+60>>2]=b.clientX-d.left;t[a+64>>2]=b.clientY-d.top}else t[a+60>>2]=0,t[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},t[a+52>>2]=b.clientX-d.left,t[a+56>>2]=b.clientY-d.top):(t[a+52>>2]=0,t[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(ec=b.screenX,fc=b.screenY)}
function zc(a,b,c,d,e,f){cc||(cc=w(72));a=sc(a);c={target:a,gd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,bd:f,od:d,pd:function(c){c=c||window.event;yc(cc,c,a);xc(d,e,cc,b)&&c.preventDefault()},nd:c};oc()&&"mousedown"==f&&(c.gd=!1);pc(c)}
function Ac(a,b,c,d){dc||(dc=w(36));a=sc(a);pc({target:a,gd:!1,bd:"resize",od:d,pd:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],k=dc;t[k>>2]=c.detail;t[k+4>>2]=document.body.clientWidth;
t[k+8>>2]=document.body.clientHeight;t[k+12>>2]=window.innerWidth;t[k+16>>2]=window.innerHeight;t[k+20>>2]=window.outerWidth;t[k+24>>2]=window.outerHeight;t[k+28>>2]=e[0];t[k+32>>2]=e[1];xc(d,10,k,b)&&c.preventDefault()}},nd:c})}
function Bc(a,b,c,d,e){function f(c){c=c||window.event;yc(N,c,a);D[N+72>>3]=c.wheelDeltaX||0;D[N+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);D[N+88>>3]=0;t[N+96>>2]=0;xc(d,9,N,b)&&c.preventDefault()}function k(c){c=c||window.event;var e=N;yc(e,c,a);D[e+72>>3]=c.deltaX;D[e+80>>3]=c.deltaY;D[e+88>>3]=c.deltaZ;t[e+96>>2]=c.deltaMode;xc(d,9,e,b)&&c.preventDefault()}N||(N=w(104));pc({target:a,gd:!0,bd:e,od:d,pd:"wheel"==e?k:f,nd:c})}
var Cc=1,Dc=0,Ec=[],P=[],Fc=[],Gc=[],Hc=[],Q=[],S=[],Ic=[],T={},U=null,vc={},Jc=[],Kc=[],Lc={},Mc={},Nc={},Oc=4;function V(a){Dc||(Dc=a)}function Pc(a){for(var b=Cc++,c=a.length;c<b;c++)a[c]=null;return b}var Qc=null,W=[0];
function Rc(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=w(8),e={handle:d,attributes:b,version:b.Pd,cd:a};e.Pc=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.Td=e);T[d]=e;("undefined"===typeof b.Id||b.Id)&&Sc(e);return d}
function Sc(a){a||(a=U);if(!a.Yd){a.Yd=!0;var b=a.cd;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.Hd=b.getExtension("EXT_disjoint_timer_query");b.Hd||(b.Hd=b.getExtension("EXT_disjoint_timer_query_webgl2"));var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}}var uc={},Tc,Uc,Vc=["default","low-power","high-performance"];function Wc(a){U=T[a];h.ke=Y=U&&U.cd;return!a||Y?0:-5}h._emscripten_webgl_make_context_current=Wc;function Xc(a){if(0===a)return 0;a=z(a);if(!E.hasOwnProperty(a))return 0;Xc.Xc&&Yc(Xc.Xc);a=E[a];var b=va(a)+1,c=w(b);c&&A(a,v,c,b);Xc.Xc=c;return Xc.Xc}var Zc=[];
function $c(a,b,c,d){for(var e=0;e<a;e++){var f=Y[c](),k=f&&Pc(d);f?(f.name=k,d[k]=f):V(1282);t[b+4*e>>2]=k}}
function ad(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&V(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=Y.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){V(1282);return}e=Y.getSupportedExtensions();d=null===e?0:2*e.length;break;case 33307:case 33308:if(2>U.version){V(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=Y.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);
return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":t[b+4*a>>2]=e[a];break;case "Float":C[b+4*a>>2]=e[a];break;case "Boolean":v[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=
e.name|0}catch(f){V(1280);r("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);return}switch(c){case "Integer64":aa=[d>>>0,(g=d,1<=+Ja(g)?0<g?(Na(+Ma(g/4294967296),4294967295)|0)>>>0:~~+La((g-+(~~g>>>0))/4294967296)>>>0:0)];t[b>>2]=aa[0];t[b+4>>2]=aa[1];break;case "Integer":t[b>>2]=d;break;case "Float":C[b>>2]=d;break;case "Boolean":v[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else V(1281)}
function bd(a){var b=va(a)+1,c=w(b);A(a,y,c,b);return c}var cd={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},dd={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function ed(a,b,c,d,e){if(b=cd[b]*dd[a]){var f=Oc;c=e+d*(c*b+f-1&-f);switch(a){case 5120:return v.subarray(e,c);case 5121:return y.subarray(e,c);case 5122:return ya.subarray(e>>1,c>>1);case 5124:return t.subarray(e>>2,c>>2);case 5126:return C.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return B.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return za.subarray(e>>1,c>>1);default:V(1280)}}else V(1280)}
function fd(a){switch(a){case 5120:return v;case 5121:return y;case 5122:return ya;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return za;case 5124:return t;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return B;case 5126:return C}}var gd={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};function hd(a){return 0===a%4&&(0!==a%100||0===a%400)}function id(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var jd=[31,29,31,30,31,30,31,31,30,31,30,31],kd=[31,28,31,30,31,30,31,31,30,31,30,31];function ld(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(hd(a.getFullYear())?jd:kd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function md(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=ld(new Date(a.Sc+1900,0,1),a.vd);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=k(n(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var u=t[d+40>>2];d={ge:t[d>>2],fe:t[d+4>>2],td:t[d+8>>2],md:t[d+12>>2],ed:t[d+16>>2],Sc:t[d+20>>2],ud:t[d+24>>2],vd:t[d+28>>2],ue:t[d+32>>2],ee:t[d+36>>2],
he:u?z(u):""};c=z(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var x in u)c=c.replace(new RegExp(x,"g"),u[x]);var X="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
R="January February March April May June July August September October November December".split(" ");u={"%a":function(a){return X[a.ud].substring(0,3)},"%A":function(a){return X[a.ud]},"%b":function(a){return R[a.ed].substring(0,3)},"%B":function(a){return R[a.ed]},"%C":function(a){return f((a.Sc+1900)/100|0,2)},"%d":function(a){return f(a.md,2)},"%e":function(a){return e(a.md,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return f(a.td,
2)},"%I":function(a){a=a.td;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.md+id(hd(a.Sc+1900)?jd:kd,a.ed-1),3)},"%m":function(a){return f(a.ed+1,2)},"%M":function(a){return f(a.fe,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.td&&12>a.td?"AM":"PM"},"%S":function(a){return f(a.ge,2)},"%t":function(){return"\t"},"%u":function(a){return a.ud||7},"%U":function(a){var b=new Date(a.Sc+1900,0,1),c=0===b.getDay()?b:ld(b,7-b.getDay());a=new Date(a.Sc+1900,a.ed,a.md);return 0>
k(c,a)?f(Math.ceil((31-c.getDate()+(id(hd(a.getFullYear())?jd:kd,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.Sc+1900,0,4)),c=n(new Date(a.Sc+1901,0,4)),d=ld(new Date(a.Sc+1900,0,1),a.vd);return 0>k(d,b)?"53":0>=k(c,d)?"01":f(Math.ceil((b.getFullYear()<a.Sc+1900?a.vd+32-b.getDate():a.vd+1-b.getDate())/7),2)},"%w":function(a){return a.ud},"%W":function(a){var b=new Date(a.Sc,0,1),c=1===b.getDay()?b:ld(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Sc+
1900,a.ed,a.md);return 0>k(c,a)?f(Math.ceil((31-c.getDate()+(id(hd(a.getFullYear())?jd:kd,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.Sc+1900).toString().substring(2)},"%Y":function(a){return a.Sc+1900},"%z":function(a){a=a.ee;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.he},"%%":function(){return"%"}};for(x in u)0<=c.indexOf(x)&&(c=c.replace(new RegExp(x,"g"),u[x](d)));x=Xa(c,!1);if(x.length>
b)return 0;v.set(x,a);return x.length-1}Ub();xb=Array(4096);Mb(G,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");kb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Pb("/dev/null",259);jb(1280,mb);jb(1536,nb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){p("random_device")});Xb("random",b);Xb("urandom",b);J("/dev/shm");
J("/dev/shm/tmp")})();J("/proc");J("/proc/self");J("/proc/self/fd");Mb({Tc:function(){var a=pb("/proc/self","fd",16895,73);a.Oc={lookup:function(a,c){var b=vb[+c];if(!b)throw new F(9);a={parent:null,Tc:{Rd:"fake"},Oc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(fa){var fs=require("fs"),sb=require("path");H.de()}
ea?ac=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ac=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?ac=function(){return performance.now()}:ac=Date.now;var Y;Qc=new Float32Array(256);for(var nd=0;256>nd;nd++)W[nd]=Qc.subarray(0,nd+1);for(var od=0;32>od;od++)Zc.push(Array(od));function Xa(a,b){var c=Array(va(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}
var rd=h.asm({},{eb:$a,c:function(a){return w(a)},ab:function(){pa=!0;throw"Pure virtual function called!";},b:function(a){"uncaught_exception"in pd?pd.Xc++:pd.Xc=1;throw a;},kb:function(){return!!pd.Xc},E:function(){},jb:function(){ab(1);return-1},H:function(a,b){L=b;try{var c=$b(),d=M(),e=M(),f=M(),k=M();a=4294967296*d+(e>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-75;Tb(c,a,k);aa=[c.position>>>0,(g=c.position,1<=+Ja(g)?0<g?(Na(+Ma(g/4294967296),4294967295)|0)>>>0:~~+La((g-+(~~g>>>
0))/4294967296)>>>0:0)];t[f>>2]=aa[0];t[f+4>>2]=aa[1];c.zd&&0===a&&0===k&&(c.zd=null);return 0}catch(n){return"undefined"!==typeof K&&n instanceof F||p(n),-n.Qc}},pb:function(a,b){L=b;try{var c=$b(),d=M();a:{var e=M();for(b=a=0;b<e;b++){var f=t[d+(8*b+4)>>2],k=c,n=t[d+8*b>>2],q=f,u=void 0,x=v;if(0>q||0>u)throw new F(22);if(null===k.fd)throw new F(9);if(1===(k.flags&2097155))throw new F(9);if(16384===(k.node.mode&61440))throw new F(21);if(!k.Nc.read)throw new F(22);var X="undefined"!==typeof u;if(!X)u=
k.position;else if(!k.seekable)throw new F(29);var R=k.Nc.read(k,x,n,q,u);X||(k.position+=R);var qa=R;if(0>qa){var Z=-1;break a}a+=qa;if(qa<f)break}Z=a}return Z}catch(Nb){return"undefined"!==typeof K&&Nb instanceof F||p(Nb),-Nb.Qc}},F:function(a,b){L=b;try{var c=$b(),d=M();a:{var e=M();for(b=a=0;b<e;b++){var f=c,k=t[d+8*b>>2],n=t[d+(8*b+4)>>2],q=void 0,u=v;if(0>n||0>q)throw new F(22);if(null===f.fd)throw new F(9);if(0===(f.flags&2097155))throw new F(9);if(16384===(f.node.mode&61440))throw new F(21);
if(!f.Nc.write)throw new F(22);f.flags&1024&&Tb(f,0,2);var x="undefined"!==typeof q;if(!x)q=f.position;else if(!f.seekable)throw new F(29);var X=f.Nc.write(f,u,k,n,q,void 0);x||(f.position+=X);try{if(f.path&&zb.onWriteToFile)zb.onWriteToFile(f.path)}catch(Z){console.log("FS.trackingDelegate['onWriteToFile']('"+f.path+"') threw an exception: "+Z.message)}var R=X;if(0>R){var qa=-1;break a}a+=R}qa=a}return qa}catch(Z){return"undefined"!==typeof K&&Z instanceof F||p(Z),-Z.Qc}},o:function(a,b){L=b;try{var c=
$b();switch(M()){case 0:var d=M();return 0>d?-22:Rb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=M(),c.flags|=d,0;case 12:return d=M(),ya[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return ab(22),-1;default:return-22}}catch(e){return"undefined"!==typeof K&&e instanceof F||p(e),-e.Qc}},sb:function(a,b){L=b;try{var c=z(M());var d=M();if(d&-8)var e=-22;else{var f=I(c,{yd:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Eb(f,
a)?-13:0}return e}catch(k){return"undefined"!==typeof K&&k instanceof F||p(k),-k.Qc}},rb:function(a,b){L=b;try{var c=z(M()),d=M(),e=M();return Rb(c,d,e).fd}catch(f){return"undefined"!==typeof K&&f instanceof F||p(f),-f.Qc}},G:function(a,b){L=b;try{var c=$b(),d=M();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-25;case 21519:if(!c.tty)return-25;var e=M();return t[e>>2]=0;case 21520:return c.tty?-22:-25;case 21531:a=
e=M();if(!c.Nc.Zd)throw new F(25);return c.Nc.Zd(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:p("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof K&&f instanceof F||p(f),-f.Qc}},I:function(a,b){L=b;try{var c=$b();if(null===c.fd)throw new F(9);c.zd&&(c.zd=null);try{c.Nc.close&&c.Nc.close(c)}catch(d){throw d;}finally{vb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof K&&d instanceof F||p(d),-d.Qc}},ib:function(a,b){L=b;try{var c=M(),d=M();if(-1==
c||0==d)var e=-22;else{var f=Zb[c];if(f&&d===f.ne){var k=vb[f.fd],n=f.flags,q=new Uint8Array(y.subarray(c,c+d));k&&k.Nc.sd&&k.Nc.sd(k,q,0,d,n);Zb[c]=null;f.Ud&&Yc(f.oe)}e=0}return e}catch(u){return"undefined"!==typeof K&&u instanceof F||p(u),-u.Qc}},j:function(){},a:function(){h.abort()},lb:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ea||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=ac();else return ab(22),-1;t[b>>2]=a/1E3|
0;t[b+4>>2]=a%1E3*1E6|0;return 0},g:function(a,b,c){b=sa(b);for(var d=[],e=0;e<b.length;e++){var f=b[e];"d"==f||"f"==f?(c=c+8-1&-8,d.push(D[c>>3]),c+=8):"i"==f&&(c=c+4-1&-4,d.push(t[c>>2]),c+=4)}return Ya[a].apply(null,d)},C:function(a,b,c){a=tc(a);if(!a)return-4;t[b>>2]=a.width;t[c>>2]=a.height},ac:function(){return window.devicePixelRatio||1},p:function(a,b,c){a=a?sc(a):h.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),D[b>>3]=a.right-a.left,D[c>>3]=a.bottom-a.top):(D[b>>
3]=a.clientWidth,D[c>>3]=a.clientHeight);return 0},db:function(a,b,c){y.set(y.subarray(b,b+c),a)},q:function(a,b,c){a=tc(a);if(!a)return-4;a.width=b;a.height=c;return 0},qb:function(a,b,c,d){wc(a,b,c,d,2,"keydown");return 0},nb:function(a,b,c,d){wc(a,b,c,d,3,"keyup");return 0},$b:function(a,b,c,d){zc(a,b,c,d,5,"mousedown");return 0},Ib:function(a,b,c,d){zc(a,b,c,d,8,"mousemove");return 0},Sb:function(a,b,c,d){zc(a,b,c,d,6,"mouseup");return 0},U:function(a,b,c,d){Ac(a,b,c,d);return 0},yb:function(a,
b,c,d){a=sc(a);return"undefined"!==typeof a.onwheel?(Bc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Bc(a,b,c,d,"mousewheel"),0):-1},bb:function(){return U&&U.cd&&U.attributes.Kd?0:-3},na:function(a,b){var c={};b>>=2;c.alpha=!!t[b];c.depth=!!t[b+1];c.stencil=!!t[b+2];c.antialias=!!t[b+3];c.premultipliedAlpha=!!t[b+4];c.preserveDrawingBuffer=!!t[b+5];c.powerPreference=Vc[t[b+6]];c.failIfMajorPerformanceCaveat=!!t[b+7];c.Pd=t[b+8];c.pe=t[b+9];c.Id=t[b+10];c.Kd=t[b+11];c.qe=t[b+12];c.se=
t[b+13];a=tc(a);!a||c.Kd?c=0:c=(a=1<c.Pd?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))?Rc(a,c):0;return c},$a:function(a){U==a&&(U=0);U===T[a]&&(U=null);if("object"===typeof qc)for(var b=T[a].cd.canvas,c=0;c<O.length;++c)O[c].target!=b||jc(c--);T[a]&&T[a].cd.canvas&&(T[a].cd.canvas.Td=void 0);Yc(T[a]);T[a]=null},Qa:function(a){a>>=2;for(var b=0;14>b;++b)t[a+b]=0;t[a]=t[a+1]=t[a+3]=t[a+4]=t[a+8]=t[a+10]=1},ca:Wc,B:function(a){qd(a)},D:Ja,r:Ja,ob:Ma,k:Xc,u:function(a){Y.activeTexture(a)},
Aa:function(a,b){Y.attachShader(P[a],S[b])},z:function(a,b){35051==a?Y.xd=b:35052==a&&(Y.Zc=b);Y.bindBuffer(a,Ec[b])},h:function(a,b,c){Y.bindBufferBase(a,b,Ec[c])},y:function(a,b,c,d,e){Y.bindBufferRange(a,b,Ec[c],d,e)},v:function(a,b){Y.bindFramebuffer(a,Fc[b])},La:function(a,b){Y.bindRenderbuffer(a,Gc[b])},t:function(a,b){Y.bindTexture(a,Hc[b])},T:function(a,b){Y.bindTransformFeedback(a,Kc[b])},Ab:function(a){Y.bindVertexArray(Ic[a])},Wa:function(a,b){Y.blendEquationSeparate(a,b)},Va:function(a,
b){Y.blendFunc(a,b)},R:function(a,b,c,d,e,f,k,n,q,u){Y.blitFramebuffer(a,b,c,d,e,f,k,n,q,u)},Oa:function(a,b,c,d){U.Pc?c?Y.bufferData(a,y,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?y.subarray(c,c+b):b,d)},Na:function(a,b,c,d){U.Pc?Y.bufferSubData(a,b,y,d,c):Y.bufferSubData(a,b,y.subarray(d,d+c))},N:function(a){return Y.checkFramebufferStatus(a)},Q:function(a){Y.clear(a)},Zb:function(a,b,c,d){Y.clearBufferfi(a,b,c,d)},_b:function(a,b,c){Y.clearBufferfv(a,b,C,c>>2)},M:function(a,b,c){Y.clearBufferiv(a,
b,t,c>>2)},L:function(a,b,c){Y.clearBufferuiv(a,b,B,c>>2)},A:function(a,b,c,d){Y.clearColor(a,b,c,d)},Ua:function(a){Y.clearDepth(a)},X:function(a){Y.compileShader(S[a])},J:function(a,b,c,d,e,f,k,n,q){U.Pc?Y.Zc?Y.compressedTexSubImage2D(a,b,c,d,e,f,k,n,q):Y.compressedTexSubImage2D(a,b,c,d,e,f,k,y,q,n):Y.compressedTexSubImage2D(a,b,c,d,e,f,k,q?y.subarray(q,q+n):null)},Fb:function(a,b,c,d,e,f,k,n,q,u,x){U.Pc?Y.Zc?Y.compressedTexSubImage3D(a,b,c,d,e,f,k,n,q,u,x):Y.compressedTexSubImage3D(a,b,c,d,e,f,
k,n,q,y,x,u):Y.compressedTexSubImage3D(a,b,c,d,e,f,k,n,q,x?y.subarray(x,x+u):null)},Ra:function(a,b,c,d,e){Y.copyBufferSubData(a,b,c,d,e)},Vb:function(a,b,c,d,e,f,k,n){Y.copyTexSubImage2D(a,b,c,d,e,f,k,n)},Ub:function(a,b,c,d,e,f,k,n,q){Y.copyTexSubImage3D(a,b,c,d,e,f,k,n,q)},Ea:function(){var a=Pc(P),b=Y.createProgram();b.name=a;P[a]=b;return a},_:function(a){var b=Pc(S);S[b]=Y.createShader(a);return b},Sa:function(a,b){for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Ec[d];e&&(Y.deleteBuffer(e),e.name=
0,Ec[d]=null,d==Tc&&(Tc=0),d==Uc&&(Uc=0),d==Y.xd&&(Y.xd=0),d==Y.Zc&&(Y.Zc=0))}},Da:function(a){if(a){var b=P[a];b?(Y.deleteProgram(b),b.name=0,P[a]=null,Lc[a]=null):V(1281)}},Z:function(a){if(a){var b=S[a];b?(Y.deleteShader(b),S[a]=null):V(1281)}},Rb:function(a,b){for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Hc[d];e&&(Y.deleteTexture(e),e.name=0,Hc[d]=null)}},xb:function(a,b){for(var c=0;c<a;c++){var d=t[b+4*c>>2];Y.deleteVertexArray(Ic[d]);Ic[d]=null}},l:function(a){Y.disable(a)},Eb:function(a,b,c){Y.drawArrays(a,
b,c)},Cb:function(a,b,c,d){Y.drawArraysInstanced(a,b,c,d)},Yb:function(a,b){for(var c=Zc[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];Y.drawBuffers(c)},Db:function(a,b,c,d){Y.drawElements(a,b,c,d)},Bb:function(a,b,c,d,e){Y.drawElementsInstanced(a,b,c,d,e)},m:function(a){Y.enable(a)},wb:function(a){Y.enableVertexAttribArray(a)},Ha:function(a,b,c,d){Y.framebufferRenderbuffer(a,b,c,Gc[d])},Ga:function(a,b,c,d,e){Y.framebufferTexture2D(a,b,c,Hc[d],e)},Fa:function(a,b,c,d,e){Y.framebufferTextureLayer(a,b,Hc[c],d,e)},
Ta:function(a,b){$c(a,b,"createBuffer",Ec)},Ia:function(a,b){$c(a,b,"createFramebuffer",Fc)},$:function(a,b){$c(a,b,"createQuery",Jc)},Ma:function(a,b){$c(a,b,"createRenderbuffer",Gc)},Tb:function(a,b){$c(a,b,"createTexture",Hc)},V:function(a,b){$c(a,b,"createTransformFeedback",Kc)},zb:function(a,b){$c(a,b,"createVertexArray",Ic)},Qb:function(a){Y.generateMipmap(a)},Pa:function(a,b,c){c?t[c>>2]=Y.getBufferParameter(a,b):V(1281)},_a:function(){var a=Y.getError()||Dc;Dc=0;return a},Ya:function(a,b){ad(a,
b,"Float")},n:function(a,b){ad(a,b,"Integer")},Ca:function(a,b,c,d){a=Y.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");0<b&&d?(b=A(a,y,d,b),c&&(t[c>>2]=b)):c&&(t[c>>2]=0)},x:function(a,b,c){if(c)if(a>=Cc)V(1281);else{var d=Lc[a];if(d)if(35716==b)a=Y.getProgramInfoLog(P[a]),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b)t[c>>2]=d.Ad;else if(35722==b){if(-1==d.hd){a=P[a];var e=Y.getProgramParameter(a,35721);for(b=d.hd=0;b<e;++b)d.hd=Math.max(d.hd,Y.getActiveAttrib(a,b).name.length+
1)}t[c>>2]=d.hd}else if(35381==b){if(-1==d.jd)for(a=P[a],e=Y.getProgramParameter(a,35382),b=d.jd=0;b<e;++b)d.jd=Math.max(d.jd,Y.getActiveUniformBlockName(a,b).length+1);t[c>>2]=d.jd}else t[c>>2]=Y.getProgramParameter(P[a],b);else V(1282)}else V(1281)},W:function(a,b,c,d){a=Y.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");0<b&&d?(b=A(a,y,d,b),c&&(t[c>>2]=b)):c&&(t[c>>2]=0)},w:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1):35720==b?
(a=Y.getShaderSource(S[a]),t[c>>2]=null===a||0==a.length?0:a.length+1):t[c>>2]=Y.getShaderParameter(S[a],b):V(1281)},i:function(a){if(Mc[a])return Mc[a];switch(a){case 7939:var b=Y.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=bd(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||V(1280);b=bd(b);break;case 7938:b=Y.getParameter(Y.VERSION);b=2<=U.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=bd(b);break;case 35724:b=
Y.getParameter(Y.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=bd(b);break;default:return V(1280),0}return Mc[a]=b},Za:function(a,b){if(2>U.version)return V(1282),0;var c=Nc[a];if(c)return 0>b||b>=c.length?(V(1281),0):c[b];switch(a){case 7939:c=Y.getSupportedExtensions();for(var d=[],e=0;e<c.length;++e)d.push(bd(c[e])),d.push(bd("GL_"+c[e]));c=Nc[a]=d;return 0>b||b>=c.length?(V(1281),
0):c[b];default:return V(1280),0}},xa:function(a,b){b=z(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Lc[a]&&Lc[a].Sd[b])&&0<=c&&c<a[0]?a[1]+c:-1},P:function(a,b,c){for(var d=Zc[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];Y.invalidateFramebuffer(a,d)},O:function(a,b,c,d,e,f,k){for(var n=Zc[b],q=0;q<b;q++)n[q]=t[c+4*q>>2];Y.invalidateSubFramebuffer(a,n,d,e,f,k)},ya:function(a){Y.linkProgram(P[a]);var b=P[a];a=Lc[a]={Sd:{},Ad:0,hd:-1,jd:-1};
for(var c=a.Sd,d=Y.getProgramParameter(b,35718),e=0;e<d;++e){var f=Y.getActiveUniform(b,e),k=f.name;a.Ad=Math.max(a.Ad,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var n=Y.getUniformLocation(b,k);if(n){var q=Pc(Q);c[k]=[f.size,q];Q[q]=n;for(var u=1;u<f.size;++u)n=Y.getUniformLocation(b,k+"["+u+"]"),q=Pc(Q),Q[q]=n}}},f:function(a,b){3317==a&&(Oc=b);Y.pixelStorei(a,b)},Xb:function(a){Y.readBuffer(a)},Wb:function(a,b,c,d,e,f,k){U.Pc?Y.xd?Y.readPixels(a,b,c,d,e,f,k):Y.readPixels(a,
b,c,d,e,f,fd(f),k>>(gd[f]|0)):(k=ed(f,e,c,d,k))?Y.readPixels(a,b,c,d,e,f,k):V(1280)},Ka:function(a,b,c,d){Y.renderbufferStorage(a,b,c,d)},Ja:function(a,b,c,d,e){Y.renderbufferStorageMultisample(a,b,c,d,e)},Xa:function(a,b,c,d){Y.scissor(a,b,c,d)},Y:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?t[d+4*f>>2]:-1;e+=z(t[c+4*f>>2],0>k?void 0:k)}Y.shaderSource(S[a],e)},Jb:function(a,b,c,d,e,f,k,n,q){U.Pc?Y.Zc?Y.texImage2D(a,b,c,d,e,f,k,n,q):0!=q?Y.texImage2D(a,b,c,d,e,f,k,n,fd(n),q>>(gd[n]|0)):Y.texImage2D(a,
b,c,d,e,f,k,n,null):Y.texImage2D(a,b,c,d,e,f,k,n,q?ed(n,k,d,e,q):null)},Hb:function(a,b,c,d,e,f,k,n,q,u){Y.Zc?Y.texImage3D(a,b,c,d,e,f,k,n,q,u):0!=u?Y.texImage3D(a,b,c,d,e,f,k,n,q,fd(q),u>>(gd[q]|0)):Y.texImage3D(a,b,c,d,e,f,k,n,q,null)},Ob:function(a,b,c){Y.texParameterf(a,b,c)},Mb:function(a,b,c){Y.texParameterf(a,b,C[c>>2])},Pb:function(a,b,c){Y.texParameteri(a,b,c)},Nb:function(a,b,c){Y.texParameteri(a,b,t[c>>2])},Lb:function(a,b,c,d,e){Y.texStorage2D(a,b,c,d,e)},Kb:function(a,b,c,d,e,f){Y.texStorage3D(a,
b,c,d,e,f)},K:function(a,b,c,d,e,f,k,n,q){if(U.Pc)Y.Zc?Y.texSubImage2D(a,b,c,d,e,f,k,n,q):0!=q?Y.texSubImage2D(a,b,c,d,e,f,k,n,fd(n),q>>(gd[n]|0)):Y.texSubImage2D(a,b,c,d,e,f,k,n,null);else{var u=null;q&&(u=ed(n,k,e,f,q));Y.texSubImage2D(a,b,c,d,e,f,k,n,u)}},Gb:function(a,b,c,d,e,f,k,n,q,u,x){Y.Zc?Y.texSubImage3D(a,b,c,d,e,f,k,n,q,u,x):0!=x?Y.texSubImage3D(a,b,c,d,e,f,k,n,q,u,fd(u),x>>(gd[u]|0)):Y.texSubImage3D(a,b,c,d,e,f,k,n,q,u,null)},za:function(a,b,c,d){a=P[a];for(var e=[],f=0;f<b;f++)e.push(z(t[c+
4*f>>2]));Y.transformFeedbackVaryings(a,e,d)},wa:function(a,b,c){if(U.Pc)Y.uniform1fv(Q[a],C,c>>2,b);else{if(256>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);Y.uniform1fv(Q[a],d)}},sa:function(a,b,c){U.Pc?Y.uniform1iv(Q[a],t,c>>2,b):Y.uniform1iv(Q[a],t.subarray(c>>2,c+4*b>>2))},oa:function(a,b,c){U.Pc?Y.uniform1uiv(Q[a],B,c>>2,b):Y.uniform1uiv(Q[a],B.subarray(c>>2,c+4*b>>2))},va:function(a,b,c){if(U.Pc)Y.uniform2fv(Q[a],C,c>>2,2*b);else{if(256>=2*b)for(var d=W[2*
b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);Y.uniform2fv(Q[a],d)}},ra:function(a,b,c){U.Pc?Y.uniform2iv(Q[a],t,c>>2,2*b):Y.uniform2iv(Q[a],t.subarray(c>>2,c+8*b>>2))},ma:function(a,b,c){U.Pc?Y.uniform2uiv(Q[a],B,c>>2,2*b):Y.uniform2uiv(Q[a],B.subarray(c>>2,c+8*b>>2))},ua:function(a,b,c){if(U.Pc)Y.uniform3fv(Q[a],C,c>>2,3*b);else{if(256>=3*b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>
2,c+12*b>>2);Y.uniform3fv(Q[a],d)}},qa:function(a,b,c){U.Pc?Y.uniform3iv(Q[a],t,c>>2,3*b):Y.uniform3iv(Q[a],t.subarray(c>>2,c+12*b>>2))},la:function(a,b,c){U.Pc?Y.uniform3uiv(Q[a],B,c>>2,3*b):Y.uniform3uiv(Q[a],B.subarray(c>>2,c+12*b>>2))},ta:function(a,b,c){if(U.Pc)Y.uniform4fv(Q[a],C,c>>2,4*b);else{if(256>=4*b)for(var d=W[4*b-1],e=0;e<4*b;e+=4)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2],d[e+3]=C[c+(4*e+12)>>2];else d=C.subarray(c>>2,c+16*b>>2);Y.uniform4fv(Q[a],d)}},pa:function(a,
b,c){U.Pc?Y.uniform4iv(Q[a],t,c>>2,4*b):Y.uniform4iv(Q[a],t.subarray(c>>2,c+16*b>>2))},ka:function(a,b,c){U.Pc?Y.uniform4uiv(Q[a],B,c>>2,4*b):Y.uniform4uiv(Q[a],B.subarray(c>>2,c+16*b>>2))},ja:function(a,b,c,d){if(U.Pc)Y.uniformMatrix2fv(Q[a],!!c,C,d>>2,4*b);else{if(256>=4*b)for(var e=W[4*b-1],f=0;f<4*b;f+=4)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2];else e=C.subarray(d>>2,d+16*b>>2);Y.uniformMatrix2fv(Q[a],!!c,e)}},ga:function(a,b,c,d){U.Pc?Y.uniformMatrix2x3fv(Q[a],
!!c,C,d>>2,6*b):Y.uniformMatrix2x3fv(Q[a],!!c,C.subarray(d>>2,d+24*b>>2))},ea:function(a,b,c,d){U.Pc?Y.uniformMatrix2x4fv(Q[a],!!c,C,d>>2,8*b):Y.uniformMatrix2x4fv(Q[a],!!c,C.subarray(d>>2,d+32*b>>2))},ia:function(a,b,c,d){if(U.Pc)Y.uniformMatrix3fv(Q[a],!!c,C,d>>2,9*b);else{if(256>=9*b)for(var e=W[9*b-1],f=0;f<9*b;f+=9)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>
2],e[f+8]=C[d+(4*f+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);Y.uniformMatrix3fv(Q[a],!!c,e)}},fa:function(a,b,c,d){U.Pc?Y.uniformMatrix3x2fv(Q[a],!!c,C,d>>2,6*b):Y.uniformMatrix3x2fv(Q[a],!!c,C.subarray(d>>2,d+24*b>>2))},ba:function(a,b,c,d){U.Pc?Y.uniformMatrix3x4fv(Q[a],!!c,C,d>>2,12*b):Y.uniformMatrix3x4fv(Q[a],!!c,C.subarray(d>>2,d+48*b>>2))},ha:function(a,b,c,d){if(U.Pc)Y.uniformMatrix4fv(Q[a],!!c,C,d>>2,16*b);else{if(256>=16*b)for(var e=W[16*b-1],f=0;f<16*b;f+=16)e[f]=C[d+4*f>>2],e[f+1]=C[d+
(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2],e[f+9]=C[d+(4*f+36)>>2],e[f+10]=C[d+(4*f+40)>>2],e[f+11]=C[d+(4*f+44)>>2],e[f+12]=C[d+(4*f+48)>>2],e[f+13]=C[d+(4*f+52)>>2],e[f+14]=C[d+(4*f+56)>>2],e[f+15]=C[d+(4*f+60)>>2];else e=C.subarray(d>>2,d+64*b>>2);Y.uniformMatrix4fv(Q[a],!!c,e)}},da:function(a,b,c,d){U.Pc?Y.uniformMatrix4x2fv(Q[a],!!c,C,d>>2,8*b):Y.uniformMatrix4x2fv(Q[a],
!!c,C.subarray(d>>2,d+32*b>>2))},aa:function(a,b,c,d){U.Pc?Y.uniformMatrix4x3fv(Q[a],!!c,C,d>>2,12*b):Y.uniformMatrix4x3fv(Q[a],!!c,C.subarray(d>>2,d+48*b>>2))},Ba:function(a){Y.useProgram(P[a])},tb:function(a,b){Y.vertexAttribDivisor(a,b)},vb:function(a,b,c,d,e){Y.vertexAttribIPointer(a,b,c,d,e)},ub:function(a,b,c,d,e,f){Y.vertexAttribPointer(a,b,c,!!d,e,f)},S:function(a,b,c,d){Y.viewport(a,b,c,d)},gb:function(){return 0},fb:function(){return 0},e:function(a){a=+a;return 0<=a?+Ma(a+.5):+La(a-.5)},
d:function(a){a|=0;var b=v.length|0;var c=t[na>>2]|0;var d=c+a|0;if(0<(a|0)&(d|0)<(c|0)|0>(d|0))return p("OOM"),0,ab(12),-1;if(a=(d|0)>(b|0))p("OOM"),a=!0;if(a)return ab(12),-1;t[na>>2]=d|0;return c|0},cb:function(){},mb:Ka,s:Ka,hb:function(a,b,c,d){return md(a,b,c,d)}},buffer);h.asm=rd;var Za=h.___wasm_call_ctors=function(){return h.asm.bc.apply(null,arguments)};h._main=function(){return h.asm.cc.apply(null,arguments)};
var Yc=h._free=function(){return h.asm.dc.apply(null,arguments)},w=h._malloc=function(){return h.asm.ec.apply(null,arguments)};h.___errno_location=function(){return h.asm.fc.apply(null,arguments)};var pd=h.__ZSt18uncaught_exceptionv=function(){return h.asm.gc.apply(null,arguments)},xa=h.stackAlloc=function(){return h.asm.hc.apply(null,arguments)};h.dynCall_vi=function(){return h.asm.ic.apply(null,arguments)};h.dynCall_ii=function(){return h.asm.jc.apply(null,arguments)};
h.dynCall_vii=function(){return h.asm.kc.apply(null,arguments)};var xc=h.dynCall_iiii=function(){return h.asm.lc.apply(null,arguments)};h.dynCall_v=function(){return h.asm.mc.apply(null,arguments)};h.dynCall_viii=function(){return h.asm.nc.apply(null,arguments)};h.dynCall_viiii=function(){return h.asm.oc.apply(null,arguments)};h.dynCall_viiiii=function(){return h.asm.pc.apply(null,arguments)};h.dynCall_iii=function(){return h.asm.qc.apply(null,arguments)};
h.dynCall_viifi=function(){return h.asm.rc.apply(null,arguments)};h.dynCall_viiiiii=function(){return h.asm.sc.apply(null,arguments)};h.dynCall_vf=function(){return h.asm.tc.apply(null,arguments)};h.dynCall_viiiiiiii=function(){return h.asm.uc.apply(null,arguments)};h.dynCall_viiiiiii=function(){return h.asm.vc.apply(null,arguments)};h.dynCall_viif=function(){return h.asm.wc.apply(null,arguments)};h.dynCall_vif=function(){return h.asm.xc.apply(null,arguments)};
h.dynCall_viiiiiiiii=function(){return h.asm.yc.apply(null,arguments)};h.dynCall_fii=function(){return h.asm.zc.apply(null,arguments)};h.dynCall_viijii=function(){return h.asm.Ac.apply(null,arguments)};h.dynCall_jiji=function(){return h.asm.Bc.apply(null,arguments)};h.dynCall_iidiiii=function(){return h.asm.Cc.apply(null,arguments)};h.dynCall_iiiiii=function(){return h.asm.Dc.apply(null,arguments)};h.dynCall_iiiiiii=function(){return h.asm.Ec.apply(null,arguments)};
h.dynCall_iiiiij=function(){return h.asm.Fc.apply(null,arguments)};h.dynCall_iiiiid=function(){return h.asm.Gc.apply(null,arguments)};h.dynCall_iiiiijj=function(){return h.asm.Hc.apply(null,arguments)};h.dynCall_iiiiiiiii=function(){return h.asm.Ic.apply(null,arguments)};h.dynCall_iiiiiiii=function(){return h.asm.Jc.apply(null,arguments)};h.dynCall_iiiiiijj=function(){return h.asm.Kc.apply(null,arguments)};h.dynCall_iiiii=function(){return h.asm.Lc.apply(null,arguments)};h.asm=rd;
function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ka.prototype=Error();ka.prototype.constructor=ka;Qa=function sd(){h.calledRun||td();h.calledRun||(Qa=sd)};
h.callMain=function(a){a=a||[];var b=a.length+1,c=xa(4*(b+1));t[c>>2]=wa(h.thisProgram);for(var d=1;d<b;d++)t[(c>>2)+d]=wa(a[d-1]);t[(c>>2)+b]=0;try{var e=h._main(b,c,0);qd(e,!0)}catch(f){f instanceof ka||("SimulateInfiniteLoop"==f?h.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),r("exception thrown: "+a),h.quit(1,f)))}finally{}};
function td(a){function b(){if(!h.calledRun&&(h.calledRun=!0,!pa)){Ha=!0;h.noFSInit||Vb||(Vb=!0,Ub(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Xb("stdin",h.stdin):Qb("/dev/tty","/dev/stdin"),h.stdout?Xb("stdout",null,h.stdout):Qb("/dev/tty","/dev/stdout"),h.stderr?Xb("stderr",null,h.stderr):Qb("/dev/tty1","/dev/stderr"),Rb("/dev/stdin","r"),Rb("/dev/stdout","w"),Rb("/dev/stderr","w"));Ba(Da);yb=!1;Ba(Ea);if(h.onRuntimeInitialized)h.onRuntimeInitialized();h._main&&ud&&h.callMain(a);
if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ga.unshift(b)}Ba(Ga)}}a=a||h.arguments;if(!(0<Oa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ia();Ba(Ca);0<Oa||h.calledRun||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=td;
function qd(a,b){if(!b||!h.noExitRuntime||0!==a){if(!h.noExitRuntime&&(pa=!0,h.onExit))h.onExit(a);h.quit(a,new ka(a))}}function p(a){if(h.onAbort)h.onAbort(a);void 0!==a?(la(a),r(a),a='"'+a+'"'):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}h.abort=p;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ud=!0;h.noInitialRun&&(ud=!1);h.noExitRuntime=!0;td();
