
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in g)g.hasOwnProperty(k)&&(aa[k]=g[k]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,m=!1,fa=!1,ha=!1;ea="object"===typeof window;m="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!m;var n="",ia,ja,ka,la;
if(fa)n=m?require("path").dirname(n)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
q),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||m)m?n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),t=g.printErr||console.warn.bind(console);for(k in aa)aa.hasOwnProperty(k)&&(g[k]=aa[k]);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var oa;g.wasmBinary&&(oa=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&t("no native wasm support detected");var pa,qa=new WebAssembly.Table({initial:523,maximum:523,element:"anyfunc"}),ra=!1;
function assert(a,b){a||q("Assertion failed: "+b)}function sa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=y(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)z[a>>2]=0;for(b=d+c;a<b;)A[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?ua(B,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var p=a.charCodeAt(++f);h=65536+((h&1023)<<10)|p&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function wa(a){var b=va(a)+1,c=xa(b);D(a,A,c,b);return c}var ya,A,B,za,Aa,z,Ba,E,F,Ca=g.INITIAL_MEMORY||16777216;g.wasmMemory?pa=g.wasmMemory:pa=new WebAssembly.Memory({initial:Ca/65536,maximum:Ca/65536});pa&&(ya=pa.buffer);Ca=ya.byteLength;var H=ya;ya=H;g.HEAP8=A=new Int8Array(H);g.HEAP16=za=new Int16Array(H);
g.HEAP32=z=new Int32Array(H);g.HEAPU8=B=new Uint8Array(H);g.HEAPU16=Aa=new Uint16Array(H);g.HEAPU32=Ba=new Uint32Array(H);g.HEAPF32=E=new Float32Array(H);g.HEAPF64=F=new Float64Array(H);z[82752]=5574048;function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Tc;"number"===typeof c?void 0===b.xc?g.dynCall_v(c):g.dynCall_vi(c,b.xc):c(void 0===b.xc?null:b.xc)}}}var Ea=[],Fa=[],Ga=[],Ha=[],Ia=[];function Ja(){var a=g.preRun.shift();Ea.unshift(a)}
var Ka=Math.abs,La=Math.ceil,Ma=Math.floor,Na=Math.min,Oa=0,Pa=null,Qa=null;g.preloadedImages={};g.preloadedAudios={};function q(a){if(g.onAbort)g.onAbort(a);na(a);t(a);ra=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ra(a){var b=Sa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ta(){return Ra("data:application/octet-stream;base64,")}var Sa="magnum-imgui.wasm";
if(!Ta()){var Ua=Sa;Sa=g.locateFile?g.locateFile(Ua,n):n+Ua}function Va(){try{if(oa)return new Uint8Array(oa);if(ja)return ja(Sa);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function Wa(){return oa||!ea&&!m||"function"!==typeof fetch||Ra("file://")?new Promise(function(a){a(Va())}):fetch(Sa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Sa+"'";return a.arrayBuffer()}).catch(function(){return Va()})}
var Xa,Ya,$a={152171:function(){var a=g.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?sa(Za(a.id)):0},152784:function(a){a:for(var b="";;){var c=B[a++>>0];if(!c)break a;b+=String.fromCharCode(c)}document.getElementById("canvas").style.cursor=b},152854:function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?g.dynCall_ii.apply(null,[a].concat(e)):g.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},281616:function(a){a=
C(a);return"undefined"!==typeof process&&a in process.env?sa(Za(process.env[a])):0}};Fa.push({Tc:function(){ab()}});function bb(){return 0<bb.nc}function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function db(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var hb=[];function ib(a,b){hb[a]={input:[],output:[],hc:b};jb(a,kb)}
var kb={open:function(a){var b=hb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.hc.flush(a.tty)},flush:function(a){a.tty.hc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.hc.Jc)throw new I(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.hc.Jc(a.tty)}catch(p){throw new I(29);}if(void 0===h&&0===e)throw new I(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.hc.Bc)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.hc.Bc(a.tty,b[c+e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},lb={Jc:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.nc?Buffer.nc(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},Bc:function(a,b){null===b||10===b?(na(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(ua(a.output,0)),a.output=[])}},mb={Bc:function(a,b){null===b||10===b?(t(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(t(ua(a.output,0)),a.output=[])}},K={Zb:null,bc:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);K.Zb||(K.Zb={dir:{node:{cc:K.Wb.cc,$b:K.Wb.$b,lookup:K.Wb.lookup,qc:K.Wb.qc,rename:K.Wb.rename,unlink:K.Wb.unlink,rmdir:K.Wb.rmdir,readdir:K.Wb.readdir,symlink:K.Wb.symlink},stream:{ec:K.Vb.ec}},file:{node:{cc:K.Wb.cc,$b:K.Wb.$b},stream:{ec:K.Vb.ec,read:K.Vb.read,write:K.Vb.write,Dc:K.Vb.Dc,Lc:K.Vb.Lc,sc:K.Vb.sc}},link:{node:{cc:K.Wb.cc,$b:K.Wb.$b,readlink:K.Wb.readlink},stream:{}},Ec:{node:{cc:K.Wb.cc,
$b:K.Wb.$b},stream:nb}});c=ob(a,b,c,d);16384===(c.mode&61440)?(c.Wb=K.Zb.dir.node,c.Vb=K.Zb.dir.stream,c.Ub={}):32768===(c.mode&61440)?(c.Wb=K.Zb.file.node,c.Vb=K.Zb.file.stream,c.Xb=0,c.Ub=null):40960===(c.mode&61440)?(c.Wb=K.Zb.link.node,c.Vb=K.Zb.link.stream):8192===(c.mode&61440)&&(c.Wb=K.Zb.Ec.node,c.Vb=K.Zb.Ec.stream);c.timestamp=Date.now();a&&(a.Ub[b]=c);return c},kd:function(a){if(a.Ub&&a.Ub.subarray){for(var b=[],c=0;c<a.Xb;++c)b.push(a.Ub[c]);return b}return a.Ub},ld:function(a){return a.Ub?
a.Ub.subarray?a.Ub.subarray(0,a.Xb):new Uint8Array(a.Ub):new Uint8Array(0)},Gc:function(a,b){var c=a.Ub?a.Ub.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ub,a.Ub=new Uint8Array(b),0<a.Xb&&a.Ub.set(c.subarray(0,a.Xb),0))},$c:function(a,b){if(a.Xb!=b)if(0==b)a.Ub=null,a.Xb=0;else{if(!a.Ub||a.Ub.subarray){var c=a.Ub;a.Ub=new Uint8Array(b);c&&a.Ub.set(c.subarray(0,Math.min(b,a.Xb)))}else if(a.Ub||(a.Ub=[]),a.Ub.length>b)a.Ub.length=b;else for(;a.Ub.length<b;)a.Ub.push(0);
a.Xb=b}},Wb:{cc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Xb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Qc=4096;b.blocks=Math.ceil(b.size/b.Qc);return b},$b:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&K.$c(a,b.size)},lookup:function(){throw pb[44];},qc:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=qb(b,c)}catch(f){}if(d)for(var e in d.Ub)throw new I(55);}delete a.parent.Ub[a.name];a.name=c;b.Ub[c]=a;a.parent=b},unlink:function(a,b){delete a.Ub[b]},rmdir:function(a,b){var c=qb(a,b),d;for(d in c.Ub)throw new I(55);delete a.Ub[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Ub)a.Ub.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Vb:{read:function(a,b,c,d,e){var f=a.node.Ub;if(e>=a.node.Xb)return 0;a=Math.min(a.node.Xb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ub||a.Ub.subarray)){if(f)return a.Ub=b.subarray(c,c+d),a.Xb=d;if(0===a.Xb&&0===e)return a.Ub=
b.slice(c,c+d),a.Xb=d;if(e+d<=a.Xb)return a.Ub.set(b.subarray(c,c+d),e),d}K.Gc(a,e+d);if(a.Ub.subarray&&b.subarray)a.Ub.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ub[e+f]=b[c+f];a.Xb=Math.max(a.Xb,e+d);return d},ec:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Xb);if(0>b)throw new I(28);return b},Dc:function(a,b,c){K.Gc(a.node,b+c);a.node.Xb=Math.max(a.node.Xb,b+c)},Lc:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.Ub;
if(f&2||a.buffer!==ya){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=y(c);if(!c)throw new I(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{sd:c,Pc:d}},sc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;K.Vb.write(a,b,0,d,c,!1);return 0}}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,xb={},I=null,pb={};
function L(a,b){a=gb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ic:!0,Cc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Cc)throw new I(32);a=cb(a.split("/").filter(function(h){return!!h}),!1);var e=rb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=qb(e,a[d]);c=db(c+"/"+a[d]);e.rc&&(!f||f&&b.Ic)&&(e=e.rc.root);if(!f||b.yc)for(f=0;40960===(e.mode&61440);)if(e=yb(c),c=gb(eb(c),e),e=L(c,{Cc:b.Cc}).node,40<f++)throw new I(32);}return{path:c,node:e}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.bc.Mc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length}function qb(a,b){var c;if(c=(c=Bb(a,"x"))?c:a.Wb.lookup?0:2)throw new I(c,a);for(c=vb[Ab(a.id,b)];c;c=c.Zc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Wb.lookup(a,b)}
function ob(a,b,c,d){a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.Zc=vb[b];return vb[b]=a}var Db={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Eb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Fb(a,b){try{return qb(a,b),20}catch(c){}return Bb(a,"wx")}function Gb(a){var b=4096;for(a=a||0;a<=b;a++)if(!tb[a])return a;throw new I(33);}function Hb(a,b){Ib||(Ib=function(){},Ib.prototype={});var c=new Ib,d;for(d in a)c[d]=a[d];a=c;b=Gb(b);a.fd=b;return tb[b]=a}var nb={open:function(a){a.Vb=sb[a.node.rdev].Vb;a.Vb.open&&a.Vb.open(a)},ec:function(){throw new I(70);}};function jb(a,b){sb[a]={Vb:b}}
function Jb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new I(10);if(!c&&!d){var e=L(b,{Ic:!1});b=e.path;e=e.node;if(e.rc)throw new I(10);if(16384!==(e.mode&61440))throw new I(54);}b={type:a,pd:{},Mc:b,Yc:[]};a=a.bc(b);a.bc=b;b.root=a;c?rb=a:e&&(e.rc=b,e.bc&&e.bc.Yc.push(b))}function Kb(a,b,c){var d=L(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Fb(d,a);if(e)throw new I(e);if(!d.Wb.qc)throw new I(63);return d.Wb.qc(d,a,b,c)}function M(a){Kb(a,16895,0)}
function Lb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Kb(a,b|8192,c)}function Mb(a,b){if(!gb(a))throw new I(44);var c=L(b,{parent:!0}).node;if(!c)throw new I(44);b=fb(b);var d=Fb(c,b);if(d)throw new I(d);if(!c.Wb.symlink)throw new I(63);c.Wb.symlink(c,b,a)}function yb(a){a=L(a).node;if(!a)throw new I(44);if(!a.Wb.readlink)throw new I(28);return gb(zb(a.parent),a.Wb.readlink(a))}
function Nb(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Db[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=db(a);try{f=L(a,{yc:!(b&131072)}).node}catch(p){}}e=!1;if(b&64)if(f){if(b&128)throw new I(20);}else f=Kb(a,c,0),e=!0;if(!f)throw new I(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new I(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Eb(b)||b&512)?31:Bb(f,Eb(b)):44))throw new I(c);if(b&512){c=f;var h;"string"===typeof c?h=L(c,{yc:!0}).node:h=c;if(!h.Wb.$b)throw new I(63);if(16384===(h.mode&61440))throw new I(31);if(32768!==(h.mode&61440))throw new I(28);if(c=Bb(h,"w"))throw new I(c);h.Wb.$b(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Hb({node:f,path:zb(f),flags:b,seekable:!0,position:0,Vb:f.Vb,gd:[],error:!1},d);d.Vb.open&&d.Vb.open(d);!g.logReadFiles||b&1||(Ob||(Ob={}),a in Ob||(Ob[a]=1,t("FS.trackingDelegate error on read file: "+
a)));try{xb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),xb.onOpenFile(a,f))}catch(p){t("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d}function Pb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Vb.ec)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Vb.ec(a,b,c);a.gd=[]}
function Qb(){I||(I=function(a,b){this.node=b;this.ad=function(c){this.ac=c};this.ad(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){pb[a]=new I(a);pb[a].stack="<generic error, no stack>"}))}var Rb;function Sb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Tb(a,b,c){a=db("/dev/"+a);var d=Sb(!!b,!!c);Ub||(Ub=64);var e=Ub++<<8|0;jb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,p,r){for(var v=0,x=0;x<r;x++){try{var G=b()}catch(R){throw new I(29);}if(void 0===G&&0===v)throw new I(6);if(null===G||void 0===G)break;v++;h[p+x]=G}v&&(f.node.timestamp=Date.now());return v},write:function(f,h,p,r){for(var v=0;v<r;v++)try{c(h[p+v])}catch(x){throw new I(29);}r&&(f.node.timestamp=Date.now());return v}});
Lb(a,d,e)}var Ub,N={},Ib,Ob,Vb={},Wb=void 0;function Xb(){Wb+=4;return z[Wb-4>>2]}function Yb(a){a=tb[a];if(!a)throw new I(8);return a}var Zb;fa?Zb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Zb=dateNow:Zb=function(){return performance.now()};function $b(){for(var a=O.length-1;0<=a;--a)ac(a);O=[];bc=[]}var bc=[];function cc(){if(dc.Kc&&ec.wc)for(var a=0;a<bc.length;++a){var b=bc[a];bc.splice(a,1);--a;b.ud.apply(null,b.hd)}}var O=[];
function ac(a){var b=O[a];b.target.removeEventListener(b.dc,b.Sc,b.mc);O.splice(a,1)}function fc(a){function b(d){++dc.Kc;ec=a;cc();a.pc(d);cc();--dc.Kc}if(a.oc)a.Sc=b,a.target.addEventListener(a.dc,b,a.mc),O.push(a),hc||(Ha.push($b),hc=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].dc==a.dc&&ac(c--)}var dc={},hc,ec,ic,jc,kc,lc,mc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){a=2<a?C(a):a;return mc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function nc(a){return 0>mc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function oc(a,b,c,d,e,f){ic||(ic=y(164));a={target:P(a),wc:!0,dc:f,oc:d,pc:function(h){var p=ic,r=p>>2;z[r]=h.location;z[r+1]=h.ctrlKey;z[r+2]=h.shiftKey;z[r+3]=h.altKey;z[r+4]=h.metaKey;z[r+5]=h.repeat;z[r+6]=h.charCode;z[r+7]=h.keyCode;z[r+8]=h.which;D(h.key||"",B,p+36,32);D(h.code||"",B,p+68,32);D(h.char||"",B,p+100,32);D(h.locale||"",B,p+132,32);pc(d,e,p,b)&&h.preventDefault()},mc:c};fc(a)}
function qc(a,b,c){a>>=2;z[a]=b.screenX;z[a+1]=b.screenY;z[a+2]=b.clientX;z[a+3]=b.clientY;z[a+4]=b.ctrlKey;z[a+5]=b.shiftKey;z[a+6]=b.altKey;z[a+7]=b.metaKey;za[2*a+16]=b.button;za[2*a+17]=b.buttons;z[a+9]=b.movementX;z[a+10]=b.movementY;c=nc(c);z[a+11]=b.clientX-c.left;z[a+12]=b.clientY-c.top}function rc(a,b,c,d,e,f){jc||(jc=y(64));a=P(a);fc({target:a,wc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,dc:f,oc:d,pc:function(h){h=h||event;qc(jc,h,a);pc(d,e,jc,b)&&h.preventDefault()},mc:c})}
function sc(a,b,c,d){kc||(kc=y(36));a=P(a);fc({target:a,dc:"resize",oc:d,pc:function(e){e=e||event;if(e.target==a){var f=kc,h=document.body;z[f>>2]=e.detail;z[f+4>>2]=h.clientWidth;z[f+8>>2]=h.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset;z[f+32>>2]=pageYOffset;pc(d,10,f,b)&&e.preventDefault()}},mc:c})}
function tc(a,b,c,d){lc||(lc=y(96));fc({target:a,wc:!0,dc:"wheel",oc:d,pc:function(e){e=e||event;var f=lc;qc(f,e,a);F[f+64>>3]=e.deltaX;F[f+72>>3]=e.deltaY;F[f+80>>3]=e.deltaZ;z[f+88>>2]=e.deltaMode;pc(d,9,f,b)&&e.preventDefault()},mc:c})}
function uc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function vc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function wc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var xc=1,yc=[],Q=[],zc=[],Ac=[],Bc=[],S=[],T=[],Cc=[],U=[],Ec=[],Fc={},Gc={},Hc=4;
function V(a){Ic||(Ic=a)}function Jc(a){for(var b=xc++,c=a.length;c<b;c++)a[c]=null;return b}
function Kc(a){a||(a=W);if(!a.Vc){a.Vc=!0;var b=a.fc;uc(b);vc(b);wc(b);b.Rc=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var W,Ic,Lc=["default","low-power","high-performance"];g._emscripten_webgl_get_current_context=function(){return W?W.Uc:0};function Mc(a){W=U[a];g.jd=X=W&&W.fc;return!a||X?0:-5}g._emscripten_webgl_make_context_current=Mc;var Nc={};
function Oc(){if(!Pc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Nc)a[b]=Nc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Pc=c}return Pc}var Pc,Qc=[];function Rc(a,b,c,d){for(var e=0;e<a;e++){var f=X[c](),h=f&&Jc(d);f?(f.name=h,d[h]=f):V(1282);z[b+4*e>>2]=h}}
function Sc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 36345:d=0;break;case 34466:var e=X.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=X.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z[b+4*a>>2]=e[a];break;case 2:E[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){V(1280);t("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);t("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=
d;Ba[b>>2]=c;Ba[b+4>>2]=(c-Ba[b>>2])/4294967296;break;case 0:z[b>>2]=d;break;case 2:E[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else V(1281)}function Tc(a){var b=va(a)+1,c=y(b);D(a,B,c,b);return c}function Uc(a,b,c,d,e){a-=5120;a=1==a?B:4==a?z:6==a?E:5==a||28922==a?Ba:Aa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Hc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var Y=[],Vc=[];function Wc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Xc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Yc=[31,29,31,30,31,30,31,31,30,31,30,31],Zc=[31,28,31,30,31,30,31,31,30,31,30,31];function $c(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Wc(a.getFullYear())?Yc:Zc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function ad(a,b,c,d){function e(l,u,w){for(l="number"===typeof l?l.toString():l||"";l.length<u;)l=w[0]+l;return l}function f(l,u){return e(l,u,"0")}function h(l,u){function w(Dc){return 0>Dc?-1:0<Dc?1:0}var J;0===(J=w(l.getFullYear()-u.getFullYear()))&&0===(J=w(l.getMonth()-u.getMonth()))&&(J=w(l.getDate()-u.getDate()));return J}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function r(l){l=$c(new Date(l.Yb+1900,0,1),l.vc);var u=new Date(l.getFullYear()+1,0,4),w=p(new Date(l.getFullYear(),0,4));u=p(u);return 0>=h(w,l)?0>=h(u,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var v=z[d+40>>2];d={dd:z[d>>2],cd:z[d+4>>2],tc:z[d+8>>2],lc:z[d+12>>2],ic:z[d+16>>2],Yb:z[d+20>>2],uc:z[d+24>>2],vc:z[d+28>>2],vd:z[d+32>>2],bd:z[d+
36>>2],ed:v?C(v):""};c=C(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var x in v)c=c.replace(new RegExp(x,"g"),v[x]);var G="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
R="January February March April May June July August September October November December".split(" ");v={"%a":function(l){return G[l.uc].substring(0,3)},"%A":function(l){return G[l.uc]},"%b":function(l){return R[l.ic].substring(0,3)},"%B":function(l){return R[l.ic]},"%C":function(l){return f((l.Yb+1900)/100|0,2)},"%d":function(l){return f(l.lc,2)},"%e":function(l){return e(l.lc,2," ")},"%g":function(l){return r(l).toString().substring(2)},"%G":function(l){return r(l)},"%H":function(l){return f(l.tc,
2)},"%I":function(l){l=l.tc;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){return f(l.lc+Xc(Wc(l.Yb+1900)?Yc:Zc,l.ic-1),3)},"%m":function(l){return f(l.ic+1,2)},"%M":function(l){return f(l.cd,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.tc&&12>l.tc?"AM":"PM"},"%S":function(l){return f(l.dd,2)},"%t":function(){return"\t"},"%u":function(l){return l.uc||7},"%U":function(l){var u=new Date(l.Yb+1900,0,1),w=0===u.getDay()?u:$c(u,7-u.getDay());l=new Date(l.Yb+1900,l.ic,l.lc);return 0>
h(w,l)?f(Math.ceil((31-w.getDate()+(Xc(Wc(l.getFullYear())?Yc:Zc,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(w,u)?"01":"00"},"%V":function(l){var u=new Date(l.Yb+1901,0,4),w=p(new Date(l.Yb+1900,0,4));u=p(u);var J=$c(new Date(l.Yb+1900,0,1),l.vc);return 0>h(J,w)?"53":0>=h(u,J)?"01":f(Math.ceil((w.getFullYear()<l.Yb+1900?l.vc+32-w.getDate():l.vc+1-w.getDate())/7),2)},"%w":function(l){return l.uc},"%W":function(l){var u=new Date(l.Yb,0,1),w=1===u.getDay()?u:$c(u,0===u.getDay()?1:7-u.getDay()+1);l=
new Date(l.Yb+1900,l.ic,l.lc);return 0>h(w,l)?f(Math.ceil((31-w.getDate()+(Xc(Wc(l.getFullYear())?Yc:Zc,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(w,u)?"01":"00"},"%y":function(l){return(l.Yb+1900).toString().substring(2)},"%Y":function(l){return l.Yb+1900},"%z":function(l){l=l.bd;var u=0<=l;l=Math.abs(l)/60;return(u?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.ed},"%%":function(){return"%"}};for(x in v)0<=c.indexOf(x)&&(c=c.replace(new RegExp(x,"g"),v[x](d)));x=
Za(c,!1);if(x.length>b)return 0;A.set(x,a);return x.length-1}var bd=[];function Cb(a,b,c,d){a||(a=this);this.parent=a;this.bc=a.bc;this.rc=null;this.id=ub++;this.name=b;this.mode=c;this.Wb={};this.Vb={};this.rdev=d}Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Qb();vb=Array(4096);Jb(K,"/");M("/tmp");M("/home");
M("/home/web_user");
(function(){M("/dev");jb(259,{read:function(){return 0},write:function(d,e,f,h){return h}});Lb("/dev/null",259);ib(1280,lb);ib(1536,mb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(fa)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});Tb("random",b);Tb("urandom",b);M("/dev/shm");
M("/dev/shm/tmp")})();M("/proc");M("/proc/self");M("/proc/self/fd");Jb({bc:function(){var a=ob("/proc/self","fd",16895,73);a.Wb={lookup:function(b,c){var d=tb[+c];if(!d)throw new I(8);b={parent:null,bc:{Mc:"fake"},Wb:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var X,Z=0;32>Z;++Z)Qc.push(Array(Z));var cd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=cd.subarray(0,Z+1);var dd=new Int32Array(288);for(Z=0;288>Z;++Z)Vc[Z]=dd.subarray(0,Z+1);
function Za(a,b){var c=Array(va(a)+1);a=D(a,c,0,c.length);b&&(c.length=a);return c}
var hd={Ma:function(a){return y(a)},La:function(a){"uncaught_exception"in bb?bb.nc++:bb.nc=1;throw a;},$a:function(){z[ed()>>2]=63;return-1},hb:function(a,b){try{a=C(a);if(b&-8)var c=-28;else{var d;(d=L(a,{yc:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Bb(d,a)?-2:0):c=-44}return c}catch(e){return"undefined"!==typeof N&&e instanceof I||q(e),-e.ac}},p:function(a,b,c){Wb=c;try{var d=Yb(a);switch(b){case 0:var e=Xb();return 0>e?-28:Nb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=Xb(),d.flags|=e,0;case 12:return e=Xb(),za[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return z[ed()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof N&&f instanceof I||q(f),-f.ac}},fb:function(a,b,c){Wb=c;try{var d=Yb(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Xb();return z[e>>2]=0;case 21520:return d.tty?
-28:-59;case 21531:a=e=Xb();if(!d.Vb.Wc)throw new I(59);return d.Vb.Wc(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:q("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof N&&f instanceof I||q(f),-f.ac}},_a:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Vb[a];if(d&&b===d.md){var e=tb[d.fd];if(d.qd&2){var f=d.flags,h=d.offset,p=B.slice(a,a+b);e&&e.Vb.sc&&e.Vb.sc(e,p,h,b,f)}Vb[a]=null;d.Pc&&fd(d.nd)}c=0}return c}catch(r){return"undefined"!==typeof N&&
r instanceof I||q(r),-r.ac}},gb:function(a,b,c){Wb=c;try{var d=C(a),e=Xb();return Nb(d,b,e).fd}catch(f){return"undefined"!==typeof N&&f instanceof I||q(f),-f.ac}},a:function(){q()},ab:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Zb();else return z[ed()>>2]=28,-1;z[b>>2]=a/1E3|0;z[b+4>>2]=a%1E3*1E6|0;return 0},e:function(a,b,c){bd.length=0;var d;for(c>>=2;d=B[b++];)bd.push(105>d?F[++c>>1]:z[c]),++c;return $a[a].apply(null,bd)},Ra:function(a,b,c){a=P(a);if(!a)return-4;z[b>>2]=a.width;
z[c>>2]=a.height},kb:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},Sa:function(a,b,c){a=P(a);if(!a)return-4;a=nc(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},Xa:function(a,b,c){B.copyWithin(a,b,b+c)},Ya:function(){q("OOM")},h:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ua:function(a,b,c,d){oc(a,b,c,d,2,"keydown");return 0},Ta:function(a,b,c,d){oc(a,b,c,d,3,"keyup");return 0},L:function(a,b,c,d){rc(a,b,c,d,5,"mousedown");return 0},jb:function(a,
b,c,d){rc(a,b,c,d,8,"mousemove");return 0},C:function(a,b,c,d){rc(a,b,c,d,6,"mouseup");return 0},U:function(a,b,c,d){sc(a,b,c,d);return 0},bb:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(tc(a,b,c,d),0):-1},Qa:function(){return W&&W.fc&&W.attributes.Hc?0:-3},ma:function(a,b){var c={};b>>=2;c.alpha=!!z[b];c.depth=!!z[b+1];c.stencil=!!z[b+2];c.antialias=!!z[b+3];c.premultipliedAlpha=!!z[b+4];c.preserveDrawingBuffer=!!z[b+5];c.powerPreference=Lc[z[b+6]];c.failIfMajorPerformanceCaveat=
!!z[b+7];c.Xc=z[b+8];c.od=z[b+9];c.Fc=z[b+10];c.Hc=z[b+11];c.rd=z[b+12];c.td=z[b+13];if(a=P(a))if(c.Hc)c=-1;else if(a=a.getContext("webgl",c)){b=Jc(U);var d={Uc:b,attributes:c,version:c.Xc,fc:a};a.canvas&&(a.canvas.Oc=d);U[b]=d;("undefined"===typeof c.Fc||c.Fc)&&Kc(d);c=b}else c=0;else c=-4;return c},Oa:function(a){W==a&&(W=0);W===U[a]&&(W=null);if("object"===typeof dc)for(var b=U[a].fc.canvas,c=0;c<O.length;++c)O[c].target!=b||ac(c--);U[a]&&U[a].fc.canvas&&(U[a].fc.canvas.Oc=void 0);U[a]=null},xa:function(a){a>>=
2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},ca:Mc,cb:function(a,b){var c=0;Oc().forEach(function(d,e){var f=b+c;e=z[a+4*e>>2]=f;for(f=0;f<d.length;++f)A[e++>>0]=d.charCodeAt(f);A[e>>0]=0;c+=d.length+1});return 0},db:function(a,b){var c=Oc();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0},o:function(a){gd(a)},r:function(a){try{var b=Yb(a);if(null===b.fd)throw new I(8);b.zc&&(b.zc=null);try{b.Vb.close&&b.Vb.close(b)}catch(c){throw c;
}finally{tb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof N&&c instanceof I||q(c),c.ac}},eb:function(a,b,c,d){try{a:{for(var e=Yb(a),f=a=0;f<c;f++){var h=z[b+(8*f+4)>>2],p=e,r=z[b+8*f>>2],v=h,x=void 0,G=A;if(0>v||0>x)throw new I(28);if(null===p.fd)throw new I(8);if(1===(p.flags&2097155))throw new I(8);if(16384===(p.node.mode&61440))throw new I(31);if(!p.Vb.read)throw new I(28);var R="undefined"!==typeof x;if(!R)x=p.position;else if(!p.seekable)throw new I(70);var l=p.Vb.read(p,
G,r,v,x);R||(p.position+=l);var u=l;if(0>u){var w=-1;break a}a+=u;if(u<h)break}w=a}z[d>>2]=w;return 0}catch(J){return"undefined"!==typeof N&&J instanceof I||q(J),J.ac}},Va:function(a,b,c,d,e){try{var f=Yb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Pb(f,a,d);Ya=[f.position>>>0,(Xa=f.position,1<=+Ka(Xa)?0<Xa?(Na(+Ma(Xa/4294967296),4294967295)|0)>>>0:~~+La((Xa-+(~~Xa>>>0))/4294967296)>>>0:0)];z[e>>2]=Ya[0];z[e+4>>2]=Ya[1];f.zc&&0===a&&0===d&&(f.zc=null);return 0}catch(h){return"undefined"!==
typeof N&&h instanceof I||q(h),h.ac}},q:function(a,b,c,d){try{a:{for(var e=Yb(a),f=a=0;f<c;f++){var h=e,p=z[b+8*f>>2],r=z[b+(8*f+4)>>2],v=void 0,x=A;if(0>r||0>v)throw new I(28);if(null===h.fd)throw new I(8);if(0===(h.flags&2097155))throw new I(8);if(16384===(h.node.mode&61440))throw new I(31);if(!h.Vb.write)throw new I(28);h.seekable&&h.flags&1024&&Pb(h,0,2);var G="undefined"!==typeof v;if(!G)v=h.position;else if(!h.seekable)throw new I(70);var R=h.Vb.write(h,x,p,r,v,void 0);G||(h.position+=R);try{if(h.path&&
xb.onWriteToFile)xb.onWriteToFile(h.path)}catch(w){t("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+w.message)}var l=R;if(0>l){var u=-1;break a}a+=l}u=a}z[d>>2]=u;return 0}catch(w){return"undefined"!==typeof N&&w instanceof I||q(w),w.ac}},g:function(a){X.activeTexture(a)},$:function(a,b){X.attachShader(Q[a],T[b])},_:function(a,b,c){X.bindAttribLocation(Q[a],b,C(c))},n:function(a,b){X.bindBuffer(a,yc[b])},ja:function(a,b){X.bindFramebuffer(a,zc[b])},ya:function(a,b){X.bindRenderbuffer(a,
Ac[b])},f:function(a,b){X.bindTexture(a,Bc[b])},u:function(a){X.bindVertexArray(Cc[a])},Ha:function(a,b){X.blendEquationSeparate(a,b)},Ga:function(a,b){X.blendFunc(a,b)},Ba:function(a,b,c,d){X.bufferData(a,c?B.subarray(c,c+b):b,d)},Aa:function(a,b,c,d){X.bufferSubData(a,b,B.subarray(d,d+c))},ha:function(a){return X.checkFramebufferStatus(a)},ia:function(a){X.clear(a)},Ja:function(a,b,c,d){X.clearColor(a,b,c,d)},Fa:function(a){X.clearDepth(a)},na:function(a){X.compileShader(T[a])},j:function(a,b,c,
d,e,f,h,p,r){X.compressedTexSubImage2D(a,b,c,d,e,f,h,r?B.subarray(r,r+p):null)},fa:function(a,b,c,d,e,f,h,p){X.copyTexSubImage2D(a,b,c,d,e,f,h,p)},ea:function(){var a=Jc(Q),b=X.createProgram();b.name=a;Q[a]=b;return a},qa:function(a){var b=Jc(T);T[b]=X.createShader(a);return b},Da:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=yc[d];e&&(X.deleteBuffer(e),e.name=0,yc[d]=null)}},da:function(a){if(a){var b=Q[a];b?(X.deleteProgram(b),b.name=0,Q[a]=null,Fc[a]=null):V(1281)}},pa:function(a){if(a){var b=
T[a];b?(X.deleteShader(b),T[a]=null):V(1281)}},J:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Bc[d];e&&(X.deleteTexture(e),e.name=0,Bc[d]=null)}},t:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];X.deleteVertexArray(Cc[d]);Cc[d]=null}},b:function(a){X.disable(a)},y:function(a){X.disableVertexAttribArray(a)},D:function(a,b,c){X.drawArrays(a,b,c)},w:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},ib:function(a,b){for(var c=Qc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];X.drawBuffers(c)},B:function(a,
b,c,d){X.drawElements(a,b,c,d)},v:function(a,b,c,d,e){X.drawElementsInstanced(a,b,c,d,e)},c:function(a){X.enable(a)},A:function(a){X.enableVertexAttribArray(a)},ua:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,Ac[d])},ta:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,Bc[d],e)},Ea:function(a,b){Rc(a,b,"createBuffer",yc)},va:function(a,b){Rc(a,b,"createFramebuffer",zc)},ra:function(a,b){for(var c=0;c<a;c++){var d=X.Rc.createQueryEXT();if(!d){for(V(1282);c<a;)z[b+4*c++>>2]=0;break}var e=Jc(Ec);
d.name=e;Ec[e]=d;z[b+4*c>>2]=e}},za:function(a,b){Rc(a,b,"createRenderbuffer",Ac)},K:function(a,b){Rc(a,b,"createTexture",Bc)},s:function(a,b){Rc(a,b,"createVertexArray",Cc)},I:function(a){X.generateMipmap(a)},Ca:function(a,b,c){c?z[c>>2]=X.getBufferParameter(a,b):V(1281)},Na:function(){var a=X.getError()||Ic;Ic=0;return a},Ka:function(a,b){Sc(a,b,2)},i:function(a,b){Sc(a,b,0)},ba:function(a,b,c,d){a=X.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,B,d,b):0;c&&(z[c>>2]=b)},l:function(a,
b,c){if(c)if(a>=xc)V(1281);else{var d=Fc[a];if(d)if(35716==b)a=X.getProgramInfoLog(Q[a]),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b)z[c>>2]=d.Ac;else if(35722==b){if(-1==d.jc){a=Q[a];var e=X.getProgramParameter(a,35721);for(b=d.jc=0;b<e;++b)d.jc=Math.max(d.jc,X.getActiveAttrib(a,b).name.length+1)}z[c>>2]=d.jc}else if(35381==b){if(-1==d.kc)for(a=Q[a],e=X.getProgramParameter(a,35382),b=d.kc=0;b<e;++b)d.kc=Math.max(d.kc,X.getActiveUniformBlockName(a,b).length+1);z[c>>2]=d.kc}else z[c>>
2]=X.getProgramParameter(Q[a],b);else V(1282)}else V(1281)},la:function(a,b,c,d){a=X.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,B,d,b):0;c&&(z[c>>2]=b)},m:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1):35720==b?(a=X.getShaderSource(T[a]),z[c>>2]=null===a||0==a.length?0:a.length+1):z[c>>2]=X.getShaderParameter(T[a],b):V(1281)},d:function(a){if(Gc[a])return Gc[a];switch(a){case 7939:var b=X.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Tc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||V(1280);b=Tc(b);break;case 7938:b=Tc("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Tc(b);break;default:return V(1280),0}return Gc[a]=b},Y:function(a,b){b=C(b);var c=0;if("]"==b[b.length-
1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Fc[a]&&Fc[a].Nc[b])&&0<=c&&c<a[0]?a[1]+c:-1},Z:function(a){X.linkProgram(Q[a]);var b=Q[a];a=Fc[a]={Nc:{},Ac:0,jc:-1,kc:-1};for(var c=a.Nc,d=X.getProgramParameter(b,35718),e=0;e<d;++e){var f=X.getActiveUniform(b,e),h=f.name;a.Ac=Math.max(a.Ac,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var p=X.getUniformLocation(b,h);if(p){var r=Jc(S);c[h]=[f.size,r];S[r]=p;for(var v=1;v<f.size;++v)p=X.getUniformLocation(b,
h+"["+v+"]"),r=Jc(S),S[r]=p}}},sa:function(a,b){3317==a&&(Hc=b);X.pixelStorei(a,b)},ga:function(a,b,c,d,e,f,h){(h=Uc(f,e,c,d,h))?X.readPixels(a,b,c,d,e,f,h):V(1280)},wa:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},Ia:function(a,b,c,d){X.scissor(a,b,c,d)},oa:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?z[d+4*f>>2]:-1;e+=C(z[c+4*f>>2],0>h?void 0:h)}X.shaderSource(T[a],e)},E:function(a,b,c,d,e,f,h,p,r){X.texImage2D(a,b,c,d,e,f,h,p,r?Uc(p,h,d,e,r):null)},G:function(a,b,c){X.texParameterf(a,
b,c)},F:function(a,b,c){X.texParameterf(a,b,E[c>>2])},H:function(a,b,c){X.texParameteri(a,b,c)},k:function(a,b,c,d,e,f,h,p,r){var v=null;r&&(v=Uc(p,h,e,f,r));X.texSubImage2D(a,b,c,d,e,f,h,p,v)},X:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);X.uniform1fv(S[a],d)},S:function(a,b,c){if(288>=b)for(var d=Vc[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);X.uniform1iv(S[a],d)},W:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=
0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);X.uniform2fv(S[a],d)},R:function(a,b,c){if(144>=b)for(var d=Vc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);X.uniform2iv(S[a],d)},V:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=E.subarray(c>>2,c+12*b>>2);X.uniform3fv(S[a],d)},Q:function(a,b,c){if(96>=b)for(var d=Vc[3*b-1],e=0;e<3*
b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);X.uniform3iv(S[a],d)},T:function(a,b,c){if(72>=b){var d=Y[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var f=c+e;d[e]=E[f];d[e+1]=E[f+1];d[e+2]=E[f+2];d[e+3]=E[f+3]}}else d=E.subarray(c>>2,c+16*b>>2);X.uniform4fv(S[a],d)},P:function(a,b,c){if(72>=b)for(var d=Vc[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);
X.uniform4iv(S[a],d)},O:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=E[d+4*f>>2],e[f+1]=E[d+(4*f+4)>>2],e[f+2]=E[d+(4*f+8)>>2],e[f+3]=E[d+(4*f+12)>>2];else e=E.subarray(d>>2,d+16*b>>2);X.uniformMatrix2fv(S[a],!!c,e)},N:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=9)e[f]=E[d+4*f>>2],e[f+1]=E[d+(4*f+4)>>2],e[f+2]=E[d+(4*f+8)>>2],e[f+3]=E[d+(4*f+12)>>2],e[f+4]=E[d+(4*f+16)>>2],e[f+5]=E[d+(4*f+20)>>2],e[f+6]=E[d+(4*f+24)>>2],e[f+7]=E[d+(4*f+28)>>2],e[f+8]=E[d+(4*f+32)>>
2];else e=E.subarray(d>>2,d+36*b>>2);X.uniformMatrix3fv(S[a],!!c,e)},M:function(a,b,c,d){if(18>=b){var e=Y[16*b-1];d>>=2;for(var f=0;f<16*b;f+=16){var h=d+f;e[f]=E[h];e[f+1]=E[h+1];e[f+2]=E[h+2];e[f+3]=E[h+3];e[f+4]=E[h+4];e[f+5]=E[h+5];e[f+6]=E[h+6];e[f+7]=E[h+7];e[f+8]=E[h+8];e[f+9]=E[h+9];e[f+10]=E[h+10];e[f+11]=E[h+11];e[f+12]=E[h+12];e[f+13]=E[h+13];e[f+14]=E[h+14];e[f+15]=E[h+15]}}else e=E.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(S[a],!!c,e)},aa:function(a){X.useProgram(Q[a])},x:function(a,
b){X.vertexAttribDivisor(a,b)},z:function(a,b,c,d,e,f){X.vertexAttribPointer(a,b,c,!!d,e,f)},ka:function(a,b,c,d){X.viewport(a,b,c,d)},memory:pa,Pa:function(a){a=+a;return 0<=a?+Ma(a+.5):+La(a-.5)},Wa:function(){},Za:function(a,b,c,d){return ad(a,b,c,d)},table:qa};
(function(){function a(e){g.asm=e.exports;Oa--;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa&&(e=Qa,Qa=null,e()))}function b(e){a(e.instance)}function c(e){return Wa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){t("failed to asynchronously prepare wasm: "+f);q(f)})}var d={a:hd};Oa++;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return t("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(oa||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||Ra("file://")||"function"!==typeof fetch)return c(b);fetch(Sa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var ab=g.___wasm_call_ctors=function(){return(ab=g.___wasm_call_ctors=g.asm.lb).apply(null,arguments)};
g._main=function(){return(g._main=g.asm.mb).apply(null,arguments)};var fd=g._free=function(){return(fd=g._free=g.asm.nb).apply(null,arguments)},y=g._malloc=function(){return(y=g._malloc=g.asm.ob).apply(null,arguments)},ed=g.___errno_location=function(){return(ed=g.___errno_location=g.asm.pb).apply(null,arguments)},xa=g.stackAlloc=function(){return(xa=g.stackAlloc=g.asm.qb).apply(null,arguments)};g.dynCall_vi=function(){return(g.dynCall_vi=g.asm.rb).apply(null,arguments)};
g.dynCall_ii=function(){return(g.dynCall_ii=g.asm.sb).apply(null,arguments)};g.dynCall_vii=function(){return(g.dynCall_vii=g.asm.tb).apply(null,arguments)};g.dynCall_iii=function(){return(g.dynCall_iii=g.asm.ub).apply(null,arguments)};var pc=g.dynCall_iiii=function(){return(pc=g.dynCall_iiii=g.asm.vb).apply(null,arguments)};g.dynCall_v=function(){return(g.dynCall_v=g.asm.wb).apply(null,arguments)};g.dynCall_viii=function(){return(g.dynCall_viii=g.asm.xb).apply(null,arguments)};
g.dynCall_viiii=function(){return(g.dynCall_viiii=g.asm.yb).apply(null,arguments)};g.dynCall_viiiii=function(){return(g.dynCall_viiiii=g.asm.zb).apply(null,arguments)};g.dynCall_vf=function(){return(g.dynCall_vf=g.asm.Ab).apply(null,arguments)};g.dynCall_viiiiiiii=function(){return(g.dynCall_viiiiiiii=g.asm.Bb).apply(null,arguments)};g.dynCall_viiiiiii=function(){return(g.dynCall_viiiiiii=g.asm.Cb).apply(null,arguments)};g.dynCall_viif=function(){return(g.dynCall_viif=g.asm.Db).apply(null,arguments)};
g.dynCall_vif=function(){return(g.dynCall_vif=g.asm.Eb).apply(null,arguments)};g.dynCall_viiiiiiiii=function(){return(g.dynCall_viiiiiiiii=g.asm.Fb).apply(null,arguments)};g.dynCall_fii=function(){return(g.dynCall_fii=g.asm.Gb).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Hb).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ib).apply(null,arguments)};g.dynCall_iidiiii=function(){return(g.dynCall_iidiiii=g.asm.Jb).apply(null,arguments)};
g.dynCall_iiiii=function(){return(g.dynCall_iiiii=g.asm.Kb).apply(null,arguments)};g.dynCall_iiiiii=function(){return(g.dynCall_iiiiii=g.asm.Lb).apply(null,arguments)};g.dynCall_iiiiiiiii=function(){return(g.dynCall_iiiiiiiii=g.asm.Mb).apply(null,arguments)};g.dynCall_iiiiiii=function(){return(g.dynCall_iiiiiii=g.asm.Nb).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ob).apply(null,arguments)};
g.dynCall_iiiiid=function(){return(g.dynCall_iiiiid=g.asm.Pb).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Qb).apply(null,arguments)};g.dynCall_iiiiiiii=function(){return(g.dynCall_iiiiiiii=g.asm.Rb).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Sb).apply(null,arguments)};g.dynCall_viiiiii=function(){return(g.dynCall_viiiiii=g.asm.Tb).apply(null,arguments)};var id;
function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function jd(){id||kd();id||(Qa=jd)};
function kd(a){function b(){if(!id&&(id=!0,g.calledRun=!0,!ra)){g.noFSInit||Rb||(Rb=!0,Qb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Tb("stdin",g.stdin):Mb("/dev/tty","/dev/stdin"),g.stdout?Tb("stdout",null,g.stdout):Mb("/dev/tty","/dev/stdout"),g.stderr?Tb("stderr",null,g.stderr):Mb("/dev/tty1","/dev/stderr"),Nb("/dev/stdin","r"),Nb("/dev/stdout","w"),Nb("/dev/stderr","w"));Da(Fa);wb=!1;Da(Ga);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(ld){var c=a,d=g._main;c=c||[];
var e=c.length+1,f=xa(4*(e+1));z[f>>2]=wa(ca);for(var h=1;h<e;h++)z[(f>>2)+h]=wa(c[h-1]);z[(f>>2)+e]=0;try{var p=d(e,f);gd(p,!0)}catch(r){r instanceof ma||("unwind"==r?noExitRuntime=!0:((c=r)&&"object"===typeof r&&r.stack&&(c=[r,r.stack]),t("exception thrown: "+c),da(1,r)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ia.unshift(c);Da(Ia)}}a=a||ba;if(!(0<Oa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ja();
Da(Ea);0<Oa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=kd;function gd(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(ra=!0,g.onExit))g.onExit(a);da(a,new ma(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ld=!0;g.noInitialRun&&(ld=!1);noExitRuntime=!0;kd();
