
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in f)f.hasOwnProperty(k)&&(aa[k]=f[k]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,m=!1,fa=!1,ha=!1;ea="object"===typeof window;m="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!m;var n="",ia,ja,ka,la;
if(fa)n=m?require("path").dirname(n)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
q),da=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||m)m?n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=f.print||console.log.bind(console),t=f.printErr||console.warn.bind(console);for(k in aa)aa.hasOwnProperty(k)&&(f[k]=aa[k]);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);var oa;f.wasmBinary&&(oa=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&t("no native wasm support detected");var pa,qa=new WebAssembly.Table({initial:1016,maximum:1016,element:"anyfunc"}),ra=!1;
function assert(a,b){a||q("Assertion failed: "+b)}function sa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=y(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)z[a>>2]=0;for(b=d+c;a<b;)A[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?ua(B,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var p=a.charCodeAt(++g);h=65536+((h&1023)<<10)|p&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function wa(a){var b=va(a)+1,c=xa(b);D(a,A,c,b);return c}var ya,A,B,za,Aa,z,Ba,E,F,Ca=f.INITIAL_MEMORY||16777216;f.wasmMemory?pa=f.wasmMemory:pa=new WebAssembly.Memory({initial:Ca/65536,maximum:Ca/65536});pa&&(ya=pa.buffer);Ca=ya.byteLength;var H=ya;ya=H;f.HEAP8=A=new Int8Array(H);f.HEAP16=za=new Int16Array(H);
f.HEAP32=z=new Int32Array(H);f.HEAPU8=B=new Uint8Array(H);f.HEAPU16=Aa=new Uint16Array(H);f.HEAPU32=Ba=new Uint32Array(H);f.HEAPF32=E=new Float32Array(H);f.HEAPF64=F=new Float64Array(H);z[33604]=5377456;function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.md;"number"===typeof c?void 0===b.Pc?f.dynCall_v(c):f.dynCall_vi(c,b.Pc):c(void 0===b.Pc?null:b.Pc)}}}var Ea=[],Fa=[],Ga=[],Ha=[],Ia=[];function Ja(){var a=f.preRun.shift();Ea.unshift(a)}
var Ka=Math.abs,La=Math.ceil,Ma=Math.floor,Na=Math.min,Oa=0,Pa=null,Qa=null;f.preloadedImages={};f.preloadedAudios={};function q(a){if(f.onAbort)f.onAbort(a);na(a);t(a);ra=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ra(a){var b=Sa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ta(){return Ra("data:application/octet-stream;base64,")}var Sa="magnum-bullet.wasm";
if(!Ta()){var Ua=Sa;Sa=f.locateFile?f.locateFile(Ua,n):n+Ua}function Va(){try{if(oa)return new Uint8Array(oa);if(ja)return ja(Sa);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function Wa(){return oa||!ea&&!m||"function"!==typeof fetch||Ra("file://")?new Promise(function(a){a(Va())}):fetch(Sa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Sa+"'";return a.arrayBuffer()}).catch(function(){return Va()})}
var Xa,Ya,$a={4291:function(){var a=f.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?sa(Za(a.id)):0},4619:function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?f.dynCall_ii.apply(null,[a].concat(e)):f.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},92556:function(a){a=C(a);return"undefined"!==typeof process&&a in process.env?sa(Za(process.env[a])):0}};Fa.push({md:function(){ab()}});
function bb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function cb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function eb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function fb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var gb=[];function hb(a,b){gb[a]={input:[],output:[],Ac:b};ib(a,jb)}
var jb={open:function(a){var b=gb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ac.flush(a.tty)},flush:function(a){a.tty.Ac.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ac.ad)throw new I(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Ac.ad(a.tty)}catch(p){throw new I(29);}if(void 0===h&&0===e)throw new I(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ac.Tc)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.Ac.Tc(a.tty,b[c+e])}catch(g){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},kb={ad:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.td?Buffer.td(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},Tc:function(a,b){null===b||10===b?(na(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(ua(a.output,0)),a.output=[])}},lb={Tc:function(a,b){null===b||10===b?(t(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(t(ua(a.output,0)),a.output=[])}},K={sc:null,vc:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);K.sc||(K.sc={dir:{node:{wc:K.pc.wc,tc:K.pc.tc,lookup:K.pc.lookup,Ic:K.pc.Ic,rename:K.pc.rename,unlink:K.pc.unlink,rmdir:K.pc.rmdir,readdir:K.pc.readdir,symlink:K.pc.symlink},stream:{yc:K.oc.yc}},file:{node:{wc:K.pc.wc,tc:K.pc.tc},stream:{yc:K.oc.yc,read:K.oc.read,write:K.oc.write,Vc:K.oc.Vc,cd:K.oc.cd,Kc:K.oc.Kc}},link:{node:{wc:K.pc.wc,tc:K.pc.tc,readlink:K.pc.readlink},stream:{}},Wc:{node:{wc:K.pc.wc,
tc:K.pc.tc},stream:mb}});c=nb(a,b,c,d);16384===(c.mode&61440)?(c.pc=K.sc.dir.node,c.oc=K.sc.dir.stream,c.nc={}):32768===(c.mode&61440)?(c.pc=K.sc.file.node,c.oc=K.sc.file.stream,c.qc=0,c.nc=null):40960===(c.mode&61440)?(c.pc=K.sc.link.node,c.oc=K.sc.link.stream):8192===(c.mode&61440)&&(c.pc=K.sc.Wc.node,c.oc=K.sc.Wc.stream);c.timestamp=Date.now();a&&(a.nc[b]=c);return c},Ed:function(a){if(a.nc&&a.nc.subarray){for(var b=[],c=0;c<a.qc;++c)b.push(a.nc[c]);return b}return a.nc},Fd:function(a){return a.nc?
a.nc.subarray?a.nc.subarray(0,a.qc):new Uint8Array(a.nc):new Uint8Array(0)},Yc:function(a,b){var c=a.nc?a.nc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.nc,a.nc=new Uint8Array(b),0<a.qc&&a.nc.set(c.subarray(0,a.qc),0))},ud:function(a,b){if(a.qc!=b)if(0==b)a.nc=null,a.qc=0;else{if(!a.nc||a.nc.subarray){var c=a.nc;a.nc=new Uint8Array(b);c&&a.nc.set(c.subarray(0,Math.min(b,a.qc)))}else if(a.nc||(a.nc=[]),a.nc.length>b)a.nc.length=b;else for(;a.nc.length<b;)a.nc.push(0);
a.qc=b}},pc:{wc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.qc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.jd=4096;b.blocks=Math.ceil(b.size/b.jd);return b},tc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&K.ud(a,b.size)},lookup:function(){throw ob[44];},Ic:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pb(b,c)}catch(g){}if(d)for(var e in d.nc)throw new I(55);}delete a.parent.nc[a.name];a.name=c;b.nc[c]=a;a.parent=b},unlink:function(a,b){delete a.nc[b]},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.nc)throw new I(55);delete a.nc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.nc)a.nc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},oc:{read:function(a,b,c,d,e){var g=a.node.nc;if(e>=a.node.qc)return 0;a=Math.min(a.node.qc-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.nc||a.nc.subarray)){if(g)return a.nc=b.subarray(c,c+d),a.qc=d;if(0===a.qc&&0===e)return a.nc=
b.slice(c,c+d),a.qc=d;if(e+d<=a.qc)return a.nc.set(b.subarray(c,c+d),e),d}K.Yc(a,e+d);if(a.nc.subarray&&b.subarray)a.nc.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.nc[e+g]=b[c+g];a.qc=Math.max(a.qc,e+d);return d},yc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.qc);if(0>b)throw new I(28);return b},Vc:function(a,b,c){K.Yc(a.node,b+c);a.node.qc=Math.max(a.node.qc,b+c)},cd:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.nc;
if(g&2||a.buffer!==ya){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=y(c);if(!c)throw new I(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{Md:c,hd:d}},Kc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;K.oc.write(a,b,0,d,c,!1);return 0}}},qb=null,rb={},sb=[],tb=1,ub=null,vb=!0,wb={},I=null,ob={};
function L(a,b){a=fb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={$c:!0,Uc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Uc)throw new I(32);a=bb(a.split("/").filter(function(h){return!!h}),!1);var e=qb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=pb(e,a[d]);c=cb(c+"/"+a[d]);e.Jc&&(!g||g&&b.$c)&&(e=e.Jc.root);if(!g||b.Qc)for(g=0;40960===(e.mode&61440);)if(e=xb(c),c=fb(db(c),e),e=L(c,{Uc:b.Uc}).node,40<g++)throw new I(32);}return{path:c,node:e}}
function yb(a){for(var b;;){if(a===a.parent)return a=a.vc.dd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ub.length}function pb(a,b){var c;if(c=(c=Ab(a,"x"))?c:a.pc.lookup?0:2)throw new I(c,a);for(c=ub[zb(a.id,b)];c;c=c.sd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.pc.lookup(a,b)}
function nb(a,b,c,d){a=new Bb(a,b,c,d);b=zb(a.parent.id,a.name);a.sd=ub[b];return ub[b]=a}var Cb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(vb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Eb(a,b){try{return pb(a,b),20}catch(c){}return Ab(a,"wx")}function Fb(a){var b=4096;for(a=a||0;a<=b;a++)if(!sb[a])return a;throw new I(33);}function Gb(a,b){Hb||(Hb=function(){},Hb.prototype={});var c=new Hb,d;for(d in a)c[d]=a[d];a=c;b=Fb(b);a.fd=b;return sb[b]=a}var mb={open:function(a){a.oc=rb[a.node.rdev].oc;a.oc.open&&a.oc.open(a)},yc:function(){throw new I(70);}};function ib(a,b){rb[a]={oc:b}}
function Ib(a,b){var c="/"===b,d=!b;if(c&&qb)throw new I(10);if(!c&&!d){var e=L(b,{$c:!1});b=e.path;e=e.node;if(e.Jc)throw new I(10);if(16384!==(e.mode&61440))throw new I(54);}b={type:a,Jd:{},dd:b,rd:[]};a=a.vc(b);a.vc=b;b.root=a;c?qb=a:e&&(e.Jc=b,e.vc&&e.vc.rd.push(b))}function Jb(a,b,c){var d=L(a,{parent:!0}).node;a=eb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Eb(d,a);if(e)throw new I(e);if(!d.pc.Ic)throw new I(63);return d.pc.Ic(d,a,b,c)}function M(a){Jb(a,16895,0)}
function Kb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Jb(a,b|8192,c)}function Lb(a,b){if(!fb(a))throw new I(44);var c=L(b,{parent:!0}).node;if(!c)throw new I(44);b=eb(b);var d=Eb(c,b);if(d)throw new I(d);if(!c.pc.symlink)throw new I(63);c.pc.symlink(c,b,a)}function xb(a){a=L(a).node;if(!a)throw new I(44);if(!a.pc.readlink)throw new I(28);return fb(yb(a.parent),a.pc.readlink(a))}
function Mb(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Cb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=cb(a);try{g=L(a,{Qc:!(b&131072)}).node}catch(p){}}e=!1;if(b&64)if(g){if(b&128)throw new I(20);}else g=Jb(a,c,0),e=!0;if(!g)throw new I(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new I(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Db(b)||b&512)?31:Ab(g,Db(b)):44))throw new I(c);if(b&512){c=g;var h;"string"===typeof c?h=L(c,{Qc:!0}).node:h=c;if(!h.pc.tc)throw new I(63);if(16384===(h.mode&61440))throw new I(31);if(32768!==(h.mode&61440))throw new I(28);if(c=Ab(h,"w"))throw new I(c);h.pc.tc(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Gb({node:g,path:yb(g),flags:b,seekable:!0,position:0,oc:g.oc,Bd:[],error:!1},d);d.oc.open&&d.oc.open(d);!f.logReadFiles||b&1||(Nb||(Nb={}),a in Nb||(Nb[a]=1,t("FS.trackingDelegate error on read file: "+
a)));try{wb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),wb.onOpenFile(a,g))}catch(p){t("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d}function Ob(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.oc.yc)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.oc.yc(a,b,c);a.Bd=[]}
function Pb(){I||(I=function(a,b){this.node=b;this.vd=function(c){this.uc=c};this.vd(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){ob[a]=new I(a);ob[a].stack="<generic error, no stack>"}))}var Qb;function Rb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Sb(a,b,c){a=cb("/dev/"+a);var d=Rb(!!b,!!c);Tb||(Tb=64);var e=Tb++<<8|0;ib(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,p,r){for(var v=0,x=0;x<r;x++){try{var G=b()}catch(R){throw new I(29);}if(void 0===G&&0===v)throw new I(6);if(null===G||void 0===G)break;v++;h[p+x]=G}v&&(g.node.timestamp=Date.now());return v},write:function(g,h,p,r){for(var v=0;v<r;v++)try{c(h[p+v])}catch(x){throw new I(29);}r&&(g.node.timestamp=Date.now());return v}});
Kb(a,d,e)}var Tb,N={},Hb,Nb,Ub={},Vb=void 0;function Wb(){Vb+=4;return z[Vb-4>>2]}function Xb(a){a=sb[a];if(!a)throw new I(8);return a}var Yb;fa?Yb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Yb=dateNow:Yb=function(){return performance.now()};function Zb(){for(var a=O.length-1;0<=a;--a)$b(a);O=[];ac=[]}var ac=[];function bc(){if(cc.bd&&dc.Oc)for(var a=0;a<ac.length;++a){var b=ac[a];ac.splice(a,1);--a;b.Od.apply(null,b.Cd)}}var O=[];
function $b(a){var b=O[a];b.target.removeEventListener(b.xc,b.ld,b.Fc);O.splice(a,1)}function ec(a){function b(d){++cc.bd;dc=a;bc();a.Hc(d);bc();--cc.bd}if(a.Gc)a.ld=b,a.target.addEventListener(a.xc,b,a.Fc),O.push(a),fc||(Ha.push(Zb),fc=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].xc==a.xc&&$b(c--)}var cc={},fc,dc,hc,ic,jc,kc,lc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){a=2<a?C(a):a;return lc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function mc(a){return 0>lc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function nc(a,b,c,d,e,g){hc||(hc=y(164));a={target:P(a),Oc:!0,xc:g,Gc:d,Hc:function(h){var p=hc,r=p>>2;z[r]=h.location;z[r+1]=h.ctrlKey;z[r+2]=h.shiftKey;z[r+3]=h.altKey;z[r+4]=h.metaKey;z[r+5]=h.repeat;z[r+6]=h.charCode;z[r+7]=h.keyCode;z[r+8]=h.which;D(h.key||"",B,p+36,32);D(h.code||"",B,p+68,32);D(h.char||"",B,p+100,32);D(h.locale||"",B,p+132,32);oc(d,e,p,b)&&h.preventDefault()},Fc:c};ec(a)}
function pc(a,b,c){a>>=2;z[a]=b.screenX;z[a+1]=b.screenY;z[a+2]=b.clientX;z[a+3]=b.clientY;z[a+4]=b.ctrlKey;z[a+5]=b.shiftKey;z[a+6]=b.altKey;z[a+7]=b.metaKey;za[2*a+16]=b.button;za[2*a+17]=b.buttons;z[a+9]=b.movementX;z[a+10]=b.movementY;c=mc(c);z[a+11]=b.clientX-c.left;z[a+12]=b.clientY-c.top}function qc(a,b,c,d,e,g){ic||(ic=y(64));a=P(a);ec({target:a,Oc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,xc:g,Gc:d,Hc:function(h){h=h||event;pc(ic,h,a);oc(d,e,ic,b)&&h.preventDefault()},Fc:c})}
function rc(a,b,c,d){jc||(jc=y(36));a=P(a);ec({target:a,xc:"resize",Gc:d,Hc:function(e){e=e||event;if(e.target==a){var g=jc,h=document.body;z[g>>2]=e.detail;z[g+4>>2]=h.clientWidth;z[g+8>>2]=h.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset;z[g+32>>2]=pageYOffset;oc(d,10,g,b)&&e.preventDefault()}},Fc:c})}
function sc(a,b,c,d){kc||(kc=y(96));ec({target:a,Oc:!0,xc:"wheel",Gc:d,Hc:function(e){e=e||event;var g=kc;pc(g,e,a);F[g+64>>3]=e.deltaX;F[g+72>>3]=e.deltaY;F[g+80>>3]=e.deltaZ;z[g+88>>2]=e.deltaMode;oc(d,9,g,b)&&e.preventDefault()},Fc:c})}
function tc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function uc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function vc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var wc=1,xc=[],Q=[],yc=[],zc=[],Ac=[],S=[],T=[],Bc=[],U=[],Cc=[],Ec={},Fc={},Gc=4;
function V(a){Hc||(Hc=a)}function Ic(a){for(var b=wc++,c=a.length;c<b;c++)a[c]=null;return b}
function Jc(a){a||(a=W);if(!a.od){a.od=!0;var b=a.zc;tc(b);uc(b);vc(b);b.kd=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var W,Hc,Kc=["default","low-power","high-performance"];f._emscripten_webgl_get_current_context=function(){return W?W.nd:0};function Lc(a){W=U[a];f.Dd=X=W&&W.zc;return!a||X?0:-5}f._emscripten_webgl_make_context_current=Lc;var Mc={};
function Nc(){if(!Oc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Mc)a[b]=Mc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Oc=c}return Oc}var Oc,Pc=[];function Qc(a,b,c,d){for(var e=0;e<a;e++){var g=X[c](),h=g&&Ic(d);g?(g.name=h,d[h]=g):V(1282);z[b+4*e>>2]=h}}
function Rc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 36345:d=0;break;case 34466:var e=X.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=X.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z[b+4*a>>2]=e[a];break;case 2:E[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){V(1280);t("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:V(1280);t("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=
d;Ba[b>>2]=c;Ba[b+4>>2]=(c-Ba[b>>2])/4294967296;break;case 0:z[b>>2]=d;break;case 2:E[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else V(1281)}function Sc(a){var b=va(a)+1,c=y(b);D(a,B,c,b);return c}function Tc(a,b,c,d,e){a-=5120;a=1==a?B:4==a?z:6==a?E:5==a||28922==a?Ba:Aa;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Gc;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var Y=[],Uc=[];function Vc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Wc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Xc=[31,29,31,30,31,30,31,31,30,31,30,31],Yc=[31,28,31,30,31,30,31,31,30,31,30,31];function Zc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Vc(a.getFullYear())?Xc:Yc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function $c(a,b,c,d){function e(l,u,w){for(l="number"===typeof l?l.toString():l||"";l.length<u;)l=w[0]+l;return l}function g(l,u){return e(l,u,"0")}function h(l,u){function w(Dc){return 0>Dc?-1:0<Dc?1:0}var J;0===(J=w(l.getFullYear()-u.getFullYear()))&&0===(J=w(l.getMonth()-u.getMonth()))&&(J=w(l.getDate()-u.getDate()));return J}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function r(l){l=Zc(new Date(l.rc+1900,0,1),l.Nc);var u=new Date(l.getFullYear()+1,0,4),w=p(new Date(l.getFullYear(),0,4));u=p(u);return 0>=h(w,l)?0>=h(u,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var v=z[d+40>>2];d={yd:z[d>>2],xd:z[d+4>>2],Lc:z[d+8>>2],Ec:z[d+12>>2],Bc:z[d+16>>2],rc:z[d+20>>2],Mc:z[d+24>>2],Nc:z[d+28>>2],Pd:z[d+32>>2],wd:z[d+
36>>2],zd:v?C(v):""};c=C(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var x in v)c=c.replace(new RegExp(x,"g"),v[x]);var G="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
R="January February March April May June July August September October November December".split(" ");v={"%a":function(l){return G[l.Mc].substring(0,3)},"%A":function(l){return G[l.Mc]},"%b":function(l){return R[l.Bc].substring(0,3)},"%B":function(l){return R[l.Bc]},"%C":function(l){return g((l.rc+1900)/100|0,2)},"%d":function(l){return g(l.Ec,2)},"%e":function(l){return e(l.Ec,2," ")},"%g":function(l){return r(l).toString().substring(2)},"%G":function(l){return r(l)},"%H":function(l){return g(l.Lc,
2)},"%I":function(l){l=l.Lc;0==l?l=12:12<l&&(l-=12);return g(l,2)},"%j":function(l){return g(l.Ec+Wc(Vc(l.rc+1900)?Xc:Yc,l.Bc-1),3)},"%m":function(l){return g(l.Bc+1,2)},"%M":function(l){return g(l.xd,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.Lc&&12>l.Lc?"AM":"PM"},"%S":function(l){return g(l.yd,2)},"%t":function(){return"\t"},"%u":function(l){return l.Mc||7},"%U":function(l){var u=new Date(l.rc+1900,0,1),w=0===u.getDay()?u:Zc(u,7-u.getDay());l=new Date(l.rc+1900,l.Bc,l.Ec);return 0>
h(w,l)?g(Math.ceil((31-w.getDate()+(Wc(Vc(l.getFullYear())?Xc:Yc,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(w,u)?"01":"00"},"%V":function(l){var u=new Date(l.rc+1901,0,4),w=p(new Date(l.rc+1900,0,4));u=p(u);var J=Zc(new Date(l.rc+1900,0,1),l.Nc);return 0>h(J,w)?"53":0>=h(u,J)?"01":g(Math.ceil((w.getFullYear()<l.rc+1900?l.Nc+32-w.getDate():l.Nc+1-w.getDate())/7),2)},"%w":function(l){return l.Mc},"%W":function(l){var u=new Date(l.rc,0,1),w=1===u.getDay()?u:Zc(u,0===u.getDay()?1:7-u.getDay()+1);l=
new Date(l.rc+1900,l.Bc,l.Ec);return 0>h(w,l)?g(Math.ceil((31-w.getDate()+(Wc(Vc(l.getFullYear())?Xc:Yc,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(w,u)?"01":"00"},"%y":function(l){return(l.rc+1900).toString().substring(2)},"%Y":function(l){return l.rc+1900},"%z":function(l){l=l.wd;var u=0<=l;l=Math.abs(l)/60;return(u?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.zd},"%%":function(){return"%"}};for(x in v)0<=c.indexOf(x)&&(c=c.replace(new RegExp(x,"g"),v[x](d)));x=
Za(c,!1);if(x.length>b)return 0;A.set(x,a);return x.length-1}var ad=[];function Bb(a,b,c,d){a||(a=this);this.parent=a;this.vc=a.vc;this.Jc=null;this.id=tb++;this.name=b;this.mode=c;this.pc={};this.oc={};this.rdev=d}Object.defineProperties(Bb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Pb();ub=Array(4096);Ib(K,"/");M("/tmp");M("/home");
M("/home/web_user");
(function(){M("/dev");ib(259,{read:function(){return 0},write:function(d,e,g,h){return h}});Kb("/dev/null",259);hb(1280,kb);hb(1536,lb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(fa)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});Sb("random",b);Sb("urandom",b);M("/dev/shm");
M("/dev/shm/tmp")})();M("/proc");M("/proc/self");M("/proc/self/fd");Ib({vc:function(){var a=nb("/proc/self","fd",16895,73);a.pc={lookup:function(b,c){var d=sb[+c];if(!d)throw new I(8);b={parent:null,vc:{dd:"fake"},pc:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var X,Z=0;32>Z;++Z)Pc.push(Array(Z));var bd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=bd.subarray(0,Z+1);var cd=new Int32Array(288);for(Z=0;288>Z;++Z)Uc[Z]=cd.subarray(0,Z+1);
function Za(a,b){var c=Array(va(a)+1);a=D(a,c,0,c.length);b&&(c.length=a);return c}
var hd={Ga:function(a){return y(a)},Fa:function(a){"uncaught_exception"in dd?dd.Ad++:dd.Ad=1;throw a;},$a:function(){z[ed()>>2]=63;return-1},gb:function(a,b){try{a=C(a);if(b&-8)var c=-28;else{var d;(d=L(a,{Qc:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Ab(d,a)?-2:0):c=-44}return c}catch(e){return"undefined"!==typeof N&&e instanceof I||q(e),-e.uc}},r:function(a,b,c){Vb=c;try{var d=Xb(a);switch(b){case 0:var e=Wb();return 0>e?-28:Mb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=Wb(),d.flags|=e,0;case 12:return e=Wb(),za[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return z[ed()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof N&&g instanceof I||q(g),-g.uc}},eb:function(a,b,c){Vb=c;try{var d=Xb(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Wb();return z[e>>2]=0;case 21520:return d.tty?
-28:-59;case 21531:a=e=Wb();if(!d.oc.pd)throw new I(59);return d.oc.pd(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:q("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof N&&g instanceof I||q(g),-g.uc}},Za:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Ub[a];if(d&&b===d.Gd){var e=sb[d.fd];if(d.Kd&2){var g=d.flags,h=d.offset,p=B.slice(a,a+b);e&&e.oc.Kc&&e.oc.Kc(e,p,h,b,g)}Ub[a]=null;d.hd&&fd(d.Hd)}c=0}return c}catch(r){return"undefined"!==typeof N&&
r instanceof I||q(r),-r.uc}},fb:function(a,b,c){Vb=c;try{var d=C(a),e=Wb();return Mb(d,b,e).fd}catch(g){return"undefined"!==typeof N&&g instanceof I||q(g),-g.uc}},a:function(){q()},ab:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Yb();else return z[ed()>>2]=28,-1;z[b>>2]=a/1E3|0;z[b+4>>2]=a%1E3*1E6|0;return 0},g:function(a,b,c){ad.length=0;var d;for(c>>=2;d=B[b++];)ad.push(105>d?F[++c>>1]:z[c]),++c;return $a[a].apply(null,ad)},Qa:function(a,b,c){a=P(a);if(!a)return-4;z[b>>2]=a.width;
z[c>>2]=a.height},ib:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},Ra:function(a,b,c){a=P(a);if(!a)return-4;a=mc(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},Wa:function(a,b,c){B.copyWithin(a,b,b+c)},Xa:function(){q("OOM")},o:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ta:function(a,b,c,d){nc(a,b,c,d,2,"keydown");return 0},Sa:function(a,b,c,d){nc(a,b,c,d,3,"keyup");return 0},K:function(a,b,c,d){qc(a,b,c,d,5,"mousedown");return 0},hb:function(a,
b,c,d){qc(a,b,c,d,8,"mousemove");return 0},B:function(a,b,c,d){qc(a,b,c,d,6,"mouseup");return 0},T:function(a,b,c,d){rc(a,b,c,d);return 0},_a:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(sc(a,b,c,d),0):-1},Pa:function(){return W&&W.zc&&W.attributes.Zc?0:-3},ma:function(a,b){var c={};b>>=2;c.alpha=!!z[b];c.depth=!!z[b+1];c.stencil=!!z[b+2];c.antialias=!!z[b+3];c.premultipliedAlpha=!!z[b+4];c.preserveDrawingBuffer=!!z[b+5];c.powerPreference=Kc[z[b+6]];c.failIfMajorPerformanceCaveat=
!!z[b+7];c.qd=z[b+8];c.Id=z[b+9];c.Xc=z[b+10];c.Zc=z[b+11];c.Ld=z[b+12];c.Nd=z[b+13];if(a=P(a))if(c.Zc)c=-1;else if(a=a.getContext("webgl",c)){b=Ic(U);var d={nd:b,attributes:c,version:c.qd,zc:a};a.canvas&&(a.canvas.gd=d);U[b]=d;("undefined"===typeof c.Xc||c.Xc)&&Jc(d);c=b}else c=0;else c=-4;return c},La:function(a){W==a&&(W=0);W===U[a]&&(W=null);if("object"===typeof cc)for(var b=U[a].zc.canvas,c=0;c<O.length;++c)O[c].target!=b||$b(c--);U[a]&&U[a].zc.canvas&&(U[a].zc.canvas.gd=void 0);U[a]=null},wa:function(a){a>>=
2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},ca:Lc,bb:function(a,b){var c=0;Nc().forEach(function(d,e){var g=b+c;e=z[a+4*e>>2]=g;for(g=0;g<d.length;++g)A[e++>>0]=d.charCodeAt(g);A[e>>0]=0;c+=d.length+1});return 0},cb:function(a,b){var c=Nc();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0},p:function(a){gd(a)},h:function(a){try{var b=Xb(a);if(null===b.fd)throw new I(8);b.Rc&&(b.Rc=null);try{b.oc.close&&b.oc.close(b)}catch(c){throw c;
}finally{sb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof N&&c instanceof I||q(c),c.uc}},db:function(a,b,c,d){try{a:{for(var e=Xb(a),g=a=0;g<c;g++){var h=z[b+(8*g+4)>>2],p=e,r=z[b+8*g>>2],v=h,x=void 0,G=A;if(0>v||0>x)throw new I(28);if(null===p.fd)throw new I(8);if(1===(p.flags&2097155))throw new I(8);if(16384===(p.node.mode&61440))throw new I(31);if(!p.oc.read)throw new I(28);var R="undefined"!==typeof x;if(!R)x=p.position;else if(!p.seekable)throw new I(70);var l=p.oc.read(p,
G,r,v,x);R||(p.position+=l);var u=l;if(0>u){var w=-1;break a}a+=u;if(u<h)break}w=a}z[d>>2]=w;return 0}catch(J){return"undefined"!==typeof N&&J instanceof I||q(J),J.uc}},Ua:function(a,b,c,d,e){try{var g=Xb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Ob(g,a,d);Ya=[g.position>>>0,(Xa=g.position,1<=+Ka(Xa)?0<Xa?(Na(+Ma(Xa/4294967296),4294967295)|0)>>>0:~~+La((Xa-+(~~Xa>>>0))/4294967296)>>>0:0)];z[e>>2]=Ya[0];z[e+4>>2]=Ya[1];g.Rc&&0===a&&0===d&&(g.Rc=null);return 0}catch(h){return"undefined"!==
typeof N&&h instanceof I||q(h),h.uc}},s:function(a,b,c,d){try{a:{for(var e=Xb(a),g=a=0;g<c;g++){var h=e,p=z[b+8*g>>2],r=z[b+(8*g+4)>>2],v=void 0,x=A;if(0>r||0>v)throw new I(28);if(null===h.fd)throw new I(8);if(0===(h.flags&2097155))throw new I(8);if(16384===(h.node.mode&61440))throw new I(31);if(!h.oc.write)throw new I(28);h.seekable&&h.flags&1024&&Ob(h,0,2);var G="undefined"!==typeof v;if(!G)v=h.position;else if(!h.seekable)throw new I(70);var R=h.oc.write(h,x,p,r,v,void 0);G||(h.position+=R);try{if(h.path&&
wb.onWriteToFile)wb.onWriteToFile(h.path)}catch(w){t("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+w.message)}var l=R;if(0>l){var u=-1;break a}a+=l}u=a}z[d>>2]=u;return 0}catch(w){return"undefined"!==typeof N&&w instanceof I||q(w),w.uc}},i:function(a){var b=Date.now();z[a>>2]=b/1E3|0;z[a+4>>2]=b%1E3*1E3|0;return 0},d:function(a){X.activeTexture(a)},aa:function(a,b){X.attachShader(Q[a],T[b])},$:function(a,b,c){X.bindAttribLocation(Q[a],b,C(c))},q:function(a,b){X.bindBuffer(a,
xc[b])},ka:function(a,b){X.bindFramebuffer(a,yc[b])},za:function(a,b){X.bindRenderbuffer(a,zc[b])},c:function(a,b){X.bindTexture(a,Ac[b])},w:function(a){X.bindVertexArray(Bc[a])},Ja:function(a,b,c,d){X.bufferData(a,c?B.subarray(c,c+b):b,d)},Ia:function(a,b,c,d){X.bufferSubData(a,b,B.subarray(d,d+c))},ia:function(a){return X.checkFramebufferStatus(a)},ja:function(a){X.clear(a)},Da:function(a,b,c,d){X.clearColor(a,b,c,d)},Ba:function(a){X.clearDepth(a)},oa:function(a){X.compileShader(T[a])},j:function(a,
b,c,d,e,g,h,p,r){X.compressedTexSubImage2D(a,b,c,d,e,g,h,r?B.subarray(r,r+p):null)},ga:function(a,b,c,d,e,g,h,p){X.copyTexSubImage2D(a,b,c,d,e,g,h,p)},fa:function(){var a=Ic(Q),b=X.createProgram();b.name=a;Q[a]=b;return a},ra:function(a){var b=Ic(T);T[b]=X.createShader(a);return b},Ma:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=xc[d];e&&(X.deleteBuffer(e),e.name=0,xc[d]=null)}},ea:function(a){if(a){var b=Q[a];b?(X.deleteProgram(b),b.name=0,Q[a]=null,Ec[a]=null):V(1281)}},qa:function(a){if(a){var b=
T[a];b?(X.deleteShader(b),T[a]=null):V(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];X.deleteVertexArray(Bc[d]);Bc[d]=null}},n:function(a){X.depthFunc(a)},A:function(a){X.disableVertexAttribArray(a)},F:function(a,b,c){X.drawArrays(a,b,c)},y:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},t:function(a,b){for(var c=Pc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];X.drawBuffers(c)},E:function(a,b,c,d){X.drawElements(a,b,c,d)},x:function(a,b,c,d,e){X.drawElementsInstanced(a,b,c,d,e)},e:function(a){X.enable(a)},
D:function(a){X.enableVertexAttribArray(a)},va:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,zc[d])},ua:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,Ac[d],e)},Na:function(a,b){Qc(a,b,"createBuffer",xc)},xa:function(a,b){Qc(a,b,"createFramebuffer",yc)},sa:function(a,b){for(var c=0;c<a;c++){var d=X.kd.createQueryEXT();if(!d){for(V(1282);c<a;)z[b+4*c++>>2]=0;break}var e=Ic(Cc);d.name=e;Cc[e]=d;z[b+4*c>>2]=e}},Aa:function(a,b){Qc(a,b,"createRenderbuffer",zc)},M:function(a,b){Qc(a,b,"createTexture",
Ac)},u:function(a,b){Qc(a,b,"createVertexArray",Bc)},L:function(a){X.generateMipmap(a)},Ka:function(a,b,c){c?z[c>>2]=X.getBufferParameter(a,b):V(1281)},Ha:function(){var a=X.getError()||Hc;Hc=0;return a},Ea:function(a,b){Rc(a,b,2)},f:function(a,b){Rc(a,b,0)},da:function(a,b,c,d){a=X.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,B,d,b):0;c&&(z[c>>2]=b)},l:function(a,b,c){if(c)if(a>=wc)V(1281);else{var d=Ec[a];if(d)if(35716==b)a=X.getProgramInfoLog(Q[a]),null===a&&(a="(unknown error)"),
z[c>>2]=a.length+1;else if(35719==b)z[c>>2]=d.Sc;else if(35722==b){if(-1==d.Cc){a=Q[a];var e=X.getProgramParameter(a,35721);for(b=d.Cc=0;b<e;++b)d.Cc=Math.max(d.Cc,X.getActiveAttrib(a,b).name.length+1)}z[c>>2]=d.Cc}else if(35381==b){if(-1==d.Dc)for(a=Q[a],e=X.getProgramParameter(a,35382),b=d.Dc=0;b<e;++b)d.Dc=Math.max(d.Dc,X.getActiveUniformBlockName(a,b).length+1);z[c>>2]=d.Dc}else z[c>>2]=X.getProgramParameter(Q[a],b);else V(1282)}else V(1281)},na:function(a,b,c,d){a=X.getShaderInfoLog(T[a]);null===
a&&(a="(unknown error)");b=0<b&&d?D(a,B,d,b):0;c&&(z[c>>2]=b)},m:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1):35720==b?(a=X.getShaderSource(T[a]),z[c>>2]=null===a||0==a.length?0:a.length+1):z[c>>2]=X.getShaderParameter(T[a],b):V(1281)},b:function(a){if(Fc[a])return Fc[a];switch(a){case 7939:var b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Sc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
X.getParameter(a))||V(1280);b=Sc(b);break;case 7938:b=Sc("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Sc(b);break;default:return V(1280),0}return Fc[a]=b},Z:function(a,b){b=C(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Ec[a]&&Ec[a].ed[b])&&
0<=c&&c<a[0]?a[1]+c:-1},_:function(a){X.linkProgram(Q[a]);var b=Q[a];a=Ec[a]={ed:{},Sc:0,Cc:-1,Dc:-1};for(var c=a.ed,d=X.getProgramParameter(b,35718),e=0;e<d;++e){var g=X.getActiveUniform(b,e),h=g.name;a.Sc=Math.max(a.Sc,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var p=X.getUniformLocation(b,h);if(p){var r=Ic(S);c[h]=[g.size,r];S[r]=p;for(var v=1;v<g.size;++v)p=X.getUniformLocation(b,h+"["+v+"]"),r=Ic(S),S[r]=p}}},ta:function(a,b){3317==a&&(Gc=b);X.pixelStorei(a,b)},Ca:function(a,
b){X.polygonOffset(a,b)},ha:function(a,b,c,d,e,g,h){(h=Tc(g,e,c,d,h))?X.readPixels(a,b,c,d,e,g,h):V(1280)},ya:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},pa:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?z[d+4*g>>2]:-1;e+=C(z[c+4*g>>2],0>h?void 0:h)}X.shaderSource(T[a],e)},G:function(a,b,c,d,e,g,h,p,r){X.texImage2D(a,b,c,d,e,g,h,p,r?Tc(p,h,d,e,r):null)},I:function(a,b,c){X.texParameterf(a,b,c)},H:function(a,b,c){X.texParameterf(a,b,E[c>>2])},J:function(a,b,c){X.texParameteri(a,b,c)},k:function(a,
b,c,d,e,g,h,p,r){var v=null;r&&(v=Tc(p,h,e,g,r));X.texSubImage2D(a,b,c,d,e,g,h,p,v)},Y:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);X.uniform1fv(S[a],d)},U:function(a,b,c){if(288>=b)for(var d=Uc[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);X.uniform1iv(S[a],d)},X:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);X.uniform2fv(S[a],d)},
S:function(a,b,c){if(144>=b)for(var d=Uc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);X.uniform2iv(S[a],d)},W:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=E.subarray(c>>2,c+12*b>>2);X.uniform3fv(S[a],d)},R:function(a,b,c){if(96>=b)for(var d=Uc[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);X.uniform3iv(S[a],
d)},V:function(a,b,c){if(72>=b){var d=Y[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var g=c+e;d[e]=E[g];d[e+1]=E[g+1];d[e+2]=E[g+2];d[e+3]=E[g+3]}}else d=E.subarray(c>>2,c+16*b>>2);X.uniform4fv(S[a],d)},Q:function(a,b,c){if(72>=b)for(var d=Uc[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);X.uniform4iv(S[a],d)},P:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],g=0;g<4*b;g+=4)e[g]=E[d+4*g>>2],e[g+1]=E[d+(4*g+4)>>
2],e[g+2]=E[d+(4*g+8)>>2],e[g+3]=E[d+(4*g+12)>>2];else e=E.subarray(d>>2,d+16*b>>2);X.uniformMatrix2fv(S[a],!!c,e)},O:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],g=0;g<9*b;g+=9)e[g]=E[d+4*g>>2],e[g+1]=E[d+(4*g+4)>>2],e[g+2]=E[d+(4*g+8)>>2],e[g+3]=E[d+(4*g+12)>>2],e[g+4]=E[d+(4*g+16)>>2],e[g+5]=E[d+(4*g+20)>>2],e[g+6]=E[d+(4*g+24)>>2],e[g+7]=E[d+(4*g+28)>>2],e[g+8]=E[d+(4*g+32)>>2];else e=E.subarray(d>>2,d+36*b>>2);X.uniformMatrix3fv(S[a],!!c,e)},N:function(a,b,c,d){if(18>=b){var e=Y[16*b-1];d>>=
2;for(var g=0;g<16*b;g+=16){var h=d+g;e[g]=E[h];e[g+1]=E[h+1];e[g+2]=E[h+2];e[g+3]=E[h+3];e[g+4]=E[h+4];e[g+5]=E[h+5];e[g+6]=E[h+6];e[g+7]=E[h+7];e[g+8]=E[h+8];e[g+9]=E[h+9];e[g+10]=E[h+10];e[g+11]=E[h+11];e[g+12]=E[h+12];e[g+13]=E[h+13];e[g+14]=E[h+14];e[g+15]=E[h+15]}}else e=E.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(S[a],!!c,e)},ba:function(a){X.useProgram(Q[a])},z:function(a,b){X.vertexAttribDivisor(a,b)},C:function(a,b,c,d,e,g){X.vertexAttribPointer(a,b,c,!!d,e,g)},la:function(a,b,c,d){X.viewport(a,
b,c,d)},memory:pa,Oa:function(a){a=+a;return 0<=a?+Ma(a+.5):+La(a-.5)},Va:function(){},Ya:function(a,b,c,d){return $c(a,b,c,d)},table:qa};
(function(){function a(e){f.asm=e.exports;Oa--;f.monitorRunDependencies&&f.monitorRunDependencies(Oa);0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa&&(e=Qa,Qa=null,e()))}function b(e){a(e.instance)}function c(e){return Wa().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){t("failed to asynchronously prepare wasm: "+g);q(g)})}var d={a:hd};Oa++;f.monitorRunDependencies&&f.monitorRunDependencies(Oa);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return t("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(oa||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||Ra("file://")||"function"!==typeof fetch)return c(b);fetch(Sa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){t("wasm streaming compile failed: "+g);t("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var ab=f.___wasm_call_ctors=function(){return(ab=f.___wasm_call_ctors=f.asm.jb).apply(null,arguments)};
f._main=function(){return(f._main=f.asm.kb).apply(null,arguments)};
var y=f._malloc=function(){return(y=f._malloc=f.asm.lb).apply(null,arguments)},fd=f._free=function(){return(fd=f._free=f.asm.mb).apply(null,arguments)},ed=f.___errno_location=function(){return(ed=f.___errno_location=f.asm.nb).apply(null,arguments)},xa=f.stackAlloc=function(){return(xa=f.stackAlloc=f.asm.ob).apply(null,arguments)},dd=f.__ZSt18uncaught_exceptionv=function(){return(dd=f.__ZSt18uncaught_exceptionv=f.asm.pb).apply(null,arguments)};
f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.qb).apply(null,arguments)};f.dynCall_vii=function(){return(f.dynCall_vii=f.asm.rb).apply(null,arguments)};f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.sb).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.tb).apply(null,arguments)};f.dynCall_vifi=function(){return(f.dynCall_vifi=f.asm.ub).apply(null,arguments)};f.dynCall_vif=function(){return(f.dynCall_vif=f.asm.vb).apply(null,arguments)};
f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.wb).apply(null,arguments)};f.dynCall_iii=function(){return(f.dynCall_iii=f.asm.xb).apply(null,arguments)};var oc=f.dynCall_iiii=function(){return(oc=f.dynCall_iiii=f.asm.yb).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.zb).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.Ab).apply(null,arguments)};f.dynCall_vf=function(){return(f.dynCall_vf=f.asm.Bb).apply(null,arguments)};
f.dynCall_viiiiiiii=function(){return(f.dynCall_viiiiiiii=f.asm.Cb).apply(null,arguments)};f.dynCall_viiiiiii=function(){return(f.dynCall_viiiiiii=f.asm.Db).apply(null,arguments)};f.dynCall_viif=function(){return(f.dynCall_viif=f.asm.Eb).apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return(f.dynCall_viiiiiiiii=f.asm.Fb).apply(null,arguments)};f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm.Gb).apply(null,arguments)};
f.dynCall_vifii=function(){return(f.dynCall_vifii=f.asm.Hb).apply(null,arguments)};f.dynCall_viifi=function(){return(f.dynCall_viifi=f.asm.Ib).apply(null,arguments)};f.dynCall_viiiiiiiif=function(){return(f.dynCall_viiiiiiiif=f.asm.Jb).apply(null,arguments)};f.dynCall_viiiiif=function(){return(f.dynCall_viiiiif=f.asm.Kb).apply(null,arguments)};f.dynCall_viiifii=function(){return(f.dynCall_viiifii=f.asm.Lb).apply(null,arguments)};
f.dynCall_viiiiffffiif=function(){return(f.dynCall_viiiiffffiif=f.asm.Mb).apply(null,arguments)};f.dynCall_viiiifffffifi=function(){return(f.dynCall_viiiifffffifi=f.asm.Nb).apply(null,arguments)};f.dynCall_viffiii=function(){return(f.dynCall_viffiii=f.asm.Ob).apply(null,arguments)};f.dynCall_viifii=function(){return(f.dynCall_viifii=f.asm.Pb).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.Qb).apply(null,arguments)};
f.dynCall_fiii=function(){return(f.dynCall_fiii=f.asm.Rb).apply(null,arguments)};f.dynCall_fiiiiiiiiii=function(){return(f.dynCall_fiiiiiiiiii=f.asm.Sb).apply(null,arguments)};f.dynCall_fiiii=function(){return(f.dynCall_fiiii=f.asm.Tb).apply(null,arguments)};f.dynCall_fiiiiiiiii=function(){return(f.dynCall_fiiiiiiiii=f.asm.Ub).apply(null,arguments)};f.dynCall_iifif=function(){return(f.dynCall_iifif=f.asm.Vb).apply(null,arguments)};
f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.Wb).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.Xb).apply(null,arguments)};f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.Yb).apply(null,arguments)};f.dynCall_fiifii=function(){return(f.dynCall_fiifii=f.asm.Zb).apply(null,arguments)};f.dynCall_fiiifii=function(){return(f.dynCall_fiiifii=f.asm._b).apply(null,arguments)};
f.dynCall_fiiiii=function(){return(f.dynCall_fiiiii=f.asm.$b).apply(null,arguments)};f.dynCall_viiif=function(){return(f.dynCall_viiif=f.asm.ac).apply(null,arguments)};f.dynCall_fi=function(){return(f.dynCall_fi=f.asm.bc).apply(null,arguments)};f.dynCall_fif=function(){return(f.dynCall_fif=f.asm.cc).apply(null,arguments)};f.dynCall_iiif=function(){return(f.dynCall_iiif=f.asm.dc).apply(null,arguments)};f.dynCall_iiiiiii=function(){return(f.dynCall_iiiiiii=f.asm.ec).apply(null,arguments)};
f.dynCall_iiiiiiiiiii=function(){return(f.dynCall_iiiiiiiiiii=f.asm.fc).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.gc).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.hc).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.ic).apply(null,arguments)};f.dynCall_iiiiid=function(){return(f.dynCall_iiiiid=f.asm.jc).apply(null,arguments)};
f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.kc).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.lc).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.mc).apply(null,arguments)};var id;function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function jd(){id||kd();id||(Qa=jd)};
function kd(a){function b(){if(!id&&(id=!0,f.calledRun=!0,!ra)){f.noFSInit||Qb||(Qb=!0,Pb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Sb("stdin",f.stdin):Lb("/dev/tty","/dev/stdin"),f.stdout?Sb("stdout",null,f.stdout):Lb("/dev/tty","/dev/stdout"),f.stderr?Sb("stderr",null,f.stderr):Lb("/dev/tty1","/dev/stderr"),Mb("/dev/stdin","r"),Mb("/dev/stdout","w"),Mb("/dev/stderr","w"));Da(Fa);vb=!1;Da(Ga);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(ld){var c=a,d=f._main;c=c||[];
var e=c.length+1,g=xa(4*(e+1));z[g>>2]=wa(ca);for(var h=1;h<e;h++)z[(g>>2)+h]=wa(c[h-1]);z[(g>>2)+e]=0;try{var p=d(e,g);gd(p,!0)}catch(r){r instanceof ma||("unwind"==r?noExitRuntime=!0:((c=r)&&"object"===typeof r&&r.stack&&(c=[r,r.stack]),t("exception thrown: "+c),da(1,r)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ia.unshift(c);Da(Ia)}}a=a||ba;if(!(0<Oa)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ja();
Da(Ea);0<Oa||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=kd;function gd(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(ra=!0,f.onExit))f.onExit(a);da(a,new ma(a))}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var ld=!0;f.noInitialRun&&(ld=!1);noExitRuntime=!0;kd();
