var aa,f;var h,k;var m;m||(m=typeof Module !== 'undefined' ? Module : {});var ba={},n;for(n in m)m.hasOwnProperty(n)&&(ba[n]=m[n]);m.arguments=[];m.thisProgram="./this.program";m.quit=function(a,b){throw b;};m.preRun=[];m.postRun=[];var ca=!1,p=!1,q=!1,da=!1;ca="object"===typeof window;p="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!ca&&!p;da=!ca&&!q&&!p;var t="";
if(q){t=__dirname+"/";var fa,ha;m.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};m.readBinary=function(a){a=m.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(m.thisProgram=process.argv[1].replace(/\\/g,"/"));m.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=m);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",
u);m.quit=function(a){process.exit(a)};m.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(m.read=function(a){return read(a)}),m.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m.arguments=scriptArgs:"undefined"!=typeof arguments&&(m.arguments=arguments),"function"===typeof quit&&(m.quit=function(a){quit(a)});else if(ca||p)p?
t=self.location.href:document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?t.substr(0,t.lastIndexOf("/")+1):"",m.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(m.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),m.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},m.setWindowTitle=function(a){document.title=a};var ja=m.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),w=m.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ja);for(n in ba)ba.hasOwnProperty(n)&&(m[n]=ba[n]);ba=void 0;function ka(a){var b=y[la>>2];a=b+a+15&-16;if(a<=ma())y[la>>2]=a;else return 0;return b}
var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&w("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||u("Assertion failed: "+b)}function qa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=z(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)y[a>>2]=0;for(b=d+c;a<b;)B[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}
var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?sa(C,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var r=a.charCodeAt(++g);l=65536+((l&1023)<<10)|r&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ua(a){var b=ta(a)+1,c=va(b);E(a,B,c,b);return c}var buffer,B,C,wa,xa,y,ya,F,G,la=102912,za=m.TOTAL_MEMORY||16777216;5242880>za&&w("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+za+"! (TOTAL_STACK=5242880)");
m.buffer?buffer=m.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(oa=new WebAssembly.Memory({initial:za/65536,maximum:za/65536}),buffer=oa.buffer):buffer=new ArrayBuffer(za);m.HEAP8=B=new Int8Array(buffer);m.HEAP16=wa=new Int16Array(buffer);m.HEAP32=y=new Int32Array(buffer);m.HEAPU8=C=new Uint8Array(buffer);m.HEAPU16=xa=new Uint16Array(buffer);m.HEAPU32=ya=new Uint32Array(buffer);m.HEAPF32=F=new Float32Array(buffer);m.HEAPF64=G=new Float64Array(buffer);y[la>>2]=5346048;
function Aa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.gd;"number"===typeof c?void 0===b.Dd?m.dynCall_v(c):m.dynCall_vi(c,b.Dd):c(void 0===b.Dd?null:b.Dd)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[],Ga=!1;
function Ha(){Ga||(Ga=!0,m.noFSInit||Ia||(Ia=!0,Ja(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?Ka("stdin",m.stdin):La("/dev/tty","/dev/stdin"),m.stdout?Ka("stdout",null,m.stdout):La("/dev/tty","/dev/stdout"),m.stderr?Ka("stderr",null,m.stderr):La("/dev/tty1","/dev/stderr"),Ma("/dev/stdin","r"),Ma("/dev/stdout","w"),Ma("/dev/stderr","w")),Aa(Ca))}function Na(){var a=m.preRun.shift();Ba.unshift(a)}var Oa=Math.abs,Pa=Math.ceil,Qa=Math.floor,Ra=Math.min,H=0,Sa=null,Ta=null;
m.preloadedImages={};m.preloadedAudios={};function Ua(){var a=I;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var I="magnum-bullet.wasm";if(!Ua()){var Va=I;I=m.locateFile?m.locateFile(Va,t):t+Va}function Wa(){try{if(m.wasmBinary)return new Uint8Array(m.wasmBinary);if(m.readBinary)return m.readBinary(I);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function Xa(){return m.wasmBinary||!ca&&!p||"function"!==typeof fetch?new Promise(function(a){a(Wa())}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}
function Ya(a){function b(a){m.asm=a.exports;H--;m.monitorRunDependencies&&m.monitorRunDependencies(H);0==H&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta&&(a=Ta,Ta=null,a()))}function c(a){b(a.instance)}function d(a){Xa().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){w("failed to asynchronously prepare wasm: "+a);u(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};H++;m.monitorRunDependencies&&m.monitorRunDependencies(H);if(m.instantiateWasm)try{return m.instantiateWasm(e,
b)}catch(g){return w("Module.instantiateWasm callback failed with error: "+g),!1}m.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ua()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(I,{credentials:"same-origin"}),e).then(c,function(a){w("wasm streaming compile failed: "+a);w("falling back to ArrayBuffer instantiation");d(c)});return{}}
m.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:1499,maximum:1499,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Ya(b)};
var $a=[function(){var a=m.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?qa(Za(a.id)):0},function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?m.dynCall_ii.apply(null,[a].concat(e)):m.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(a){a=D(a);return"undefined"!==typeof process&&a in process.env?qa(Za(process.env[a])):0}];
Ca.push({gd:function(){ab()}},{gd:function(){bb()}},{gd:function(){cb()}},{gd:function(){db()}},{gd:function(){eb()}},{gd:function(){fb()}});var J={};
function gb(a){if(gb.Nc){var b=y[a>>2];var c=y[b>>2]}else gb.Nc=!0,J.USER=J.LOGNAME="web_user",J.PATH="/",J.PWD="/",J.HOME="/home/web_user",J.LANG="C.UTF-8",J._=m.thisProgram,c=Ga?z(1024):ka(1024),b=Ga?z(256):ka(256),y[b>>2]=c,y[a>>2]=b;a=[];var d=0,e;for(e in J)if("string"===typeof J[e]){var g=e+"="+J[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=a[e];for(var l=c,r=0;r<d.length;++r)B[l++>>0]=d.charCodeAt(r);B[l>>0]=0;y[b+4*
e>>2]=c;c+=g.length+1}y[b+4*a.length>>2]=0}function hb(a){m.___errno_location&&(y[m.___errno_location()>>2]=a);return a}function ib(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function jb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ib(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function kb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function lb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function mb(){var a=Array.prototype.slice.call(arguments,0);return jb(a.join("/"))}function K(a,b){return jb(a+"/"+b)}
function nb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ib(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ob=[];function pb(a,b){ob[a]={input:[],output:[],hd:b};qb(a,sb)}
var sb={open:function(a){var b=ob[a.node.rdev];if(!b)throw new L(M.Cd);a.tty=b;a.seekable=!1},close:function(a){a.tty.hd.flush(a.tty)},flush:function(a){a.tty.hd.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.hd.be)throw new L(M.Pd);for(var e=0,g=0;g<d;g++){try{var l=a.tty.hd.be(a.tty)}catch(r){throw new L(M.Nd);}if(void 0===l&&0===e)throw new L(M.ie);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.hd.Id)throw new L(M.Pd);
try{for(var e=0;e<d;e++)a.tty.hd.Id(a.tty,b[c+e])}catch(g){throw new L(M.Nd);}d&&(a.node.timestamp=Date.now());return e}},tb={be:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},Id:function(a,b){null===b||10===b?(ja(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(sa(a.output,0)),a.output=[])}},ub={Id:function(a,b){null===b||10===b?(w(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(w(sa(a.output,0)),a.output=[])}},O={Uc:null,Oc:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(M.me);O.Uc||(O.Uc={dir:{node:{Xc:O.Gc.Xc,Rc:O.Gc.Rc,lookup:O.Gc.lookup,od:O.Gc.od,rename:O.Gc.rename,unlink:O.Gc.unlink,rmdir:O.Gc.rmdir,readdir:O.Gc.readdir,symlink:O.Gc.symlink},stream:{Zc:O.Fc.Zc}},file:{node:{Xc:O.Gc.Xc,Rc:O.Gc.Rc},stream:{Zc:O.Fc.Zc,read:O.Fc.read,write:O.Fc.write,Rd:O.Fc.Rd,de:O.Fc.de,
xd:O.Fc.xd}},link:{node:{Xc:O.Gc.Xc,Rc:O.Gc.Rc,readlink:O.Gc.readlink},stream:{}},Td:{node:{Xc:O.Gc.Xc,Rc:O.Gc.Rc},stream:vb}});c=wb(a,b,c,d);16384===(c.mode&61440)?(c.Gc=O.Uc.dir.node,c.Fc=O.Uc.dir.stream,c.Ec={}):32768===(c.mode&61440)?(c.Gc=O.Uc.file.node,c.Fc=O.Uc.file.stream,c.Hc=0,c.Ec=null):40960===(c.mode&61440)?(c.Gc=O.Uc.link.node,c.Fc=O.Uc.link.stream):8192===(c.mode&61440)&&(c.Gc=O.Uc.Td.node,c.Fc=O.Uc.Td.stream);c.timestamp=Date.now();a&&(a.Ec[b]=c);return c},Wg:function(a){if(a.Ec&&
a.Ec.subarray){for(var b=[],c=0;c<a.Hc;++c)b.push(a.Ec[c]);return b}return a.Ec},Xg:function(a){return a.Ec?a.Ec.subarray?a.Ec.subarray(0,a.Hc):new Uint8Array(a.Ec):new Uint8Array},Wd:function(a,b){var c=a.Ec?a.Ec.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Ec,a.Ec=new Uint8Array(b),0<a.Hc&&a.Ec.set(c.subarray(0,a.Hc),0))},Ge:function(a,b){if(a.Hc!=b)if(0==b)a.Ec=null,a.Hc=0;else{if(!a.Ec||a.Ec.subarray){var c=a.Ec;a.Ec=new Uint8Array(new ArrayBuffer(b));c&&
a.Ec.set(c.subarray(0,Math.min(b,a.Hc)))}else if(a.Ec||(a.Ec=[]),a.Ec.length>b)a.Ec.length=b;else for(;a.Ec.length<b;)a.Ec.push(0);a.Hc=b}},Gc:{Xc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Hc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.bd=4096;b.blocks=Math.ceil(b.size/
b.bd);return b},Rc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Ge(a,b.size)},lookup:function(){throw xb[M.ke];},od:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=yb(b,c)}catch(g){}if(d)for(var e in d.Ec)throw new L(M.Od);}delete a.parent.Ec[a.name];a.name=c;b.Ec[c]=a;a.parent=b},unlink:function(a,b){delete a.Ec[b]},rmdir:function(a,b){var c=yb(a,b),d;for(d in c.Ec)throw new L(M.Od);
delete a.Ec[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Ec)a.Ec.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(M.Qc);return a.link}},Fc:{read:function(a,b,c,d,e){var g=a.node.Ec;if(e>=a.node.Hc)return 0;a=Math.min(a.node.Hc-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.Ec||a.Ec.subarray)){if(g)return a.Ec=b.subarray(c,c+d),a.Hc=d;if(0===a.Hc&&0===e)return a.Ec=new Uint8Array(b.subarray(c,c+d)),a.Hc=d;if(e+d<=a.Hc)return a.Ec.set(b.subarray(c,c+d),e),d}O.Wd(a,e+d);if(a.Ec.subarray&&b.subarray)a.Ec.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Ec[e+g]=b[c+g];a.Hc=Math.max(a.Hc,e+d);return d},Zc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Hc);if(0>b)throw new L(M.Qc);return b},Rd:function(a,
b,c){O.Wd(a.node,b+c);a.node.Hc=Math.max(a.node.Hc,b+c)},de:function(a,b,c,d,e,g,l){if(32768!==(a.node.mode&61440))throw new L(M.Cd);c=a.node.Ec;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.Hc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=z(d);if(!d)throw new L(M.le);b.set(c,d)}else a=!1,d=c.byteOffset;return{dh:d,oe:a}},xd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(M.Cd);if(e&2)return 0;O.Fc.write(a,b,0,d,c,!1);return 0}}},P={vd:!1,
Ie:function(){P.vd=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.Yd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Sd:function(a){return Buffer.Nc?Buffer.from(a):new Buffer(a)},Oc:function(a){assert(q);return P.createNode(null,"/",P.ae(a.Hd.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(M.Qc);a=wb(a,b,c);a.Gc=P.Gc;a.Fc=P.Fc;return a},ae:function(a){try{var b=
fs.lstatSync(a);P.vd&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(M[c.code]);}return b.mode},Pc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Oc.Hd.root);b.reverse();return mb.apply(null,b)},ue:function(a){a&=-2656257;var b=0,c;for(c in P.Yd)a&c&&(b|=P.Yd[c],a^=c);if(a)throw new L(M.Qc);return b},Gc:{Xc:function(a){a=P.Pc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(M[c.code]);}P.vd&&!b.bd&&(b.bd=4096);P.vd&&!b.blocks&&
(b.blocks=(b.size+b.bd-1)/b.bd|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,bd:b.bd,blocks:b.blocks}},Rc:function(a,b){var c=P.Pc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(M[d.code]);}},lookup:function(a,b){var c=K(P.Pc(a),b);c=P.ae(c);return P.createNode(a,b,c)},od:function(a,b,c,d){a=P.createNode(a,
b,c,d);b=P.Pc(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new L(M[e.code]);}return a},rename:function(a,b,c){a=P.Pc(a);b=K(P.Pc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(M[d.code]);}},unlink:function(a,b){a=K(P.Pc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(M[c.code]);}},rmdir:function(a,b){a=K(P.Pc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(M[c.code]);
}},readdir:function(a){a=P.Pc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(M[b.code]);}},symlink:function(a,b,c){a=K(P.Pc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(M[d.code]);}},readlink:function(a){var b=P.Pc(a);try{return b=fs.readlinkSync(b),b=zb.relative(zb.resolve(a.Oc.Hd.root),b)}catch(c){if(!c.code)throw c;throw new L(M[c.code]);}}},Fc:{open:function(a){var b=P.Pc(a.node);try{32768===(a.node.mode&61440)&&(a.pd=fs.openSync(b,P.ue(a.flags)))}catch(c){if(!c.code)throw c;
throw new L(M[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.pd&&fs.closeSync(a.pd)}catch(b){if(!b.code)throw b;throw new L(M[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.pd,P.Sd(b.buffer),c,d,e)}catch(g){throw new L(M[g.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.pd,P.Sd(b.buffer),c,d,e)}catch(g){throw new L(M[g.code]);}},Zc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.pd).size}catch(d){throw new L(M[d.code]);
}if(0>b)throw new L(M.Qc);return b}}},Ab=null,Bb={},Cb=[],Db=1,Eb=null,Fb=!0,Gb={},L=null,xb={};
function Q(a,b){a=nb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Zd:!0,Jd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Jd)throw new L(40);a=ib(a.split("/").filter(function(a){return!!a}),!1);var e=Ab;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=yb(e,a[d]);c=K(c,a[d]);e.wd&&(!g||g&&b.Zd)&&(e=e.wd.root);if(!g||b.Ed)for(g=0;40960===(e.mode&61440);)if(e=Hb(c),c=nb(kb(c),e),e=Q(c,{Jd:b.Jd}).node,40<g++)throw new L(40);}return{path:c,node:e}}
function Ib(a){for(var b;;){if(a===a.parent)return a=a.Oc.ee,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Eb.length}function Kb(a){var b=Jb(a.parent.id,a.name);a.De=Eb[b];Eb[b]=a}function yb(a,b){var c;if(c=(c=Lb(a,"x"))?c:a.Gc.lookup?0:13)throw new L(c,a);for(c=Eb[Jb(a.id,b)];c;c=c.De){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Gc.lookup(a,b)}
function wb(a,b,c,d){Mb||(Mb=function(a,b,c,d){a||(a=this);this.parent=a;this.Oc=a.Oc;this.wd=null;this.id=Db++;this.name=b;this.mode=c;this.Gc={};this.Fc={};this.rdev=d},Mb.prototype={},Object.defineProperties(Mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Mb(a,b,c,d);Kb(a);return a}
var Nb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Lb(a,b){if(Fb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Pb(a,b){try{return yb(a,b),17}catch(c){}return Lb(a,"wx")}
function Qb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Cb[a])return a;throw new L(24);}function Rb(a,b){Sb||(Sb=function(){},Sb.prototype={},Object.defineProperties(Sb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Sb,d;for(d in a)c[d]=a[d];a=c;b=Qb(b);a.fd=b;return Cb[b]=a}var vb={open:function(a){a.Fc=Bb[a.node.rdev].Fc;a.Fc.open&&a.Fc.open(a)},Zc:function(){throw new L(29);}};function qb(a,b){Bb[a]={Fc:b}}
function Tb(a,b){var c="/"===b,d=!b;if(c&&Ab)throw new L(16);if(!c&&!d){var e=Q(b,{Zd:!1});b=e.path;e=e.node;if(e.wd)throw new L(16);if(16384!==(e.mode&61440))throw new L(20);}b={type:a,Hd:{},ee:b,Ce:[]};a=a.Oc(b);a.Oc=b;b.root=a;c?Ab=a:e&&(e.wd=b,e.Oc&&e.Oc.Ce.push(b))}function Ub(a,b,c){var d=Q(a,{parent:!0}).node;a=lb(a);if(!a||"."===a||".."===a)throw new L(22);var e=Pb(d,a);if(e)throw new L(e);if(!d.Gc.od)throw new L(1);return d.Gc.od(d,a,b,c)}function R(a){Ub(a,16895,0)}
function Vb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ub(a,b|8192,c)}function La(a,b){if(!nb(a))throw new L(2);var c=Q(b,{parent:!0}).node;if(!c)throw new L(2);b=lb(b);var d=Pb(c,b);if(d)throw new L(d);if(!c.Gc.symlink)throw new L(1);c.Gc.symlink(c,b,a)}function Hb(a){a=Q(a).node;if(!a)throw new L(2);if(!a.Gc.readlink)throw new L(22);return nb(Ib(a.parent),a.Gc.readlink(a))}
function Ma(a,b,c,d){if(""===a)throw new L(2);if("string"===typeof b){var e=Nb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=jb(a);try{g=Q(a,{Ed:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(g){if(b&128)throw new L(17);}else g=Ub(a,c,0),e=!0;if(!g)throw new L(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new L(20);if(!e&&(c=g?40960===(g.mode&61440)?40:
16384===(g.mode&61440)&&("r"!==Ob(b)||b&512)?21:Lb(g,Ob(b)):2))throw new L(c);if(b&512){c=g;var l;"string"===typeof c?l=Q(c,{Ed:!0}).node:l=c;if(!l.Gc.Rc)throw new L(1);if(16384===(l.mode&61440))throw new L(21);if(32768!==(l.mode&61440))throw new L(22);if(c=Lb(l,"w"))throw new L(c);l.Gc.Rc(l,{size:0,timestamp:Date.now()})}b&=-641;d=Rb({node:g,path:Ib(g),flags:b,seekable:!0,position:0,Fc:g.Fc,Ne:[],error:!1},d);d.Fc.open&&d.Fc.open(d);!m.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Gb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Gb.onOpenFile(a,g))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function Xb(a,b,c){if(null===a.fd)throw new L(9);if(!a.seekable||!a.Fc.Zc)throw new L(29);if(0!=c&&1!=c&&2!=c)throw new L(22);a.position=a.Fc.Zc(a,b,c);a.Ne=[]}
function Ja(){L||(L=function(a,b){this.node=b;this.He=function(a){this.Wc=a};this.He(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[2].forEach(function(a){xb[a]=new L(a);xb[a].stack="<generic error, no stack>"}))}var Ia;function Yb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ka(a,b,c){a=K("/dev",a);var d=Yb(!!b,!!c);Zb||(Zb=64);var e=Zb++<<8|0;qb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,l=0;l<e;l++){try{var r=b()}catch(N){throw new L(5);}if(void 0===r&&0===g)throw new L(11);if(null===r||void 0===r)break;g++;c[d+l]=r}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(A){throw new L(5);}e&&(a.node.timestamp=Date.now());return g}});
Vb(a,d,e)}
var Zb,U={},Mb,Sb,Wb,M={me:1,ke:2,Gg:3,yf:4,Nd:5,Pd:6,Oe:7,Zf:8,je:9,cf:10,ie:11,Qg:11,le:12,he:13,rf:14,kg:15,af:16,qf:17,Rg:18,Cd:19,mg:20,Af:21,Qc:22,Uf:23,Mf:24,ed:25,Ng:26,sf:27,gg:28,Fg:29,Cg:30,Nf:31,vg:32,mf:33,zg:34,cg:42,vf:43,df:44,Cf:45,Df:46,Ef:47,Kf:48,Og:49,Xf:50,Bf:51,jf:35,$f:37,Ue:52,Xe:53,Sg:54,Vf:55,Ye:56,Ze:57,kf:35,$e:59,ig:60,Yf:61,Kg:62,hg:63,dg:64,eg:65,Bg:66,ag:67,Re:68,Hg:69,ef:70,wg:71,Pf:72,nf:73,We:74,qg:76,Ve:77,Ag:78,Ff:79,Gf:80,Jf:81,If:82,Hf:83,jg:38,Od:39,Qf:36,
Lf:40,rg:95,ug:96,hf:104,Wf:105,Se:97,yg:91,og:88,fg:92,Dg:108,gf:111,Pe:98,ff:103,Tf:101,Rf:100,Lg:110,tf:112,uf:113,xf:115,Te:114,lf:89,Of:90,xg:93,Eg:94,Qe:99,Sf:102,zf:106,lg:107,Mg:109,Pg:87,pf:122,Ig:116,pg:95,bg:123,wf:84,sg:75,bf:125,ng:131,tg:130,Jg:86},$b={},V=0;function W(){V+=4;return y[V-4>>2]}function ac(){var a=Cb[W()];if(!a)throw new L(M.je);return a}function bc(){u()}var cc=0,dc=0,X=0,ec=0,fc=null,hc=null,ic=!1;function jc(){for(var a=Y.length-1;0<=a;--a)kc(a);Y=[];lc=[]}var lc=[];
function mc(){if(nc&&oc.jd)for(var a=0;a<lc.length;++a){var b=lc[a];lc.splice(a,1);--a;b.fh.apply(this,b.Tg)}}var nc=0,oc=null,Y=[];function pc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function kc(a){var b=Y[a];b.target.removeEventListener(b.cd,b.te,b.rd);Y.splice(a,1)}
function qc(a){function b(b){++nc;oc=a;mc();a.ud(b);mc();--nc}if(a.td)a.te=b,a.target.addEventListener(a.cd,b,a.rd),Y.push(a),ic||(Ea.push(jc),ic=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].cd==a.cd&&kc(c--)}var rc={},sc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function tc(a){try{if(!a)return window;"number"===typeof a&&(a=sc[a]||D(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?m.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function uc(a){"number"===typeof a&&(a=D(a));return a&&"#canvas"!==a?"undefined"!==typeof h&&h.yd[a]?h.yd[a]:tc(a):"undefined"!==typeof h&&h.yd.canvas?h.yd.canvas:m.canvas}function ma(){return B.length}function vc(){u("OOM")}
function wc(a,b,c,d,e,g){cc||(cc=z(164));a={target:tc(a),jd:pc()?!1:!0,cd:g,td:d,ud:function(a){a=a||window.event;var c=cc;E(a.key?a.key:"",C,c+0,32);E(a.code?a.code:"",C,c+32,32);y[c+64>>2]=a.location;y[c+68>>2]=a.ctrlKey;y[c+72>>2]=a.shiftKey;y[c+76>>2]=a.altKey;y[c+80>>2]=a.metaKey;y[c+84>>2]=a.repeat;E(a.locale?a.locale:"",C,c+88,32);E(a.char?a.char:"",C,c+120,32);y[c+152>>2]=a.charCode;y[c+156>>2]=a.keyCode;y[c+160>>2]=a.which;xc(d,e,c,b)&&a.preventDefault()},rd:c};qc(a)}
function yc(a,b,c){G[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();y[a+8>>2]=b.screenX;y[a+12>>2]=b.screenY;y[a+16>>2]=b.clientX;y[a+20>>2]=b.clientY;y[a+24>>2]=b.ctrlKey;y[a+28>>2]=b.shiftKey;y[a+32>>2]=b.altKey;y[a+36>>2]=b.metaKey;wa[a+40>>1]=b.button;wa[a+42>>1]=b.buttons;y[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-fc;y[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-hc;if(m.canvas){var d=m.canvas.getBoundingClientRect();
y[a+60>>2]=b.clientX-d.left;y[a+64>>2]=b.clientY-d.top}else y[a+60>>2]=0,y[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},y[a+52>>2]=b.clientX-d.left,y[a+56>>2]=b.clientY-d.top):(y[a+52>>2]=0,y[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(fc=b.screenX,hc=b.screenY)}
function zc(a,b,c,d,e,g){dc||(dc=z(72));a=tc(a);c={target:a,jd:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,cd:g,td:d,ud:function(c){c=c||window.event;yc(dc,c,a);xc(d,e,dc,b)&&c.preventDefault()},rd:c};pc()&&"mousedown"==g&&(c.jd=!1);qc(c)}
function Ac(a,b,c,d){ec||(ec=z(36));a=tc(a);qc({target:a,jd:!1,cd:"resize",td:d,ud:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=ec;y[l>>2]=c.detail;y[l+4>>2]=document.body.clientWidth;
y[l+8>>2]=document.body.clientHeight;y[l+12>>2]=window.innerWidth;y[l+16>>2]=window.innerHeight;y[l+20>>2]=window.outerWidth;y[l+24>>2]=window.outerHeight;y[l+28>>2]=e[0];y[l+32>>2]=e[1];xc(d,10,l,b)&&c.preventDefault()}},rd:c})}
function Bc(a,b,c,d,e){function g(c){c=c||window.event;yc(X,c,a);G[X+72>>3]=c.wheelDeltaX||0;G[X+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);G[X+88>>3]=0;y[X+96>>2]=0;xc(d,9,X,b)&&c.preventDefault()}function l(c){c=c||window.event;var e=X;yc(e,c,a);G[e+72>>3]=c.deltaX;G[e+80>>3]=c.deltaY;G[e+88>>3]=c.deltaZ;y[e+96>>2]=c.deltaMode;xc(d,9,e,b)&&c.preventDefault()}X||(X=z(104));qc({target:a,jd:!0,cd:e,td:d,ud:"wheel"==e?l:g,rd:c})}
function Cc(){if(!h.Mc||!h.Mc.Yc)return-3;if(!h.Mc.Yc.pe)return-1;if(!h.Mc.attributes.Xd)return-3;h.Mc.Yc.pe();return 0}
h={Ud:1,ld:0,sd:[],$g:{},Lc:[],$d:[],Kd:[],Md:[],Jc:[],Sc:[],Bd:[],Tc:{},Mc:null,yd:{},gh:[],qd:{},Ld:{},ge:4,we:function(){h.ce=new Float32Array(h.Vc);for(var a=0;a<h.Vc;a++)h.$c[a]=h.ce.subarray(0,a+1)},Ic:function(a){h.ld||(h.ld=a)},kd:function(a){for(var b=h.Ud++,c=a.length;c<b;c++)a[c]=null;return b},Vc:256,ce:null,$c:[0],ve:function(a,b,c,d){a="";for(var e=0;e<b;++e){var g=d?y[d+4*e>>2]:-1;a+=D(y[c+4*e>>2],0>g?void 0:g)}return a},createContext:function(a,b){return(a=a.getContext("webgl",b)||
a.getContext("experimental-webgl",b))&&h.Fe(a,b)},Fe:function(a,b){var c=z(8),d={handle:c,attributes:b,version:b.Ae,Yc:a};a.canvas&&(a.canvas.ne=d);h.Tc[c]=d;("undefined"===typeof b.Vd||b.Vd)&&h.xe(d);return c},Be:function(a){h.Mc=h.Tc[a];m.Ug=k=h.Mc&&h.Mc.Yc;return!(a&&!k)},getContext:function(a){return h.Tc[a]},se:function(a){h.Mc===h.Tc[a]&&(h.Mc=null);if("object"===typeof rc)for(var b=h.Tc[a].Yc.canvas,c=0;c<Y.length;++c)Y[c].target!=b||kc(c--);h.Tc[a]&&h.Tc[a].Yc.canvas&&(h.Tc[a].Yc.canvas.ne=
void 0);Dc(h.Tc[a]);h.Tc[a]=null},xe:function(a){a||(a=h.Mc);if(!a.ye){a.ye=!0;var b=a.Yc;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,g){c.drawElementsInstancedANGLE(a,b,d,e,g)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.Vg=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}},Ee:function(a){var b=h.Lc[a];a=h.qd[a]={Jc:{},Gd:0,md:-1,nd:-1};for(var c=a.Jc,d=k.getProgramParameter(b,35718),e=0;e<d;++e){var g=k.getActiveUniform(b,e),l=g.name;a.Gd=Math.max(a.Gd,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var r=k.getUniformLocation(b,l);if(r){var v=h.kd(h.Jc);c[l]=[g.size,v];h.Jc[v]=r;for(var x=1;x<g.size;++x)r=k.getUniformLocation(b,
l+"["+x+"]"),v=h.kd(h.Jc),h.Jc[v]=r}}}};var Ec=["default","low-power","high-performance"];function Fc(a){return h.Be(a)?0:-5}m._emscripten_webgl_make_context_current=Fc;function Gc(a){if(0===a)return 0;a=D(a);if(!J.hasOwnProperty(a))return 0;Gc.Nc&&Dc(Gc.Nc);a=J[a];var b=ta(a)+1,c=z(b);c&&E(a,B,c,b);Gc.Nc=c;return Gc.Nc}var Hc=[];function Ic(a,b,c,d){for(var e=0;e<a;e++){var g=k[c](),l=g&&h.kd(d);g?(g.name=l,d[l]=g):h.Ic(1282);y[b+4*e>>2]=l}}
function Jc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&h.Ic(1280);return;case 36345:d=0;break;case 34466:var e=k.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=k.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":h.Ic(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:h.Ic(1280);return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":y[b+4*a>>2]=e[a];break;case "Float":F[b+4*a>>2]=e[a];break;case "Boolean":B[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=e.name|0}catch(g){h.Ic(1280);w("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:h.Ic(1280);return}switch(c){case "Integer64":aa=
[d>>>0,(f=d,1<=+Oa(f)?0<f?(Ra(+Qa(f/4294967296),4294967295)|0)>>>0:~~+Pa((f-+(~~f>>>0))/4294967296)>>>0:0)];y[b>>2]=aa[0];y[b+4>>2]=aa[1];break;case "Integer":y[b>>2]=d;break;case "Float":F[b>>2]=d;break;case "Boolean":B[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else h.Ic(1281)}function Kc(a){var b=ta(a)+1,c=z(b);E(a,C,c,b);return c}var Lc={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Mc={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Nc(a,b,c,d,e){if(b=Lc[b]*Mc[a]){var g=h.ge;c=e+d*(c*b+g-1&-g);switch(a){case 5121:return C.subarray(e,c);case 5126:return F.subarray(e>>2,c>>2);case 5125:case 34042:return ya.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return xa.subarray(e>>1,c>>1);default:h.Ic(1280)}}else h.Ic(1280)}function Z(){Z.Nc||(Z.Nc=[]);Z.Nc.push(Oc());return Z.Nc.length-1}function Pc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Qc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Rc=[31,29,31,30,31,30,31,31,30,31,30,31],Sc=[31,28,31,30,31,30,31,31,30,31,30,31];function Tc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Pc(a.getFullYear())?Rc:Sc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Uc(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return e(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function v(a){a=Tc(new Date(a.Kc+1900,0,1),a.Ad);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=l(r(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var x=y[d+40>>2];d={Le:y[d>>2],Ke:y[d+4>>2],zd:y[d+8>>2],dd:y[d+12>>2],ad:y[d+16>>2],Kc:y[d+20>>2],fe:y[d+24>>2],Ad:y[d+28>>2],hh:y[d+32>>2],Je:y[d+36>>2],
Me:x?D(x):""};c=D(c);x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var A in x)c=c.replace(new RegExp(A,"g"),x[A]);var S="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),N="January February March April May June July August September October November December".split(" ");x={"%a":function(a){return S[a.fe].substring(0,3)},"%A":function(a){return S[a.fe]},"%b":function(a){return N[a.ad].substring(0,
3)},"%B":function(a){return N[a.ad]},"%C":function(a){return g((a.Kc+1900)/100|0,2)},"%d":function(a){return g(a.dd,2)},"%e":function(a){return e(a.dd,2," ")},"%g":function(a){return v(a).toString().substring(2)},"%G":function(a){return v(a)},"%H":function(a){return g(a.zd,2)},"%I":function(a){a=a.zd;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.dd+Qc(Pc(a.Kc+1900)?Rc:Sc,a.ad-1),3)},"%m":function(a){return g(a.ad+1,2)},"%M":function(a){return g(a.Ke,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.zd&&12>a.zd?"AM":"PM"},"%S":function(a){return g(a.Le,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Kc+1900,a.ad+1,a.dd,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Kc+1900,0,1),c=0===b.getDay()?b:Tc(b,7-b.getDay());a=new Date(a.Kc+1900,a.ad,a.dd);return 0>l(c,a)?g(Math.ceil((31-c.getDate()+(Qc(Pc(a.getFullYear())?Rc:Sc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.Kc+1900,0,4)),c=r(new Date(a.Kc+
1901,0,4)),d=Tc(new Date(a.Kc+1900,0,1),a.Ad);return 0>l(d,b)?"53":0>=l(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Kc+1900?a.Ad+32-b.getDate():a.Ad+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Kc+1900,a.ad+1,a.dd,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Kc,0,1),c=1===b.getDay()?b:Tc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Kc+1900,a.ad,a.dd);return 0>l(c,a)?g(Math.ceil((31-c.getDate()+(Qc(Pc(a.getFullYear())?Rc:Sc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":
"00"},"%y":function(a){return(a.Kc+1900).toString().substring(2)},"%Y":function(a){return a.Kc+1900},"%z":function(a){a=a.Je;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Me},"%%":function(){return"%"}};for(A in x)0<=c.indexOf(A)&&(c=c.replace(new RegExp(A,"g"),x[A](d)));A=Za(c,!1);if(A.length>b)return 0;B.set(A,a);return A.length-1}Ja();Eb=Array(4096);Tb(O,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");qb(259,{read:function(){return 0},write:function(a,b,c,l){return l}});Vb("/dev/null",259);pb(1280,tb);pb(1536,ub);Vb("/dev/tty",1280);Vb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(q)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});Ka("random",b);Ka("urandom",b);R("/dev/shm");
R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");Tb({Oc:function(){var a=wb("/proc/self","fd",16895,73);a.Gc={lookup:function(a,c){var b=Cb[+c];if(!b)throw new L(9);a={parent:null,Oc:{ee:"fake"},Gc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(q){var fs=require("fs"),zb=require("path");P.Ie()}
q?bc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?bc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?bc=function(){return performance.now()}:bc=Date.now;h.we();for(var Vc=0;32>Vc;Vc++)Hc.push(Array(Vc));function Za(a,b){var c=Array(ta(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var Zc=m.asm({},{c:u,ub:gb,e:function(a){return z(a)},Ja:function(){pa=!0;throw"Pure virtual function called!";},d:function(a){"uncaught_exception"in Wc?Wc.Qd++:Wc.Qd=1;throw a;},ua:function(){return!!Wc.Qd},k:function(){},ca:function(){hb(1);return-1},t:hb,s:function(a,b){V=b;try{var c=ac();W();var d=W(),e=W(),g=W();Xb(c,d,g);y[e>>2]=c.position;c.Fd&&0===d&&0===g&&(c.Fd=null);return 0}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.Wc}},tb:function(a,b){V=b;try{var c=ac(),d=W();a:{var e=
W();for(b=a=0;b<e;b++){var g=y[d+(8*b+4)>>2],l=c,r=y[d+8*b>>2],v=g,x=void 0,A=B;if(0>v||0>x)throw new L(22);if(null===l.fd)throw new L(9);if(1===(l.flags&2097155))throw new L(9);if(16384===(l.node.mode&61440))throw new L(21);if(!l.Fc.read)throw new L(22);var S="undefined"!==typeof x;if(!S)x=l.position;else if(!l.seekable)throw new L(29);var N=l.Fc.read(l,A,r,v,x);S||(l.position+=N);var ea=N;if(0>ea){var T=-1;break a}a+=ea;if(ea<g)break}T=a}return T}catch(rb){return"undefined"!==typeof U&&rb instanceof
L||u(rb),-rb.Wc}},D:function(a,b){V=b;try{var c=ac(),d=W();a:{var e=W();for(b=a=0;b<e;b++){var g=c,l=y[d+8*b>>2],r=y[d+(8*b+4)>>2],v=void 0,x=B;if(0>r||0>v)throw new L(22);if(null===g.fd)throw new L(9);if(0===(g.flags&2097155))throw new L(9);if(16384===(g.node.mode&61440))throw new L(21);if(!g.Fc.write)throw new L(22);g.flags&1024&&Xb(g,0,2);var A="undefined"!==typeof v;if(!A)v=g.position;else if(!g.seekable)throw new L(29);var S=g.Fc.write(g,x,l,r,v,void 0);A||(g.position+=S);try{if(g.path&&Gb.onWriteToFile)Gb.onWriteToFile(g.path)}catch(T){console.log("FS.trackingDelegate['onWriteToFile']('"+
g.path+"') threw an exception: "+T.message)}var N=S;if(0>N){var ea=-1;break a}a+=N}ea=a}return ea}catch(T){return"undefined"!==typeof U&&T instanceof L||u(T),-T.Wc}},l:function(a,b){V=b;try{var c=ac();switch(W()){case 0:var d=W();return 0>d?-M.Qc:Ma(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=W(),c.flags|=d,0;case 12:return d=W(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-M.Qc;case 9:return hb(M.Qc),-1;default:return-M.Qc}}catch(e){return"undefined"!==
typeof U&&e instanceof L||u(e),-e.Wc}},Wa:function(a,b){V=b;try{var c=D(W());var d=W();if(d&-8)var e=-M.Qc;else{var g=Q(c,{Ed:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Lb(g,a)?-M.he:0}return e}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.Wc}},Va:function(a,b){V=b;try{var c=D(W()),d=W(),e=W();return Ma(c,d,e).fd}catch(g){return"undefined"!==typeof U&&g instanceof L||u(g),-g.Wc}},B:function(a,b){V=b;try{var c=ac(),d=W();switch(d){case 21509:case 21505:return c.tty?
0:-M.ed;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-M.ed;case 21519:if(!c.tty)return-M.ed;var e=W();return y[e>>2]=0;case 21520:return c.tty?-M.Qc:-M.ed;case 21531:a=e=W();if(!c.Fc.ze)throw new L(25);return c.Fc.ze(c,d,a);case 21523:return c.tty?0:-M.ed;case 21524:return c.tty?0:-M.ed;default:u("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof U&&g instanceof L||u(g),-g.Wc}},A:function(a,b){V=b;try{var c=ac();if(null===c.fd)throw new L(9);c.Fd&&(c.Fd=
null);try{c.Fc.close&&c.Fc.close(c)}catch(d){throw d;}finally{Cb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.Wc}},Ua:function(a,b){V=b;try{var c=W(),d=W(),e=$b[c];if(!e)return 0;if(d===e.Yg){var g=Cb[e.fd],l=e.flags,r=new Uint8Array(C.subarray(c,c+d));g&&g.Fc.xd&&g.Fc.xd(g,r,0,d,l);$b[c]=null;e.oe&&Dc(e.Zg)}return 0}catch(v){return"undefined"!==typeof U&&v instanceof L||u(v),-v.Wc}},i:function(){},b:function(){m.abort()},Ta:function(a,b){if(0===a)a=
Date.now();else if(1===a&&(q||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=bc();else return hb(22),-1;y[b>>2]=a/1E3|0;y[b+4>>2]=a%1E3*1E6|0;return 0},Sa:function(a){return $a[a]()},Ra:function(a,b){return $a[a](b)},Qa:function(a,b,c){return $a[a](b,c)},Pa:function(a,b,c){a=uc(a);if(!a)return-4;y[b>>2]=a.width;y[c>>2]=a.height},Oa:function(){return window.devicePixelRatio||1},Na:function(a,b,c){a=a?tc(a):m.canvas;if(!a)return-4;a.getBoundingClientRect?
(a=a.getBoundingClientRect(),G[b>>3]=a.right-a.left,G[c>>3]=a.bottom-a.top):(G[b>>3]=a.clientWidth,G[c>>3]=a.clientHeight);return 0},Ma:ma,La:function(a,b,c){C.set(C.subarray(b,b+c),a)},Ka:function(a){vc(a)},z:function(a,b,c){a=uc(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ia:function(a,b,c,d){wc(a,b,c,d,2,"keydown");return 0},Ha:function(a,b,c,d){wc(a,b,c,d,3,"keyup");return 0},Ga:function(a,b,c,d){zc(a,b,c,d,5,"mousedown");return 0},Fa:function(a,b,c,d){zc(a,b,c,d,8,"mousemove");return 0},
Ea:function(a,b,c,d){zc(a,b,c,d,6,"mouseup");return 0},Da:function(a,b,c,d){Ac(a,b,c,d);return 0},Ca:function(a,b,c,d){a=tc(a);return"undefined"!==typeof a.onwheel?(Bc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Bc(a,b,c,d,"mousewheel"),0):-1},Ba:function(){return Cc()},Aa:function(a,b){var c={};b>>=2;c.alpha=!!y[b];c.depth=!!y[b+1];c.stencil=!!y[b+2];c.antialias=!!y[b+3];c.premultipliedAlpha=!!y[b+4];c.preserveDrawingBuffer=!!y[b+5];c.powerPreference=Ec[y[b+6]];c.failIfMajorPerformanceCaveat=
!!y[b+7];c.Ae=y[b+8];c.ah=y[b+9];c.Vd=y[b+10];c.Xd=y[b+11];c.bh=y[b+12];c.eh=y[b+13];a=uc(a);return!a||c.Xd?0:h.createContext(a,c)},za:function(a){h.Mc==a&&(h.Mc=0);h.se(a)},ya:function(a){a>>=2;for(var b=0;14>b;++b)y[a+b]=0;y[a]=y[a+1]=y[a+3]=y[a+4]=y[a+8]=y[a+10]=1},xa:Fc,y:function(a){Xc(a)},h:Gc,x:function(a){var b=Date.now();y[a>>2]=b/1E3|0;y[a+4>>2]=b%1E3*1E3|0;return 0},p:function(a){k.activeTexture(a)},wa:function(a,b){k.attachShader(h.Lc[a],h.Sc[b])},va:function(a,b,c){k.bindAttribLocation(h.Lc[a],
b,D(c))},w:function(a,b){k.bindBuffer(a,h.sd[b])},ta:function(a,b){k.bindFramebuffer(a,h.$d[b])},sa:function(a,b){k.bindRenderbuffer(a,h.Kd[b])},o:function(a,b){k.bindTexture(a,h.Md[b])},ra:function(a){k.bindVertexArray(h.Bd[a])},qa:function(a,b,c,d){k.bufferData(a,c?C.subarray(c,c+b):b,d)},pa:function(a,b,c,d){k.bufferSubData(a,b,C.subarray(d,d+c))},oa:function(a){return k.checkFramebufferStatus(a)},na:function(a){k.clear(a)},ma:function(a,b,c,d){k.clearColor(a,b,c,d)},la:function(a){k.clearDepth(a)},
ka:function(a){k.compileShader(h.Sc[a])},v:function(a,b,c,d,e,g,l,r,v){k.compressedTexSubImage2D(a,b,c,d,e,g,l,v?C.subarray(v,v+r):null)},ja:function(a,b,c,d,e,g,l,r){k.copyTexSubImage2D(a,b,c,d,e,g,l,r)},ia:function(){var a=h.kd(h.Lc),b=k.createProgram();b.name=a;h.Lc[a]=b;return a},ha:function(a){var b=h.kd(h.Sc);h.Sc[b]=k.createShader(a);return b},ga:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=h.sd[d];e&&(k.deleteBuffer(e),e.name=0,h.sd[d]=null,d==h.qe&&(h.qe=0),d==h.re&&(h.re=0))}},
fa:function(a){if(a){var b=h.Lc[a];b?(k.deleteProgram(b),b.name=0,h.Lc[a]=null,h.qd[a]=null):h.Ic(1281)}},ea:function(a){if(a){var b=h.Sc[a];b?(k.deleteShader(b),h.Sc[a]=null):h.Ic(1281)}},da:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];k.deleteVertexArray(h.Bd[d]);h.Bd[d]=null}},u:function(a){k.depthFunc(a)},ba:function(a){k.disableVertexAttribArray(a)},aa:function(a,b,c){k.drawArrays(a,b,c)},$:function(a,b,c,d){k.drawArraysInstanced(a,b,c,d)},_:function(a,b){for(var c=Hc[a],d=0;d<a;d++)c[d]=
y[b+4*d>>2];k.drawBuffers(c)},Z:function(a,b,c,d){k.drawElements(a,b,c,d)},Y:function(a,b,c,d,e){k.drawElementsInstanced(a,b,c,d,e)},n:function(a){k.enable(a)},X:function(a){k.enableVertexAttribArray(a)},W:function(a,b,c,d){k.framebufferRenderbuffer(a,b,c,h.Kd[d])},V:function(a,b,c,d,e){k.framebufferTexture2D(a,b,c,h.Md[d],e)},U:function(a,b){Ic(a,b,"createBuffer",h.sd)},T:function(a,b){Ic(a,b,"createFramebuffer",h.$d)},S:function(a,b){Ic(a,b,"createRenderbuffer",h.Kd)},R:function(a,b){Ic(a,b,"createTexture",
h.Md)},Q:function(a,b){Ic(a,b,"createVertexArray",h.Bd)},P:function(a){k.generateMipmap(a)},O:function(a,b,c){c?y[c>>2]=k.getBufferParameter(a,b):h.Ic(1281)},N:function(){if(h.ld){var a=h.ld;h.ld=0;return a}return k.getError()},M:function(a,b){Jc(a,b,"Float")},m:function(a,b){Jc(a,b,"Integer")},L:function(a,b,c,d){a=k.getProgramInfoLog(h.Lc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},r:function(a,b,c){if(c)if(a>=h.Ud)h.Ic(1281);else{var d=h.qd[a];if(d)if(35716==
b)a=k.getProgramInfoLog(h.Lc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b)y[c>>2]=d.Gd;else if(35722==b){if(-1==d.md){a=h.Lc[a];var e=k.getProgramParameter(a,35721);for(b=d.md=0;b<e;++b)d.md=Math.max(d.md,k.getActiveAttrib(a,b).name.length+1)}y[c>>2]=d.md}else if(35381==b){if(-1==d.nd)for(a=h.Lc[a],e=k.getProgramParameter(a,35382),b=d.nd=0;b<e;++b)d.nd=Math.max(d.nd,k.getActiveUniformBlockName(a,b).length+1);y[c>>2]=d.nd}else y[c>>2]=k.getProgramParameter(h.Lc[a],b);else h.Ic(1282)}else h.Ic(1281)},
K:function(a,b,c,d){a=k.getShaderInfoLog(h.Sc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},q:function(a,b,c){c?35716==b?(a=k.getShaderInfoLog(h.Sc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1):35720==b?(a=k.getShaderSource(h.Sc[a]),y[c>>2]=null===a||0==a.length?0:a.length+1):y[c>>2]=k.getShaderParameter(h.Sc[a],b):h.Ic(1281)},j:function(a){if(h.Ld[a])return h.Ld[a];switch(a){case 7939:var b=k.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),
c.push("GL_"+b[d]);b=Kc(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=k.getParameter(a))||h.Ic(1280);b=Kc(b);break;case 7938:b=Kc("OpenGL ES 2.0 ("+k.getParameter(k.VERSION)+")");break;case 35724:b=k.getParameter(k.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Kc(b);break;default:return h.Ic(1280),0}return h.Ld[a]=b},J:function(a,b){b=D(b);var c=0;if("]"==b[b.length-
1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=h.qd[a]&&h.qd[a].Jc[b])&&0<=c&&c<a[0]?a[1]+c:-1},I:function(a){k.linkProgram(h.Lc[a]);h.Ee(a)},H:function(a,b){3317==a&&(h.ge=b);k.pixelStorei(a,b)},G:function(a,b){k.polygonOffset(a,b)},F:function(a,b,c,d,e,g,l){(l=Nc(g,e,c,d,l))?k.readPixels(a,b,c,d,e,g,l):h.Ic(1280)},sb:function(a,b,c,d){k.renderbufferStorage(a,b,c,d)},rb:function(a,b,c,d){b=h.ve(a,b,c,d);k.shaderSource(h.Sc[a],b)},qb:function(a,b,c,d,e,
g,l,r,v){k.texImage2D(a,b,c,d,e,g,l,r,v?Nc(r,l,d,e,v):null)},pb:function(a,b,c){k.texParameterf(a,b,c)},ob:function(a,b,c){k.texParameterf(a,b,F[c>>2])},nb:function(a,b,c){k.texParameteri(a,b,c)},E:function(a,b,c,d,e,g,l,r,v){var x=null;v&&(x=Nc(r,l,e,g,v));k.texSubImage2D(a,b,c,d,e,g,l,r,x)},mb:function(a,b,c){if(b<=h.Vc)for(var d=h.$c[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);k.uniform1fv(h.Jc[a],d)},lb:function(a,b,c){k.uniform1iv(h.Jc[a],y.subarray(c>>2,c+4*b>>2))},kb:function(a,
b,c){if(2*b<=h.Vc)for(var d=h.$c[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);k.uniform2fv(h.Jc[a],d)},jb:function(a,b,c){k.uniform2iv(h.Jc[a],y.subarray(c>>2,c+8*b>>2))},ib:function(a,b,c){if(3*b<=h.Vc)for(var d=h.$c[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);k.uniform3fv(h.Jc[a],d)},hb:function(a,b,c){k.uniform3iv(h.Jc[a],y.subarray(c>>2,c+12*b>>2))},gb:function(a,b,c){if(4*
b<=h.Vc)for(var d=h.$c[4*b-1],e=0;e<4*b;e+=4)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2],d[e+3]=F[c+(4*e+12)>>2];else d=F.subarray(c>>2,c+16*b>>2);k.uniform4fv(h.Jc[a],d)},fb:function(a,b,c){k.uniform4iv(h.Jc[a],y.subarray(c>>2,c+16*b>>2))},eb:function(a,b,c,d){if(4*b<=h.Vc)for(var e=h.$c[4*b-1],g=0;g<4*b;g+=4)e[g]=F[d+4*g>>2],e[g+1]=F[d+(4*g+4)>>2],e[g+2]=F[d+(4*g+8)>>2],e[g+3]=F[d+(4*g+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);k.uniformMatrix2fv(h.Jc[a],!!c,e)},db:function(a,
b,c,d){if(9*b<=h.Vc)for(var e=h.$c[9*b-1],g=0;g<9*b;g+=9)e[g]=F[d+4*g>>2],e[g+1]=F[d+(4*g+4)>>2],e[g+2]=F[d+(4*g+8)>>2],e[g+3]=F[d+(4*g+12)>>2],e[g+4]=F[d+(4*g+16)>>2],e[g+5]=F[d+(4*g+20)>>2],e[g+6]=F[d+(4*g+24)>>2],e[g+7]=F[d+(4*g+28)>>2],e[g+8]=F[d+(4*g+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);k.uniformMatrix3fv(h.Jc[a],!!c,e)},cb:function(a,b,c,d){if(16*b<=h.Vc)for(var e=h.$c[16*b-1],g=0;g<16*b;g+=16)e[g]=F[d+4*g>>2],e[g+1]=F[d+(4*g+4)>>2],e[g+2]=F[d+(4*g+8)>>2],e[g+3]=F[d+(4*g+12)>>2],e[g+4]=
F[d+(4*g+16)>>2],e[g+5]=F[d+(4*g+20)>>2],e[g+6]=F[d+(4*g+24)>>2],e[g+7]=F[d+(4*g+28)>>2],e[g+8]=F[d+(4*g+32)>>2],e[g+9]=F[d+(4*g+36)>>2],e[g+10]=F[d+(4*g+40)>>2],e[g+11]=F[d+(4*g+44)>>2],e[g+12]=F[d+(4*g+48)>>2],e[g+13]=F[d+(4*g+52)>>2],e[g+14]=F[d+(4*g+56)>>2],e[g+15]=F[d+(4*g+60)>>2];else e=F.subarray(d>>2,d+64*b>>2);k.uniformMatrix4fv(h.Jc[a],!!c,e)},bb:function(a){k.useProgram(h.Lc[a])},ab:function(a,b){k.vertexAttribDivisor(a,b)},$a:function(a,b,c,d,e,g){k.vertexAttribPointer(a,b,c,!!d,e,g)},
_a:function(a,b,c,d){k.viewport(a,b,c,d)},g:function(a){var b=Z.Nc[a];Z.Nc.splice(a,1);Yc(b)},f:Z,C:function(){u("trap!")},Za:function(){return 0},Ya:function(a,b,c,d){return Uc(a,b,c,d)},Xa:vc,a:la},buffer);m.asm=Zc;
var cb=m.__GLOBAL__sub_I_btConeTwistConstraint_cpp=function(){return m.asm.vb.apply(null,arguments)},db=m.__GLOBAL__sub_I_btQuickprof_cpp=function(){return m.asm.wb.apply(null,arguments)},ab=m.__GLOBAL__sub_I_driverSpecific_cpp=function(){return m.asm.xb.apply(null,arguments)},fb=m.__GLOBAL__sub_I_iostream_cpp=function(){return m.asm.yb.apply(null,arguments)},bb=m.__GLOBAL__sub_I_resource_MagnumShaders_RCS_cpp=function(){return m.asm.zb.apply(null,arguments)},Wc=m.__ZSt18uncaught_exceptionv=function(){return m.asm.Ab.apply(null,
arguments)},eb=m.___emscripten_environ_constructor=function(){return m.asm.Bb.apply(null,arguments)};m.___errno_location=function(){return m.asm.Cb.apply(null,arguments)};var Dc=m._free=function(){return m.asm.Db.apply(null,arguments)};m._main=function(){return m.asm.Eb.apply(null,arguments)};
var z=m._malloc=function(){return m.asm.Fb.apply(null,arguments)},va=m.stackAlloc=function(){return m.asm.Bc.apply(null,arguments)},Yc=m.stackRestore=function(){return m.asm.Cc.apply(null,arguments)},Oc=m.stackSave=function(){return m.asm.Dc.apply(null,arguments)};m.dynCall_fi=function(){return m.asm.Gb.apply(null,arguments)};m.dynCall_fif=function(){return m.asm.Hb.apply(null,arguments)};m.dynCall_fiifii=function(){return m.asm.Ib.apply(null,arguments)};
m.dynCall_fiii=function(){return m.asm.Jb.apply(null,arguments)};m.dynCall_fiiifii=function(){return m.asm.Kb.apply(null,arguments)};m.dynCall_fiiii=function(){return m.asm.Lb.apply(null,arguments)};m.dynCall_fiiiii=function(){return m.asm.Mb.apply(null,arguments)};m.dynCall_fiiiiiiiii=function(){return m.asm.Nb.apply(null,arguments)};m.dynCall_fiiiiiiiiii=function(){return m.asm.Ob.apply(null,arguments)};m.dynCall_ii=function(){return m.asm.Pb.apply(null,arguments)};
m.dynCall_iifif=function(){return m.asm.Qb.apply(null,arguments)};m.dynCall_iii=function(){return m.asm.Rb.apply(null,arguments)};m.dynCall_iiif=function(){return m.asm.Sb.apply(null,arguments)};var xc=m.dynCall_iiii=function(){return m.asm.Tb.apply(null,arguments)};m.dynCall_iiiii=function(){return m.asm.Ub.apply(null,arguments)};m.dynCall_iiiiid=function(){return m.asm.Vb.apply(null,arguments)};m.dynCall_iiiiii=function(){return m.asm.Wb.apply(null,arguments)};
m.dynCall_iiiiiid=function(){return m.asm.Xb.apply(null,arguments)};m.dynCall_iiiiiii=function(){return m.asm.Yb.apply(null,arguments)};m.dynCall_iiiiiiii=function(){return m.asm.Zb.apply(null,arguments)};m.dynCall_iiiiiiiii=function(){return m.asm._b.apply(null,arguments)};m.dynCall_iiiiiiiiiii=function(){return m.asm.$b.apply(null,arguments)};m.dynCall_iiiiij=function(){return m.asm.ac.apply(null,arguments)};m.dynCall_v=function(){return m.asm.bc.apply(null,arguments)};
m.dynCall_vf=function(){return m.asm.cc.apply(null,arguments)};m.dynCall_vi=function(){return m.asm.dc.apply(null,arguments)};m.dynCall_vif=function(){return m.asm.ec.apply(null,arguments)};m.dynCall_viffiii=function(){return m.asm.fc.apply(null,arguments)};m.dynCall_vifi=function(){return m.asm.gc.apply(null,arguments)};m.dynCall_vifii=function(){return m.asm.hc.apply(null,arguments)};m.dynCall_vii=function(){return m.asm.ic.apply(null,arguments)};
m.dynCall_viif=function(){return m.asm.jc.apply(null,arguments)};m.dynCall_viifi=function(){return m.asm.kc.apply(null,arguments)};m.dynCall_viifii=function(){return m.asm.lc.apply(null,arguments)};m.dynCall_viii=function(){return m.asm.mc.apply(null,arguments)};m.dynCall_viiif=function(){return m.asm.nc.apply(null,arguments)};m.dynCall_viiifii=function(){return m.asm.oc.apply(null,arguments)};m.dynCall_viiii=function(){return m.asm.pc.apply(null,arguments)};
m.dynCall_viiiifffffifi=function(){return m.asm.qc.apply(null,arguments)};m.dynCall_viiiiffffiif=function(){return m.asm.rc.apply(null,arguments)};m.dynCall_viiiii=function(){return m.asm.sc.apply(null,arguments)};m.dynCall_viiiiif=function(){return m.asm.tc.apply(null,arguments)};m.dynCall_viiiiii=function(){return m.asm.uc.apply(null,arguments)};m.dynCall_viiiiiii=function(){return m.asm.vc.apply(null,arguments)};m.dynCall_viiiiiiii=function(){return m.asm.wc.apply(null,arguments)};
m.dynCall_viiiiiiiif=function(){return m.asm.xc.apply(null,arguments)};m.dynCall_viiiiiiiii=function(){return m.asm.yc.apply(null,arguments)};m.dynCall_viiiiiiiiii=function(){return m.asm.zc.apply(null,arguments)};m.dynCall_viijii=function(){return m.asm.Ac.apply(null,arguments)};m.asm=Zc;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ia.prototype=Error();ia.prototype.constructor=ia;Ta=function $c(){m.calledRun||ad();m.calledRun||(Ta=$c)};
m.callMain=function(a){a=a||[];Ha();var b=a.length+1,c=va(4*(b+1));y[c>>2]=ua(m.thisProgram);for(var d=1;d<b;d++)y[(c>>2)+d]=ua(a[d-1]);y[(c>>2)+b]=0;try{var e=m._main(b,c,0);Xc(e,!0)}catch(g){g instanceof ia||("SimulateInfiniteLoop"==g?m.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),w("exception thrown: "+a),m.quit(1,g)))}finally{}};
function ad(a){function b(){if(!m.calledRun&&(m.calledRun=!0,!pa)){Ha();Fb=!1;Aa(Da);if(m.onRuntimeInitialized)m.onRuntimeInitialized();m._main&&bd&&m.callMain(a);if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();Fa.unshift(b)}Aa(Fa)}}a=a||m.arguments;if(!(0<H)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Na();Aa(Ba);0<H||m.calledRun||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},
1);b()},1)):b())}}m.run=ad;function Xc(a,b){if(!b||!m.noExitRuntime||0!==a){if(!m.noExitRuntime&&(pa=!0,m.onExit))m.onExit(a);m.quit(a,new ia(a))}}function u(a){if(m.onAbort)m.onAbort(a);void 0!==a?(ja(a),w(a),a=JSON.stringify(a)):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}m.abort=u;if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();var bd=!0;m.noInitialRun&&(bd=!1);m.noExitRuntime=!0;ad();
