var aa,g;var h;h||(h=typeof Module !== 'undefined' ? Module : {});var ba={},l;for(l in h)h.hasOwnProperty(l)&&(ba[l]=h[l]);h.arguments=[];h.thisProgram="./this.program";h.quit=function(a,b){throw b;};h.preRun=[];h.postRun=[];var ca=!1,da=!1,ea=!1,fa=!1,ha=!1;ca="object"===typeof window;da="function"===typeof importScripts;ea=(fa="object"===typeof process&&"function"===typeof require)&&!ca&&!da;ha=!ca&&!ea&&!da;var m="";
if(ea){m=__dirname+"/";var ia,ja;h.read=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);a=ia.readFileSync(a);return b?a:a.toString()};h.readBinary=function(a){a=h.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(h.thisProgram=process.argv[1].replace(/\\/g,"/"));h.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});process.on("unhandledRejection",
p);h.quit=function(a){process.exit(a)};h.inspect=function(){return"[Emscripten Module object]"}}else if(ha)"undefined"!=typeof read&&(h.read=function(a){return read(a)}),h.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?h.arguments=scriptArgs:"undefined"!=typeof arguments&&(h.arguments=arguments),"function"===typeof quit&&(h.quit=function(a){quit(a)});else if(ca||da)da?
m=self.location.href:document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.lastIndexOf("/")+1):"",h.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},da&&(h.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),h.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},h.setWindowTitle=function(a){document.title=a};var la=h.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),r=h.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||la);for(l in ba)ba.hasOwnProperty(l)&&(h[l]=ba[l]);ba=void 0;function ma(a){var b=t[na>>2];a=b+a+15&-16;a>u.length&&p();t[na>>2]=a;return b}
"object"!==typeof WebAssembly&&r("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||p("Assertion failed: "+b)}function ra(a){var b=h["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function sa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=w(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)t[a>>2]=0;for(b=d+c;a<b;)u[a++>>0]=0;return d}a.subarray||a.slice?x.set(a,d):x.set(new Uint8Array(a),d);return d}function ta(a){for(var b="";;){var c=x[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function va(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ua)return ua.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?va(x,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function xa(a){var b=wa(a)+1,c=ya(b);A(a,u,c,b);return c}function za(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,u,x,Aa,Ba,t,B,C,D;
function Ca(){h.HEAP8=u=new Int8Array(buffer);h.HEAP16=Aa=new Int16Array(buffer);h.HEAP32=t=new Int32Array(buffer);h.HEAPU8=x=new Uint8Array(buffer);h.HEAPU16=Ba=new Uint16Array(buffer);h.HEAPU32=B=new Uint32Array(buffer);h.HEAPF32=C=new Float32Array(buffer);h.HEAPF64=D=new Float64Array(buffer)}var na=309536,Da=h.TOTAL_MEMORY||16777216;5242880>Da&&r("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Da+"! (TOTAL_STACK=5242880)");
h.buffer?buffer=h.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(oa=new WebAssembly.Memory({initial:Da/65536}),buffer=oa.buffer):buffer=new ArrayBuffer(Da);Ca();t[na>>2]=5552448;function Ea(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.je;"number"===typeof c?void 0===b.Kd?h.dynCall_v(c):h.dynCall_vi(c,b.Kd):c(void 0===b.Kd?null:b.Kd)}}}var Fa=[],Ga=[],Ha=[],Ia=[],Ja=[],Ka=!1;
function La(){Ka||(Ka=!0,h.noFSInit||Ma||(Ma=!0,Na(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Oa("stdin",h.stdin):Pa("/dev/tty","/dev/stdin"),h.stdout?Oa("stdout",null,h.stdout):Pa("/dev/tty","/dev/stdout"),h.stderr?Oa("stderr",null,h.stderr):Pa("/dev/tty1","/dev/stderr"),Qa("/dev/stdin","r"),Qa("/dev/stdout","w"),Qa("/dev/stderr","w")),Ea(Ga))}function Ra(){var a=h.preRun.shift();Fa.unshift(a)}
var Sa=Math.abs,Ta=Math.sqrt,Ua=Math.ceil,Va=Math.floor,Wa=Math.min,Xa=0,Ya=null,Za=null;h.preloadedImages={};h.preloadedAudios={};function $a(){var a=ab;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var ab="magnum-player.wasm";if(!$a()){var bb=ab;ab=h.locateFile?h.locateFile(bb,m):m+bb}
function cb(){try{if(h.wasmBinary)return new Uint8Array(h.wasmBinary);if(h.readBinary)return h.readBinary(ab);throw"both async and sync fetching of the wasm failed";}catch(a){p(a)}}function db(){return h.wasmBinary||!ca&&!da||"function"!==typeof fetch?new Promise(function(a){a(cb())}):fetch(ab,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+ab+"'";return a.arrayBuffer()}).catch(function(){return cb()})}
function eb(a){function b(a){h.asm=a.exports;Xa--;h.monitorRunDependencies&&h.monitorRunDependencies(Xa);0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za&&(a=Za,Za=null,a()))}function c(a){b(a.instance)}function d(a){return db().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){r("failed to asynchronously prepare wasm: "+a);p(a)})}var e={env:a};Xa++;h.monitorRunDependencies&&h.monitorRunDependencies(Xa);if(h.instantiateWasm)try{return h.instantiateWasm(e,b)}catch(f){return r("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(h.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||$a()||"function"!==typeof fetch)return d(c);fetch(ab,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(c,function(a){r("wasm streaming compile failed: "+a);r("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}h.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:871,maximum:871,element:"anyfunc"});return eb(b)};
var gb=[function(){h.setFullsize(!1)},function(){h.setFullsize(!0)},function(){var a=h.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?sa(fb(a.id)):0},function(a){document.getElementById("container").className=ta(a)},function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?h.dynCall_ii.apply(null,[a].concat(e)):h.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(a){a=z(a);return"undefined"!==
typeof process&&a in process.env?sa(fb(process.env[a])):0}];Ga.push({je:function(){hb()}});var E={};
function ib(a){if(ib.md){var b=t[a>>2];var c=t[b>>2]}else ib.md=!0,E.USER=E.LOGNAME="web_user",E.PATH="/",E.PWD="/",E.HOME="/home/web_user",E.LANG="C.UTF-8",E._=h.thisProgram,c=Ka?w(1024):ma(1024),b=Ka?w(256):ma(256),t[b>>2]=c,t[a>>2]=b;a=[];var d=0,e;for(e in E)if("string"===typeof E[e]){var f=e+"="+E[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var k=c,n=0;n<d.length;++n)u[k++>>0]=d.charCodeAt(n);u[k>>0]=0;t[b+4*
e>>2]=c;c+=f.length+1}t[b+4*a.length>>2]=0}function jb(a){h.___errno_location&&(t[h.___errno_location()>>2]=a)}function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function lb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function mb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function nb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function ob(){var a=Array.prototype.slice.call(arguments,0);return lb(a.join("/"))}function pb(a,b){return lb(a+"/"+b)}
function qb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var rb=[];function sb(a,b){rb[a]={input:[],output:[],td:b};tb(a,ub)}
var ub={open:function(a){var b=rb[a.node.rdev];if(!b)throw new F(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.td.flush(a.tty)},flush:function(a){a.tty.td.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.td.ae)throw new F(6);for(var e=0,f=0;f<d;f++){try{var k=a.tty.td.ae(a.tty)}catch(n){throw new F(5);}if(void 0===k&&0===e)throw new F(11);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.td.Qd)throw new F(6);
try{for(var e=0;e<d;e++)a.tty.td.Qd(a.tty,b[c+e])}catch(f){throw new F(5);}d&&(a.node.timestamp=Date.now());return e}},vb={ae:function(a){if(!a.input.length){var b=null;if(ea){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(k){}}try{d=fs.readSync(e,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=fb(b,!0)}return a.input.shift()},Qd:function(a,b){null===b||10===b?(la(va(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(va(a.output,0)),a.output=[])}},wb={Qd:function(a,b){null===b||10===b?(r(va(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(r(va(a.output,0)),a.output=[])}},G={ld:null,hd:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(1);G.ld||(G.ld={dir:{node:{nd:G.bd.nd,kd:G.bd.kd,lookup:G.bd.lookup,yd:G.bd.yd,rename:G.bd.rename,unlink:G.bd.unlink,rmdir:G.bd.rmdir,readdir:G.bd.readdir,symlink:G.bd.symlink},stream:{pd:G.ad.pd}},file:{node:{nd:G.bd.nd,kd:G.bd.kd},stream:{pd:G.ad.pd,read:G.ad.read,write:G.ad.write,Sd:G.ad.Sd,ce:G.ad.ce,
Gd:G.ad.Gd}},link:{node:{nd:G.bd.nd,kd:G.bd.kd,readlink:G.bd.readlink},stream:{}},Ud:{node:{nd:G.bd.nd,kd:G.bd.kd},stream:xb}});c=yb(a,b,c,d);16384===(c.mode&61440)?(c.bd=G.ld.dir.node,c.ad=G.ld.dir.stream,c.$c={}):32768===(c.mode&61440)?(c.bd=G.ld.file.node,c.ad=G.ld.file.stream,c.ed=0,c.$c=null):40960===(c.mode&61440)?(c.bd=G.ld.link.node,c.ad=G.ld.link.stream):8192===(c.mode&61440)&&(c.bd=G.ld.Ud.node,c.ad=G.ld.Ud.stream);c.timestamp=Date.now();a&&(a.$c[b]=c);return c},ze:function(a){if(a.$c&&
a.$c.subarray){for(var b=[],c=0;c<a.ed;++c)b.push(a.$c[c]);return b}return a.$c},Ae:function(a){return a.$c?a.$c.subarray?a.$c.subarray(0,a.ed):new Uint8Array(a.$c):new Uint8Array},Wd:function(a,b){var c=a.$c?a.$c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.$c,a.$c=new Uint8Array(b),0<a.ed&&a.$c.set(c.subarray(0,a.ed),0))},oe:function(a,b){if(a.ed!=b)if(0==b)a.$c=null,a.ed=0;else{if(!a.$c||a.$c.subarray){var c=a.$c;a.$c=new Uint8Array(new ArrayBuffer(b));c&&
a.$c.set(c.subarray(0,Math.min(b,a.ed)))}else if(a.$c||(a.$c=[]),a.$c.length>b)a.$c.length=b;else for(;a.$c.length<b;)a.$c.push(0);a.ed=b}},bd:{nd:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ed:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.qd=4096;b.blocks=Math.ceil(b.size/
b.qd);return b},kd:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.oe(a,b.size)},lookup:function(){throw zb[2];},yd:function(a,b,c,d){return G.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Ab(b,c)}catch(f){}if(d)for(var e in d.$c)throw new F(39);}delete a.parent.$c[a.name];a.name=c;b.$c[c]=a;a.parent=b},unlink:function(a,b){delete a.$c[b]},rmdir:function(a,b){var c=Ab(a,b),d;for(d in c.$c)throw new F(39);
delete a.$c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.$c)a.$c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new F(22);return a.link}},ad:{read:function(a,b,c,d,e){var f=a.node.$c;if(e>=a.node.ed)return 0;a=Math.min(a.node.ed-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){f=!1;if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.$c||a.$c.subarray)){if(f)return a.$c=b.subarray(c,c+d),a.ed=d;if(0===a.ed&&0===e)return a.$c=new Uint8Array(b.subarray(c,c+d)),a.ed=d;if(e+d<=a.ed)return a.$c.set(b.subarray(c,c+d),e),d}G.Wd(a,e+d);if(a.$c.subarray&&b.subarray)a.$c.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.$c[e+f]=b[c+f];a.ed=Math.max(a.ed,e+d);return d},pd:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ed);if(0>b)throw new F(22);return b},Sd:function(a,
b,c){G.Wd(a.node,b+c);a.node.ed=Math.max(a.node.ed,b+c)},ce:function(a,b,c,d,e,f,k){if(32768!==(a.node.mode&61440))throw new F(19);c=a.node.$c;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.ed)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=w(d);if(!d)throw new F(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{Fe:d,ge:a}},Gd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(19);if(e&2)return 0;G.ad.write(a,b,0,d,c,!1);return 0}}},H={Ed:!1,qe:function(){H.Ed=
!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);H.Yd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Td:function(a){return Buffer.md?Buffer.from(a):new Buffer(a)},hd:function(a){assert(fa);return H.createNode(null,"/",H.$d(a.Pd.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new F(22);a=yb(a,b,c);a.bd=H.bd;a.ad=H.ad;return a},$d:function(a){try{var b=
fs.lstatSync(a);H.Ed&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new F(-c.dd);}return b.mode},jd:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.hd.Pd.root);b.reverse();return ob.apply(null,b)},ie:function(a){a&=-2656257;var b=0,c;for(c in H.Yd)a&c&&(b|=H.Yd[c],a^=c);if(a)throw new F(22);return b},bd:{nd:function(a){a=H.jd(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new F(-c.dd);}H.Ed&&!b.qd&&(b.qd=4096);H.Ed&&!b.blocks&&(b.blocks=
(b.size+b.qd-1)/b.qd|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,qd:b.qd,blocks:b.blocks}},kd:function(a,b){var c=H.jd(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new F(-d.dd);}},lookup:function(a,b){var c=pb(H.jd(a),b);c=H.$d(c);return H.createNode(a,b,c)},yd:function(a,b,c,d){a=H.createNode(a,b,c,d);b=H.jd(a);
try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new F(-e.dd);}return a},rename:function(a,b,c){a=H.jd(a);b=pb(H.jd(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new F(-d.dd);}},unlink:function(a,b){a=pb(H.jd(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new F(-c.dd);}},rmdir:function(a,b){a=pb(H.jd(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new F(-c.dd);}},readdir:function(a){a=
H.jd(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new F(-b.dd);}},symlink:function(a,b,c){a=pb(H.jd(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new F(-d.dd);}},readlink:function(a){var b=H.jd(a);try{return b=fs.readlinkSync(b),b=Bb.relative(Bb.resolve(a.hd.Pd.root),b)}catch(c){if(!c.code)throw c;throw new F(-c.dd);}}},ad:{open:function(a){var b=H.jd(a.node);try{32768===(a.node.mode&61440)&&(a.zd=fs.openSync(b,H.ie(a.flags)))}catch(c){if(!c.code)throw c;throw new F(-c.dd);
}},close:function(a){try{32768===(a.node.mode&61440)&&a.zd&&fs.closeSync(a.zd)}catch(b){if(!b.code)throw b;throw new F(-b.dd);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.zd,H.Td(b.buffer),c,d,e)}catch(f){throw new F(-f.dd);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.zd,H.Td(b.buffer),c,d,e)}catch(f){throw new F(-f.dd);}},pd:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.zd).size}catch(d){throw new F(-d.dd);
}if(0>b)throw new F(22);return b}}},Cb=null,Db={},Eb=[],Fb=1,Gb=null,Hb=!0,Ib={},F=null,zb={};
function I(a,b){a=qb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Zd:!0,Rd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Rd)throw new F(40);a=kb(a.split("/").filter(function(a){return!!a}),!1);var e=Cb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Ab(e,a[d]);c=pb(c,a[d]);e.Fd&&(!f||f&&b.Zd)&&(e=e.Fd.root);if(!f||b.Md)for(f=0;40960===(e.mode&61440);)if(e=Jb(c),c=qb(mb(c),e),e=I(c,{Rd:b.Rd}).node,40<f++)throw new F(40);}return{path:c,node:e}}
function Kb(a){for(var b;;){if(a===a.parent)return a=a.hd.de,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Mb(a){var b=Lb(a.parent.id,a.name);a.ne=Gb[b];Gb[b]=a}function Ab(a,b){var c;if(c=(c=Nb(a,"x"))?c:a.bd.lookup?0:13)throw new F(c,a);for(c=Gb[Lb(a.id,b)];c;c=c.ne){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.bd.lookup(a,b)}
function yb(a,b,c,d){Ob||(Ob=function(a,b,c,d){a||(a=this);this.parent=a;this.hd=a.hd;this.Fd=null;this.id=Fb++;this.name=b;this.mode=c;this.bd={};this.ad={};this.rdev=d},Ob.prototype={},Object.defineProperties(Ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Ob(a,b,c,d);Mb(a);return a}
var Pb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Rb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Nb(a,b){if(Hb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Sb(a,b){try{return Ab(a,b),17}catch(c){}return Nb(a,"wx")}
function Tb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Eb[a])return a;throw new F(24);}function Ub(a,b){Vb||(Vb=function(){},Vb.prototype={},Object.defineProperties(Vb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Vb,d;for(d in a)c[d]=a[d];a=c;b=Tb(b);a.fd=b;return Eb[b]=a}var xb={open:function(a){a.ad=Db[a.node.rdev].ad;a.ad.open&&a.ad.open(a)},pd:function(){throw new F(29);}};function tb(a,b){Db[a]={ad:b}}
function Wb(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new F(16);if(!c&&!d){var e=I(b,{Zd:!1});b=e.path;e=e.node;if(e.Fd)throw new F(16);if(16384!==(e.mode&61440))throw new F(20);}b={type:a,Pd:{},de:b,me:[]};a=a.hd(b);a.hd=b;b.root=a;c?Cb=a:e&&(e.Fd=b,e.hd&&e.hd.me.push(b))}function Xb(a,b,c){var d=I(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new F(22);var e=Sb(d,a);if(e)throw new F(e);if(!d.bd.yd)throw new F(1);return d.bd.yd(d,a,b,c)}function J(a){Xb(a,16895,0)}
function Yb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Xb(a,b|8192,c)}function Pa(a,b){if(!qb(a))throw new F(2);var c=I(b,{parent:!0}).node;if(!c)throw new F(2);b=nb(b);var d=Sb(c,b);if(d)throw new F(d);if(!c.bd.symlink)throw new F(1);c.bd.symlink(c,b,a)}function Jb(a){a=I(a).node;if(!a)throw new F(2);if(!a.bd.readlink)throw new F(22);return qb(Kb(a.parent),a.bd.readlink(a))}
function Qa(a,b,c,d){if(""===a)throw new F(2);if("string"===typeof b){var e=Pb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=lb(a);try{f=I(a,{Md:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new F(17);}else f=Xb(a,c,0),e=!0;if(!f)throw new F(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new F(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Rb(b)||b&512)?21:Nb(f,Rb(b)):2))throw new F(c);if(b&512){c=f;var k;"string"===typeof c?k=I(c,{Md:!0}).node:k=c;if(!k.bd.kd)throw new F(1);if(16384===(k.mode&61440))throw new F(21);if(32768!==(k.mode&61440))throw new F(22);if(c=Nb(k,"w"))throw new F(c);k.bd.kd(k,{size:0,timestamp:Date.now()})}b&=-641;d=Ub({node:f,path:Kb(f),flags:b,seekable:!0,position:0,ad:f.ad,ve:[],error:!1},d);d.ad.open&&d.ad.open(d);!h.logReadFiles||b&1||(Zb||(Zb={}),a in Zb||(Zb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Ib.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Ib.onOpenFile(a,f))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function $b(a,b,c){if(null===a.fd)throw new F(9);if(!a.seekable||!a.ad.pd)throw new F(29);if(0!=c&&1!=c&&2!=c)throw new F(22);a.position=a.ad.pd(a,b,c);a.ve=[]}
function Na(){F||(F=function(a,b){this.node=b;this.pe=function(a){this.dd=a};this.pe(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},F.prototype=Error(),F.prototype.constructor=F,[2].forEach(function(a){zb[a]=new F(a);zb[a].stack="<generic error, no stack>"}))}var Ma;function ac(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Oa(a,b,c){a=pb("/dev",a);var d=ac(!!b,!!c);bc||(bc=64);var e=bc++<<8|0;tb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,k=0;k<e;k++){try{var n=b()}catch(R){throw new F(5);}if(void 0===n&&0===f)throw new F(11);if(null===n||void 0===n)break;f++;c[d+k]=n}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(y){throw new F(5);}e&&(a.node.timestamp=Date.now());return f}});
Yb(a,d,e)}var bc,K={},Ob,Vb,Zb,cc={},L=0;function M(){L+=4;return t[L-4>>2]}function dc(){var a=Eb[M()];if(!a)throw new F(9);return a}function ec(){p()}var fc=0,hc=0,N=0,ic=0,jc=null,kc=null,lc=!1;function mc(){for(var a=O.length-1;0<=a;--a)nc(a);O=[];oc=[]}var oc=[];function pc(){if(qc&&rc.vd)for(var a=0;a<oc.length;++a){var b=oc[a];oc.splice(a,1);--a;b.He.apply(this,b.we)}}var qc=0,rc=null,O=[];
function sc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function nc(a){var b=O[a];b.target.removeEventListener(b.rd,b.he,b.Bd);O.splice(a,1)}function tc(a){function b(b){++qc;rc=a;pc();a.Dd(b);pc();--qc}if(a.Cd)a.he=b,a.target.addEventListener(a.rd,b,a.Bd),O.push(a),lc||(Ia.push(mc),lc=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].rd==a.rd&&nc(c--)}
var uc={},vc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function wc(a){try{if(!a)return window;"number"===typeof a&&(a=vc[a]||z(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?h.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}
function xc(a){"number"===typeof a&&(a=z(a));return a&&"#canvas"!==a?"undefined"!==typeof yc&&zc[a]?zc[a]:wc(a):"undefined"!==typeof yc&&zc.canvas?zc.canvas:h.canvas}
function Ac(a,b,c,d,e,f){fc||(fc=w(164));a={target:wc(a),vd:sc()?!1:!0,rd:f,Cd:d,Dd:function(a){a=a||window.event;var c=fc;A(a.key?a.key:"",x,c+0,32);A(a.code?a.code:"",x,c+32,32);t[c+64>>2]=a.location;t[c+68>>2]=a.ctrlKey;t[c+72>>2]=a.shiftKey;t[c+76>>2]=a.altKey;t[c+80>>2]=a.metaKey;t[c+84>>2]=a.repeat;A(a.locale?a.locale:"",x,c+88,32);A(a.char?a.char:"",x,c+120,32);t[c+152>>2]=a.charCode;t[c+156>>2]=a.keyCode;t[c+160>>2]=a.which;Bc(d,e,c,b)&&a.preventDefault()},Bd:c};tc(a)}
function Cc(a,b,c){D[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();t[a+8>>2]=b.screenX;t[a+12>>2]=b.screenY;t[a+16>>2]=b.clientX;t[a+20>>2]=b.clientY;t[a+24>>2]=b.ctrlKey;t[a+28>>2]=b.shiftKey;t[a+32>>2]=b.altKey;t[a+36>>2]=b.metaKey;Aa[a+40>>1]=b.button;Aa[a+42>>1]=b.buttons;t[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-jc;t[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-kc;if(h.canvas){var d=h.canvas.getBoundingClientRect();
t[a+60>>2]=b.clientX-d.left;t[a+64>>2]=b.clientY-d.top}else t[a+60>>2]=0,t[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},t[a+52>>2]=b.clientX-d.left,t[a+56>>2]=b.clientY-d.top):(t[a+52>>2]=0,t[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(jc=b.screenX,kc=b.screenY)}
function Dc(a,b,c,d,e,f){hc||(hc=w(72));a=wc(a);c={target:a,vd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,rd:f,Cd:d,Dd:function(c){c=c||window.event;Cc(hc,c,a);Bc(d,e,hc,b)&&c.preventDefault()},Bd:c};sc()&&"mousedown"==f&&(c.vd=!1);tc(c)}
function Ec(a,b,c,d){ic||(ic=w(36));a=wc(a);tc({target:a,vd:!1,rd:"resize",Cd:d,Dd:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],k=ic;t[k>>2]=c.detail;t[k+4>>2]=document.body.clientWidth;
t[k+8>>2]=document.body.clientHeight;t[k+12>>2]=window.innerWidth;t[k+16>>2]=window.innerHeight;t[k+20>>2]=window.outerWidth;t[k+24>>2]=window.outerHeight;t[k+28>>2]=e[0];t[k+32>>2]=e[1];Bc(d,10,k,b)&&c.preventDefault()}},Bd:c})}
function Fc(a,b,c,d,e){function f(c){c=c||window.event;Cc(N,c,a);D[N+72>>3]=c.wheelDeltaX||0;D[N+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);D[N+88>>3]=0;t[N+96>>2]=0;Bc(d,9,N,b)&&c.preventDefault()}function k(c){c=c||window.event;var e=N;Cc(e,c,a);D[e+72>>3]=c.deltaX;D[e+80>>3]=c.deltaY;D[e+88>>3]=c.deltaZ;t[e+96>>2]=c.deltaMode;Bc(d,9,e,b)&&c.preventDefault()}N||(N=w(104));tc({target:a,vd:!0,rd:e,Cd:d,Dd:"wheel"==e?k:f,Bd:c})}
var Gc=1,Hc=0,Ic=[],P=[],Jc=[],Kc=[],Lc=[],Q=[],S=[],Mc=[],T={},U=null,zc={},Nc=[],Oc=[],Pc={},Qc={},Rc={},Sc=4;function V(a){Hc||(Hc=a)}function Tc(a){for(var b=Gc++,c=a.length;c<b;c++)a[c]=null;return b}var Uc=null,W=[0];
function Vc(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=w(8),e={handle:d,attributes:b,version:b.be,sd:a};e.cd=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.fe=e);T[d]=e;("undefined"===typeof b.Vd||b.Vd)&&Wc(e);return d}
function Wc(a){a||(a=U);if(!a.ke){a.ke=!0;var b=a.sd;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.ye=b.getExtension("EXT_disjoint_timer_query");var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}}var yc={},Xc,Yc,Zc=["default","low-power","high-performance"];function $c(a){U=T[a];h.xe=Y=U&&U.sd;return!a||Y?0:-5}h._emscripten_webgl_make_context_current=$c;function ad(a){if(0===a)return 0;a=z(a);if(!E.hasOwnProperty(a))return 0;ad.md&&bd(ad.md);a=E[a];var b=wa(a)+1,c=w(b);c&&A(a,u,c,b);ad.md=c;return ad.md}var cd=[];
function dd(a,b,c,d){for(var e=0;e<a;e++){var f=Y[c](),k=f&&Tc(d);f?(f.name=k,d[k]=f):V(1282);t[b+4*e>>2]=k}}
function ed(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&V(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=Y.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){V(1282);return}e=Y.getSupportedExtensions();d=null===e?0:2*e.length;break;case 33307:case 33308:if(2>U.version){V(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=Y.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);
return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":t[b+4*a>>2]=e[a];break;case "Float":C[b+4*a>>2]=e[a];break;case "Boolean":u[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=
e.name|0}catch(f){V(1280);r("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);return}switch(c){case "Integer64":aa=[d>>>0,(g=d,1<=+Sa(g)?0<g?(Wa(+Va(g/4294967296),4294967295)|0)>>>0:~~+Ua((g-+(~~g>>>0))/4294967296)>>>0:0)];t[b>>2]=aa[0];t[b+4>>2]=aa[1];break;case "Integer":t[b>>2]=d;break;case "Float":C[b>>2]=d;break;case "Boolean":u[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else V(1281)}
function fd(a){var b=wa(a)+1,c=w(b);A(a,x,c,b);return c}var gd={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},hd={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function id(a,b,c,d,e){if(b=gd[b]*hd[a]){var f=Sc;c=e+d*(c*b+f-1&-f);switch(a){case 5120:return u.subarray(e,c);case 5121:return x.subarray(e,c);case 5122:return Aa.subarray(e>>1,c>>1);case 5124:return t.subarray(e>>2,c>>2);case 5126:return C.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return B.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Ba.subarray(e>>1,c>>1);default:V(1280)}}else V(1280)}
function jd(a){switch(a){case 5120:return u;case 5121:return x;case 5122:return Aa;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Ba;case 5124:return t;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return B;case 5126:return C}}var kd={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};
function ld(a){a=za(a);var b=buffer.byteLength;try{return-1!==oa.grow((a-b)/65536)?(buffer=oa.buffer,!0):!1}catch(c){return!1}}function md(a){return 0===a%4&&(0!==a%100||0===a%400)}function nd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var od=[31,29,31,30,31,30,31,31,30,31,30,31],pd=[31,28,31,30,31,30,31,31,30,31,30,31];
function qd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(md(a.getFullYear())?od:pd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function rd(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=qd(new Date(a.gd+1900,0,1),a.Jd);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=k(n(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var v=t[d+40>>2];d={te:t[d>>2],se:t[d+4>>2],Hd:t[d+8>>2],Ad:t[d+12>>2],ud:t[d+16>>2],gd:t[d+20>>2],Id:t[d+24>>2],Jd:t[d+28>>2],Ie:t[d+32>>2],re:t[d+36>>2],
ue:v?z(v):""};c=z(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in v)c=c.replace(new RegExp(y,"g"),v[y]);var X="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
R="January February March April May June July August September October November December".split(" ");v={"%a":function(a){return X[a.Id].substring(0,3)},"%A":function(a){return X[a.Id]},"%b":function(a){return R[a.ud].substring(0,3)},"%B":function(a){return R[a.ud]},"%C":function(a){return f((a.gd+1900)/100|0,2)},"%d":function(a){return f(a.Ad,2)},"%e":function(a){return e(a.Ad,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return f(a.Hd,
2)},"%I":function(a){a=a.Hd;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Ad+nd(md(a.gd+1900)?od:pd,a.ud-1),3)},"%m":function(a){return f(a.ud+1,2)},"%M":function(a){return f(a.se,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.Hd&&12>a.Hd?"AM":"PM"},"%S":function(a){return f(a.te,2)},"%t":function(){return"\t"},"%u":function(a){return a.Id||7},"%U":function(a){var b=new Date(a.gd+1900,0,1),c=0===b.getDay()?b:qd(b,7-b.getDay());a=new Date(a.gd+1900,a.ud,a.Ad);return 0>
k(c,a)?f(Math.ceil((31-c.getDate()+(nd(md(a.getFullYear())?od:pd,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.gd+1900,0,4)),c=n(new Date(a.gd+1901,0,4)),d=qd(new Date(a.gd+1900,0,1),a.Jd);return 0>k(d,b)?"53":0>=k(c,d)?"01":f(Math.ceil((b.getFullYear()<a.gd+1900?a.Jd+32-b.getDate():a.Jd+1-b.getDate())/7),2)},"%w":function(a){return a.Id},"%W":function(a){var b=new Date(a.gd,0,1),c=1===b.getDay()?b:qd(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.gd+
1900,a.ud,a.Ad);return 0>k(c,a)?f(Math.ceil((31-c.getDate()+(nd(md(a.getFullYear())?od:pd,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.gd+1900).toString().substring(2)},"%Y":function(a){return a.gd+1900},"%z":function(a){a=a.re;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.ue},"%%":function(){return"%"}};for(y in v)0<=c.indexOf(y)&&(c=c.replace(new RegExp(y,"g"),v[y](d)));y=fb(c,!1);if(y.length>
b)return 0;u.set(y,a);return y.length-1}Na();Gb=Array(4096);Wb(G,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");tb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Yb("/dev/null",259);sb(1280,vb);sb(1536,wb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){p("random_device")});Oa("random",b);Oa("urandom",b);J("/dev/shm");
J("/dev/shm/tmp")})();J("/proc");J("/proc/self");J("/proc/self/fd");Wb({hd:function(){var a=yb("/proc/self","fd",16895,73);a.bd={lookup:function(a,c){var b=Eb[+c];if(!b)throw new F(9);a={parent:null,hd:{de:"fake"},bd:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(fa){var fs=require("fs"),Bb=require("path");H.qe()}
ea?ec=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ec=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?ec=function(){return performance.now()}:ec=Date.now;var Y;Uc=new Float32Array(256);for(var sd=0;256>sd;sd++)W[sd]=Uc.subarray(0,sd+1);for(var td=0;32>td;td++)cd.push(Array(td));function fb(a,b){var c=Array(wa(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}
var wd=h.asm({},{fb:ib,c:function(a){return w(a)},_a:function(){pa=!0;throw"Pure virtual function called!";},b:function(a){"uncaught_exception"in ud?ud.md++:ud.md=1;throw a;},sb:function(){return!!ud.md},D:function(){},ob:function(){jb(1);return-1},B:function(a,b){L=b;try{var c=dc(),d=M(),e=M(),f=M(),k=M();a=4294967296*d+(e>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-75;$b(c,a,k);aa=[c.position>>>0,(g=c.position,1<=+Sa(g)?0<g?(Wa(+Va(g/4294967296),4294967295)|0)>>>0:~~+Ua((g-+(~~g>>>
0))/4294967296)>>>0:0)];t[f>>2]=aa[0];t[f+4>>2]=aa[1];c.Nd&&0===a&&0===k&&(c.Nd=null);return 0}catch(n){return"undefined"!==typeof K&&n instanceof F||p(n),-n.dd}},jb:function(a,b){L=b;try{var c=dc(),d=M();a:{var e=M();for(b=a=0;b<e;b++){var f=t[d+(8*b+4)>>2],k=c,n=t[d+8*b>>2],q=f,v=void 0,y=u;if(0>q||0>v)throw new F(22);if(null===k.fd)throw new F(9);if(1===(k.flags&2097155))throw new F(9);if(16384===(k.node.mode&61440))throw new F(21);if(!k.ad.read)throw new F(22);var X="undefined"!==typeof v;if(!X)v=
k.position;else if(!k.seekable)throw new F(29);var R=k.ad.read(k,y,n,q,v);X||(k.position+=R);var qa=R;if(0>qa){var Z=-1;break a}a+=qa;if(qa<f)break}Z=a}return Z}catch(Qb){return"undefined"!==typeof K&&Qb instanceof F||p(Qb),-Qb.dd}},z:function(a,b){L=b;try{var c=dc(),d=M();a:{var e=M();for(b=a=0;b<e;b++){var f=c,k=t[d+8*b>>2],n=t[d+(8*b+4)>>2],q=void 0,v=u;if(0>n||0>q)throw new F(22);if(null===f.fd)throw new F(9);if(0===(f.flags&2097155))throw new F(9);if(16384===(f.node.mode&61440))throw new F(21);
if(!f.ad.write)throw new F(22);f.flags&1024&&$b(f,0,2);var y="undefined"!==typeof q;if(!y)q=f.position;else if(!f.seekable)throw new F(29);var X=f.ad.write(f,v,k,n,q,void 0);y||(f.position+=X);try{if(f.path&&Ib.onWriteToFile)Ib.onWriteToFile(f.path)}catch(Z){console.log("FS.trackingDelegate['onWriteToFile']('"+f.path+"') threw an exception: "+Z.message)}var R=X;if(0>R){var qa=-1;break a}a+=R}qa=a}return qa}catch(Z){return"undefined"!==typeof K&&Z instanceof F||p(Z),-Z.dd}},l:function(a,b){L=b;try{var c=
dc();switch(M()){case 0:var d=M();return 0>d?-22:Qa(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=M(),c.flags|=d,0;case 12:return d=M(),Aa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return jb(22),-1;default:return-22}}catch(e){return"undefined"!==typeof K&&e instanceof F||p(e),-e.dd}},mb:function(a,b){L=b;try{var c=z(M());var d=M();if(d&-8)var e=-22;else{var f=I(c,{Md:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Nb(f,
a)?-13:0}return e}catch(k){return"undefined"!==typeof K&&k instanceof F||p(k),-k.dd}},lb:function(a,b){L=b;try{var c=z(M()),d=M(),e=M();return Qa(c,d,e).fd}catch(f){return"undefined"!==typeof K&&f instanceof F||p(f),-f.dd}},A:function(a,b){L=b;try{var c=dc(),d=M();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-25;case 21519:if(!c.tty)return-25;var e=M();return t[e>>2]=0;case 21520:return c.tty?-22:-25;case 21531:a=
e=M();if(!c.ad.le)throw new F(25);return c.ad.le(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:p("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof K&&f instanceof F||p(f),-f.dd}},C:function(a,b){L=b;try{var c=dc();if(null===c.fd)throw new F(9);c.Nd&&(c.Nd=null);try{c.ad.close&&c.ad.close(c)}catch(d){throw d;}finally{Eb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof K&&d instanceof F||p(d),-d.dd}},kb:function(a,b){L=b;try{var c=M(),d=M(),e=
cc[c];if(!e)return 0;if(d===e.Be){var f=Eb[e.fd],k=e.flags,n=new Uint8Array(x.subarray(c,c+d));f&&f.ad.Gd&&f.ad.Gd(f,n,0,d,k);cc[c]=null;e.ge&&bd(e.Ce)}return 0}catch(q){return"undefined"!==typeof K&&q instanceof F||p(q),-q.dd}},i:function(){},a:function(){h.abort()},tb:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ea||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=ec();else return jb(22),-1;t[b>>2]=a/1E3|0;t[b+4>>2]=a%1E3*1E6|
0;return 0},e:function(a,b,c){b=ta(b);for(var d=[],e=0;e<b.length;e++){var f=b[e];"d"==f||"f"==f?(c=c+8-1&-8,d.push(D[c>>3]),c+=8):"i"==f&&(c=c+4-1&-4,d.push(B[c>>2]),c+=4)}return gb[a].apply(null,d)},bb:function(a,b,c){a=xc(a);if(!a)return-4;t[b>>2]=a.width;t[c>>2]=a.height},Ja:function(){return window.devicePixelRatio||1},cb:function(a,b,c){a=a?wc(a):h.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),D[b>>3]=a.right-a.left,D[c>>3]=a.bottom-a.top):(D[b>>3]=a.clientWidth,
D[c>>3]=a.clientHeight);return 0},eb:function(a,b,c){x.set(x.subarray(b,b+c),a)},t:function(a,b,c){a=xc(a);if(!a)return-4;a.width=b;a.height=c;return 0},nb:function(a,b,c,d){Ac(a,b,c,d,2,"keydown");return 0},hb:function(a,b,c,d){Ac(a,b,c,d,3,"keyup");return 0},Wb:function(a,b,c,d){Dc(a,b,c,d,5,"mousedown");return 0},Fb:function(a,b,c,d){Dc(a,b,c,d,8,"mousemove");return 0},Ob:function(a,b,c,d){Dc(a,b,c,d,6,"mouseup");return 0},fc:function(a,b,c,d){Ec(a,b,c,d);return 0},ub:function(a,b,c,d){a=wc(a);
return"undefined"!==typeof a.onwheel?(Fc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Fc(a,b,c,d,"mousewheel"),0):-1},ab:function(){return U&&U.sd&&U.attributes.Xd?0:-3},Z:function(a,b){var c={};b>>=2;c.alpha=!!t[b];c.depth=!!t[b+1];c.stencil=!!t[b+2];c.antialias=!!t[b+3];c.premultipliedAlpha=!!t[b+4];c.preserveDrawingBuffer=!!t[b+5];c.powerPreference=Zc[t[b+6]];c.failIfMajorPerformanceCaveat=!!t[b+7];c.be=t[b+8];c.De=t[b+9];c.Vd=t[b+10];c.Xd=t[b+11];c.Ee=t[b+12];c.Ge=t[b+13];a=xc(a);
!a||c.Xd?c=0:c=(a=1<c.be?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&Vc(a,c);return c},Aa:function(a){U==a&&(U=0);U===T[a]&&(U=null);if("object"===typeof uc)for(var b=T[a].sd.canvas,c=0;c<O.length;++c)O[c].target!=b||nc(c--);T[a]&&T[a].sd.canvas&&(T[a].sd.canvas.fe=void 0);bd(T[a]);T[a]=null},ia:function(a){a>>=2;for(var b=0;14>b;++b)t[a+b]=0;t[a]=t[a+1]=t[a+3]=t[a+4]=t[a+8]=t[a+10]=1},P:$c,j:function(a){vd(a)},ib:Sa,y:Sa,gb:Va,f:ad,p:function(a){Y.activeTexture(a)},
qa:function(a,b){Y.attachShader(P[a],S[b])},pa:function(a,b,c){Y.bindAttribLocation(P[a],b,z(c))},r:function(a,b){35051==a?Y.Ld=b:35052==a&&(Y.od=b);Y.bindBuffer(a,Ic[b])},s:function(a,b,c){Y.bindBufferBase(a,b,Ic[c])},M:function(a,b,c,d,e){Y.bindBufferRange(a,b,Ic[c],d,e)},x:function(a,b){Y.bindFramebuffer(a,Jc[b])},Yb:function(a,b){Y.bindRenderbuffer(a,Kc[b])},o:function(a,b){Y.bindTexture(a,Lc[b])},Jb:function(a,b){Y.bindTransformFeedback(a,Oc[b])},Cb:function(a){Y.bindVertexArray(Mc[a])},Sb:function(a,
b){Y.blendFunc(a,b)},Ya:function(a,b,c,d,e,f,k,n,q,v){Y.blitFramebuffer(a,b,c,d,e,f,k,n,q,v)},J:function(a,b,c,d){U.cd?c?Y.bufferData(a,x,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?x.subarray(c,c+b):b,d)},I:function(a,b,c,d){U.cd?Y.bufferSubData(a,b,x,d,c):Y.bufferSubData(a,b,x.subarray(d,d+c))},Ua:function(a){return Y.checkFramebufferStatus(a)},Xa:function(a){Y.clear(a)},Qa:function(a,b,c,d){Y.clearBufferfi(a,b,c,d)},Ra:function(a,b,c){Y.clearBufferfv(a,b,C,c>>2)},Ta:function(a,b,c){Y.clearBufferiv(a,
b,t,c>>2)},Sa:function(a,b,c){Y.clearBufferuiv(a,b,B,c>>2)},Ub:function(a,b,c,d){Y.clearColor(a,b,c,d)},Rb:function(a){Y.clearDepth(a)},Mb:function(a){Y.compileShader(S[a])},v:function(a,b,c,d,e,f,k,n,q){U.cd?Y.od?Y.compressedTexSubImage2D(a,b,c,d,e,f,k,n,q):Y.compressedTexSubImage2D(a,b,c,d,e,f,k,x,q,n):Y.compressedTexSubImage2D(a,b,c,d,e,f,k,q?x.subarray(q,q+n):null)},va:function(a,b,c,d,e,f,k,n,q,v,y){U.cd?Y.od?Y.compressedTexSubImage3D(a,b,c,d,e,f,k,n,q,v,y):Y.compressedTexSubImage3D(a,b,c,d,
e,f,k,n,q,x,y,v):Y.compressedTexSubImage3D(a,b,c,d,e,f,k,n,q,y?x.subarray(y,y+v):null)},L:function(a,b,c,d,e){Y.copyBufferSubData(a,b,c,d,e)},Ma:function(a,b,c,d,e,f,k,n){Y.copyTexSubImage2D(a,b,c,d,e,f,k,n)},La:function(a,b,c,d,e,f,k,n,q){Y.copyTexSubImage3D(a,b,c,d,e,f,k,n,q)},ua:function(){var a=Tc(P),b=Y.createProgram();b.name=a;P[a]=b;return a},Qb:function(a){var b=Tc(S);S[b]=Y.createShader(a);return b},N:function(a,b){for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Ic[d];e&&(Y.deleteBuffer(e),e.name=
0,Ic[d]=null,d==Xc&&(Xc=0),d==Yc&&(Yc=0),d==Y.Ld&&(Y.Ld=0),d==Y.od&&(Y.od=0))}},cc:function(a,b){for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Jc[d];e&&(Y.deleteFramebuffer(e),e.name=0,Jc[d]=null)}},ta:function(a){if(a){var b=P[a];b?(Y.deleteProgram(b),b.name=0,P[a]=null,Pc[a]=null):V(1281)}},Zb:function(a,b){for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Kc[d];e&&(Y.deleteRenderbuffer(e),e.name=0,Kc[d]=null)}},Pb:function(a){if(a){var b=S[a];b?(Y.deleteShader(b),S[a]=null):V(1281)}},Ha:function(a,b){for(var c=
0;c<a;c++){var d=t[b+4*c>>2],e=Lc[d];e&&(Y.deleteTexture(e),e.name=0,Lc[d]=null)}},Ab:function(a,b){for(var c=0;c<a;c++){var d=t[b+4*c>>2];Y.deleteVertexArray(Mc[d]);Mc[d]=null}},G:function(a){Y.depthMask(!!a)},m:function(a){Y.disable(a)},Hb:function(a,b,c){Y.drawArrays(a,b,c)},Eb:function(a,b,c,d){Y.drawArraysInstanced(a,b,c,d)},Pa:function(a,b){for(var c=cd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];Y.drawBuffers(c)},Gb:function(a,b,c,d){Y.drawElements(a,b,c,d)},Db:function(a,b,c,d,e){Y.drawElementsInstanced(a,
b,c,d,e)},h:function(a){Y.enable(a)},zb:function(a){Y.enableVertexAttribArray(a)},bc:function(a,b,c,d){Y.framebufferRenderbuffer(a,b,c,Kc[d])},ac:function(a,b,c,d,e){Y.framebufferTexture2D(a,b,c,Lc[d],e)},$b:function(a,b,c,d,e){Y.framebufferTextureLayer(a,b,Lc[c],d,e)},O:function(a,b){dd(a,b,"createBuffer",Ic)},dc:function(a,b){dd(a,b,"createFramebuffer",Jc)},Ib:function(a,b){dd(a,b,"createQuery",Nc)},_b:function(a,b){dd(a,b,"createRenderbuffer",Kc)},Ia:function(a,b){dd(a,b,"createTexture",Lc)},Kb:function(a,
b){dd(a,b,"createTransformFeedback",Oc)},Bb:function(a,b){dd(a,b,"createVertexArray",Mc)},Ga:function(a){Y.generateMipmap(a)},K:function(a,b,c){c?t[c>>2]=Y.getBufferParameter(a,b):V(1281)},H:function(){if(Hc){var a=Hc;Hc=0;return a}return Y.getError()},Ka:function(a,b){ed(a,b,"Float")},k:function(a,b){ed(a,b,"Integer")},sa:function(a,b,c,d){a=Y.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");0<b&&d?(b=A(a,x,d,b),c&&(t[c>>2]=b)):c&&(t[c>>2]=0)},u:function(a,b,c){if(c)if(a>=Gc)V(1281);else{var d=
Pc[a];if(d)if(35716==b)a=Y.getProgramInfoLog(P[a]),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b)t[c>>2]=d.Od;else if(35722==b){if(-1==d.wd){a=P[a];var e=Y.getProgramParameter(a,35721);for(b=d.wd=0;b<e;++b)d.wd=Math.max(d.wd,Y.getActiveAttrib(a,b).name.length+1)}t[c>>2]=d.wd}else if(35381==b){if(-1==d.xd)for(a=P[a],e=Y.getProgramParameter(a,35382),b=d.xd=0;b<e;++b)d.xd=Math.max(d.xd,Y.getActiveUniformBlockName(a,b).length+1);t[c>>2]=d.xd}else t[c>>2]=Y.getProgramParameter(P[a],
b);else V(1282)}else V(1281)},Lb:function(a,b,c,d){a=Y.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");0<b&&d?(b=A(a,x,d,b),c&&(t[c>>2]=b)):c&&(t[c>>2]=0)},F:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1):35720==b?(a=Y.getShaderSource(S[a]),t[c>>2]=null===a||0==a.length?0:a.length+1):t[c>>2]=Y.getShaderParameter(S[a],b):V(1281)},n:function(a){if(Qc[a])return Qc[a];switch(a){case 7939:var b=Y.getSupportedExtensions();for(var c=[],d=
0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=fd(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||V(1280);b=fd(b);break;case 7938:b=Y.getParameter(Y.VERSION);b=2<=U.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=fd(b);break;case 35724:b=Y.getParameter(Y.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=fd(b);break;default:return V(1280),
0}return Qc[a]=b},ec:function(a,b){if(2>U.version)return V(1282),0;var c=Rc[a];if(c)return 0>b||b>=c.length?(V(1281),0):c[b];switch(a){case 7939:c=Y.getSupportedExtensions();for(var d=[],e=0;e<c.length;++e)d.push(fd(c[e])),d.push(fd("GL_"+c[e]));c=Rc[a]=d;return 0>b||b>=c.length?(V(1281),0):c[b];default:return V(1280),0}},la:function(a,b){return Y.getUniformBlockIndex(P[a],z(b))},ma:function(a,b){b=z(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;
b=b.slice(0,d)}return(a=Pc[a]&&Pc[a].ee[b])&&0<=c&&c<a[0]?a[1]+c:-1},Wa:function(a,b,c){for(var d=cd[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];Y.invalidateFramebuffer(a,d)},Va:function(a,b,c,d,e,f,k){for(var n=cd[b],q=0;q<b;q++)n[q]=t[c+4*q>>2];Y.invalidateSubFramebuffer(a,n,d,e,f,k)},na:function(a){Y.linkProgram(P[a]);var b=P[a];a=Pc[a]={ee:{},Od:0,wd:-1,xd:-1};for(var c=a.ee,d=Y.getProgramParameter(b,35718),e=0;e<d;++e){var f=Y.getActiveUniform(b,e),k=f.name;a.Od=Math.max(a.Od,k.length+1);"]"==k.slice(-1)&&
(k=k.slice(0,k.lastIndexOf("[")));var n=Y.getUniformLocation(b,k);if(n){var q=Tc(Q);c[k]=[f.size,q];Q[q]=n;for(var v=1;v<f.size;++v)n=Y.getUniformLocation(b,k+"["+v+"]"),q=Tc(Q),Q[q]=n}}},g:function(a,b){3317==a&&(Sc=b);Y.pixelStorei(a,b)},Oa:function(a){Y.readBuffer(a)},Na:function(a,b,c,d,e,f,k){U.cd?Y.Ld?Y.readPixels(a,b,c,d,e,f,k):Y.readPixels(a,b,c,d,e,f,jd(f),k>>(kd[f]|0)):(k=id(f,e,c,d,k))?Y.readPixels(a,b,c,d,e,f,k):V(1280)},Xb:function(a,b,c,d){Y.renderbufferStorage(a,b,c,d)},Vb:function(a,
b,c,d,e){Y.renderbufferStorageMultisample(a,b,c,d,e)},Tb:function(a,b,c,d){Y.scissor(a,b,c,d)},Nb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?t[d+4*f>>2]:-1;e+=z(t[c+4*f>>2],0>k?void 0:k)}Y.shaderSource(S[a],e)},ya:function(a,b,c,d,e,f,k,n,q){U.cd?Y.od?Y.texImage2D(a,b,c,d,e,f,k,n,q):0!=q?Y.texImage2D(a,b,c,d,e,f,k,n,jd(n),q>>(kd[n]|0)):Y.texImage2D(a,b,c,d,e,f,k,n,null):Y.texImage2D(a,b,c,d,e,f,k,n,q?id(n,k,d,e,q):null)},xa:function(a,b,c,d,e,f,k,n,q,v){Y.od?Y.texImage3D(a,b,c,d,e,f,k,n,
q,v):0!=v?Y.texImage3D(a,b,c,d,e,f,k,n,q,jd(q),v>>(kd[q]|0)):Y.texImage3D(a,b,c,d,e,f,k,n,q,null)},Ea:function(a,b,c){Y.texParameterf(a,b,c)},Ca:function(a,b,c){Y.texParameterf(a,b,C[c>>2])},Fa:function(a,b,c){Y.texParameteri(a,b,c)},Da:function(a,b,c){Y.texParameteri(a,b,t[c>>2])},Ba:function(a,b,c,d,e){Y.texStorage2D(a,b,c,d,e)},za:function(a,b,c,d,e,f){Y.texStorage3D(a,b,c,d,e,f)},w:function(a,b,c,d,e,f,k,n,q){if(U.cd)Y.od?Y.texSubImage2D(a,b,c,d,e,f,k,n,q):0!=q?Y.texSubImage2D(a,b,c,d,e,f,k,n,
jd(n),q>>(kd[n]|0)):Y.texSubImage2D(a,b,c,d,e,f,k,n,null);else{var v=null;q&&(v=id(n,k,e,f,q));Y.texSubImage2D(a,b,c,d,e,f,k,n,v)}},wa:function(a,b,c,d,e,f,k,n,q,v,y){Y.od?Y.texSubImage3D(a,b,c,d,e,f,k,n,q,v,y):0!=y?Y.texSubImage3D(a,b,c,d,e,f,k,n,q,v,jd(v),y>>(kd[v]|0)):Y.texSubImage3D(a,b,c,d,e,f,k,n,q,v,null)},oa:function(a,b,c,d){a=P[a];for(var e=[],f=0;f<b;f++)e.push(z(t[c+4*f>>2]));Y.transformFeedbackVaryings(a,e,d)},ka:function(a,b,c){if(U.cd)Y.uniform1fv(Q[a],C,c>>2,b);else{if(256>=b)for(var d=
W[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);Y.uniform1fv(Q[a],d)}},fa:function(a,b,c){U.cd?Y.uniform1iv(Q[a],t,c>>2,b):Y.uniform1iv(Q[a],t.subarray(c>>2,c+4*b>>2))},ba:function(a,b,c){U.cd?Y.uniform1uiv(Q[a],B,c>>2,b):Y.uniform1uiv(Q[a],B.subarray(c>>2,c+4*b>>2))},ja:function(a,b,c){if(U.cd)Y.uniform2fv(Q[a],C,c>>2,2*b);else{if(256>=2*b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);Y.uniform2fv(Q[a],d)}},ea:function(a,
b,c){U.cd?Y.uniform2iv(Q[a],t,c>>2,2*b):Y.uniform2iv(Q[a],t.subarray(c>>2,c+8*b>>2))},aa:function(a,b,c){U.cd?Y.uniform2uiv(Q[a],B,c>>2,2*b):Y.uniform2uiv(Q[a],B.subarray(c>>2,c+8*b>>2))},ha:function(a,b,c){if(U.cd)Y.uniform3fv(Q[a],C,c>>2,3*b);else{if(256>=3*b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);Y.uniform3fv(Q[a],d)}},da:function(a,b,c){U.cd?Y.uniform3iv(Q[a],t,c>>2,3*b):Y.uniform3iv(Q[a],t.subarray(c>>
2,c+12*b>>2))},$:function(a,b,c){U.cd?Y.uniform3uiv(Q[a],B,c>>2,3*b):Y.uniform3uiv(Q[a],B.subarray(c>>2,c+12*b>>2))},ga:function(a,b,c){if(U.cd)Y.uniform4fv(Q[a],C,c>>2,4*b);else{if(256>=4*b)for(var d=W[4*b-1],e=0;e<4*b;e+=4)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2],d[e+3]=C[c+(4*e+12)>>2];else d=C.subarray(c>>2,c+16*b>>2);Y.uniform4fv(Q[a],d)}},ca:function(a,b,c){U.cd?Y.uniform4iv(Q[a],t,c>>2,4*b):Y.uniform4iv(Q[a],t.subarray(c>>2,c+16*b>>2))},_:function(a,b,c){U.cd?Y.uniform4uiv(Q[a],
B,c>>2,4*b):Y.uniform4uiv(Q[a],B.subarray(c>>2,c+16*b>>2))},vb:function(a,b,c){a=P[a];Y.uniformBlockBinding(a,b,c)},Y:function(a,b,c,d){if(U.cd)Y.uniformMatrix2fv(Q[a],!!c,C,d>>2,4*b);else{if(256>=4*b)for(var e=W[4*b-1],f=0;f<4*b;f+=4)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2];else e=C.subarray(d>>2,d+16*b>>2);Y.uniformMatrix2fv(Q[a],!!c,e)}},V:function(a,b,c,d){U.cd?Y.uniformMatrix2x3fv(Q[a],!!c,C,d>>2,6*b):Y.uniformMatrix2x3fv(Q[a],!!c,C.subarray(d>>2,
d+24*b>>2))},T:function(a,b,c,d){U.cd?Y.uniformMatrix2x4fv(Q[a],!!c,C,d>>2,8*b):Y.uniformMatrix2x4fv(Q[a],!!c,C.subarray(d>>2,d+32*b>>2))},X:function(a,b,c,d){if(U.cd)Y.uniformMatrix3fv(Q[a],!!c,C,d>>2,9*b);else{if(256>=9*b)for(var e=W[9*b-1],f=0;f<9*b;f+=9)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);Y.uniformMatrix3fv(Q[a],
!!c,e)}},U:function(a,b,c,d){U.cd?Y.uniformMatrix3x2fv(Q[a],!!c,C,d>>2,6*b):Y.uniformMatrix3x2fv(Q[a],!!c,C.subarray(d>>2,d+24*b>>2))},R:function(a,b,c,d){U.cd?Y.uniformMatrix3x4fv(Q[a],!!c,C,d>>2,12*b):Y.uniformMatrix3x4fv(Q[a],!!c,C.subarray(d>>2,d+48*b>>2))},W:function(a,b,c,d){if(U.cd)Y.uniformMatrix4fv(Q[a],!!c,C,d>>2,16*b);else{if(256>=16*b)for(var e=W[16*b-1],f=0;f<16*b;f+=16)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+
5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2],e[f+9]=C[d+(4*f+36)>>2],e[f+10]=C[d+(4*f+40)>>2],e[f+11]=C[d+(4*f+44)>>2],e[f+12]=C[d+(4*f+48)>>2],e[f+13]=C[d+(4*f+52)>>2],e[f+14]=C[d+(4*f+56)>>2],e[f+15]=C[d+(4*f+60)>>2];else e=C.subarray(d>>2,d+64*b>>2);Y.uniformMatrix4fv(Q[a],!!c,e)}},S:function(a,b,c,d){U.cd?Y.uniformMatrix4x2fv(Q[a],!!c,C,d>>2,8*b):Y.uniformMatrix4x2fv(Q[a],!!c,C.subarray(d>>2,d+32*b>>2))},Q:function(a,b,c,d){U.cd?Y.uniformMatrix4x3fv(Q[a],
!!c,C,d>>2,12*b):Y.uniformMatrix4x3fv(Q[a],!!c,C.subarray(d>>2,d+48*b>>2))},ra:function(a){Y.useProgram(P[a])},wb:function(a,b){Y.vertexAttribDivisor(a,b)},yb:function(a,b,c,d,e){Y.vertexAttribIPointer(a,b,c,d,e)},xb:function(a,b,c,d,e,f){Y.vertexAttribPointer(a,b,c,!!d,e,f)},Za:function(a,b,c,d){Y.viewport(a,b,c,d)},qb:function(){return 0},pb:function(){return 0},$a:function(a){a=+a;return 0<=a?+Va(a+.5):+Ua(a-.5)},E:function(a){a=+a;return 0<=a?+Va(a+.5):+Ua(a-.5)},d:function(a){a|=0;var b=u.length|
0;var c=t[na>>2]|0;var d=c+a|0;if(0<(a|0)&(d|0)<(c|0)|0>(d|0))return p("OOM"),0,jb(12),-1;if(a=(d|0)>(b|0)){a=d|0;if(2147418112<a)a=!1;else{for(b=Math.max(u.length,16777216);b<a;)536870912>=b?b=za(2*b):b=Math.min(za((3*b+2147483648)/4),2147418112);ld(b)?(Ca(),a=!0):a=!1}a=!(a|0)}if(a)return jb(12),-1;t[na>>2]=d|0;return c|0},db:function(){},q:Ta,rb:function(a,b,c,d){return rd(a,b,c,d)}},buffer);h.asm=wd;var hb=h.___wasm_call_ctors=function(){return h.asm.gc.apply(null,arguments)};
h._loadFile=function(){return h.asm.hc.apply(null,arguments)};h._main=function(){return h.asm.ic.apply(null,arguments)};var bd=h._free=function(){return h.asm.jc.apply(null,arguments)};h.___errno_location=function(){return h.asm.kc.apply(null,arguments)};
var w=h._malloc=function(){return h.asm.lc.apply(null,arguments)},ud=h.__ZSt18uncaught_exceptionv=function(){return h.asm.mc.apply(null,arguments)},xd=h.stackSave=function(){return h.asm.nc.apply(null,arguments)},ya=h.stackAlloc=function(){return h.asm.oc.apply(null,arguments)},yd=h.stackRestore=function(){return h.asm.pc.apply(null,arguments)};h.dynCall_iiif=function(){return h.asm.qc.apply(null,arguments)};h.dynCall_vi=function(){return h.asm.rc.apply(null,arguments)};
h.dynCall_vifiiii=function(){return h.asm.sc.apply(null,arguments)};h.dynCall_vfii=function(){return h.asm.tc.apply(null,arguments)};h.dynCall_viiii=function(){return h.asm.uc.apply(null,arguments)};h.dynCall_vii=function(){return h.asm.vc.apply(null,arguments)};h.dynCall_iiiii=function(){return h.asm.wc.apply(null,arguments)};h.dynCall_ii=function(){return h.asm.xc.apply(null,arguments)};h.dynCall_viii=function(){return h.asm.yc.apply(null,arguments)};
h.dynCall_vifi=function(){return h.asm.zc.apply(null,arguments)};h.dynCall_vif=function(){return h.asm.Ac.apply(null,arguments)};h.dynCall_iii=function(){return h.asm.Bc.apply(null,arguments)};var Bc=h.dynCall_iiii=function(){return h.asm.Cc.apply(null,arguments)};h.dynCall_v=function(){return h.asm.Dc.apply(null,arguments)};h.dynCall_viiiii=function(){return h.asm.Ec.apply(null,arguments)};h.dynCall_viifi=function(){return h.asm.Fc.apply(null,arguments)};
h.dynCall_viiiiii=function(){return h.asm.Gc.apply(null,arguments)};h.dynCall_vf=function(){return h.asm.Hc.apply(null,arguments)};h.dynCall_viiiiiiii=function(){return h.asm.Ic.apply(null,arguments)};h.dynCall_viiiiiii=function(){return h.asm.Jc.apply(null,arguments)};h.dynCall_viif=function(){return h.asm.Kc.apply(null,arguments)};h.dynCall_viiiiiiiii=function(){return h.asm.Lc.apply(null,arguments)};h.dynCall_vijf=function(){return h.asm.Mc.apply(null,arguments)};
h.dynCall_viiif=function(){return h.asm.Nc.apply(null,arguments)};h.dynCall_iiiiiiiii=function(){return h.asm.Oc.apply(null,arguments)};h.dynCall_viijii=function(){return h.asm.Pc.apply(null,arguments)};h.dynCall_viiifi=function(){return h.asm.Qc.apply(null,arguments)};h.dynCall_iiiiii=function(){return h.asm.Rc.apply(null,arguments)};h.dynCall_iiiiiii=function(){return h.asm.Sc.apply(null,arguments)};h.dynCall_iiiiij=function(){return h.asm.Tc.apply(null,arguments)};
h.dynCall_iiiiid=function(){return h.asm.Uc.apply(null,arguments)};h.dynCall_iiiiijj=function(){return h.asm.Vc.apply(null,arguments)};h.dynCall_iiiiiiii=function(){return h.asm.Wc.apply(null,arguments)};h.dynCall_iiiiiijj=function(){return h.asm.Xc.apply(null,arguments)};h.dynCall_jiji=function(){return h.asm.Yc.apply(null,arguments)};h.dynCall_iidiiii=function(){return h.asm.Zc.apply(null,arguments)};h.asm=wd;
h.ccall=function(a,b,c,d){var e={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=ya(c);A(a,x,b,c)}return b},array:function(a){var b=ya(a.length);u.set(a,b);return b}},f=ra(a),k=[];a=0;if(d)for(var n=0;n<d.length;n++){var q=e[c[n]];q?(0===a&&(a=xd()),k[n]=q(d[n])):k[n]=d[n]}c=f.apply(null,k);c=function(a){return"string"===b?z(a):"boolean"===b?!!a:a}(c);0!==a&&yd(a);return c};
function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ka.prototype=Error();ka.prototype.constructor=ka;Za=function zd(){h.calledRun||Ad();h.calledRun||(Za=zd)};
h.callMain=function(a){a=a||[];La();var b=a.length+1,c=ya(4*(b+1));t[c>>2]=xa(h.thisProgram);for(var d=1;d<b;d++)t[(c>>2)+d]=xa(a[d-1]);t[(c>>2)+b]=0;try{var e=h._main(b,c,0);vd(e,!0)}catch(f){f instanceof ka||("SimulateInfiniteLoop"==f?h.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),r("exception thrown: "+a),h.quit(1,f)))}finally{}};
function Ad(a){function b(){if(!h.calledRun&&(h.calledRun=!0,!pa)){La();Hb=!1;Ea(Ha);if(h.onRuntimeInitialized)h.onRuntimeInitialized();h._main&&Bd&&h.callMain(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ja.unshift(b)}Ea(Ja)}}a=a||h.arguments;if(!(0<Xa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ra();Ea(Fa);0<Xa||h.calledRun||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}h.run=Ad;function vd(a,b){if(!b||!h.noExitRuntime||0!==a){if(!h.noExitRuntime&&(pa=!0,h.onExit))h.onExit(a);h.quit(a,new ka(a))}}function p(a){if(h.onAbort)h.onAbort(a);void 0!==a?(la(a),r(a),a='"'+a+'"'):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}h.abort=p;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Bd=!0;h.noInitialRun&&(Bd=!1);h.noExitRuntime=!0;Ad();
