var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,la;
if(ca){var fs=require("fs");ia=__dirname+"/";la=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(ma(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var na=console.log.bind(console),n=console.error.bind(console),oa,pa=!1,qa,ma=a=>a.startsWith("file://"),ra,p,q,sa,ua,t,u,v,w,x;
function va(){var a=ra.buffer;p=new Int8Array(a);sa=new Int16Array(a);h.HEAPU8=q=new Uint8Array(a);ua=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);v=new Float32Array(a);w=new Float64Array(a);x=new BigInt64Array(a);new BigUint64Array(a)}function wa(a){h.onAbort?.(a);a="Aborted("+a+")";n(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa;
async function ya(a){if(!oa)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==xa&&oa)a=new Uint8Array(oa);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}
async function Aa(a){var b=xa;if(!oa&&!ma(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return za(b,a)}class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ca=a=>{for(;0<a.length;)a.shift()(h)},Da=[],Ea=[],Fa=()=>{var a=h.preRun.shift();Ea.push(a)},Ga=0,Ha=null,Ia=!0,Ja=[],Ka=0,La=0;
class Ma{constructor(a){this.le=a;this.sd=a-24}}
var Pa=a=>{var b=La;if(!b)return Na(0),0;var c=new Ma(b);u[c.sd+16>>2]=b;var d=u[c.sd+4>>2];if(!d)return Na(0),b;for(var e of a){if(0===e||e===d)break;if(Oa(e,d,c.sd+16))return Na(e),b}Na(d);return b},z=()=>{var a=t[+Qa>>2];Qa+=4;return a},Ra=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Sa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ra(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ta=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ua=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Va=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Wa=a=>{(Wa=Va())(a)},Xa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ra(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ya=(a,b)=>{function c(g){for(var k=0;k<g.length&&""===g[k];k++);for(var l=g.length-1;0<=l&&""===g[l];l--);return k>l?[]:g.slice(k,l-k+1)}a=Xa(a).slice(1);b=Xa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Za="undefined"!=
typeof TextDecoder?new TextDecoder:void 0,A=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Za)return Za.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},$a=[],ab=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=
0;return c-e},bb=[];function cb(a,b){bb[a]={input:[],output:[],Ad:b};db(a,eb)}
var eb={open(a){var b=bb[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ad.fsync(a.tty)},fsync(a){a.tty.Ad.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ad.ne)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ad.ne(a.tty)}catch(k){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ad.ae)throw new D(60);try{for(var e=0;e<d;e++)a.tty.Ad.ae(a.tty,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},fb={ne(){a:{if(!$a.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(ab(a)+1);a=C(a,b,0,b.length);b.length=a;$a=b}a=$a.shift()}return a},ae(a,b){null===
b||10===b?(na(A(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(na(A(a.output)),a.output=[])},He(){return{Se:25856,Ue:5,Re:191,Te:35387,Qe:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ie(){return 0},Je(){return[24,80]}},gb={ae(a,b){null===b||10===b?(n(A(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(n(A(a.output)),a.output=[])}},E={yd:null,ud(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new D(63);E.yd||(E.yd={dir:{node:{wd:E.nd.wd,zd:E.nd.zd,lookup:E.nd.lookup,Pd:E.nd.Pd,rename:E.nd.rename,unlink:E.nd.unlink,rmdir:E.nd.rmdir,readdir:E.nd.readdir,symlink:E.nd.symlink},stream:{xd:E.od.xd}},file:{node:{wd:E.nd.wd,zd:E.nd.zd},stream:{xd:E.od.xd,read:E.od.read,write:E.od.write,se:E.od.se,ue:E.od.ue}},link:{node:{wd:E.nd.wd,zd:E.nd.zd,readlink:E.nd.readlink},stream:{}},he:{node:{wd:E.nd.wd,zd:E.nd.zd},stream:hb}});c=ib(a,b,c,d);F(c.mode)?(c.nd=E.yd.dir.node,
c.od=E.yd.dir.stream,c.pd={}):32768===(c.mode&61440)?(c.nd=E.yd.file.node,c.od=E.yd.file.stream,c.qd=0,c.pd=null):40960===(c.mode&61440)?(c.nd=E.yd.link.node,c.od=E.yd.link.stream):8192===(c.mode&61440)&&(c.nd=E.yd.he.node,c.od=E.yd.he.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.pd[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},bf(a){return a.pd?a.pd.subarray?a.pd.subarray(0,a.qd):new Uint8Array(a.pd):new Uint8Array(0)},nd:{wd(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;F(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.qd:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},zd(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.qd!=b&&(0==b?(a.pd=null,a.qd=0):(c=a.pd,a.pd=new Uint8Array(b),c&&a.pd.set(c.subarray(0,Math.min(b,
a.qd))),a.qd=b)))},lookup(){E.Ud||(E.Ud=new D(44),E.Ud.stack="<generic error, no stack>");throw E.Ud;},Pd(a,b,c,d){return E.createNode(a,b,c,d)},rename(a,b,c){try{var d=G(b,c)}catch(f){}if(d){if(F(a.mode))for(var e in d.pd)throw new D(55);jb(d)}delete a.parent.pd[a.name];b.pd[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.pd[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=G(a,b),d;for(d in c.pd)throw new D(55);delete a.pd[b];a.ctime=a.mtime=Date.now()},
readdir(a){return[".","..",...Object.keys(a.pd)]},symlink(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},od:{read(a,b,c,d,e){var f=a.node.pd;if(e>=a.node.qd)return 0;a=Math.min(a.node.qd-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.pd||a.pd.subarray)){if(f)return a.pd=
b.subarray(c,c+d),a.qd=d;if(0===a.qd&&0===e)return a.pd=b.slice(c,c+d),a.qd=d;if(e+d<=a.qd)return a.pd.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.pd?a.pd.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.pd,a.pd=new Uint8Array(f),0<a.qd&&a.pd.set(g.subarray(0,a.qd),0));if(a.pd.subarray&&b.subarray)a.pd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.pd[e+f]=b[c+f];a.qd=Math.max(a.qd,e+d);return d},xd(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&
(b+=a.node.qd);if(0>b)throw new D(28);return b},se(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.pd;if(e&2||!a||a.buffer!==p.buffer){d=!0;wa();e=void 0;if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{sd:e,Oe:d}},ue(a,b,c,d){E.od.write(a,b,0,d,c,!1);return 0}}},kb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},lb=null,mb={},nb=[],ob=1,pb=null,qb=!1,rb=!0,sb={},D=
class{name="ErrnoError";constructor(a){this.rd=a}},tb=class{Fd={};node=null;get flags(){return this.Fd.flags}set flags(a){this.Fd.flags=a}get position(){return this.Fd.position}set position(a){this.Fd.position=a}},ub=class{nd={};od={};Dd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ud=a.ud;this.id=ob++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===
(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function H(a,b={}){if(!a)throw new D(44);b.Xd??(b.Xd=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=lb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ta(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Sa(e+"/"+a[f]);try{d=G(d,a[f])}catch(k){if(44===k?.rd&&g&&b.Le)return{path:e};throw k;}!d.Dd||g&&!b.Xd||(d=d.Dd.root);if(40960===(d.mode&61440)&&(!g||b.Wd)){if(!d.nd.readlink)throw new D(52);
d=d.nd.readlink(d);"/"===d.charAt(0)||(d=Ta(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function vb(a){for(var b;;){if(a===a.parent)return a=a.ud.te,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function wb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pb.length}function xb(a){var b=wb(a.parent.id,a.name);a.Jd=pb[b];pb[b]=a}
function jb(a){var b=wb(a.parent.id,a.name);if(pb[b]===a)pb[b]=a.Jd;else for(b=pb[b];b;){if(b.Jd===a){b.Jd=a.Jd;break}b=b.Jd}}function G(a,b){var c=F(a.mode)?(c=yb(a,"x"))?c:a.nd.lookup?0:2:54;if(c)throw new D(c);for(c=pb[wb(a.id,b)];c;c=c.Jd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.nd.lookup(a,b)}function ib(a,b,c,d){a=new ub(a,b,c,d);xb(a);return a}function F(a){return 16384===(a&61440)}function zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function yb(a,b){if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ab(a,b){if(!F(a.mode))return 54;try{return G(a,b),20}catch(c){}return yb(a,"wx")}function Bb(a,b,c){try{var d=G(a,b)}catch(e){return e.rd}if(a=yb(a,"wx"))return a;if(c){if(!F(d.mode))return 54;if(d===d.parent||"/"===vb(d))return 10}else if(F(d.mode))return 31;return 0}function I(a){a=nb[a];if(!a)throw new D(8);return a}
function Cb(a,b=-1){a=Object.assign(new tb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!nb[b])break a;throw new D(33);}a.fd=b;return nb[b]=a}function Db(a,b=-1){a=Cb(a,b);a.od?.Ze?.(a);return a}function Fb(a,b){var c=null?.od.zd,d=c?null:a;c??=a.nd.zd;if(!c)throw new D(63);c(d,b)}var hb={open(a){a.od=mb[a.node.rdev].od;a.od.open?.(a)},xd(){throw new D(70);}};function db(a,b){mb[a]={od:b}}
function Gb(a,b){var c="/"===b;if(c&&lb)throw new D(10);if(!c&&b){var d=H(b,{Xd:!1});b=d.path;d=d.node;if(d.Dd)throw new D(10);if(!F(d.mode))throw new D(54);}b={type:a,ef:{},te:b,Ke:[]};a=a.ud(b);a.ud=b;b.root=a;c?lb=a:d&&(d.Dd=b,d.ud&&d.ud.Ke.push(b))}function Hb(a,b,c){var d=H(a,{parent:!0}).node;a=Ua(a);if(!a)throw new D(28);if("."===a||".."===a)throw new D(20);var e=Ab(d,a);if(e)throw new D(e);if(!d.nd.Pd)throw new D(63);return d.nd.Pd(d,a,b,c)}function Ib(a){return Hb(a,16895,0)}
function Jb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Hb(a,b|8192,c)}function Kb(a,b){if(!Xa(a))throw new D(44);var c=H(b,{parent:!0}).node;if(!c)throw new D(44);b=Ua(b);var d=Ab(c,b);if(d)throw new D(d);if(!c.nd.symlink)throw new D(63);c.nd.symlink(c,b,a)}
function Lb(a,b,c=438){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=H(a,{Wd:!(b&131072),Le:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=Hb(a,c|511,0);f=!0}if(!d)throw new D(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!F(d.mode))throw new D(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:F(d.mode)&&("r"!==zb(b)||b&576)?31:yb(d,zb(b)):44))throw new D(e);if(b&512&&!f){e=d;e="string"==typeof e?H(e,{Wd:!0}).node:e;if(F(e.mode))throw new D(31);if(32768!==(e.mode&61440))throw new D(28);var g=yb(e,"w");if(g)throw new D(g);Fb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Cb({node:d,path:vb(d),flags:b,seekable:!0,position:0,od:d.od,Ne:[],error:!1});e.od.open&&e.od.open(e);f&&(c&=511,d="string"==typeof d?H(d,{Wd:!0}).node:d,Fb(d,{mode:c&4095|d.mode&-4096,
ctime:Date.now(),Ye:void 0}));!h.logReadFiles||b&1||a in sb||(sb[a]=1);return e}function Mb(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.od.xd)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.od.xd(a,b,c);a.Ne=[]}
function Nb(a,b,c){a=Sa("/dev/"+a);var d=kb(!!b,!!c);Nb.pe??(Nb.pe=64);var e=Nb.pe++<<8|0;db(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,l){for(var m=0,r=0;r<l;r++){try{var y=b()}catch(B){throw new D(29);}if(void 0===y&&0===m)throw new D(6);if(null===y||void 0===y)break;m++;g[k+r]=y}m&&(f.node.atime=Date.now());return m},write(f,g,k,l){for(var m=0;m<l;m++)try{c(g[k+m])}catch(r){throw new D(29);}l&&(f.node.mtime=f.node.ctime=Date.now());return m}});Jb(a,d,e)}var J={};
function Ob(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":I(a).path;if(0==b.length)throw new D(44);return a+"/"+b}
var Qa=void 0,Pb=0,Qb={},Rb=a=>{a instanceof Ba||"unwind"==a||fa(1,a)},Sb=a=>{qa=a;Ia||0<Pb||(h.onExit?.(a),pa=!0);fa(a,new Ba(a))},Tb=a=>{qa=a;Sb(a)},Ub=a=>{if(!pa)try{if(a(),!(Ia||0<Pb))try{qa=a=qa,Sb(a)}catch(b){Rb(b)}}catch(b){Rb(b)}},Vb=[],Wb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?A(q,a):"":a;return Wb[a]||("undefined"!=typeof document?document.querySelector(a):null)},Xb=a=>0>Wb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};
function Yb(a){var b=L.td[a];b.target.removeEventListener(b.vd,b.ke,b.Gd);L.td.splice(a,1)}function Zb(){if(navigator.userActivation?navigator.userActivation.isActive:L.Zd&&L.Be.Rd){var a=L.Cd;L.Cd=[];for(var b of a)b.be(...b.ge)}}function $b(a){if(!a.target)return-4;if(a.Hd)a.ke=function(c){++L.Zd;L.Be=a;Zb();a.Id(c);Zb();--L.Zd},a.target.addEventListener(a.vd,a.ke,a.Gd),L.td.push(a);else for(var b=0;b<L.td.length;++b)L.td[b].target==a.target&&L.td[b].vd==a.vd&&Yb(b--);return 0}
var L={Pe:0,af:0,$d:0,Qd:0,fe:0,de:0,Vd:0,Xe:0,ff:0,We:0,$e:0,gf:0,nf:0,ce:0,cf(a,b,c){p.set(p.subarray(b,b+c),a)},jf(){for(;L.td.length;)Yb(L.td.length-1);L.Cd=[]},Zd:0,Cd:[],Ve(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of L.Cd)if(e.be==a&&d(e.ge,c))return;L.Cd.push({be:a,we:b,ge:c});L.Cd.sort((f,g)=>f.we<g.we)},kf(a){L.Cd=L.Cd.filter(b=>b.be!=a)},td:[],Me:(a,b)=>{for(var c=0;c<L.td.length;++c)L.td[c].target!=a||b&&b!=L.td[c].vd||
Yb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},ac=[],bc,O=a=>{var b=ac[a];b||(ac[a]=b=bc.get(a));return b},cc=(a,b,c,d,e,f)=>{L.Vd||(L.Vd=P(256));a={target:K(a),vd:f,Hd:d,Id:(g=event)=>{var k=g.target.id?g.target.id:"",l=L.Vd,m=g.target;C(m?m==window?"#window":m==screen?"#screen":m?.nodeName||"":"",q,l+0,128);C(k,q,l+128,128);O(d)(e,l,b)&&g.preventDefault()},Gd:c};return $b(a)},dc=(a,b,c,d,e,f)=>{L.$d||(L.$d=P(160));a={target:K(a),vd:f,Hd:d,Id:g=>
{var k=L.$d;w[k>>3]=g.timeStamp;var l=k>>2;t[l+2]=g.location;p[k+12]=g.ctrlKey;p[k+13]=g.shiftKey;p[k+14]=g.altKey;p[k+15]=g.metaKey;p[k+16]=g.repeat;t[l+5]=g.charCode;t[l+6]=g.keyCode;t[l+7]=g.which;C(g.key||"",q,k+32,32);C(g.code||"",q,k+64,32);C(g.char||"",q,k+96,32);C(g.locale||"",q,k+128,32);O(d)(e,k,b)&&g.preventDefault()},Gd:c};return $b(a)},ec=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+
26]=b.altKey;p[a+27]=b.metaKey;sa[2*d+14]=b.button;sa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Xb(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},fc=(a,b,c,d,e,f)=>{L.Qd||(L.Qd=P(64));a=K(a);return $b({target:a,Rd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,vd:f,Hd:d,Id:(g=event)=>{ec(L.Qd,g,a);O(d)(e,L.Qd,b)&&g.preventDefault()},Gd:c})},gc=(a,b,c,d)=>{L.de||(L.de=P(36));a=K(a);return $b({target:a,vd:"resize",Hd:d,Id:(e=event)=>{if(e.target==a){var f=document.body;
if(f){var g=L.de;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;O(d)(10,g,b)&&e.preventDefault()}}},Gd:c})},hc=(a,b,c,d,e,f)=>{L.ce||(L.ce=P(1552));a=K(a);return $b({target:a,Rd:"touchstart"==f||"touchend"==f,vd:f,Hd:d,Id:g=>{var k={},l=g.touches;for(var m of l)m.oe=m.ve=0,k[m.identifier]=m;for(var r of g.changedTouches)r.oe=1,k[r.identifier]=r;for(var y of g.targetTouches)k[y.identifier].ve=
1;l=L.ce;w[l>>3]=g.timeStamp;p[l+12]=g.ctrlKey;p[l+13]=g.shiftKey;p[l+14]=g.altKey;p[l+15]=g.metaKey;m=l+16;r=Xb(a);y=0;for(let B of Object.values(k))if(k=m>>2,t[k]=B.identifier,t[k+1]=B.screenX,t[k+2]=B.screenY,t[k+3]=B.clientX,t[k+4]=B.clientY,t[k+5]=B.pageX,t[k+6]=B.pageY,p[m+28]=B.oe,p[m+29]=B.ve,t[k+8]=B.clientX-(r.left|0),t[k+9]=B.clientY-(r.top|0),m+=48,31<++y)break;t[l+8>>2]=y;O(d)(e,l,b)&&g.preventDefault()},Gd:c})},ic=(a,b,c,d)=>{L.fe||(L.fe=P(96));return $b({target:a,Rd:!0,vd:"wheel",Hd:d,
Id:(e=event)=>{var f=L.fe;ec(f,e,a);w[f+64>>3]=e.deltaX;w[f+72>>3]=e.deltaY;w[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;O(d)(9,f,b)&&e.preventDefault()},Gd:c})},Q,jc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},kc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=
()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},lc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},mc=a=>{a.ie=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},nc=a=>{a.re=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},oc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},pc=1,qc=[],S=[],rc=[],sc=[],tc=[],T=[],uc=[],vc=[],wc=[],xc=[],yc={},zc={},Ac=4,Bc=0,Cc=a=>{for(var b=pc++,c=a.length;c<b;c++)a[c]=null;return b},Dc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=Q[c](),g=f&&Cc(d);f?(f.name=g,d[g]=f):U||=1282;t[b+4*e>>2]=g}},Fc=(a,b)=>{a.Fd||(a.Fd=a.getContext,a.getContext=function(d,e){e=a.Fd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.qe?a.getContext("webgl2",b):a.getContext("webgl",
b);return c?Ec(c,b):0},Ec=(a,b)=>{var c=Cc(vc),d={handle:c,attributes:b,version:b.qe,Ed:a};a.canvas&&(a.canvas.Ae=d);vc[c]=d;("undefined"==typeof b.je||b.je)&&Gc(d);return c},Gc=a=>{a||=V;if(!a.Fe){a.Fe=!0;var b=a.Ed;b.Kd=b.getExtension("WEBGL_multi_draw");b.Ee=b.getExtension("EXT_polygon_offset_clamp");b.De=b.getExtension("EXT_clip_control");b.ze=b.getExtension("WEBGL_polygon_mode");jc(b);kc(b);lc(b);mc(b);nc(b);2<=a.version&&(b.Td=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||
!b.Td)b.Td=b.getExtension("EXT_disjoint_timer_query");oc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Hc=["default","low-power","high-performance"],Ic={},Kc=()=>{if(!Jc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ic)void 0===Ic[b]?delete a[b]:a[b]=Ic[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Jc=
c}return Jc},Jc,Lc=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=u[b>>2],k=u[b+4>>2];b+=8;var l=a;var m=g,r=k,y=d,B=p;if(0>r||0>y)throw new D(28);if(null===l.fd)throw new D(8);if(1===(l.flags&2097155))throw new D(8);if(F(l.node.mode))throw new D(31);if(!l.od.read)throw new D(28);g="undefined"!=typeof y;if(!g)y=l.position;else if(!l.seekable)throw new D(70);m=l.od.read(l,B,m,r,y);g||(l.position+=m);l=m;if(0>l)return-1;e+=l;if(l<k)break;"undefined"!=typeof d&&(d+=l)}return e},Mc=[],Nc=()=>{var a=oc(Q);
return a=a.concat(a.map(b=>"GL_"+b))},Oc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(U||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=Q.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>V.version){U||=1282;return}d=Nc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=Q.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U||=1280;return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:U||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:p[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){U||=
1280;n(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:U||=1280;n(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:p[b]=d?1:0}}else U||=1281},Pc=a=>{var b=ab(a)+1,c=P(b);c&&C(a,q,c,b);return c},Qc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),
Rc=a=>{a-=5120;return 0==a?p:1==a?q:2==a?sa:4==a?t:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?u:ua},Sc=(a,b,c,d,e)=>{a=Rc(a);b=d*((Bc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Ac-1&-Ac);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=Q.Ce;if(b){var c=b.Ld[a];"number"==typeof c&&(b.Ld[a]=c=Q.getUniformLocation(b,b.xe[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Tc=[],Uc=(a,
b=[])=>O(a)(...b),Wc=a=>{var b=ab(a)+1,c=Vc(b);C(a,q,c,b);return c};pb=Array(4096);Gb(E,"/");Ib("/tmp");Ib("/home");Ib("/home/web_user");(function(){Ib("/dev");db(259,{read:()=>0,write:(d,e,f,g)=>g,xd:()=>0});Jb("/dev/null",259);cb(1280,fb);cb(1536,gb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Wa(a),b=a.byteLength);return a[--b]};Nb("random",c);Nb("urandom",c);Ib("/dev/shm");Ib("/dev/shm/tmp")})();
(function(){Ib("/proc");var a=Ib("/proc/self");Ib("/proc/self/fd");Gb({ud(){var b=ib(a,"fd",16895,73);b.od={xd:E.od.xd};b.nd={lookup(c,d){c=+d;var e=I(c);c={parent:null,ud:{te:"fake"},nd:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(nb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();for(let a=0;32>a;++a)Mc.push(Array(a));for(var Xc=new Float32Array(288),Yc=0;288>=Yc;++Yc)Tc[Yc]=Xc.subarray(0,Yc);h.noExitRuntime&&(Ia=h.noExitRuntime);
h.print&&(na=h.print);h.printErr&&(n=h.printErr);h.wasmBinary&&(oa=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
h.ccall=(a,b,c,d)=>{var e={string:m=>{var r=0;null!==m&&void 0!==m&&0!==m&&(r=Wc(m));return r},array:m=>{var r=Vc(m.length);p.set(m,r);return r}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var l=e[c[k]];l?(0===g&&(g=X()),f[k]=l(d[k])):f[k]=d[k]}c=a(...f);return c=function(m){0!==g&&Y(g);return"string"===b?m?A(q,m):"":"boolean"===b?!!m:m}(c)};
var Zc={1191320:a=>{h.setFullsize(a)},1191348:()=>{var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},1191450:()=>{var a=h.canvas.getContext("webgl2").getExtension("WEBGL_compressed_texture_astc").getSupportedProfiles();return(0<=a.indexOf("ldr")?1:0)|(0<=a.indexOf("hdr")?2:0)}},$c,P,ad,Z,Na,Y,Vc,X,bd,cd,Oa,dd,Hd={k:a=>{var b=new Ma(a);0==p[b.sd+12]&&(p[b.sd+12]=1,Ka--);p[b.sd+13]=0;Ja.push(b);cd(a);return dd(a)},p:()=>{Z(0,0);var a=Ja.pop();bd(a.le);La=0},a:()=>Pa([]),g:a=>Pa([a]),
_:(a,b)=>Pa([a,b]),ua:()=>{var a=Ja.pop();a||wa("no exception to throw");var b=a.le;0==p[a.sd+13]&&(Ja.push(a),p[a.sd+13]=1,p[a.sd+12]=0,Ka++);La=b;throw La;},j:(a,b,c)=>{var d=new Ma(a);u[d.sd+16>>2]=0;u[d.sd+4>>2]=b;u[d.sd+8>>2]=c;La=a;Ka++;throw La;},Kb:()=>Ka,d:a=>{La||=a;throw La;},ra:function(a,b,c){Qa=c;try{var d=I(a);switch(b){case 0:var e=z();if(0>e)break;for(;nb[e];)e++;return Db(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=z(),d.flags|=e,0;case 12:return e=z(),sa[e+
0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.rd}},Sb:function(a,b){try{var c=I(a),d=c.node,e=c.od.wd;a=e?c:d;e??=d.nd.wd;if(!e)throw new D(63);var f=e(a);u[b>>2]=f.dev;u[b+4>>2]=f.mode;u[b+8>>2]=f.nlink;u[b+12>>2]=f.uid;u[b+16>>2]=f.gid;u[b+20>>2]=f.rdev;x[b+24>>3]=BigInt(f.size);t[b+32>>2]=4096;t[b+36>>2]=f.blocks;var g=f.atime.getTime(),k=f.mtime.getTime(),l=f.ctime.getTime();x[b+40>>3]=BigInt(Math.floor(g/1E3));u[b+48>>2]=
g%1E3*1E6;x[b+56>>3]=BigInt(Math.floor(k/1E3));u[b+64>>2]=k%1E3*1E6;x[b+72>>3]=BigInt(Math.floor(l/1E3));u[b+80>>2]=l%1E3*1E6;x[b+88>>3]=BigInt(f.ino);return 0}catch(m){if("undefined"==typeof J||"ErrnoError"!==m.name)throw m;return-m.rd}},Vb:function(a,b,c){Qa=c;try{var d=I(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ad.He){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=z();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>
2]=35387;for(var f=0;32>f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ad.Ie)for(e=z(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=z();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=z();if(!d.od.Ge)throw new D(59);return d.od.Ge(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ad.Je&&(f=[24,80],e=z(),sa[e>>1]=f[0],sa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?
0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return-g.rd}},sa:function(a,b,c,d){Qa=d;try{b=b?A(q,b):"";b=Ob(a,b);var e=d?z():0;return Lb(b,c,e).fd}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.rd}},Nb:function(a,b,c,d){try{b=b?A(q,b):"";d=d?A(q,d):"";b=Ob(a,b);d=Ob(c,d);a=b;var e=Ta(a),f=Ta(d),g=Ua(a),k=Ua(d);var l=H(a,{parent:!0});var m=l.node;l=H(d,{parent:!0});var r=l.node;if(!m||!r)throw new D(44);
if(m.ud!==r.ud)throw new D(75);var y=G(m,g),B=Ya(a,f);if("."!==B.charAt(0))throw new D(28);B=Ya(d,e);if("."!==B.charAt(0))throw new D(55);try{var N=G(r,k)}catch(M){}if(y!==N){var ka=F(y.mode),R=Bb(m,g,ka);if(R)throw new D(R);if(R=N?Bb(r,k,ka):Ab(r,k))throw new D(R);if(!m.nd.rename)throw new D(63);if(y.Dd||N&&N.Dd)throw new D(10);if(r!==m&&(R=yb(m,"w")))throw new D(R);jb(y);try{m.nd.rename(y,r,k),y.parent=r}catch(M){throw M;}finally{xb(y)}}return 0}catch(M){if("undefined"==typeof J||"ErrnoError"!==
M.name)throw M;return-M.rd}},Ob:function(a,b,c){try{b=b?A(q,b):"";b=Ob(a,b);if(c)if(512===c){var d=b,e=H(d,{parent:!0}).node,f=Ua(d),g=G(e,f),k=Bb(e,f,!0);if(k)throw new D(k);if(!e.nd.rmdir)throw new D(63);if(g.Dd)throw new D(10);e.nd.rmdir(e,f);jb(g)}else return-28;else{e=b;d=H(e,{parent:!0}).node;if(!d)throw new D(44);var l=Ua(e),m=G(d,l),r=Bb(d,l,!1);if(r)throw new D(r);if(!d.nd.unlink)throw new D(63);if(m.Dd)throw new D(10);d.nd.unlink(d,l);jb(m)}return 0}catch(y){if("undefined"==typeof J||"ErrnoError"!==
y.name)throw y;return-y.rd}},Wb:()=>wa(""),Hb:()=>{Ia=!1;Pb=0},Ib:(a,b)=>{Qb[a]&&(clearTimeout(Qb[a].id),delete Qb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Qb[a];Ub(()=>ad(a,performance.now()))},b);Qb[a]={id:c,mf:b};return 0},Jb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();u[a>>2]=60*Math.max(f,e);t[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%
60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(C(a,q,c,17),C(b,q,d,17)):(C(a,q,d,17),C(b,q,c,17))},Lb:function(a,b,c){if(!(0<=a&&3>=a))return 28;x[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},ta:function(a){if("undefined"!==typeof process){if(1==a)return process.stdout.isTTY;if(2==a)return process.stderr.isTTY}return!1},_b:function(a,b){a=a?A(q,a,b):"";if("undefined"!==typeof process&&a in process.env){a=process.env[a];b=ab(a)+1;var c=P(b);C(a,q,c,b);return c}return 0},
$:(a,b,c)=>{Vb.length=0;for(var d;d=q[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Vb.push(112==d?u[c>>2]:106==d?x[c>>3]:105==d?t[c>>2]:w[c>>3]);c+=e?8:4}return Zc[a](...Vb)},q:(a,b,c)=>{a=K(a);if(!a)return-4;t[b>>2]=a.width;t[c>>2]=a.height},la:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,y:(a,b,c)=>{a=K(a);if(!a)return-4;a=Xb(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},Mb:a=>{var b=q.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);va();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},mc:(a,b,c,d)=>cc(a,b,c,d,12,"blur"),ha:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},wc:(a,b,c,d)=>cc(a,b,c,d,13,"focus"),na:(a,b,c,d)=>dc(a,b,c,d,2,"keydown"),ma:(a,b,c,d)=>dc(a,b,c,d,3,"keyup"),bc:(a,b,c,d)=>fc(a,b,c,d,5,"mousedown"),Qb:(a,b,c,d)=>fc(a,b,c,d,8,"mousemove"),Yb:(a,b,c,d)=>fc(a,b,c,d,6,"mouseup"),
Fc:(a,b,c,d)=>gc(a,b,c,d),Db:(a,b,c,d)=>hc(a,b,c,d,23,"touchend"),yb:(a,b,c,d)=>hc(a,b,c,d,24,"touchmove"),Eb:(a,b,c,d)=>hc(a,b,c,d,22,"touchstart"),Fb:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?ic(a,b,c,d):-1:-4,Oc:()=>V&&V.Ed&&V.attributes.me?0:-3,Za:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:Hc[t[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],qe:t[c+4],df:t[c+5],je:p[b+24],
me:p[b+25],hf:t[c+7],lf:p[b+32]};a=K(a);return!a||b.me?0:Fc(a,b)},ob:a=>{V==a&&(V=0);V===vc[a]&&(V=null);"object"==typeof L&&L.Me(vc[a].Ed.canvas);vc[a]?.Ed.canvas&&(vc[a].Ed.canvas.Ae=void 0);vc[a]=null},Ra:(a,b)=>{a=vc[a];b=b?A(q,b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&jc(Q);"OES_vertex_array_object"==b&&kc(Q);"WEBGL_draw_buffers"==b&&lc(Q);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&mc(Q);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&nc(Q);"WEBGL_multi_draw"==
b&&(Q.Kd=Q.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(Q.Ee=Q.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(Q.De=Q.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(Q.ze=Q.getExtension("WEBGL_polygon_mode"));return!!a.Ed.getExtension(b)},Qa:()=>V?V.handle:0,Ta:a=>{V=vc[a];h.ctx=Q=V?.Ed;return!a||Q?0:-5},Xb:(a,b)=>{var c=0,d=0,e;for(e of Kc()){var f=b+c;u[a+d>>2]=f;c+=C(e,q,f,Infinity)+1;d+=4}return 0},Zb:(a,b)=>{var c=Kc();u[a>>2]=c.length;a=0;for(var d of c)a+=
ab(d)+1;u[b>>2]=a;return 0},O:Tb,ba:function(a){try{var b=I(a);if(null===b.fd)throw new D(8);b.Yd&&(b.Yd=null);try{b.od.close&&b.od.close(b)}catch(c){throw c;}finally{nb[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return c.rd}},Pb:function(a,b,c,d,e){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(d))return 61;var f=I(a),g=Lc(f,b,c,d);u[e>>2]=g;return 0}catch(k){if("undefined"==typeof J||"ErrnoError"!==k.name)throw k;return k.rd}},
Ub:function(a,b,c,d){try{var e=I(a),f=Lc(e,b,c);u[d>>2]=f;return 0}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return g.rd}},Rb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=I(a);Mb(e,b,c);x[d>>3]=BigInt(e.position);e.Yd&&0===b&&0===c&&(e.Yd=null);return 0}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return f.rd}},Tb:function(a,b,c,d){try{a:{var e=I(a);a=b;for(var f,g=b=0;g<c;g++){var k=u[a>>2],l=
u[a+4>>2];a+=8;var m=e,r=k,y=l,B=f,N=p;if(0>y||0>B)throw new D(28);if(null===m.fd)throw new D(8);if(0===(m.flags&2097155))throw new D(8);if(F(m.node.mode))throw new D(31);if(!m.od.write)throw new D(28);m.seekable&&m.flags&1024&&Mb(m,0,2);var ka="undefined"!=typeof B;if(!ka)B=m.position;else if(!m.seekable)throw new D(70);var R=m.od.write(m,N,r,y,B,void 0);ka||(m.position+=R);var M=R;if(0>M){var ta=-1;break a}b+=M;if(M<l)break;"undefined"!=typeof f&&(f+=M)}ta=b}u[d>>2]=ta;return 0}catch(Eb){if("undefined"==
typeof J||"ErrnoError"!==Eb.name)throw Eb;return Eb.rd}},da:a=>Q.activeTexture(a),r:(a,b)=>{Q.attachShader(S[a],T[b])},tb:(a,b)=>{Q.beginQuery(a,wc[b])},ja:(a,b)=>{35051==a?Q.Sd=b:35052==a&&(Q.Bd=b);Q.bindBuffer(a,qc[b])},N:(a,b,c)=>{Q.bindBufferBase(a,b,qc[c])},ia:(a,b,c,d,e)=>{Q.bindBufferRange(a,b,qc[c],d,e)},t:(a,b)=>{Q.bindFramebuffer(a,rc[b])},ga:(a,b)=>{Q.bindRenderbuffer(a,sc[b])},wa:(a,b)=>{Q.bindTexture(a,tc[b])},P:(a,b)=>{Q.bindTransformFeedback(a,xc[b])},X:a=>{Q.bindVertexArray(uc[a])},
C:(a,b)=>Q.blendFunc(a,b),Oa:(a,b,c,d,e,f,g,k,l,m)=>Q.blitFramebuffer(a,b,c,d,e,f,g,k,l,m),kb:(a,b,c,d)=>{2<=V.version?c&&b?Q.bufferData(a,q,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?q.subarray(c,c+b):b,d)},jb:(a,b,c,d)=>{2<=V.version?c&&Q.bufferSubData(a,b,q,d,c):Q.bufferSubData(a,b,q.subarray(d,d+c))},Ja:a=>Q.checkFramebufferStatus(a),Ma:a=>Q.clear(a),Fa:(a,b,c,d)=>Q.clearBufferfi(a,b,c,d),Ga:(a,b,c)=>{Q.clearBufferfv(a,b,v,c>>2)},Ia:(a,b,c)=>{Q.clearBufferiv(a,b,t,c>>2)},Ha:(a,b,c)=>{Q.clearBufferuiv(a,
b,u,c>>2)},_a:(a,b,c,d)=>Q.clearColor(a,b,c,d),cc:a=>Q.clearDepth(a),ec:a=>{Q.compileShader(T[a])},va:(a,b,c,d,e,f,g,k,l)=>{2<=V.version?Q.Bd||!k?Q.compressedTexSubImage2D(a,b,c,d,e,f,g,k,l):Q.compressedTexSubImage2D(a,b,c,d,e,f,g,q,l,k):Q.compressedTexSubImage2D(a,b,c,d,e,f,g,q.subarray(l,l+k))},uc:(a,b,c,d,e,f,g,k,l,m,r)=>{Q.Bd?Q.compressedTexSubImage3D(a,b,c,d,e,f,g,k,l,m,r):Q.compressedTexSubImage3D(a,b,c,d,e,f,g,k,l,q,r,m)},nb:(a,b,c,d,e)=>Q.copyBufferSubData(a,b,c,d,e),Ba:(a,b,c,d,e,f,g,k)=>
Q.copyTexSubImage2D(a,b,c,d,e,f,g,k),Aa:(a,b,c,d,e,f,g,k,l)=>Q.copyTexSubImage3D(a,b,c,d,e,f,g,k,l),B:()=>{var a=Cc(S),b=Q.createProgram();b.name=a;b.Od=b.Md=b.Nd=0;b.ee=1;S[a]=b;return a},hc:a=>{var b=Cc(T);T[b]=Q.createShader(a);return b},pb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=qc[d];e&&(Q.deleteBuffer(e),e.name=0,qc[d]=null,d==Q.Sd&&(Q.Sd=0),d==Q.Bd&&(Q.Bd=0))}},hb:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=rc[d];e&&(Q.deleteFramebuffer(e),e.name=0,rc[d]=null)}},za:a=>{if(a){var b=
S[a];b?(Q.deleteProgram(b),b.name=0,S[a]=null):U||=1281}},J:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=wc[d];e&&(Q.deleteQuery(e),wc[d]=null)}},cb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=sc[d];e&&(Q.deleteRenderbuffer(e),e.name=0,sc[d]=null)}},gc:a=>{if(a){var b=T[a];b?(Q.deleteShader(b),T[a]=null):U||=1281}},Hc:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=tc[d];e&&(Q.deleteTexture(e),e.name=0,tc[d]=null)}},nc:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];Q.deleteVertexArray(uc[d]);
uc[d]=null}},Q:a=>{Q.depthMask(!!a)},ac:(a,b)=>Q.depthRange(a,b),w:a=>Q.disable(a),tc:(a,b,c)=>{Q.drawArrays(a,b,c)},qc:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},Ya:(a,b,c,d,e)=>{Q.ie.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},Ea:(a,b)=>{for(var c=Mc[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];Q.drawBuffers(c)},rc:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},pc:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},M:(a,b,c,d,e,f,g)=>{Q.ie.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,f,g)},sc:(a,b,c,
d,e,f)=>{Q.drawElements(a,d,e,f)},u:a=>Q.enable(a),lc:a=>{Q.enableVertexAttribArray(a)},sb:a=>Q.endQuery(a),gb:(a,b,c,d)=>{Q.framebufferRenderbuffer(a,b,c,sc[d])},fb:(a,b,c,d,e)=>{Q.framebufferTexture2D(a,b,c,tc[d],e)},eb:(a,b,c,d,e)=>{Q.framebufferTextureLayer(a,b,tc[c],d,e)},qb:(a,b)=>{Dc(a,b,"createBuffer",qc)},ib:(a,b)=>{Dc(a,b,"createFramebuffer",rc)},vb:(a,b)=>{Dc(a,b,"createQuery",wc)},db:(a,b)=>{Dc(a,b,"createRenderbuffer",sc)},Ic:(a,b)=>{Dc(a,b,"createTexture",tc)},Pa:(a,b)=>{Dc(a,b,"createTransformFeedback",
xc)},oc:(a,b)=>{Dc(a,b,"createVertexArray",uc)},Gc:a=>Q.generateMipmap(a),mb:(a,b,c)=>{c?t[c>>2]=Q.getBufferParameter(a,b):U||=1281},lb:(a,b,c,d)=>{d?c&&Q.getBufferSubData(a,b,q,d,c):U||=1281},rb:()=>{var a=Q.getError()||U;U=0;return a},$a:(a,b)=>Oc(a,b,2),I:(a,b)=>Oc(a,b,0),ya:(a,b,c,d)=>{a=Q.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,q,d,b):0;c&&(t[c>>2]=b)},Z:(a,b,c)=>{if(c)if(a>=pc)U||=1281;else if(a=S[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
t[c>>2]=a.length+1;else if(35719==b){if(!a.Od){var d=Q.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Od=Math.max(a.Od,Q.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.Od}else if(35722==b){if(!a.Md)for(d=Q.getProgramParameter(a,35721),b=0;b<d;++b)a.Md=Math.max(a.Md,Q.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Md}else if(35381==b){if(!a.Nd)for(d=Q.getProgramParameter(a,35382),b=0;b<d;++b)a.Nd=Math.max(a.Nd,Q.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Nd}else t[c>>2]=Q.getProgramParameter(a,
b);else U||=1281},ub:(a,b,c)=>{if(c){a=wc[a];b=2>V.version?Q.Td.getQueryObjectEXT(a,b):Q.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;u[c>>2]=d;u[c+4>>2]=(d-u[c>>2])/4294967296}else U||=1281},dc:(a,b,c,d)=>{a=Q.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,q,d,b):0;c&&(t[c>>2]=b)},Y:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(T[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=Q.getShaderParameter(T[a],
b):U||=1281},D:a=>{var b=yc[a];if(!b){switch(a){case 7939:b=Pc(Nc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||(U||=1280);b=b?Pc(b):0;break;case 7938:b=Q.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=V.version&&(c=`OpenGL ES 3.0 (${b})`);b=Pc(c);break;case 35724:b=Q.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Pc(b);break;default:U||=1280}yc[a]=
b}return b},ka:(a,b)=>{if(2>V.version)return U||=1282,0;var c=zc[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Nc().map(Pc),c=zc[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},Wc:(a,b)=>Q.getUniformBlockIndex(S[a],b?A(q,b):""),Xc:(a,b)=>{b=b?A(q,b):"";if(a=S[a]){var c=a,d=c.Ld,e=c.ye,f;if(!d){c.Ld=d={};c.xe={};var g=Q.getProgramParameter(c,35718);for(f=0;f<g;++f){var k=Q.getActiveUniform(c,f);var l=k.name;k=k.size;var m=Qc(l);m=0<m?l.slice(0,m):
l;var r=c.ee;c.ee+=k;e[m]=[k,r];for(l=0;l<k;++l)d[r]=l,c.xe[r++]=m}}c=a.Ld;d=0;e=b;f=Qc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ye[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else U||=1281;return-1},La:(a,b,c)=>{for(var d=Mc[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];Q.invalidateFramebuffer(a,d)},Ka:(a,b,c,d,e,f,g)=>{for(var k=Mc[b],l=0;l<b;l++)k[l]=t[c+4*l>>2];Q.invalidateSubFramebuffer(a,k,d,e,f,g)},E:a=>{a=S[a];Q.linkProgram(a);a.Ld=0;a.ye={}},Xa:(a,b,c,d)=>
{Q.Kd.multiDrawArraysWEBGL(a,t,b>>2,t,c>>2,d)},Va:(a,b,c,d,e)=>{Q.Kd.multiDrawArraysInstancedWEBGL(a,t,b>>2,t,c>>2,t,d>>2,e)},Sa:(a,b,c,d,e,f)=>{Q.re.multiDrawArraysInstancedBaseInstanceWEBGL(a,t,b>>2,t,c>>2,t,d>>2,u,e>>2,f)},Wa:(a,b,c,d,e)=>{Q.Kd.multiDrawElementsWEBGL(a,t,b>>2,c,t,d>>2,e)},Ua:(a,b,c,d,e,f)=>{Q.Kd.multiDrawElementsInstancedWEBGL(a,t,b>>2,c,t,d>>2,t,e>>2,f)},ea:(a,b,c,d,e,f,g,k)=>{Q.re.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,t,b>>2,c,t,d>>2,t,e>>2,t,f>>2,u,g>>2,k)},
L:(a,b)=>{3317==a?Ac=b:3314==a&&(Bc=b);Q.pixelStorei(a,b)},$b:(a,b)=>{Q.ze.polygonModeWEBGL(a,b)},fa:(a,b)=>Q.polygonOffset(a,b),Da:a=>Q.readBuffer(a),Ca:(a,b,c,d,e,f,g)=>{if(2<=V.version)if(Q.Sd)Q.readPixels(a,b,c,d,e,f,g);else{var k=Rc(f);g>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);Q.readPixels(a,b,c,d,e,f,k,g)}else(k=Sc(f,e,c,d,g))?Q.readPixels(a,b,c,d,e,f,k):U||=1280},bb:(a,b,c,d)=>Q.renderbufferStorage(a,b,c,d),ab:(a,b,c,d,e)=>Q.renderbufferStorageMultisample(a,b,c,d,e),R:(a,b,c,d)=>Q.scissor(a,
b,c,d),fc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=u[c+4*f>>2])?A(q,g,d?u[d+4*f>>2]:void 0):"";e+=g}Q.shaderSource(T[a],e)},yc:(a,b,c,d,e,f,g,k,l)=>{if(2<=V.version){if(Q.Bd){Q.texImage2D(a,b,c,d,e,f,g,k,l);return}if(l){var m=Rc(k);l>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);Q.texImage2D(a,b,c,d,e,f,g,k,m,l);return}}m=l?Sc(k,g,d,e,l):null;Q.texImage2D(a,b,c,d,e,f,g,k,m)},xc:(a,b,c,d,e,f,g,k,l,m)=>{if(Q.Bd)Q.texImage3D(a,b,c,d,e,f,g,k,l,m);else if(m){var r=Rc(l);Q.texImage3D(a,b,c,d,e,f,g,k,l,r,
m>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else Q.texImage3D(a,b,c,d,e,f,g,k,l,null)},Dc:(a,b,c)=>Q.texParameterf(a,b,c),Bc:(a,b,c)=>{Q.texParameterf(a,b,v[c>>2])},Ec:(a,b,c)=>Q.texParameteri(a,b,c),Cc:(a,b,c)=>{Q.texParameteri(a,b,t[c>>2])},Ac:(a,b,c,d,e)=>Q.texStorage2D(a,b,c,d,e),zc:(a,b,c,d,e,f)=>Q.texStorage3D(a,b,c,d,e,f),ca:(a,b,c,d,e,f,g,k,l)=>{if(2<=V.version){if(Q.Bd){Q.texSubImage2D(a,b,c,d,e,f,g,k,l);return}if(l){var m=Rc(k);Q.texSubImage2D(a,b,c,d,e,f,g,k,m,l>>>31-Math.clz32(m.BYTES_PER_ELEMENT));
return}}l=l?Sc(k,g,e,f,l):null;Q.texSubImage2D(a,b,c,d,e,f,g,k,l)},vc:(a,b,c,d,e,f,g,k,l,m,r)=>{if(Q.Bd)Q.texSubImage3D(a,b,c,d,e,f,g,k,l,m,r);else if(r){var y=Rc(m);Q.texSubImage3D(a,b,c,d,e,f,g,k,l,m,y,r>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else Q.texSubImage3D(a,b,c,d,e,f,g,k,l,m,null)},xa:(a,b,c,d)=>{a=S[a];for(var e=[],f=0;f<b;f++){var g=e,k=g.push;var l=(l=t[c+4*f>>2])?A(q,l):"";k.call(g,l)}Q.transformFeedbackVaryings(a,e,d)},Vc:(a,b)=>{Q.uniform1f(W(a),b)},Nc:(a,b,c)=>{if(2<=V.version)b&&
Q.uniform1fv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Tc[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);Q.uniform1fv(W(a),d)}},Rc:(a,b)=>{Q.uniform1i(W(a),b)},Qc:(a,b)=>{Q.uniform1ui(W(a),b)},Uc:(a,b,c)=>{Q.uniform2f(W(a),b,c)},Pc:(a,b,c)=>{Q.uniform2ui(W(a),b,c)},Tc:(a,b,c,d)=>{Q.uniform3f(W(a),b,c,d)},Mc:(a,b,c)=>{if(2<=V.version)b&&Q.uniform3fv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Tc[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=
v.subarray(c>>2,c+12*b>>2);Q.uniform3fv(W(a),d)}},Sc:(a,b,c,d,e)=>{Q.uniform4f(W(a),b,c,d,e)},Lc:(a,b,c)=>{if(2<=V.version)b&&Q.uniform4fv(W(a),v,c>>2,4*b);else{if(72>=b){var d=Tc[4*b],e=v;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);Q.uniform4fv(W(a),d)}},m:(a,b,c)=>{a=S[a];Q.uniformBlockBinding(a,b,c)},Kc:(a,b,c,d)=>{if(2<=V.version)b&&Q.uniformMatrix3fv(W(a),!!c,v,d>>2,9*b);else{if(32>=b){b*=9;for(var e=Tc[b],
f=0;f<b;f+=9)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2],e[f+4]=v[d+(4*f+16)>>2],e[f+5]=v[d+(4*f+20)>>2],e[f+6]=v[d+(4*f+24)>>2],e[f+7]=v[d+(4*f+28)>>2],e[f+8]=v[d+(4*f+32)>>2]}else e=v.subarray(d>>2,d+36*b>>2);Q.uniformMatrix3fv(W(a),!!c,e)}},Jc:(a,b,c,d)=>{if(2<=V.version)b&&Q.uniformMatrix4fv(W(a),!!c,v,d>>2,16*b);else{if(18>=b){var e=Tc[16*b],f=v;d>>=2;b*=16;for(var g=0;g<b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+
4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=v.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(W(a),!!c,e)}},x:a=>{a=S[a];Q.useProgram(a);Q.Ce=a},ic:(a,b)=>{Q.vertexAttribDivisor(a,b)},kc:(a,b,c,d,e)=>{Q.vertexAttribIPointer(a,b,c,d,e)},jc:(a,b,c,d,e,f)=>{Q.vertexAttribPointer(a,b,c,!!d,e,f)},Na:(a,b,c,d)=>Q.viewport(a,b,c,d),qa:ed,Cb:fd,c:gd,b:hd,f:jd,H:kd,v:ld,Ab:md,z:nd,
n:od,V:pd,T:qd,oa:rd,zb:sd,pa:td,W:ud,Bb:vd,i:wd,l:xd,e:yd,h:zd,o:Ad,U:Bd,A:Cd,s:Dd,K:Ed,S:Fd,aa:Gd,G:a=>a,wb:function(){var a="#"+h.canvas.id,b=ab(a)+1,c=P(b);C(a,q,c,b);return c},xb:function(){var a=h.keyboardListeningElement||document;if(a===document)return 1;if(a===window)return 2;if("id"in a){a="#"+a.id;var b=ab(a)+1,c=P(b);C(a,q,c,b);return c}return 0},F:function(a,b){function c(){var d=window.requestAnimationFrame(c);Uc(a,[b])||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},
Yc:function(a,b){(h.canvas.closest(".mn-container")||document.getElementById("container")).className=["mn-container",a?A(q,a,b):""].join(" ")},Gb:Sb};function yd(a,b,c){var d=X();try{O(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function gd(a,b){var c=X();try{return O(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function hd(a,b,c){var d=X();try{return O(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}
function ud(a,b){var c=X();try{return O(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0);return 0n}}function Gd(a,b,c){var d=X();try{O(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function jd(a,b,c,d){var e=X();try{return O(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function xd(a,b){var c=X();try{O(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function wd(a){var b=X();try{O(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}
function kd(a,b,c,d,e,f,g,k,l){var m=X();try{return O(a)(b,c,d,e,f,g,k,l)}catch(r){Y(m);if(r!==r+0)throw r;Z(1,0)}}function zd(a,b,c,d){var e=X();try{O(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function pd(a,b,c,d,e,f,g,k){var l=X();try{return O(a)(b,c,d,e,f,g,k)}catch(m){Y(l);if(m!==m+0)throw m;Z(1,0)}}function ld(a,b,c,d,e){var f=X();try{return O(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}
function od(a,b,c,d,e,f,g){var k=X();try{return O(a)(b,c,d,e,f,g)}catch(l){Y(k);if(l!==l+0)throw l;Z(1,0)}}function Cd(a,b,c,d,e,f,g){var k=X();try{O(a)(b,c,d,e,f,g)}catch(l){Y(k);if(l!==l+0)throw l;Z(1,0)}}function Ad(a,b,c,d,e){var f=X();try{O(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}function ed(a,b){var c=X();try{return O(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function nd(a,b,c,d,e,f){var g=X();try{return O(a)(b,c,d,e,f)}catch(k){Y(g);if(k!==k+0)throw k;Z(1,0)}}
function Bd(a,b,c,d,e,f){var g=X();try{O(a)(b,c,d,e,f)}catch(k){Y(g);if(k!==k+0)throw k;Z(1,0)}}function fd(a){var b=X();try{return O(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function vd(a,b,c,d,e){var f=X();try{return O(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0);return 0n}}function Dd(a,b,c,d,e,f,g,k){var l=X();try{O(a)(b,c,d,e,f,g,k)}catch(m){Y(l);if(m!==m+0)throw m;Z(1,0)}}function td(a){var b=X();try{return O(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0);return 0n}}
function rd(a,b,c,d,e,f){var g=X();try{return O(a)(b,c,d,e,f)}catch(k){Y(g);if(k!==k+0)throw k;Z(1,0)}}function md(a,b,c,d,e,f){var g=X();try{return O(a)(b,c,d,e,f)}catch(k){Y(g);if(k!==k+0)throw k;Z(1,0)}}function sd(a,b,c){var d=X();try{return O(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function qd(a,b,c,d,e,f,g,k,l,m,r,y){var B=X();try{return O(a)(b,c,d,e,f,g,k,l,m,r,y)}catch(N){Y(B);if(N!==N+0)throw N;Z(1,0)}}
function Ed(a,b,c,d,e,f,g,k,l,m,r){var y=X();try{O(a)(b,c,d,e,f,g,k,l,m,r)}catch(B){Y(y);if(B!==B+0)throw B;Z(1,0)}}function Fd(a,b,c,d,e,f,g,k,l,m,r,y,B,N,ka,R){var M=X();try{O(a)(b,c,d,e,f,g,k,l,m,r,y,B,N,ka,R)}catch(ta){Y(M);if(ta!==ta+0)throw ta;Z(1,0)}}function Id(a=[]){var b=$c;a.unshift(ea);var c=a.length,d=Vc(4*(c+1)),e=d;a.forEach(g=>{u[e>>2]=Wc(g);e+=4});u[e>>2]=0;try{var f=b(c,d);Tb(f,!0)}catch(g){Rb(g)}}
function Jd(a=da){function b(){h.calledRun=!0;if(!pa){if(!h.noFSInit&&!qb){var c,d;qb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Nb("stdin",c):Kb("/dev/tty","/dev/stdin");d?Nb("stdout",null,d):Kb("/dev/tty","/dev/stdout");e?Nb("stderr",null,e):Kb("/dev/tty1","/dev/stderr");Lb("/dev/stdin",0);Lb("/dev/stdout",1);Lb("/dev/stderr",1)}Kd._c();rb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Id(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=h.postRun.shift();
Da.push(e)}Ca(Da)}}if(0<Ga)Ha=Jd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Fa();Ca(Ea);0<Ga?Ha=Jd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Kd;
(async function(){function a(c){Kd=c.exports;ra=Kd.Zc;va();bc=Kd.cd;c=Kd;h._loadFile=c.$c;h._main=$c=c.ad;h._malloc=P=c.bd;ad=c.dd;Z=c.ed;Na=c.fd;Y=c.gd;Vc=c.hd;X=c.id;bd=c.jd;cd=c.kd;Oa=c.ld;dd=c.md;Ga--;h.monitorRunDependencies?.(Ga);0==Ga&&Ha&&(c=Ha,Ha=null,c());return Kd}Ga++;h.monitorRunDependencies?.(Ga);var b={a:Hd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});xa??=h.locateFile?h.locateFile("magnum-player.wasm",ia):ia+"magnum-player.wasm";return a((await Aa(b)).instance)})();
Jd();
