
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var k="",ka,la,ma,na;
if(ia)k=ha?require("path").dirname(k)+"/":__dirname+"/",ka=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")},la=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?k=self.location.href:document.currentScript&&(k=document.currentScript.src),k=0!==k.indexOf("blob:")?k.substr(0,k.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var pa=f.print||console.log.bind(console),n=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);function qa(a){ra||(ra={});ra[a]||(ra[a]=1,n(a))}var ra,sa;f.wasmBinary&&(sa=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&n("no native wasm support detected");
var ta,ua=new WebAssembly.Table({initial:744,maximum:744,element:"anyfunc"}),va=!1;function assert(a,b){a||l("Assertion failed: "+b)}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function t(a,b){return a?xa(u,a,b):""}
function ya(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Aa(a){var b=za(a)+1,c=Ba(b);ya(a,v,c,b);return c}var Ca,v,u,Da,Ea,x,y,A,Fa,Ga=f.INITIAL_MEMORY||16777216;f.wasmMemory?ta=f.wasmMemory:ta=new WebAssembly.Memory({initial:Ga/65536,maximum:Ga/65536});ta&&(Ca=ta.buffer);Ga=Ca.byteLength;var Ha=Ca;Ca=Ha;f.HEAP8=v=new Int8Array(Ha);f.HEAP16=Da=new Int16Array(Ha);
f.HEAP32=x=new Int32Array(Ha);f.HEAPU8=u=new Uint8Array(Ha);f.HEAPU16=Ea=new Uint16Array(Ha);f.HEAPU32=y=new Uint32Array(Ha);f.HEAPF32=A=new Float32Array(Ha);f.HEAPF64=Fa=new Float64Array(Ha);x[9872]=5282528;function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.dh;"number"===typeof c?void 0===b.Kg?f.dynCall_v(c):f.dynCall_vi(c,b.Kg):c(void 0===b.Kg?null:b.Kg)}}}var Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=f.preRun.shift();Ja.unshift(a)}
var Oa=Math.abs,Pa=Math.ceil,Qa=Math.floor,Ra=Math.min,Sa=0,Ta=null,Ua=null;f.preloadedImages={};f.preloadedAudios={};function l(a){if(f.onAbort)f.onAbort(a);pa(a);n(a);va=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Va(a){var b=Wa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Xa(){return Va("data:application/octet-stream;base64,")}var Wa="magnum-gl-info.wasm";
if(!Xa()){var Ya=Wa;Wa=f.locateFile?f.locateFile(Ya,k):k+Ya}function Za(){try{if(sa)return new Uint8Array(sa);if(la)return la(Wa);throw"both async and sync fetching of the wasm failed";}catch(a){l(a)}}function $a(){return sa||!fa&&!ha||"function"!==typeof fetch||Va("file://")?new Promise(function(a){a(Za())}):fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Za()})}
var ab,bb,eb={11410:function(a){a=t(a);if("undefined"!==typeof process&&a in process.env){var b=cb(process.env[a]);if("number"===typeof b){var c=!0;a=b}else c=!1,a=b.length;var d=db(Math.max(a,1));if(c){b=d;assert(0==(d&3));for(c=d+(a&-4);b<c;b+=4)x[b>>2]=0;for(c=d+a;b<c;)v[b++>>0]=0}else b.subarray||b.slice?u.set(b,d):u.set(new Uint8Array(b),d);a=d}else a=0;return a}};Ka.push({dh:function(){fb()}});function gb(){return 0<gb.Og}
function hb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ib(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=hb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function jb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function kb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=hb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],output:[],Eg:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new B(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Eg.flush(a.tty)},flush:function(a){a.tty.Eg.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Eg.eh)throw new B(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Eg.eh(a.tty)}catch(m){throw new B(29);}if(void 0===h&&0===e)throw new B(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Eg.Wg)throw new B(60);
try{for(var e=0;e<d;e++)a.tty.Eg.Wg(a.tty,b[c+e])}catch(g){throw new B(29);}d&&(a.node.timestamp=Date.now());return e}},qb={eh:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Og?Buffer.Og(256):new Buffer(256),d=0;try{d=ma.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=cb(b,!0)}return a.input.shift()},Wg:function(a,b){null===b||10===b?(pa(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(xa(a.output,0)),a.output=[])}},rb={Wg:function(a,b){null===b||10===b?(n(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(n(xa(a.output,0)),a.output=[])}},E={xg:null,zg:function(){return E.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new B(63);E.xg||(E.xg={dir:{node:{Ag:E.rg.Ag,yg:E.rg.yg,lookup:E.rg.lookup,Lg:E.rg.Lg,rename:E.rg.rename,unlink:E.rg.unlink,rmdir:E.rg.rmdir,readdir:E.rg.readdir,symlink:E.rg.symlink},stream:{Cg:E.sg.Cg}},file:{node:{Ag:E.rg.Ag,yg:E.rg.yg},stream:{Cg:E.sg.Cg,read:E.sg.read,write:E.sg.write,Yg:E.sg.Yg,fh:E.sg.fh,Ng:E.sg.Ng}},link:{node:{Ag:E.rg.Ag,yg:E.rg.yg,readlink:E.rg.readlink},stream:{}},Zg:{node:{Ag:E.rg.Ag,
yg:E.rg.yg},stream:sb}});c=tb(a,b,c,d);16384===(c.mode&61440)?(c.rg=E.xg.dir.node,c.sg=E.xg.dir.stream,c.qg={}):32768===(c.mode&61440)?(c.rg=E.xg.file.node,c.sg=E.xg.file.stream,c.tg=0,c.qg=null):40960===(c.mode&61440)?(c.rg=E.xg.link.node,c.sg=E.xg.link.stream):8192===(c.mode&61440)&&(c.rg=E.xg.Zg.node,c.sg=E.xg.Zg.stream);c.timestamp=Date.now();a&&(a.qg[b]=c);return c},Eh:function(a){if(a.qg&&a.qg.subarray){for(var b=[],c=0;c<a.tg;++c)b.push(a.qg[c]);return b}return a.qg},Fh:function(a){return a.qg?
a.qg.subarray?a.qg.subarray(0,a.tg):new Uint8Array(a.qg):new Uint8Array(0)},$g:function(a,b){var c=a.qg?a.qg.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.qg,a.qg=new Uint8Array(b),0<a.tg&&a.qg.set(c.subarray(0,a.tg),0))},sh:function(a,b){if(a.tg!=b)if(0==b)a.qg=null,a.tg=0;else{if(!a.qg||a.qg.subarray){var c=a.qg;a.qg=new Uint8Array(b);c&&a.qg.set(c.subarray(0,Math.min(b,a.tg)))}else if(a.qg||(a.qg=[]),a.qg.length>b)a.qg.length=b;else for(;a.qg.length<b;)a.qg.push(0);
a.tg=b}},rg:{Ag:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.tg:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.lh=4096;b.blocks=Math.ceil(b.size/b.lh);return b},yg:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&E.sh(a,b.size)},lookup:function(){throw ub[44];},Lg:function(a,b,c,d){return E.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=vb(b,c)}catch(g){}if(d)for(var e in d.qg)throw new B(55);}delete a.parent.qg[a.name];a.name=c;b.qg[c]=a;a.parent=b},unlink:function(a,b){delete a.qg[b]},rmdir:function(a,b){var c=vb(a,b),d;for(d in c.qg)throw new B(55);delete a.qg[b]},readdir:function(a){var b=[".",".."],c;for(c in a.qg)a.qg.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new B(28);return a.link}},sg:{read:function(a,b,c,d,e){var g=a.node.qg;if(e>=a.node.tg)return 0;a=Math.min(a.node.tg-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.qg||a.qg.subarray)){if(g)return a.qg=b.subarray(c,c+d),a.tg=d;if(0===a.tg&&0===e)return a.qg=
b.slice(c,c+d),a.tg=d;if(e+d<=a.tg)return a.qg.set(b.subarray(c,c+d),e),d}E.$g(a,e+d);if(a.qg.subarray&&b.subarray)a.qg.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.qg[e+g]=b[c+g];a.tg=Math.max(a.tg,e+d);return d},Cg:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.tg);if(0>b)throw new B(28);return b},Yg:function(a,b,c){E.$g(a.node,b+c);a.node.tg=Math.max(a.node.tg,b+c)},fh:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new B(43);a=a.node.qg;
if(g&2||a.buffer!==Ca){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=db(c);if(!c)throw new B(48);v.set(a,c)}else d=!1,c=a.byteOffset;return{Oh:c,kh:d}},Ng:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new B(43);if(e&2)return 0;E.sg.write(a,b,0,d,c,!1);return 0}}},wb=null,xb={},yb=[],zb=1,Ab=null,Bb=!0,Cb={},B=null,ub={};
function Db(a,b){a=lb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={bh:!0,Xg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Xg)throw new B(32);a=hb(a.split("/").filter(function(h){return!!h}),!1);var e=wb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=vb(e,a[d]);c=ib(c+"/"+a[d]);e.Mg&&(!g||g&&b.bh)&&(e=e.Mg.root);if(!g||b.ah)for(g=0;40960===(e.mode&61440);)if(e=Eb(c),c=lb(jb(c),e),e=Db(c,{Xg:b.Xg}).node,40<g++)throw new B(32);}return{path:c,node:e}}
function Fb(a){for(var b;;){if(a===a.parent)return a=a.zg.gh,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length}function vb(a,b){var c;if(c=(c=Hb(a,"x"))?c:a.rg.lookup?0:2)throw new B(c,a);for(c=Ab[Gb(a.id,b)];c;c=c.qh){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.rg.lookup(a,b)}
function tb(a,b,c,d){a=new Ib(a,b,c,d);b=Gb(a.parent.id,a.name);a.qh=Ab[b];return Ab[b]=a}var Jb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Bb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Lb(a,b){try{return vb(a,b),20}catch(c){}return Hb(a,"wx")}function Mb(){var a=4096;for(var b=0;b<=a;b++)if(!yb[b])return b;throw new B(33);}function Nb(a){Ob||(Ob=function(){},Ob.prototype={});var b=new Ob,c;for(c in a)b[c]=a[c];a=b;b=Mb();a.fd=b;return yb[b]=a}var sb={open:function(a){a.sg=xb[a.node.rdev].sg;a.sg.open&&a.sg.open(a)},Cg:function(){throw new B(70);}};function ob(a,b){xb[a]={sg:b}}
function Pb(a,b){var c="/"===b,d=!b;if(c&&wb)throw new B(10);if(!c&&!d){var e=Db(b,{bh:!1});b=e.path;e=e.node;if(e.Mg)throw new B(10);if(16384!==(e.mode&61440))throw new B(54);}b={type:a,Mh:{},gh:b,ph:[]};a=a.zg(b);a.zg=b;b.root=a;c?wb=a:e&&(e.Mg=b,e.zg&&e.zg.ph.push(b))}function Qb(a,b,c){var d=Db(a,{parent:!0}).node;a=kb(a);if(!a||"."===a||".."===a)throw new B(28);var e=Lb(d,a);if(e)throw new B(e);if(!d.rg.Lg)throw new B(63);return d.rg.Lg(d,a,b,c)}function Rb(a){Qb(a,16895,0)}
function Sb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Qb(a,b|8192,c)}function Tb(a,b){if(!lb(a))throw new B(44);var c=Db(b,{parent:!0}).node;if(!c)throw new B(44);b=kb(b);var d=Lb(c,b);if(d)throw new B(d);if(!c.rg.symlink)throw new B(63);c.rg.symlink(c,b,a)}function Eb(a){a=Db(a).node;if(!a)throw new B(44);if(!a.rg.readlink)throw new B(28);return lb(Fb(a.parent),a.rg.readlink(a))}
function Ub(a,b){if(""===a)throw new B(44);if("string"===typeof b){var c=Jb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=ib(a);try{e=Db(a,{ah:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new B(20);}else e=Qb(a,d,0),c=!0;if(!e)throw new B(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new B(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Kb(b)||b&512)?31:Hb(e,Kb(b)):44))throw new B(d);if(b&512){d=e;var g;"string"===typeof d?g=Db(d,{ah:!0}).node:g=d;if(!g.rg.yg)throw new B(63);if(16384===(g.mode&61440))throw new B(31);if(32768!==(g.mode&61440))throw new B(28);if(d=Hb(g,"w"))throw new B(d);g.rg.yg(g,{size:0,timestamp:Date.now()})}b&=-131713;e=Nb({node:e,path:Fb(e),flags:b,seekable:!0,position:0,sg:e.sg,yh:[],error:!1});e.sg.open&&e.sg.open(e);!f.logReadFiles||b&1||(Vb||(Vb={}),a in Vb||(Vb[a]=1,n("FS.trackingDelegate error on read file: "+
a)));try{Cb.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Cb.onOpenFile(a,e))}catch(h){n("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}}function Wb(a,b,c){if(null===a.fd)throw new B(8);if(!a.seekable||!a.sg.Cg)throw new B(70);if(0!=c&&1!=c&&2!=c)throw new B(28);a.position=a.sg.Cg(a,b,c);a.yh=[]}
function Xb(){B||(B=function(a,b){this.node=b;this.th=function(c){this.Gg=c};this.th(a);this.message="FS error"},B.prototype=Error(),B.prototype.constructor=B,[44].forEach(function(a){ub[a]=new B(a);ub[a].stack="<generic error, no stack>"}))}var Yb;function Zb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function $b(a,b,c){a=ib("/dev/"+a);var d=Zb(!!b,!!c);ac||(ac=64);var e=ac++<<8|0;ob(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,m,p){for(var r=0,w=0;w<p;w++){try{var D=b()}catch(I){throw new B(29);}if(void 0===D&&0===r)throw new B(6);if(null===D||void 0===D)break;r++;h[m+w]=D}r&&(g.node.timestamp=Date.now());return r},write:function(g,h,m,p){for(var r=0;r<p;r++)try{c(h[m+r])}catch(w){throw new B(29);}p&&(g.node.timestamp=Date.now());return r}});
Sb(a,d,e)}var ac,bc={},Ob,Vb,cc={};function dc(a){a=yb[a];if(!a)throw new B(8);return a}
function ec(a,b){fc=a;hc=b;if(ic)if(0==a)jc=function(){var d=Math.max(0,kc+b-lc())|0;setTimeout(mc,d)};else if(1==a)jc=function(){nc(mc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}jc=function(){setImmediate(mc)}}}var lc;ia?lc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?lc=dateNow:lc=function(){return performance.now()};
function oc(a){var b=pc;noExitRuntime=!0;assert(!ic,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ic=a;pc=b;var c="undefined"!==typeof b?function(){f.dynCall_vi(a,b)}:function(){f.dynCall_v(a)};var d=qc;mc=function(){if(!va)if(0<rc.length){var e=Date.now(),g=rc.shift();g.dh(g.Kg);if(sc){var h=sc,m=0==h%1?h-1:Math.floor(h);sc=g.Bh?m:(8*h+(m+.5))/9}console.log('main loop blocker "'+
g.name+'" took '+(Date.now()-e)+" ms");f.setStatus&&(e=f.statusMessage||"Please wait...",g=sc,h=tc.Dh,g?g<h?f.setStatus(e+" ("+(h-g)+"/"+h+")"):f.setStatus(e):f.setStatus(""));d<qc||setTimeout(mc,0)}else if(!(d<qc))if(uc=uc+1|0,1==fc&&1<hc&&0!=uc%hc)jc();else{0==fc&&(kc=lc());a:if(!(va||f.preMainLoop&&!1===f.preMainLoop())){try{c()}catch(p){if(p instanceof oa)break a;p&&"object"===typeof p&&p.stack&&n("exception thrown: "+[p,p.stack]);throw p;}f.postMainLoop&&f.postMainLoop()}d<qc||("object"===typeof SDL&&
SDL.audio&&SDL.audio.rh&&SDL.audio.rh(),jc())}}}var jc=null,qc=0,ic=null,pc=0,fc=0,hc=0,uc=0,rc=[],tc={},kc,mc,sc,vc=!1,wc=!1,xc=[];
function yc(){function a(){wc=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!zc){zc=!0;try{Ac=!0}catch(c){Ac=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Bc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Ac?null:console.log("warning: no BlobBuilder");
Cc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;f.hh||"undefined"!==typeof Cc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.hh=!0);f.preloadPlugins.push({canHandle:function(c){return!f.hh&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(Ac)try{h=new Blob([c],{type:Dc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Dc(d)}))}catch(r){qa("Blob constructor present but fails: "+
r+"; falling back to blob builder")}h||(h=new Bc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=Cc.createObjectURL(h),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=p.width;r.height=p.height;r.getContext("2d").drawImage(p,0,0);f.preloadedImages[d]=r;Cc.revokeObjectURL(m);e&&e(c)};p.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};p.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Lh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(D){p||(p=!0,f.preloadedAudios[d]=D,e&&e(c))}function m(){p||(p=!0,f.preloadedAudios[d]=new Audio,g&&g())}var p=!1;if(Ac){try{var r=new Blob([c],{type:Dc(d)})}catch(D){return m()}r=Cc.createObjectURL(r);var w=new Audio;w.addEventListener("canplaythrough",function(){h(w)},!1);w.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var D="",I=0,q=0,
z=0;z<c.length;z++)for(I=I<<8|c[z],q+=8;6<=q;){var C=I>>q-6&63;q-=6;D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}2==q?(D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(I&3)<<4],D+="=="):4==q&&(D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(I&15)<<2],D+="=");w.src="data:audio/x-"+d.substr(-3)+";base64,"+D;h(w)}};w.src=r;Ec(function(){h(w)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&
b.addEventListener("click",function(c){!wc&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Fc(a,b,c,d){if(b&&f.Sg&&a==f.canvas)return f.Sg;var e;if(b){var g={antialias:!1,alpha:!1,Ug:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof Gc&&(e=Hc(a,g)))var m=F[e].Dg}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof G,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Sg=m,b&&Ic(e),f.zh=b,xc.forEach(function(p){p()}),yc());return m}var Jc=!1,Kc=void 0,Lc=void 0;
function Mc(a,b){function c(){vc=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Nc,Kc&&d.requestPointerLock(),vc=!0,Lc?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),Oc(f.canvas),Pc()):Oc(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Lc?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),Oc(f.canvas),Pc()):Oc(d));if(f.onFullScreen)f.onFullScreen(vc);if(f.onFullscreen)f.onFullscreen(vc)}Kc=a;Lc=b;"undefined"===typeof Kc&&(Kc=!0);"undefined"===typeof Lc&&(Lc=!1);var d=f.canvas;Jc||(Jc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Nc(){if(!vc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Qc=0;function nc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Qc)Qc=b+1E3/60;else for(;b+2>=Qc;)Qc+=1E3/60;setTimeout(a,Math.max(Qc-b,0))}}function Ec(a){noExitRuntime=!0;setTimeout(function(){va||a()},1E4)}
function Dc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Rc=[];function Pc(){var a=f.canvas;Rc.forEach(function(b){b(a.width,a.height)})}
function Oc(a,b,c){b&&c?(a.Ah=b,a.nh=c):(b=a.Ah,c=a.nh);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Lc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var zc,Ac,Bc,Cc,H=12288,Sc=0,Tc={alpha:!1,depth:!1,stencil:!1,antialias:!1},Uc;
function Vc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Wc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Yc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Zc=1,J=[],K=[],$c=[],ad=[],L=[],M=[],N=[],O=[],F=[],P=[],bd=[],Q=[],cd=[],dd=[],ed={},fd={},gd={},hd=4;function R(a){id||(id=a)}function jd(a){for(var b=Zc++,c=a.length;c<b;c++)a[c]=null;return b}function Hc(a,b){if(a=1<b.Ug?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=jd(F),d={Gh:c,attributes:b,version:b.Ug,Dg:a};a.canvas&&(a.canvas.jh=d);F[c]=d;("undefined"===typeof b.mh||b.mh)&&kd(d);b=c}else b=0;return b}function Ic(a){S=F[a];f.Sg=G=S&&S.Dg}
function kd(a){a||(a=S);if(!a.oh){a.oh=!0;var b=a.Dg;Vc(b);Wc(b);Yc(b);b.Ch=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.wg=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Gc={},id,S,ld=[];function md(a,b,c,d){G.drawElements(a,b,c,d)}function T(a,b,c,d){for(var e=0;e<a;e++){var g=G[c](),h=g&&jd(d);g?(g.name=h,d[h]=g):R(1282);x[b+4*e>>2]=h}}function nd(a,b,c,d,e,g,h,m){b=K[b];if(a=G[a](b,c))d=m&&ya(a.name,u,m,d),e&&(x[e>>2]=d),g&&(x[g>>2]=a.size),h&&(x[h>>2]=a.type)}function od(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function pd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=G.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>S.version){R(1282);return}d=2*(G.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){R(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=G.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:v[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){R(1280);
n("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:R(1280);n("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:od(b,d);break;case 0:x[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:v[b>>0]=d?1:0}}else R(1281)}
function qd(a,b,c,d){if(c){b=G.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:R(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{R(1280);return}break;default:R(1280);return}switch(d){case 1:od(c,a);break;case 0:x[c>>2]=a;break;case 2:A[c>>2]=a;break;case 4:v[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else R(1281)}
function U(a){var b=za(a)+1,c=db(b);ya(a,u,c,b);return c}function rd(a,b,c,d){if(c)if(a=G.getUniform(K[a],M[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a;break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else R(1281)}
function sd(a,b,c,d){if(c)if(a=G.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b]);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+
d;}else R(1281)}function V(a){a-=5120;return 0==a?v:1==a?u:2==a?Da:4==a?x:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?y:Ea}function X(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function td(a,b,c,d,e){a=V(a);var g=X(a),h=hd;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var Y=[],ud=[],vd={};
function wd(){if(!xd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in vd)a[b]=vd[b];var c=[];for(b in a)c.push(b+"="+a[b]);xd=c}return xd}var xd;function yd(a){return 0===a%4&&(0!==a%100||0===a%400)}function zd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Ad=[31,29,31,30,31,30,31,31,30,31,30,31],Bd=[31,28,31,30,31,30,31,31,30,31,30,31];function Cd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(yd(a.getFullYear())?Ad:Bd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Dd(a,b,c,d){function e(q,z,C){for(q="number"===typeof q?q.toString():q||"";q.length<z;)q=C[0]+q;return q}function g(q,z){return e(q,z,"0")}function h(q,z){function C(Xc){return 0>Xc?-1:0<Xc?1:0}var W;0===(W=C(q.getFullYear()-z.getFullYear()))&&0===(W=C(q.getMonth()-z.getMonth()))&&(W=C(q.getDate()-z.getDate()));return W}function m(q){switch(q.getDay()){case 0:return new Date(q.getFullYear()-1,11,29);case 1:return q;case 2:return new Date(q.getFullYear(),0,3);case 3:return new Date(q.getFullYear(),
0,2);case 4:return new Date(q.getFullYear(),0,1);case 5:return new Date(q.getFullYear()-1,11,31);case 6:return new Date(q.getFullYear()-1,11,30)}}function p(q){q=Cd(new Date(q.vg+1900,0,1),q.Rg);var z=new Date(q.getFullYear()+1,0,4),C=m(new Date(q.getFullYear(),0,4));z=m(z);return 0>=h(C,q)?0>=h(z,q)?q.getFullYear()+1:q.getFullYear():q.getFullYear()-1}var r=x[d+40>>2];d={wh:x[d>>2],vh:x[d+4>>2],Pg:x[d+8>>2],Jg:x[d+12>>2],Fg:x[d+16>>2],vg:x[d+20>>2],Qg:x[d+24>>2],Rg:x[d+28>>2],Qh:x[d+32>>2],uh:x[d+
36>>2],xh:r?t(r):""};c=t(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var w in r)c=c.replace(new RegExp(w,"g"),r[w]);var D="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
I="January February March April May June July August September October November December".split(" ");r={"%a":function(q){return D[q.Qg].substring(0,3)},"%A":function(q){return D[q.Qg]},"%b":function(q){return I[q.Fg].substring(0,3)},"%B":function(q){return I[q.Fg]},"%C":function(q){return g((q.vg+1900)/100|0,2)},"%d":function(q){return g(q.Jg,2)},"%e":function(q){return e(q.Jg,2," ")},"%g":function(q){return p(q).toString().substring(2)},"%G":function(q){return p(q)},"%H":function(q){return g(q.Pg,
2)},"%I":function(q){q=q.Pg;0==q?q=12:12<q&&(q-=12);return g(q,2)},"%j":function(q){return g(q.Jg+zd(yd(q.vg+1900)?Ad:Bd,q.Fg-1),3)},"%m":function(q){return g(q.Fg+1,2)},"%M":function(q){return g(q.vh,2)},"%n":function(){return"\n"},"%p":function(q){return 0<=q.Pg&&12>q.Pg?"AM":"PM"},"%S":function(q){return g(q.wh,2)},"%t":function(){return"\t"},"%u":function(q){return q.Qg||7},"%U":function(q){var z=new Date(q.vg+1900,0,1),C=0===z.getDay()?z:Cd(z,7-z.getDay());q=new Date(q.vg+1900,q.Fg,q.Jg);return 0>
h(C,q)?g(Math.ceil((31-C.getDate()+(zd(yd(q.getFullYear())?Ad:Bd,q.getMonth()-1)-31)+q.getDate())/7),2):0===h(C,z)?"01":"00"},"%V":function(q){var z=new Date(q.vg+1901,0,4),C=m(new Date(q.vg+1900,0,4));z=m(z);var W=Cd(new Date(q.vg+1900,0,1),q.Rg);return 0>h(W,C)?"53":0>=h(z,W)?"01":g(Math.ceil((C.getFullYear()<q.vg+1900?q.Rg+32-C.getDate():q.Rg+1-C.getDate())/7),2)},"%w":function(q){return q.Qg},"%W":function(q){var z=new Date(q.vg,0,1),C=1===z.getDay()?z:Cd(z,0===z.getDay()?1:7-z.getDay()+1);q=
new Date(q.vg+1900,q.Fg,q.Jg);return 0>h(C,q)?g(Math.ceil((31-C.getDate()+(zd(yd(q.getFullYear())?Ad:Bd,q.getMonth()-1)-31)+q.getDate())/7),2):0===h(C,z)?"01":"00"},"%y":function(q){return(q.vg+1900).toString().substring(2)},"%Y":function(q){return q.vg+1900},"%z":function(q){q=q.uh;var z=0<=q;q=Math.abs(q)/60;return(z?"+":"-")+String("0000"+(q/60*100+q%60)).slice(-4)},"%Z":function(q){return q.xh},"%%":function(){return"%"}};for(w in r)0<=c.indexOf(w)&&(c=c.replace(new RegExp(w,"g"),r[w](d)));w=
cb(c,!1);if(w.length>b)return 0;v.set(w,a);return w.length-1}var Ed=[];function Ib(a,b,c,d){a||(a=this);this.parent=a;this.zg=a.zg;this.Mg=null;this.id=zb++;this.name=b;this.mode=c;this.rg={};this.sg={};this.rdev=d}Object.defineProperties(Ib.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Xb();Ab=Array(4096);Pb(E,"/");Rb("/tmp");
Rb("/home");Rb("/home/web_user");
(function(){Rb("/dev");ob(259,{read:function(){return 0},write:function(d,e,g,h){return h}});Sb("/dev/null",259);nb(1280,qb);nb(1536,rb);Sb("/dev/tty",1280);Sb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ia)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){l("random_device")});$b("random",b);$b("urandom",b);Rb("/dev/shm");
Rb("/dev/shm/tmp")})();Rb("/proc");Rb("/proc/self");Rb("/proc/self/fd");Pb({zg:function(){var a=tb("/proc/self","fd",16895,73);a.rg={lookup:function(b,c){var d=yb[+c];if(!d)throw new B(8);b={parent:null,zg:{gh:"fake"},rg:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");f.requestFullscreen=function(a,b){Mc(a,b)};f.requestAnimationFrame=function(a){nc(a)};f.setCanvasSize=function(a,b,c){Oc(f.canvas,a,b);c||Pc()};f.pauseMainLoop=function(){jc=null;qc++};
f.resumeMainLoop=function(){qc++;var a=fc,b=hc,c=ic;ic=null;oc(c);ec(a,b);jc()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Fc(a,b,c,d)};for(var G,Z=0;32>Z;++Z)ld.push(Array(Z));var Fd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Fd.subarray(0,Z+1);var Gd=new Int32Array(288);for(Z=0;288>Z;++Z)ud[Z]=Gd.subarray(0,Z+1);
function cb(a,b){var c=Array(za(a)+1);a=ya(a,c,0,c.length);b&&(c.length=a);return c}
var Kd={hg:function(a){return db(a)},gg:function(a){"uncaught_exception"in gb?gb.Og++:gb.Og=1;throw a;},_f:function(){x[Hd()>>2]=63;return-1},Zf:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=cc[a];if(d&&b===d.Hh){var e=yb[d.fd];if(d.Nh&2){var g=d.flags,h=d.offset,m=u.slice(a,a+b);e&&e.sg.Ng&&e.sg.Ng(e,m,h,b,g)}cc[a]=null;d.kh&&Id(d.Jh)}c=0}return c}catch(p){return"undefined"!==typeof bc&&p instanceof B||l(p),-p.Gg}},a:function(){l()},r:function(a){if(12448==a)return H=12288,1;H=12300;
return 0},q:function(a,b,c,d,e){if(62E3!=a)H=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)Tc.alpha=0<x[b+4>>2];else if(12325==a)Tc.depth=0<x[b+4>>2];else if(12326==a)Tc.stencil=0<x[b+4>>2];else if(12337==a)a=x[b+4>>2],Tc.antialias=0<a;else if(12338==a)a=x[b+4>>2],Tc.antialias=1==a;else if(12544==a)Tc.Ih=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),H=12288,c=1):(H=12300,c=0)}return c},p:function(a,b,c,d){if(62E3!=a)return H=12296,0;for(a=1;;){b=
x[d>>2];if(12440==b)a=x[d+4>>2];else if(12344==b)break;else return H=12292,0;d+=8}if(2>a||3<a)return H=12293,0;Tc.Ug=a-1;Tc.Kh=0;Uc=Hc(f.canvas,Tc);if(0!=Uc)return H=12288,Ic(Uc),f.zh=!0,xc.forEach(function(e){e()}),Ic(null),62004;H=12297;return 0},o:function(a,b){if(62E3!=a)return H=12296,0;if(62004!=b)return H=12294,0;a=Uc;S===F[a]&&(S=null);"object"===typeof JSEvents&&JSEvents.Ph(F[a].Dg.canvas);F[a]&&F[a].Dg.canvas&&(F[a].Dg.canvas.jh=void 0);F[a]=null;H=12288;Sc==b&&(Sc=0);return 1},t:function(){H=
12288;return 62E3},c:function(){return H},s:function(a,b,c){if(62E3==a)return b&&(x[b>>2]=1),c&&(x[c>>2]=4),H=12288,1;H=12296;return 0},dg:function(a,b,c,d){if(62E3!=a)return H=12296,0;if(0!=d&&62004!=d)return H=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return H=12301,0;Ic(d?Uc:null);Sc=d;H=12288;return 1},eg:function(a){if(62E3!=a)return H=12296,0;Sc=0;H=12288;return 1},ua:function(a,b,c){Ed.length=0;var d;for(c>>=2;d=u[b++];)Ed.push(105>d?Fa[++c>>1]:x[c]),++c;return eb[a].apply(null,Ed)},Af:function(a){G.activeTexture(a)},
zf:function(a,b){G.attachShader(K[a],N[b])},sc:function(a,b){G.beginQuery(a,bd[b])},Rf:function(a,b){G.wg.beginQueryEXT(a,P[b])},Zb:function(a){G.beginTransformFeedback(a)},yf:function(a,b,c){G.bindAttribLocation(K[a],b,t(c))},xf:function(a,b){35051==a?G.Bg=b:35052==a&&(G.ug=b);G.bindBuffer(a,J[b])},Wb:function(a,b,c){G.bindBufferBase(a,b,J[c])},Xb:function(a,b,c,d,e){G.bindBufferRange(a,b,J[c],d,e)},wf:function(a,b){G.bindFramebuffer(a,$c[b])},vf:function(a,b){G.bindRenderbuffer(a,ad[b])},_a:function(a,
b){G.bindSampler(a,Q[b])},uf:function(a,b){G.bindTexture(a,L[b])},Ra:function(a,b){G.bindTransformFeedback(a,cd[b])},cc:function(a){G.bindVertexArray(O[a])},If:function(a){G.bindVertexArray(O[a])},tf:function(a,b,c,d){G.blendColor(a,b,c,d)},sf:function(a){G.blendEquation(a)},rf:function(a,b){G.blendEquationSeparate(a,b)},qf:function(a,b){G.blendFunc(a,b)},pf:function(a,b,c,d){G.blendFuncSeparate(a,b,c,d)},gc:function(a,b,c,d,e,g,h,m,p,r){G.blitFramebuffer(a,b,c,d,e,g,h,m,p,r)},of:function(a,b,c,d){2<=
S.version?c?G.bufferData(a,u,d,c,b):G.bufferData(a,b,d):G.bufferData(a,c?u.subarray(c,c+b):b,d)},nf:function(a,b,c,d){2<=S.version?G.bufferSubData(a,b,u,d,c):G.bufferSubData(a,b,u.subarray(d,d+c))},mf:function(a){return G.checkFramebufferStatus(a)},lf:function(a){G.clear(a)},xb:function(a,b,c,d){G.clearBufferfi(a,b,c,d)},yb:function(a,b,c){G.clearBufferfv(a,b,A,c>>2)},Bb:function(a,b,c){G.clearBufferiv(a,b,x,c>>2)},zb:function(a,b,c){G.clearBufferuiv(a,b,y,c>>2)},kf:function(a,b,c,d){G.clearColor(a,
b,c,d)},jf:function(a){G.clearDepth(a)},hf:function(a){G.clearStencil(a)},ib:function(a,b,c,d){return G.clientWaitSync(dd[a],b,(c>>>0)+4294967296*d)},ff:function(a,b,c,d){G.colorMask(!!a,!!b,!!c,!!d)},ef:function(a){G.compileShader(N[a])},df:function(a,b,c,d,e,g,h,m){2<=S.version?G.ug?G.compressedTexImage2D(a,b,c,d,e,g,h,m):G.compressedTexImage2D(a,b,c,d,e,g,u,m,h):G.compressedTexImage2D(a,b,c,d,e,g,m?u.subarray(m,m+h):null)},xc:function(a,b,c,d,e,g,h,m,p){G.ug?G.compressedTexImage3D(a,b,c,d,e,g,
h,m,p):G.compressedTexImage3D(a,b,c,d,e,g,h,u,p,m)},cf:function(a,b,c,d,e,g,h,m,p){2<=S.version?G.ug?G.compressedTexSubImage2D(a,b,c,d,e,g,h,m,p):G.compressedTexSubImage2D(a,b,c,d,e,g,h,u,p,m):G.compressedTexSubImage2D(a,b,c,d,e,g,h,p?u.subarray(p,p+m):null)},wc:function(a,b,c,d,e,g,h,m,p,r,w){G.ug?G.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,r,w):G.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,u,w,r)},vb:function(a,b,c,d,e){G.copyBufferSubData(a,b,c,d,e)},bf:function(a,b,c,d,e,g,h,m){G.copyTexImage2D(a,
b,c,d,e,g,h,m)},af:function(a,b,c,d,e,g,h,m){G.copyTexSubImage2D(a,b,c,d,e,g,h,m)},yc:function(a,b,c,d,e,g,h,m,p){G.copyTexSubImage3D(a,b,c,d,e,g,h,m,p)},$e:function(){var a=jd(K),b=G.createProgram();b.name=a;K[a]=b;return a},_e:function(a){var b=jd(N);N[b]=G.createShader(a);return b},Ze:function(a){G.cullFace(a)},Ye:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=J[d];e&&(G.deleteBuffer(e),e.name=0,J[d]=null,d==G.Bg&&(G.Bg=0),d==G.ug&&(G.ug=0))}},We:function(a,b){for(var c=0;c<a;++c){var d=
x[b+4*c>>2],e=$c[d];e&&(G.deleteFramebuffer(e),e.name=0,$c[d]=null)}},Ve:function(a){if(a){var b=K[a];b?(G.deleteProgram(b),b.name=0,K[a]=null,ed[a]=null):R(1281)}},uc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=bd[d];e&&(G.deleteQuery(e),bd[d]=null)}},Tf:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=P[d];e&&(G.wg.deleteQueryEXT(e),P[d]=null)}},Ue:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=ad[d];e&&(G.deleteRenderbuffer(e),e.name=0,ad[d]=null)}},ab:function(a,b){for(var c=
0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(G.deleteSampler(e),e.name=0,Q[d]=null)}},Te:function(a){if(a){var b=N[a];b?(G.deleteShader(b),N[a]=null):R(1281)}},jb:function(a){if(a){var b=dd[a];b?(G.deleteSync(b),b.name=0,dd[a]=null):R(1281)}},Se:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=L[d];e&&(G.deleteTexture(e),e.name=0,L[d]=null)}},Qa:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=cd[d];e&&(G.deleteTransformFeedback(e),e.name=0,cd[d]=null)}},bc:function(a,b){for(var c=0;c<a;c++){var d=
x[b+4*c>>2];G.deleteVertexArray(O[d]);O[d]=null}},Hf:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];G.deleteVertexArray(O[d]);O[d]=null}},Re:function(a){G.depthFunc(a)},Qe:function(a){G.depthMask(!!a)},Pe:function(a,b){G.depthRange(a,b)},Oe:function(a,b){G.detachShader(K[a],N[b])},Ne:function(a){G.disable(a)},Le:function(a){G.disableVertexAttribArray(a)},Ke:function(a,b,c){G.drawArrays(a,b,c)},nb:function(a,b,c,d){G.drawArraysInstanced(a,b,c,d)},Df:function(a,b,c,d){G.drawArraysInstanced(a,
b,c,d)},ya:function(a,b,c,d){G.drawArraysInstanced(a,b,c,d)},Gc:function(a,b,c,d){G.drawArraysInstanced(a,b,c,d)},Aa:function(a,b,c,d){G.drawArraysInstanced(a,b,c,d)},nc:function(a,b){for(var c=ld[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];G.drawBuffers(c)},Ec:function(a,b){for(var c=ld[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];G.drawBuffers(c)},Ef:function(a,b){for(var c=ld[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];G.drawBuffers(c)},Je:function(a,b,c,d){G.drawElements(a,b,c,d)},mb:function(a,b,c,d,e){G.drawElementsInstanced(a,
b,c,d,e)},Cf:function(a,b,c,d,e){G.drawElementsInstanced(a,b,c,d,e)},wa:function(a,b,c,d,e){G.drawElementsInstanced(a,b,c,d,e)},xa:function(a,b,c,d,e){G.drawElementsInstanced(a,b,c,d,e)},Fc:function(a,b,c,d,e){G.drawElementsInstanced(a,b,c,d,e)},Cc:function(a,b,c,d,e,g){md(a,d,e,g)},Ie:function(a){G.enable(a)},He:function(a){G.enableVertexAttribArray(a)},rc:function(a){G.endQuery(a)},Qf:function(a){G.wg.endQueryEXT(a)},Yb:function(){G.endTransformFeedback()},lb:function(a,b){return(a=G.fenceSync(a,
b))?(b=jd(dd),a.name=b,dd[b]=a,b):0},Ge:function(){G.finish()},Fe:function(){G.flush()},Ee:function(a,b,c,d){G.framebufferRenderbuffer(a,b,c,ad[d])},De:function(a,b,c,d,e){G.framebufferTexture2D(a,b,c,L[d],e)},dc:function(a,b,c,d,e){G.framebufferTextureLayer(a,b,L[c],d,e)},Ce:function(a){G.frontFace(a)},Ae:function(a,b){T(a,b,"createBuffer",J)},ye:function(a,b){T(a,b,"createFramebuffer",$c)},vc:function(a,b){T(a,b,"createQuery",bd)},Uf:function(a,b){for(var c=0;c<a;c++){var d=G.wg.createQueryEXT();
if(!d){for(R(1282);c<a;)x[b+4*c++>>2]=0;break}var e=jd(P);d.name=e;P[e]=d;x[b+4*c>>2]=e}},xe:function(a,b){T(a,b,"createRenderbuffer",ad)},bb:function(a,b){T(a,b,"createSampler",Q)},we:function(a,b){T(a,b,"createTexture",L)},Pa:function(a,b){T(a,b,"createTransformFeedback",cd)},ac:function(a,b){T(a,b,"createVertexArray",O)},Gf:function(a,b){T(a,b,"createVertexArray",O)},ze:function(a){G.generateMipmap(a)},ve:function(a,b,c,d,e,g,h){nd("getActiveAttrib",a,b,c,d,e,g,h)},ue:function(a,b,c,d,e,g,h){nd("getActiveUniform",
a,b,c,d,e,g,h)},qb:function(a,b,c,d,e){a=K[a];if(a=G.getActiveUniformBlockName(a,b))e&&0<c?(c=ya(a,u,e,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0)},rb:function(a,b,c,d){if(d)switch(a=K[a],c){case 35393:a=G.getActiveUniformBlockName(a,b);x[d>>2]=a.length+1;break;default:if(a=G.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)x[d>>2]=a;else for(b=0;b<a.length;b++)x[d+4*b>>2]=a[b]}else R(1281)},tb:function(a,b,c,d,e){if(e)if(0<b&&0==c)R(1281);else{a=K[a];for(var g=[],h=0;h<b;h++)g.push(x[c+4*h>>2]);
if(a=G.getActiveUniforms(a,g,d))for(b=a.length,h=0;h<b;h++)x[e+4*h>>2]=a[h]}else R(1281)},te:function(a,b,c,d){a=G.getAttachedShaders(K[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=N.indexOf(a[b])},se:function(a,b){return G.getAttribLocation(K[a],t(b))},re:function(a,b){pd(a,b,4)},cb:function(a,b,c){c?od(c,G.getBufferParameter(a,b)):R(1281)},pe:function(a,b,c){c?x[c>>2]=G.getBufferParameter(a,b):R(1281)},oe:function(){var a=G.getError()||id;id=0;return a},ne:function(a,b){pd(a,
b,2)},Kb:function(a,b){return G.getFragDataLocation(K[a],t(b))},me:function(a,b,c,d){a=G.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},db:function(a,b,c){qd(a,b,c,1)},gb:function(a,b){pd(a,b,1)},_b:function(a,b,c){qd(a,b,c,0)},le:function(a,b){pd(a,b,0)},Da:function(a,b,c,d,e){if(0>d)R(1281);else if(e){if(a=G.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)x[e+b>>2]=a[b]}else R(1281)},La:function(){R(1282)},
je:function(a,b,c,d){a=G.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?ya(a,u,d,b):0;c&&(x[c>>2]=b)},ke:function(a,b,c){if(c)if(a>=Zc)R(1281);else{var d=ed[a];if(d)if(35716==b)a=G.getProgramInfoLog(K[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.Vg;else if(35722==b){if(-1==d.Hg){a=K[a];var e=G.getProgramParameter(a,35721);for(b=d.Hg=0;b<e;++b)d.Hg=Math.max(d.Hg,G.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.Hg}else if(35381==b){if(-1==d.Ig)for(a=
K[a],e=G.getProgramParameter(a,35382),b=d.Ig=0;b<e;++b)d.Ig=Math.max(d.Ig,G.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.Ig}else x[c>>2]=G.getProgramParameter(K[a],b);else R(1282)}else R(1281)},Kf:function(a,b,c){if(c){a=G.wg.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;od(c,d)}else R(1281)},Nf:function(a,b,c){if(c){a=G.wg.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)},Jf:function(a,b,c){if(c){a=G.wg.getQueryObjectEXT(P[a],b);var d;
"boolean"==typeof a?d=a?1:0:d=a;od(c,d)}else R(1281)},oc:function(a,b,c){if(c){a=G.getQueryParameter(bd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)},Lf:function(a,b,c){if(c){a=G.wg.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)},qc:function(a,b,c){c?x[c>>2]=G.getQuery(a,b):R(1281)},Of:function(a,b,c){c?x[c>>2]=G.wg.getQueryEXT(a,b):R(1281)},ie:function(a,b,c){c?x[c>>2]=G.getRenderbufferParameter(a,b):R(1281)},Ta:function(a,b,c){c?(a=Q[a],
A[c>>2]=G.getSamplerParameter(a,b)):R(1281)},Ua:function(a,b,c){c?(a=Q[a],x[c>>2]=G.getSamplerParameter(a,b)):R(1281)},ge:function(a,b,c,d){a=G.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?ya(a,u,d,b):0;c&&(x[c>>2]=b)},ee:function(a,b,c,d){a=G.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},de:function(a,b,c,d){if(a=G.getShaderSource(N[a]))b=0<b&&d?ya(a,u,d,b):0,c&&(x[c>>2]=b)},he:function(a,b,c){c?35716==b?(a=G.getShaderInfoLog(N[a]),
null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=G.getShaderSource(N[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=G.getShaderParameter(N[a],b):R(1281)},ce:function(a){if(fd[a])return fd[a];switch(a){case 7939:var b=G.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=U(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=G.getParameter(a))||R(1280);b=U(b);break;case 7938:b=G.getParameter(7938);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+
b+")";b=U(b);break;case 35724:b=G.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=U(b);break;default:return R(1280),0}return fd[a]=b},wb:function(a,b){if(2>S.version)return R(1282),0;var c=gd[a];if(c)return 0>b||b>=c.length?(R(1281),0):c[b];switch(a){case 7939:return c=G.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return U(d)}),c=gd[a]=
c,0>b||b>=c.length?(R(1281),0):c[b];default:return R(1280),0}},fb:function(a,b,c,d,e){0>c?R(1281):e?(a=G.getSyncParameter(dd[a],b),x[d>>2]=a,null!==a&&d&&(x[d>>2]=1)):R(1281)},be:function(a,b,c){c?A[c>>2]=G.getTexParameter(a,b):R(1281)},ae:function(a,b,c){c?x[c>>2]=G.getTexParameter(a,b):R(1281)},Ub:function(a,b,c,d,e,g,h){a=K[a];if(a=G.getTransformFeedbackVarying(a,b))h&&0<c?(c=ya(a.name,u,h,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0),e&&(x[e>>2]=a.size),g&&(x[g>>2]=a.type)},sb:function(a,b){return G.getUniformBlockIndex(K[a],
t(b))},ub:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))R(1281);else{a=K[a];for(var e=[],g=0;g<b;g++)e.push(t(x[c+4*g>>2]));if(a=G.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)x[d+4*g>>2]=a[g]}else R(1281)},Zd:function(a,b){b=t(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=ed[a]&&ed[a].ih[b])&&0<=c&&c<a[0]?a[1]+c:-1},$d:function(a,b,c){rd(a,b,c,2)},_d:function(a,b,c){rd(a,b,c,0)},Mb:function(a,b,c){rd(a,b,c,0)},Sb:function(a,
b,c){sd(a,b,c,0)},Rb:function(a,b,c){sd(a,b,c,0)},Vd:function(a,b,c){c?x[c>>2]=G.getVertexAttribOffset(a,b):R(1281)},Yd:function(a,b,c){sd(a,b,c,2)},Xd:function(a,b,c){sd(a,b,c,5)},Ud:function(a,b){G.hint(a,b)},Ha:function(a,b,c){for(var d=ld[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];G.invalidateFramebuffer(a,d)},Ga:function(a,b,c,d,e,g,h){for(var m=ld[b],p=0;p<b;p++)m[p]=x[c+4*p>>2];G.invalidateSubFramebuffer(a,m,d,e,g,h)},Td:function(a){return(a=J[a])?G.isBuffer(a):0},Sd:function(a){return G.isEnabled(a)},
Rd:function(a){return(a=$c[a])?G.isFramebuffer(a):0},Qd:function(a){return(a=K[a])?G.isProgram(a):0},tc:function(a){return(a=bd[a])?G.isQuery(a):0},Sf:function(a){return(a=P[a])?G.wg.isQueryEXT(a):0},Pd:function(a){return(a=ad[a])?G.isRenderbuffer(a):0},$a:function(a){return(a=Q[a])?G.isSampler(a):0},Od:function(a){return(a=N[a])?G.isShader(a):0},kb:function(a){return G.isSync(dd[a])},Nd:function(a){return(a=L[a])?G.isTexture(a):0},Oa:function(a){return G.isTransformFeedback(cd[a])},$b:function(a){return(a=
O[a])?G.isVertexArray(a):0},Ff:function(a){return(a=O[a])?G.isVertexArray(a):0},Md:function(a){G.lineWidth(a)},Kd:function(a){G.linkProgram(K[a]);var b=K[a];a=ed[a]={ih:{},Vg:0,Hg:-1,Ig:-1};for(var c=a.ih,d=G.getProgramParameter(b,35718),e=0;e<d;++e){var g=G.getActiveUniform(b,e),h=g.name;a.Vg=Math.max(a.Vg,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=G.getUniformLocation(b,h);if(m){var p=jd(M);c[h]=[g.size,p];M[p]=m;for(var r=1;r<g.size;++r)m=G.getUniformLocation(b,h+"["+
r+"]"),p=jd(M),M[p]=m}}},Na:function(){G.pauseTransformFeedback()},Jd:function(a,b){3317==a&&(hd=b);G.pixelStorei(a,b)},Id:function(a,b){G.polygonOffset(a,b)},Ja:function(){R(1280)},Ia:function(){R(1280)},Pf:function(a,b){G.wg.queryCounterEXT(P[a],b)},Dc:function(a){G.readBuffer(a)},Hd:function(a,b,c,d,e,g,h){if(2<=S.version)if(G.Bg)G.readPixels(a,b,c,d,e,g,h);else{var m=V(g);G.readPixels(a,b,c,d,e,g,m,h>>X(m))}else(h=td(g,e,c,d,h))?G.readPixels(a,b,c,d,e,g,h):R(1280)},Gd:function(){},Fd:function(a,
b,c,d){G.renderbufferStorage(a,b,c,d)},fc:function(a,b,c,d,e){G.renderbufferStorageMultisample(a,b,c,d,e)},Ma:function(){G.resumeTransformFeedback()},Ed:function(a,b){G.sampleCoverage(a,!!b)},Xa:function(a,b,c){G.samplerParameterf(Q[a],b,c)},Wa:function(a,b,c){G.samplerParameterf(Q[a],b,A[c>>2])},Za:function(a,b,c){G.samplerParameteri(Q[a],b,c)},Ya:function(a,b,c){G.samplerParameteri(Q[a],b,x[c>>2])},Dd:function(a,b,c,d){G.scissor(a,b,c,d)},Cd:function(){R(1280)},Bd:function(a,b,c,d){for(var e="",
g=0;g<b;++g){var h=d?x[d+4*g>>2]:-1;e+=t(x[c+4*g>>2],0>h?void 0:h)}G.shaderSource(N[a],e)},zd:function(a,b,c){G.stencilFunc(a,b,c)},yd:function(a,b,c,d){G.stencilFuncSeparate(a,b,c,d)},xd:function(a){G.stencilMask(a)},wd:function(a,b){G.stencilMaskSeparate(a,b)},vd:function(a,b,c){G.stencilOp(a,b,c)},ud:function(a,b,c,d){G.stencilOpSeparate(a,b,c,d)},td:function(a,b,c,d,e,g,h,m,p){if(2<=S.version)if(G.ug)G.texImage2D(a,b,c,d,e,g,h,m,p);else if(p){var r=V(m);G.texImage2D(a,b,c,d,e,g,h,m,r,p>>X(r))}else G.texImage2D(a,
b,c,d,e,g,h,m,null);else G.texImage2D(a,b,c,d,e,g,h,m,p?td(m,h,d,e,p):null)},Bc:function(a,b,c,d,e,g,h,m,p,r){if(G.ug)G.texImage3D(a,b,c,d,e,g,h,m,p,r);else if(r){var w=V(p);G.texImage3D(a,b,c,d,e,g,h,m,p,w,r>>X(w))}else G.texImage3D(a,b,c,d,e,g,h,m,p,null)},sd:function(a,b,c){G.texParameterf(a,b,c)},rd:function(a,b,c){G.texParameterf(a,b,A[c>>2])},qd:function(a,b,c){G.texParameteri(a,b,c)},od:function(a,b,c){G.texParameteri(a,b,x[c>>2])},Fa:function(a,b,c,d,e){G.texStorage2D(a,b,c,d,e)},Ea:function(a,
b,c,d,e,g){G.texStorage3D(a,b,c,d,e,g)},nd:function(a,b,c,d,e,g,h,m,p){if(2<=S.version)if(G.ug)G.texSubImage2D(a,b,c,d,e,g,h,m,p);else if(p){var r=V(m);G.texSubImage2D(a,b,c,d,e,g,h,m,r,p>>X(r))}else G.texSubImage2D(a,b,c,d,e,g,h,m,null);else r=null,p&&(r=td(m,h,e,g,p)),G.texSubImage2D(a,b,c,d,e,g,h,m,r)},zc:function(a,b,c,d,e,g,h,m,p,r,w){if(G.ug)G.texSubImage3D(a,b,c,d,e,g,h,m,p,r,w);else if(w){var D=V(r);G.texSubImage3D(a,b,c,d,e,g,h,m,p,r,D,w>>X(D))}else G.texSubImage3D(a,b,c,d,e,g,h,m,p,r,null)},
Vb:function(a,b,c,d){a=K[a];for(var e=[],g=0;g<b;g++)e.push(t(x[c+4*g>>2]));G.transformFeedbackVaryings(a,e,d)},md:function(a,b){G.uniform1f(M[a],b)},ld:function(a,b,c){if(2<=S.version)G.uniform1fv(M[a],A,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);G.uniform1fv(M[a],d)}},kd:function(a,b){G.uniform1i(M[a],b)},jd:function(a,b,c){if(2<=S.version)G.uniform1iv(M[a],x,c>>2,b);else{if(288>=b)for(var d=ud[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>
2,c+4*b>>2);G.uniform1iv(M[a],d)}},Jb:function(a,b){G.uniform1ui(M[a],b)},Fb:function(a,b,c){G.uniform1uiv(M[a],y,c>>2,b)},id:function(a,b,c){G.uniform2f(M[a],b,c)},hd:function(a,b,c){if(2<=S.version)G.uniform2fv(M[a],A,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);G.uniform2fv(M[a],d)}},gd:function(a,b,c){G.uniform2i(M[a],b,c)},fd:function(a,b,c){if(2<=S.version)G.uniform2iv(M[a],x,c>>2,2*b);else{if(144>=b)for(var d=
ud[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);G.uniform2iv(M[a],d)}},Ib:function(a,b,c){G.uniform2ui(M[a],b,c)},Eb:function(a,b,c){G.uniform2uiv(M[a],y,c>>2,2*b)},ed:function(a,b,c,d){G.uniform3f(M[a],b,c,d)},dd:function(a,b,c){if(2<=S.version)G.uniform3fv(M[a],A,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);G.uniform3fv(M[a],d)}},cd:function(a,
b,c,d){G.uniform3i(M[a],b,c,d)},bd:function(a,b,c){if(2<=S.version)G.uniform3iv(M[a],x,c>>2,3*b);else{if(96>=b)for(var d=ud[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);G.uniform3iv(M[a],d)}},Hb:function(a,b,c,d){G.uniform3ui(M[a],b,c,d)},Db:function(a,b,c){G.uniform3uiv(M[a],y,c>>2,3*b)},ad:function(a,b,c,d,e){G.uniform4f(M[a],b,c,d,e)},$c:function(a,b,c){if(2<=S.version)G.uniform4fv(M[a],A,c>>2,4*b);else{if(72>=b){var d=Y[4*
b-1];c>>=2;for(var e=0;e<4*b;e+=4){var g=c+e;d[e]=A[g];d[e+1]=A[g+1];d[e+2]=A[g+2];d[e+3]=A[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);G.uniform4fv(M[a],d)}},_c:function(a,b,c,d,e){G.uniform4i(M[a],b,c,d,e)},Zc:function(a,b,c){if(2<=S.version)G.uniform4iv(M[a],x,c>>2,4*b);else{if(72>=b)for(var d=ud[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);G.uniform4iv(M[a],d)}},Gb:function(a,b,c,d,e){G.uniform4ui(M[a],
b,c,d,e)},Cb:function(a,b,c){G.uniform4uiv(M[a],y,c>>2,4*b)},ob:function(a,b,c){a=K[a];G.uniformBlockBinding(a,b,c)},Yc:function(a,b,c,d){if(2<=S.version)G.uniformMatrix2fv(M[a],!!c,A,d>>2,4*b);else{if(72>=b)for(var e=Y[4*b-1],g=0;g<4*b;g+=4)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=A[d+(4*g+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);G.uniformMatrix2fv(M[a],!!c,e)}},mc:function(a,b,c,d){G.uniformMatrix2x3fv(M[a],!!c,A,d>>2,6*b)},kc:function(a,b,c,d){G.uniformMatrix2x4fv(M[a],
!!c,A,d>>2,8*b)},Xc:function(a,b,c,d){if(2<=S.version)G.uniformMatrix3fv(M[a],!!c,A,d>>2,9*b);else{if(32>=b)for(var e=Y[9*b-1],g=0;g<9*b;g+=9)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=A[d+(4*g+12)>>2],e[g+4]=A[d+(4*g+16)>>2],e[g+5]=A[d+(4*g+20)>>2],e[g+6]=A[d+(4*g+24)>>2],e[g+7]=A[d+(4*g+28)>>2],e[g+8]=A[d+(4*g+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);G.uniformMatrix3fv(M[a],!!c,e)}},lc:function(a,b,c,d){G.uniformMatrix3x2fv(M[a],!!c,A,d>>2,6*b)},ic:function(a,b,c,d){G.uniformMatrix3x4fv(M[a],
!!c,A,d>>2,12*b)},Vc:function(a,b,c,d){if(2<=S.version)G.uniformMatrix4fv(M[a],!!c,A,d>>2,16*b);else{if(18>=b){var e=Y[16*b-1];d>>=2;for(var g=0;g<16*b;g+=16){var h=d+g;e[g]=A[h];e[g+1]=A[h+1];e[g+2]=A[h+2];e[g+3]=A[h+3];e[g+4]=A[h+4];e[g+5]=A[h+5];e[g+6]=A[h+6];e[g+7]=A[h+7];e[g+8]=A[h+8];e[g+9]=A[h+9];e[g+10]=A[h+10];e[g+11]=A[h+11];e[g+12]=A[h+12];e[g+13]=A[h+13];e[g+14]=A[h+14];e[g+15]=A[h+15]}}else e=A.subarray(d>>2,d+64*b>>2);G.uniformMatrix4fv(M[a],!!c,e)}},jc:function(a,b,c,d){G.uniformMatrix4x2fv(M[a],
!!c,A,d>>2,8*b)},hc:function(a,b,c,d){G.uniformMatrix4x3fv(M[a],!!c,A,d>>2,12*b)},Uc:function(a){G.useProgram(K[a])},Tc:function(a){G.validateProgram(K[a])},Sc:function(a,b){G.vertexAttrib1f(a,b)},Rc:function(a,b){G.vertexAttrib1f(a,A[b>>2])},Qc:function(a,b,c){G.vertexAttrib2f(a,b,c)},Pc:function(a,b){G.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},Oc:function(a,b,c,d){G.vertexAttrib3f(a,b,c,d)},Nc:function(a,b){G.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},Mc:function(a,b,c,d,e){G.vertexAttrib4f(a,b,
c,d,e)},Kc:function(a,b){G.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},Sa:function(a,b){G.vertexAttribDivisor(a,b)},Bf:function(a,b){G.vertexAttribDivisor(a,b)},Ba:function(a,b){G.vertexAttribDivisor(a,b)},Hc:function(a,b){G.vertexAttribDivisor(a,b)},Ca:function(a,b){G.vertexAttribDivisor(a,b)},Qb:function(a,b,c,d,e){G.vertexAttribI4i(a,b,c,d,e)},Ob:function(a,b){G.vertexAttribI4i(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},Pb:function(a,b,c,d,e){G.vertexAttribI4ui(a,b,c,d,e)},Nb:function(a,
b){G.vertexAttribI4ui(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},Tb:function(a,b,c,d,e){G.vertexAttribIPointer(a,b,c,d,e)},Jc:function(a,b,c,d,e,g){G.vertexAttribPointer(a,b,c,!!d,e,g)},Ic:function(a,b,c,d){G.viewport(a,b,c,d)},hb:function(a,b,c,d){G.waitSync(dd[a],b,(c>>>0)+4294967296*d)},Vf:function(a,b,c){u.copyWithin(a,b,b+c)},Wf:function(){l("OOM")},$f:function(a,b){var c=0;wd().forEach(function(d,e){var g=b+c;e=x[a+4*e>>2]=g;for(g=0;g<d.length;++g)v[e++>>0]=d.charCodeAt(g);v[e>>0]=0;c+=d.length+
1});return 0},ag:function(a,b){var c=wd();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0},g:function(a){Jd(a)},cg:function(a){try{var b=dc(a);if(null===b.fd)throw new B(8);b.Tg&&(b.Tg=null);try{b.sg.close&&b.sg.close(b)}catch(c){throw c;}finally{yb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof bc&&c instanceof B||l(c),c.Gg}},bg:function(a,b,c,d){try{a:{for(var e=dc(a),g=a=0;g<c;g++){var h=x[b+(8*g+4)>>2],m=e,p=x[b+8*g>>2],r=h,w=void 0,D=v;if(0>
r||0>w)throw new B(28);if(null===m.fd)throw new B(8);if(1===(m.flags&2097155))throw new B(8);if(16384===(m.node.mode&61440))throw new B(31);if(!m.sg.read)throw new B(28);var I="undefined"!==typeof w;if(!I)w=m.position;else if(!m.seekable)throw new B(70);var q=m.sg.read(m,D,p,r,w);I||(m.position+=q);var z=q;if(0>z){var C=-1;break a}a+=z;if(z<h)break}C=a}x[d>>2]=C;return 0}catch(W){return"undefined"!==typeof bc&&W instanceof B||l(W),W.Gg}},va:function(a,b,c,d,e){try{var g=dc(a);a=4294967296*c+(b>>>
0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Wb(g,a,d);bb=[g.position>>>0,(ab=g.position,1<=+Oa(ab)?0<ab?(Ra(+Qa(ab/4294967296),4294967295)|0)>>>0:~~+Pa((ab-+(~~ab>>>0))/4294967296)>>>0:0)];x[e>>2]=bb[0];x[e+4>>2]=bb[1];g.Tg&&0===a&&0===d&&(g.Tg=null);return 0}catch(h){return"undefined"!==typeof bc&&h instanceof B||l(h),h.Gg}},n:function(a,b,c,d){try{a:{for(var e=dc(a),g=a=0;g<c;g++){var h=e,m=x[b+8*g>>2],p=x[b+(8*g+4)>>2],r=void 0,w=v;if(0>p||0>r)throw new B(28);if(null===h.fd)throw new B(8);
if(0===(h.flags&2097155))throw new B(8);if(16384===(h.node.mode&61440))throw new B(31);if(!h.sg.write)throw new B(28);h.seekable&&h.flags&1024&&Wb(h,0,2);var D="undefined"!==typeof r;if(!D)r=h.position;else if(!h.seekable)throw new B(70);var I=h.sg.write(h,w,m,p,r,void 0);D||(h.position+=I);try{if(h.path&&Cb.onWriteToFile)Cb.onWriteToFile(h.path)}catch(C){n("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+C.message)}var q=I;if(0>q){var z=-1;break a}a+=q}z=a}x[d>>2]=z;return 0}catch(C){return"undefined"!==
typeof bc&&C instanceof B||l(C),C.Gg}},e:function(a){G.activeTexture(a)},j:function(a,b){35051==a?G.Bg=b:35052==a&&(G.ug=b);G.bindBuffer(a,J[b])},l:function(a,b,c){G.bindBufferBase(a,b,J[c])},H:function(a,b,c,d,e){G.bindBufferRange(a,b,J[c],d,e)},m:function(a,b){G.bindFramebuffer(a,$c[b])},Ld:function(a,b){G.bindRenderbuffer(a,ad[b])},k:function(a,b){G.bindTexture(a,L[b])},ec:function(a,b){G.bindTransformFeedback(a,cd[b])},B:function(a){G.bindVertexArray(O[a])},Lb:function(a,b,c,d,e,g,h,m,p,r){G.blitFramebuffer(a,
b,c,d,e,g,h,m,p,r)},Xf:function(a,b,c,d){2<=S.version?c?G.bufferData(a,u,d,c,b):G.bufferData(a,b,d):G.bufferData(a,c?u.subarray(c,c+b):b,d)},Mf:function(a,b,c,d){2<=S.version?G.bufferSubData(a,b,u,d,c):G.bufferSubData(a,b,u.subarray(d,d+c))},eb:function(a){return G.checkFramebufferStatus(a)},ta:function(a,b,c,d){G.clearBufferfi(a,b,c,d)},za:function(a,b,c){G.clearBufferfv(a,b,A,c>>2)},Va:function(a,b,c){G.clearBufferiv(a,b,x,c>>2)},Ka:function(a,b,c){G.clearBufferuiv(a,b,y,c>>2)},Wc:function(a,b,
c,d){G.clearColor(a,b,c,d)},Lc:function(a){G.clearDepth(a)},h:function(a,b,c,d,e,g,h,m,p){2<=S.version?G.ug?G.compressedTexSubImage2D(a,b,c,d,e,g,h,m,p):G.compressedTexSubImage2D(a,b,c,d,e,g,h,u,p,m):G.compressedTexSubImage2D(a,b,c,d,e,g,h,p?u.subarray(p,p+m):null)},E:function(a,b,c,d,e,g,h,m,p,r,w){G.ug?G.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,r,w):G.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,u,w,r)},x:function(a,b,c,d,e){G.copyBufferSubData(a,b,c,d,e)},pa:function(a,b,c,d,e,g,h,m){G.copyTexSubImage2D(a,
b,c,d,e,g,h,m)},oa:function(a,b,c,d,e,g,h,m,p){G.copyTexSubImage3D(a,b,c,d,e,g,h,m,p)},Z:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=J[d];e&&(G.deleteBuffer(e),e.name=0,J[d]=null,d==G.Bg&&(G.Bg=0),d==G.ug&&(G.ug=0))}},z:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];G.deleteVertexArray(O[d]);O[d]=null}},D:function(a,b,c){G.drawArrays(a,b,c)},sa:function(a,b){for(var c=ld[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];G.drawBuffers(c)},C:md,y:function(a){G.enableVertexAttribArray(a)},Be:function(a,
b,c,d){G.framebufferRenderbuffer(a,b,c,ad[d])},qe:function(a,b,c,d,e){G.framebufferTexture2D(a,b,c,L[d],e)},fe:function(a,b,c,d,e){G.framebufferTextureLayer(a,b,L[c],d,e)},ia:function(a,b){T(a,b,"createBuffer",J)},Me:function(a,b){T(a,b,"createFramebuffer",$c)},Ac:function(a,b){T(a,b,"createQuery",bd)},Wd:function(a,b){T(a,b,"createRenderbuffer",ad)},Q:function(a,b){T(a,b,"createTexture",L)},pc:function(a,b){T(a,b,"createTransformFeedback",cd)},A:function(a,b){T(a,b,"createVertexArray",O)},P:function(a){G.generateMipmap(a)},
fg:function(a,b,c){c?x[c>>2]=G.getBufferParameter(a,b):R(1281)},gf:function(){var a=G.getError()||id;id=0;return a},f:function(a,b){pd(a,b,2)},b:function(a,b){pd(a,b,0)},d:function(a){if(fd[a])return fd[a];switch(a){case 7939:var b=G.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=U(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=G.getParameter(a))||R(1280);b=U(b);break;case 7938:b=G.getParameter(7938);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+
b+")";b=U(b);break;case 35724:b=G.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=U(b);break;default:return R(1280),0}return fd[a]=b},Xe:function(a,b){if(2>S.version)return R(1282),0;var c=gd[a];if(c)return 0>b||b>=c.length?(R(1281),0):c[b];switch(a){case 7939:return c=G.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return U(d)}),c=gd[a]=
c,0>b||b>=c.length?(R(1281),0):c[b];default:return R(1280),0}},Ab:function(a,b,c){for(var d=ld[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];G.invalidateFramebuffer(a,d)},pb:function(a,b,c,d,e,g,h){for(var m=ld[b],p=0;p<b;p++)m[p]=x[c+4*p>>2];G.invalidateSubFramebuffer(a,m,d,e,g,h)},ra:function(a){G.readBuffer(a)},qa:function(a,b,c,d,e,g,h){if(2<=S.version)if(G.Bg)G.readPixels(a,b,c,d,e,g,h);else{var m=V(g);G.readPixels(a,b,c,d,e,g,m,h>>X(m))}else(h=td(g,e,c,d,h))?G.readPixels(a,b,c,d,e,g,h):R(1280)},Ad:function(a,
b,c,d){G.renderbufferStorage(a,b,c,d)},pd:function(a,b,c,d,e){G.renderbufferStorageMultisample(a,b,c,d,e)},I:function(a,b,c,d,e,g,h,m,p){if(2<=S.version)if(G.ug)G.texImage2D(a,b,c,d,e,g,h,m,p);else if(p){var r=V(m);G.texImage2D(a,b,c,d,e,g,h,m,r,p>>X(r))}else G.texImage2D(a,b,c,d,e,g,h,m,null);else G.texImage2D(a,b,c,d,e,g,h,m,p?td(m,h,d,e,p):null)},G:function(a,b,c,d,e,g,h,m,p,r){if(G.ug)G.texImage3D(a,b,c,d,e,g,h,m,p,r);else if(r){var w=V(p);G.texImage3D(a,b,c,d,e,g,h,m,p,w,r>>X(w))}else G.texImage3D(a,
b,c,d,e,g,h,m,p,null)},N:function(a,b,c){G.texParameterf(a,b,c)},L:function(a,b,c){G.texParameterf(a,b,A[c>>2])},O:function(a,b,c){G.texParameteri(a,b,c)},M:function(a,b,c){G.texParameteri(a,b,x[c>>2])},K:function(a,b,c,d,e){G.texStorage2D(a,b,c,d,e)},J:function(a,b,c,d,e,g){G.texStorage3D(a,b,c,d,e,g)},i:function(a,b,c,d,e,g,h,m,p){if(2<=S.version)if(G.ug)G.texSubImage2D(a,b,c,d,e,g,h,m,p);else if(p){var r=V(m);G.texSubImage2D(a,b,c,d,e,g,h,m,r,p>>X(r))}else G.texSubImage2D(a,b,c,d,e,g,h,m,null);
else r=null,p&&(r=td(m,h,e,g,p)),G.texSubImage2D(a,b,c,d,e,g,h,m,r)},F:function(a,b,c,d,e,g,h,m,p,r,w){if(G.ug)G.texSubImage3D(a,b,c,d,e,g,h,m,p,r,w);else if(w){var D=V(r);G.texSubImage3D(a,b,c,d,e,g,h,m,p,r,D,w>>X(D))}else G.texSubImage3D(a,b,c,d,e,g,h,m,p,r,null)},ma:function(a,b,c,d){a=K[a];for(var e=[],g=0;g<b;g++)e.push(t(x[c+4*g>>2]));G.transformFeedbackVaryings(a,e,d)},la:function(a,b,c){if(2<=S.version)G.uniform1fv(M[a],A,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];
else d=A.subarray(c>>2,c+4*b>>2);G.uniform1fv(M[a],d)}},ga:function(a,b,c){if(2<=S.version)G.uniform1iv(M[a],x,c>>2,b);else{if(288>=b)for(var d=ud[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);G.uniform1iv(M[a],d)}},ca:function(a,b,c){G.uniform1uiv(M[a],y,c>>2,b)},ka:function(a,b,c){if(2<=S.version)G.uniform2fv(M[a],A,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);G.uniform2fv(M[a],d)}},fa:function(a,
b,c){if(2<=S.version)G.uniform2iv(M[a],x,c>>2,2*b);else{if(144>=b)for(var d=ud[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);G.uniform2iv(M[a],d)}},ba:function(a,b,c){G.uniform2uiv(M[a],y,c>>2,2*b)},ja:function(a,b,c){if(2<=S.version)G.uniform3fv(M[a],A,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);G.uniform3fv(M[a],d)}},ea:function(a,b,c){if(2<=
S.version)G.uniform3iv(M[a],x,c>>2,3*b);else{if(96>=b)for(var d=ud[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);G.uniform3iv(M[a],d)}},aa:function(a,b,c){G.uniform3uiv(M[a],y,c>>2,3*b)},ha:function(a,b,c){if(2<=S.version)G.uniform4fv(M[a],A,c>>2,4*b);else{if(72>=b){var d=Y[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var g=c+e;d[e]=A[g];d[e+1]=A[g+1];d[e+2]=A[g+2];d[e+3]=A[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);G.uniform4fv(M[a],d)}},
da:function(a,b,c){if(2<=S.version)G.uniform4iv(M[a],x,c>>2,4*b);else{if(72>=b)for(var d=ud[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);G.uniform4iv(M[a],d)}},$:function(a,b,c){G.uniform4uiv(M[a],y,c>>2,4*b)},_:function(a,b,c,d){if(2<=S.version)G.uniformMatrix2fv(M[a],!!c,A,d>>2,4*b);else{if(72>=b)for(var e=Y[4*b-1],g=0;g<4*b;g+=4)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=
A[d+(4*g+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);G.uniformMatrix2fv(M[a],!!c,e)}},W:function(a,b,c,d){G.uniformMatrix2x3fv(M[a],!!c,A,d>>2,6*b)},U:function(a,b,c,d){G.uniformMatrix2x4fv(M[a],!!c,A,d>>2,8*b)},Y:function(a,b,c,d){if(2<=S.version)G.uniformMatrix3fv(M[a],!!c,A,d>>2,9*b);else{if(32>=b)for(var e=Y[9*b-1],g=0;g<9*b;g+=9)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=A[d+(4*g+12)>>2],e[g+4]=A[d+(4*g+16)>>2],e[g+5]=A[d+(4*g+20)>>2],e[g+6]=A[d+(4*g+24)>>2],e[g+7]=A[d+
(4*g+28)>>2],e[g+8]=A[d+(4*g+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);G.uniformMatrix3fv(M[a],!!c,e)}},V:function(a,b,c,d){G.uniformMatrix3x2fv(M[a],!!c,A,d>>2,6*b)},S:function(a,b,c,d){G.uniformMatrix3x4fv(M[a],!!c,A,d>>2,12*b)},X:function(a,b,c,d){if(2<=S.version)G.uniformMatrix4fv(M[a],!!c,A,d>>2,16*b);else{if(18>=b){var e=Y[16*b-1];d>>=2;for(var g=0;g<16*b;g+=16){var h=d+g;e[g]=A[h];e[g+1]=A[h+1];e[g+2]=A[h+2];e[g+3]=A[h+3];e[g+4]=A[h+4];e[g+5]=A[h+5];e[g+6]=A[h+6];e[g+7]=A[h+7];e[g+8]=A[h+8];
e[g+9]=A[h+9];e[g+10]=A[h+10];e[g+11]=A[h+11];e[g+12]=A[h+12];e[g+13]=A[h+13];e[g+14]=A[h+14];e[g+15]=A[h+15]}}else e=A.subarray(d>>2,d+64*b>>2);G.uniformMatrix4fv(M[a],!!c,e)}},T:function(a,b,c,d){G.uniformMatrix4x2fv(M[a],!!c,A,d>>2,8*b)},R:function(a,b,c,d){G.uniformMatrix4x3fv(M[a],!!c,A,d>>2,12*b)},na:function(a){G.useProgram(K[a])},u:function(a,b){G.vertexAttribDivisor(a,b)},w:function(a,b,c,d,e){G.vertexAttribIPointer(a,b,c,d,e)},v:function(a,b,c,d,e,g){G.vertexAttribPointer(a,b,c,!!d,e,g)},
memory:ta,Yf:function(a,b,c,d){return Dd(a,b,c,d)},table:ua};
(function(){function a(e){f.asm=e.exports;Sa--;f.monitorRunDependencies&&f.monitorRunDependencies(Sa);0==Sa&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua&&(e=Ua,Ua=null,e()))}function b(e){a(e.instance)}function c(e){return $a().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){n("failed to asynchronously prepare wasm: "+g);l(g)})}var d={a:Kd};Sa++;f.monitorRunDependencies&&f.monitorRunDependencies(Sa);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return n("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(sa||"function"!==typeof WebAssembly.instantiateStreaming||Xa()||Va("file://")||"function"!==typeof fetch)return c(b);fetch(Wa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){n("wasm streaming compile failed: "+g);n("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var fb=f.___wasm_call_ctors=function(){return(fb=f.___wasm_call_ctors=f.asm.ig).apply(null,arguments)};
f._main=function(){return(f._main=f.asm.jg).apply(null,arguments)};var Hd=f.___errno_location=function(){return(Hd=f.___errno_location=f.asm.kg).apply(null,arguments)},Id=f._free=function(){return(Id=f._free=f.asm.lg).apply(null,arguments)},db=f._malloc=function(){return(db=f._malloc=f.asm.mg).apply(null,arguments)},Ba=f.stackAlloc=function(){return(Ba=f.stackAlloc=f.asm.ng).apply(null,arguments)};f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.og).apply(null,arguments)};
f.dynCall_v=function(){return(f.dynCall_v=f.asm.pg).apply(null,arguments)};var Ld;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ua=function Md(){Ld||Nd();Ld||(Ua=Md)};
function Nd(a){function b(){if(!Ld&&(Ld=!0,f.calledRun=!0,!va)){f.noFSInit||Yb||(Yb=!0,Xb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?$b("stdin",f.stdin):Tb("/dev/tty","/dev/stdin"),f.stdout?$b("stdout",null,f.stdout):Tb("/dev/tty","/dev/stdout"),f.stderr?$b("stderr",null,f.stderr):Tb("/dev/tty1","/dev/stderr"),Ub("/dev/stdin","r"),Ub("/dev/stdout","w"),Ub("/dev/stderr","w"));Ia(Ka);Bb=!1;Ia(La);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Od){var c=a,d=f._main;c=c||[];
var e=c.length+1,g=Ba(4*(e+1));x[g>>2]=Aa(da);for(var h=1;h<e;h++)x[(g>>2)+h]=Aa(c[h-1]);x[(g>>2)+e]=0;try{var m=d(e,g);Jd(m,!0)}catch(p){p instanceof oa||("unwind"==p?noExitRuntime=!0:((c=p)&&"object"===typeof p&&p.stack&&(c=[p,p.stack]),n("exception thrown: "+c),ea(1,p)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ma.unshift(c);Ia(Ma)}}a=a||ca;if(!(0<Sa)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Na();
Ia(Ja);0<Sa||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Nd;function Jd(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(va=!0,f.onExit))f.onExit(a);ea(a,new oa(a))}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Od=!0;f.noInitialRun&&(Od=!1);noExitRuntime=!0;Nd();
