var g;g||=typeof Module != 'undefined' ? Module : {};var ca="object"==typeof window,da="undefined"!=typeof WorkerGlobalScope,ea="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,fa=[],ha="./this.program",ia=(a,b)=>{throw b;},ja="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ja=__filename:da&&(ja=self.location.href);var ka="",la,ma;
if(ea){var fs=require("fs");ka=__dirname+"/";ma=a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a)};la=async a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ha=process.argv[1].replace(/\\/g,"/"));fa=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ia=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da){try{ka=(new URL(".",ja)).href}catch{}da&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
la=async a=>{if(na(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var oa=console.log.bind(console),k=console.error.bind(console),m,pa=!1,qa,na=a=>a.startsWith("file://"),ra,n,p,sa,ta,t,u,v,ua,va;
function wa(a){g.onAbort?.(a);a="Aborted("+a+")";k(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa;async function ya(a){if(!m)try{var b=await la(a);return new Uint8Array(b)}catch{}if(a==xa&&m)a=new Uint8Array(m);else if(ma)a=ma(a);else throw"both async and sync fetching of the wasm failed";return a}
async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}async function Aa(a){var b=xa;if(!m&&!na(b)&&!ea)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return za(b,a)}
class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ca=a=>{for(;0<a.length;)a.shift()(g)},Da=[],Ea=[],Fa=()=>{var a=g.preRun.shift();Ea.push(a)},w=0,x=null,Ga=!0;class Ha{constructor(a){this.ub=a-24}}
var Ia=0,Ja=0,Ka=0,y={},La=a=>{a instanceof Ba||"unwind"==a||ia(1,a)},Ma=a=>{qa=a;Ga||0<Ka||(g.onExit?.(a),pa=!0);ia(a,new Ba(a))},Na=a=>{qa=a;Ma(a)},Oa=a=>{if(!pa)try{if(a(),!(Ga||0<Ka))try{qa=a=qa,Ma(a)}catch(b){La(b)}}catch(b){La(b)}},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>
6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;f++}}b[c]=0;return c-e},D=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Pa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Pa)return Pa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=
String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Qa=[],G=12288,Ra=0,H={alpha:!1,depth:!1,stencil:!1,antialias:!1},I,J,Sa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,
d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},Ta=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ua=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Va=a=>{a.Fb=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},
Xa=a=>{a.Kb=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Ya=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Za=1,K=[],$a=[],ab=[],bb=[],cb=[],db=[],eb=[],L=[],fb=[],gb=[],hb={},ib={},jb=a=>{for(var b=Za++,c=a.length;c<b;c++)a[c]=null;return b},O=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=J[c](),h=f&&jb(d);f?(f.name=h,d[h]=f):N||=1282;t[b+4*e>>2]=h}},lb=()=>{var a=g.canvas;a.lb||(a.lb=a.getContext,a.getContext=function(c,d){d=a.lb(c,d);return"webgl"==c==d instanceof WebGLRenderingContext?d:null});var b=1<H.Jb?a.getContext("webgl2",H):a.getContext("webgl",
H);return b?kb(b):0},kb=a=>{var b=jb(L),c={handle:b,attributes:H,version:H.Jb,mb:a};a.canvas&&(a.canvas.Pb=c);L[b]=c;("undefined"==typeof H.Qb||H.Qb)&&mb(c);return b},nb=a=>{P=L[a];g.ctx=J=P?.mb},mb=a=>{a||=P;if(!a.Tb){a.Tb=!0;var b=a.mb;b.qb=b.getExtension("WEBGL_multi_draw");b.Sb=b.getExtension("EXT_polygon_offset_clamp");b.Rb=b.getExtension("EXT_clip_control");b.Ob=b.getExtension("WEBGL_polygon_mode");Sa(b);Ta(b);Ua(b);Va(b);Xa(b);2<=a.version&&(b.Gb=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(2>a.version||!b.Gb)b.Gb=b.getExtension("EXT_disjoint_timer_query");Ya(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},N,P,ob=[],pb={},rb=()=>{if(!qb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ha||"./this.program"},b;for(b in pb)void 0===pb[b]?delete a[b]:a[b]=pb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qb=c}return qb},qb,sb=(a,
b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},tb=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=sb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ub=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},vb=()=>{if(ea){var a=require("crypto");
return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},wb=a=>{(wb=vb())(a)},xb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=sb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},yb=[],zb=[];function Ab(a,b){zb[a]={input:[],output:[],ob:b};Bb(a,Cb)}
var Cb={open(a){var b=zb[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close(a){a.tty.ob.fsync(a.tty)},fsync(a){a.tty.ob.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ob.Hb)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.ob.Hb(a.tty)}catch(l){throw new Q(29);}if(void 0===h&&0===e)throw new Q(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ob.Db)throw new Q(60);try{for(var e=0;e<d;e++)a.tty.ob.Db(a.tty,b[c+e])}catch(f){throw new Q(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Db={Hb(){a:{if(!yb.length){var a=null;if(ea){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(D(a)+1);a=C(a,b,0,b.length);b.length=a;yb=b}a=yb.shift()}return a},Db(a,b){null===
b||10===b?(oa(E(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(oa(E(a.output)),a.output=[])},ec(){return{$b:25856,bc:5,Zb:191,ac:35387,Yb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},fc(){return 0},hc(){return[24,80]}},Eb={Db(a,b){null===b||10===b?(k(E(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(E(a.output)),a.output=[])}},R={hb:null,jb(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new Q(63);R.hb||(R.hb={dir:{node:{kb:R.cb.kb,ib:R.cb.ib,lookup:R.cb.lookup,sb:R.cb.sb,rename:R.cb.rename,unlink:R.cb.unlink,rmdir:R.cb.rmdir,readdir:R.cb.readdir,symlink:R.cb.symlink},stream:{gb:R.eb.gb}},file:{node:{kb:R.cb.kb,ib:R.cb.ib},stream:{gb:R.eb.gb,read:R.eb.read,write:R.eb.write,Lb:R.eb.Lb,Nb:R.eb.Nb}},link:{node:{kb:R.cb.kb,ib:R.cb.ib,readlink:R.cb.readlink},stream:{}},Eb:{node:{kb:R.cb.kb,ib:R.cb.ib},stream:Fb}});c=Gb(a,b,c,d);16384===(c.mode&61440)?
(c.cb=R.hb.dir.node,c.eb=R.hb.dir.stream,c.bb={}):32768===(c.mode&61440)?(c.cb=R.hb.file.node,c.eb=R.hb.file.stream,c.fb=0,c.bb=null):40960===(c.mode&61440)?(c.cb=R.hb.link.node,c.eb=R.hb.link.stream):8192===(c.mode&61440)&&(c.cb=R.hb.Eb.node,c.eb=R.hb.Eb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.bb[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},dc(a){return a.bb?a.bb.subarray?a.bb.subarray(0,a.fb):new Uint8Array(a.bb):new Uint8Array(0)},cb:{kb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:
1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.fb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},ib(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.fb!=b&&(0==b?(a.bb=null,a.fb=0):(c=a.bb,a.bb=new Uint8Array(b),c&&
a.bb.set(c.subarray(0,Math.min(b,a.fb))),a.fb=b)))},lookup(){R.wb||(R.wb=new Q(44),R.wb.stack="<generic error, no stack>");throw R.wb;},sb(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=Hb(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.bb)throw new Q(55);e=Ib(d.parent.id,d.name);if(S[e]===d)S[e]=d.nb;else for(e=S[e];e;){if(e.nb===d){e.nb=d.nb;break}e=e.nb}}delete a.parent.bb[a.name];b.bb[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,
b){delete a.bb[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Hb(a,b),d;for(d in c.bb)throw new Q(55);delete a.bb[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.bb)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},eb:{read(a,b,c,d,e){var f=a.node.bb;if(e>=a.node.fb)return 0;a=Math.min(a.node.fb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},
write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.bb||a.bb.subarray)){if(f)return a.bb=b.subarray(c,c+d),a.fb=d;if(0===a.fb&&0===e)return a.bb=b.slice(c,c+d),a.fb=d;if(e+d<=a.fb)return a.bb.set(b.subarray(c,c+d),e),d}f=e+d;var h=a.bb?a.bb.length:0;h>=f||(f=Math.max(f,h*(1048576>h?2:1.125)>>>0),0!=h&&(f=Math.max(f,256)),h=a.bb,a.bb=new Uint8Array(f),0<a.fb&&a.bb.set(h.subarray(0,a.fb),0));if(a.bb.subarray&&b.subarray)a.bb.set(b.subarray(c,c+d),e);else for(f=0;f<
d;f++)a.bb[e+f]=b[c+f];a.fb=Math.max(a.fb,e+d);return d},gb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.fb);if(0>b)throw new Q(28);return b},Lb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.bb;if(e&2||!a||a.buffer!==n.buffer){d=!0;wa();e=void 0;if(!e)throw new Q(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);n.set(a,e)}}else d=!1,e=a.byteOffset;return{ub:e,Xb:d}},Nb(a,b,c,d){R.eb.write(a,b,0,d,
c,!1);return 0}}},Jb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Kb=null,Lb={},T=[],Mb=1,S=null,Nb=!1,Ob=!0,Pb={},Q=class{name="ErrnoError";constructor(a){this.pb=a}},Qb=class{lb={};node=null;get flags(){return this.lb.flags}set flags(a){this.lb.flags=a}get position(){return this.lb.position}set position(a){this.lb.position=a}},Rb=class{cb={};eb={};tb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.jb=a.jb;this.id=Mb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=
Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function U(a,b={}){if(!a)throw new Q(44);b.yb??(b.yb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=Kb,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=ub(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=tb(e+"/"+a[f]);try{d=Hb(d,a[f])}catch(l){if(44===l?.pb&&h&&b.Vb)return{path:e};throw l;}!d.tb||h&&!b.yb||(d=d.tb.root);if(40960===(d.mode&61440)&&(!h||b.xb)){if(!d.cb.readlink)throw new Q(52);
d=d.cb.readlink(d);"/"===d.charAt(0)||(d=ub(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new Q(32);}function Ib(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function Hb(a,b){var c=16384===(a.mode&61440)?(c=Sb(a,"x"))?c:a.cb.lookup?0:2:54;if(c)throw new Q(c);for(c=S[Ib(a.id,b)];c;c=c.nb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.cb.lookup(a,b)}
function Gb(a,b,c,d){a=new Rb(a,b,c,d);b=Ib(a.parent.id,a.name);a.nb=S[b];return S[b]=a}function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Sb(a,b){if(Ob)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ub(a,b){if(16384!==(a.mode&61440))return 54;try{return Hb(a,b),20}catch(c){}return Sb(a,"wx")}function V(a){a=T[a];if(!a)throw new Q(8);return a}
function Vb(a,b){var c=null?.eb.ib,d=c?null:a;c??=a.cb.ib;if(!c)throw new Q(63);c(d,b)}var Fb={open(a){a.eb=Lb[a.node.rdev].eb;a.eb.open?.(a)},gb(){throw new Q(70);}};function Bb(a,b){Lb[a]={eb:b}}function Wb(a,b){var c="/"===b;if(c&&Kb)throw new Q(10);if(!c&&b){var d=U(b,{yb:!1});b=d.path;d=d.node;if(d.tb)throw new Q(10);if(16384!==(d.mode&61440))throw new Q(54);}b={type:a,kc:{},Mb:b,Ub:[]};a=a.jb(b);a.jb=b;b.root=a;c?Kb=a:d&&(d.tb=b,d.jb&&d.jb.Ub.push(b))}
function Xb(a,b,c){var d=U(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new Q(28);if("."===a||".."===a)throw new Q(20);var e=Ub(d,a);if(e)throw new Q(e);if(!d.cb.sb)throw new Q(63);return d.cb.sb(d,a,b,c)}function W(a){return Xb(a,16895,0)}function Yb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Xb(a,b|8192,c)}
function Zb(a,b){if(!xb(a))throw new Q(44);var c=U(b,{parent:!0}).node;if(!c)throw new Q(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ub(c,b);if(d)throw new Q(d);if(!c.cb.symlink)throw new Q(63);c.cb.symlink(c,b,a)}
function $b(a,b){if(""===a)throw new Q(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=U(a,{xb:!(b&131072),Vb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new Q(20);}else{if(e)throw new Q(31);d=Xb(a,c|511,0);f=!0}if(!d)throw new Q(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new Q(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Tb(b)||b&576)?31:Sb(d,Tb(b)):44))throw new Q(e);if(b&512&&!f){e=d;e="string"==typeof e?U(e,{xb:!0}).node:e;if(16384===(e.mode&61440))throw new Q(31);if(32768!==(e.mode&61440))throw new Q(28);var h=Sb(e,"w");if(h)throw new Q(h);Vb(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.jb.Mb;var l=l?"/"!==e[e.length-1]?`${e}/${l}`:e+l:e;break a}l=l?`${e.name}/${l}`:e.name;e=e.parent}l={node:d,path:l,flags:b,
seekable:!0,position:0,eb:d.eb,Wb:[],error:!1};e=-1;l=Object.assign(new Qb,l);if(-1==e)a:{for(e=0;4096>=e;e++)if(!T[e])break a;throw new Q(33);}l.fd=e;T[e]=l;l.eb.open&&l.eb.open(l);f&&(c&=511,d="string"==typeof d?U(d,{xb:!0}).node:d,Vb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),cc:void 0}));!g.logReadFiles||b&1||a in Pb||(Pb[a]=1)}function ac(a,b,c){if(null===a.fd)throw new Q(8);if(!a.seekable||!a.eb.gb)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.eb.gb(a,b,c);a.Wb=[]}
function X(a,b,c){a=tb("/dev/"+a);var d=Jb(!!b,!!c);X.Ib??(X.Ib=64);var e=X.Ib++<<8|0;Bb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,h,l,r){for(var q=0,z=0;z<r;z++){try{var A=b()}catch(B){throw new Q(29);}if(void 0===A&&0===q)throw new Q(6);if(null===A||void 0===A)break;q++;h[l+z]=A}q&&(f.node.atime=Date.now());return q},write(f,h,l,r){for(var q=0;q<r;q++)try{c(h[l+q])}catch(z){throw new Q(29);}r&&(f.node.mtime=f.node.ctime=Date.now());return q}});Yb(a,d,e)}
var bc={},cc=[],dc=()=>{var a=Ya(J);return a=a.concat(a.map(b=>"GL_"+b))},ec=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(N||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>P.version){N||=1282;return}d=dc().length;break;case 33307:case 33308:if(2>P.version){N||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;
case "string":N||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:N||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];
break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){N||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:N||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:n[b]=d?1:0}}else N||=1281},Y=a=>{var b=D(a)+1,c=fc(b);
c&&C(a,p,c,b);return c},gc=a=>{a-=5120;return 0==a?n:1==a?p:2==a?sa:4==a?t:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?u:ta};S=Array(4096);Wb(R,"/");W("/tmp");W("/home");W("/home/web_user");(function(){W("/dev");Bb(259,{read:()=>0,write:(d,e,f,h)=>h,gb:()=>0});Yb("/dev/null",259);Ab(1280,Db);Ab(1536,Eb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(wb(a),b=a.byteLength);return a[--b]};X("random",c);X("urandom",c);W("/dev/shm");W("/dev/shm/tmp")})();
(function(){W("/proc");var a=W("/proc/self");W("/proc/self/fd");Wb({jb(){var b=Gb(a,"fd",16895,73);b.eb={gb:R.eb.gb};b.cb={lookup(c,d){c=+d;var e=V(c);c={parent:null,jb:{Mb:"fake"},cb:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(T.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();for(let a=0;32>a;++a)cc.push(Array(a));g.noExitRuntime&&(Ga=g.noExitRuntime);g.print&&(oa=g.print);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);
g.arguments&&(fa=g.arguments);g.thisProgram&&(ha=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var hc={32688:()=>{var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},32790:()=>{var a=g.canvas.getContext("webgl2").getExtension("WEBGL_compressed_texture_astc").getSupportedProfiles();return(0<=a.indexOf("ldr")?1:0)|(0<=a.indexOf("hdr")?2:0)}},ic,fc,jc,kc,lc={y:(a,b,c)=>{var d=new Ha(a);u[d.ub+16>>2]=0;u[d.ub+4>>2]=b;u[d.ub+8>>2]=c;Ia=a;Ja++;throw Ia;},Va:()=>wa(""),Oa:()=>{Ga=!1;Ka=0},Pa:(a,b)=>{y[a]&&(clearTimeout(y[a].id),delete y[a]);if(!b)return 0;var c=setTimeout(()=>{delete y[a];
Oa(()=>jc(a,performance.now()))},b);y[a]={id:c,mc:b};return 0},x:function(a,b){a=a?E(p,a,b):"";if("undefined"!==typeof process&&a in process.env){a=process.env[a];b=D(a)+1;var c=fc(b);C(a,p,c,b);return c}return 0},B:a=>{if(12448==a)return G=12288,1;G=12300;return 0},A:(a,b,c,d,e)=>{if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)H.alpha=0<t[b+4>>2];else if(12325==a)H.depth=0<t[b+4>>2];else if(12326==a)H.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],H.antialias=0<a;else if(12338==
a)a=t[b+4>>2],H.antialias=1==a;else if(12544==a)H.ic=12547!=t[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(t[e>>2]=1),c&&0<d&&(u[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c},z:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2>a||3<a)return G=12293,0;H.Jb=a-1;H.jc=0;I=lb();if(0!=I)return G=12288,nb(I),Qa.forEach(e=>e()),nb(null),62004;G=12297;return 0},n:(a,b)=>{if(62E3!=a)return G=12296,0;if(62004!=
b)return G=12294,0;a=I;P===L[a]&&(P=null);"object"==typeof JSEvents&&JSEvents.lc(L[a].mb.canvas);L[a]?.mb.canvas&&(L[a].mb.canvas.Pb=void 0);L[a]=null;G=12288;Ra==b&&(Ra=0);return 1},E:a=>{G=12288;return 0!=a&&1!=a?0:62E3},d:()=>G,D:(a,b,c)=>{if(62E3!=a)return G=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);G=12288;return 1},i:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;nb(d?I:null);Ra=d;G=12288;return 1},m:a=>{if(62E3!=a)return G=
12296,0;Ra=0;G=12288;return 1},r:(a,b,c)=>{ob.length=0;for(var d;d=p[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;ob.push(112==d?u[c>>2]:106==d?va[c>>3]:105==d?t[c>>2]:ua[c>>3]);c+=e?8:4}return hc[a](...ob)},Qa:()=>{wa("OOM")},sa:(a,b)=>{a=L[a];b=b?E(p,b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&Sa(J);"OES_vertex_array_object"==b&&Ta(J);"WEBGL_draw_buffers"==b&&Ua(J);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Va(J);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&Xa(J);"WEBGL_multi_draw"==b&&(J.qb=J.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(J.Sb=J.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(J.Rb=J.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(J.Ob=J.getExtension("WEBGL_polygon_mode"));return!!a.mb.getExtension(b)},ra:()=>P?P.handle:0,v:(a,b)=>{var c=0,d=0,e;for(e of rb()){var f=b+c;u[a+d>>2]=f;c+=C(e,p,f,Infinity)+1;d+=4}return 0},w:(a,b)=>{var c=rb();u[a>>2]=c.length;a=0;for(var d of c)a+=D(d)+
1;u[b>>2]=a;return 0},l:Na,Ua:function(a){try{var b=V(a);if(null===b.fd)throw new Q(8);b.zb&&(b.zb=null);try{b.eb.close&&b.eb.close(b)}catch(c){throw c;}finally{T[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof bc||"ErrnoError"!==c.name)throw c;return c.pb}},Ta:function(a,b,c,d){try{a:{var e=V(a);a=b;for(var f,h=b=0;h<c;h++){var l=u[a>>2],r=u[a+4>>2];a+=8;var q=e,z=l,A=r,B=f,Wa=n;if(0>A||0>B)throw new Q(28);if(null===q.fd)throw new Q(8);if(1===(q.flags&2097155))throw new Q(8);if(16384===
(q.node.mode&61440))throw new Q(31);if(!q.eb.read)throw new Q(28);var Z="undefined"!=typeof B;if(!Z)B=q.position;else if(!q.seekable)throw new Q(70);var aa=q.eb.read(q,Wa,z,A,B);Z||(q.position+=aa);var F=aa;if(0>F){var ba=-1;break a}b+=F;if(F<r)break;"undefined"!=typeof f&&(f+=F)}ba=b}u[d>>2]=ba;return 0}catch(M){if("undefined"==typeof bc||"ErrnoError"!==M.name)throw M;return M.pb}},Ra:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=V(a);ac(e,
b,c);va[d>>3]=BigInt(e.position);e.zb&&0===b&&0===c&&(e.zb=null);return 0}catch(f){if("undefined"==typeof bc||"ErrnoError"!==f.name)throw f;return f.pb}},Sa:function(a,b,c,d){try{a:{var e=V(a);a=b;for(var f,h=b=0;h<c;h++){var l=u[a>>2],r=u[a+4>>2];a+=8;var q=e,z=l,A=r,B=f,Wa=n;if(0>A||0>B)throw new Q(28);if(null===q.fd)throw new Q(8);if(0===(q.flags&2097155))throw new Q(8);if(16384===(q.node.mode&61440))throw new Q(31);if(!q.eb.write)throw new Q(28);q.seekable&&q.flags&1024&&ac(q,0,2);var Z="undefined"!=
typeof B;if(!Z)B=q.position;else if(!q.seekable)throw new Q(70);var aa=q.eb.write(q,Wa,z,A,B,void 0);Z||(q.position+=aa);var F=aa;if(0>F){var ba=-1;break a}b+=F;if(F<r)break;"undefined"!=typeof f&&(f+=F)}ba=b}u[d>>2]=ba;return 0}catch(M){if("undefined"==typeof bc||"ErrnoError"!==M.name)throw M;return M.pb}},j:a=>J.activeTexture(a),q:(a,b)=>{35051==a?J.vb=b:35052==a&&(J.rb=b);J.bindBuffer(a,K[b])},f:(a,b,c)=>{J.bindBufferBase(a,b,K[c])},p:(a,b,c,d,e)=>{J.bindBufferRange(a,b,K[c],d,e)},b:(a,b)=>{J.bindFramebuffer(a,
ab[b])},t:(a,b)=>{J.bindRenderbuffer(a,bb[b])},o:(a,b)=>{J.bindTexture(a,cb[b])},h:(a,b)=>{J.bindTransformFeedback(a,gb[b])},g:a=>{J.bindVertexArray(eb[a])},pa:(a,b,c,d,e,f,h,l,r,q)=>J.blitFramebuffer(a,b,c,d,e,f,h,l,r,q),C:(a,b,c,d)=>{2<=P.version?c&&b?J.bufferData(a,p,d,c,b):J.bufferData(a,b,d):J.bufferData(a,c?p.subarray(c,c+b):b,d)},Wa:(a,b,c,d)=>{2<=P.version?c&&J.bufferSubData(a,b,p,d,c):J.bufferSubData(a,b,p.subarray(d,d+c))},ma:a=>J.checkFramebufferStatus(a),ja:(a,b,c)=>{J.clearBufferfv(a,
b,v,c>>2)},la:(a,b,c)=>{J.clearBufferiv(a,b,t,c>>2)},ka:(a,b,c)=>{J.clearBufferuiv(a,b,u,c>>2)},Da:(a,b,c,d)=>J.clearColor(a,b,c,d),H:a=>J.clearDepth(a),W:(a,b,c,d,e,f,h,l,r)=>{2<=P.version?J.rb||!l?J.compressedTexSubImage2D(a,b,c,d,e,f,h,l,r):J.compressedTexSubImage2D(a,b,c,d,e,f,h,p,r,l):J.compressedTexSubImage2D(a,b,c,d,e,f,h,p.subarray(r,r+l))},U:(a,b,c,d,e,f,h,l,r,q,z)=>{J.rb?J.compressedTexSubImage3D(a,b,c,d,e,f,h,l,r,q,z):J.compressedTexSubImage3D(a,b,c,d,e,f,h,l,r,p,z,q)},aa:(a,b,c,d,e)=>
J.copyBufferSubData(a,b,c,d,e),fa:(a,b,c,d,e,f,h,l)=>J.copyTexSubImage2D(a,b,c,d,e,f,h,l),ea:(a,b,c,d,e,f,h,l,r)=>J.copyTexSubImage3D(a,b,c,d,e,f,h,l,r),ya:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=K[d];e&&(J.deleteBuffer(e),e.name=0,K[d]=null,d==J.vb&&(J.vb=0),d==J.rb&&(J.rb=0))}},N:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];J.deleteVertexArray(eb[d]);eb[d]=null}},G:(a,b)=>J.depthRange(a,b),T:(a,b,c)=>{J.drawArrays(a,b,c)},Q:(a,b,c,d)=>{J.drawArraysInstanced(a,b,c,d)},Ca:(a,b,c,d,e)=>
{J.Fb.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},ia:(a,b)=>{for(var c=cc[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];J.drawBuffers(c)},R:(a,b,c,d)=>{J.drawElements(a,b,c,d)},P:(a,b,c,d,e)=>{J.drawElementsInstanced(a,b,c,d,e)},e:(a,b,c,d,e,f,h)=>{J.Fb.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,f,h)},S:(a,b,c,d,e,f)=>{J.drawElements(a,d,e,f)},L:a=>{J.enableVertexAttribArray(a)},Ka:(a,b,c,d)=>{J.framebufferRenderbuffer(a,b,c,bb[d])},Ja:(a,b,c,d,e)=>{J.framebufferTexture2D(a,b,c,cb[d],e)},Ia:(a,
b,c,d,e)=>{J.framebufferTextureLayer(a,b,cb[c],d,e)},Ga:(a,b)=>{O(a,b,"createBuffer",K)},La:(a,b)=>{O(a,b,"createFramebuffer",ab)},ua:(a,b)=>{O(a,b,"createQuery",fb)},Ha:(a,b)=>{O(a,b,"createRenderbuffer",bb)},ca:(a,b)=>{O(a,b,"createTexture",cb)},qa:(a,b)=>{O(a,b,"createTransformFeedback",gb)},O:(a,b)=>{O(a,b,"createVertexArray",eb)},ba:a=>J.generateMipmap(a),V:(a,b,c)=>{c?t[c>>2]=J.getBufferParameter(a,b):N||=1281},M:(a,b,c,d)=>{d?c&&J.getBufferSubData(a,b,p,d,c):N||=1281},Ma:()=>{var a=J.getError()||
N;N=0;return a},k:(a,b)=>ec(a,b,2),a:(a,b)=>ec(a,b,0),va:(a,b,c)=>{if(c)if(a>=Za)N||=1281;else if(a=$a[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.Cb){var d=J.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Cb=Math.max(a.Cb,J.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.Cb}else if(35722==b){if(!a.Ab)for(d=J.getProgramParameter(a,35721),b=0;b<d;++b)a.Ab=Math.max(a.Ab,J.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Ab}else if(35381==
b){if(!a.Bb)for(d=J.getProgramParameter(a,35382),b=0;b<d;++b)a.Bb=Math.max(a.Bb,J.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Bb}else t[c>>2]=J.getProgramParameter(a,b);else N||=1281},ta:(a,b,c)=>{c?35716==b?(a=J.getShaderInfoLog(db[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=J.getShaderSource(db[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=J.getShaderParameter(db[a],b):N||=1281},c:a=>{var b=hb[a];if(!b){switch(a){case 7939:b=Y(dc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
J.getParameter(a))||(N||=1280);b=b?Y(b):0;break;case 7938:b=J.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=P.version&&(c=`OpenGL ES 3.0 (${b})`);b=Y(c);break;case 35724:b=J.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Y(b);break;default:N||=1280}hb[a]=b}return b},u:(a,b)=>{if(2>P.version)return N||=1282,0;var c=ib[a];if(c)return 0>b||b>=c.length?(N||=1281,0):c[b];switch(a){case 7939:return c=
dc().map(Y),c=ib[a]=c,0>b||b>=c.length?(N||=1281,0):c[b];default:return N||=1280,0}},oa:(a,b,c)=>{for(var d=cc[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];J.invalidateFramebuffer(a,d)},na:(a,b,c,d,e,f,h)=>{for(var l=cc[b],r=0;r<b;r++)l[r]=t[c+4*r>>2];J.invalidateSubFramebuffer(a,l,d,e,f,h)},Ba:(a,b,c,d)=>{J.qb.multiDrawArraysWEBGL(a,t,b>>2,t,c>>2,d)},za:(a,b,c,d,e)=>{J.qb.multiDrawArraysInstancedWEBGL(a,t,b>>2,t,c>>2,t,d>>2,e)},wa:(a,b,c,d,e,f)=>{J.Kb.multiDrawArraysInstancedBaseInstanceWEBGL(a,t,b>>2,t,c>>2,
t,d>>2,u,e>>2,f)},Aa:(a,b,c,d,e)=>{J.qb.multiDrawElementsWEBGL(a,t,b>>2,c,t,d>>2,e)},xa:(a,b,c,d,e,f)=>{J.qb.multiDrawElementsInstancedWEBGL(a,t,b>>2,c,t,d>>2,t,e>>2,f)},s:(a,b,c,d,e,f,h,l)=>{J.Kb.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,t,b>>2,c,t,d>>2,t,e>>2,t,f>>2,u,h>>2,l)},F:(a,b)=>{J.Ob.polygonModeWEBGL(a,b)},ha:a=>J.readBuffer(a),ga:(a,b,c,d,e,f,h)=>{if(2<=P.version)if(J.vb)J.readPixels(a,b,c,d,e,f,h);else{var l=gc(f);h>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);J.readPixels(a,b,
c,d,e,f,l,h)}else{l=gc(f);var r=d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[e-6402]||1)*l.BYTES_PER_ELEMENT+4-1&-4);(h=l.subarray(h>>>31-Math.clz32(l.BYTES_PER_ELEMENT),h+r>>>31-Math.clz32(l.BYTES_PER_ELEMENT)))?J.readPixels(a,b,c,d,e,f,h):N||=1280}},Fa:(a,b,c,d)=>J.renderbufferStorage(a,b,c,d),Ea:(a,b,c,d,e)=>J.renderbufferStorageMultisample(a,b,c,d,e),Z:(a,b,c)=>{J.texParameterf(a,b,v[c>>2])},$:(a,b,c)=>J.texParameteri(a,b,c),_:(a,b,c)=>{J.texParameteri(a,b,t[c>>2])},Y:(a,
b,c,d,e)=>J.texStorage2D(a,b,c,d,e),X:(a,b,c,d,e,f)=>J.texStorage3D(a,b,c,d,e,f),da:(a,b,c,d)=>{a=$a[a];for(var e=[],f=0;f<b;f++){var h=e,l=h.push;var r=(r=t[c+4*f>>2])?E(p,r):"";l.call(h,r)}J.transformFeedbackVaryings(a,e,d)},I:(a,b)=>{J.vertexAttribDivisor(a,b)},K:(a,b,c,d,e)=>{J.vertexAttribIPointer(a,b,c,d,e)},J:(a,b,c,d,e,f)=>{J.vertexAttribPointer(a,b,c,!!d,e,f)},Na:Ma};
function mc(a=[]){var b=ic;a.unshift(ha);var c=a.length,d=kc(4*(c+1)),e=d;a.forEach(h=>{var l=u,r=e>>2,q=D(h)+1,z=kc(q);C(h,p,z,q);l[r]=z;e+=4});u[e>>2]=0;try{var f=b(c,d);Na(f,!0)}catch(h){La(h)}}
function nc(a=fa){function b(){g.calledRun=!0;if(!pa){if(!g.noFSInit&&!Nb){var c,d;Nb=!0;c??=g.stdin;d??=g.stdout;e??=g.stderr;c?X("stdin",c):Zb("/dev/tty","/dev/stdin");d?X("stdout",null,d):Zb("/dev/tty","/dev/stdout");e?X("stderr",null,e):Zb("/dev/tty1","/dev/stderr");$b("/dev/stdin",0);$b("/dev/stdout",1);$b("/dev/stderr",1)}oc.Ya();Ob=!1;g.onRuntimeInitialized?.();g.noInitialRun||mc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var e=g.postRun.shift();
Da.push(e)}Ca(Da)}}if(0<w)x=nc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Fa();Ca(Ea);0<w?x=nc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var oc;
(async function(){function a(c){oc=c.exports;ra=oc.Xa;c=ra.buffer;n=new Int8Array(c);sa=new Int16Array(c);p=new Uint8Array(c);ta=new Uint16Array(c);t=new Int32Array(c);u=new Uint32Array(c);v=new Float32Array(c);ua=new Float64Array(c);va=new BigInt64Array(c);new BigUint64Array(c);c=oc;g._main=ic=c.Za;fc=c._a;jc=c.$a;kc=c.ab;w--;g.monitorRunDependencies?.(w);0==w&&x&&(c=x,x=null,c());return oc}w++;g.monitorRunDependencies?.(w);var b={a:lc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,
(d,e)=>{c(a(d,e))})});xa??=g.locateFile?g.locateFile("magnum-gl-info.wasm",ka):ka+"magnum-gl-info.wasm";return a((await Aa(b)).instance)})();nc();
