
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var k="",ka,la,ma,na;
if(ia)k=ha?require("path").dirname(k)+"/":__dirname+"/",ka=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")},la=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",
l),ea=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?k=self.location.href:"undefined"!==typeof document&&document.currentScript&&(k=document.currentScript.src),k=0!==k.indexOf("blob:")?k.substr(0,k.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var pa=f.print||console.log.bind(console),r=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);function qa(a){ra||(ra={});ra[a]||(ra[a]=1,r(a))}var ra,sa;f.wasmBinary&&(sa=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");var ta,ua=!1;
function assert(a,b){a||l("Assertion failed: "+b)}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function wa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&va)return va.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function t(a,b){return a?wa(u,a,b):""}
function w(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ya(a){var b=xa(a)+1,c=za(b);w(a,y,c,b);return c}var Aa,y,u,Ba,Ca,z,B,C,Da,Ea,Fa=[],Ga=[],Ha=[],Ia=[];function Ja(){var a=f.preRun.shift();Fa.unshift(a)}var Ka=0,La=null,Ma=null;f.preloadedImages={};f.preloadedAudios={};
function l(a){if(f.onAbort)f.onAbort(a);r(a);ua=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Na(a){var b=Oa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Pa(){return Na("data:application/octet-stream;base64,")}var Oa="magnum-gl-info.wasm";if(!Pa()){var Qa=Oa;Oa=f.locateFile?f.locateFile(Qa,k):k+Qa}
function Ra(){try{if(sa)return new Uint8Array(sa);if(la)return la(Oa);throw"both async and sync fetching of the wasm failed";}catch(a){l(a)}}function Sa(){return sa||!fa&&!ha||"function"!==typeof fetch||Na("file://")?Promise.resolve().then(Ra):fetch(Oa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Oa+"'";return a.arrayBuffer()}).catch(function(){return Ra()})}
var Ta,Ua,Wa={7964:function(){var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},14228:function(a){a=t(a);if("undefined"!==typeof process&&a in process.env){a=process.env[a];var b=xa(a)+1,c=Va(b);w(a,u,c,b);return c}return 0}};function Xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Og;"number"===typeof c?void 0===b.vg?Ea.get(c)():Ea.get(c)(b.vg):c(void 0===b.vg?null:b.vg)}}}
function Ya(a){this.qg=a-16;this.nh=function(b){z[this.qg+8>>2]=b};this.kh=function(b){z[this.qg+0>>2]=b};this.lh=function(){z[this.qg+4>>2]=0};this.jh=function(){y[this.qg+12>>0]=0};this.mh=function(){y[this.qg+13>>0]=0};this.bh=function(b,c){this.nh(b);this.kh(c);this.lh();this.jh();this.mh()}}var Za=0;
function $a(a,b){ab=a;bb=b;if(cb)if(0==a)db=function(){var d=Math.max(0,eb+b-fb())|0;setTimeout(gb,d)};else if(1==a)db=function(){hb(gb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}db=function(){setImmediate(gb)}}}var fb;ia?fb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?fb=dateNow:fb=function(){return performance.now()};
function ib(a){noExitRuntime=!0;assert(!cb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");cb=a;var b=jb;gb=function(){if(!ua)if(0<kb.length){var c=Date.now(),d=kb.shift();d.Og(d.vg);if(lb){var e=lb,g=0==e%1?e-1:Math.floor(e);lb=d.wh?g:(8*e+(g+.5))/9}console.log('main loop blocker "'+d.name+'" took '+(Date.now()-c)+" ms");f.setStatus&&(c=f.statusMessage||"Please wait...",
d=lb,e=mb.xh,d?d<e?f.setStatus(c+" ("+(e-d)+"/"+e+")"):f.setStatus(c):f.setStatus(""));b<jb||setTimeout(gb,0)}else if(!(b<jb))if(nb=nb+1|0,1==ab&&1<bb&&0!=nb%bb)db();else{0==ab&&(eb=fb());a:if(!(ua||f.preMainLoop&&!1===f.preMainLoop())){try{a()}catch(h){if(h instanceof oa||"unwind"==h)break a;h&&"object"===typeof h&&h.stack&&r("exception thrown: "+[h,h.stack]);throw h;}f.postMainLoop&&f.postMainLoop()}b<jb||("object"===typeof SDL&&SDL.audio&&SDL.audio.gh&&SDL.audio.gh(),db())}}}
var db=null,jb=0,cb=null,ab=0,bb=0,nb=0,kb=[],mb={},eb,gb,lb,ob=!1,pb=!1,qb=[];
function rb(){function a(){pb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!sb){sb=!0;try{tb=!0}catch(c){tb=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}ub="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:tb?null:console.log("warning: no BlobBuilder");
vb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Ug||"undefined"!==typeof vb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Ug=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Ug&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(tb)try{h=new Blob([c],{type:wb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:wb(d)}))}catch(q){qa("Blob constructor present but fails: "+
q+"; falling back to blob builder")}h||(h=new ub,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=vb.createObjectURL(h),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=p.width;q.height=p.height;q.getContext("2d").drawImage(p,0,0);f.preloadedImages[d]=q;vb.revokeObjectURL(m);e&&e(c)};p.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};p.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Ch&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(D){p||(p=!0,f.preloadedAudios[d]=D,e&&e(c))}function m(){p||(p=!0,f.preloadedAudios[d]=new Audio,g&&g())}var p=!1;if(tb){try{var q=new Blob([c],{type:wb(d)})}catch(D){return m()}q=vb.createObjectURL(q);var v=new Audio;v.addEventListener("canplaythrough",function(){h(v)},!1);v.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var D="",K=0,n=0,
x=0;x<c.length;x++)for(K=K<<8|c[x],n+=8;6<=n;){var A=K>>n-6&63;n-=6;D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==n?(D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(K&3)<<4],D+="=="):4==n&&(D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(K&15)<<2],D+="=");v.src="data:audio/x-"+d.substr(-3)+";base64,"+D;h(v)}};v.src=q;xb(function(){h(v)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&
b.addEventListener("click",function(c){!pb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function yb(a,b,c,d){if(b&&f.Cg&&a==f.canvas)return f.Cg;var e;if(b){var g={antialias:!1,alpha:!1,Eg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof zb&&(e=Ab(a,g)))var m=E[e].lg}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof F,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Cg=m,b&&Bb(e),f.th=b,qb.forEach(function(p){p()}),rb());return m}var Cb=!1,Db=void 0,Eb=void 0;
function Fb(a,b){function c(){ob=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Gb,Db&&d.requestPointerLock(),ob=!0,Eb?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=B[SDL.screen>>2]|8388608),Hb(f.canvas),Ib()):Hb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Eb?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=B[SDL.screen>>2]&
-8388609),Hb(f.canvas),Ib()):Hb(d));if(f.onFullScreen)f.onFullScreen(ob);if(f.onFullscreen)f.onFullscreen(ob)}Db=a;Eb=b;"undefined"===typeof Db&&(Db=!0);"undefined"===typeof Eb&&(Eb=!1);var d=f.canvas;Cb||(Cb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Gb(){if(!ob)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Jb=0;function hb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Jb)Jb=b+1E3/60;else for(;b+2>=Jb;)Jb+=1E3/60;setTimeout(a,Math.max(Jb-b,0))}}function xb(a){noExitRuntime=!0;setTimeout(function(){ua||a()},1E4)}
function wb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Kb=[];function Ib(){var a=f.canvas;Kb.forEach(function(b){b(a.width,a.height)})}
function Hb(a,b,c){b&&c?(a.uh=b,a.ah=c):(b=a.uh,c=a.ah);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Eb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var sb,tb,ub,vb,G=12288,Lb=0,Mb={alpha:!1,depth:!1,stencil:!1,antialias:!1},Nb;
function Ob(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Pb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Qb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Rb(a){a.Kg=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function Sb(a){a.Qg=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function Tb(a){a.yg=a.getExtension("WEBGL_multi_draw")}var Ub=1,H=[],I=[],Vb=[],Wb=[],J=[],L=[],M=[],N=[],E=[],O=[],P=[],Xb=[],Yb=[],Zb={},$b={},ac={},bc=4;function Q(a){cc||(cc=a)}function dc(a){for(var b=Ub++,c=a.length;c<b;c++)a[c]=null;return b}
function Ab(a,b){if(a=1<b.Eg?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=dc(E),d={$g:c,attributes:b,version:b.Eg,lg:a};a.canvas&&(a.canvas.Wg=d);E[c]=d;("undefined"===typeof b.Zg||b.Zg)&&ec(d);b=c}else b=0;return b}function Bb(a){R=E[a];f.Cg=F=R&&R.lg}
function ec(a){a||(a=R);if(!a.dh){a.dh=!0;var b=a.lg;Ob(b);Pb(b);Qb(b);Rb(b);Sb(b);b.fg=b.getExtension("EXT_disjoint_timer_query");!b.fg&&2<=a.version&&(b.fg=b.getExtension("EXT_disjoint_timer_query_webgl2"));Tb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var zb={},cc,R,fc=[];function hc(a,b,c,d){F.drawElements(a,b,c,d)}
function S(a,b,c,d){for(var e=0;e<a;e++){var g=F[c](),h=g&&dc(d);g?(g.name=h,d[h]=g):Q(1282);z[b+4*e>>2]=h}}function ic(a,b,c,d,e,g,h,m){b=I[b];if(a=F[a](b,c))d=m&&w(a.name,u,m,d),e&&(z[e>>2]=d),g&&(z[g>>2]=a.size),h&&(z[h>>2]=a.type)}function jc(a,b){B[a>>2]=b;B[a+4>>2]=(b-B[a>>2])/4294967296}
function kc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=F.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>R.version){Q(1282);return}d=2*(F.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=F.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Q(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z[b+4*a>>2]=e[a];break;case 2:C[b+4*a>>2]=e[a];break;case 4:y[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){Q(1280);
r("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:Q(1280);r("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:jc(b,d);break;case 0:z[b>>2]=d;break;case 2:C[b>>2]=d;break;case 4:y[b>>0]=d?1:0}}else Q(1281)}
function lc(a,b,c,d){if(c){b=F.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:Q(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Q(1280);return}break;default:Q(1280);return}switch(d){case 1:jc(c,a);break;case 0:z[c>>2]=a;break;case 2:C[c>>2]=a;break;case 4:y[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else Q(1281)}
function T(a){var b=xa(a)+1,c=Va(b);w(a,u,c,b);return c}function mc(a,b,c,d){if(c)if(a=F.getUniform(I[a],L[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:z[c>>2]=a;break;case 2:C[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:z[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b]}else Q(1281)}
function nc(a,b,c,d){if(c)if(a=F.getVertexAttrib(a,b),34975==b)z[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z[c>>2]=a;break;case 2:C[c>>2]=a;break;case 5:z[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:z[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b];break;case 5:z[c+4*b>>2]=Math.fround(a[b])}else Q(1281)}function U(a){a-=5120;return 0==a?y:1==a?u:2==a?Ba:4==a?z:6==a?C:5==a||28922==a||28520==a||30779==a||30782==a?B:Ca}
function V(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function oc(a,b,c,d,e){a=U(a);var g=V(a),h=bc;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var pc=[],qc=[],rc={};
function sc(){if(!tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in rc)a[b]=rc[b];var c=[];for(b in a)c.push(b+"="+a[b]);tc=c}return tc}var tc;
function uc(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function vc(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=uc(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function wc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function xc(a){if("/"===a)return"/";a=vc(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function yc(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){l("randomDevice")}}
function zc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=uc(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ac=[];function Bc(a,b){Ac[a]={input:[],output:[],pg:b};Cc(a,Dc)}
var Dc={open:function(a){var b=Ac[a.node.rdev];if(!b)throw new X(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.pg.flush(a.tty)},flush:function(a){a.tty.pg.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.pg.Pg)throw new X(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.pg.Pg(a.tty)}catch(m){throw new X(29);}if(void 0===h&&0===e)throw new X(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.pg.Gg)throw new X(60);
try{for(var e=0;e<d;e++)a.tty.pg.Gg(a.tty,b[c+e])}catch(g){throw new X(29);}d&&(a.node.timestamp=Date.now());return e}},Fc={Pg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Xg?Buffer.Xg(256):new Buffer(256),d=0;try{d=ma.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ec(b,!0)}return a.input.shift()},Gg:function(a,b){null===b||10===b?(pa(wa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(wa(a.output,0)),a.output=[])}},Gc={Gg:function(a,b){null===b||10===b?(r(wa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(r(wa(a.output,0)),a.output=[])}},Y={hg:null,jg:function(){return Y.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new X(63);Y.hg||(Y.hg={dir:{node:{kg:Y.bg.kg,ig:Y.bg.ig,lookup:Y.bg.lookup,wg:Y.bg.wg,rename:Y.bg.rename,unlink:Y.bg.unlink,rmdir:Y.bg.rmdir,readdir:Y.bg.readdir,symlink:Y.bg.symlink},stream:{ng:Y.cg.ng}},file:{node:{kg:Y.bg.kg,ig:Y.bg.ig},stream:{ng:Y.cg.ng,read:Y.cg.read,write:Y.cg.write,Ig:Y.cg.Ig,Rg:Y.cg.Rg,Tg:Y.cg.Tg}},link:{node:{kg:Y.bg.kg,ig:Y.bg.ig,readlink:Y.bg.readlink},stream:{}},Jg:{node:{kg:Y.bg.kg,
ig:Y.bg.ig},stream:Hc}});c=Ic(a,b,c,d);16384===(c.mode&61440)?(c.bg=Y.hg.dir.node,c.cg=Y.hg.dir.stream,c.ag={}):32768===(c.mode&61440)?(c.bg=Y.hg.file.node,c.cg=Y.hg.file.stream,c.dg=0,c.ag=null):40960===(c.mode&61440)?(c.bg=Y.hg.link.node,c.cg=Y.hg.link.stream):8192===(c.mode&61440)&&(c.bg=Y.hg.Jg.node,c.cg=Y.hg.Jg.stream);c.timestamp=Date.now();a&&(a.ag[b]=c);return c},yh:function(a){if(a.ag&&a.ag.subarray){for(var b=[],c=0;c<a.dg;++c)b.push(a.ag[c]);return b}return a.ag},zh:function(a){return a.ag?
a.ag.subarray?a.ag.subarray(0,a.dg):new Uint8Array(a.ag):new Uint8Array(0)},Lg:function(a,b){var c=a.ag?a.ag.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ag,a.ag=new Uint8Array(b),0<a.dg&&a.ag.set(c.subarray(0,a.dg),0))},hh:function(a,b){if(a.dg!=b)if(0==b)a.ag=null,a.dg=0;else{if(!a.ag||a.ag.subarray){var c=a.ag;a.ag=new Uint8Array(b);c&&a.ag.set(c.subarray(0,Math.min(b,a.dg)))}else if(a.ag||(a.ag=[]),a.ag.length>b)a.ag.length=b;else for(;a.ag.length<b;)a.ag.push(0);
a.dg=b}},bg:{kg:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.dg:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Yg=4096;b.blocks=Math.ceil(b.size/b.Yg);return b},ig:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&Y.hh(a,b.size)},lookup:function(){throw Jc[44];},wg:function(a,b,c,d){return Y.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Kc(b,c)}catch(g){}if(d)for(var e in d.ag)throw new X(55);}delete a.parent.ag[a.name];a.name=c;b.ag[c]=a;a.parent=b},unlink:function(a,b){delete a.ag[b]},rmdir:function(a,b){var c=Kc(a,b),d;for(d in c.ag)throw new X(55);delete a.ag[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ag)a.ag.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=Y.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new X(28);return a.link}},cg:{read:function(a,b,c,d,e){var g=a.node.ag;if(e>=a.node.dg)return 0;a=Math.min(a.node.dg-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ag||a.ag.subarray)){if(g)return a.ag=b.subarray(c,c+d),a.dg=d;if(0===a.dg&&0===e)return a.ag=
b.slice(c,c+d),a.dg=d;if(e+d<=a.dg)return a.ag.set(b.subarray(c,c+d),e),d}Y.Lg(a,e+d);if(a.ag.subarray&&b.subarray)a.ag.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ag[e+g]=b[c+g];a.dg=Math.max(a.dg,e+d);return d},ng:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.dg);if(0>b)throw new X(28);return b},Ig:function(a,b,c){Y.Lg(a.node,b+c);a.node.dg=Math.max(a.node.dg,b+c)},Rg:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new X(43);a=a.node.ag;
if(g&2||a.buffer!==Aa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=Va(g);c<g;)y[b+c++]=0;c=b;if(!c)throw new X(48);y.set(a,c)}else d=!1,c=a.byteOffset;return{qg:c,vh:d}},Tg:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new X(43);if(e&2)return 0;Y.cg.write(a,b,0,d,c,!1);return 0}}},Lc=null,Mc={},Nc=[],Oc=1,Pc=null,Qc=!0,Rc={},X=null,Jc={};
function Sc(a,b){a=zc("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ng:!0,Hg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Hg)throw new X(32);a=uc(a.split("/").filter(function(h){return!!h}),!1);var e=Lc;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=Kc(e,a[d]);c=vc(c+"/"+a[d]);e.xg&&(!g||g&&b.Ng)&&(e=e.xg.root);if(!g||b.Mg)for(g=0;40960===(e.mode&61440);)if(e=Tc(c),c=zc(wc(c),e),e=Sc(c,{Hg:b.Hg}).node,40<g++)throw new X(32);}return{path:c,node:e}}
function Uc(a){for(var b;;){if(a===a.parent)return a=a.jg.Sg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Vc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Pc.length}function Kc(a,b){var c;if(c=(c=Wc(a,"x"))?c:a.bg.lookup?0:2)throw new X(c,a);for(c=Pc[Vc(a.id,b)];c;c=c.fh){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.bg.lookup(a,b)}
function Ic(a,b,c,d){a=new Yc(a,b,c,d);b=Vc(a.parent.id,a.name);a.fh=Pc[b];return Pc[b]=a}var Zc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function $c(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Wc(a,b){if(Qc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function ad(a,b){try{return Kc(a,b),20}catch(c){}return Wc(a,"wx")}
function bd(){var a=4096;for(var b=0;b<=a;b++)if(!Nc[b])return b;throw new X(33);}function cd(a){dd||(dd=function(){},dd.prototype={});var b=new dd,c;for(c in a)b[c]=a[c];a=b;b=bd();a.fd=b;return Nc[b]=a}var Hc={open:function(a){a.cg=Mc[a.node.rdev].cg;a.cg.open&&a.cg.open(a)},ng:function(){throw new X(70);}};function Cc(a,b){Mc[a]={cg:b}}
function ed(a,b){var c="/"===b,d=!b;if(c&&Lc)throw new X(10);if(!c&&!d){var e=Sc(b,{Ng:!1});b=e.path;e=e.node;if(e.xg)throw new X(10);if(16384!==(e.mode&61440))throw new X(54);}b={type:a,Dh:{},Sg:b,eh:[]};a=a.jg(b);a.jg=b;b.root=a;c?Lc=a:e&&(e.xg=b,e.jg&&e.jg.eh.push(b))}function fd(a,b,c){var d=Sc(a,{parent:!0}).node;a=xc(a);if(!a||"."===a||".."===a)throw new X(28);var e=ad(d,a);if(e)throw new X(e);if(!d.bg.wg)throw new X(63);return d.bg.wg(d,a,b,c)}function gd(a){fd(a,16895,0)}
function hd(a,b,c){"undefined"===typeof c&&(c=b,b=438);fd(a,b|8192,c)}function id(a,b){if(!zc(a))throw new X(44);var c=Sc(b,{parent:!0}).node;if(!c)throw new X(44);b=xc(b);var d=ad(c,b);if(d)throw new X(d);if(!c.bg.symlink)throw new X(63);c.bg.symlink(c,b,a)}function Tc(a){a=Sc(a).node;if(!a)throw new X(44);if(!a.bg.readlink)throw new X(28);return zc(Uc(a.parent),a.bg.readlink(a))}
function jd(a,b){if(""===a)throw new X(44);if("string"===typeof b){var c=Zc[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=vc(a);try{e=Sc(a,{Mg:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new X(20);}else e=fd(a,d,0),c=!0;if(!e)throw new X(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new X(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==$c(b)||b&512)?31:Wc(e,$c(b)):44))throw new X(d);if(b&512){d=e;var g;"string"===typeof d?g=Sc(d,{Mg:!0}).node:g=d;if(!g.bg.ig)throw new X(63);if(16384===(g.mode&61440))throw new X(31);if(32768!==(g.mode&61440))throw new X(28);if(d=Wc(g,"w"))throw new X(d);g.bg.ig(g,{size:0,timestamp:Date.now()})}b&=-131713;e=cd({node:e,path:Uc(e),flags:b,seekable:!0,position:0,cg:e.cg,sh:[],error:!1});e.cg.open&&e.cg.open(e);!f.logReadFiles||b&1||(kd||(kd={}),a in kd||(kd[a]=1,r("FS.trackingDelegate error on read file: "+
a)));try{Rc.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Rc.onOpenFile(a,e))}catch(h){r("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}}function ld(a,b,c){if(null===a.fd)throw new X(8);if(!a.seekable||!a.cg.ng)throw new X(70);if(0!=c&&1!=c&&2!=c)throw new X(28);a.position=a.cg.ng(a,b,c);a.sh=[]}
function md(){X||(X=function(a,b){this.node=b;this.ih=function(c){this.og=c};this.ih(a);this.message="FS error"},X.prototype=Error(),X.prototype.constructor=X,[44].forEach(function(a){Jc[a]=new X(a);Jc[a].stack="<generic error, no stack>"}))}var nd;function od(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function pd(a,b,c){a=vc("/dev/"+a);var d=od(!!b,!!c);qd||(qd=64);var e=qd++<<8|0;Cc(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,m,p){for(var q=0,v=0;v<p;v++){try{var D=b()}catch(K){throw new X(29);}if(void 0===D&&0===q)throw new X(6);if(null===D||void 0===D)break;q++;h[m+v]=D}q&&(g.node.timestamp=Date.now());return q},write:function(g,h,m,p){for(var q=0;q<p;q++)try{c(h[m+q])}catch(v){throw new X(29);}p&&(g.node.timestamp=Date.now());return q}});
hd(a,d,e)}var qd,rd={},dd,kd;function sd(a){a=Nc[a];if(!a)throw new X(8);return a}function td(a){return 0===a%4&&(0!==a%100||0===a%400)}function ud(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var vd=[31,29,31,30,31,30,31,31,30,31,30,31],wd=[31,28,31,30,31,30,31,31,30,31,30,31];
function xd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(td(a.getFullYear())?vd:wd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function yd(a,b,c,d){function e(n,x,A){for(n="number"===typeof n?n.toString():n||"";n.length<x;)n=A[0]+n;return n}function g(n,x){return e(n,x,"0")}function h(n,x){function A(Xc){return 0>Xc?-1:0<Xc?1:0}var W;0===(W=A(n.getFullYear()-x.getFullYear()))&&0===(W=A(n.getMonth()-x.getMonth()))&&(W=A(n.getDate()-x.getDate()));return W}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),
0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function p(n){n=xd(new Date(n.gg+1900,0,1),n.Bg);var x=new Date(n.getFullYear()+1,0,4),A=m(new Date(n.getFullYear(),0,4));x=m(x);return 0>=h(A,n)?0>=h(x,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var q=z[d+40>>2];d={qh:z[d>>2],ph:z[d+4>>2],zg:z[d+8>>2],ug:z[d+12>>2],rg:z[d+16>>2],gg:z[d+20>>2],Ag:z[d+24>>2],Bg:z[d+28>>2],Fh:z[d+32>>2],oh:z[d+
36>>2],rh:q?t(q):""};c=t(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in q)c=c.replace(new RegExp(v,"g"),q[v]);var D="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
K="January February March April May June July August September October November December".split(" ");q={"%a":function(n){return D[n.Ag].substring(0,3)},"%A":function(n){return D[n.Ag]},"%b":function(n){return K[n.rg].substring(0,3)},"%B":function(n){return K[n.rg]},"%C":function(n){return g((n.gg+1900)/100|0,2)},"%d":function(n){return g(n.ug,2)},"%e":function(n){return e(n.ug,2," ")},"%g":function(n){return p(n).toString().substring(2)},"%G":function(n){return p(n)},"%H":function(n){return g(n.zg,
2)},"%I":function(n){n=n.zg;0==n?n=12:12<n&&(n-=12);return g(n,2)},"%j":function(n){return g(n.ug+ud(td(n.gg+1900)?vd:wd,n.rg-1),3)},"%m":function(n){return g(n.rg+1,2)},"%M":function(n){return g(n.ph,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.zg&&12>n.zg?"AM":"PM"},"%S":function(n){return g(n.qh,2)},"%t":function(){return"\t"},"%u":function(n){return n.Ag||7},"%U":function(n){var x=new Date(n.gg+1900,0,1),A=0===x.getDay()?x:xd(x,7-x.getDay());n=new Date(n.gg+1900,n.rg,n.ug);return 0>
h(A,n)?g(Math.ceil((31-A.getDate()+(ud(td(n.getFullYear())?vd:wd,n.getMonth()-1)-31)+n.getDate())/7),2):0===h(A,x)?"01":"00"},"%V":function(n){var x=new Date(n.gg+1901,0,4),A=m(new Date(n.gg+1900,0,4));x=m(x);var W=xd(new Date(n.gg+1900,0,1),n.Bg);return 0>h(W,A)?"53":0>=h(x,W)?"01":g(Math.ceil((A.getFullYear()<n.gg+1900?n.Bg+32-A.getDate():n.Bg+1-A.getDate())/7),2)},"%w":function(n){return n.Ag},"%W":function(n){var x=new Date(n.gg,0,1),A=1===x.getDay()?x:xd(x,0===x.getDay()?1:7-x.getDay()+1);n=
new Date(n.gg+1900,n.rg,n.ug);return 0>h(A,n)?g(Math.ceil((31-A.getDate()+(ud(td(n.getFullYear())?vd:wd,n.getMonth()-1)-31)+n.getDate())/7),2):0===h(A,x)?"01":"00"},"%y":function(n){return(n.gg+1900).toString().substring(2)},"%Y":function(n){return n.gg+1900},"%z":function(n){n=n.oh;var x=0<=n;n=Math.abs(n)/60;return(x?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.rh},"%%":function(){return"%"}};for(v in q)0<=c.indexOf(v)&&(c=c.replace(new RegExp(v,"g"),q[v](d)));v=
Ec(c,!1);if(v.length>b)return 0;y.set(v,a);return v.length-1}var zd=[];f.requestFullscreen=function(a,b){Fb(a,b)};f.requestAnimationFrame=function(a){hb(a)};f.setCanvasSize=function(a,b,c){Hb(f.canvas,a,b);c||Ib()};f.pauseMainLoop=function(){db=null;jb++};f.resumeMainLoop=function(){jb++;var a=ab,b=bb,c=cb;cb=null;ib(c);$a(a,b);db()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return yb(a,b,c,d)};for(var F,Z=0;32>Z;++Z)fc.push(Array(Z));var Ad=new Float32Array(288);for(Z=0;288>Z;++Z)pc[Z]=Ad.subarray(0,Z+1);var Bd=new Int32Array(288);for(Z=0;288>Z;++Z)qc[Z]=Bd.subarray(0,Z+1);function Yc(a,b,c,d){a||(a=this);this.parent=a;this.jg=a.jg;this.xg=null;this.id=Oc++;this.name=b;this.mode=c;this.bg={};this.cg={};this.rdev=d}
Object.defineProperties(Yc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});md();Pc=Array(4096);ed(Y,"/");gd("/tmp");gd("/home");gd("/home/web_user");
(function(){gd("/dev");Cc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});hd("/dev/null",259);Bc(1280,Fc);Bc(1536,Gc);hd("/dev/tty",1280);hd("/dev/tty1",1536);var a=yc();pd("random",a);pd("urandom",a);gd("/dev/shm");gd("/dev/shm/tmp")})();gd("/proc");gd("/proc/self");gd("/proc/self/fd");
ed({jg:function(){var a=Ic("/proc/self","fd",16895,73);a.bg={lookup:function(b,c){var d=Nc[+c];if(!d)throw new X(8);b={parent:null,jg:{Sg:"fake"},bg:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");function Ec(a,b){var c=Array(xa(a)+1);a=w(a,c,0,c.length);b&&(c.length=a);return c}Ga.push({Og:function(){Cd()}});
var Ed={Vf:function(a){return Va(a+16)+16},Td:function(a,b,c){(new Ya(a)).bh(b,c);Za++;throw a;},a:function(){l()},F:function(a){if(12448==a)return G=12288,1;G=12300;return 0},E:function(a,b,c,d,e){if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=z[b>>2];if(12321==a)Mb.alpha=0<z[b+4>>2];else if(12325==a)Mb.depth=0<z[b+4>>2];else if(12326==a)Mb.stencil=0<z[b+4>>2];else if(12337==a)a=z[b+4>>2],Mb.antialias=0<a;else if(12338==a)a=z[b+4>>2],Mb.antialias=1==a;else if(12544==a)Mb.Ah=12547!=z[b+4>>2];else if(12344==
a)break;b+=8}c&&d||e?(e&&(z[e>>2]=1),c&&0<d&&(z[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c},D:function(a,b,c,d){if(62E3!=a)return G=12296,0;for(a=1;;){b=z[d>>2];if(12440==b)a=z[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2>a||3<a)return G=12293,0;Mb.Eg=a-1;Mb.Bh=0;Nb=Ab(f.canvas,Mb);if(0!=Nb)return G=12288,Bb(Nb),f.th=!0,qb.forEach(function(e){e()}),Bb(null),62004;G=12297;return 0},C:function(a,b){if(62E3!=a)return G=12296,0;if(62004!=b)return G=12294,0;a=Nb;R===E[a]&&(R=null);
"object"===typeof JSEvents&&JSEvents.Eh(E[a].lg.canvas);E[a]&&E[a].lg.canvas&&(E[a].lg.canvas.Wg=void 0);E[a]=null;G=12288;Lb==b&&(Lb=0);return 1},H:function(){G=12288;return 62E3},c:function(){return G},G:function(a,b,c){if(62E3==a)return b&&(z[b>>2]=1),c&&(z[c>>2]=4),G=12288,1;G=12296;return 0},j:function(a,b,c,d){if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;Bb(d?Nb:null);Lb=d;G=12288;return 1},A:function(a){if(62E3!=a)return G=
12296,0;Lb=0;G=12288;return 1},q:function(a,b,c){zd.length=0;var d;for(c>>=2;d=u[b++];)(d=105>d)&&c&1&&c++,zd.push(d?Da[c++>>1]:z[c]),++c;return Wa[a].apply(null,zd)},Af:function(a){F.activeTexture(a)},zf:function(a,b){F.attachShader(I[a],M[b])},rc:function(a,b){F.beginQuery(a,O[b])},Rf:function(a,b){F.fg.beginQueryEXT(a,O[b])},Zb:function(a){F.beginTransformFeedback(a)},xf:function(a,b,c){F.bindAttribLocation(I[a],b,t(c))},wf:function(a,b){35051==a?F.mg=b:35052==a&&(F.eg=b);F.bindBuffer(a,H[b])},
Wb:function(a,b,c){F.bindBufferBase(a,b,H[c])},Xb:function(a,b,c,d,e){F.bindBufferRange(a,b,H[c],d,e)},vf:function(a,b){F.bindFramebuffer(a,Vb[b])},uf:function(a,b){F.bindRenderbuffer(a,Wb[b])},_a:function(a,b){F.bindSampler(a,P[b])},tf:function(a,b){F.bindTexture(a,J[b])},Ra:function(a,b){F.bindTransformFeedback(a,Xb[b])},dc:function(a){F.bindVertexArray(N[a])},If:function(a){F.bindVertexArray(N[a])},sf:function(a,b,c,d){F.blendColor(a,b,c,d)},rf:function(a){F.blendEquation(a)},qf:function(a,b){F.blendEquationSeparate(a,
b)},pf:function(a,b){F.blendFunc(a,b)},of:function(a,b,c,d){F.blendFuncSeparate(a,b,c,d)},gc:function(a,b,c,d,e,g,h,m,p,q){F.blitFramebuffer(a,b,c,d,e,g,h,m,p,q)},nf:function(a,b,c,d){2<=R.version?c?F.bufferData(a,u,d,c,b):F.bufferData(a,b,d):F.bufferData(a,c?u.subarray(c,c+b):b,d)},mf:function(a,b,c,d){2<=R.version?F.bufferSubData(a,b,u,d,c):F.bufferSubData(a,b,u.subarray(d,d+c))},lf:function(a){return F.checkFramebufferStatus(a)},kf:function(a){F.clear(a)},xb:function(a,b,c,d){F.clearBufferfi(a,
b,c,d)},yb:function(a,b,c){F.clearBufferfv(a,b,C,c>>2)},Ab:function(a,b,c){F.clearBufferiv(a,b,z,c>>2)},zb:function(a,b,c){F.clearBufferuiv(a,b,B,c>>2)},jf:function(a,b,c,d){F.clearColor(a,b,c,d)},hf:function(a){F.clearDepth(a)},gf:function(a){F.clearStencil(a)},hb:function(a,b,c,d){return F.clientWaitSync(Yb[a],b,(c>>>0)+4294967296*d)},ff:function(a,b,c,d){F.colorMask(!!a,!!b,!!c,!!d)},ef:function(a){F.compileShader(M[a])},df:function(a,b,c,d,e,g,h,m){2<=R.version?F.eg?F.compressedTexImage2D(a,b,
c,d,e,g,h,m):F.compressedTexImage2D(a,b,c,d,e,g,u,m,h):F.compressedTexImage2D(a,b,c,d,e,g,m?u.subarray(m,m+h):null)},xc:function(a,b,c,d,e,g,h,m,p){F.eg?F.compressedTexImage3D(a,b,c,d,e,g,h,m,p):F.compressedTexImage3D(a,b,c,d,e,g,h,u,p,m)},cf:function(a,b,c,d,e,g,h,m,p){2<=R.version?F.eg?F.compressedTexSubImage2D(a,b,c,d,e,g,h,m,p):F.compressedTexSubImage2D(a,b,c,d,e,g,h,u,p,m):F.compressedTexSubImage2D(a,b,c,d,e,g,h,p?u.subarray(p,p+m):null)},vc:function(a,b,c,d,e,g,h,m,p,q,v){F.eg?F.compressedTexSubImage3D(a,
b,c,d,e,g,h,m,p,q,v):F.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,u,v,q)},ub:function(a,b,c,d,e){F.copyBufferSubData(a,b,c,d,e)},bf:function(a,b,c,d,e,g,h,m){F.copyTexImage2D(a,b,c,d,e,g,h,m)},af:function(a,b,c,d,e,g,h,m){F.copyTexSubImage2D(a,b,c,d,e,g,h,m)},yc:function(a,b,c,d,e,g,h,m,p){F.copyTexSubImage3D(a,b,c,d,e,g,h,m,p)},$e:function(){var a=dc(I),b=F.createProgram();b.name=a;I[a]=b;return a},_e:function(a){var b=dc(M);M[b]=F.createShader(a);return b},Ze:function(a){F.cullFace(a)},Ye:function(a,
b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=H[d];e&&(F.deleteBuffer(e),e.name=0,H[d]=null,d==F.mg&&(F.mg=0),d==F.eg&&(F.eg=0))}},Xe:function(a,b){for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=Vb[d];e&&(F.deleteFramebuffer(e),e.name=0,Vb[d]=null)}},We:function(a){if(a){var b=I[a];b?(F.deleteProgram(b),b.name=0,I[a]=null,Zb[a]=null):Q(1281)}},tc:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=O[d];e&&(F.deleteQuery(e),O[d]=null)}},Tf:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=O[d];e&&
(F.fg.deleteQueryEXT(e),O[d]=null)}},Ve:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Wb[d];e&&(F.deleteRenderbuffer(e),e.name=0,Wb[d]=null)}},ab:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=P[d];e&&(F.deleteSampler(e),e.name=0,P[d]=null)}},Te:function(a){if(a){var b=M[a];b?(F.deleteShader(b),M[a]=null):Q(1281)}},ib:function(a){if(a){var b=Yb[a];b?(F.deleteSync(b),b.name=0,Yb[a]=null):Q(1281)}},Se:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=J[d];e&&(F.deleteTexture(e),
e.name=0,J[d]=null)}},Qa:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Xb[d];e&&(F.deleteTransformFeedback(e),e.name=0,Xb[d]=null)}},cc:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];F.deleteVertexArray(N[d]);N[d]=null}},Hf:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];F.deleteVertexArray(N[d]);N[d]=null}},Re:function(a){F.depthFunc(a)},Qe:function(a){F.depthMask(!!a)},Pe:function(a,b){F.depthRange(a,b)},Oe:function(a,b){F.detachShader(I[a],M[b])},Ne:function(a){F.disable(a)},
Me:function(a){F.disableVertexAttribArray(a)},Le:function(a,b,c){F.drawArrays(a,b,c)},nb:function(a,b,c,d){F.drawArraysInstanced(a,b,c,d)},Df:function(a,b,c,d){F.drawArraysInstanced(a,b,c,d)},za:function(a,b,c,d){F.drawArraysInstanced(a,b,c,d)},Fc:function(a,b,c,d){F.drawArraysInstanced(a,b,c,d)},Aa:function(a,b,c,d){F.drawArraysInstanced(a,b,c,d)},nc:function(a,b){for(var c=fc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];F.drawBuffers(c)},Dc:function(a,b){for(var c=fc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];F.drawBuffers(c)},
Ef:function(a,b){for(var c=fc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];F.drawBuffers(c)},Ke:function(a,b,c,d){F.drawElements(a,b,c,d)},mb:function(a,b,c,d,e){F.drawElementsInstanced(a,b,c,d,e)},Cf:function(a,b,c,d,e){F.drawElementsInstanced(a,b,c,d,e)},xa:function(a,b,c,d,e){F.drawElementsInstanced(a,b,c,d,e)},ya:function(a,b,c,d,e){F.drawElementsInstanced(a,b,c,d,e)},Ec:function(a,b,c,d,e){F.drawElementsInstanced(a,b,c,d,e)},Bc:function(a,b,c,d,e,g){hc(a,d,e,g)},Ie:function(a){F.enable(a)},He:function(a){F.enableVertexAttribArray(a)},
qc:function(a){F.endQuery(a)},Qf:function(a){F.fg.endQueryEXT(a)},Yb:function(){F.endTransformFeedback()},kb:function(a,b){return(a=F.fenceSync(a,b))?(b=dc(Yb),a.name=b,Yb[b]=a,b):0},Ge:function(){F.finish()},Fe:function(){F.flush()},Ee:function(a,b,c,d){F.framebufferRenderbuffer(a,b,c,Wb[d])},De:function(a,b,c,d,e){F.framebufferTexture2D(a,b,c,J[d],e)},ec:function(a,b,c,d,e){F.framebufferTextureLayer(a,b,J[c],d,e)},Ce:function(a){F.frontFace(a)},Be:function(a,b){S(a,b,"createBuffer",H)},ze:function(a,
b){S(a,b,"createFramebuffer",Vb)},uc:function(a,b){S(a,b,"createQuery",O)},s:function(a,b){for(var c=0;c<a;c++){var d=F.fg.createQueryEXT();if(!d){for(Q(1282);c<a;)z[b+4*c++>>2]=0;break}var e=dc(O);d.name=e;O[e]=d;z[b+4*c>>2]=e}},xe:function(a,b){S(a,b,"createRenderbuffer",Wb)},bb:function(a,b){S(a,b,"createSampler",P)},we:function(a,b){S(a,b,"createTexture",J)},Pa:function(a,b){S(a,b,"createTransformFeedback",Xb)},ac:function(a,b){S(a,b,"createVertexArray",N)},Gf:function(a,b){S(a,b,"createVertexArray",
N)},Ae:function(a){F.generateMipmap(a)},ve:function(a,b,c,d,e,g,h){ic("getActiveAttrib",a,b,c,d,e,g,h)},ue:function(a,b,c,d,e,g,h){ic("getActiveUniform",a,b,c,d,e,g,h)},pb:function(a,b,c,d,e){a=I[a];if(a=F.getActiveUniformBlockName(a,b))e&&0<c?(c=w(a,u,e,c),d&&(z[d>>2]=c)):d&&(z[d>>2]=0)},qb:function(a,b,c,d){if(d)switch(a=I[a],c){case 35393:a=F.getActiveUniformBlockName(a,b);z[d>>2]=a.length+1;break;default:if(a=F.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)z[d>>2]=a;else for(b=0;b<
a.length;b++)z[d+4*b>>2]=a[b]}else Q(1281)},sb:function(a,b,c,d,e){if(e)if(0<b&&0==c)Q(1281);else{a=I[a];for(var g=[],h=0;h<b;h++)g.push(z[c+4*h>>2]);if(a=F.getActiveUniforms(a,g,d))for(b=a.length,h=0;h<b;h++)z[e+4*h>>2]=a[h]}else Q(1281)},te:function(a,b,c,d){a=F.getAttachedShaders(I[a]);var e=a.length;e>b&&(e=b);z[c>>2]=e;for(b=0;b<e;++b)z[d+4*b>>2]=M.indexOf(a[b])},se:function(a,b){return F.getAttribLocation(I[a],t(b))},re:function(a,b){kc(a,b,4)},cb:function(a,b,c){c?jc(c,F.getBufferParameter(a,
b)):Q(1281)},qe:function(a,b,c){c?z[c>>2]=F.getBufferParameter(a,b):Q(1281)},pe:function(){var a=F.getError()||cc;cc=0;return a},oe:function(a,b){kc(a,b,2)},Kb:function(a,b){return F.getFragDataLocation(I[a],t(b))},me:function(a,b,c,d){a=F.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;z[d>>2]=a},db:function(a,b,c){lc(a,b,c,1)},fb:function(a,b){kc(a,b,1)},_b:function(a,b,c){lc(a,b,c,0)},le:function(a,b){kc(a,b,0)},Da:function(a,b,c,
d,e){if(0>d)Q(1281);else if(e){if(a=F.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)z[e+b>>2]=a[b]}else Q(1281)},La:function(){Q(1282)},je:function(a,b,c,d){a=F.getProgramInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?w(a,u,d,b):0;c&&(z[c>>2]=b)},ke:function(a,b,c){if(c)if(a>=Ub)Q(1281);else{var d=Zb[a];if(d)if(35716==b)a=F.getProgramInfoLog(I[a]),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b)z[c>>2]=d.Fg;else if(35722==b){if(-1==d.sg){a=I[a];
var e=F.getProgramParameter(a,35721);for(b=d.sg=0;b<e;++b)d.sg=Math.max(d.sg,F.getActiveAttrib(a,b).name.length+1)}z[c>>2]=d.sg}else if(35381==b){if(-1==d.tg)for(a=I[a],e=F.getProgramParameter(a,35382),b=d.tg=0;b<e;++b)d.tg=Math.max(d.tg,F.getActiveUniformBlockName(a,b).length+1);z[c>>2]=d.tg}else z[c>>2]=F.getProgramParameter(I[a],b);else Q(1282)}else Q(1281)},Lf:function(a,b,c){if(c){a=O[a];b=2>R.version?F.fg.getQueryObjectEXT(a,b):F.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;
jc(c,d)}else Q(1281)},Nf:function(a,b,c){if(c){a=F.fg.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z[c>>2]=d}else Q(1281)},Kf:function(a,b,c){if(c){a=O[a];b=2>R.version?F.fg.getQueryObjectEXT(a,b):F.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;jc(c,d)}else Q(1281)},oc:function(a,b,c){if(c){a=F.getQueryParameter(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z[c>>2]=d}else Q(1281)},Mf:function(a,b,c){if(c){a=F.fg.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;z[c>>2]=d}else Q(1281)},pc:function(a,b,c){c?z[c>>2]=F.getQuery(a,b):Q(1281)},Of:function(a,b,c){c?z[c>>2]=F.fg.getQueryEXT(a,b):Q(1281)},ie:function(a,b,c){c?z[c>>2]=F.getRenderbufferParameter(a,b):Q(1281)},Ua:function(a,b,c){c?(a=P[a],C[c>>2]=F.getSamplerParameter(a,b)):Q(1281)},Va:function(a,b,c){c?(a=P[a],z[c>>2]=F.getSamplerParameter(a,b)):Q(1281)},ge:function(a,b,c,d){a=F.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?w(a,u,d,b):0;c&&(z[c>>2]=b)},fe:function(a,b,
c,d){a=F.getShaderPrecisionFormat(a,b);z[c>>2]=a.rangeMin;z[c+4>>2]=a.rangeMax;z[d>>2]=a.precision},ee:function(a,b,c,d){if(a=F.getShaderSource(M[a]))b=0<b&&d?w(a,u,d,b):0,c&&(z[c>>2]=b)},he:function(a,b,c){c?35716==b?(a=F.getShaderInfoLog(M[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=F.getShaderSource(M[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=F.getShaderParameter(M[a],b):Q(1281)},de:function(a){if($b[a])return $b[a];switch(a){case 7939:var b=F.getSupportedExtensions()||[];
b=b.concat(b.map(function(d){return"GL_"+d}));b=T(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=F.getParameter(a))||Q(1280);b=T(b);break;case 7938:b=F.getParameter(7938);b=2<=R.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=T(b);break;case 35724:b=F.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=T(b);break;default:return Q(1280),0}return $b[a]=b},vb:function(a,
b){if(2>R.version)return Q(1282),0;var c=ac[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=F.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return T(d)}),c=ac[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},eb:function(a,b,c,d,e){0>c?Q(1281):e?(a=F.getSyncParameter(Yb[a],b),z[d>>2]=a,null!==a&&d&&(z[d>>2]=1)):Q(1281)},be:function(a,b,c){c?C[c>>2]=F.getTexParameter(a,b):Q(1281)},ae:function(a,b,c){c?z[c>>
2]=F.getTexParameter(a,b):Q(1281)},Ub:function(a,b,c,d,e,g,h){a=I[a];if(a=F.getTransformFeedbackVarying(a,b))h&&0<c?(c=w(a.name,u,h,c),d&&(z[d>>2]=c)):d&&(z[d>>2]=0),e&&(z[e>>2]=a.size),g&&(z[g>>2]=a.type)},rb:function(a,b){return F.getUniformBlockIndex(I[a],t(b))},tb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))Q(1281);else{a=I[a];for(var e=[],g=0;g<b;g++)e.push(t(z[c+4*g>>2]));if(a=F.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)z[d+4*g>>2]=a[g]}else Q(1281)},Zd:function(a,b){b=t(b);var c=0;
if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Zb[a]&&Zb[a].Vg[b])&&0<=c&&c<a[0]?a[1]+c:-1},$d:function(a,b,c){mc(a,b,c,2)},_d:function(a,b,c){mc(a,b,c,0)},Lb:function(a,b,c){mc(a,b,c,0)},Rb:function(a,b,c){nc(a,b,c,0)},Qb:function(a,b,c){nc(a,b,c,0)},Wd:function(a,b,c){c?z[c>>2]=F.getVertexAttribOffset(a,b):Q(1281)},Yd:function(a,b,c){nc(a,b,c,2)},Xd:function(a,b,c){nc(a,b,c,5)},Vd:function(a,b){F.hint(a,b)},Ia:function(a,b,c){for(var d=
fc[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];F.invalidateFramebuffer(a,d)},Ga:function(a,b,c,d,e,g,h){for(var m=fc[b],p=0;p<b;p++)m[p]=z[c+4*p>>2];F.invalidateSubFramebuffer(a,m,d,e,g,h)},Ud:function(a){return(a=H[a])?F.isBuffer(a):0},Rd:function(a){return F.isEnabled(a)},Qd:function(a){return(a=Vb[a])?F.isFramebuffer(a):0},Pd:function(a){return(a=I[a])?F.isProgram(a):0},sc:function(a){return(a=O[a])?F.isQuery(a):0},Sf:function(a){return(a=O[a])?F.fg.isQueryEXT(a):0},Od:function(a){return(a=Wb[a])?F.isRenderbuffer(a):
0},$a:function(a){return(a=P[a])?F.isSampler(a):0},Nd:function(a){return(a=M[a])?F.isShader(a):0},jb:function(a){return F.isSync(Yb[a])},Md:function(a){return(a=J[a])?F.isTexture(a):0},Oa:function(a){return F.isTransformFeedback(Xb[a])},$b:function(a){return(a=N[a])?F.isVertexArray(a):0},Ff:function(a){return(a=N[a])?F.isVertexArray(a):0},Ld:function(a){F.lineWidth(a)},Kd:function(a){F.linkProgram(I[a]);var b=I[a];a=Zb[a]={Vg:{},Fg:0,sg:-1,tg:-1};for(var c=a.Vg,d=F.getProgramParameter(b,35718),e=
0;e<d;++e){var g=F.getActiveUniform(b,e),h=g.name;a.Fg=Math.max(a.Fg,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=F.getUniformLocation(b,h);if(m){var p=dc(L);c[h]=[g.size,p];L[p]=m;for(var q=1;q<g.size;++q)m=F.getUniformLocation(b,h+"["+q+"]"),p=dc(L),L[p]=m}}},Na:function(){F.pauseTransformFeedback()},Jd:function(a,b){3317==a&&(bc=b);F.pixelStorei(a,b)},Id:function(a,b){F.polygonOffset(a,b)},Ka:function(){Q(1280)},Ja:function(){Q(1280)},Pf:function(a,b){F.fg.queryCounterEXT(O[a],
b)},Cc:function(a){F.readBuffer(a)},Gd:function(a,b,c,d,e,g,h){if(2<=R.version)if(F.mg)F.readPixels(a,b,c,d,e,g,h);else{var m=U(g);F.readPixels(a,b,c,d,e,g,m,h>>V(m))}else(h=oc(g,e,c,d,h))?F.readPixels(a,b,c,d,e,g,h):Q(1280)},Fd:function(){},Ed:function(a,b,c,d){F.renderbufferStorage(a,b,c,d)},fc:function(a,b,c,d,e){F.renderbufferStorageMultisample(a,b,c,d,e)},Ma:function(){F.resumeTransformFeedback()},Dd:function(a,b){F.sampleCoverage(a,!!b)},Xa:function(a,b,c){F.samplerParameterf(P[a],b,c)},Wa:function(a,
b,c){F.samplerParameterf(P[a],b,C[c>>2])},Za:function(a,b,c){F.samplerParameteri(P[a],b,c)},Ya:function(a,b,c){F.samplerParameteri(P[a],b,z[c>>2])},Cd:function(a,b,c,d){F.scissor(a,b,c,d)},Bd:function(){Q(1280)},Ad:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?z[d+4*g>>2]:-1;e+=t(z[c+4*g>>2],0>h?void 0:h)}F.shaderSource(M[a],e)},zd:function(a,b,c){F.stencilFunc(a,b,c)},yd:function(a,b,c,d){F.stencilFuncSeparate(a,b,c,d)},xd:function(a){F.stencilMask(a)},vd:function(a,b){F.stencilMaskSeparate(a,
b)},ud:function(a,b,c){F.stencilOp(a,b,c)},td:function(a,b,c,d){F.stencilOpSeparate(a,b,c,d)},sd:function(a,b,c,d,e,g,h,m,p){if(2<=R.version)if(F.eg)F.texImage2D(a,b,c,d,e,g,h,m,p);else if(p){var q=U(m);F.texImage2D(a,b,c,d,e,g,h,m,q,p>>V(q))}else F.texImage2D(a,b,c,d,e,g,h,m,null);else F.texImage2D(a,b,c,d,e,g,h,m,p?oc(m,h,d,e,p):null)},Ac:function(a,b,c,d,e,g,h,m,p,q){if(F.eg)F.texImage3D(a,b,c,d,e,g,h,m,p,q);else if(q){var v=U(p);F.texImage3D(a,b,c,d,e,g,h,m,p,v,q>>V(v))}else F.texImage3D(a,b,
c,d,e,g,h,m,p,null)},rd:function(a,b,c){F.texParameterf(a,b,c)},qd:function(a,b,c){F.texParameterf(a,b,C[c>>2])},pd:function(a,b,c){F.texParameteri(a,b,c)},od:function(a,b,c){F.texParameteri(a,b,z[c>>2])},Fa:function(a,b,c,d,e){F.texStorage2D(a,b,c,d,e)},Ea:function(a,b,c,d,e,g){F.texStorage3D(a,b,c,d,e,g)},nd:function(a,b,c,d,e,g,h,m,p){if(2<=R.version)if(F.eg)F.texSubImage2D(a,b,c,d,e,g,h,m,p);else if(p){var q=U(m);F.texSubImage2D(a,b,c,d,e,g,h,m,q,p>>V(q))}else F.texSubImage2D(a,b,c,d,e,g,h,m,
null);else q=null,p&&(q=oc(m,h,e,g,p)),F.texSubImage2D(a,b,c,d,e,g,h,m,q)},zc:function(a,b,c,d,e,g,h,m,p,q,v){if(F.eg)F.texSubImage3D(a,b,c,d,e,g,h,m,p,q,v);else if(v){var D=U(q);F.texSubImage3D(a,b,c,d,e,g,h,m,p,q,D,v>>V(D))}else F.texSubImage3D(a,b,c,d,e,g,h,m,p,q,null)},Vb:function(a,b,c,d){a=I[a];for(var e=[],g=0;g<b;g++)e.push(t(z[c+4*g>>2]));F.transformFeedbackVaryings(a,e,d)},md:function(a,b){F.uniform1f(L[a],b)},kd:function(a,b,c){if(2<=R.version)F.uniform1fv(L[a],C,c>>2,b);else{if(288>=b)for(var d=
pc[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);F.uniform1fv(L[a],d)}},jd:function(a,b){F.uniform1i(L[a],b)},id:function(a,b,c){if(2<=R.version)F.uniform1iv(L[a],z,c>>2,b);else{if(288>=b)for(var d=qc[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);F.uniform1iv(L[a],d)}},Jb:function(a,b){F.uniform1ui(L[a],b)},Eb:function(a,b,c){F.uniform1uiv(L[a],B,c>>2,b)},hd:function(a,b,c){F.uniform2f(L[a],b,c)},gd:function(a,b,c){if(2<=R.version)F.uniform2fv(L[a],C,c>>2,
2*b);else{if(144>=b)for(var d=pc[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);F.uniform2fv(L[a],d)}},fd:function(a,b,c){F.uniform2i(L[a],b,c)},ed:function(a,b,c){if(2<=R.version)F.uniform2iv(L[a],z,c>>2,2*b);else{if(144>=b)for(var d=qc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);F.uniform2iv(L[a],d)}},Ib:function(a,b,c){F.uniform2ui(L[a],b,c)},Db:function(a,b,c){F.uniform2uiv(L[a],B,c>>2,2*b)},dd:function(a,
b,c,d){F.uniform3f(L[a],b,c,d)},cd:function(a,b,c){if(2<=R.version)F.uniform3fv(L[a],C,c>>2,3*b);else{if(96>=b)for(var d=pc[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);F.uniform3fv(L[a],d)}},bd:function(a,b,c,d){F.uniform3i(L[a],b,c,d)},$c:function(a,b,c){if(2<=R.version)F.uniform3iv(L[a],z,c>>2,3*b);else{if(96>=b)for(var d=qc[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>
2,c+12*b>>2);F.uniform3iv(L[a],d)}},Gb:function(a,b,c,d){F.uniform3ui(L[a],b,c,d)},Cb:function(a,b,c){F.uniform3uiv(L[a],B,c>>2,3*b)},_c:function(a,b,c,d,e){F.uniform4f(L[a],b,c,d,e)},Zc:function(a,b,c){if(2<=R.version)F.uniform4fv(L[a],C,c>>2,4*b);else{if(72>=b){var d=pc[4*b-1],e=C;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=C.subarray(c>>2,c+16*b>>2);F.uniform4fv(L[a],d)}},Yc:function(a,b,c,d,e){F.uniform4i(L[a],b,c,d,e)},Xc:function(a,b,c){if(2<=
R.version)F.uniform4iv(L[a],z,c>>2,4*b);else{if(72>=b)for(var d=qc[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);F.uniform4iv(L[a],d)}},Fb:function(a,b,c,d,e){F.uniform4ui(L[a],b,c,d,e)},Bb:function(a,b,c){F.uniform4uiv(L[a],B,c>>2,4*b)},ob:function(a,b,c){a=I[a];F.uniformBlockBinding(a,b,c)},Wc:function(a,b,c,d){if(2<=R.version)F.uniformMatrix2fv(L[a],!!c,C,d>>2,4*b);else{if(72>=b)for(var e=pc[4*b-1],
g=0;g<4*b;g+=4)e[g]=C[d+4*g>>2],e[g+1]=C[d+(4*g+4)>>2],e[g+2]=C[d+(4*g+8)>>2],e[g+3]=C[d+(4*g+12)>>2];else e=C.subarray(d>>2,d+16*b>>2);F.uniformMatrix2fv(L[a],!!c,e)}},mc:function(a,b,c,d){F.uniformMatrix2x3fv(L[a],!!c,C,d>>2,6*b)},kc:function(a,b,c,d){F.uniformMatrix2x4fv(L[a],!!c,C,d>>2,8*b)},Vc:function(a,b,c,d){if(2<=R.version)F.uniformMatrix3fv(L[a],!!c,C,d>>2,9*b);else{if(32>=b)for(var e=pc[9*b-1],g=0;g<9*b;g+=9)e[g]=C[d+4*g>>2],e[g+1]=C[d+(4*g+4)>>2],e[g+2]=C[d+(4*g+8)>>2],e[g+3]=C[d+(4*g+
12)>>2],e[g+4]=C[d+(4*g+16)>>2],e[g+5]=C[d+(4*g+20)>>2],e[g+6]=C[d+(4*g+24)>>2],e[g+7]=C[d+(4*g+28)>>2],e[g+8]=C[d+(4*g+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);F.uniformMatrix3fv(L[a],!!c,e)}},lc:function(a,b,c,d){F.uniformMatrix3x2fv(L[a],!!c,C,d>>2,6*b)},ic:function(a,b,c,d){F.uniformMatrix3x4fv(L[a],!!c,C,d>>2,12*b)},Uc:function(a,b,c,d){if(2<=R.version)F.uniformMatrix4fv(L[a],!!c,C,d>>2,16*b);else{if(18>=b){var e=pc[16*b-1],g=C;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=g[m];e[h+1]=g[m+
1];e[h+2]=g[m+2];e[h+3]=g[m+3];e[h+4]=g[m+4];e[h+5]=g[m+5];e[h+6]=g[m+6];e[h+7]=g[m+7];e[h+8]=g[m+8];e[h+9]=g[m+9];e[h+10]=g[m+10];e[h+11]=g[m+11];e[h+12]=g[m+12];e[h+13]=g[m+13];e[h+14]=g[m+14];e[h+15]=g[m+15]}}else e=C.subarray(d>>2,d+64*b>>2);F.uniformMatrix4fv(L[a],!!c,e)}},jc:function(a,b,c,d){F.uniformMatrix4x2fv(L[a],!!c,C,d>>2,8*b)},hc:function(a,b,c,d){F.uniformMatrix4x3fv(L[a],!!c,C,d>>2,12*b)},Tc:function(a){F.useProgram(I[a])},Sc:function(a){F.validateProgram(I[a])},Rc:function(a,b){F.vertexAttrib1f(a,
b)},Qc:function(a,b){F.vertexAttrib1f(a,C[b>>2])},Pc:function(a,b,c){F.vertexAttrib2f(a,b,c)},Oc:function(a,b){F.vertexAttrib2f(a,C[b>>2],C[b+4>>2])},Nc:function(a,b,c,d){F.vertexAttrib3f(a,b,c,d)},Mc:function(a,b){F.vertexAttrib3f(a,C[b>>2],C[b+4>>2],C[b+8>>2])},Lc:function(a,b,c,d,e){F.vertexAttrib4f(a,b,c,d,e)},Kc:function(a,b){F.vertexAttrib4f(a,C[b>>2],C[b+4>>2],C[b+8>>2],C[b+12>>2])},Ta:function(a,b){F.vertexAttribDivisor(a,b)},Bf:function(a,b){F.vertexAttribDivisor(a,b)},Ba:function(a,b){F.vertexAttribDivisor(a,
b)},Gc:function(a,b){F.vertexAttribDivisor(a,b)},Ca:function(a,b){F.vertexAttribDivisor(a,b)},Pb:function(a,b,c,d,e){F.vertexAttribI4i(a,b,c,d,e)},Nb:function(a,b){F.vertexAttribI4i(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},Ob:function(a,b,c,d,e){F.vertexAttribI4ui(a,b,c,d,e)},Mb:function(a,b){F.vertexAttribI4ui(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},Tb:function(a,b,c,d,e){F.vertexAttribIPointer(a,b,c,d,e)},Jc:function(a,b,c,d,e,g){F.vertexAttribPointer(a,b,c,!!d,e,g)},Ic:function(a,b,c,d){F.viewport(a,
b,c,d)},gb:function(a,b,c,d){F.waitSync(Yb[a],b,(c>>>0)+4294967296*d)},t:function(a,b,c){u.copyWithin(a,b,b+c)},u:function(){l("OOM")},ua:function(a,b){a=E[a];b=t(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Ob(F);"OES_vertex_array_object"==b&&Pb(F);"WEBGL_draw_buffers"==b&&Qb(F);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Rb(F);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Sb(F);"WEBGL_multi_draw"==b&&Tb(F);return!!a.lg.getExtension(b)},va:function(){return R?
R.$g:0},w:function(a,b){try{var c=0;sc().forEach(function(d,e){var g=b+c;e=z[a+4*e>>2]=g;for(g=0;g<d.length;++g)y[e++>>0]=d.charCodeAt(g);y[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof rd&&d instanceof X||l(d),d.og}},x:function(a,b){try{var c=sc();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0}catch(e){return"undefined"!==typeof rd&&e instanceof X||l(e),e.og}},h:function(a){Dd(a)},z:function(a){try{var b=sd(a);if(null===b.fd)throw new X(8);
b.Dg&&(b.Dg=null);try{b.cg.close&&b.cg.close(b)}catch(c){throw c;}finally{Nc[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof rd&&c instanceof X||l(c),c.og}},y:function(a,b,c,d){try{a:{for(var e=sd(a),g=a=0;g<c;g++){var h=z[b+(8*g+4)>>2],m=e,p=z[b+8*g>>2],q=h,v=void 0,D=y;if(0>q||0>v)throw new X(28);if(null===m.fd)throw new X(8);if(1===(m.flags&2097155))throw new X(8);if(16384===(m.node.mode&61440))throw new X(31);if(!m.cg.read)throw new X(28);var K="undefined"!==typeof v;if(!K)v=
m.position;else if(!m.seekable)throw new X(70);var n=m.cg.read(m,D,p,q,v);K||(m.position+=n);var x=n;if(0>x){var A=-1;break a}a+=x;if(x<h)break}A=a}z[d>>2]=A;return 0}catch(W){return"undefined"!==typeof rd&&W instanceof X||l(W),W.og}},wa:function(a,b,c,d,e){try{var g=sd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ld(g,a,d);Ua=[g.position>>>0,(Ta=g.position,1<=+Math.abs(Ta)?0<Ta?(Math.min(+Math.floor(Ta/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Ta-+(~~Ta>>>0))/
4294967296)>>>0:0)];z[e>>2]=Ua[0];z[e+4>>2]=Ua[1];g.Dg&&0===a&&0===d&&(g.Dg=null);return 0}catch(h){return"undefined"!==typeof rd&&h instanceof X||l(h),h.og}},i:function(a,b,c,d){try{a:{for(var e=sd(a),g=a=0;g<c;g++){var h=e,m=z[b+8*g>>2],p=z[b+(8*g+4)>>2],q=void 0,v=y;if(0>p||0>q)throw new X(28);if(null===h.fd)throw new X(8);if(0===(h.flags&2097155))throw new X(8);if(16384===(h.node.mode&61440))throw new X(31);if(!h.cg.write)throw new X(28);h.seekable&&h.flags&1024&&ld(h,0,2);var D="undefined"!==
typeof q;if(!D)q=h.position;else if(!h.seekable)throw new X(70);var K=h.cg.write(h,v,m,p,q,void 0);D||(h.position+=K);try{if(h.path&&Rc.onWriteToFile)Rc.onWriteToFile(h.path)}catch(A){r("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+A.message)}var n=K;if(0>n){var x=-1;break a}a+=n}x=a}z[d>>2]=x;return 0}catch(A){return"undefined"!==typeof rd&&A instanceof X||l(A),A.og}},f:function(a){F.activeTexture(a)},k:function(a,b){35051==a?F.mg=b:35052==a&&(F.eg=b);F.bindBuffer(a,H[b])},
p:function(a,b,c){F.bindBufferBase(a,b,H[c])},K:function(a,b,c,d,e){F.bindBufferRange(a,b,H[c],d,e)},o:function(a,b){F.bindFramebuffer(a,Vb[b])},wd:function(a,b){F.bindRenderbuffer(a,Wb[b])},n:function(a,b){F.bindTexture(a,J[b])},sa:function(a,b){F.bindTransformFeedback(a,Xb[b])},P:function(a){F.bindVertexArray(N[a])},ra:function(a,b,c,d,e,g,h,m,p,q){F.blitFramebuffer(a,b,c,d,e,g,h,m,p,q)},Jf:function(a,b,c,d){2<=R.version?c?F.bufferData(a,u,d,c,b):F.bufferData(a,b,d):F.bufferData(a,c?u.subarray(c,
c+b):b,d)},yf:function(a,b,c,d){2<=R.version?F.bufferSubData(a,b,u,d,c):F.bufferSubData(a,b,u.subarray(d,d+c))},oa:function(a){return F.checkFramebufferStatus(a)},ja:function(a,b,c,d){F.clearBufferfi(a,b,c,d)},la:function(a,b,c){F.clearBufferfv(a,b,C,c>>2)},na:function(a,b,c){F.clearBufferiv(a,b,z,c>>2)},ma:function(a,b,c){F.clearBufferuiv(a,b,B,c>>2)},Hc:function(a,b,c,d){F.clearColor(a,b,c,d)},wc:function(a){F.clearDepth(a)},l:function(a,b,c,d,e,g,h,m,p){2<=R.version?F.eg?F.compressedTexSubImage2D(a,
b,c,d,e,g,h,m,p):F.compressedTexSubImage2D(a,b,c,d,e,g,h,u,p,m):F.compressedTexSubImage2D(a,b,c,d,e,g,h,p?u.subarray(p,p+m):null)},S:function(a,b,c,d,e,g,h,m,p,q,v){F.eg?F.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,q,v):F.compressedTexSubImage3D(a,b,c,d,e,g,h,m,p,u,v,q)},B:function(a,b,c,d,e){F.copyBufferSubData(a,b,c,d,e)},fa:function(a,b,c,d,e,g,h,m){F.copyTexSubImage2D(a,b,c,d,e,g,h,m)},ea:function(a,b,c,d,e,g,h,m,p){F.copyTexSubImage3D(a,b,c,d,e,g,h,m,p)},ba:function(a,b){for(var c=0;c<a;c++){var d=
z[b+4*c>>2],e=H[d];e&&(F.deleteBuffer(e),e.name=0,H[d]=null,d==F.mg&&(F.mg=0),d==F.eg&&(F.eg=0))}},N:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];F.deleteVertexArray(N[d]);N[d]=null}},R:function(a,b,c){F.drawArrays(a,b,c)},bc:function(a,b,c,d,e){F.Kg.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},ia:function(a,b){for(var c=fc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];F.drawBuffers(c)},Q:hc,e:function(a,b,c,d,e,g,h){F.Kg.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,g,h)},M:function(a){F.enableVertexAttribArray(a)},
ne:function(a,b,c,d){F.framebufferRenderbuffer(a,b,c,Wb[d])},ce:function(a,b,c,d,e){F.framebufferTexture2D(a,b,c,J[d],e)},Sd:function(a,b,c,d,e){F.framebufferTextureLayer(a,b,J[c],d,e)},ka:function(a,b){S(a,b,"createBuffer",H)},ye:function(a,b){S(a,b,"createFramebuffer",Vb)},Ha:function(a,b){S(a,b,"createQuery",O)},Hd:function(a,b){S(a,b,"createRenderbuffer",Wb)},ca:function(a,b){S(a,b,"createTexture",J)},ta:function(a,b){S(a,b,"createTransformFeedback",Xb)},O:function(a,b){S(a,b,"createVertexArray",
N)},aa:function(a){F.generateMipmap(a)},Uf:function(a,b,c){c?z[c>>2]=F.getBufferParameter(a,b):Q(1281)},Ue:function(){var a=F.getError()||cc;cc=0;return a},g:function(a,b){kc(a,b,2)},b:function(a,b){kc(a,b,0)},d:function(a){if($b[a])return $b[a];switch(a){case 7939:var b=F.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=T(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=F.getParameter(a))||Q(1280);b=T(b);break;case 7938:b=F.getParameter(7938);b=2<=R.version?
"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=T(b);break;case 35724:b=F.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=T(b);break;default:return Q(1280),0}return $b[a]=b},Je:function(a,b){if(2>R.version)return Q(1282),0;var c=ac[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=F.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),
c=c.map(function(d){return T(d)}),c=ac[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},qa:function(a,b,c){for(var d=fc[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];F.invalidateFramebuffer(a,d)},pa:function(a,b,c,d,e,g,h){for(var m=fc[b],p=0;p<b;p++)m[p]=z[c+4*p>>2];F.invalidateSubFramebuffer(a,m,d,e,g,h)},Hb:function(a,b,c,d){F.yg.multiDrawArraysWEBGL(a,z,b>>2,z,c>>2,d)},lb:function(a,b,c,d,e){F.yg.multiDrawArraysInstancedWEBGL(a,z,b>>2,z,c>>2,z,d>>2,e)},Sa:function(a,b,c,d,e,g){F.Qg.multiDrawArraysInstancedBaseInstanceWEBGL(a,
z,b>>2,z,c>>2,z,d>>2,B,e>>2,g)},Sb:function(a,b,c,d,e){F.yg.multiDrawElementsWEBGL(a,z,b>>2,c,z,d>>2,e)},wb:function(a,b,c,d,e,g){F.yg.multiDrawElementsInstancedWEBGL(a,z,b>>2,c,z,d>>2,z,e>>2,g)},r:function(a,b,c,d,e,g,h,m){F.Qg.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,z,b>>2,c,z,d>>2,z,e>>2,z,g>>2,B,h>>2,m)},ha:function(a){F.readBuffer(a)},ga:function(a,b,c,d,e,g,h){if(2<=R.version)if(F.mg)F.readPixels(a,b,c,d,e,g,h);else{var m=U(g);F.readPixels(a,b,c,d,e,g,m,h>>V(m))}else(h=oc(g,
e,c,d,h))?F.readPixels(a,b,c,d,e,g,h):Q(1280)},ld:function(a,b,c,d){F.renderbufferStorage(a,b,c,d)},ad:function(a,b,c,d,e){F.renderbufferStorageMultisample(a,b,c,d,e)},V:function(a,b,c,d,e,g,h,m,p){if(2<=R.version)if(F.eg)F.texImage2D(a,b,c,d,e,g,h,m,p);else if(p){var q=U(m);F.texImage2D(a,b,c,d,e,g,h,m,q,p>>V(q))}else F.texImage2D(a,b,c,d,e,g,h,m,null);else F.texImage2D(a,b,c,d,e,g,h,m,p?oc(m,h,d,e,p):null)},U:function(a,b,c,d,e,g,h,m,p,q){if(F.eg)F.texImage3D(a,b,c,d,e,g,h,m,p,q);else if(q){var v=
U(p);F.texImage3D(a,b,c,d,e,g,h,m,p,v,q>>V(v))}else F.texImage3D(a,b,c,d,e,g,h,m,p,null)},_:function(a,b,c){F.texParameterf(a,b,c)},Y:function(a,b,c){F.texParameterf(a,b,C[c>>2])},$:function(a,b,c){F.texParameteri(a,b,c)},Z:function(a,b,c){F.texParameteri(a,b,z[c>>2])},X:function(a,b,c,d,e){F.texStorage2D(a,b,c,d,e)},W:function(a,b,c,d,e,g){F.texStorage3D(a,b,c,d,e,g)},m:function(a,b,c,d,e,g,h,m,p){if(2<=R.version)if(F.eg)F.texSubImage2D(a,b,c,d,e,g,h,m,p);else if(p){var q=U(m);F.texSubImage2D(a,
b,c,d,e,g,h,m,q,p>>V(q))}else F.texSubImage2D(a,b,c,d,e,g,h,m,null);else q=null,p&&(q=oc(m,h,e,g,p)),F.texSubImage2D(a,b,c,d,e,g,h,m,q)},T:function(a,b,c,d,e,g,h,m,p,q,v){if(F.eg)F.texSubImage3D(a,b,c,d,e,g,h,m,p,q,v);else if(v){var D=U(q);F.texSubImage3D(a,b,c,d,e,g,h,m,p,q,D,v>>V(D))}else F.texSubImage3D(a,b,c,d,e,g,h,m,p,q,null)},da:function(a,b,c,d){a=I[a];for(var e=[],g=0;g<b;g++)e.push(t(z[c+4*g>>2]));F.transformFeedbackVaryings(a,e,d)},I:function(a,b){F.vertexAttribDivisor(a,b)},L:function(a,
b,c,d,e){F.vertexAttribIPointer(a,b,c,d,e)},J:function(a,b,c,d,e,g){F.vertexAttribPointer(a,b,c,!!d,e,g)},v:function(a,b,c,d){return yd(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;ta=f.asm.Wf;Aa=e=ta.buffer;f.HEAP8=y=new Int8Array(e);f.HEAP16=Ba=new Int16Array(e);f.HEAP32=z=new Int32Array(e);f.HEAPU8=u=new Uint8Array(e);f.HEAPU16=Ca=new Uint16Array(e);f.HEAPU32=B=new Uint32Array(e);f.HEAPF32=C=new Float32Array(e);f.HEAPF64=Da=new Float64Array(e);Ea=f.asm.Xf;Ka--;f.monitorRunDependencies&&f.monitorRunDependencies(Ka);0==Ka&&(null!==La&&(clearInterval(La),La=null),Ma&&(e=Ma,Ma=null,e()))}function b(e){a(e.instance)}function c(e){return Sa().then(function(g){return WebAssembly.instantiate(g,
d)}).then(e,function(g){r("failed to asynchronously prepare wasm: "+g);l(g)})}var d={a:Ed};Ka++;f.monitorRunDependencies&&f.monitorRunDependencies(Ka);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return sa||"function"!==typeof WebAssembly.instantiateStreaming||Pa()||Na("file://")||"function"!==typeof fetch?c(b):fetch(Oa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(g){r("wasm streaming compile failed: "+g);r("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Cd=f.___wasm_call_ctors=function(){return(Cd=f.___wasm_call_ctors=f.asm.Yf).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Zf).apply(null,arguments)};var Va=f._malloc=function(){return(Va=f._malloc=f.asm._f).apply(null,arguments)},za=f.stackAlloc=function(){return(za=f.stackAlloc=f.asm.$f).apply(null,arguments)},Fd;
function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ma=function Gd(){Fd||Hd();Fd||(Ma=Gd)};
function Hd(a){function b(){if(!Fd&&(Fd=!0,f.calledRun=!0,!ua)){f.noFSInit||nd||(nd=!0,md(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?pd("stdin",f.stdin):id("/dev/tty","/dev/stdin"),f.stdout?pd("stdout",null,f.stdout):id("/dev/tty","/dev/stdout"),f.stderr?pd("stderr",null,f.stderr):id("/dev/tty1","/dev/stderr"),jd("/dev/stdin",0),jd("/dev/stdout",1),jd("/dev/stderr",1));Xa(Ga);Qc=!1;Xa(Ha);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Id){var c=a,d=f._main;c=c||[];var e=
c.length+1,g=za(4*(e+1));z[g>>2]=ya(da);for(var h=1;h<e;h++)z[(g>>2)+h]=ya(c[h-1]);z[(g>>2)+e]=0;try{var m=d(e,g);Dd(m,!0)}catch(p){p instanceof oa||("unwind"==p?noExitRuntime=!0:((c=p)&&"object"===typeof p&&p.stack&&(c=[p,p.stack]),r("exception thrown: "+c),ea(1,p)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ia.unshift(c);Xa(Ia)}}a=a||ca;if(!(0<Ka)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ja();
Xa(Fa);0<Ka||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Hd;function Dd(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ua=!0}ea(a,new oa(a))}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Id=!0;f.noInitialRun&&(Id=!1);noExitRuntime=!0;Hd();
