
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa={},l;for(l in h)h.hasOwnProperty(l)&&(aa[l]=h[l]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,m=!1,fa=!1,ha=!1;ea="object"===typeof window;m="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!m;var p="",ia,ja,ka,la;
if(fa)p=m?require("path").dirname(p)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
t),da=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||m)m?p=self.location.href:"undefined"!==typeof document&&document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=h.print||console.log.bind(console),w=h.printErr||console.warn.bind(console);for(l in aa)aa.hasOwnProperty(l)&&(h[l]=aa[l]);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var oa;h.wasmBinary&&(oa=h.wasmBinary);var noExitRuntime;h.noExitRuntime&&(noExitRuntime=h.noExitRuntime);"object"!==typeof WebAssembly&&t("no native wasm support detected");var pa,qa=!1;function assert(a,b){a||t("Assertion failed: "+b)}
var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?sa(z,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ua(a){var b=ta(a)+1,c=va(b);A(a,B,c,b);return c}var wa,B,z,xa,ya,D,E,F,G,H,za=[],Aa=[],Ba=[],Ca=[],Da=[];function Ea(){var a=h.preRun.shift();za.unshift(a)}var Fa=0,Ga=null,Ha=null;h.preloadedImages={};h.preloadedAudios={};
function t(a){if(h.onAbort)h.onAbort(a);w(a);qa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ia(a){var b=Ja;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ka(){return Ia("data:application/octet-stream;base64,")}var Ja="magnum-picking.wasm";if(!Ka()){var La=Ja;Ja=h.locateFile?h.locateFile(La,p):p+La}
function Ma(){try{if(oa)return new Uint8Array(oa);if(ja)return ja(Ja);throw"both async and sync fetching of the wasm failed";}catch(a){t(a)}}function Na(){return oa||!ea&&!m||"function"!==typeof fetch||Ia("file://")?Promise.resolve().then(Ma):fetch(Ja,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ja+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}
var Oa,Pa,Qa={4485:function(){var a=h.keyboardListeningElement||document;if(a===document)return 1;if(a===window)return 2;if("id"in a){var b=ta(a.id)+1,c=I(b);A(a.id,z,c,b);return c}return 0},4888:function(a,b){function c(){var d=window.requestAnimationFrame(c);H.get(a).apply(null,[b])||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},5156:function(){var a=h.canvas.id,b=ta(a)+1,c=I(b);A(a,z,c,b);return c},131118:function(a){a=y(a);if("undefined"!==typeof process&&a in process.env){a=
process.env[a];var b=ta(a)+1,c=I(b);A(a,z,c,b);return c}return 0}};function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Kc;"number"===typeof c?void 0===b.kc?H.get(c)():H.get(c)(b.kc):c(void 0===b.kc?null:b.kc)}}}
function Sa(a){this.Wb=a-16;this.Yc=function(b){D[this.Wb+8>>2]=b};this.Vc=function(b){D[this.Wb+0>>2]=b};this.Wc=function(){D[this.Wb+4>>2]=0};this.Uc=function(){B[this.Wb+12>>0]=0};this.Xc=function(){B[this.Wb+13>>0]=0};this.Mc=function(b,c){this.Yc(b);this.Vc(c);this.Wc();this.Uc();this.Xc()}}var Ta=0;function Ua(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Va(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ua(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Wa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Xa(a){if("/"===a)return"/";a=Va(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ya(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){t("randomDevice")}}
function Za(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ua(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var $a=[];function ab(a,b){$a[a]={input:[],output:[],Vb:b};bb(a,cb)}
var cb={open:function(a){var b=$a[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Vb.flush(a.tty)},flush:function(a){a.tty.Vb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Vb.zc)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Vb.zc(a.tty)}catch(n){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Vb.pc)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.Vb.pc(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},eb={zc:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.Hc?Buffer.Hc(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=db(b,!0)}return a.input.shift()},pc:function(a,b){null===b||10===b?(na(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(sa(a.output,0)),a.output=[])}},fb={pc:function(a,b){null===b||10===b?(w(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(w(sa(a.output,0)),a.output=[])}},L={Nb:null,Pb:function(){return L.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);L.Nb||(L.Nb={dir:{node:{Rb:L.Ib.Rb,Ob:L.Ib.Ob,lookup:L.Ib.lookup,dc:L.Ib.dc,rename:L.Ib.rename,unlink:L.Ib.unlink,rmdir:L.Ib.rmdir,readdir:L.Ib.readdir,symlink:L.Ib.symlink},stream:{Tb:L.Jb.Tb}},file:{node:{Rb:L.Ib.Rb,Ob:L.Ib.Ob},stream:{Tb:L.Jb.Tb,read:L.Jb.read,write:L.Jb.write,rc:L.Jb.rc,Bc:L.Jb.Bc,Dc:L.Jb.Dc}},link:{node:{Rb:L.Ib.Rb,Ob:L.Ib.Ob,readlink:L.Ib.readlink},stream:{}},sc:{node:{Rb:L.Ib.Rb,
Ob:L.Ib.Ob},stream:gb}});c=hb(a,b,c,d);16384===(c.mode&61440)?(c.Ib=L.Nb.dir.node,c.Jb=L.Nb.dir.stream,c.Hb={}):32768===(c.mode&61440)?(c.Ib=L.Nb.file.node,c.Jb=L.Nb.file.stream,c.Kb=0,c.Hb=null):40960===(c.mode&61440)?(c.Ib=L.Nb.link.node,c.Jb=L.Nb.link.stream):8192===(c.mode&61440)&&(c.Ib=L.Nb.sc.node,c.Jb=L.Nb.sc.stream);c.timestamp=Date.now();a&&(a.Hb[b]=c);return c},hd:function(a){if(a.Hb&&a.Hb.subarray){for(var b=[],c=0;c<a.Kb;++c)b.push(a.Hb[c]);return b}return a.Hb},jd:function(a){return a.Hb?
a.Hb.subarray?a.Hb.subarray(0,a.Kb):new Uint8Array(a.Hb):new Uint8Array(0)},wc:function(a,b){var c=a.Hb?a.Hb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Hb,a.Hb=new Uint8Array(b),0<a.Kb&&a.Hb.set(c.subarray(0,a.Kb),0))},Sc:function(a,b){if(a.Kb!=b)if(0==b)a.Hb=null,a.Kb=0;else{if(!a.Hb||a.Hb.subarray){var c=a.Hb;a.Hb=new Uint8Array(b);c&&a.Hb.set(c.subarray(0,Math.min(b,a.Kb)))}else if(a.Hb||(a.Hb=[]),a.Hb.length>b)a.Hb.length=b;else for(;a.Hb.length<b;)a.Hb.push(0);
a.Kb=b}},Ib:{Rb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Kb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ic=4096;b.blocks=Math.ceil(b.size/b.Ic);return b},Ob:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&L.Sc(a,b.size)},lookup:function(){throw ib[44];},dc:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=jb(b,c)}catch(f){}if(d)for(var e in d.Hb)throw new J(55);}delete a.parent.Hb[a.name];a.name=c;b.Hb[c]=a;a.parent=b},unlink:function(a,b){delete a.Hb[b]},rmdir:function(a,b){var c=jb(a,b),d;for(d in c.Hb)throw new J(55);delete a.Hb[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Hb)a.Hb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},Jb:{read:function(a,b,c,d,e){var f=a.node.Hb;if(e>=a.node.Kb)return 0;a=Math.min(a.node.Kb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Hb||a.Hb.subarray)){if(f)return a.Hb=b.subarray(c,c+d),a.Kb=d;if(0===a.Kb&&0===e)return a.Hb=
b.slice(c,c+d),a.Kb=d;if(e+d<=a.Kb)return a.Hb.set(b.subarray(c,c+d),e),d}L.wc(a,e+d);if(a.Hb.subarray&&b.subarray)a.Hb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Hb[e+f]=b[c+f];a.Kb=Math.max(a.Kb,e+d);return d},Tb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Kb);if(0>b)throw new J(28);return b},rc:function(a,b,c){L.wc(a.node,b+c);a.node.Kb=Math.max(a.node.Kb,b+c)},Bc:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.Hb;
if(f&2||a.buffer!==wa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=I(f);c<f;)B[b+c++]=0;c=b;if(!c)throw new J(48);B.set(a,c)}else d=!1,c=a.byteOffset;return{Wb:c,dd:d}},Dc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;L.Jb.write(a,b,0,d,c,!1);return 0}}},kb=null,lb={},mb=[],nb=1,ob=null,pb=!0,qb={},J=null,ib={};
function M(a,b){a=Za("/",a);b=b||{};if(!a)return{path:"",node:null};var c={yc:!0,qc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.qc)throw new J(32);a=Ua(a.split("/").filter(function(g){return!!g}),!1);var e=kb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=jb(e,a[d]);c=Va(c+"/"+a[d]);e.ec&&(!f||f&&b.yc)&&(e=e.ec.root);if(!f||b.mc)for(f=0;40960===(e.mode&61440);)if(e=rb(c),c=Za(Wa(c),e),e=M(c,{qc:b.qc}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function sb(a){for(var b;;){if(a===a.parent)return a=a.Pb.Cc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ob.length}function jb(a,b){var c;if(c=(c=ub(a,"x"))?c:a.Ib.lookup?0:2)throw new J(c,a);for(c=ob[tb(a.id,b)];c;c=c.Rc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ib.lookup(a,b)}
function hb(a,b,c,d){a=new vb(a,b,c,d);b=tb(a.parent.id,a.name);a.Rc=ob[b];return ob[b]=a}var wb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function xb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ub(a,b){if(pb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function yb(a,b){try{return jb(a,b),20}catch(c){}return ub(a,"wx")}
function zb(a){var b=4096;for(a=a||0;a<=b;a++)if(!mb[a])return a;throw new J(33);}function Ab(a,b){Bb||(Bb=function(){},Bb.prototype={});var c=new Bb,d;for(d in a)c[d]=a[d];a=c;b=zb(b);a.fd=b;return mb[b]=a}var gb={open:function(a){a.Jb=lb[a.node.rdev].Jb;a.Jb.open&&a.Jb.open(a)},Tb:function(){throw new J(70);}};function bb(a,b){lb[a]={Jb:b}}
function Cb(a,b){var c="/"===b,d=!b;if(c&&kb)throw new J(10);if(!c&&!d){var e=M(b,{yc:!1});b=e.path;e=e.node;if(e.ec)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,ld:{},Cc:b,Qc:[]};a=a.Pb(b);a.Pb=b;b.root=a;c?kb=a:e&&(e.ec=b,e.Pb&&e.Pb.Qc.push(b))}function Db(a,b,c){var d=M(a,{parent:!0}).node;a=Xa(a);if(!a||"."===a||".."===a)throw new J(28);var e=yb(d,a);if(e)throw new J(e);if(!d.Ib.dc)throw new J(63);return d.Ib.dc(d,a,b,c)}function N(a){Db(a,16895,0)}
function Eb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Db(a,b|8192,c)}function Fb(a,b){if(!Za(a))throw new J(44);var c=M(b,{parent:!0}).node;if(!c)throw new J(44);b=Xa(b);var d=yb(c,b);if(d)throw new J(d);if(!c.Ib.symlink)throw new J(63);c.Ib.symlink(c,b,a)}function rb(a){a=M(a).node;if(!a)throw new J(44);if(!a.Ib.readlink)throw new J(28);return Za(sb(a.parent),a.Ib.readlink(a))}
function Gb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=wb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Va(a);try{f=M(a,{mc:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Db(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==xb(b)||b&512)?31:ub(f,xb(b)):44))throw new J(c);if(b&512){c=f;var g;"string"===typeof c?g=M(c,{mc:!0}).node:g=c;if(!g.Ib.Ob)throw new J(63);if(16384===(g.mode&61440))throw new J(31);if(32768!==(g.mode&61440))throw new J(28);if(c=ub(g,"w"))throw new J(c);g.Ib.Ob(g,{size:0,timestamp:Date.now()})}b&=-131713;d=Ab({node:f,path:sb(f),flags:b,seekable:!0,position:0,Jb:f.Jb,cd:[],error:!1},d);d.Jb.open&&d.Jb.open(d);!h.logReadFiles||b&1||(Hb||(Hb={}),a in Hb||(Hb[a]=1,w("FS.trackingDelegate error on read file: "+
a)));try{qb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),qb.onOpenFile(a,f))}catch(n){w("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function Ib(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.Jb.Tb)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.Jb.Tb(a,b,c);a.cd=[]}
function Jb(){J||(J=function(a,b){this.node=b;this.Tc=function(c){this.Mb=c};this.Tc(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){ib[a]=new J(a);ib[a].stack="<generic error, no stack>"}))}var Kb;function Lb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Mb(a,b,c){a=Va("/dev/"+a);var d=Lb(!!b,!!c);Nb||(Nb=64);var e=Nb++<<8|0;bb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,n,q){for(var r=0,v=0;v<q;v++){try{var C=b()}catch(R){throw new J(29);}if(void 0===C&&0===r)throw new J(6);if(null===C||void 0===C)break;r++;g[n+v]=C}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,n,q){for(var r=0;r<q;r++)try{c(g[n+r])}catch(v){throw new J(29);}q&&(f.node.timestamp=Date.now());return r}});
Eb(a,d,e)}var Nb,O={},Bb,Hb,Ob=void 0;function Pb(){Ob+=4;return D[Ob-4>>2]}function Qb(a){a=mb[a];if(!a)throw new J(8);return a}var Rb=0;function Sb(){for(var a=P.length-1;0<=a;--a)Tb(a);P=[];Ub=[]}var Ub=[];function Vb(){if(Rb&&Wb.jc)for(var a=0;a<Ub.length;++a){var b=Ub[a];Ub.splice(a,1);--a;b.od.apply(null,b.ed)}}var P=[];function Tb(a){var b=P[a];b.target.removeEventListener(b.Sb,b.Jc,b.ac);P.splice(a,1)}
function Xb(a){function b(d){++Rb;Wb=a;Vb();a.cc(d);Vb();--Rb}if(a.bc)a.Jc=b,a.target.addEventListener(a.Sb,b,a.ac),P.push(a),Yb||(Ca.push(Sb),Yb=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].Sb==a.Sb&&Tb(c--)}var Zb={},Yb,Wb,$b,ac,bc,cc,dc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Q(a){a=2<a?y(a):a;return dc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function ec(a){return 0>dc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function fc(a,b,c,d,e,f){$b||($b=I(164));a={target:Q(a),jc:!0,Sb:f,bc:d,cc:function(g){var n=$b,q=n>>2;D[q]=g.location;D[q+1]=g.ctrlKey;D[q+2]=g.shiftKey;D[q+3]=g.altKey;D[q+4]=g.metaKey;D[q+5]=g.repeat;D[q+6]=g.charCode;D[q+7]=g.keyCode;D[q+8]=g.which;A(g.key||"",z,n+36,32);A(g.code||"",z,n+68,32);A(g.char||"",z,n+100,32);A(g.locale||"",z,n+132,32);H.get(d)(e,n,b)&&g.preventDefault()},ac:c};Xb(a)}
function hc(a,b,c){a>>=2;D[a]=b.screenX;D[a+1]=b.screenY;D[a+2]=b.clientX;D[a+3]=b.clientY;D[a+4]=b.ctrlKey;D[a+5]=b.shiftKey;D[a+6]=b.altKey;D[a+7]=b.metaKey;xa[2*a+16]=b.button;xa[2*a+17]=b.buttons;D[a+9]=b.movementX;D[a+10]=b.movementY;c=ec(c);D[a+11]=b.clientX-c.left;D[a+12]=b.clientY-c.top}function ic(a,b,c,d,e,f){ac||(ac=I(64));a=Q(a);Xb({target:a,jc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Sb:f,bc:d,cc:function(g){g=g||event;hc(ac,g,a);H.get(d)(e,ac,b)&&g.preventDefault()},ac:c})}
function jc(a,b,c,d){bc||(bc=I(36));a=Q(a);Xb({target:a,Sb:"resize",bc:d,cc:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=bc;D[g>>2]=e.detail;D[g+4>>2]=f.clientWidth;D[g+8>>2]=f.clientHeight;D[g+12>>2]=innerWidth;D[g+16>>2]=innerHeight;D[g+20>>2]=outerWidth;D[g+24>>2]=outerHeight;D[g+28>>2]=pageXOffset;D[g+32>>2]=pageYOffset;H.get(d)(10,g,b)&&e.preventDefault()}}},ac:c})}
function kc(a,b,c,d){cc||(cc=I(96));Xb({target:a,jc:!0,Sb:"wheel",bc:d,cc:function(e){e=e||event;var f=cc;hc(f,e,a);G[f+64>>3]=e.deltaX;G[f+72>>3]=e.deltaY;G[f+80>>3]=e.deltaZ;D[f+88>>2]=e.deltaMode;H.get(d)(9,f,b)&&e.preventDefault()},ac:c})}
function lc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function mc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function nc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var oc=1,pc=[],S=[],qc=[],rc=[],sc=[],T=[],U=[],tc=[],V=[],uc=[],wc=[],xc={},yc={},zc={},Ac=4;function W(a){Bc||(Bc=a)}function Cc(a){for(var b=oc++,c=a.length;c<b;c++)a[c]=null;return b}
function Dc(a){a||(a=X);if(!a.Nc){a.Nc=!0;var b=a.Ub;lc(b);mc(b);nc(b);b.tc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Pc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.uc=b.getExtension("EXT_disjoint_timer_query");!b.uc&&2<=a.version&&(b.uc=b.getExtension("EXT_disjoint_timer_query_webgl2"));b.Ec=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}
var X,Bc,Ec=["default","low-power","high-performance"];h._emscripten_webgl_get_current_context=function(){return X?X.Lc:0};function Fc(a){X=V[a];h.gd=Y=X&&X.Ub;return!a||Y?0:-5}h._emscripten_webgl_make_context_current=Fc;var Gc={};
function Hc(){if(!Ic){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gc)a[b]=Gc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ic=c}return Ic}var Ic,Jc=[];function Kc(a,b,c,d){for(var e=0;e<a;e++){var f=Y[c](),g=f&&Cc(d);f?(f.name=g,d[g]=f):W(1282);D[b+4*e>>2]=g}}
function Lc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&W(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=Y.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>X.version){W(1282);return}d=2*(Y.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>X.version){W(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=Y.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":W(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:W(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:D[b+4*a>>2]=e[a];break;case 2:F[b+4*a>>2]=e[a];break;case 4:B[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){W(1280);
w("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);w("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;E[b>>2]=c;E[b+4>>2]=(c-E[b>>2])/4294967296;break;case 0:D[b>>2]=d;break;case 2:F[b>>2]=d;break;case 4:B[b>>0]=d?1:0}}else W(1281)}function Mc(a){var b=ta(a)+1,c=I(b);A(a,z,c,b);return c}
function Nc(a){a-=5120;return 0==a?B:1==a?z:2==a?xa:4==a?D:6==a?F:5==a||28922==a||28520==a||30779==a||30782==a?E:ya}function Oc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Pc(a,b,c,d,e){a=Nc(a);var f=Oc(a),g=Ac;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Qc=[];function Rc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Sc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Tc=[31,29,31,30,31,30,31,31,30,31,30,31],Uc=[31,28,31,30,31,30,31,31,30,31,30,31];function Vc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Rc(a.getFullYear())?Tc:Uc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Wc(a,b,c,d){function e(k,u,x){for(k="number"===typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function g(k,u){function x(vc){return 0>vc?-1:0<vc?1:0}var K;0===(K=x(k.getFullYear()-u.getFullYear()))&&0===(K=x(k.getMonth()-u.getMonth()))&&(K=x(k.getDate()-u.getDate()));return K}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function q(k){k=Vc(new Date(k.Lb+1900,0,1),k.ic);var u=new Date(k.getFullYear()+1,0,4),x=n(new Date(k.getFullYear(),0,4));u=n(u);return 0>=g(x,k)?0>=g(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var r=D[d+40>>2];d={ad:D[d>>2],$c:D[d+4>>2],fc:D[d+8>>2],$b:D[d+12>>2],Xb:D[d+16>>2],Lb:D[d+20>>2],hc:D[d+24>>2],ic:D[d+28>>2],pd:D[d+32>>2],Zc:D[d+
36>>2],bd:r?y(r):""};c=y(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in r)c=c.replace(new RegExp(v,"g"),r[v]);var C="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
R="January February March April May June July August September October November December".split(" ");r={"%a":function(k){return C[k.hc].substring(0,3)},"%A":function(k){return C[k.hc]},"%b":function(k){return R[k.Xb].substring(0,3)},"%B":function(k){return R[k.Xb]},"%C":function(k){return f((k.Lb+1900)/100|0,2)},"%d":function(k){return f(k.$b,2)},"%e":function(k){return e(k.$b,2," ")},"%g":function(k){return q(k).toString().substring(2)},"%G":function(k){return q(k)},"%H":function(k){return f(k.fc,
2)},"%I":function(k){k=k.fc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.$b+Sc(Rc(k.Lb+1900)?Tc:Uc,k.Xb-1),3)},"%m":function(k){return f(k.Xb+1,2)},"%M":function(k){return f(k.$c,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.fc&&12>k.fc?"AM":"PM"},"%S":function(k){return f(k.ad,2)},"%t":function(){return"\t"},"%u":function(k){return k.hc||7},"%U":function(k){var u=new Date(k.Lb+1900,0,1),x=0===u.getDay()?u:Vc(u,7-u.getDay());k=new Date(k.Lb+1900,k.Xb,k.$b);return 0>
g(x,k)?f(Math.ceil((31-x.getDate()+(Sc(Rc(k.getFullYear())?Tc:Uc,k.getMonth()-1)-31)+k.getDate())/7),2):0===g(x,u)?"01":"00"},"%V":function(k){var u=new Date(k.Lb+1901,0,4),x=n(new Date(k.Lb+1900,0,4));u=n(u);var K=Vc(new Date(k.Lb+1900,0,1),k.ic);return 0>g(K,x)?"53":0>=g(u,K)?"01":f(Math.ceil((x.getFullYear()<k.Lb+1900?k.ic+32-x.getDate():k.ic+1-x.getDate())/7),2)},"%w":function(k){return k.hc},"%W":function(k){var u=new Date(k.Lb,0,1),x=1===u.getDay()?u:Vc(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.Lb+1900,k.Xb,k.$b);return 0>g(x,k)?f(Math.ceil((31-x.getDate()+(Sc(Rc(k.getFullYear())?Tc:Uc,k.getMonth()-1)-31)+k.getDate())/7),2):0===g(x,u)?"01":"00"},"%y":function(k){return(k.Lb+1900).toString().substring(2)},"%Y":function(k){return k.Lb+1900},"%z":function(k){k=k.Zc;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.bd},"%%":function(){return"%"}};for(v in r)0<=c.indexOf(v)&&(c=c.replace(new RegExp(v,"g"),r[v](d)));v=
db(c,!1);if(v.length>b)return 0;B.set(v,a);return v.length-1}var Xc=[];function vb(a,b,c,d){a||(a=this);this.parent=a;this.Pb=a.Pb;this.ec=null;this.id=nb++;this.name=b;this.mode=c;this.Ib={};this.Jb={};this.rdev=d}Object.defineProperties(vb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Jb();ob=Array(4096);Cb(L,"/");N("/tmp");N("/home");
N("/home/web_user");(function(){N("/dev");bb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Eb("/dev/null",259);ab(1280,eb);ab(1536,fb);Eb("/dev/tty",1280);Eb("/dev/tty1",1536);var a=Ya();Mb("random",a);Mb("urandom",a);N("/dev/shm");N("/dev/shm/tmp")})();N("/proc");N("/proc/self");N("/proc/self/fd");
Cb({Pb:function(){var a=hb("/proc/self","fd",16895,73);a.Ib={lookup:function(b,c){var d=mb[+c];if(!d)throw new J(8);b={parent:null,Pb:{Cc:"fake"},Ib:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var Y,Z=0;32>Z;++Z)Jc.push(Array(Z));var Yc=new Float32Array(288);for(Z=0;288>Z;++Z)Qc[Z]=Yc.subarray(0,Z+1);for(Z=0;288>Z;++Z);function db(a,b){var c=Array(ta(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}Aa.push({Kc:function(){Zc()}});
var bd={na:function(a){return I(a+16)+16},ma:function(a,b,c){(new Sa(a)).Mc(b,c);Ta++;throw a;},eb:function(a,b){try{a=y(a);if(b&-8)var c=-28;else{var d;(d=M(a,{mc:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&ub(d,a)?-2:0):c=-44}return c}catch(e){return"undefined"!==typeof O&&e instanceof J||t(e),-e.Mb}},z:function(a,b,c){Ob=c;try{var d=Qb(a);switch(b){case 0:var e=Pb();return 0>e?-28:Gb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Pb(),d.flags|=
e,0;case 12:return e=Pb(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return D[$c()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof O&&f instanceof J||t(f),-f.Mb}},cb:function(a,b,c){Ob=c;try{var d=Qb(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Pb();return D[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Pb();if(!d.Jb.Oc)throw new J(59);
return d.Jb.Oc(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof O&&f instanceof J||t(f),-f.Mb}},db:function(a,b,c){Ob=c;try{var d=y(a),e=Pb();return Gb(d,b,e).fd}catch(f){return"undefined"!==typeof O&&f instanceof J||t(f),-f.Mb}},a:function(){t()},c:function(a,b,c){Xc.length=0;var d;for(c>>=2;d=z[b++];)(d=105>d)&&c&1&&c++,Xc.push(d?G[c++>>1]:D[c]),++c;return Qa[a].apply(null,Xc)},x:function(a,b,c){a=Q(a);if(!a)return-4;
D[b>>2]=a.width;D[c>>2]=a.height},Sa:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},f:function(a,b,c){a=Q(a);if(!a)return-4;a=ec(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},Xa:function(a,b,c){z.copyWithin(a,b,b+c)},Ya:function(){t("OOM")},n:function(a,b,c){a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},Va:function(a,b,c,d){fc(a,b,c,d,2,"keydown");return 0},Ua:function(a,b,c,d){fc(a,b,c,d,3,"keyup");return 0},zb:function(a,b,c,d){ic(a,b,c,d,5,"mousedown");return 0},
gb:function(a,b,c,d){ic(a,b,c,d,8,"mousemove");return 0},qb:function(a,b,c,d){ic(a,b,c,d,6,"mouseup");return 0},K:function(a,b,c,d){jc(a,b,c,d);return 0},_a:function(a,b,c,d){a=Q(a);return"undefined"!==typeof a.onwheel?(kc(a,b,c,d),0):-1},Ta:function(){return X&&X.Ub&&X.attributes.xc?0:-3},ca:function(a,b){b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:Ec[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+
7],Ac:D[b+8],kd:D[b+9],vc:D[b+10],xc:D[b+11],md:D[b+12],nd:D[b+13]};a=Q(a);if(!a||b.xc)b=0;else if(a=1<b.Ac?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=Cc(V),d={Lc:c,attributes:b,version:b.Ac,Ub:a};a.canvas&&(a.canvas.Gc=d);V[c]=d;("undefined"===typeof b.vc||b.vc)&&Dc(d);b=c}else b=0;return b},Ma:function(a){X==a&&(X=0);X===V[a]&&(X=null);if("object"===typeof Zb)for(var b=V[a].Ub.canvas,c=0;c<P.length;++c)P[c].target!=b||Tb(c--);V[a]&&V[a].Ub.canvas&&(V[a].Ub.canvas.Gc=void 0);V[a]=null},
la:function(a){a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},T:Fc,$a:function(a,b){try{var c=0;Hc().forEach(function(d,e){var f=b+c;e=D[a+4*e>>2]=f;for(f=0;f<d.length;++f)B[e++>>0]=d.charCodeAt(f);B[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof O&&d instanceof J||t(d),d.Mb}},ab:function(a,b){try{var c=Hc();D[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});D[b>>2]=d;return 0}catch(e){return"undefined"!==typeof O&&e instanceof J||
t(e),e.Mb}},w:function(a){ad(a)},A:function(a){try{var b=Qb(a);if(null===b.fd)throw new J(8);b.nc&&(b.nc=null);try{b.Jb.close&&b.Jb.close(b)}catch(c){throw c;}finally{mb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof O&&c instanceof J||t(c),c.Mb}},bb:function(a,b,c,d){try{a:{for(var e=Qb(a),f=a=0;f<c;f++){var g=D[b+(8*f+4)>>2],n=e,q=D[b+8*f>>2],r=g,v=void 0,C=B;if(0>r||0>v)throw new J(28);if(null===n.fd)throw new J(8);if(1===(n.flags&2097155))throw new J(8);if(16384===(n.node.mode&
61440))throw new J(31);if(!n.Jb.read)throw new J(28);var R="undefined"!==typeof v;if(!R)v=n.position;else if(!n.seekable)throw new J(70);var k=n.Jb.read(n,C,q,r,v);R||(n.position+=k);var u=k;if(0>u){var x=-1;break a}a+=u;if(u<g)break}x=a}D[d>>2]=x;return 0}catch(K){return"undefined"!==typeof O&&K instanceof J||t(K),K.Mb}},Wa:function(a,b,c,d,e){try{var f=Qb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Ib(f,a,d);Pa=[f.position>>>0,(Oa=f.position,1<=+Math.abs(Oa)?
0<Oa?(Math.min(+Math.floor(Oa/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Oa-+(~~Oa>>>0))/4294967296)>>>0:0)];D[e>>2]=Pa[0];D[e+4>>2]=Pa[1];f.nc&&0===a&&0===d&&(f.nc=null);return 0}catch(g){return"undefined"!==typeof O&&g instanceof J||t(g),g.Mb}},y:function(a,b,c,d){try{a:{for(var e=Qb(a),f=a=0;f<c;f++){var g=e,n=D[b+8*f>>2],q=D[b+(8*f+4)>>2],r=void 0,v=B;if(0>q||0>r)throw new J(28);if(null===g.fd)throw new J(8);if(0===(g.flags&2097155))throw new J(8);if(16384===(g.node.mode&61440))throw new J(31);
if(!g.Jb.write)throw new J(28);g.seekable&&g.flags&1024&&Ib(g,0,2);var C="undefined"!==typeof r;if(!C)r=g.position;else if(!g.seekable)throw new J(70);var R=g.Jb.write(g,v,n,q,r,void 0);C||(g.position+=R);try{if(g.path&&qb.onWriteToFile)qb.onWriteToFile(g.path)}catch(x){w("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+x.message)}var k=R;if(0>k){var u=-1;break a}a+=k}u=a}D[d>>2]=u;return 0}catch(x){return"undefined"!==typeof O&&x instanceof J||t(x),x.Mb}},m:function(a){Y.activeTexture(a)},
R:function(a,b){Y.attachShader(S[a],U[b])},u:function(a,b){35051==a?Y.lc=b:35052==a&&(Y.Qb=b);Y.bindBuffer(a,pc[b])},g:function(a,b,c){Y.bindBufferBase(a,b,pc[c])},t:function(a,b,c,d,e){Y.bindBufferRange(a,b,pc[c],d,e)},b:function(a,b){Y.bindFramebuffer(a,qc[b])},s:function(a,b){Y.bindRenderbuffer(a,rc[b])},p:function(a,b){Y.bindTexture(a,sc[b])},j:function(a,b){Y.bindTransformFeedback(a,wc[b])},l:function(a){Y.bindVertexArray(tc[a])},ia:function(a,b,c,d,e,f,g,n,q,r){Y.blitFramebuffer(a,b,c,d,e,f,
g,n,q,r)},La:function(a,b,c,d){2<=X.version?c?Y.bufferData(a,z,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?z.subarray(c,c+b):b,d)},Ka:function(a,b,c,d){2<=X.version?Y.bufferSubData(a,b,z,d,c):Y.bufferSubData(a,b,z.subarray(d,d+c))},ea:function(a){return Y.checkFramebufferStatus(a)},ha:function(a){Y.clear(a)},$:function(a,b,c,d){Y.clearBufferfi(a,b,c,d)},aa:function(a,b,c){Y.clearBufferfv(a,b,F,c>>2)},da:function(a,b,c){Y.clearBufferiv(a,b,D,c>>2)},ba:function(a,b,c){Y.clearBufferuiv(a,b,E,c>>2)},
ya:function(a,b,c,d){Y.clearColor(a,b,c,d)},xa:function(a){Y.clearDepth(a)},pa:function(a){Y.compileShader(U[a])},B:function(a,b,c,d,e,f,g,n,q){2<=X.version?Y.Qb?Y.compressedTexSubImage2D(a,b,c,d,e,f,g,n,q):Y.compressedTexSubImage2D(a,b,c,d,e,f,g,z,q,n):Y.compressedTexSubImage2D(a,b,c,d,e,f,g,q?z.subarray(q,q+n):null)},sb:function(a,b,c,d,e,f,g,n,q,r,v){Y.Qb?Y.compressedTexSubImage3D(a,b,c,d,e,f,g,n,q,r,v):Y.compressedTexSubImage3D(a,b,c,d,e,f,g,n,q,z,v,r)},Oa:function(a,b,c,d,e){Y.copyBufferSubData(a,
b,c,d,e)},X:function(a,b,c,d,e,f,g,n){Y.copyTexSubImage2D(a,b,c,d,e,f,g,n)},W:function(a,b,c,d,e,f,g,n,q){Y.copyTexSubImage3D(a,b,c,d,e,f,g,n,q)},V:function(){var a=Cc(S),b=Y.createProgram();b.name=a;S[a]=b;return a},sa:function(a){var b=Cc(U);U[b]=Y.createShader(a);return b},Pa:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=pc[d];e&&(Y.deleteBuffer(e),e.name=0,pc[d]=null,d==Y.lc&&(Y.lc=0),d==Y.Qb&&(Y.Qb=0))}},Ia:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],e=qc[d];e&&(Y.deleteFramebuffer(e),
e.name=0,qc[d]=null)}},U:function(a){if(a){var b=S[a];b?(Y.deleteProgram(b),b.name=0,S[a]=null,xc[a]=null):W(1281)}},Da:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=rc[d];e&&(Y.deleteRenderbuffer(e),e.name=0,rc[d]=null)}},ra:function(a){if(a){var b=U[a];b?(Y.deleteShader(b),U[a]=null):W(1281)}},lb:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2];Y.deleteVertexArray(tc[d]);tc[d]=null}},rb:function(a,b,c){Y.drawArrays(a,b,c)},ob:function(a,b,c,d){Y.drawArraysInstanced(a,b,c,d)},wa:function(a,
b,c,d,e){Y.tc.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},_:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=D[b+4*d>>2];Y.drawBuffers(c)},pb:function(a,b,c,d){Y.drawElements(a,b,c,d)},nb:function(a,b,c,d,e){Y.drawElementsInstanced(a,b,c,d,e)},e:function(a,b,c,d,e,f,g){Y.tc.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,f,g)},za:function(a){Y.enable(a)},kb:function(a){Y.enableVertexAttribArray(a)},Ha:function(a,b,c,d){Y.framebufferRenderbuffer(a,b,c,rc[d])},Ga:function(a,b,c,d,e){Y.framebufferTexture2D(a,
b,c,sc[d],e)},Fa:function(a,b,c,d,e){Y.framebufferTextureLayer(a,b,sc[c],d,e)},Qa:function(a,b){Kc(a,b,"createBuffer",pc)},Ja:function(a,b){Kc(a,b,"createFramebuffer",qc)},ta:function(a,b){Kc(a,b,"createQuery",uc)},Ea:function(a,b){Kc(a,b,"createRenderbuffer",rc)},G:function(a,b){Kc(a,b,"createTexture",sc)},ka:function(a,b){Kc(a,b,"createTransformFeedback",wc)},mb:function(a,b){Kc(a,b,"createVertexArray",tc)},F:function(a){Y.generateMipmap(a)},Na:function(a,b,c){c?D[c>>2]=Y.getBufferParameter(a,b):
W(1281)},Ra:function(){var a=Y.getError()||Bc;Bc=0;return a},Aa:function(a,b){Lc(a,b,2)},h:function(a,b){Lc(a,b,0)},S:function(a,b,c,d){a=Y.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,z,d,b):0;c&&(D[c>>2]=b)},q:function(a,b,c){if(c)if(a>=oc)W(1281);else{var d=xc[a];if(d)if(35716==b)a=Y.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b)D[c>>2]=d.oc;else if(35722==b){if(-1==d.Yb){a=S[a];var e=Y.getProgramParameter(a,35721);for(b=d.Yb=
0;b<e;++b)d.Yb=Math.max(d.Yb,Y.getActiveAttrib(a,b).name.length+1)}D[c>>2]=d.Yb}else if(35381==b){if(-1==d.Zb)for(a=S[a],e=Y.getProgramParameter(a,35382),b=d.Zb=0;b<e;++b)d.Zb=Math.max(d.Zb,Y.getActiveUniformBlockName(a,b).length+1);D[c>>2]=d.Zb}else D[c>>2]=Y.getProgramParameter(S[a],b);else W(1282)}else W(1281)},oa:function(a,b,c,d){a=Y.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,z,d,b):0;c&&(D[c>>2]=b)},r:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(U[a]),null===a&&
(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=Y.getShaderSource(U[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=Y.getShaderParameter(U[a],b):W(1281)},i:function(a){if(yc[a])return yc[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Mc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||W(1280);b=Mc(b);break;case 7938:b=Y.getParameter(7938);b=2<=X.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Mc(b);
break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Mc(b);break;default:return W(1280),0}return yc[a]=b},v:function(a,b){if(2>X.version)return W(1282),0;var c=zc[a];if(c)return 0>b||b>=c.length?(W(1281),0):c[b];switch(a){case 7939:return c=Y.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Mc(d)}),c=zc[a]=c,0>b||b>=
c.length?(W(1281),0):c[b];default:return W(1280),0}},O:function(a,b){b=y(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=xc[a]&&xc[a].Fc[b])&&0<=c&&c<a[0]?a[1]+c:-1},ga:function(a,b,c){for(var d=Jc[b],e=0;e<b;e++)d[e]=D[c+4*e>>2];Y.invalidateFramebuffer(a,d)},fa:function(a,b,c,d,e,f,g){for(var n=Jc[b],q=0;q<b;q++)n[q]=D[c+4*q>>2];Y.invalidateSubFramebuffer(a,n,d,e,f,g)},P:function(a){Y.linkProgram(S[a]);var b=S[a];a=xc[a]={Fc:{},
oc:0,Yb:-1,Zb:-1};for(var c=a.Fc,d=Y.getProgramParameter(b,35718),e=0;e<d;++e){var f=Y.getActiveUniform(b,e),g=f.name;a.oc=Math.max(a.oc,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var n=Y.getUniformLocation(b,g);if(n){var q=Cc(T);c[g]=[f.size,q];T[q]=n;for(var r=1;r<f.size;++r)n=Y.getUniformLocation(b,g+"["+r+"]"),q=Cc(T),T[q]=n}}},ua:function(a,b,c,d){Y.Ec.multiDrawArraysWEBGL(a,D,b>>2,D,c>>2,d)},va:function(a,b,c,d,e){Y.Ec.multiDrawElementsWEBGL(a,D,b>>2,c,D,d>>2,e)},fb:function(a,
b,c,d,e,f,g,n){Y.Pc.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,D,b>>2,c,D,d>>2,D,e>>2,D,f>>2,E,g>>2,n)},k:function(a,b){3317==a&&(Ac=b);Y.pixelStorei(a,b)},Z:function(a){Y.readBuffer(a)},Y:function(a,b,c,d,e,f,g){if(2<=X.version)if(Y.lc)Y.readPixels(a,b,c,d,e,f,g);else{var n=Nc(f);Y.readPixels(a,b,c,d,e,f,n,g>>Oc(n))}else(g=Pc(f,e,c,d,g))?Y.readPixels(a,b,c,d,e,f,g):W(1280)},Ca:function(a,b,c,d){Y.renderbufferStorage(a,b,c,d)},Ba:function(a,b,c,d,e){Y.renderbufferStorageMultisample(a,
b,c,d,e)},qa:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?D[d+4*f>>2]:-1;e+=y(D[c+4*f>>2],0>g?void 0:g)}Y.shaderSource(U[a],e)},vb:function(a,b,c,d,e,f,g,n,q){if(2<=X.version)if(Y.Qb)Y.texImage2D(a,b,c,d,e,f,g,n,q);else if(q){var r=Nc(n);Y.texImage2D(a,b,c,d,e,f,g,n,r,q>>Oc(r))}else Y.texImage2D(a,b,c,d,e,f,g,n,null);else Y.texImage2D(a,b,c,d,e,f,g,n,q?Pc(n,g,d,e,q):null)},ub:function(a,b,c,d,e,f,g,n,q,r){if(Y.Qb)Y.texImage3D(a,b,c,d,e,f,g,n,q,r);else if(r){var v=Nc(q);Y.texImage3D(a,b,c,d,
e,f,g,n,q,v,r>>Oc(v))}else Y.texImage3D(a,b,c,d,e,f,g,n,q,null)},D:function(a,b,c){Y.texParameterf(a,b,c)},yb:function(a,b,c){Y.texParameterf(a,b,F[c>>2])},E:function(a,b,c){Y.texParameteri(a,b,c)},C:function(a,b,c){Y.texParameteri(a,b,D[c>>2])},xb:function(a,b,c,d,e){Y.texStorage2D(a,b,c,d,e)},wb:function(a,b,c,d,e,f){Y.texStorage3D(a,b,c,d,e,f)},o:function(a,b,c,d,e,f,g,n,q){if(2<=X.version)if(Y.Qb)Y.texSubImage2D(a,b,c,d,e,f,g,n,q);else if(q){var r=Nc(n);Y.texSubImage2D(a,b,c,d,e,f,g,n,r,q>>Oc(r))}else Y.texSubImage2D(a,
b,c,d,e,f,g,n,null);else r=null,q&&(r=Pc(n,g,e,f,q)),Y.texSubImage2D(a,b,c,d,e,f,g,n,r)},tb:function(a,b,c,d,e,f,g,n,q,r,v){if(Y.Qb)Y.texSubImage3D(a,b,c,d,e,f,g,n,q,r,v);else if(v){var C=Nc(r);Y.texSubImage3D(a,b,c,d,e,f,g,n,q,r,C,v>>Oc(C))}else Y.texSubImage3D(a,b,c,d,e,f,g,n,q,r,null)},Q:function(a,b,c,d){a=S[a];for(var e=[],f=0;f<b;f++)e.push(y(D[c+4*f>>2]));Y.transformFeedbackVaryings(a,e,d)},N:function(a,b,c){if(2<=X.version)Y.uniform1fv(T[a],F,c>>2,b);else{if(288>=b)for(var d=Qc[b-1],e=0;e<
b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);Y.uniform1fv(T[a],d)}},J:function(a,b,c){Y.uniform1uiv(T[a],E,c>>2,b)},M:function(a,b,c){if(2<=X.version)Y.uniform3fv(T[a],F,c>>2,3*b);else{if(96>=b)for(var d=Qc[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);Y.uniform3fv(T[a],d)}},L:function(a,b,c){if(2<=X.version)Y.uniform4fv(T[a],F,c>>2,4*b);else{if(72>=b){var d=Qc[4*b-1],e=F;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=
e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=F.subarray(c>>2,c+16*b>>2);Y.uniform4fv(T[a],d)}},I:function(a,b,c,d){if(2<=X.version)Y.uniformMatrix3fv(T[a],!!c,F,d>>2,9*b);else{if(32>=b)for(var e=Qc[9*b-1],f=0;f<9*b;f+=9)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);Y.uniformMatrix3fv(T[a],!!c,e)}},
H:function(a,b,c,d){if(2<=X.version)Y.uniformMatrix4fv(T[a],!!c,F,d>>2,16*b);else{if(18>=b){var e=Qc[16*b-1],f=F;d>>=2;for(var g=0;g<16*b;g+=16){var n=d+g;e[g]=f[n];e[g+1]=f[n+1];e[g+2]=f[n+2];e[g+3]=f[n+3];e[g+4]=f[n+4];e[g+5]=f[n+5];e[g+6]=f[n+6];e[g+7]=f[n+7];e[g+8]=f[n+8];e[g+9]=f[n+9];e[g+10]=f[n+10];e[g+11]=f[n+11];e[g+12]=f[n+12];e[g+13]=f[n+13];e[g+14]=f[n+14];e[g+15]=f[n+15]}}else e=F.subarray(d>>2,d+64*b>>2);Y.uniformMatrix4fv(T[a],!!c,e)}},d:function(a){Y.useProgram(S[a])},hb:function(a,
b){Y.vertexAttribDivisor(a,b)},jb:function(a,b,c,d,e){Y.vertexAttribIPointer(a,b,c,d,e)},ib:function(a,b,c,d,e,f){Y.vertexAttribPointer(a,b,c,!!d,e,f)},ja:function(a,b,c,d){Y.viewport(a,b,c,d)},Za:function(a,b,c,d){return Wc(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;pa=h.asm.Ab;wa=e=pa.buffer;h.HEAP8=B=new Int8Array(e);h.HEAP16=xa=new Int16Array(e);h.HEAP32=D=new Int32Array(e);h.HEAPU8=z=new Uint8Array(e);h.HEAPU16=ya=new Uint16Array(e);h.HEAPU32=E=new Uint32Array(e);h.HEAPF32=F=new Float32Array(e);h.HEAPF64=G=new Float64Array(e);H=h.asm.Bb;Fa--;h.monitorRunDependencies&&h.monitorRunDependencies(Fa);0==Fa&&(null!==Ga&&(clearInterval(Ga),Ga=null),Ha&&(e=Ha,Ha=null,e()))}function b(e){a(e.instance)}function c(e){return Na().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){w("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:bd};Fa++;h.monitorRunDependencies&&h.monitorRunDependencies(Fa);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return w("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return oa||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||Ia("file://")||"function"!==typeof fetch?c(b):fetch(Ja,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){w("wasm streaming compile failed: "+f);w("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Zc=h.___wasm_call_ctors=function(){return(Zc=h.___wasm_call_ctors=h.asm.Cb).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Db).apply(null,arguments)};
var I=h._malloc=function(){return(I=h._malloc=h.asm.Eb).apply(null,arguments)},$c=h.___errno_location=function(){return($c=h.___errno_location=h.asm.Fb).apply(null,arguments)},va=h.stackAlloc=function(){return(va=h.stackAlloc=h.asm.Gb).apply(null,arguments)},cd;function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ha=function dd(){cd||ed();cd||(Ha=dd)};
function ed(a){function b(){if(!cd&&(cd=!0,h.calledRun=!0,!qa)){h.noFSInit||Kb||(Kb=!0,Jb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Mb("stdin",h.stdin):Fb("/dev/tty","/dev/stdin"),h.stdout?Mb("stdout",null,h.stdout):Fb("/dev/tty","/dev/stdout"),h.stderr?Mb("stderr",null,h.stderr):Fb("/dev/tty1","/dev/stderr"),Gb("/dev/stdin",0),Gb("/dev/stdout",1),Gb("/dev/stderr",1));Ra(Aa);pb=!1;Ra(Ba);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(fd){var c=a,d=h._main;c=c||[];var e=
c.length+1,f=va(4*(e+1));D[f>>2]=ua(ca);for(var g=1;g<e;g++)D[(f>>2)+g]=ua(c[g-1]);D[(f>>2)+e]=0;try{var n=d(e,f);ad(n,!0)}catch(q){q instanceof ma||("unwind"==q?noExitRuntime=!0:((c=q)&&"object"===typeof q&&q.stack&&(c=[q,q.stack]),w("exception thrown: "+c),da(1,q)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Da.unshift(c);Ra(Da)}}a=a||ba;if(!(0<Fa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ea();
Ra(za);0<Fa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=ed;function ad(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);qa=!0}da(a,new ma(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var fd=!0;h.noInitialRun&&(fd=!1);noExitRuntime=!0;ed();
