var g,h;var k,m,n,p;var r;r||(r=typeof Module !== 'undefined' ? Module : {});var aa={},u;for(u in r)r.hasOwnProperty(u)&&(aa[u]=r[u]);r.arguments=[];r.thisProgram="./this.program";r.quit=function(a,b){throw b;};r.preRun=[];r.postRun=[];var ba=!1,w=!1,x=!1,ca=!1;ba="object"===typeof window;w="function"===typeof importScripts;x="object"===typeof process&&"function"===typeof require&&!ba&&!w;ca=!ba&&!x&&!w;var z="";
if(x){z=__dirname+"/";var da,ea;r.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};r.readBinary=function(a){a=r.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(r.thisProgram=process.argv[1].replace(/\\/g,"/"));r.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=r);process.on("uncaughtException",function(a){if(!(a instanceof A))throw a;});process.on("unhandledRejection",
C);r.quit=function(a){process.exit(a)};r.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(r.read=function(a){return read(a)}),r.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r.arguments=scriptArgs:"undefined"!=typeof arguments&&(r.arguments=arguments),"function"===typeof quit&&(r.quit=function(a){quit(a)});else if(ba||w)w?
z=self.location.href:document.currentScript&&(z=document.currentScript.src),z=0!==z.indexOf("blob:")?z.substr(0,z.lastIndexOf("/")+1):"",r.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},w&&(r.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),r.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},r.setWindowTitle=function(a){document.title=a};var fa=r.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),D=r.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(u in aa)aa.hasOwnProperty(u)&&(r[u]=aa[u]);aa=void 0;function ha(a){var b=E[ia>>2];a=b+a+15&-16;if(a<=ja())E[ia>>2]=a;else return 0;return b}
function ka(a){la||(la={});la[a]||(la[a]=1,D(a))}var la,ma={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&D("no native wasm support detected");var na,F=!1;function assert(a,b){a||C("Assertion failed: "+b)}
function oa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=G(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)E[a>>2]=0;for(b=d+c;a<b;)I[a++>>0]=0;return d}a.subarray||a.slice?J.set(a,d):J.set(new Uint8Array(a),d);return d}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function M(a,b){return a?qa(J,a,b):""}
function ra(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var q=a.charCodeAt(++f);l=65536+((l&1023)<<10)|q&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ta(a){var b=sa(a)+1,c=ua(b);ra(a,I,c,b);return c}var buffer,I,J,va,wa,E,N,O,xa,ia=47712,ya=r.TOTAL_MEMORY||16777216;5242880>ya&&D("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+ya+"! (TOTAL_STACK=5242880)");
r.buffer?buffer=r.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(na=new WebAssembly.Memory({initial:ya/65536,maximum:ya/65536}),buffer=na.buffer):buffer=new ArrayBuffer(ya);r.HEAP8=I=new Int8Array(buffer);r.HEAP16=va=new Int16Array(buffer);r.HEAP32=E=new Int32Array(buffer);r.HEAPU8=J=new Uint8Array(buffer);r.HEAPU16=wa=new Uint16Array(buffer);r.HEAPU32=N=new Uint32Array(buffer);r.HEAPF32=O=new Float32Array(buffer);r.HEAPF64=xa=new Float64Array(buffer);E[ia>>2]=5290848;
function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Ac;"number"===typeof c?void 0===b.Yc?r.dynCall_v(c):r.dynCall_vi(c,b.Yc):c(void 0===b.Yc?null:b.Yc)}}}var Aa=[],Ba=[],Ca=[],Da=[],Ea=!1;
function Fa(){Ea||(Ea=!0,r.noFSInit||Ga||(Ga=!0,Ha(),r.stdin=r.stdin,r.stdout=r.stdout,r.stderr=r.stderr,r.stdin?Ia("stdin",r.stdin):Ja("/dev/tty","/dev/stdin"),r.stdout?Ia("stdout",null,r.stdout):Ja("/dev/tty","/dev/stdout"),r.stderr?Ia("stderr",null,r.stderr):Ja("/dev/tty1","/dev/stderr"),Ka("/dev/stdin","r"),Ka("/dev/stdout","w"),Ka("/dev/stderr","w")),za(Ba))}function La(){var a=r.preRun.shift();Aa.unshift(a)}var Ma=Math.abs,Na=Math.ceil,Oa=Math.floor,Pa=Math.min,Qa=0,Ra=null,Sa=null;
function Ta(){Qa++;r.monitorRunDependencies&&r.monitorRunDependencies(Qa)}function Ua(){Qa--;r.monitorRunDependencies&&r.monitorRunDependencies(Qa);if(0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}r.preloadedImages={};r.preloadedAudios={};function Va(){var a=Wa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Wa="magnum-picking.wasm";
if(!Va()){var Xa=Wa;Wa=r.locateFile?r.locateFile(Xa,z):z+Xa}function Ya(){try{if(r.wasmBinary)return new Uint8Array(r.wasmBinary);if(r.readBinary)return r.readBinary(Wa);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}
function Za(){return r.wasmBinary||!ba&&!w||"function"!==typeof fetch?new Promise(function(a){a(Ya())}):fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Ya()})}
function $a(a){function b(a){r.asm=a.exports;Ua()}function c(a){b(a.instance)}function d(a){Za().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){D("failed to asynchronously prepare wasm: "+a);C(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ma};Ta();if(r.instantiateWasm)try{return r.instantiateWasm(e,b)}catch(f){return D("Module.instantiateWasm callback failed with error: "+f),!1}r.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Va()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(Wa,{credentials:"same-origin"}),e).then(c,function(a){D("wasm streaming compile failed: "+a);D("falling back to ArrayBuffer instantiation");d(c)});return{}}r.asm=function(a,b){b.memory=na;b.table=new WebAssembly.Table({initial:874,maximum:874,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return $a(b)};var bb=[function(a){a=M(a);return"undefined"!==typeof process&&a in process.env?oa(ab(process.env[a])):0}];
Ba.push({Ac:function(){cb()}},{Ac:function(){db()}},{Ac:function(){eb()}},{Ac:function(){fb()}});function gb(a){r.___errno_location&&(E[r.___errno_location()>>2]=a);return a}function hb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function ib(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=hb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function jb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function kb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function lb(){var a=Array.prototype.slice.call(arguments,0);return ib(a.join("/"))}function mb(a,b){return ib(a+"/"+b)}function nb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=hb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ob=[];function pb(a,b){ob[a]={input:[],output:[],kd:b};qb(a,rb)}
var rb={open:function(a){var b=ob[a.node.rdev];if(!b)throw new P(R.$d);a.tty=b;a.seekable=!1},close:function(a){a.tty.kd.flush(a.tty)},flush:function(a){a.tty.kd.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.kd.Qe)throw new P(R.ve);for(var e=0,f=0;f<d;f++){try{var l=a.tty.kd.Qe(a.tty)}catch(q){throw new P(R.te);}if(void 0===l&&0===e)throw new P(R.rf);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.kd.oe)throw new P(R.ve);
try{for(var e=0;e<d;e++)a.tty.kd.oe(a.tty,b[c+e])}catch(f){throw new P(R.te);}d&&(a.node.timestamp=Date.now());return e}},sb={Qe:function(a){if(!a.input.length){var b=null;if(x){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ab(b,!0)}return a.input.shift()},oe:function(a,b){null===b||10===b?(fa(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(fa(qa(a.output,0)),a.output=[])}},tb={oe:function(a,b){null===b||10===b?(D(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(D(qa(a.output,0)),a.output=[])}},S={Ic:null,Cc:function(){return S.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(R.vf);S.Ic||(S.Ic={dir:{node:{Nc:S.qc.Nc,Fc:S.qc.Fc,lookup:S.qc.lookup,Ad:S.qc.Ad,rename:S.qc.rename,unlink:S.qc.unlink,rmdir:S.qc.rmdir,readdir:S.qc.readdir,symlink:S.qc.symlink},stream:{Sc:S.pc.Sc}},file:{node:{Nc:S.qc.Nc,Fc:S.qc.Fc},stream:{Sc:S.pc.Sc,read:S.pc.read,write:S.pc.write,we:S.pc.we,Xe:S.pc.Xe,
Qd:S.pc.Qd}},link:{node:{Nc:S.qc.Nc,Fc:S.qc.Fc,readlink:S.qc.readlink},stream:{}},Ae:{node:{Nc:S.qc.Nc,Fc:S.qc.Fc},stream:ub}});c=vb(a,b,c,d);16384===(c.mode&61440)?(c.qc=S.Ic.dir.node,c.pc=S.Ic.dir.stream,c.nc={}):32768===(c.mode&61440)?(c.qc=S.Ic.file.node,c.pc=S.Ic.file.stream,c.uc=0,c.nc=null):40960===(c.mode&61440)?(c.qc=S.Ic.link.node,c.pc=S.Ic.link.stream):8192===(c.mode&61440)&&(c.qc=S.Ic.Ae.node,c.pc=S.Ic.Ae.stream);c.timestamp=Date.now();a&&(a.nc[b]=c);return c},ij:function(a){if(a.nc&&
a.nc.subarray){for(var b=[],c=0;c<a.uc;++c)b.push(a.nc[c]);return b}return a.nc},jj:function(a){return a.nc?a.nc.subarray?a.nc.subarray(0,a.uc):new Uint8Array(a.nc):new Uint8Array},Ie:function(a,b){var c=a.nc?a.nc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.nc,a.nc=new Uint8Array(b),0<a.uc&&a.nc.set(c.subarray(0,a.uc),0))},qg:function(a,b){if(a.uc!=b)if(0==b)a.nc=null,a.uc=0;else{if(!a.nc||a.nc.subarray){var c=a.nc;a.nc=new Uint8Array(new ArrayBuffer(b));c&&
a.nc.set(c.subarray(0,Math.min(b,a.uc)))}else if(a.nc||(a.nc=[]),a.nc.length>b)a.nc.length=b;else for(;a.nc.length<b;)a.nc.push(0);a.uc=b}},qc:{Nc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.uc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Zc=4096;b.blocks=Math.ceil(b.size/
b.Zc);return b},Fc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&S.qg(a,b.size)},lookup:function(){throw wb[R.tf];},Ad:function(a,b,c,d){return S.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=xb(b,c)}catch(f){}if(d)for(var e in d.nc)throw new P(R.ue);}delete a.parent.nc[a.name];a.name=c;b.nc[c]=a;a.parent=b},unlink:function(a,b){delete a.nc[b]},rmdir:function(a,b){var c=xb(a,b),d;for(d in c.nc)throw new P(R.ue);
delete a.nc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.nc)a.nc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new P(R.Ec);return a.link}},pc:{read:function(a,b,c,d,e){var f=a.node.nc;if(e>=a.node.uc)return 0;a=Math.min(a.node.uc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.nc||a.nc.subarray)){if(f)return a.nc=b.subarray(c,c+d),a.uc=d;if(0===a.uc&&0===e)return a.nc=new Uint8Array(b.subarray(c,c+d)),a.uc=d;if(e+d<=a.uc)return a.nc.set(b.subarray(c,c+d),e),d}S.Ie(a,e+d);if(a.nc.subarray&&b.subarray)a.nc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.nc[e+f]=b[c+f];a.uc=Math.max(a.uc,e+d);return d},Sc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.uc);if(0>b)throw new P(R.Ec);return b},we:function(a,
b,c){S.Ie(a.node,b+c);a.node.uc=Math.max(a.node.uc,b+c)},Xe:function(a,b,c,d,e,f,l){if(32768!==(a.node.mode&61440))throw new P(R.$d);c=a.node.nc;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.uc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=G(d);if(!d)throw new P(R.uf);b.set(c,d)}else a=!1,d=c.byteOffset;return{Aj:d,zf:a}},Qd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(R.$d);if(e&2)return 0;S.pc.write(a,b,0,d,c,!1);return 0}}},T={Ld:!1,
yg:function(){T.Ld=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);T.Ke={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},xe:function(a){return Buffer.Bc?Buffer.from(a):new Buffer(a)},Cc:function(a){assert(x);return T.createNode(null,"/",T.Pe(a.ne.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new P(R.Ec);a=vb(a,b,c);a.qc=T.qc;a.pc=T.pc;return a},Pe:function(a){try{var b=
fs.lstatSync(a);T.Ld&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new P(R[c.code]);}return b.mode},Dc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Cc.ne.root);b.reverse();return lb.apply(null,b)},Hf:function(a){a&=-2656257;var b=0,c;for(c in T.Ke)a&c&&(b|=T.Ke[c],a^=c);if(a)throw new P(R.Ec);return b},qc:{Nc:function(a){a=T.Dc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new P(R[c.code]);}T.Ld&&!b.Zc&&(b.Zc=4096);T.Ld&&!b.blocks&&
(b.blocks=(b.size+b.Zc-1)/b.Zc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Zc:b.Zc,blocks:b.blocks}},Fc:function(a,b){var c=T.Dc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new P(R[d.code]);}},lookup:function(a,b){var c=mb(T.Dc(a),b);c=T.Pe(c);return T.createNode(a,b,c)},Ad:function(a,b,c,d){a=T.createNode(a,
b,c,d);b=T.Dc(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new P(R[e.code]);}return a},rename:function(a,b,c){a=T.Dc(a);b=mb(T.Dc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new P(R[d.code]);}},unlink:function(a,b){a=mb(T.Dc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new P(R[c.code]);}},rmdir:function(a,b){a=mb(T.Dc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new P(R[c.code]);
}},readdir:function(a){a=T.Dc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new P(R[b.code]);}},symlink:function(a,b,c){a=mb(T.Dc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new P(R[d.code]);}},readlink:function(a){var b=T.Dc(a);try{return b=fs.readlinkSync(b),b=yb.relative(yb.resolve(a.Cc.ne.root),b)}catch(c){if(!c.code)throw c;throw new P(R[c.code]);}}},pc:{open:function(a){var b=T.Dc(a.node);try{32768===(a.node.mode&61440)&&(a.Bd=fs.openSync(b,T.Hf(a.flags)))}catch(c){if(!c.code)throw c;
throw new P(R[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Bd&&fs.closeSync(a.Bd)}catch(b){if(!b.code)throw b;throw new P(R[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Bd,T.xe(b.buffer),c,d,e)}catch(f){throw new P(R[f.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Bd,T.xe(b.buffer),c,d,e)}catch(f){throw new P(R[f.code]);}},Sc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Bd).size}catch(d){throw new P(R[d.code]);
}if(0>b)throw new P(R.Ec);return b}}},zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,Fb={},P=null,wb={};
function U(a,b){a=nb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Le:!0,pe:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.pe)throw new P(40);a=hb(a.split("/").filter(function(a){return!!a}),!1);var e=zb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=xb(e,a[d]);c=mb(c,a[d]);e.Pd&&(!f||f&&b.Le)&&(e=e.Pd.root);if(!f||b.ee)for(f=0;40960===(e.mode&61440);)if(e=Gb(c),c=nb(jb(c),e),e=U(c,{pe:b.pe}).node,40<f++)throw new P(40);}return{path:c,node:e}}
function Hb(a){for(var b;;){if(a===a.parent)return a=a.Cc.Ze,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ib(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function Jb(a){var b=Ib(a.parent.id,a.name);a.gg=Db[b];Db[b]=a}function xb(a,b){var c;if(c=(c=Kb(a,"x"))?c:a.qc.lookup?0:13)throw new P(c,a);for(c=Db[Ib(a.id,b)];c;c=c.gg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.qc.lookup(a,b)}
function vb(a,b,c,d){Lb||(Lb=function(a,b,c,d){a||(a=this);this.parent=a;this.Cc=a.Cc;this.Pd=null;this.id=Cb++;this.name=b;this.mode=c;this.qc={};this.pc={};this.rdev=d},Lb.prototype={},Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Lb(a,b,c,d);Jb(a);return a}
var Mb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Kb(a,b){if(Eb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Ob(a,b){try{return xb(a,b),17}catch(c){}return Kb(a,"wx")}
function Pb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Bb[a])return a;throw new P(24);}function Qb(a,b){Rb||(Rb=function(){},Rb.prototype={},Object.defineProperties(Rb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Rb,d;for(d in a)c[d]=a[d];a=c;b=Pb(b);a.fd=b;return Bb[b]=a}var ub={open:function(a){a.pc=Ab[a.node.rdev].pc;a.pc.open&&a.pc.open(a)},Sc:function(){throw new P(29);}};function qb(a,b){Ab[a]={pc:b}}
function Sb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new P(16);if(!c&&!d){var e=U(b,{Le:!1});b=e.path;e=e.node;if(e.Pd)throw new P(16);if(16384!==(e.mode&61440))throw new P(20);}b={type:a,ne:{},Ze:b,fg:[]};a=a.Cc(b);a.Cc=b;b.root=a;c?zb=a:e&&(e.Pd=b,e.Cc&&e.Cc.fg.push(b))}function Tb(a,b,c){var d=U(a,{parent:!0}).node;a=kb(a);if(!a||"."===a||".."===a)throw new P(22);var e=Ob(d,a);if(e)throw new P(e);if(!d.qc.Ad)throw new P(1);return d.qc.Ad(d,a,b,c)}function V(a){Tb(a,16895,0)}
function Ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);Tb(a,b|8192,c)}function Ja(a,b){if(!nb(a))throw new P(2);var c=U(b,{parent:!0}).node;if(!c)throw new P(2);b=kb(b);var d=Ob(c,b);if(d)throw new P(d);if(!c.qc.symlink)throw new P(1);c.qc.symlink(c,b,a)}function Gb(a){a=U(a).node;if(!a)throw new P(2);if(!a.qc.readlink)throw new P(22);return nb(Hb(a.parent),a.qc.readlink(a))}
function Ka(a,b,c,d){if(""===a)throw new P(2);if("string"===typeof b){var e=Mb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=ib(a);try{f=U(a,{ee:!(b&131072)}).node}catch(q){}}e=!1;if(b&64)if(f){if(b&128)throw new P(17);}else f=Tb(a,c,0),e=!0;if(!f)throw new P(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new P(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Nb(b)||b&512)?21:Kb(f,Nb(b)):2))throw new P(c);if(b&512){c=f;var l;"string"===typeof c?l=U(c,{ee:!0}).node:l=c;if(!l.qc.Fc)throw new P(1);if(16384===(l.mode&61440))throw new P(21);if(32768!==(l.mode&61440))throw new P(22);if(c=Kb(l,"w"))throw new P(c);l.qc.Fc(l,{size:0,timestamp:Date.now()})}b&=-641;d=Qb({node:f,path:Hb(f),flags:b,seekable:!0,position:0,pc:f.pc,Fg:[],error:!1},d);d.pc.open&&d.pc.open(d);!r.logReadFiles||b&1||(Vb||(Vb={}),a in Vb||(Vb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Fb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Fb.onOpenFile(a,f))}catch(q){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+q.message)}return d}function Wb(a,b,c){if(null===a.fd)throw new P(9);if(!a.seekable||!a.pc.Sc)throw new P(29);if(0!=c&&1!=c&&2!=c)throw new P(22);a.position=a.pc.Sc(a,b,c);a.Fg=[]}
function Ha(){P||(P=function(a,b){this.node=b;this.vg=function(a){this.Mc=a};this.vg(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},P.prototype=Error(),P.prototype.constructor=P,[2].forEach(function(a){wb[a]=new P(a);wb[a].stack="<generic error, no stack>"}))}var Ga;function Xb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ia(a,b,c){a=mb("/dev",a);var d=Xb(!!b,!!c);Yb||(Yb=64);var e=Yb++<<8|0;qb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,l=0;l<e;l++){try{var q=b()}catch(B){throw new P(5);}if(void 0===q&&0===f)throw new P(11);if(null===q||void 0===q)break;f++;c[d+l]=q}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(y){throw new P(5);}e&&(a.node.timestamp=Date.now());return f}});
Ub(a,d,e)}var Yb,W={},Lb,Rb,Vb;
function Zb(a,b){k.lc.Vd=a;k.lc.Wd=b;if(k.lc.Ac)if(0==a)k.lc.Wc=function(){var a=Math.max(0,k.lc.Ag+b-$b())|0;setTimeout(k.lc.md,a)},k.lc.method="timeout";else if(1==a)k.lc.Wc=function(){k.requestAnimationFrame(k.lc.md)},k.lc.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);w?(void 0===r.setImmediates&&(r.setImmediates=
[]),r.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}k.lc.Wc=function(){setImmediate(k.lc.md)};k.lc.method="immediate"}}function $b(){C()}
function ac(a,b,c,d,e){r.noExitRuntime=!0;assert(!k.lc.Ac,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");k.lc.Ac=a;k.lc.Yc=d;var f="undefined"!==typeof d?function(){r.dynCall_vi(a,d)}:function(){r.dynCall_v(a)};var l=k.lc.ed;k.lc.md=function(){if(!F)if(0<k.lc.df.length){var a=Date.now(),b=k.lc.df.shift();b.Ac(b.Yc);if(k.lc.qe){var c=k.lc.qe,d=0==c%1?c-1:Math.floor(c);
k.lc.qe=b.Zi?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");k.lc.Hg();l<k.lc.ed||setTimeout(k.lc.md,0)}else l<k.lc.ed||(k.lc.ce=k.lc.ce+1|0,1==k.lc.Vd&&1<k.lc.Wd&&0!=k.lc.ce%k.lc.Wd?k.lc.Wc():(0==k.lc.Vd&&(k.lc.Ag=$b()),"timeout"===k.lc.method&&r.zc&&(D("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
k.lc.method=""),k.lc.sg(f),l<k.lc.ed||("object"===typeof m&&m.audio&&m.audio.ng&&m.audio.ng(),k.lc.Wc())))};e||(b&&0<b?Zb(0,1E3/b):Zb(1,1),k.lc.Wc());if(c)throw"SimulateInfiniteLoop";}
k={lc:{Wc:null,method:"",ed:0,Ac:null,Yc:0,Vd:0,Wd:0,ce:0,df:[],pause:function(){k.lc.Wc=null;k.lc.ed++},resume:function(){k.lc.ed++;var a=k.lc.Vd,b=k.lc.Wd,c=k.lc.Ac;k.lc.Ac=null;ac(c,0,!1,k.lc.Yc,!0);Zb(a,b);k.lc.Wc()},Hg:function(){if(r.setStatus){var a=r.statusMessage||"Please wait...",b=k.lc.qe,c=k.lc.gj;b?b<c?r.setStatus(a+" ("+(c-b)+"/"+c+")"):r.setStatus(a):r.setStatus("")}},sg:function(a){if(!(F||r.preMainLoop&&!1===r.preMainLoop())){try{a()}catch(b){if(b instanceof A)return;b&&"object"===
typeof b&&b.stack&&D("exception thrown: "+[b,b.stack]);throw b;}r.postMainLoop&&r.postMainLoop()}}},wd:!1,Sd:!1,eg:[],workers:[],he:function(){function a(){k.Sd=document.pointerLockElement===r.canvas||document.mozPointerLockElement===r.canvas||document.webkitPointerLockElement===r.canvas||document.msPointerLockElement===r.canvas}r.preloadPlugins||(r.preloadPlugins=[]);if(!k.Sf){k.Sf=!0;try{k.Kd=!0}catch(c){k.Kd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}k.BlobBuilder=
"undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:k.Kd?null:console.log("warning: no BlobBuilder");k.Hd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;r.af||"undefined"!==typeof k.Hd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),r.af=!0);r.preloadPlugins.push({canHandle:function(a){return!r.af&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,
b,e,f){var c=null;if(k.Kd)try{c=new Blob([a],{type:k.fe(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:k.fe(b)}))}catch(v){ka("Blob constructor present but fails: "+v+"; falling back to blob builder")}c||(c=new k.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=k.Hd.createObjectURL(c),t=new Image;t.onload=function(){assert(t.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=t.width;c.height=t.height;c.getContext("2d").drawImage(t,
0,0);r.preloadedImages[b]=c;k.Hd.revokeObjectURL(d);e&&e(a)};t.onerror=function(){console.log("Image "+d+" could not be decoded");f&&f()};t.src=d}});r.preloadPlugins.push({canHandle:function(a){return!r.wj&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,f){function c(c){t||(t=!0,r.preloadedAudios[b]=c,e&&e(a))}function d(){t||(t=!0,r.preloadedAudios[b]=new Audio,f&&f())}var t=!1;if(k.Kd){try{var v=new Blob([a],{type:k.fe(b)})}catch(K){return d()}v=k.Hd.createObjectURL(v);var y=
new Audio;y.addEventListener("canplaythrough",function(){c(y)},!1);y.onerror=function(){if(!t){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,l=0;l<a.length;l++)for(e=e<<8|a[l],f+=8;6<=f;){var q=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[q]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");y.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(y)}};y.src=v;k.tg(function(){c(y)},1E4)}else return d()}});var b=r.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),r.elementPointerLock&&b.addEventListener("click",function(a){!k.Sd&&r.canvas.requestPointerLock&&(r.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&r.zc&&a==r.canvas)return r.zc;var e;if(b){var f={antialias:!1,alpha:!1,Ve:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var l in d)f[l]=
d[l];if("undefined"!==typeof n&&(e=n.createContext(a,f)))var q=n.getContext(e).cd}else q=a.getContext("2d");if(!q)return null;c&&(b||assert("undefined"===typeof p,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),r.zc=q,b&&n.bg(e),r.Tj=b,k.eg.forEach(function(a){a()}),k.he());return q},bj:function(){},Ne:!1,Od:void 0,ld:void 0,requestFullscreen:function(a,b,c){function d(){k.wd=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||
document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=k.exitFullscreen,k.Od&&e.requestPointerLock(),k.wd=!0,k.ld?k.wg():k.Fd(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),k.ld?k.xg():k.Fd(e));if(r.onFullScreen)r.onFullScreen(k.wd);if(r.onFullscreen)r.onFullscreen(k.wd)}k.Od=a;k.ld=b;k.pf=c;"undefined"===typeof k.Od&&(k.Od=!0);"undefined"===typeof k.ld&&(k.ld=!1);"undefined"===typeof k.pf&&(k.pf=null);var e=
r.canvas;k.Ne||(k.Ne=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:
null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?f.requestFullscreen({Uj:c}):f.requestFullscreen()},ef:function(a,b,c){D("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");k.ef=function(a,b,c){return k.requestFullscreen(a,b,c)};return k.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!k.wd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||
document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},jd:0,Je:function(a){var b=Date.now();if(0===k.jd)k.jd=b+1E3/60;else for(;b+2>=k.jd;)k.jd+=1E3/60;setTimeout(a,Math.max(k.jd-b,0))},requestAnimationFrame:function(a){"undefined"===typeof window?k.Je(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||k.Je),
window.requestAnimationFrame(a))},Dj:function(a){return function(){if(!F)return a.apply(null,arguments)}},qd:!0,Dd:[],yj:function(){k.qd=!1},Bj:function(){k.qd=!0;if(0<k.Dd.length){var a=k.Dd;k.Dd=[];a.forEach(function(a){a()})}},Ej:function(a){return k.requestAnimationFrame(function(){F||(k.qd?a():k.Dd.push(a))})},tg:function(a,b){r.noExitRuntime=!0;return setTimeout(function(){F||(k.qd?a():k.Dd.push(a))},b)},Fj:function(a,b){r.noExitRuntime=!0;return setInterval(function(){F||k.qd&&a()},b)},fe:function(a){return{jpg:"image/jpeg",
jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Lf:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},Mf:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Kf:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=
a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},Uc:0,Vc:0,gd:0,hd:0,touches:{},Nd:{},ye:function(a){if(k.Sd)"mousemove"!=a.type&&"mozMovementX"in a?k.gd=k.hd=0:(k.gd=k.Lf(a),k.hd=k.Mf(a)),"undefined"!=typeof m?(k.Uc=m.Uc+k.gd,k.Vc=m.Vc+k.hd):(k.Uc+=k.gd,k.Vc+=k.hd);else{var b=r.canvas.getBoundingClientRect(),
c=r.canvas.width,d=r.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var l=a.od;if(void 0!==l)if(e=l.pageX-(e+b.left),f=l.pageY-(f+b.top),e*=c/b.width,f*=d/b.height,b={x:e,y:f},"touchstart"===a.type)k.Nd[l.identifier]=b,k.touches[l.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=k.touches[l.identifier])||
(a=b),k.Nd[l.identifier]=a,k.touches[l.identifier]=b}else l=a.pageX-(e+b.left),a=a.pageY-(f+b.top),l*=c/b.width,a*=d/b.height,k.gd=l-k.Uc,k.hd=a-k.Vc,k.Uc=l,k.Vc=a}},Si:function(a,b,c,d){var e=d?"":"al "+a;r.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&Ua()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ta()},ff:[],se:function(){var a=r.canvas;k.ff.forEach(function(b){b(a.width,a.height)})},gf:function(a,b,
c){k.Fd(r.canvas,a,b);c||k.se()},Xj:0,Wj:0,wg:function(){"undefined"!=typeof m&&(E[m.screen>>2]=N[m.screen>>2]|8388608);k.Fd(r.canvas);k.se()},xg:function(){"undefined"!=typeof m&&(E[m.screen>>2]=N[m.screen>>2]&-8388609);k.Fd(r.canvas);k.se()},Fd:function(a,b,c){b&&c?(a.Lg=b,a.Pf=c):(b=a.Lg,c=a.Pf);var d=b,e=c;r.forcedAspectRatio&&0<r.forcedAspectRatio&&(d/e<r.forcedAspectRatio?d=Math.round(e*r.forcedAspectRatio):e=Math.round(d/r.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||
document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}k.ld?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",
d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Vj:{},$e:0,kj:function(){var a=k.$e;k.$e++;return a}};
m={td:{width:320,height:200,Cf:!0,Fe:!1,bf:!0},version:null,nd:{},be:[],events:[],fonts:[null],Ti:[null],Cj:[null],le:{audio:null,volume:1},tj:22050,sj:32784,uj:2,rj:1024,Vi:0,ae:!1,$c:{0:3,1:3,2:2,3:0,4:0,5:1,6:16,7:0,8:0,9:0,10:0,11:0,12:0,13:0,14:0,15:1,16:0,17:0,18:0},Oc:null,Md:{},ze:!1,Se:!1,kf:!1,startTime:null,Re:0,rd:0,Ye:0,Qc:[0,0,0],rc:{},xf:0,Ge:null,Gf:null,He:0,Zf:{16:1249,17:1248,18:1250,20:1081,33:1099,34:1102,35:1101,36:1098,37:1104,38:1106,39:1103,40:1105,44:316,45:1097,46:127,91:1251,
93:1125,96:1122,97:1113,98:1114,99:1115,100:1116,101:1117,102:1118,103:1119,104:1120,105:1121,106:1109,107:1111,109:1110,110:1123,111:1108,112:1082,113:1083,114:1084,115:1085,116:1086,117:1087,118:1088,119:1089,120:1090,121:1091,122:1092,123:1093,124:1128,125:1129,126:1130,127:1131,128:1132,129:1133,130:1134,131:1135,132:1136,133:1137,134:1138,135:1139,144:1107,160:94,161:33,162:34,163:35,164:36,165:37,166:38,167:95,168:40,169:41,170:42,171:43,172:124,173:45,174:123,175:125,176:126,181:127,182:129,
183:128,188:44,190:46,191:47,192:96,219:91,220:92,221:93,222:39,224:1251},ug:{8:42,9:43,13:40,27:41,32:44,35:204,39:53,44:54,46:55,47:56,48:39,49:30,50:31,51:32,52:33,53:34,54:35,55:36,56:37,57:38,58:203,59:51,61:46,91:47,92:49,93:48,96:52,97:4,98:5,99:6,100:7,101:8,102:9,103:10,104:11,105:12,106:13,107:14,108:15,109:16,110:17,111:18,112:19,113:20,114:21,115:22,116:23,117:24,118:25,119:26,120:27,121:28,122:29,127:76,305:224,308:226,316:70},Te:function(a){return{x:E[a+0>>2],y:E[a+4>>2],wc:E[a+8>>2],
vc:E[a+12>>2]}},Gg:function(a,b){E[a>>2]=b.x;E[a+4>>2]=b.y;E[a+8>>2]=b.wc;E[a+12>>2]=b.vc},Tf:function(a,b){var c=Math.max(a.x,b.x),d=Math.max(a.y,b.y);return{x:c,y:d,wc:Math.max(c,Math.min(a.x+a.wc,b.x+b.wc))-c,vc:Math.max(d,Math.min(a.y+a.vc,b.y+b.vc))-d}},Wi:function(){},nj:function(a){a=E[a>>2];return"rgb("+(a&255)+","+(a>>8&255)+","+(a>>16&255)+")"},oj:function(a){a=E[a>>2];return"rgba("+(a&255)+","+(a>>8&255)+","+(a>>16&255)+","+(a>>24&255)/255+")"},Nj:function(a){return"rgba("+(a&255)+","+
(a>>8&255)+","+(a>>16&255)+","+(a>>>24)/255+")"},Oj:function(a,b,c,d){return"rgba("+(a&255)+","+(b&255)+","+(c&255)+","+(d&255)/255+")"},Pj:function(a,b,c,d){return a|b<<8|c<<16|d<<24},dg:function(a,b,c,d,e,f,l,q,t){c=c||0;var v=c&1,y=c&2097152,K=c&67108864,B=G(60),H=G(44),L=y?1:4;y=0;v||K||(y=G(a*b*4));E[B>>2]=c;E[B+4>>2]=H;E[B+8>>2]=a;E[B+12>>2]=b;E[B+16>>2]=a*L;E[B+20>>2]=y;E[B+36>>2]=0;E[B+40>>2]=0;E[B+44>>2]=r.canvas.width;E[B+48>>2]=r.canvas.height;E[B+56>>2]=1;E[H>>2]=-2042224636;E[H+4>>2]=
0;I[H+8>>0]=8*L;I[H+9>>0]=L;E[H+12>>2]=f||255;E[H+16>>2]=l||65280;E[H+20>>2]=q||16711680;E[H+24>>2]=t||4278190080;m.ae=m.ae||K;if(d)var Q=r.canvas;else 0<m.be.length?Q=m.be.pop():Q=document.createElement("canvas"),Q.width=a,Q.height=b;f=k.createContext(Q,K,d,{antialias:0!=m.$c[13]&&1<m.$c[14],depth:0<m.$c[6],stencil:0<m.$c[7],alpha:0<m.$c[3]});m.nd[B]={width:a,height:b,canvas:Q,zc:f,zg:B,buffer:y,ig:H,alpha:255,flags:c,locked:0,Ig:d,source:e,Vf:function(a){return c&a}};return B},Yi:function(a,b,c,
d,e){if(a.colors){var f=r.canvas.width,l=r.canvas.height;b=b||0;c=c||0;d=(d||f-b)+b;e=(e||l-c)+c;l=a.buffer;a.image.De||(a.image.De=new Uint32Array(a.image.data.buffer));var q=a.image.De;for(a=a.Xi;c<e;++c)for(var t=c*f,v=b;v<d;++v)q[t+v]=a[J[l+t+v>>0]]}},Me:function(a){var b=a+56,c=E[b>>2];1<c?E[b>>2]=c-1:(b=m.nd[a],!b.Ig&&b.canvas&&m.be.push(b.canvas),b.buffer&&bc(b.buffer),bc(b.ig),bc(a),m.nd[a]=null,a===m.screen&&(m.screen=null))},Ui:function(a,b,c,d,e){var f=m.nd[a];a=m.nd[c];var l,q;b?l=m.Te(b):
l={x:0,y:0,wc:f.width,vc:f.height};d?q=m.Te(d):q={x:0,y:0,wc:f.width,vc:f.height};if(a.Bf){b=e&&0!==l.wc?l.wc/q.wc:1;var t=e&&0!==l.vc?l.vc/q.vc:1;q=m.Tf(a.Bf,q);l.wc=q.wc*b;l.vc=q.vc*t;d&&m.Gg(d,q)}e?(d=q.wc,e=q.vc):(d=l.wc,e=l.vc);if(0===l.wc||0===l.vc||0===d||0===e)return 0;b=a.zc.globalAlpha;a.zc.globalAlpha=f.alpha/255;a.zc.drawImage(f.canvas,l.x,l.y,l.wc,l.vc,q.x,q.y,d,e);a.zc.globalAlpha=b;if(c!=m.screen){ka("WARNING: copying canvas data to memory for compatibility");a:if(l=m.nd[c],l.locked++,
!(1<l.locked||(l.buffer||(l.buffer=G(l.width*l.height*4),E[c+20>>2]=l.buffer),E[c+20>>2]=l.buffer,c==m.screen&&r.Hj&&l.image))){if(m.td.Fe){if(l.image||(l.image=l.zc.createImageData(l.width,l.height)),!m.td.bf)break a}else l.image=l.zc.getImageData(0,0,l.width,l.height);if(c==m.screen&&m.td.bf)for(c=l.image.data,q=c.length,f=0;f<q/4;f++)c[4*f+3]=255;if(m.td.Cf&&!m.td.Fe){if(l.Vf(2097152))throw"CopyOnLock is not supported for SDL_LockSurface with SDL_HWPALETTE flag set"+Error().stack;J.set(l.image.data,
l.buffer)}}a.locked--}return 0},Id:{},Td:null,Pc:function(a){function b(){for(var a in m.Md)m.events.push({type:"keyup",keyCode:m.Md[a]})}switch(a.type){case "touchstart":case "touchmove":a.preventDefault();var c=[];if("touchstart"===a.type)for(var d=0;d<a.touches.length;d++){var e=a.touches[d];1!=m.Id[e.identifier]&&(m.Id[e.identifier]=!0,c.push(e))}else c=a.touches;if(d=c[0]){"touchstart"==a.type&&(m.Qc[0]=1);switch(a.type){case "touchstart":var f="mousedown";break;case "touchmove":f="mousemove"}f=
{type:f,button:0,pageX:d.clientX,pageY:d.clientY};m.events.push(f)}for(d=0;d<c.length;d++)e=c[d],m.events.push({type:a.type,od:e});break;case "touchend":a.preventDefault();for(d=0;d<a.changedTouches.length;d++)e=a.changedTouches[d],!0===m.Id[e.identifier]&&delete m.Id[e.identifier];f={type:"mouseup",button:0,pageX:a.changedTouches[0].clientX,pageY:a.changedTouches[0].clientY};m.Qc[0]=0;m.events.push(f);for(d=0;d<a.changedTouches.length;d++)e=a.changedTouches[d],m.events.push({type:"touchend",od:e});
break;case "DOMMouseScroll":case "mousewheel":case "wheel":c=-k.Kf(a);c=0==c?0:0<c?Math.max(c,1):Math.min(c,-1);f=0<c?3:4;m.events.push({type:"mousedown",button:f,pageX:a.pageX,pageY:a.pageY});m.events.push({type:"mouseup",button:f,pageX:a.pageX,pageY:a.pageY});m.events.push({type:"wheel",deltaX:0,deltaY:c});a.preventDefault();break;case "mousemove":if(1===m.Qc[0]&&m.events.push({type:"touchmove",od:{identifier:0,ud:-1,pageX:a.pageX,pageY:a.pageY}}),k.Sd&&("mozMovementX"in a&&(a.movementX=a.mozMovementX,
a.movementY=a.mozMovementY),0==a.movementX&&0==a.movementY)){a.preventDefault();return}case "keydown":case "keyup":case "keypress":case "mousedown":case "mouseup":"keydown"===a.type&&(m.Rj||m.kf)&&8!==a.keyCode&&9!==a.keyCode||a.preventDefault();if("mousedown"==a.type)m.Qc[a.button]=1,m.events.push({type:"touchstart",od:{identifier:0,ud:-1,pageX:a.pageX,pageY:a.pageY}});else if("mouseup"==a.type){if(!m.Qc[a.button])return;m.events.push({type:"touchend",od:{identifier:0,ud:-1,pageX:a.pageX,pageY:a.pageY}});
m.Qc[a.button]=0}if("keydown"===a.type||"mousedown"===a.type)m.ze=!0;else if("keyup"===a.type||"mouseup"===a.type)m.Se&&(r.requestFullscreen(!0,!0),m.Se=!1),m.ze=!1;"keypress"===a.type&&m.Td?(m.Td.$f=a.charCode,m.Td=null):"keydown"===a.type&&(m.Td=a);("keypress"!==a.type||m.kf)&&m.events.push(a);break;case "mouseout":for(d=0;3>d;d++)m.Qc[d]&&(m.events.push({type:"mouseup",button:d,pageX:a.pageX,pageY:a.pageY}),m.Qc[d]=0);a.preventDefault();break;case "focus":m.events.push(a);a.preventDefault();break;
case "blur":m.events.push(a);b();a.preventDefault();break;case "visibilitychange":m.events.push({type:"visibilitychange",visible:!document.hidden});b();a.preventDefault();break;case "unload":k.lc.md&&(m.events.push(a),k.lc.md());return;case "resize":m.events.push(a),a.preventDefault&&a.preventDefault()}1E4<=m.events.length&&(D("SDL event queue full, dropping events"),m.events=m.events.slice(0,1E4));m.If()},Ue:function(a){var b=a.keyCode;65<=b&&90>=b?b+=32:(b=m.Zf[a.keyCode]||a.keyCode,a.location===
KeyboardEvent.Bc&&1248<=b&&1251>=b&&(b+=4));return b},handleEvent:function(a){if(!a.Of)switch(a.Of=!0,a.type){case "touchstart":case "touchend":case "touchmove":k.ye(a);break;case "keydown":case "keyup":var b="keydown"===a.type,c=m.Ue(a);I[m.Oc+c>>0]=b;m.Ye=(I[m.Oc+1248>>0]?64:0)|(I[m.Oc+1249>>0]?1:0)|(I[m.Oc+1250>>0]?256:0)|(I[m.Oc+1252>>0]?128:0)|(I[m.Oc+1253>>0]?2:0)|(I[m.Oc+1254>>0]?512:0);b?m.Md[c]=a.keyCode:delete m.Md[c];break;case "mousedown":case "mouseup":"mousedown"==a.type?m.rd|=1<<a.button:
"mouseup"==a.type&&(m.rd&=~(1<<a.button));case "mousemove":k.ye(a)}},If:function(){if(m.Ge)for(;m.cf(m.He);)r.dynCall_iii(m.Ge,m.Gf,m.He)},cf:function(a){m.Re&512&&m.Yf&&m.mg();if(a){for(;0<m.events.length;)if(!1!==m.ag(m.events.shift(),a))return 1;return 0}return 0<m.events.length},ag:function(a,b){if("number"===typeof a)cc(b,a,28),bc(a);else switch(m.handleEvent(a),a.type){case "keydown":case "keyup":var c="keydown"===a.type,d=m.Ue(a),e;1024<=d?e=d-1024:e=m.ug[d]||d;E[b>>2]=m.rc[a.type];I[b+8>>
0]=c?1:0;I[b+9>>0]=0;E[b+12>>2]=e;E[b+16>>2]=d;va[b+20>>1]=m.Ye;E[b+24>>2]=a.$f||d;break;case "keypress":E[b>>2]=m.rc[a.type];a=ab(String.fromCharCode(a.charCode));for(c=0;c<a.length;++c)I[b+(8+c)>>0]=a[c];break;case "mousedown":case "mouseup":case "mousemove":"mousemove"!=a.type?(c="mousedown"===a.type,E[b>>2]=m.rc[a.type],E[b+4>>2]=0,E[b+8>>2]=0,E[b+12>>2]=0,I[b+16>>0]=a.button+1,I[b+17>>0]=c?1:0,E[b+20>>2]=k.Uc,E[b+24>>2]=k.Vc):(E[b>>2]=m.rc[a.type],E[b+4>>2]=0,E[b+8>>2]=0,E[b+12>>2]=0,E[b+16>>
2]=m.rd,E[b+20>>2]=k.Uc,E[b+24>>2]=k.Vc,E[b+28>>2]=k.gd,E[b+32>>2]=k.hd);break;case "wheel":E[b>>2]=m.rc[a.type];E[b+16>>2]=a.deltaX;E[b+20>>2]=a.deltaY;break;case "touchstart":case "touchend":case "touchmove":c=a.od;if(!k.touches[c.identifier])break;var f=r.canvas.width,l=r.canvas.height;d=k.touches[c.identifier].x/f;e=k.touches[c.identifier].y/l;f=d-k.Nd[c.identifier].x/f;l=e-k.Nd[c.identifier].y/l;void 0===c.deviceID&&(c.ud=m.xf);if(0===f&&0===l&&"touchmove"===a.type)return!1;E[b>>2]=m.rc[a.type];
E[b+4>>2]=Date.now()-m.startTime|0;g=[c.ud>>>0,(h=c.ud,1<=+Ma(h)?0<h?(Pa(+Oa(h/4294967296),4294967295)|0)>>>0:~~+Na((h-+(~~h>>>0))/4294967296)>>>0:0)];E[b+8>>2]=g[0];E[b+12>>2]=g[1];g=[c.identifier>>>0,(h=c.identifier,1<=+Ma(h)?0<h?(Pa(+Oa(h/4294967296),4294967295)|0)>>>0:~~+Na((h-+(~~h>>>0))/4294967296)>>>0:0)];E[b+16>>2]=g[0];E[b+20>>2]=g[1];O[b+24>>2]=d;O[b+28>>2]=e;O[b+32>>2]=f;O[b+36>>2]=l;O[b+40>>2]=void 0!==c.force?c.force:"touchend"==a.type?0:1;break;case "unload":E[b>>2]=m.rc[a.type];break;
case "resize":E[b>>2]=m.rc[a.type];E[b+4>>2]=a.wc;E[b+8>>2]=a.vc;break;case "joystick_button_up":case "joystick_button_down":c="joystick_button_up"===a.type?0:1;E[b>>2]=m.rc[a.type];I[b+4>>0]=a.index;I[b+5>>0]=a.button;I[b+6>>0]=c;break;case "joystick_axis_motion":E[b>>2]=m.rc[a.type];I[b+4>>0]=a.index;I[b+5>>0]=a.axis;E[b+8>>2]=m.Xf(a.value);break;case "focus":E[b>>2]=m.rc[a.type];E[b+4>>2]=0;I[b+8>>0]=12;break;case "blur":E[b>>2]=m.rc[a.type];E[b+4>>2]=0;I[b+8>>0]=13;break;case "visibilitychange":c=
a.visible?1:2;E[b>>2]=m.rc[a.type];E[b+4>>2]=0;I[b+8>>0]=c;break;default:throw"Unhandled SDL event: "+a.type;}},cg:function(a,b){"'"!=b.charAt(0)&&'"'!=b.charAt(0)&&(b='"'+b+'"');return a+"px "+b+", serif"},dj:function(a,b){var c=m.cg(a.size,a.name);a=m.Qj;a.save();a.font=c;b=a.measureText(b).width|0;a.restore();return b},Ri:function(a){if(!(m.me&&m.me>=a&&0!=a)){m.me=a;m.sd=[];for(var b=0;b<a;b++)m.sd[b]={audio:null,volume:1}}},Ij:function(a,b){if(!a)return 0;var c=128*a.volume;if(-1!=b&&(a.volume=
Math.min(Math.max(b,0),128)/128,a.audio))try{a.audio.volume=a.volume,a.audio.Gd&&(a.audio.Gd.gain.value=a.volume)}catch(d){D("setGetVolume failed to set audio volume: "+d)}return c},Jj:function(a,b,c,d){a&&a.audio&&a.audio.pd&&a.audio.pd.setPosition(b,c,d)},jg:function(a){if(a&&!a.Jc&&m.Kg())try{var b=a.rg.Jg;a.paused=!1;b.Ee?(a.Jc=m.Lc.createBufferSource(),a.Jc.buffer=b.Ee,a.Jc.loop=a.loop,a.Jc.onended=function(){a.onended()},a.pd=m.Lc.createPanner(),a.pd.setPosition(0,0,-.5),a.pd.panningModel="equalpower",
a.Gd=m.Lc.createGain(),a.Gd.gain.value=a.volume,a.Jc.connect(a.pd),a.pd.connect(a.Gd),a.Gd.connect(m.Lc.destination),a.Jc.start(0,a.Ce),a.startTime=m.Lc.currentTime-a.Ce):(void 0===b.hg&&C("Cannot play back audio object that was not loaded"),b.hg.push(function(){a.paused||m.jg(a)}))}catch(c){D("playWebAudio failed: "+c)}},zj:function(a){if(a){if(a.Jc)try{a.Ce=(m.Lc.currentTime-a.startTime)%a.rg.Jg.Ee.duration,a.Jc.onended=void 0,a.Jc.stop(0),a.Jc=void 0}catch(b){D("pauseWebAudio failed: "+b)}a.paused=
!0}},xj:function(){m.Lc||("undefined"!==typeof AudioContext?m.Lc=new AudioContext:"undefined"!==typeof webkitAudioContext&&(m.Lc=new webkitAudioContext))},Kg:function(){return!!m.Lc},hj:function(a,b,c){for(var d=m.audio.sd,e=0;e<d;++e){var f=c.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(32784==m.audio.format)for(var l=0;l<b;++l)f[l]=va[a+2*(l*d+e)>>1]/32768;else if(8==m.audio.format)for(l=0;l<
b;++l){var q=I[a+(l*d+e)>>0];f[l]=(0<=q?q-128:q+128)/128}else if(33056==m.audio.format)for(l=0;l<b;++l)f[l]=O[a+4*(l*d+e)>>2];else throw"Invalid SDL audio format "+m.audio.format+"!";}},$i:function(a){console.log("dumping surface "+[a.zg,a.source,a.width,a.height]);for(var b=a.zc.getImageData(0,0,a.width,a.height).data,c=Math.min(a.width,a.height),d=0;d<c;d++)console.log("   diagonal "+d+":"+[b[d*a.width*4+4*d],b[d*a.width*4+4*d+1],b[d*a.width*4+4*d+2],b[d*a.width*4+4*d+3]])},Yf:1,ie:{},lj:{},og:function(a,
b){for(var c=Array(b.buttons.length),d=0;d<b.buttons.length;d++)c[d]=m.Oe(b.buttons[d]);m.ie[a]={buttons:c,axes:b.axes.slice(0),timestamp:b.timestamp,index:b.index,id:b.id}},Oe:function(a){return"object"===typeof a?a.pressed:0<a},mg:function(){for(var a in m.ie){var b=m.Jf(a-1),c=m.ie[a];if("undefined"===typeof b)break;if(null===b)break;if("number"!==typeof b.timestamp||b.timestamp!==c.timestamp||!b.timestamp){var d;for(d=0;d<b.buttons.length;d++){var e=m.Oe(b.buttons[d]);e!==c.buttons[d]&&m.events.push({type:e?
"joystick_button_down":"joystick_button_up",Wf:a,index:a-1,button:d})}for(d=0;d<b.axes.length;d++)b.axes[d]!==c.axes[d]&&m.events.push({type:"joystick_axis_motion",Wf:a,index:a-1,axis:d,value:b.axes[d]});m.og(a,b)}}},Xf:function(a){a=Math.min(1,Math.max(a,-1));return Math.ceil(32767.5*(a+1)-32768)},getGamepads:function(){var a=navigator.getGamepads||navigator.vj||navigator.ke||navigator.Bc||navigator.webkitGetGamepads;return void 0!==a?a.apply(navigator):[]},Jf:function(a){var b=m.getGamepads();return b.length>
a&&0<=a?b[a]:null}};
n={Be:1,xd:0,dd:[],qj:{},yc:[],Jd:[],Ed:[],Ud:[],mc:[],Gc:[],Zd:[],Hc:{},oc:null,Rd:{},Lj:[],lg:[],Gj:[],mf:[],Kj:[],Cd:{},re:{},jf:{},nf:4,he:function(){n.We=new Float32Array(n.Kc);for(var a=0;a<n.Kc;a++)n.Tc[a]=n.We.subarray(0,a+1)},tc:function(a){n.xd||(n.xd=a)},vd:function(a){for(var b=n.Be++,c=a.length;c<b;c++)a[c]=null;return b},Kc:256,We:null,Tc:[0],Nf:function(a,b,c,d){a="";for(var e=0;e<b;++e){var f=d?E[d+4*e>>2]:-1;a+=M(E[c+4*e>>2],0>f?void 0:f)}return a},createContext:function(a,b){return(a=
1<b.Ve?a.getContext("webgl2",b):a.getContext("webgl",b)||a.getContext("experimental-webgl",b))&&n.pg(a,b)},pg:function(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=G(8),e={handle:d,attributes:b,version:b.Ve,cd:a};e.sc=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.wf=e);n.Hc[d]=e;("undefined"===typeof b.Ff||b.Ff)&&n.Qf(e);return d},bg:function(a){n.oc=n.Hc[a];r.zc=p=n.oc&&n.oc.cd;return!(a&&!p)},getContext:function(a){return n.Hc[a]},
aj:function(a){n.oc===n.Hc[a]&&(n.oc=null);if("object"===typeof dc)for(var b=n.Hc[a].cd.canvas,c=0;c<ec.length;++c)if(ec[c].target==b){var d=c--,e=ec[d];e.target.removeEventListener(e.fj,e.ej,e.Sj);ec.splice(d,1)}n.Hc[a]&&n.Hc[a].cd.canvas&&(n.Hc[a].cd.canvas.wf=void 0);bc(n.Hc[a]);n.Hc[a]=null},Qf:function(a){a||(a=n.oc);if(!a.Rf){a.Rf=!0;var b=a.cd;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=
function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,
b){e.drawBuffersWEBGL(a,b)})}b.cj=b.getExtension("EXT_disjoint_timer_query");var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}},kg:function(a){var b=n.yc[a];a=n.Cd[a]={mc:{},je:0,yd:-1,zd:-1};for(var c=a.mc,d=p.getProgramParameter(b,35718),e=0;e<d;++e){var f=p.getActiveUniform(b,e),l=f.name;a.je=Math.max(a.je,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var q=p.getUniformLocation(b,l);if(q){var t=n.vd(n.mc);c[l]=[f.size,t];n.mc[t]=q;for(var v=1;v<f.size;++v)q=p.getUniformLocation(b,
l+"["+v+"]"),t=n.vd(n.mc),n.mc[t]=q}}}};var X={};
function fc(a){if(fc.Af){var b=E[a>>2];var c=E[b>>2]}else fc.Af=!0,X.USER=X.LOGNAME="web_user",X.PATH="/",X.PWD="/",X.HOME="/home/web_user",X.LANG="C.UTF-8",X._=r.thisProgram,c=Ea?G(1024):ha(1024),b=Ea?G(256):ha(256),E[b>>2]=c,E[a>>2]=b;a=[];var d=0,e;for(e in X)if("string"===typeof X[e]){var f=e+"="+X[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var l=c,q=0;q<d.length;++q)I[l++>>0]=d.charCodeAt(q);I[l>>0]=0;E[b+4*
e>>2]=c;c+=f.length+1}E[b+4*a.length>>2]=0}
var R={vf:1,tf:2,Ei:3,vh:4,te:5,ve:6,Mg:7,Wh:8,sf:9,ah:10,rf:11,Oi:11,uf:12,qf:13,oh:14,hi:15,Zg:16,nh:17,Pi:18,$d:19,ji:20,xh:21,Ec:22,Rh:23,Jh:24,bd:25,Li:26,ph:27,di:28,Di:29,Ai:30,Kh:31,ti:32,kh:33,xi:34,$h:42,sh:43,bh:44,zh:45,Ah:46,Bh:47,Hh:48,Mi:49,Uh:50,yh:51,hh:35,Xh:37,Sg:52,Vg:53,Qi:54,Sh:55,Wg:56,Xg:57,ih:35,Yg:59,fi:60,Vh:61,Ii:62,ei:63,ai:64,bi:65,zi:66,Yh:67,Pg:68,Fi:69,dh:70,ui:71,Mh:72,lh:73,Ug:74,ni:76,Tg:77,yi:78,Ch:79,Dh:80,Gh:81,Fh:82,Eh:83,gi:38,ue:39,Nh:36,Ih:40,oi:95,si:96,
gh:104,Th:105,Qg:97,wi:91,li:88,ci:92,Bi:108,fh:111,Ng:98,eh:103,Qh:101,Oh:100,Ji:110,qh:112,rh:113,uh:115,Rg:114,jh:89,Lh:90,vi:93,Ci:94,Og:99,Ph:102,wh:106,ii:107,Ki:109,Ni:87,mh:122,Gi:116,mi:95,Zh:123,th:84,pi:75,$g:125,ki:131,ri:130,Hi:86},hc={},Y=0;function Z(){Y+=4;return E[Y-4>>2]}function ic(){var a=Bb[Z()];if(!a)throw new P(R.sf);return a}var ec=[],dc={},jc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function kc(a){try{if(!a)return window;"number"===typeof a&&(a=jc[a]||M(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?r.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function ja(){return I.length}function lc(){C("OOM")}function mc(a){if(0===a)return 0;a=M(a);if(!X.hasOwnProperty(a))return 0;mc.Bc&&bc(mc.Bc);a=X[a];var b=sa(a)+1,c=G(b);c&&ra(a,I,c,b);mc.Bc=c;return mc.Bc}var nc=[];
function oc(a,b,c,d){for(var e=0;e<a;e++){var f=p[c](),l=f&&n.vd(d);f?(f.name=l,d[l]=f):n.tc(1282);E[b+4*e>>2]=l}}
function pc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&n.tc(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=p.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>n.oc.version){n.tc(1282);return}d=2*p.getSupportedExtensions().length;break;case 33307:case 33308:if(2>n.oc.version){n.tc(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=p.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":n.tc(1280);
return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:d=0;break;default:n.tc(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":E[b+4*a>>2]=e[a];break;case "Float":O[b+4*a>>2]=e[a];break;case "Boolean":I[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=
e.name|0}catch(f){n.tc(1280);D("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:n.tc(1280);return}switch(c){case "Integer64":g=[d>>>0,(h=d,1<=+Ma(h)?0<h?(Pa(+Oa(h/4294967296),4294967295)|0)>>>0:~~+Na((h-+(~~h>>>0))/4294967296)>>>0:0)];E[b>>2]=g[0];E[b+4>>2]=g[1];break;case "Integer":E[b>>2]=d;break;case "Float":O[b>>2]=d;break;case "Boolean":I[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else n.tc(1281)}
function qc(a){var b=sa(a)+1,c=G(b);ra(a,J,c,b);return c}var rc={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},sc={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function tc(a,b,c,d,e){if(b=rc[b]*sc[a]){var f=n.nf;c=e+d*(c*b+f-1&-f);switch(a){case 5120:return I.subarray(e,c);case 5121:return J.subarray(e,c);case 5122:return va.subarray(e>>1,c>>1);case 5124:return E.subarray(e>>2,c>>2);case 5126:return O.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return N.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return wa.subarray(e>>1,c>>1);default:n.tc(1280)}}else n.tc(1280)}
function uc(a){switch(a){case 5120:return I;case 5121:return J;case 5122:return va;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return wa;case 5124:return E;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return N;case 5126:return O}}var vc={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};function wc(){wc.Bc||(wc.Bc=[]);wc.Bc.push(xc());return wc.Bc.length-1}
function yc(a){return 0===a%4&&(0!==a%100||0===a%400)}function zc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ac=[31,29,31,30,31,30,31,31,30,31,30,31],Bc=[31,28,31,30,31,30,31,31,30,31,30,31];function Cc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(yc(a.getFullYear())?Ac:Bc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Dc(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function q(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function t(a){a=Cc(new Date(a.xc+1900,0,1),a.Yd);var b=q(new Date(a.getFullYear()+1,0,4));return 0>=l(q(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var v=E[d+40>>2];d={Dg:E[d>>2],Cg:E[d+4>>2],Xd:E[d+8>>2],ad:E[d+12>>2],Xc:E[d+16>>2],xc:E[d+20>>2],lf:E[d+24>>2],Yd:E[d+28>>2],Mj:E[d+32>>2],Bg:E[d+36>>2],
Eg:v?M(v):""};c=M(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var y in v)c=c.replace(new RegExp(y,"g"),v[y]);var K="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),B="January February March April May June July August September October November December".split(" ");v={"%a":function(a){return K[a.lf].substring(0,3)},"%A":function(a){return K[a.lf]},"%b":function(a){return B[a.Xc].substring(0,
3)},"%B":function(a){return B[a.Xc]},"%C":function(a){return f((a.xc+1900)/100|0,2)},"%d":function(a){return f(a.ad,2)},"%e":function(a){return e(a.ad,2," ")},"%g":function(a){return t(a).toString().substring(2)},"%G":function(a){return t(a)},"%H":function(a){return f(a.Xd,2)},"%I":function(a){a=a.Xd;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.ad+zc(yc(a.xc+1900)?Ac:Bc,a.Xc-1),3)},"%m":function(a){return f(a.Xc+1,2)},"%M":function(a){return f(a.Cg,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.Xd&&12>a.Xd?"AM":"PM"},"%S":function(a){return f(a.Dg,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.xc+1900,a.Xc+1,a.ad,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.xc+1900,0,1),c=0===b.getDay()?b:Cc(b,7-b.getDay());a=new Date(a.xc+1900,a.Xc,a.ad);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(zc(yc(a.getFullYear())?Ac:Bc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=q(new Date(a.xc+1900,0,4)),c=q(new Date(a.xc+
1901,0,4)),d=Cc(new Date(a.xc+1900,0,1),a.Yd);return 0>l(d,b)?"53":0>=l(c,d)?"01":f(Math.ceil((b.getFullYear()<a.xc+1900?a.Yd+32-b.getDate():a.Yd+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.xc+1900,a.Xc+1,a.ad,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.xc,0,1),c=1===b.getDay()?b:Cc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.xc+1900,a.Xc,a.ad);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(zc(yc(a.getFullYear())?Ac:Bc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":
"00"},"%y":function(a){return(a.xc+1900).toString().substring(2)},"%Y":function(a){return a.xc+1900},"%z":function(a){a=a.Bg;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Eg},"%%":function(){return"%"}};for(y in v)0<=c.indexOf(y)&&(c=c.replace(new RegExp(y,"g"),v[y](d)));y=ab(c,!1);if(y.length>b)return 0;I.set(y,a);return y.length-1}Ha();Db=Array(4096);Sb(S,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");qb(259,{read:function(){return 0},write:function(a,b,c,l){return l}});Ub("/dev/null",259);pb(1280,sb);pb(1536,tb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(x)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){C("random_device")});Ia("random",b);Ia("urandom",b);V("/dev/shm");
V("/dev/shm/tmp")})();V("/proc");V("/proc/self");V("/proc/self/fd");Sb({Cc:function(){var a=vb("/proc/self","fd",16895,73);a.qc={lookup:function(a,c){var b=Bb[+c];if(!b)throw new P(9);a={parent:null,Cc:{Ze:"fake"},qc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(x){var fs=require("fs"),yb=require("path");T.yg()}
r.requestFullScreen=function(a,b,c){D("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");r.requestFullScreen=r.requestFullscreen;k.ef(a,b,c)};r.requestFullscreen=function(a,b,c){k.requestFullscreen(a,b,c)};r.requestAnimationFrame=function(a){k.requestAnimationFrame(a)};r.setCanvasSize=function(a,b,c){k.gf(a,b,c)};r.pauseMainLoop=function(){k.lc.pause()};r.resumeMainLoop=function(){k.lc.resume()};r.getUserMedia=function(){k.getUserMedia()};
r.createContext=function(a,b,c,d){return k.createContext(a,b,c,d)};x?$b=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?$b=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?$b=function(){return performance.now()}:$b=Date.now;n.he();for(var Ec=0;32>Ec;Ec++)nc.push(Array(Ec));function ab(a,b){var c=Array(sa(a)+1);a=ra(a,c,0,c.length);b&&(c.length=a);return c}
var Jc=r.asm({},{c:C,Vb:function(){},D:function(a){a&&m.Me(a)},f:function(a,b){a in m.$c||C("Unknown SDL GL attribute ("+a+"). Please check if your SDL version is supported.");m.$c[a]=b},z:function(){m.errorMessage||(m.errorMessage=oa(ab("unknown SDL-emscripten error")));return m.errorMessage},Da:function(a){m.startTime=Date.now();m.Re=a;r.doNotCaptureKeyboard||(a=r.keyboardListeningElement||document,a.addEventListener("keydown",m.Pc),a.addEventListener("keyup",m.Pc),a.addEventListener("keypress",
m.Pc),window.addEventListener("focus",m.Pc),window.addEventListener("blur",m.Pc),document.addEventListener("visibilitychange",m.Pc));window.addEventListener("unload",m.Pc);m.Oc=G(65536);Fc(m.Oc,0,65536);m.rc.keydown=768;m.rc.keyup=769;m.rc.keypress=771;m.rc.mousedown=1025;m.rc.mouseup=1026;m.rc.mousemove=1024;m.rc.wheel=1027;m.rc.touchstart=1792;m.rc.touchend=1793;m.rc.touchmove=1794;m.rc.unload=256;m.rc.resize=28673;m.rc.visibilitychange=512;m.rc.focus=512;m.rc.blur=512;m.rc.joystick_axis_motion=
1536;m.rc.joystick_button_down=1539;m.rc.joystick_button_up=1540;return 0},sa:function(a){return m.cf(a)},ia:function(){for(var a=0;a<m.me;++a)m.sd[a].audio&&(m.sd[a].audio.pause(),m.sd[a].audio=void 0);m.le.audio&&m.le.audio.pause();m.le.audio=void 0;fa("SDL_Quit called (and ignored)")},u:function(a,b,c,d){"touchstart touchend touchmove mousedown mouseup mousemove DOMMouseScroll mousewheel wheel mouseout".split(" ").forEach(function(a){r.canvas.addEventListener(a,m.Pc,!0)});c=r.canvas;0==a&&0==b&&
(a=c.width,b=c.height);m.yf||(m.yf=!0,k.ff.push(function(a,b){m.hf||m.Pc({type:"resize",wc:a,vc:b})}));m.hf=!0;k.gf(a,b);m.hf=!1;m.screen&&(m.Me(m.screen),assert(!m.screen));m.ae&&(d|=67108864);m.screen=m.dg(a,b,d,!0,"screen");return m.screen},P:fc,e:function(a){return G(a)},Mb:function(){F=!0;throw"Pure virtual function called!";},d:function(a){"uncaught_exception"in Gc?Gc.ke++:Gc.ke=1;throw a;},sb:function(){return!!Gc.ke},n:function(){},_a:function(){gb(1);return-1},G:gb,F:function(a,b){Y=b;try{var c=
ic();Z();var d=Z(),e=Z(),f=Z();Wb(c,d,f);E[e>>2]=c.position;c.ge&&0===d&&0===f&&(c.ge=null);return 0}catch(l){return"undefined"!==typeof W&&l instanceof P||C(l),-l.Mc}},Va:function(a,b){Y=b;try{var c=ic(),d=Z();a:{var e=Z();for(b=a=0;b<e;b++){var f=E[d+(8*b+4)>>2],l=c,q=E[d+8*b>>2],t=f,v=void 0,y=I;if(0>t||0>v)throw new P(22);if(null===l.fd)throw new P(9);if(1===(l.flags&2097155))throw new P(9);if(16384===(l.node.mode&61440))throw new P(21);if(!l.pc.read)throw new P(22);var K="undefined"!==typeof v;
if(!K)v=l.position;else if(!l.seekable)throw new P(29);var B=l.pc.read(l,y,q,t,v);K||(l.position+=B);var H=B;if(0>H){var L=-1;break a}a+=H;if(H<f)break}L=a}return L}catch(Q){return"undefined"!==typeof W&&Q instanceof P||C(Q),-Q.Mc}},E:function(a,b){Y=b;try{var c=ic(),d=Z();a:{var e=Z();for(b=a=0;b<e;b++){var f=c,l=E[d+8*b>>2],q=E[d+(8*b+4)>>2],t=void 0,v=I;if(0>q||0>t)throw new P(22);if(null===f.fd)throw new P(9);if(0===(f.flags&2097155))throw new P(9);if(16384===(f.node.mode&61440))throw new P(21);
if(!f.pc.write)throw new P(22);f.flags&1024&&Wb(f,0,2);var y="undefined"!==typeof t;if(!y)t=f.position;else if(!f.seekable)throw new P(29);var K=f.pc.write(f,v,l,q,t,void 0);y||(f.position+=K);try{if(f.path&&Fb.onWriteToFile)Fb.onWriteToFile(f.path)}catch(L){console.log("FS.trackingDelegate['onWriteToFile']('"+f.path+"') threw an exception: "+L.message)}var B=K;if(0>B){var H=-1;break a}a+=B}H=a}return H}catch(L){return"undefined"!==typeof W&&L instanceof P||C(L),-L.Mc}},m:function(a,b){Y=b;try{var c=
ic();switch(Z()){case 0:var d=Z();return 0>d?-R.Ec:Ka(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Z(),c.flags|=d,0;case 12:return d=Z(),va[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-R.Ec;case 9:return gb(R.Ec),-1;default:return-R.Ec}}catch(e){return"undefined"!==typeof W&&e instanceof P||C(e),-e.Mc}},Ua:function(a,b){Y=b;try{var c=M(Z());var d=Z();if(d&-8)var e=-R.Ec;else{var f=U(c,{ee:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");
e=a&&Kb(f,a)?-R.qf:0}return e}catch(l){return"undefined"!==typeof W&&l instanceof P||C(l),-l.Mc}},Ta:function(a,b){Y=b;try{var c=M(Z()),d=Z(),e=Z();return Ka(c,d,e).fd}catch(f){return"undefined"!==typeof W&&f instanceof P||C(f),-f.Mc}},C:function(a,b){Y=b;try{var c=ic(),d=Z();switch(d){case 21509:case 21505:return c.tty?0:-R.bd;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-R.bd;case 21519:if(!c.tty)return-R.bd;var e=Z();return E[e>>2]=0;case 21520:return c.tty?
-R.Ec:-R.bd;case 21531:a=e=Z();if(!c.pc.Uf)throw new P(25);return c.pc.Uf(c,d,a);case 21523:return c.tty?0:-R.bd;case 21524:return c.tty?0:-R.bd;default:C("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof W&&f instanceof P||C(f),-f.Mc}},B:function(a,b){Y=b;try{var c=ic();if(null===c.fd)throw new P(9);c.ge&&(c.ge=null);try{c.pc.close&&c.pc.close(c)}catch(d){throw d;}finally{Bb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof W&&d instanceof P||C(d),-d.Mc}},Sa:function(a,
b){Y=b;try{var c=Z(),d=Z(),e=hc[c];if(!e)return 0;if(d===e.mj){var f=Bb[e.fd],l=e.flags,q=new Uint8Array(J.subarray(c,c+d));f&&f.pc.Qd&&f.pc.Qd(f,q,0,d,l);hc[c]=null;e.zf&&bc(e.pj)}return 0}catch(t){return"undefined"!==typeof W&&t instanceof P||C(t),-t.Mc}},j:function(){},b:function(){r.abort()},Ra:function(a,b){return bb[a](b)},Qa:function(){k.lc.pause();k.lc.Ac=null},Pa:function(){return window.devicePixelRatio||1},A:function(a,b,c){a=a?kc(a):r.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),
xa[b>>3]=a.right-a.left,xa[c>>3]=a.bottom-a.top):(xa[b>>3]=a.clientWidth,xa[c>>3]=a.clientHeight);return 0},Oa:ja,Na:function(a,b,c){J.set(J.subarray(b,b+c),a)},Ma:function(a){lc(a)},La:function(a,b,c){"number"===typeof a&&(a=M(a));a=a&&"#canvas"!==a?"undefined"!==typeof n&&n.Rd[a]?n.Rd[a]:kc(a):"undefined"!==typeof n&&n.Rd.canvas?n.Rd.canvas:r.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},Ka:function(a,b,c,d){ac(a,c,d,b)},l:function(a){Hc(a)},i:mc,q:function(a){p.activeTexture(a)},Ja:function(a,
b){p.attachShader(n.yc[a],n.Gc[b])},y:function(a,b){35051==a?p.de=b:35052==a&&(p.Rc=b);p.bindBuffer(a,n.dd[b])},x:function(a,b,c){p.bindBufferBase(a,b,n.dd[c])},Ia:function(a,b,c,d,e){p.bindBufferRange(a,b,n.dd[c],d,e)},w:function(a,b){p.bindFramebuffer(a,n.Jd[b])},Ha:function(a,b){p.bindRenderbuffer(a,n.Ed[b])},p:function(a,b){p.bindTexture(a,n.Ud[b])},Ga:function(a,b){p.bindTransformFeedback(a,n.mf[b])},Fa:function(a){p.bindVertexArray(n.Zd[a])},Ea:function(a,b,c,d,e,f,l,q,t,v){p.blitFramebuffer(a,
b,c,d,e,f,l,q,t,v)},Ca:function(a,b,c,d){n.oc.sc?c?p.bufferData(a,J,d,c,b):p.bufferData(a,b,d):p.bufferData(a,c?J.subarray(c,c+b):b,d)},Ba:function(a,b,c,d){n.oc.sc?p.bufferSubData(a,b,J,d,c):p.bufferSubData(a,b,J.subarray(d,d+c))},Aa:function(a){return p.checkFramebufferStatus(a)},za:function(a){p.clear(a)},ya:function(a,b,c,d){p.clearBufferfi(a,b,c,d)},xa:function(a,b,c){p.clearBufferfv(a,b,O,c>>2)},wa:function(a,b,c){p.clearBufferiv(a,b,E,c>>2)},va:function(a,b,c){p.clearBufferuiv(a,b,N,c>>2)},
ua:function(a,b,c,d){p.clearColor(a,b,c,d)},ta:function(a){p.clearDepth(a)},ra:function(a){p.compileShader(n.Gc[a])},v:function(a,b,c,d,e,f,l,q,t){n.oc.sc?p.Rc?p.compressedTexSubImage2D(a,b,c,d,e,f,l,q,t):p.compressedTexSubImage2D(a,b,c,d,e,f,l,J,t,q):p.compressedTexSubImage2D(a,b,c,d,e,f,l,t?J.subarray(t,t+q):null)},qa:function(a,b,c,d,e,f,l,q,t,v,y){n.oc.sc?p.Rc?p.compressedTexSubImage3D(a,b,c,d,e,f,l,q,t,v,y):p.compressedTexSubImage3D(a,b,c,d,e,f,l,q,t,J,y,v):p.compressedTexSubImage3D(a,b,c,d,
e,f,l,q,t,y?J.subarray(y,y+v):null)},pa:function(a,b,c,d,e){p.copyBufferSubData(a,b,c,d,e)},oa:function(a,b,c,d,e,f,l,q){p.copyTexSubImage2D(a,b,c,d,e,f,l,q)},na:function(a,b,c,d,e,f,l,q,t){p.copyTexSubImage3D(a,b,c,d,e,f,l,q,t)},ma:function(){var a=n.vd(n.yc),b=p.createProgram();b.name=a;n.yc[a]=b;return a},la:function(a){var b=n.vd(n.Gc);n.Gc[b]=p.createShader(a);return b},ka:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=n.dd[d];e&&(p.deleteBuffer(e),e.name=0,n.dd[d]=null,d==n.Df&&(n.Df=
0),d==n.Ef&&(n.Ef=0),d==p.de&&(p.de=0),d==p.Rc&&(p.Rc=0))}},ja:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],e=n.Jd[d];e&&(p.deleteFramebuffer(e),e.name=0,n.Jd[d]=null)}},ha:function(a){if(a){var b=n.yc[a];b?(p.deleteProgram(b),b.name=0,n.yc[a]=null,n.Cd[a]=null):n.tc(1281)}},ga:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=n.Ed[d];e&&(p.deleteRenderbuffer(e),e.name=0,n.Ed[d]=null)}},fa:function(a){if(a){var b=n.Gc[a];b?(p.deleteShader(b),n.Gc[a]=null):n.tc(1281)}},ea:function(a,b){for(var c=
0;c<a;c++){var d=E[b+4*c>>2];p.deleteVertexArray(n.Zd[d]);n.Zd[d]=null}},da:function(a,b,c){p.drawArrays(a,b,c)},ca:function(a,b,c,d){p.drawArraysInstanced(a,b,c,d)},ba:function(a,b){for(var c=nc[a],d=0;d<a;d++)c[d]=E[b+4*d>>2];p.drawBuffers(c)},aa:function(a,b,c,d){p.drawElements(a,b,c,d)},$:function(a,b,c,d,e){p.drawElementsInstanced(a,b,c,d,e)},_:function(a){p.enable(a)},Z:function(a){p.enableVertexAttribArray(a)},Y:function(a,b,c,d){p.framebufferRenderbuffer(a,b,c,n.Ed[d])},X:function(a,b,c,d,
e){p.framebufferTexture2D(a,b,c,n.Ud[d],e)},W:function(a,b,c,d,e){p.framebufferTextureLayer(a,b,n.Ud[c],d,e)},V:function(a,b){oc(a,b,"createBuffer",n.dd)},U:function(a,b){oc(a,b,"createFramebuffer",n.Jd)},T:function(a,b){oc(a,b,"createQuery",n.lg)},S:function(a,b){oc(a,b,"createRenderbuffer",n.Ed)},R:function(a,b){oc(a,b,"createTexture",n.Ud)},Q:function(a,b){oc(a,b,"createTransformFeedback",n.mf)},O:function(a,b){oc(a,b,"createVertexArray",n.Zd)},N:function(a){p.generateMipmap(a)},M:function(a,b,
c){c?E[c>>2]=p.getBufferParameter(a,b):n.tc(1281)},L:function(){if(n.xd){var a=n.xd;n.xd=0;return a}return p.getError()},K:function(a,b){pc(a,b,"Float")},k:function(a,b){pc(a,b,"Integer")},J:function(a,b,c,d){a=p.getProgramInfoLog(n.yc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=ra(a,J,d,b),c&&(E[c>>2]=b)):c&&(E[c>>2]=0)},t:function(a,b,c){if(c)if(a>=n.Be)n.tc(1281);else{var d=n.Cd[a];if(d)if(35716==b)a=p.getProgramInfoLog(n.yc[a]),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==
b)E[c>>2]=d.je;else if(35722==b){if(-1==d.yd){a=n.yc[a];var e=p.getProgramParameter(a,35721);for(b=d.yd=0;b<e;++b)d.yd=Math.max(d.yd,p.getActiveAttrib(a,b).name.length+1)}E[c>>2]=d.yd}else if(35381==b){if(-1==d.zd)for(a=n.yc[a],e=p.getProgramParameter(a,35382),b=d.zd=0;b<e;++b)d.zd=Math.max(d.zd,p.getActiveUniformBlockName(a,b).length+1);E[c>>2]=d.zd}else E[c>>2]=p.getProgramParameter(n.yc[a],b);else n.tc(1282)}else n.tc(1281)},I:function(a,b,c,d){a=p.getShaderInfoLog(n.Gc[a]);null===a&&(a="(unknown error)");
0<b&&d?(b=ra(a,J,d,b),c&&(E[c>>2]=b)):c&&(E[c>>2]=0)},s:function(a,b,c){c?35716==b?(a=p.getShaderInfoLog(n.Gc[a]),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1):35720==b?(a=p.getShaderSource(n.Gc[a]),E[c>>2]=null===a||0==a.length?0:a.length+1):E[c>>2]=p.getShaderParameter(n.Gc[a],b):n.tc(1281)},r:function(a){if(n.re[a])return n.re[a];switch(a){case 7939:var b=p.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=qc(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
p.getParameter(a))||n.tc(1280);b=qc(b);break;case 7938:b=p.getParameter(p.VERSION);b=2<=n.oc.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=qc(b);break;case 35724:b=p.getParameter(p.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=qc(b);break;default:return n.tc(1280),0}return n.re[a]=b},Ub:function(a,b){if(2>n.oc.version)return n.tc(1282),0;var c=n.jf[a];if(c)return 0>b||
b>=c.length?(n.tc(1281),0):c[b];switch(a){case 7939:c=p.getSupportedExtensions();for(var d=[],e=0;e<c.length;++e)d.push(qc(c[e])),d.push(qc("GL_"+c[e]));c=n.jf[a]=d;return 0>b||b>=c.length?(n.tc(1281),0):c[b];default:return n.tc(1280),0}},Tb:function(a,b){b=M(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=n.Cd[a]&&n.Cd[a].mc[b])&&0<=c&&c<a[0]?a[1]+c:-1},Sb:function(a,b,c){for(var d=nc[b],e=0;e<b;e++)d[e]=E[c+4*e>>2];p.invalidateFramebuffer(a,
d)},Rb:function(a,b,c,d,e,f,l){for(var q=nc[b],t=0;t<b;t++)q[t]=E[c+4*t>>2];p.invalidateSubFramebuffer(a,q,d,e,f,l)},Qb:function(a){p.linkProgram(n.yc[a]);n.kg(a)},o:function(a,b){3317==a&&(n.nf=b);p.pixelStorei(a,b)},Pb:function(a){p.readBuffer(a)},Ob:function(a,b,c,d,e,f,l){n.oc.sc?p.de?p.readPixels(a,b,c,d,e,f,l):p.readPixels(a,b,c,d,e,f,uc(f),l>>(vc[f]|0)):(l=tc(f,e,c,d,l))?p.readPixels(a,b,c,d,e,f,l):n.tc(1280)},Nb:function(a,b,c,d){p.renderbufferStorage(a,b,c,d)},Lb:function(a,b,c,d,e){p.renderbufferStorageMultisample(a,
b,c,d,e)},Kb:function(a,b,c,d){b=n.Nf(a,b,c,d);p.shaderSource(n.Gc[a],b)},Jb:function(a,b,c,d,e,f,l,q,t){n.oc.sc?p.Rc?p.texImage2D(a,b,c,d,e,f,l,q,t):0!=t?p.texImage2D(a,b,c,d,e,f,l,q,uc(q),t>>(vc[q]|0)):p.texImage2D(a,b,c,d,e,f,l,q,null):p.texImage2D(a,b,c,d,e,f,l,q,t?tc(q,l,d,e,t):null)},Ib:function(a,b,c,d,e,f,l,q,t,v){p.Rc?p.texImage3D(a,b,c,d,e,f,l,q,t,v):0!=v?p.texImage3D(a,b,c,d,e,f,l,q,t,uc(t),v>>(vc[t]|0)):p.texImage3D(a,b,c,d,e,f,l,q,t,null)},Hb:function(a,b,c){p.texParameterf(a,b,c)},Gb:function(a,
b,c){p.texParameterf(a,b,O[c>>2])},Fb:function(a,b,c){p.texParameteri(a,b,c)},Eb:function(a,b,c){p.texParameteri(a,b,E[c>>2])},Db:function(a,b,c,d,e){p.texStorage2D(a,b,c,d,e)},Cb:function(a,b,c,d,e,f){p.texStorage3D(a,b,c,d,e,f)},H:function(a,b,c,d,e,f,l,q,t){if(n.oc.sc)p.Rc?p.texSubImage2D(a,b,c,d,e,f,l,q,t):0!=t?p.texSubImage2D(a,b,c,d,e,f,l,q,uc(q),t>>(vc[q]|0)):p.texSubImage2D(a,b,c,d,e,f,l,q,null);else{var v=null;t&&(v=tc(q,l,e,f,t));p.texSubImage2D(a,b,c,d,e,f,l,q,v)}},Bb:function(a,b,c,d,
e,f,l,q,t,v,y){p.Rc?p.texSubImage3D(a,b,c,d,e,f,l,q,t,v,y):0!=y?p.texSubImage3D(a,b,c,d,e,f,l,q,t,v,uc(v),y>>(vc[v]|0)):p.texSubImage3D(a,b,c,d,e,f,l,q,t,v,null)},Ab:function(a,b,c,d){a=n.yc[a];for(var e=[],f=0;f<b;f++)e.push(M(E[c+4*f>>2]));p.transformFeedbackVaryings(a,e,d)},zb:function(a,b,c){if(n.oc.sc)p.uniform1fv(n.mc[a],O,c>>2,b);else{if(b<=n.Kc)for(var d=n.Tc[b-1],e=0;e<b;++e)d[e]=O[c+4*e>>2];else d=O.subarray(c>>2,c+4*b>>2);p.uniform1fv(n.mc[a],d)}},yb:function(a,b,c){n.oc.sc?p.uniform1iv(n.mc[a],
E,c>>2,b):p.uniform1iv(n.mc[a],E.subarray(c>>2,c+4*b>>2))},xb:function(a,b,c){n.oc.sc?p.uniform1uiv(n.mc[a],N,c>>2,b):p.uniform1uiv(n.mc[a],N.subarray(c>>2,c+4*b>>2))},wb:function(a,b,c){if(n.oc.sc)p.uniform2fv(n.mc[a],O,c>>2,2*b);else{if(2*b<=n.Kc)for(var d=n.Tc[2*b-1],e=0;e<2*b;e+=2)d[e]=O[c+4*e>>2],d[e+1]=O[c+(4*e+4)>>2];else d=O.subarray(c>>2,c+8*b>>2);p.uniform2fv(n.mc[a],d)}},vb:function(a,b,c){n.oc.sc?p.uniform2iv(n.mc[a],E,c>>2,2*b):p.uniform2iv(n.mc[a],E.subarray(c>>2,c+8*b>>2))},ub:function(a,
b,c){n.oc.sc?p.uniform2uiv(n.mc[a],N,c>>2,2*b):p.uniform2uiv(n.mc[a],N.subarray(c>>2,c+8*b>>2))},tb:function(a,b,c){if(n.oc.sc)p.uniform3fv(n.mc[a],O,c>>2,3*b);else{if(3*b<=n.Kc)for(var d=n.Tc[3*b-1],e=0;e<3*b;e+=3)d[e]=O[c+4*e>>2],d[e+1]=O[c+(4*e+4)>>2],d[e+2]=O[c+(4*e+8)>>2];else d=O.subarray(c>>2,c+12*b>>2);p.uniform3fv(n.mc[a],d)}},rb:function(a,b,c){n.oc.sc?p.uniform3iv(n.mc[a],E,c>>2,3*b):p.uniform3iv(n.mc[a],E.subarray(c>>2,c+12*b>>2))},qb:function(a,b,c){n.oc.sc?p.uniform3uiv(n.mc[a],N,c>>
2,3*b):p.uniform3uiv(n.mc[a],N.subarray(c>>2,c+12*b>>2))},pb:function(a,b,c){if(n.oc.sc)p.uniform4fv(n.mc[a],O,c>>2,4*b);else{if(4*b<=n.Kc)for(var d=n.Tc[4*b-1],e=0;e<4*b;e+=4)d[e]=O[c+4*e>>2],d[e+1]=O[c+(4*e+4)>>2],d[e+2]=O[c+(4*e+8)>>2],d[e+3]=O[c+(4*e+12)>>2];else d=O.subarray(c>>2,c+16*b>>2);p.uniform4fv(n.mc[a],d)}},ob:function(a,b,c){n.oc.sc?p.uniform4iv(n.mc[a],E,c>>2,4*b):p.uniform4iv(n.mc[a],E.subarray(c>>2,c+16*b>>2))},nb:function(a,b,c){n.oc.sc?p.uniform4uiv(n.mc[a],N,c>>2,4*b):p.uniform4uiv(n.mc[a],
N.subarray(c>>2,c+16*b>>2))},mb:function(a,b,c,d){if(n.oc.sc)p.uniformMatrix2fv(n.mc[a],!!c,O,d>>2,4*b);else{if(4*b<=n.Kc)for(var e=n.Tc[4*b-1],f=0;f<4*b;f+=4)e[f]=O[d+4*f>>2],e[f+1]=O[d+(4*f+4)>>2],e[f+2]=O[d+(4*f+8)>>2],e[f+3]=O[d+(4*f+12)>>2];else e=O.subarray(d>>2,d+16*b>>2);p.uniformMatrix2fv(n.mc[a],!!c,e)}},lb:function(a,b,c,d){n.oc.sc?p.uniformMatrix2x3fv(n.mc[a],!!c,O,d>>2,6*b):p.uniformMatrix2x3fv(n.mc[a],!!c,O.subarray(d>>2,d+24*b>>2))},kb:function(a,b,c,d){n.oc.sc?p.uniformMatrix2x4fv(n.mc[a],
!!c,O,d>>2,8*b):p.uniformMatrix2x4fv(n.mc[a],!!c,O.subarray(d>>2,d+32*b>>2))},jb:function(a,b,c,d){if(n.oc.sc)p.uniformMatrix3fv(n.mc[a],!!c,O,d>>2,9*b);else{if(9*b<=n.Kc)for(var e=n.Tc[9*b-1],f=0;f<9*b;f+=9)e[f]=O[d+4*f>>2],e[f+1]=O[d+(4*f+4)>>2],e[f+2]=O[d+(4*f+8)>>2],e[f+3]=O[d+(4*f+12)>>2],e[f+4]=O[d+(4*f+16)>>2],e[f+5]=O[d+(4*f+20)>>2],e[f+6]=O[d+(4*f+24)>>2],e[f+7]=O[d+(4*f+28)>>2],e[f+8]=O[d+(4*f+32)>>2];else e=O.subarray(d>>2,d+36*b>>2);p.uniformMatrix3fv(n.mc[a],!!c,e)}},ib:function(a,b,
c,d){n.oc.sc?p.uniformMatrix3x2fv(n.mc[a],!!c,O,d>>2,6*b):p.uniformMatrix3x2fv(n.mc[a],!!c,O.subarray(d>>2,d+24*b>>2))},hb:function(a,b,c,d){n.oc.sc?p.uniformMatrix3x4fv(n.mc[a],!!c,O,d>>2,12*b):p.uniformMatrix3x4fv(n.mc[a],!!c,O.subarray(d>>2,d+48*b>>2))},gb:function(a,b,c,d){if(n.oc.sc)p.uniformMatrix4fv(n.mc[a],!!c,O,d>>2,16*b);else{if(16*b<=n.Kc)for(var e=n.Tc[16*b-1],f=0;f<16*b;f+=16)e[f]=O[d+4*f>>2],e[f+1]=O[d+(4*f+4)>>2],e[f+2]=O[d+(4*f+8)>>2],e[f+3]=O[d+(4*f+12)>>2],e[f+4]=O[d+(4*f+16)>>2],
e[f+5]=O[d+(4*f+20)>>2],e[f+6]=O[d+(4*f+24)>>2],e[f+7]=O[d+(4*f+28)>>2],e[f+8]=O[d+(4*f+32)>>2],e[f+9]=O[d+(4*f+36)>>2],e[f+10]=O[d+(4*f+40)>>2],e[f+11]=O[d+(4*f+44)>>2],e[f+12]=O[d+(4*f+48)>>2],e[f+13]=O[d+(4*f+52)>>2],e[f+14]=O[d+(4*f+56)>>2],e[f+15]=O[d+(4*f+60)>>2];else e=O.subarray(d>>2,d+64*b>>2);p.uniformMatrix4fv(n.mc[a],!!c,e)}},fb:function(a,b,c,d){n.oc.sc?p.uniformMatrix4x2fv(n.mc[a],!!c,O,d>>2,8*b):p.uniformMatrix4x2fv(n.mc[a],!!c,O.subarray(d>>2,d+32*b>>2))},eb:function(a,b,c,d){n.oc.sc?
p.uniformMatrix4x3fv(n.mc[a],!!c,O,d>>2,12*b):p.uniformMatrix4x3fv(n.mc[a],!!c,O.subarray(d>>2,d+48*b>>2))},db:function(a){p.useProgram(n.yc[a])},cb:function(a,b){p.vertexAttribDivisor(a,b)},bb:function(a,b,c,d,e){p.vertexAttribIPointer(a,b,c,d,e)},ab:function(a,b,c,d,e,f){p.vertexAttribPointer(a,b,c,!!d,e,f)},$a:function(a,b,c,d){p.viewport(a,b,c,d)},h:function(a){var b=wc.Bc[a];wc.Bc.splice(a,1);Ic(b)},g:wc,Za:function(){C("trap!")},Ya:function(){return 0},Xa:function(a,b,c,d){return Dc(a,b,c,d)},
Wa:lc,a:ia},buffer);r.asm=Jc;var db=r.__GLOBAL__sub_I_driverSpecific_cpp=function(){return r.asm.Wb.apply(null,arguments)},fb=r.__GLOBAL__sub_I_iostream_cpp=function(){return r.asm.Xb.apply(null,arguments)},cb=r.__GLOBAL__sub_I_resource_Picking_RESOURCES_cpp=function(){return r.asm.Yb.apply(null,arguments)},Gc=r.__ZSt18uncaught_exceptionv=function(){return r.asm.Zb.apply(null,arguments)},eb=r.___emscripten_environ_constructor=function(){return r.asm._b.apply(null,arguments)};
r.___errno_location=function(){return r.asm.$b.apply(null,arguments)};var bc=r._free=function(){return r.asm.ac.apply(null,arguments)};r._main=function(){return r.asm.bc.apply(null,arguments)};
var G=r._malloc=function(){return r.asm.cc.apply(null,arguments)},cc=r._memcpy=function(){return r.asm.dc.apply(null,arguments)},Fc=r._memset=function(){return r.asm.ec.apply(null,arguments)},ua=r.stackAlloc=function(){return r.asm.ic.apply(null,arguments)},Ic=r.stackRestore=function(){return r.asm.jc.apply(null,arguments)},xc=r.stackSave=function(){return r.asm.kc.apply(null,arguments)};r.dynCall_iii=function(){return r.asm.fc.apply(null,arguments)};
r.dynCall_v=function(){return r.asm.gc.apply(null,arguments)};r.dynCall_vi=function(){return r.asm.hc.apply(null,arguments)};r.asm=Jc;function A(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}A.prototype=Error();A.prototype.constructor=A;Sa=function Kc(){r.calledRun||Lc();r.calledRun||(Sa=Kc)};
r.callMain=function(a){a=a||[];Fa();var b=a.length+1,c=ua(4*(b+1));E[c>>2]=ta(r.thisProgram);for(var d=1;d<b;d++)E[(c>>2)+d]=ta(a[d-1]);E[(c>>2)+b]=0;try{var e=r._main(b,c,0);Hc(e,!0)}catch(f){f instanceof A||("SimulateInfiniteLoop"==f?r.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),D("exception thrown: "+a),r.quit(1,f)))}finally{}};
function Lc(a){function b(){if(!r.calledRun&&(r.calledRun=!0,!F)){Fa();Eb=!1;za(Ca);if(r.onRuntimeInitialized)r.onRuntimeInitialized();r._main&&Mc&&r.callMain(a);if(r.postRun)for("function"==typeof r.postRun&&(r.postRun=[r.postRun]);r.postRun.length;){var b=r.postRun.shift();Da.unshift(b)}za(Da)}}a=a||r.arguments;if(!(0<Qa)){if(r.preRun)for("function"==typeof r.preRun&&(r.preRun=[r.preRun]);r.preRun.length;)La();za(Aa);0<Qa||r.calledRun||(r.setStatus?(r.setStatus("Running..."),setTimeout(function(){setTimeout(function(){r.setStatus("")},
1);b()},1)):b())}}r.run=Lc;function Hc(a,b){if(!b||!r.noExitRuntime||0!==a){if(!r.noExitRuntime&&(F=!0,r.onExit))r.onExit(a);r.quit(a,new A(a))}}function C(a){if(r.onAbort)r.onAbort(a);void 0!==a?(fa(a),D(a),a=JSON.stringify(a)):a="";F=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}r.abort=C;if(r.preInit)for("function"==typeof r.preInit&&(r.preInit=[r.preInit]);0<r.preInit.length;)r.preInit.pop()();var Mc=!0;r.noInitialRun&&(Mc=!1);r.noExitRuntime=!0;Lc();
