var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),l,na=!1,oa,la=a=>a.startsWith("file://"),pa,m,n,qa,r,t,u,ra,sa;
function ta(a){g.onAbort?.(a);a="Aborted("+a+")";k(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;async function va(a){if(!l)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&l)a=new Uint8Array(l);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}async function xa(a){var b=ua;if(!l&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return wa(b,a)}
class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var za=a=>{for(;0<a.length;)a.shift()(g)},Aa=[],Ba=[],Ca=()=>{var a=g.preRun.shift();Ba.push(a)},w=0,x=null,Da=!0;class Ea{constructor(a){this.Ua=a-24}}
var Fa=0,Ga=0,Ha=0,B={},Ia=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ja=a=>{oa=a;Da||0<Ha||(g.onExit?.(a),na=!0);fa(a,new ya(a))},Ka=a=>{oa=a;Ja(a)},La=a=>{if(!na)try{if(a(),!(Da||0<Ha))try{oa=a=oa,Ja(a)}catch(b){Ia(b)}}catch(b){Ia(b)}},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>
6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;f++}}b[c]=0;return c-e},D=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ma="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=
String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Na=[],G=12288,Oa=0,H={alpha:!1,depth:!1,stencil:!1,antialias:!1},I,J,Pa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,
d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},Qa=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ra=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Sa=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ta=1,Ua=[],Va=[],Xa=[],Ya=[],Za=[],$a=[],ab=[],L=[],bb=[],cb={},db=4,eb=0,fb=a=>{for(var b=Ta++,c=a.length;c<b;c++)a[c]=null;return b},N=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=J[c](),h=f&&fb(d);f?(f.name=h,d[h]=f):M||=1282;r[b+4*e>>2]=h}},hb=()=>{var a=g.canvas;a.Ma||(a.Ma=a.getContext,a.getContext=function(c,d){d=a.Ma(c,d);return"webgl"==c==d instanceof WebGLRenderingContext?d:null});var b=a.getContext("webgl",H);return b?gb(b):0},
gb=a=>{var b=fb(L),c={handle:b,attributes:H,version:H.qb,Na:a};a.canvas&&(a.canvas.kb=c);L[b]=c;("undefined"==typeof H.mb||H.mb)&&ib(c);return b},jb=a=>{O=L[a];g.ctx=J=O?.Na},ib=a=>{a||=O;if(!a.pb){a.pb=!0;var b=a.Na;b.Ra=b.getExtension("WEBGL_multi_draw");b.ob=b.getExtension("EXT_polygon_offset_clamp");b.nb=b.getExtension("EXT_clip_control");b.jb=b.getExtension("WEBGL_polygon_mode");Pa(b);Qa(b);Ra(b);b.lb=b.getExtension("EXT_disjoint_timer_query");Sa(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},M,O,kb=[],lb={},nb=()=>{if(!mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in lb)void 0===lb[b]?delete a[b]:a[b]=lb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mb=c}return mb},mb,ob=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");
return a},pb=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=ob(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},qb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},rb=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},sb=a=>{(sb=rb())(a)},tb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=
0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=ob(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ub=[],vb=[];function wb(a,b){vb[a]={input:[],output:[],Pa:b};xb(a,yb)}
var yb={open(a){var b=vb[a.node.rdev];if(!b)throw new P(43);a.tty=b;a.seekable=!1},close(a){a.tty.Pa.fsync(a.tty)},fsync(a){a.tty.Pa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Pa.eb)throw new P(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Pa.eb(a.tty)}catch(q){throw new P(29);}if(void 0===h&&0===e)throw new P(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Pa.bb)throw new P(60);try{for(var e=0;e<d;e++)a.tty.Pa.bb(a.tty,b[c+e])}catch(f){throw new P(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},zb={eb(){a:{if(!ub.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(D(a)+1);a=C(a,b,0,b.length);b.length=a;ub=b}a=ub.shift()}return a},bb(a,b){null===
b||10===b?(ma(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(F(a.output)),a.output=[])},Cb(){return{xb:25856,zb:5,wb:191,yb:35387,vb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Db(){return 0},Eb(){return[24,80]}},Ab={bb(a,b){null===b||10===b?(k(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(F(a.output)),a.output=[])}},Q={Ia:null,Ka(){return Q.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new P(63);Q.Ia||(Q.Ia={dir:{node:{La:Q.Ea.La,Ja:Q.Ea.Ja,lookup:Q.Ea.lookup,Sa:Q.Ea.Sa,rename:Q.Ea.rename,unlink:Q.Ea.unlink,rmdir:Q.Ea.rmdir,readdir:Q.Ea.readdir,symlink:Q.Ea.symlink},stream:{Ha:Q.Fa.Ha}},file:{node:{La:Q.Ea.La,Ja:Q.Ea.Ja},stream:{Ha:Q.Fa.Ha,read:Q.Fa.read,write:Q.Fa.write,gb:Q.Fa.gb,ib:Q.Fa.ib}},link:{node:{La:Q.Ea.La,Ja:Q.Ea.Ja,readlink:Q.Ea.readlink},stream:{}},cb:{node:{La:Q.Ea.La,Ja:Q.Ea.Ja},stream:Bb}});c=Cb(a,b,c,d);16384===(c.mode&61440)?
(c.Ea=Q.Ia.dir.node,c.Fa=Q.Ia.dir.stream,c.Da={}):32768===(c.mode&61440)?(c.Ea=Q.Ia.file.node,c.Fa=Q.Ia.file.stream,c.Ga=0,c.Da=null):40960===(c.mode&61440)?(c.Ea=Q.Ia.link.node,c.Fa=Q.Ia.link.stream):8192===(c.mode&61440)&&(c.Ea=Q.Ia.cb.node,c.Fa=Q.Ia.cb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Da[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Bb(a){return a.Da?a.Da.subarray?a.Da.subarray(0,a.Ga):new Uint8Array(a.Da):new Uint8Array(0)},Ea:{La(a){var b={};b.dev=8192===(a.mode&61440)?a.id:
1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ga:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ja(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Ga!=b&&(0==b?(a.Da=null,a.Ga=0):(c=a.Da,a.Da=new Uint8Array(b),c&&
a.Da.set(c.subarray(0,Math.min(b,a.Ga))),a.Ga=b)))},lookup(){Q.Va||(Q.Va=new P(44),Q.Va.stack="<generic error, no stack>");throw Q.Va;},Sa(a,b,c,d){return Q.createNode(a,b,c,d)},rename(a,b,c){try{var d=Db(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.Da)throw new P(55);e=Eb(d.parent.id,d.name);if(R[e]===d)R[e]=d.Oa;else for(e=R[e];e;){if(e.Oa===d){e.Oa=d.Oa;break}e=e.Oa}}delete a.parent.Da[a.name];b.Da[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,
b){delete a.Da[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Db(a,b),d;for(d in c.Da)throw new P(55);delete a.Da[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Da)]},symlink(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},Fa:{read(a,b,c,d,e){var f=a.node.Da;if(e>=a.node.Ga)return 0;a=Math.min(a.node.Ga-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},
write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Da||a.Da.subarray)){if(f)return a.Da=b.subarray(c,c+d),a.Ga=d;if(0===a.Ga&&0===e)return a.Da=b.slice(c,c+d),a.Ga=d;if(e+d<=a.Ga)return a.Da.set(b.subarray(c,c+d),e),d}f=e+d;var h=a.Da?a.Da.length:0;h>=f||(f=Math.max(f,h*(1048576>h?2:1.125)>>>0),0!=h&&(f=Math.max(f,256)),h=a.Da,a.Da=new Uint8Array(f),0<a.Ga&&a.Da.set(h.subarray(0,a.Ga),0));if(a.Da.subarray&&b.subarray)a.Da.set(b.subarray(c,c+d),e);else for(f=0;f<
d;f++)a.Da[e+f]=b[c+f];a.Ga=Math.max(a.Ga,e+d);return d},Ha(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ga);if(0>b)throw new P(28);return b},gb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.Da;if(e&2||!a||a.buffer!==m.buffer){d=!0;ta();e=void 0;if(!e)throw new P(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{Ua:e,ub:d}},ib(a,b,c,d){Q.Fa.write(a,b,0,d,
c,!1);return 0}}},Fb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Gb=null,Hb={},S=[],Ib=1,R=null,Jb=!1,Kb=!0,Lb={},P=class{name="ErrnoError";constructor(a){this.Qa=a}},Mb=class{Ma={};node=null;get flags(){return this.Ma.flags}set flags(a){this.Ma.flags=a}get position(){return this.Ma.position}set position(a){this.Ma.position=a}},Nb=class{Ea={};Fa={};Ta=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Ka=a.Ka;this.id=Ib++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=
Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function T(a,b={}){if(!a)throw new P(44);b.Xa??(b.Xa=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(q=>!!q);for(var d=Gb,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=qb(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=pb(e+"/"+a[f]);try{d=Db(d,a[f])}catch(q){if(44===q?.Qa&&h&&b.sb)return{path:e};throw q;}!d.Ta||h&&!b.Xa||(d=d.Ta.root);if(40960===(d.mode&61440)&&(!h||b.Wa)){if(!d.Ea.readlink)throw new P(52);
d=d.Ea.readlink(d);"/"===d.charAt(0)||(d=qb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new P(32);}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function Db(a,b){var c=16384===(a.mode&61440)?(c=Ob(a,"x"))?c:a.Ea.lookup?0:2:54;if(c)throw new P(c);for(c=R[Eb(a.id,b)];c;c=c.Oa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ea.lookup(a,b)}
function Cb(a,b,c,d){a=new Nb(a,b,c,d);b=Eb(a.parent.id,a.name);a.Oa=R[b];return R[b]=a}function Pb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ob(a,b){if(Kb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Qb(a,b){if(16384!==(a.mode&61440))return 54;try{return Db(a,b),20}catch(c){}return Ob(a,"wx")}function U(a){a=S[a];if(!a)throw new P(8);return a}
function Rb(a,b){var c=null?.Fa.Ja,d=c?null:a;c??=a.Ea.Ja;if(!c)throw new P(63);c(d,b)}var Bb={open(a){a.Fa=Hb[a.node.rdev].Fa;a.Fa.open?.(a)},Ha(){throw new P(70);}};function xb(a,b){Hb[a]={Fa:b}}function Sb(a,b){var c="/"===b;if(c&&Gb)throw new P(10);if(!c&&b){var d=T(b,{Xa:!1});b=d.path;d=d.node;if(d.Ta)throw new P(10);if(16384!==(d.mode&61440))throw new P(54);}b={type:a,Hb:{},hb:b,rb:[]};a=a.Ka(b);a.Ka=b;b.root=a;c?Gb=a:d&&(d.Ta=b,d.Ka&&d.Ka.rb.push(b))}
function Tb(a,b,c){var d=T(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new P(28);if("."===a||".."===a)throw new P(20);var e=Qb(d,a);if(e)throw new P(e);if(!d.Ea.Sa)throw new P(63);return d.Ea.Sa(d,a,b,c)}function V(a){return Tb(a,16895,0)}function Ub(a,b,c){"undefined"==typeof c&&(c=b,b=438);Tb(a,b|8192,c)}
function Vb(a,b){if(!tb(a))throw new P(44);var c=T(b,{parent:!0}).node;if(!c)throw new P(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Qb(c,b);if(d)throw new P(d);if(!c.Ea.symlink)throw new P(63);c.Ea.symlink(c,b,a)}
function Wb(a,b){if(""===a)throw new P(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=T(a,{Wa:!(b&131072),sb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new P(20);}else{if(e)throw new P(31);d=Tb(a,c|511,0);f=!0}if(!d)throw new P(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new P(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Pb(b)||b&576)?31:Ob(d,Pb(b)):44))throw new P(e);if(b&512&&!f){e=d;e="string"==typeof e?T(e,{Wa:!0}).node:e;if(16384===(e.mode&61440))throw new P(31);if(32768!==(e.mode&61440))throw new P(28);var h=Ob(e,"w");if(h)throw new P(h);Rb(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.Ka.hb;var q=q?"/"!==e[e.length-1]?`${e}/${q}`:e+q:e;break a}q=q?`${e.name}/${q}`:e.name;e=e.parent}q={node:d,path:q,flags:b,
seekable:!0,position:0,Fa:d.Fa,tb:[],error:!1};e=-1;q=Object.assign(new Mb,q);if(-1==e)a:{for(e=0;4096>=e;e++)if(!S[e])break a;throw new P(33);}q.fd=e;S[e]=q;q.Fa.open&&q.Fa.open(q);f&&(c&=511,d="string"==typeof d?T(d,{Wa:!0}).node:d,Rb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Ab:void 0}));!g.logReadFiles||b&1||a in Lb||(Lb[a]=1)}function Xb(a,b,c){if(null===a.fd)throw new P(8);if(!a.seekable||!a.Fa.Ha)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.Fa.Ha(a,b,c);a.tb=[]}
function W(a,b,c){a=pb("/dev/"+a);var d=Fb(!!b,!!c);W.fb??(W.fb=64);var e=W.fb++<<8|0;xb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,h,q,v){for(var p=0,y=0;y<v;y++){try{var z=b()}catch(A){throw new P(29);}if(void 0===z&&0===p)throw new P(6);if(null===z||void 0===z)break;p++;h[q+y]=z}p&&(f.node.atime=Date.now());return p},write(f,h,q,v){for(var p=0;p<v;p++)try{c(h[q+p])}catch(y){throw new P(29);}v&&(f.node.mtime=f.node.ctime=Date.now());return p}});Ub(a,d,e)}
var Yb={},Zb=[],$b=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(M||=1280);return;case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":M||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:M||=1280;return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){M||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:M||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=
d;t[b>>2]=c;t[b+4>>2]=(c-t[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:m[b]=d?1:0}}else M||=1281},bc=a=>{var b=D(a)+1,c=ac(b);c&&C(a,n,c,b);return c},cc=()=>{var a=Sa(J);return a=a.concat(a.map(b=>"GL_"+b))},dc=(a,b,c,d,e)=>{a-=5120;a=1==a?n:4==a?r:6==a?u:5==a||28922==a?t:qa;b=d*((eb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+db-1&-db);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))};R=Array(4096);
Sb(Q,"/");V("/tmp");V("/home");V("/home/web_user");(function(){V("/dev");xb(259,{read:()=>0,write:(d,e,f,h)=>h,Ha:()=>0});Ub("/dev/null",259);wb(1280,zb);wb(1536,Ab);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(sb(a),b=a.byteLength);return a[--b]};W("random",c);W("urandom",c);V("/dev/shm");V("/dev/shm/tmp")})();
(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");Sb({Ka(){var b=Cb(a,"fd",16895,73);b.Fa={Ha:Q.Fa.Ha};b.Ea={lookup(c,d){c=+d;var e=U(c);c={parent:null,Ka:{hb:"fake"},Ea:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(S.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();for(let a=0;32>a;++a)Zb.push(Array(a));g.noExitRuntime&&(Da=g.noExitRuntime);g.print&&(ma=g.print);g.printErr&&(k=g.printErr);g.wasmBinary&&(l=g.wasmBinary);
g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var ec={33040:()=>{var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},33142:()=>{var a=g.canvas.getContext("webgl").getExtension("WEBGL_compressed_texture_astc").getSupportedProfiles();return(0<=a.indexOf("ldr")?1:0)|(0<=a.indexOf("hdr")?2:0)}},fc,ac,gc,hc,ic={E:(a,b,c)=>{var d=new Ea(a);t[d.Ua+16>>2]=0;t[d.Ua+4>>2]=b;t[d.Ua+8>>2]=c;Fa=a;Ga++;throw Fa;},z:()=>ta(""),s:()=>{Da=!1;Ha=0},t:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];
La(()=>gc(a,performance.now()))},b);B[a]={id:c,Jb:b};return 0},D:function(a,b){a=a?F(n,a,b):"";if("undefined"!==typeof process&&a in process.env){a=process.env[a];b=D(a)+1;var c=ac(b);C(a,n,c,b);return c}return 0},H:a=>{if(12448==a)return G=12288,1;G=12300;return 0},G:(a,b,c,d,e)=>{if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=r[b>>2];if(12321==a)H.alpha=0<r[b+4>>2];else if(12325==a)H.depth=0<r[b+4>>2];else if(12326==a)H.stencil=0<r[b+4>>2];else if(12337==a)a=r[b+4>>2],H.antialias=0<a;else if(12338==
a)a=r[b+4>>2],H.antialias=1==a;else if(12544==a)H.Fb=12547!=r[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(r[e>>2]=1),c&&0<d&&(t[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c},F:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;for(a=1;;){b=r[d>>2];if(12440==b)a=r[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2!=a)return G=12293,0;H.qb=a-1;H.Gb=0;I=hb();if(0!=I)return G=12288,jb(I),Na.forEach(e=>e()),jb(null),62004;G=12297;return 0},i:(a,b)=>{if(62E3!=a)return G=12296,0;if(62004!=b)return G=
12294,0;a=I;O===L[a]&&(O=null);"object"==typeof JSEvents&&JSEvents.Ib(L[a].Na.canvas);L[a]?.Na.canvas&&(L[a].Na.canvas.kb=void 0);L[a]=null;G=12288;Oa==b&&(Oa=0);return 1},K:a=>{G=12288;return 0!=a&&1!=a?0:62E3},c:()=>G,I:(a,b,c)=>{if(62E3!=a)return G=12296,0;b&&(r[b>>2]=1);c&&(r[c>>2]=4);G=12288;return 1},e:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;jb(d?I:null);Oa=d;G=12288;return 1},h:a=>{if(62E3!=a)return G=12296,
0;Oa=0;G=12288;return 1},m:(a,b,c)=>{kb.length=0;for(var d;d=n[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;kb.push(112==d?t[c>>2]:106==d?sa[c>>3]:105==d?r[c>>2]:ra[c>>3]);c+=e?8:4}return ec[a](...kb)},u:()=>{ta("OOM")},ha:(a,b)=>{a=L[a];b=b?F(n,b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&Pa(J);"OES_vertex_array_object"==b&&Qa(J);"WEBGL_draw_buffers"==b&&Ra(J);"WEBGL_multi_draw"==b&&(J.Ra=J.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(J.ob=J.getExtension("EXT_polygon_offset_clamp"));
"EXT_clip_control"==b&&(J.nb=J.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(J.jb=J.getExtension("WEBGL_polygon_mode"));return!!a.Na.getExtension(b)},ga:()=>O?O.handle:0,A:(a,b)=>{var c=0,d=0,e;for(e of nb()){var f=b+c;t[a+d>>2]=f;c+=C(e,n,f,Infinity)+1;d+=4}return 0},C:(a,b)=>{var c=nb();t[a>>2]=c.length;a=0;for(var d of c)a+=D(d)+1;t[b>>2]=a;return 0},g:Ka,y:function(a){try{var b=U(a);if(null===b.fd)throw new P(8);b.Ya&&(b.Ya=null);try{b.Fa.close&&b.Fa.close(b)}catch(c){throw c;}finally{S[b.fd]=
null}b.fd=null;return 0}catch(c){if("undefined"==typeof Yb||"ErrnoError"!==c.name)throw c;return c.Qa}},x:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var f,h=b=0;h<c;h++){var q=t[a>>2],v=t[a+4>>2];a+=8;var p=e,y=q,z=v,A=f,Wa=m;if(0>z||0>A)throw new P(28);if(null===p.fd)throw new P(8);if(1===(p.flags&2097155))throw new P(8);if(16384===(p.node.mode&61440))throw new P(31);if(!p.Fa.read)throw new P(28);var X="undefined"!=typeof A;if(!X)A=p.position;else if(!p.seekable)throw new P(70);var Y=p.Fa.read(p,
Wa,y,z,A);X||(p.position+=Y);var E=Y;if(0>E){var Z=-1;break a}b+=E;if(E<v)break;"undefined"!=typeof f&&(f+=E)}Z=b}t[d>>2]=Z;return 0}catch(K){if("undefined"==typeof Yb||"ErrnoError"!==K.name)throw K;return K.Qa}},v:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=U(a);Xb(e,b,c);sa[d>>3]=BigInt(e.position);e.Ya&&0===b&&0===c&&(e.Ya=null);return 0}catch(f){if("undefined"==typeof Yb||"ErrnoError"!==f.name)throw f;return f.Qa}},w:function(a,b,c,
d){try{a:{var e=U(a);a=b;for(var f,h=b=0;h<c;h++){var q=t[a>>2],v=t[a+4>>2];a+=8;var p=e,y=q,z=v,A=f,Wa=m;if(0>z||0>A)throw new P(28);if(null===p.fd)throw new P(8);if(0===(p.flags&2097155))throw new P(8);if(16384===(p.node.mode&61440))throw new P(31);if(!p.Fa.write)throw new P(28);p.seekable&&p.flags&1024&&Xb(p,0,2);var X="undefined"!=typeof A;if(!X)A=p.position;else if(!p.seekable)throw new P(70);var Y=p.Fa.write(p,Wa,y,z,A,void 0);X||(p.position+=Y);var E=Y;if(0>E){var Z=-1;break a}b+=E;if(E<v)break;
"undefined"!=typeof f&&(f+=E)}Z=b}t[d>>2]=Z;return 0}catch(K){if("undefined"==typeof Yb||"ErrnoError"!==K.name)throw K;return K.Qa}},f:a=>J.activeTexture(a),n:(a,b)=>{J.bindBuffer(a,Ua[b])},ea:(a,b)=>{J.bindFramebuffer(a,Xa[b])},r:(a,b)=>{J.bindRenderbuffer(a,Ya[b])},l:(a,b)=>{J.bindTexture(a,Za[b])},d:a=>{J.bindVertexArray(ab[a])},sa:(a,b,c,d)=>{J.bufferData(a,c?n.subarray(c,c+b):b,d)},ra:(a,b,c,d)=>{J.bufferSubData(a,b,n.subarray(d,d+c))},da:a=>J.checkFramebufferStatus(a),wa:(a,b,c,d)=>J.clearColor(a,
b,c,d),O:a=>J.clearDepth(a),aa:(a,b,c,d,e,f,h,q)=>J.copyTexSubImage2D(a,b,c,d,e,f,h,q),ua:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Ua[d];e&&(J.deleteBuffer(e),e.name=0,Ua[d]=null)}},S:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];J.deleteVertexArray(ab[d]);ab[d]=null}},N:(a,b)=>J.depthRange(a,b),P:a=>{J.disableVertexAttribArray(a)},V:(a,b,c)=>{J.drawArrays(a,b,c)},ma:(a,b,c,d)=>{J.drawArraysInstanced(a,b,c,d)},ca:(a,b)=>{for(var c=Zb[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];J.drawBuffers(c)},U:(a,
b,c,d)=>{J.drawElements(a,b,c,d)},la:(a,b,c,d,e)=>{J.drawElementsInstanced(a,b,c,d,e)},k:a=>{J.enableVertexAttribArray(a)},R:(a,b,c,d)=>{J.framebufferRenderbuffer(a,b,c,Ya[d])},J:(a,b,c,d,e)=>{J.framebufferTexture2D(a,b,c,Za[d],e)},va:(a,b)=>{N(a,b,"createBuffer",Ua)},Y:(a,b)=>{N(a,b,"createFramebuffer",Xa)},ja:(a,b)=>{for(var c=0;c<a;c++){var d=J.lb.createQueryEXT();if(!d){for(M||=1282;c<a;)r[b+4*c++>>2]=0;break}var e=fb(bb);d.name=e;bb[e]=d;r[b+4*c>>2]=e}},B:(a,b)=>{N(a,b,"createRenderbuffer",Ya)},
$:(a,b)=>{N(a,b,"createTexture",Za)},T:(a,b)=>{N(a,b,"createVertexArray",ab)},_:a=>J.generateMipmap(a),ta:(a,b,c)=>{c?r[c>>2]=J.getBufferParameter(a,b):M||=1281},fa:()=>{var a=J.getError()||M;M=0;return a},o:(a,b)=>$b(a,b,2),a:(a,b)=>$b(a,b,0),ka:(a,b,c)=>{if(c)if(a>=Ta)M||=1281;else if(a=Va[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.ab){var d=J.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ab=Math.max(a.ab,J.getActiveUniform(a,
b).name.length+1)}r[c>>2]=a.ab}else if(35722==b){if(!a.Za)for(d=J.getProgramParameter(a,35721),b=0;b<d;++b)a.Za=Math.max(a.Za,J.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Za}else if(35381==b){if(!a.$a)for(d=J.getProgramParameter(a,35382),b=0;b<d;++b)a.$a=Math.max(a.$a,J.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.$a}else r[c>>2]=J.getProgramParameter(a,b);else M||=1281},ia:(a,b,c)=>{c?35716==b?(a=J.getShaderInfoLog($a[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?
(a=J.getShaderSource($a[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=J.getShaderParameter($a[a],b):M||=1281},b:a=>{var b=cb[a];if(!b){switch(a){case 7939:b=bc(cc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||(M||=1280);b=b?bc(b):0;break;case 7938:b=bc(`OpenGL ES 2.0 (${J.getParameter(7938)})`);break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);
b=bc(b);break;default:M||=1280}cb[a]=b}return b},qa:(a,b,c,d)=>{J.Ra.multiDrawArraysWEBGL(a,r,b>>2,r,c>>2,d)},oa:(a,b,c,d,e)=>{J.Ra.multiDrawArraysInstancedWEBGL(a,r,b>>2,r,c>>2,r,d>>2,e)},pa:(a,b,c,d,e)=>{J.Ra.multiDrawElementsWEBGL(a,r,b>>2,c,r,d>>2,e)},na:(a,b,c,d,e,f)=>{J.Ra.multiDrawElementsInstancedWEBGL(a,r,b>>2,c,r,d>>2,r,e>>2,f)},L:(a,b)=>{3317==a?db=b:3314==a&&(eb=b);J.pixelStorei(a,b)},M:(a,b)=>{J.jb.polygonModeWEBGL(a,b)},ba:(a,b,c,d,e,f,h)=>{(h=dc(f,e,c,d,h))?J.readPixels(a,b,c,d,e,f,
h):M||=1280},p:(a,b,c,d)=>J.renderbufferStorage(a,b,c,d),W:(a,b,c,d,e,f,h,q,v)=>{v=v?dc(q,h,d,e,v):null;J.texImage2D(a,b,c,d,e,f,h,q,v)},X:(a,b,c)=>{J.texParameterf(a,b,u[c>>2])},Z:(a,b,c)=>J.texParameteri(a,b,c),Q:(a,b)=>{J.vertexAttribDivisor(a,b)},j:(a,b,c,d,e,f)=>{J.vertexAttribPointer(a,b,c,!!d,e,f)},q:Ja};
function jc(a=[]){var b=fc;a.unshift(ea);var c=a.length,d=hc(4*(c+1)),e=d;a.forEach(h=>{var q=t,v=e>>2,p=D(h)+1,y=hc(p);C(h,n,y,p);q[v]=y;e+=4});t[e>>2]=0;try{var f=b(c,d);Ka(f,!0)}catch(h){Ia(h)}}
function kc(a=da){function b(){g.calledRun=!0;if(!na){if(!g.noFSInit&&!Jb){var c,d;Jb=!0;c??=g.stdin;d??=g.stdout;e??=g.stderr;c?W("stdin",c):Vb("/dev/tty","/dev/stdin");d?W("stdout",null,d):Vb("/dev/tty","/dev/stdout");e?W("stderr",null,e):Vb("/dev/tty1","/dev/stderr");Wb("/dev/stdin",0);Wb("/dev/stdout",1);Wb("/dev/stderr",1)}lc.ya();Kb=!1;g.onRuntimeInitialized?.();g.noInitialRun||jc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var e=g.postRun.shift();
Aa.push(e)}za(Aa)}}if(0<w)x=kc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ca();za(Ba);0<w?x=kc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var lc;
(async function(){function a(c){lc=c.exports;pa=lc.xa;c=pa.buffer;m=new Int8Array(c);new Int16Array(c);n=new Uint8Array(c);qa=new Uint16Array(c);r=new Int32Array(c);t=new Uint32Array(c);u=new Float32Array(c);ra=new Float64Array(c);sa=new BigInt64Array(c);new BigUint64Array(c);c=lc;g._main=fc=c.za;ac=c.Aa;gc=c.Ba;hc=c.Ca;w--;g.monitorRunDependencies?.(w);0==w&&x&&(c=x,x=null,c());return lc}w++;g.monitorRunDependencies?.(w);var b={a:ic};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,
(d,e)=>{c(a(d,e))})});ua??=g.locateFile?g.locateFile("magnum-gl-info.wasm",ia):ia+"magnum-gl-info.wasm";return a((await xa(b)).instance)})();kc();
