
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in g)g.hasOwnProperty(k)&&(aa[k]=g[k]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,m=!1,fa=!1,ha=!1;ea="object"===typeof window;m="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!m;var n="",ia,ja,ka,la;
if(fa)n=m?require("path").dirname(n)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
r),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||m)m?n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),u=g.printErr||console.warn.bind(console);for(k in aa)aa.hasOwnProperty(k)&&(g[k]=aa[k]);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function oa(a){pa||(pa={});pa[a]||(pa[a]=1,u(a))}var pa,qa;g.wasmBinary&&(qa=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&u("no native wasm support detected");
var ra,sa=new WebAssembly.Table({initial:612,maximum:612,element:"anyfunc"}),ta=!1;function assert(a,b){a||r("Assertion failed: "+b)}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function va(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ua)return ua.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function wa(a,b){return a?va(w,a,b):""}
function xa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var p=a.charCodeAt(++f);h=65536+((h&1023)<<10)|p&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function ya(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function za(a){var b=ya(a)+1,c=Aa(b);xa(a,x,c,b);return c}var Ba,x,w,Ca,A,Da,C,Ea,Fa=g.INITIAL_MEMORY||16777216;g.wasmMemory?ra=g.wasmMemory:ra=new WebAssembly.Memory({initial:Fa/65536,maximum:Fa/65536});ra&&(Ba=ra.buffer);Fa=Ba.byteLength;var D=Ba;Ba=D;g.HEAP8=x=new Int8Array(D);g.HEAP16=new Int16Array(D);
g.HEAP32=A=new Int32Array(D);g.HEAPU8=w=new Uint8Array(D);g.HEAPU16=Ca=new Uint16Array(D);g.HEAPU32=Da=new Uint32Array(D);g.HEAPF32=C=new Float32Array(D);g.HEAPF64=Ea=new Float64Array(D);A[9708]=5281872;function Ga(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.te;"number"===typeof c?void 0===b.ce?g.dynCall_v(c):g.dynCall_vi(c,b.ce):c(void 0===b.ce?null:b.ce)}}}var Ha=[],Ia=[],Ja=[],Ka=[];function La(){var a=g.preRun.shift();Ha.unshift(a)}
var Ma=Math.abs,Na=Math.ceil,Oa=Math.floor,Pa=Math.min,Qa=0,Ra=null,Sa=null;g.preloadedImages={};g.preloadedAudios={};function r(a){if(g.onAbort)g.onAbort(a);na(a);u(a);ta=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ta(a){var b=Ua;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Va(){return Ta("data:application/octet-stream;base64,")}var Ua="magnum-gl-info.wasm";
if(!Va()){var Wa=Ua;Ua=g.locateFile?g.locateFile(Wa,n):n+Wa}function Xa(){try{if(qa)return new Uint8Array(qa);if(ja)return ja(Ua);throw"both async and sync fetching of the wasm failed";}catch(a){r(a)}}function Ya(){return qa||!ea&&!m||"function"!==typeof fetch||Ta("file://")?new Promise(function(a){a(Xa())}):fetch(Ua,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ua+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}
var Za,$a,cb={13082:function(a){a=wa(a);if("undefined"!==typeof process&&a in process.env){var b=ab(process.env[a]);if("number"===typeof b){var c=!0;a=b}else c=!1,a=b.length;var d=bb(Math.max(a,1));if(c){b=d;assert(0==(d&3));for(c=d+(a&-4);b<c;b+=4)A[b>>2]=0;for(c=d+a;b<c;)x[b++>>0]=0}else b.subarray||b.slice?w.set(b,d):w.set(new Uint8Array(b),d);a=d}else a=0;return a}};Ia.push({te:function(){db()}});function eb(){return 0<eb.be}
function fb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function gb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],Wd:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new E(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Wd.flush(a.tty)},flush:function(a){a.tty.Wd.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Wd.ue)throw new E(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Wd.ue(a.tty)}catch(p){throw new E(29);}if(void 0===h&&0===e)throw new E(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Wd.me)throw new E(60);
try{for(var e=0;e<d;e++)a.tty.Wd.me(a.tty,b[c+e])}catch(f){throw new E(29);}d&&(a.node.timestamp=Date.now());return e}},ob={ue:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.be?Buffer.be(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ab(b,!0)}return a.input.shift()},me:function(a,b){null===b||10===b?(na(va(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(va(a.output,0)),a.output=[])}},pb={me:function(a,b){null===b||10===b?(u(va(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(u(va(a.output,0)),a.output=[])}},G={Qd:null,Sd:function(){return G.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(63);G.Qd||(G.Qd={dir:{node:{Td:G.Ld.Td,Rd:G.Ld.Rd,lookup:G.Ld.lookup,de:G.Ld.de,rename:G.Ld.rename,unlink:G.Ld.unlink,rmdir:G.Ld.rmdir,readdir:G.Ld.readdir,symlink:G.Ld.symlink},stream:{Ud:G.Md.Ud}},file:{node:{Td:G.Ld.Td,Rd:G.Ld.Rd},stream:{Ud:G.Md.Ud,read:G.Md.read,write:G.Md.write,oe:G.Md.oe,we:G.Md.we,fe:G.Md.fe}},link:{node:{Td:G.Ld.Td,Rd:G.Ld.Rd,readlink:G.Ld.readlink},stream:{}},pe:{node:{Td:G.Ld.Td,
Rd:G.Ld.Rd},stream:qb}});c=rb(a,b,c,d);16384===(c.mode&61440)?(c.Ld=G.Qd.dir.node,c.Md=G.Qd.dir.stream,c.Kd={}):32768===(c.mode&61440)?(c.Ld=G.Qd.file.node,c.Md=G.Qd.file.stream,c.Nd=0,c.Kd=null):40960===(c.mode&61440)?(c.Ld=G.Qd.link.node,c.Md=G.Qd.link.stream):8192===(c.mode&61440)&&(c.Ld=G.Qd.pe.node,c.Md=G.Qd.pe.stream);c.timestamp=Date.now();a&&(a.Kd[b]=c);return c},Ue:function(a){if(a.Kd&&a.Kd.subarray){for(var b=[],c=0;c<a.Nd;++c)b.push(a.Kd[c]);return b}return a.Kd},Ve:function(a){return a.Kd?
a.Kd.subarray?a.Kd.subarray(0,a.Nd):new Uint8Array(a.Kd):new Uint8Array(0)},qe:function(a,b){var c=a.Kd?a.Kd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Kd,a.Kd=new Uint8Array(b),0<a.Nd&&a.Kd.set(c.subarray(0,a.Nd),0))},Je:function(a,b){if(a.Nd!=b)if(0==b)a.Kd=null,a.Nd=0;else{if(!a.Kd||a.Kd.subarray){var c=a.Kd;a.Kd=new Uint8Array(b);c&&a.Kd.set(c.subarray(0,Math.min(b,a.Nd)))}else if(a.Kd||(a.Kd=[]),a.Kd.length>b)a.Kd.length=b;else for(;a.Kd.length<b;)a.Kd.push(0);
a.Nd=b}},Ld:{Td:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Nd:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ce=4096;b.blocks=Math.ceil(b.size/b.Ce);return b},Rd:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&G.Je(a,b.size)},lookup:function(){throw sb[44];},de:function(a,b,c,d){return G.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tb(b,c)}catch(f){}if(d)for(var e in d.Kd)throw new E(55);}delete a.parent.Kd[a.name];a.name=c;b.Kd[c]=a;a.parent=b},unlink:function(a,b){delete a.Kd[b]},rmdir:function(a,b){var c=tb(a,b),d;for(d in c.Kd)throw new E(55);delete a.Kd[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Kd)a.Kd.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new E(28);return a.link}},Md:{read:function(a,b,c,d,e){var f=a.node.Kd;if(e>=a.node.Nd)return 0;a=Math.min(a.node.Nd-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Kd||a.Kd.subarray)){if(f)return a.Kd=b.subarray(c,c+d),a.Nd=d;if(0===a.Nd&&0===e)return a.Kd=
b.slice(c,c+d),a.Nd=d;if(e+d<=a.Nd)return a.Kd.set(b.subarray(c,c+d),e),d}G.qe(a,e+d);if(a.Kd.subarray&&b.subarray)a.Kd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Kd[e+f]=b[c+f];a.Nd=Math.max(a.Nd,e+d);return d},Ud:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Nd);if(0>b)throw new E(28);return b},oe:function(a,b,c){G.qe(a.node,b+c);a.node.Nd=Math.max(a.node.Nd,b+c)},we:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new E(43);a=a.node.Kd;
if(f&2||a.buffer!==Ba){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=bb(c);if(!c)throw new E(48);x.set(a,c)}else d=!1,c=a.byteOffset;return{df:c,Be:d}},fe:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new E(43);if(e&2)return 0;G.Md.write(a,b,0,d,c,!1);return 0}}},ub=null,vb={},wb=[],xb=1,yb=null,zb=!0,Ab={},E=null,sb={};
function Bb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={se:!0,ne:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ne)throw new E(32);a=fb(a.split("/").filter(function(h){return!!h}),!1);var e=ub;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=tb(e,a[d]);c=gb(c+"/"+a[d]);e.ee&&(!f||f&&b.se)&&(e=e.ee.root);if(!f||b.re)for(f=0;40960===(e.mode&61440);)if(e=Cb(c),c=jb(hb(c),e),e=Bb(c,{ne:b.ne}).node,40<f++)throw new E(32);}return{path:c,node:e}}
function Db(a){for(var b;;){if(a===a.parent)return a=a.Sd.xe,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yb.length}function tb(a,b){var c;if(c=(c=Fb(a,"x"))?c:a.Ld.lookup?0:2)throw new E(c,a);for(c=yb[Eb(a.id,b)];c;c=c.He){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ld.lookup(a,b)}
function rb(a,b,c,d){a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.He=yb[b];return yb[b]=a}var Hb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Fb(a,b){if(zb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Jb(a,b){try{return tb(a,b),20}catch(c){}return Fb(a,"wx")}function Kb(){var a=4096;for(var b=0;b<=a;b++)if(!wb[b])return b;throw new E(33);}function Lb(a){Mb||(Mb=function(){},Mb.prototype={});var b=new Mb,c;for(c in a)b[c]=a[c];a=b;b=Kb();a.fd=b;return wb[b]=a}var qb={open:function(a){a.Md=vb[a.node.rdev].Md;a.Md.open&&a.Md.open(a)},Ud:function(){throw new E(70);}};function mb(a,b){vb[a]={Md:b}}
function Nb(a,b){var c="/"===b,d=!b;if(c&&ub)throw new E(10);if(!c&&!d){var e=Bb(b,{se:!1});b=e.path;e=e.node;if(e.ee)throw new E(10);if(16384!==(e.mode&61440))throw new E(54);}b={type:a,bf:{},xe:b,Ge:[]};a=a.Sd(b);a.Sd=b;b.root=a;c?ub=a:e&&(e.ee=b,e.Sd&&e.Sd.Ge.push(b))}function Ob(a,b,c){var d=Bb(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new E(28);var e=Jb(d,a);if(e)throw new E(e);if(!d.Ld.de)throw new E(63);return d.Ld.de(d,a,b,c)}function H(a){Ob(a,16895,0)}
function Pb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ob(a,b|8192,c)}function Qb(a,b){if(!jb(a))throw new E(44);var c=Bb(b,{parent:!0}).node;if(!c)throw new E(44);b=ib(b);var d=Jb(c,b);if(d)throw new E(d);if(!c.Ld.symlink)throw new E(63);c.Ld.symlink(c,b,a)}function Cb(a){a=Bb(a).node;if(!a)throw new E(44);if(!a.Ld.readlink)throw new E(28);return jb(Db(a.parent),a.Ld.readlink(a))}
function Rb(a,b){if(""===a)throw new E(44);if("string"===typeof b){var c=Hb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=gb(a);try{e=Bb(a,{re:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new E(20);}else e=Ob(a,d,0),c=!0;if(!e)throw new E(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new E(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(e,Ib(b)):44))throw new E(d);if(b&512){d=e;var f;"string"===typeof d?f=Bb(d,{re:!0}).node:f=d;if(!f.Ld.Rd)throw new E(63);if(16384===(f.mode&61440))throw new E(31);if(32768!==(f.mode&61440))throw new E(28);if(d=Fb(f,"w"))throw new E(d);f.Ld.Rd(f,{size:0,timestamp:Date.now()})}b&=-131713;e=Lb({node:e,path:Db(e),flags:b,seekable:!0,position:0,Md:e.Md,Pe:[],error:!1});e.Md.open&&e.Md.open(e);!g.logReadFiles||b&1||(Sb||(Sb={}),a in Sb||(Sb[a]=1,u("FS.trackingDelegate error on read file: "+
a)));try{Ab.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Ab.onOpenFile(a,e))}catch(h){u("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}}function Tb(a,b,c){if(null===a.fd)throw new E(8);if(!a.seekable||!a.Md.Ud)throw new E(70);if(0!=c&&1!=c&&2!=c)throw new E(28);a.position=a.Md.Ud(a,b,c);a.Pe=[]}
function Ub(){E||(E=function(a,b){this.node=b;this.Ke=function(c){this.Yd=c};this.Ke(a);this.message="FS error"},E.prototype=Error(),E.prototype.constructor=E,[44].forEach(function(a){sb[a]=new E(a);sb[a].stack="<generic error, no stack>"}))}var Vb;function Wb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Xb(a,b,c){a=gb("/dev/"+a);var d=Wb(!!b,!!c);Yb||(Yb=64);var e=Yb++<<8|0;mb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,p,q){for(var t=0,z=0;z<q;z++){try{var B=b()}catch(F){throw new E(29);}if(void 0===B&&0===t)throw new E(6);if(null===B||void 0===B)break;t++;h[p+z]=B}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,p,q){for(var t=0;t<q;t++)try{c(h[p+t])}catch(z){throw new E(29);}q&&(f.node.timestamp=Date.now());return t}});
Pb(a,d,e)}var Yb,Zb={},Mb,Sb,$b={};function ac(a){a=wb[a];if(!a)throw new E(8);return a}
function bc(a,b){cc=a;dc=b;if(ec)if(0==a)fc=function(){var d=Math.max(0,hc+b-ic())|0;setTimeout(jc,d)};else if(1==a)fc=function(){kc(jc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);m?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}fc=function(){setImmediate(jc)}}}var ic;fa?ic=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ic=dateNow:ic=function(){return performance.now()};
function lc(a){var b=mc;noExitRuntime=!0;assert(!ec,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ec=a;mc=b;var c="undefined"!==typeof b?function(){g.dynCall_vi(a,b)}:function(){g.dynCall_v(a)};var d=nc;jc=function(){if(!ta)if(0<oc.length){var e=Date.now(),f=oc.shift();f.te(f.ce);if(pc){var h=pc,p=0==h%1?h-1:Math.floor(h);pc=f.Se?p:(8*h+(p+.5))/9}console.log('main loop blocker "'+
f.name+'" took '+(Date.now()-e)+" ms");g.setStatus&&(e=g.statusMessage||"Please wait...",f=pc,h=qc.Te,f?f<h?g.setStatus(e+" ("+(h-f)+"/"+h+")"):g.setStatus(e):g.setStatus(""));d<nc||setTimeout(jc,0)}else if(!(d<nc))if(rc=rc+1|0,1==cc&&1<dc&&0!=rc%dc)fc();else{0==cc&&(hc=ic());a:if(!(ta||g.preMainLoop&&!1===g.preMainLoop())){try{c()}catch(q){if(q instanceof ma)break a;q&&"object"===typeof q&&q.stack&&u("exception thrown: "+[q,q.stack]);throw q;}g.postMainLoop&&g.postMainLoop()}d<nc||("object"===typeof SDL&&
SDL.audio&&SDL.audio.Ie&&SDL.audio.Ie(),fc())}}}var fc=null,nc=0,ec=null,mc=0,cc=0,dc=0,rc=0,oc=[],qc={},hc,jc,pc,sc=!1,tc=!1,uc=[];
function vc(){function a(){tc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!wc){wc=!0;try{xc=!0}catch(c){xc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}yc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:xc?null:console.log("warning: no BlobBuilder");
zc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.ye||"undefined"!==typeof zc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.ye=!0);g.preloadPlugins.push({canHandle:function(c){return!g.ye&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(xc)try{h=new Blob([c],{type:Ac(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Ac(d)}))}catch(t){oa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}h||(h=new yc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var p=zc.createObjectURL(h),q=new Image;q.onload=function(){assert(q.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=q.width;t.height=q.height;t.getContext("2d").drawImage(q,0,0);g.preloadedImages[d]=t;zc.revokeObjectURL(p);e&&e(c)};q.onerror=function(){console.log("Image "+p+" could not be decoded");f&&f()};q.src=p}});g.preloadPlugins.push({canHandle:function(c){return!g.af&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(B){q||(q=!0,g.preloadedAudios[d]=B,e&&e(c))}function p(){q||(q=!0,g.preloadedAudios[d]=new Audio,f&&f())}var q=!1;if(xc){try{var t=new Blob([c],{type:Ac(d)})}catch(B){return p()}t=zc.createObjectURL(t);var z=new Audio;z.addEventListener("canplaythrough",function(){h(z)},!1);z.onerror=function(){if(!q){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var B="",F=0,l=0,
v=0;v<c.length;v++)for(F=F<<8|c[v],l+=8;6<=l;){var y=F>>l-6&63;l-=6;B+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[y]}2==l?(B+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(F&3)<<4],B+="=="):4==l&&(B+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(F&15)<<2],B+="=");z.src="data:audio/x-"+d.substr(-3)+";base64,"+B;h(z)}};z.src=t;Bc(function(){h(z)})}else return p()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!tc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Cc(a,b,c,d){if(b&&g.je&&a==g.canvas)return g.je;var e;if(b){var f={antialias:!1,alpha:!1,ve:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof Dc&&(e=Ec(a,f)))var p=I[e].Vd}else p=a.getContext("2d");if(!p)return null;c&&(b||assert("undefined"===typeof J,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.je=p,b&&Fc(e),g.Qe=b,uc.forEach(function(q){q()}),vc());return p}var Gc=!1,Hc=void 0,Ic=void 0;
function Jc(a,b){function c(){sc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Kc,Hc&&d.requestPointerLock(),sc=!0,Ic?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Da[SDL.screen>>2]|8388608),Lc(g.canvas),Mc()):Lc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Ic?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Da[SDL.screen>>2]&
-8388609),Lc(g.canvas),Mc()):Lc(d));if(g.onFullScreen)g.onFullScreen(sc);if(g.onFullscreen)g.onFullscreen(sc)}Hc=a;Ic=b;"undefined"===typeof Hc&&(Hc=!0);"undefined"===typeof Ic&&(Ic=!1);var d=g.canvas;Gc||(Gc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Kc(){if(!sc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Oc=0;function kc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Oc)Oc=b+1E3/60;else for(;b+2>=Oc;)Oc+=1E3/60;setTimeout(a,Math.max(Oc-b,0))}}function Bc(a){noExitRuntime=!0;setTimeout(function(){ta||a()},1E4)}
function Ac(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Pc=[];function Mc(){var a=g.canvas;Pc.forEach(function(b){b(a.width,a.height)})}
function Lc(a,b,c){b&&c?(a.Re=b,a.Ee=c):(b=a.Re,c=a.Ee);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Ic?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var wc,xc,yc,zc,K=12288,Qc=0,L={alpha:!1,depth:!1,stencil:!1,antialias:!1},Rc;
function Sc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Tc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Uc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Vc=1,N=[],O=[],Wc=[],P=[],Q=[],R=[],S=[],T=[],I=[],U=[],Xc={},Yc={},Zc=4;
function V(a){$c||($c=a)}function ad(a){for(var b=Vc++,c=a.length;c<b;c++)a[c]=null;return b}function Ec(a,b){if(a=a.getContext("webgl",b)){var c=ad(I),d={We:c,attributes:b,version:b.ve,Vd:a};a.canvas&&(a.canvas.Ae=d);I[c]=d;("undefined"===typeof b.De||b.De)&&bd(d);b=c}else b=0;return b}function Fc(a){cd=I[a];g.je=J=cd&&cd.Vd}
function bd(a){a||(a=cd);if(!a.Fe){a.Fe=!0;var b=a.Vd;Sc(b);Tc(b);Uc(b);b.Pd=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Dc={},$c,cd,dd=[];function W(a,b,c,d){for(var e=0;e<a;e++){var f=J[c](),h=f&&ad(d);f?(f.name=h,d[h]=f):V(1282);A[b+4*e>>2]=h}}function ed(a,b,c,d,e,f,h,p){b=O[b];if(a=J[a](b,c))d=p&&xa(a.name,w,p,d),e&&(A[e>>2]=d),f&&(A[f>>2]=a.size),h&&(A[h>>2]=a.type)}function fd(a,b){Da[a>>2]=b;Da[a+4>>2]=(b-Da[a>>2])/4294967296}
function gd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:A[b+4*a>>2]=e[a];break;case 2:C[b+4*a>>2]=e[a];break;case 4:x[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){V(1280);u("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);u("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:fd(b,
d);break;case 0:A[b>>2]=d;break;case 2:C[b>>2]=d;break;case 4:x[b>>0]=d?1:0}}else V(1281)}function hd(a){var b=ya(a)+1,c=bb(b);xa(a,w,c,b);return c}
function id(a,b,c,d){if(c)if(a=J.getUniform(O[a],R[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:A[c>>2]=a;break;case 2:C[c>>2]=a;break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:A[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b];break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else V(1281)}
function jd(a,b,c,d){if(c)if(a=J.getVertexAttrib(a,b),34975==b)A[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:A[c>>2]=a;break;case 2:C[c>>2]=a;break;case 5:A[c>>2]=Math.fround(a);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:A[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b];break;case 5:A[c+4*b>>2]=Math.fround(a[b]);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+
d;}else V(1281)}function kd(a,b,c,d,e){a-=5120;a=1==a?w:4==a?A:6==a?C:5==a||28922==a?Da:Ca;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Zc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var X=[],Y=[],ld={};
function md(){if(!nd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in ld)a[b]=ld[b];var c=[];for(b in a)c.push(b+"="+a[b]);nd=c}return nd}var nd;function od(a){return 0===a%4&&(0!==a%100||0===a%400)}function pd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var qd=[31,29,31,30,31,30,31,31,30,31,30,31],rd=[31,28,31,30,31,30,31,31,30,31,30,31];function sd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(od(a.getFullYear())?qd:rd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function td(a,b,c,d){function e(l,v,y){for(l="number"===typeof l?l.toString():l||"";l.length<v;)l=y[0]+l;return l}function f(l,v){return e(l,v,"0")}function h(l,v){function y(Nc){return 0>Nc?-1:0<Nc?1:0}var M;0===(M=y(l.getFullYear()-v.getFullYear()))&&0===(M=y(l.getMonth()-v.getMonth()))&&(M=y(l.getDate()-v.getDate()));return M}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function q(l){l=sd(new Date(l.Od+1900,0,1),l.ie);var v=new Date(l.getFullYear()+1,0,4),y=p(new Date(l.getFullYear(),0,4));v=p(v);return 0>=h(y,l)?0>=h(v,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var t=A[d+40>>2];d={Ne:A[d>>2],Me:A[d+4>>2],ge:A[d+8>>2],ae:A[d+12>>2],Xd:A[d+16>>2],Od:A[d+20>>2],he:A[d+24>>2],ie:A[d+28>>2],ff:A[d+32>>2],Le:A[d+
36>>2],Oe:t?wa(t):""};c=wa(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var z in t)c=c.replace(new RegExp(z,"g"),t[z]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");t={"%a":function(l){return B[l.he].substring(0,3)},"%A":function(l){return B[l.he]},"%b":function(l){return F[l.Xd].substring(0,3)},"%B":function(l){return F[l.Xd]},"%C":function(l){return f((l.Od+1900)/100|0,2)},"%d":function(l){return f(l.ae,2)},"%e":function(l){return e(l.ae,2," ")},"%g":function(l){return q(l).toString().substring(2)},"%G":function(l){return q(l)},"%H":function(l){return f(l.ge,
2)},"%I":function(l){l=l.ge;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){return f(l.ae+pd(od(l.Od+1900)?qd:rd,l.Xd-1),3)},"%m":function(l){return f(l.Xd+1,2)},"%M":function(l){return f(l.Me,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.ge&&12>l.ge?"AM":"PM"},"%S":function(l){return f(l.Ne,2)},"%t":function(){return"\t"},"%u":function(l){return l.he||7},"%U":function(l){var v=new Date(l.Od+1900,0,1),y=0===v.getDay()?v:sd(v,7-v.getDay());l=new Date(l.Od+1900,l.Xd,l.ae);return 0>
h(y,l)?f(Math.ceil((31-y.getDate()+(pd(od(l.getFullYear())?qd:rd,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(y,v)?"01":"00"},"%V":function(l){var v=new Date(l.Od+1901,0,4),y=p(new Date(l.Od+1900,0,4));v=p(v);var M=sd(new Date(l.Od+1900,0,1),l.ie);return 0>h(M,y)?"53":0>=h(v,M)?"01":f(Math.ceil((y.getFullYear()<l.Od+1900?l.ie+32-y.getDate():l.ie+1-y.getDate())/7),2)},"%w":function(l){return l.he},"%W":function(l){var v=new Date(l.Od,0,1),y=1===v.getDay()?v:sd(v,0===v.getDay()?1:7-v.getDay()+1);l=
new Date(l.Od+1900,l.Xd,l.ae);return 0>h(y,l)?f(Math.ceil((31-y.getDate()+(pd(od(l.getFullYear())?qd:rd,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(y,v)?"01":"00"},"%y":function(l){return(l.Od+1900).toString().substring(2)},"%Y":function(l){return l.Od+1900},"%z":function(l){l=l.Le;var v=0<=l;l=Math.abs(l)/60;return(v?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Oe},"%%":function(){return"%"}};for(z in t)0<=c.indexOf(z)&&(c=c.replace(new RegExp(z,"g"),t[z](d)));z=
ab(c,!1);if(z.length>b)return 0;x.set(z,a);return z.length-1}var ud=[];function Gb(a,b,c,d){a||(a=this);this.parent=a;this.Sd=a.Sd;this.ee=null;this.id=xb++;this.name=b;this.mode=c;this.Ld={};this.Md={};this.rdev=d}Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ub();yb=Array(4096);Nb(G,"/");H("/tmp");H("/home");
H("/home/web_user");
(function(){H("/dev");mb(259,{read:function(){return 0},write:function(d,e,f,h){return h}});Pb("/dev/null",259);lb(1280,ob);lb(1536,pb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(fa)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){r("random_device")});Xb("random",b);Xb("urandom",b);H("/dev/shm");
H("/dev/shm/tmp")})();H("/proc");H("/proc/self");H("/proc/self/fd");Nb({Sd:function(){var a=rb("/proc/self","fd",16895,73);a.Ld={lookup:function(b,c){var d=wb[+c];if(!d)throw new E(8);b={parent:null,Sd:{xe:"fake"},Ld:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");g.requestFullscreen=function(a,b){Jc(a,b)};g.requestAnimationFrame=function(a){kc(a)};g.setCanvasSize=function(a,b,c){Lc(g.canvas,a,b);c||Mc()};g.pauseMainLoop=function(){fc=null;nc++};
g.resumeMainLoop=function(){nc++;var a=cc,b=dc,c=ec;ec=null;lc(c);bc(a,b);fc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Cc(a,b,c,d)};for(var J,Z=0;32>Z;++Z)dd.push(Array(Z));var vd=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=vd.subarray(0,Z+1);var wd=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=wd.subarray(0,Z+1);
function ab(a,b){var c=Array(ya(a)+1);a=xa(a,c,0,c.length);b&&(c.length=a);return c}
var Ad={Bd:function(a){return bb(a)},Ad:function(a){"uncaught_exception"in eb?eb.be++:eb.be=1;throw a;},C:function(){A[xd()>>2]=63;return-1},B:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=$b[a];if(d&&b===d.Xe){var e=wb[d.fd];if(d.cf&2){var f=d.flags,h=d.offset,p=w.slice(a,a+b);e&&e.Md.fe&&e.Md.fe(e,p,h,b,f)}$b[a]=null;d.Be&&yd(d.Ze)}c=0}return c}catch(q){return"undefined"!==typeof Zb&&q instanceof E||r(q),-q.Yd}},a:function(){r()},ba:function(a){if(12448==a)return K=12288,1;K=12300;
return 0},aa:function(a,b,c,d,e){if(62E3!=a)K=12296,c=0;else{if(b)for(;;){a=A[b>>2];if(12321==a)L.alpha=0<A[b+4>>2];else if(12325==a)L.depth=0<A[b+4>>2];else if(12326==a)L.stencil=0<A[b+4>>2];else if(12337==a)a=A[b+4>>2],L.antialias=0<a;else if(12338==a)a=A[b+4>>2],L.antialias=1==a;else if(12544==a)L.Ye=12547!=A[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(A[e>>2]=1),c&&0<d&&(A[c>>2]=62002),K=12288,c=1):(K=12300,c=0)}return c},$:function(a,b,c,d){if(62E3!=a)return K=12296,0;for(a=1;;){b=A[d>>
2];if(12440==b)a=A[d+4>>2];else if(12344==b)break;else return K=12292,0;d+=8}if(2!=a)return K=12293,0;L.ve=a-1;L.$e=0;Rc=Ec(g.canvas,L);if(0!=Rc)return K=12288,Fc(Rc),g.Qe=!0,uc.forEach(function(e){e()}),Fc(null),62004;K=12297;return 0},_:function(a,b){if(62E3!=a)return K=12296,0;if(62004!=b)return K=12294,0;a=Rc;cd===I[a]&&(cd=null);"object"===typeof JSEvents&&JSEvents.ef(I[a].Vd.canvas);I[a]&&I[a].Vd.canvas&&(I[a].Vd.canvas.Ae=void 0);I[a]=null;K=12288;Qc==b&&(Qc=0);return 1},da:function(){K=12288;
return 62E3},c:function(){return K},ca:function(a,b,c){if(62E3==a)return b&&(A[b>>2]=1),c&&(A[c>>2]=4),K=12288,1;K=12296;return 0},Y:function(a,b,c,d){if(62E3!=a)return K=12296,0;if(0!=d&&62004!=d)return K=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return K=12301,0;Fc(d?Rc:null);Qc=d;K=12288;return 1},Z:function(a){if(62E3!=a)return K=12296,0;Qc=0;K=12288;return 1},Fa:function(a,b,c){ud.length=0;var d;for(c>>=2;d=w[b++];)ud.push(105>d?Ea[++c>>1]:A[c]),++c;return cb[a].apply(null,ud)},yd:function(a){J.activeTexture(a)},
xd:function(a,b){J.attachShader(O[a],S[b])},t:function(a,b){J.Pd.beginQueryEXT(a,U[b])},wd:function(a,b,c){J.bindAttribLocation(O[a],b,wa(c))},vd:function(a,b){J.bindBuffer(a,N[b])},ud:function(a,b){J.bindFramebuffer(a,Wc[b])},td:function(a,b){J.bindRenderbuffer(a,P[b])},sd:function(a,b){J.bindTexture(a,Q[b])},P:function(a){J.bindVertexArray(T[a])},rd:function(a,b,c,d){J.blendColor(a,b,c,d)},qd:function(a){J.blendEquation(a)},pd:function(a,b){J.blendEquationSeparate(a,b)},nd:function(a,b){J.blendFunc(a,
b)},md:function(a,b,c,d){J.blendFuncSeparate(a,b,c,d)},ld:function(a,b,c,d){J.bufferData(a,c?w.subarray(c,c+b):b,d)},kd:function(a,b,c,d){J.bufferSubData(a,b,w.subarray(d,d+c))},jd:function(a){return J.checkFramebufferStatus(a)},id:function(a){J.clear(a)},hd:function(a,b,c,d){J.clearColor(a,b,c,d)},gd:function(a){J.clearDepth(a)},fd:function(a){J.clearStencil(a)},ed:function(a,b,c,d){J.colorMask(!!a,!!b,!!c,!!d)},cd:function(a){J.compileShader(S[a])},bd:function(a,b,c,d,e,f,h,p){J.compressedTexImage2D(a,
b,c,d,e,f,p?w.subarray(p,p+h):null)},ad:function(a,b,c,d,e,f,h,p,q){J.compressedTexSubImage2D(a,b,c,d,e,f,h,q?w.subarray(q,q+p):null)},$c:function(a,b,c,d,e,f,h,p){J.copyTexImage2D(a,b,c,d,e,f,h,p)},_c:function(a,b,c,d,e,f,h,p){J.copyTexSubImage2D(a,b,c,d,e,f,h,p)},Zc:function(){var a=ad(O),b=J.createProgram();b.name=a;O[a]=b;return a},Yc:function(a){var b=ad(S);S[b]=J.createShader(a);return b},Xc:function(a){J.cullFace(a)},Wc:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=N[d];e&&(J.deleteBuffer(e),
e.name=0,N[d]=null)}},Vc:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=Wc[d];e&&(J.deleteFramebuffer(e),e.name=0,Wc[d]=null)}},Uc:function(a){if(a){var b=O[a];b?(J.deleteProgram(b),b.name=0,O[a]=null,Xc[a]=null):V(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=U[d];e&&(J.Pd.deleteQueryEXT(e),U[d]=null)}},Tc:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=P[d];e&&(J.deleteRenderbuffer(e),e.name=0,P[d]=null)}},Sc:function(a){if(a){var b=S[a];b?(J.deleteShader(b),S[a]=
null):V(1281)}},Rc:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Q[d];e&&(J.deleteTexture(e),e.name=0,Q[d]=null)}},O:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];J.deleteVertexArray(T[d]);T[d]=null}},Qc:function(a){J.depthFunc(a)},Pc:function(a){J.depthMask(!!a)},Oc:function(a,b){J.depthRange(a,b)},Nc:function(a,b){J.detachShader(O[a],S[b])},Mc:function(a){J.disable(a)},Lc:function(a){J.disableVertexAttribArray(a)},Jc:function(a,b,c){J.drawArrays(a,b,c)},K:function(a,b,c,d){J.drawArraysInstanced(a,
b,c,d)},I:function(a,b){for(var c=dd[a],d=0;d<a;d++)c[d]=A[b+4*d>>2];J.drawBuffers(c)},Ic:function(a,b,c,d){J.drawElements(a,b,c,d)},J:function(a,b,c,d,e){J.drawElementsInstanced(a,b,c,d,e)},Hc:function(a){J.enable(a)},Gc:function(a){J.enableVertexAttribArray(a)},s:function(a){J.Pd.endQueryEXT(a)},Fc:function(){J.finish()},Ec:function(){J.flush()},Dc:function(a,b,c,d){J.framebufferRenderbuffer(a,b,c,P[d])},Cc:function(a,b,c,d,e){J.framebufferTexture2D(a,b,c,Q[d],e)},Bc:function(a){J.frontFace(a)},
Ac:function(a,b){W(a,b,"createBuffer",N)},xc:function(a,b){W(a,b,"createFramebuffer",Wc)},x:function(a,b){for(var c=0;c<a;c++){var d=J.Pd.createQueryEXT();if(!d){for(V(1282);c<a;)A[b+4*c++>>2]=0;break}var e=ad(U);d.name=e;U[e]=d;A[b+4*c>>2]=e}},wc:function(a,b){W(a,b,"createRenderbuffer",P)},vc:function(a,b){W(a,b,"createTexture",Q)},N:function(a,b){W(a,b,"createVertexArray",T)},yc:function(a){J.generateMipmap(a)},uc:function(a,b,c,d,e,f,h){ed("getActiveAttrib",a,b,c,d,e,f,h)},tc:function(a,b,c,d,
e,f,h){ed("getActiveUniform",a,b,c,d,e,f,h)},sc:function(a,b,c,d){a=J.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);A[c>>2]=e;for(b=0;b<e;++b)A[d+4*b>>2]=S.indexOf(a[b])},rc:function(a,b){return J.getAttribLocation(O[a],wa(b))},qc:function(a,b){gd(a,b,4)},pc:function(a,b,c){c?A[c>>2]=J.getBufferParameter(a,b):V(1281)},nc:function(){var a=J.getError()||$c;$c=0;return a},mc:function(a,b){gd(a,b,2)},lc:function(a,b,c,d){a=J.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||
a instanceof WebGLTexture)a=a.name|0;A[d>>2]=a},kc:function(a,b){gd(a,b,0)},ic:function(a,b,c,d){a=J.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?xa(a,w,d,b):0;c&&(A[c>>2]=b)},jc:function(a,b,c){if(c)if(a>=Vc)V(1281);else{var d=Xc[a];if(d)if(35716==b)a=J.getProgramInfoLog(O[a]),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b)A[c>>2]=d.le;else if(35722==b){if(-1==d.Zd){a=O[a];var e=J.getProgramParameter(a,35721);for(b=d.Zd=0;b<e;++b)d.Zd=Math.max(d.Zd,J.getActiveAttrib(a,
b).name.length+1)}A[c>>2]=d.Zd}else if(35381==b){if(-1==d.$d)for(a=O[a],e=J.getProgramParameter(a,35382),b=d.$d=0;b<e;++b)d.$d=Math.max(d.$d,J.getActiveUniformBlockName(a,b).length+1);A[c>>2]=d.$d}else A[c>>2]=J.getProgramParameter(O[a],b);else V(1282)}else V(1281)},n:function(a,b,c){if(c){a=J.Pd.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;fd(c,d)}else V(1281)},p:function(a,b,c){if(c){a=J.Pd.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;A[c>>2]=d}else V(1281)},
m:function(a,b,c){if(c){a=J.Pd.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;fd(c,d)}else V(1281)},o:function(a,b,c){if(c){a=J.Pd.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;A[c>>2]=d}else V(1281)},q:function(a,b,c){c?A[c>>2]=J.Pd.getQueryEXT(a,b):V(1281)},hc:function(a,b,c){c?A[c>>2]=J.getRenderbufferParameter(a,b):V(1281)},fc:function(a,b,c,d){a=J.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?xa(a,w,d,b):0;c&&(A[c>>2]=b)},ec:function(a,b,c,
d){a=J.getShaderPrecisionFormat(a,b);A[c>>2]=a.rangeMin;A[c+4>>2]=a.rangeMax;A[d>>2]=a.precision},cc:function(a,b,c,d){if(a=J.getShaderSource(S[a]))b=0<b&&d?xa(a,w,d,b):0,c&&(A[c>>2]=b)},gc:function(a,b,c){c?35716==b?(a=J.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1):35720==b?(a=J.getShaderSource(S[a]),A[c>>2]=null===a||0==a.length?0:a.length+1):A[c>>2]=J.getShaderParameter(S[a],b):V(1281)},bc:function(a){if(Yc[a])return Yc[a];switch(a){case 7939:var b=J.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=hd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||V(1280);b=hd(b);break;case 7938:b=hd("OpenGL ES 2.0 ("+J.getParameter(7938)+")");break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=hd(b);break;default:return V(1280),0}return Yc[a]=b},ac:function(a,b,c){c?C[c>>2]=J.getTexParameter(a,
b):V(1281)},$b:function(a,b,c){c?A[c>>2]=J.getTexParameter(a,b):V(1281)},Yb:function(a,b){b=wa(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Xc[a]&&Xc[a].ze[b])&&0<=c&&c<a[0]?a[1]+c:-1},_b:function(a,b,c){id(a,b,c,2)},Zb:function(a,b,c){id(a,b,c,0)},Vb:function(a,b,c){c?A[c>>2]=J.getVertexAttribOffset(a,b):V(1281)},Xb:function(a,b,c){jd(a,b,c,2)},Wb:function(a,b,c){jd(a,b,c,5)},Ub:function(a,b){J.hint(a,b)},Tb:function(a){return(a=
N[a])?J.isBuffer(a):0},Sb:function(a){return J.isEnabled(a)},Rb:function(a){return(a=Wc[a])?J.isFramebuffer(a):0},Qb:function(a){return(a=O[a])?J.isProgram(a):0},u:function(a){return(a=U[a])?J.Pd.isQueryEXT(a):0},Pb:function(a){return(a=P[a])?J.isRenderbuffer(a):0},Ob:function(a){return(a=S[a])?J.isShader(a):0},Nb:function(a){return(a=Q[a])?J.isTexture(a):0},M:function(a){return(a=T[a])?J.isVertexArray(a):0},Mb:function(a){J.lineWidth(a)},Lb:function(a){J.linkProgram(O[a]);var b=O[a];a=Xc[a]={ze:{},
le:0,Zd:-1,$d:-1};for(var c=a.ze,d=J.getProgramParameter(b,35718),e=0;e<d;++e){var f=J.getActiveUniform(b,e),h=f.name;a.le=Math.max(a.le,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var p=J.getUniformLocation(b,h);if(p){var q=ad(R);c[h]=[f.size,q];R[q]=p;for(var t=1;t<f.size;++t)p=J.getUniformLocation(b,h+"["+t+"]"),q=ad(R),R[q]=p}}},Jb:function(a,b){3317==a&&(Zc=b);J.pixelStorei(a,b)},Ib:function(a,b){J.polygonOffset(a,b)},r:function(a,b){J.Pd.queryCounterEXT(U[a],b)},Hb:function(a,
b,c,d,e,f,h){(h=kd(f,e,c,d,h))?J.readPixels(a,b,c,d,e,f,h):V(1280)},Gb:function(){},Fb:function(a,b,c,d){J.renderbufferStorage(a,b,c,d)},Eb:function(a,b){J.sampleCoverage(a,!!b)},Db:function(a,b,c,d){J.scissor(a,b,c,d)},Cb:function(){V(1280)},Bb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?A[d+4*f>>2]:-1;e+=wa(A[c+4*f>>2],0>h?void 0:h)}J.shaderSource(S[a],e)},Ab:function(a,b,c){J.stencilFunc(a,b,c)},yb:function(a,b,c,d){J.stencilFuncSeparate(a,b,c,d)},xb:function(a){J.stencilMask(a)},wb:function(a,
b){J.stencilMaskSeparate(a,b)},vb:function(a,b,c){J.stencilOp(a,b,c)},ub:function(a,b,c,d){J.stencilOpSeparate(a,b,c,d)},tb:function(a,b,c,d,e,f,h,p,q){J.texImage2D(a,b,c,d,e,f,h,p,q?kd(p,h,d,e,q):null)},sb:function(a,b,c){J.texParameterf(a,b,c)},rb:function(a,b,c){J.texParameterf(a,b,C[c>>2])},qb:function(a,b,c){J.texParameteri(a,b,c)},pb:function(a,b,c){J.texParameteri(a,b,A[c>>2])},nb:function(a,b,c,d,e,f,h,p,q){var t=null;q&&(t=kd(p,h,e,f,q));J.texSubImage2D(a,b,c,d,e,f,h,p,t)},mb:function(a,
b){J.uniform1f(R[a],b)},lb:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);J.uniform1fv(R[a],d)},kb:function(a,b){J.uniform1i(R[a],b)},jb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);J.uniform1iv(R[a],d)},ib:function(a,b,c){J.uniform2f(R[a],b,c)},hb:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);J.uniform2fv(R[a],
d)},gb:function(a,b,c){J.uniform2i(R[a],b,c)},fb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);J.uniform2iv(R[a],d)},eb:function(a,b,c,d){J.uniform3f(R[a],b,c,d)},cb:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);J.uniform3fv(R[a],d)},bb:function(a,b,c,d){J.uniform3i(R[a],b,c,d)},ab:function(a,b,c){if(96>=
b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);J.uniform3iv(R[a],d)},$a:function(a,b,c,d,e){J.uniform4f(R[a],b,c,d,e)},_a:function(a,b,c){if(72>=b){var d=X[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var f=c+e;d[e]=C[f];d[e+1]=C[f+1];d[e+2]=C[f+2];d[e+3]=C[f+3]}}else d=C.subarray(c>>2,c+16*b>>2);J.uniform4fv(R[a],d)},Za:function(a,b,c,d,e){J.uniform4i(R[a],b,c,d,e)},Ya:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<
4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);J.uniform4iv(R[a],d)},Xa:function(a,b,c,d){if(72>=b)for(var e=X[4*b-1],f=0;f<4*b;f+=4)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2];else e=C.subarray(d>>2,d+16*b>>2);J.uniformMatrix2fv(R[a],!!c,e)},Wa:function(a,b,c,d){if(32>=b)for(var e=X[9*b-1],f=0;f<9*b;f+=9)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=
C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(R[a],!!c,e)},Va:function(a,b,c,d){if(18>=b){var e=X[16*b-1];d>>=2;for(var f=0;f<16*b;f+=16){var h=d+f;e[f]=C[h];e[f+1]=C[h+1];e[f+2]=C[h+2];e[f+3]=C[h+3];e[f+4]=C[h+4];e[f+5]=C[h+5];e[f+6]=C[h+6];e[f+7]=C[h+7];e[f+8]=C[h+8];e[f+9]=C[h+9];e[f+10]=C[h+10];e[f+11]=C[h+11];e[f+12]=C[h+12];e[f+13]=C[h+13];e[f+14]=C[h+
14];e[f+15]=C[h+15]}}else e=C.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(R[a],!!c,e)},Ta:function(a){J.useProgram(O[a])},Sa:function(a){J.validateProgram(O[a])},Ra:function(a,b){J.vertexAttrib1f(a,b)},Qa:function(a,b){J.vertexAttrib1f(a,C[b>>2])},Pa:function(a,b,c){J.vertexAttrib2f(a,b,c)},Oa:function(a,b){J.vertexAttrib2f(a,C[b>>2],C[b+4>>2])},Na:function(a,b,c,d){J.vertexAttrib3f(a,b,c,d)},Ma:function(a,b){J.vertexAttrib3f(a,C[b>>2],C[b+4>>2],C[b+8>>2])},La:function(a,b,c,d,e){J.vertexAttrib4f(a,
b,c,d,e)},Ka:function(a,b){J.vertexAttrib4f(a,C[b>>2],C[b+4>>2],C[b+8>>2],C[b+12>>2])},L:function(a,b){J.vertexAttribDivisor(a,b)},Ia:function(a,b,c,d,e,f){J.vertexAttribPointer(a,b,c,!!d,e,f)},Ha:function(a,b,c,d){J.viewport(a,b,c,d)},y:function(a,b,c){w.copyWithin(a,b,b+c)},z:function(){r("OOM")},D:function(a,b){var c=0;md().forEach(function(d,e){var f=b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)x[e++>>0]=d.charCodeAt(f);x[e>>0]=0;c+=d.length+1});return 0},E:function(a,b){var c=md();A[a>>2]=c.length;
var d=0;c.forEach(function(e){d+=e.length+1});A[b>>2]=d;return 0},f:function(a){zd(a)},H:function(a){try{var b=ac(a);if(null===b.fd)throw new E(8);b.ke&&(b.ke=null);try{b.Md.close&&b.Md.close(b)}catch(c){throw c;}finally{wb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof Zb&&c instanceof E||r(c),c.Yd}},F:function(a,b,c,d){try{a:{for(var e=ac(a),f=a=0;f<c;f++){var h=A[b+(8*f+4)>>2],p=e,q=A[b+8*f>>2],t=h,z=void 0,B=x;if(0>t||0>z)throw new E(28);if(null===p.fd)throw new E(8);if(1===
(p.flags&2097155))throw new E(8);if(16384===(p.node.mode&61440))throw new E(31);if(!p.Md.read)throw new E(28);var F="undefined"!==typeof z;if(!F)z=p.position;else if(!p.seekable)throw new E(70);var l=p.Md.read(p,B,q,t,z);F||(p.position+=l);var v=l;if(0>v){var y=-1;break a}a+=v;if(v<h)break}y=a}A[d>>2]=y;return 0}catch(M){return"undefined"!==typeof Zb&&M instanceof E||r(M),M.Yd}},Ga:function(a,b,c,d,e){try{var f=ac(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Tb(f,
a,d);$a=[f.position>>>0,(Za=f.position,1<=+Ma(Za)?0<Za?(Pa(+Oa(Za/4294967296),4294967295)|0)>>>0:~~+Na((Za-+(~~Za>>>0))/4294967296)>>>0:0)];A[e>>2]=$a[0];A[e+4>>2]=$a[1];f.ke&&0===a&&0===d&&(f.ke=null);return 0}catch(h){return"undefined"!==typeof Zb&&h instanceof E||r(h),h.Yd}},g:function(a,b,c,d){try{a:{for(var e=ac(a),f=a=0;f<c;f++){var h=e,p=A[b+8*f>>2],q=A[b+(8*f+4)>>2],t=void 0,z=x;if(0>q||0>t)throw new E(28);if(null===h.fd)throw new E(8);if(0===(h.flags&2097155))throw new E(8);if(16384===(h.node.mode&
61440))throw new E(31);if(!h.Md.write)throw new E(28);h.seekable&&h.flags&1024&&Tb(h,0,2);var B="undefined"!==typeof t;if(!B)t=h.position;else if(!h.seekable)throw new E(70);var F=h.Md.write(h,z,p,q,t,void 0);B||(h.position+=F);try{if(h.path&&Ab.onWriteToFile)Ab.onWriteToFile(h.path)}catch(y){u("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+y.message)}var l=F;if(0>l){var v=-1;break a}a+=l}v=a}A[d>>2]=v;return 0}catch(y){return"undefined"!==typeof Zb&&y instanceof E||r(y),
y.Yd}},e:function(a){J.activeTexture(a)},k:function(a,b){J.bindBuffer(a,N[b])},Ja:function(a,b){J.bindFramebuffer(a,Wc[b])},od:function(a,b){J.bindRenderbuffer(a,P[b])},j:function(a,b){J.bindTexture(a,Q[b])},U:function(a){J.bindVertexArray(T[a])},zb:function(a,b,c,d){J.bufferData(a,c?w.subarray(c,c+b):b,d)},ob:function(a,b,c,d){J.bufferSubData(a,b,w.subarray(d,d+c))},Ea:function(a){return J.checkFramebufferStatus(a)},Kc:function(a,b,c,d){J.clearColor(a,b,c,d)},zc:function(a){J.clearDepth(a)},h:function(a,
b,c,d,e,f,h,p,q){J.compressedTexSubImage2D(a,b,c,d,e,f,h,q?w.subarray(q,q+p):null)},Ca:function(a,b,c,d,e,f,h,p){J.copyTexSubImage2D(a,b,c,d,e,f,h,p)},dc:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=N[d];e&&(J.deleteBuffer(e),e.name=0,N[d]=null)}},T:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];J.deleteVertexArray(T[d]);T[d]=null}},ea:function(a){J.disableVertexAttribArray(a)},ia:function(a,b,c){J.drawArrays(a,b,c)},W:function(a,b,c,d){J.drawArraysInstanced(a,b,c,d)},Q:function(a,
b){for(var c=dd[a],d=0;d<a;d++)c[d]=A[b+4*d>>2];J.drawBuffers(c)},ha:function(a,b,c,d){J.drawElements(a,b,c,d)},V:function(a,b,c,d,e){J.drawElementsInstanced(a,b,c,d,e)},ga:function(a){J.enableVertexAttribArray(a)},G:function(a,b,c,d){J.framebufferRenderbuffer(a,b,c,P[d])},w:function(a,b,c,d,e){J.framebufferTexture2D(a,b,c,Q[d],e)},oc:function(a,b){W(a,b,"createBuffer",N)},R:function(a,b){W(a,b,"createFramebuffer",Wc)},Ua:function(a,b){for(var c=0;c<a;c++){var d=J.Pd.createQueryEXT();if(!d){for(V(1282);c<
a;)A[b+4*c++>>2]=0;break}var e=ad(U);d.name=e;U[e]=d;A[b+4*c>>2]=e}},zd:function(a,b){W(a,b,"createRenderbuffer",P)},pa:function(a,b){W(a,b,"createTexture",Q)},S:function(a,b){W(a,b,"createVertexArray",T)},oa:function(a){J.generateMipmap(a)},Kb:function(a,b,c){c?A[c>>2]=J.getBufferParameter(a,b):V(1281)},ja:function(){var a=J.getError()||$c;$c=0;return a},l:function(a,b){gd(a,b,2)},b:function(a,b){gd(a,b,0)},d:function(a){if(Yc[a])return Yc[a];switch(a){case 7939:var b=J.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=hd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||V(1280);b=hd(b);break;case 7938:b=hd("OpenGL ES 2.0 ("+J.getParameter(7938)+")");break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=hd(b);break;default:return V(1280),0}return Yc[a]=b},db:function(a,b){3317==a&&(Zc=b);J.pixelStorei(a,
b)},Da:function(a,b,c,d,e,f,h){(h=kd(f,e,c,d,h))?J.readPixels(a,b,c,d,e,f,h):V(1280)},dd:function(a,b,c,d){J.renderbufferStorage(a,b,c,d)},ka:function(a,b,c,d,e,f,h,p,q){J.texImage2D(a,b,c,d,e,f,h,p,q?kd(p,h,d,e,q):null)},ma:function(a,b,c){J.texParameterf(a,b,c)},la:function(a,b,c){J.texParameterf(a,b,C[c>>2])},na:function(a,b,c){J.texParameteri(a,b,c)},i:function(a,b,c,d,e,f,h,p,q){var t=null;q&&(t=kd(p,h,e,f,q));J.texSubImage2D(a,b,c,d,e,f,h,p,t)},Aa:function(a,b,c){if(288>=b)for(var d=X[b-1],
e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);J.uniform1fv(R[a],d)},wa:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);J.uniform1iv(R[a],d)},za:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);J.uniform2fv(R[a],d)},va:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*
b>>2);J.uniform2iv(R[a],d)},ya:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);J.uniform3fv(R[a],d)},ua:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);J.uniform3iv(R[a],d)},xa:function(a,b,c){if(72>=b){var d=X[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var f=c+e;d[e]=C[f];d[e+1]=C[f+1];d[e+
2]=C[f+2];d[e+3]=C[f+3]}}else d=C.subarray(c>>2,c+16*b>>2);J.uniform4fv(R[a],d)},ta:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2],d[e+3]=A[c+(4*e+12)>>2];else d=A.subarray(c>>2,c+16*b>>2);J.uniform4iv(R[a],d)},sa:function(a,b,c,d){if(72>=b)for(var e=X[4*b-1],f=0;f<4*b;f+=4)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2];else e=C.subarray(d>>2,d+16*b>>2);J.uniformMatrix2fv(R[a],!!c,e)},
ra:function(a,b,c,d){if(32>=b)for(var e=X[9*b-1],f=0;f<9*b;f+=9)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(R[a],!!c,e)},qa:function(a,b,c,d){if(18>=b){var e=X[16*b-1];d>>=2;for(var f=0;f<16*b;f+=16){var h=d+f;e[f]=C[h];e[f+1]=C[h+1];e[f+2]=C[h+2];e[f+3]=C[h+3];e[f+4]=C[h+4];e[f+5]=C[h+
5];e[f+6]=C[h+6];e[f+7]=C[h+7];e[f+8]=C[h+8];e[f+9]=C[h+9];e[f+10]=C[h+10];e[f+11]=C[h+11];e[f+12]=C[h+12];e[f+13]=C[h+13];e[f+14]=C[h+14];e[f+15]=C[h+15]}}else e=C.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(R[a],!!c,e)},Ba:function(a){J.useProgram(O[a])},X:function(a,b){J.vertexAttribDivisor(a,b)},fa:function(a,b,c,d,e,f){J.vertexAttribPointer(a,b,c,!!d,e,f)},memory:ra,A:function(a,b,c,d){return td(a,b,c,d)},table:sa};
(function(){function a(e){g.asm=e.exports;Qa--;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa&&(e=Sa,Sa=null,e()))}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){u("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:Ad};Qa++;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return u("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(qa||"function"!==typeof WebAssembly.instantiateStreaming||Va()||Ta("file://")||"function"!==typeof fetch)return c(b);fetch(Ua,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){u("wasm streaming compile failed: "+f);u("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var db=g.___wasm_call_ctors=function(){return(db=g.___wasm_call_ctors=g.asm.Cd).apply(null,arguments)};
g._main=function(){return(g._main=g.asm.Dd).apply(null,arguments)};var xd=g.___errno_location=function(){return(xd=g.___errno_location=g.asm.Ed).apply(null,arguments)},yd=g._free=function(){return(yd=g._free=g.asm.Fd).apply(null,arguments)},bb=g._malloc=function(){return(bb=g._malloc=g.asm.Gd).apply(null,arguments)},Aa=g.stackAlloc=function(){return(Aa=g.stackAlloc=g.asm.Hd).apply(null,arguments)};g.dynCall_vi=function(){return(g.dynCall_vi=g.asm.Id).apply(null,arguments)};
g.dynCall_v=function(){return(g.dynCall_v=g.asm.Jd).apply(null,arguments)};var Bd;function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function Cd(){Bd||Dd();Bd||(Sa=Cd)};
function Dd(a){function b(){if(!Bd&&(Bd=!0,g.calledRun=!0,!ta)){g.noFSInit||Vb||(Vb=!0,Ub(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Xb("stdin",g.stdin):Qb("/dev/tty","/dev/stdin"),g.stdout?Xb("stdout",null,g.stdout):Qb("/dev/tty","/dev/stdout"),g.stderr?Xb("stderr",null,g.stderr):Qb("/dev/tty1","/dev/stderr"),Rb("/dev/stdin","r"),Rb("/dev/stdout","w"),Rb("/dev/stderr","w"));Ga(Ia);zb=!1;Ga(Ja);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ed){var c=a,d=g._main;c=c||[];
var e=c.length+1,f=Aa(4*(e+1));A[f>>2]=za(ca);for(var h=1;h<e;h++)A[(f>>2)+h]=za(c[h-1]);A[(f>>2)+e]=0;try{var p=d(e,f);zd(p,!0)}catch(q){q instanceof ma||("unwind"==q?noExitRuntime=!0:((c=q)&&"object"===typeof q&&q.stack&&(c=[q,q.stack]),u("exception thrown: "+c),da(1,q)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ka.unshift(c);Ga(Ka)}}a=a||ba;if(!(0<Qa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)La();
Ga(Ha);0<Qa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Dd;function zd(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(ta=!0,g.onExit))g.onExit(a);da(a,new ma(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ed=!0;g.noInitialRun&&(Ed=!1);noExitRuntime=!0;Dd();
