
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},f),ca=[],da="./this.program",ea=(a,b)=>{throw b;},fa="object"===typeof window,l="function"===typeof importScripts,ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,m="",ia,ja,ka,fs,la,ma;
if(ha)m=l?require("path").dirname(m)+"/":__dirname+"/",ma=()=>{la||(fs=require("fs"),la=require("path"))},ia=function(a,b){ma();a=la.normalize(a);return fs.readFileSync(a,b?null:"utf8")},ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a},ja=(a,b,c)=>{ma();a=la.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof
na))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ea=(a,b)=>{if(noExitRuntime||0<oa)throw process.exitCode=a,b;b instanceof na||n("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(fa||l)l?m=self.location.href:"undefined"!==typeof document&&document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ia=a=>{var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},l&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var t=f.print||console.log.bind(console),n=f.printErr||console.warn.bind(console);aa(f,ba);ba=null;f.arguments&&(ca=f.arguments);
f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);function pa(a){qa||(qa={});qa[a]||(qa[a]=1,n(a))}var qa,x;f.wasmBinary&&(x=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ra,B=!1,sa,ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function E(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ua(a){var b=E(a)+1,c=va(b);D(a,F,c,b);return c}var wa,F,H,xa,I,J,K,ya,za,Aa=[],Ba=[],Ca=[],Da=[],Ea=!1,oa=0;function Fa(){var a=f.preRun.shift();Aa.unshift(a)}var L=0,Ga=null,Ha=null;f.preloadedImages={};f.preloadedAudios={};
function A(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";n(a);B=!0;sa=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ia(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="magnum-gl-info.wasm";if(!Ia()){var Ja=M;M=f.locateFile?f.locateFile(Ja,m):m+Ja}function Ka(){var a=M;try{if(a==M&&x)return new Uint8Array(x);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function La(){if(!x&&(fa||l)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(ja)return new Promise(function(a,b){ja(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}
var N,Ma,Oa={32212:function(){var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},32314:function(){var a="";if("undefined"!==typeof process)for(var b in process.env)a+=b+"="+process.env[b]+"\b";a+="\b";b=E(a)+1;const c=Na(b);D(a,H,c,b);return c},32572:function(a,b){a=a?C(H,a,b):"";if("undefined"!==typeof process&&a in process.env){a=process.env[a];b=E(a)+1;var c=Na(b);D(a,H,c,b);return c}return 0}};
function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.sb;"number"===typeof c?void 0===b.Qa?Qa(c)():Qa(c)(b.Qa):c(void 0===b.Qa?null:b.Qa)}}}var Ra=[];function Qa(a){var b=Ra[a];b||(a>=Ra.length&&(Ra.length=a+1),Ra[a]=b=za.get(a));return b}function Sa(a){a instanceof na||"unwind"==a||ea(1,a)}
function Ta(a){this.Na=a-16;this.Gb=function(b){I[this.Na+4>>2]=b};this.Db=function(b){I[this.Na+8>>2]=b};this.Eb=function(){I[this.Na>>2]=0};this.Cb=function(){F[this.Na+12>>0]=0};this.Fb=function(){F[this.Na+13>>0]=0};this.vb=function(b,c){this.Gb(b);this.Db(c);this.Eb();this.Cb();this.Fb()}}var Ua=0;
function Va(a,b){Wa=a;Xa=b;if(Ya)if(Za||(Za=!0),0==a)O=function(){var d=Math.max(0,$a+b-ab())|0;setTimeout(bb,d)};else if(1==a)O=function(){cb(bb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);l?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}O=function(){setImmediate(bb)}}}var ab;ab=ha?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function db(a){function b(){if(c<eb){if(!(noExitRuntime||0<oa))try{fb(sa)}catch(d){Sa(d)}return!1}return!0}!Ya||A("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ya=a;var c=eb;Za=!1;bb=function(){if(!B)if(0<gb.length){var d=Date.now(),e=gb.shift();e.sb(e.Qa);if(hb){var g=hb,k=0==g%1?g-1:Math.floor(g);hb=e.Pb?k:(8*g+(k+.5))/9}t('main loop blocker "'+e.name+
'" took '+(Date.now()-d)+" ms");f.setStatus&&(d=f.statusMessage||"Please wait...",e=hb,g=ib.Qb,e?e<g?f.setStatus(d+" ("+(g-e)+"/"+g+")"):f.setStatus(d):f.setStatus(""));b()&&setTimeout(bb,0)}else b()&&(jb=jb+1|0,1==Wa&&1<Xa&&0!=jb%Xa?O():(0==Wa&&($a=ab()),B||f.preMainLoop&&!1===f.preMainLoop()||(kb(a),f.postMainLoop&&f.postMainLoop()),b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.zb&&SDL.audio.zb(),O())))}}function kb(a){if(!Ea&&!B)try{a()}catch(b){Sa(b)}}
function lb(a){setTimeout(function(){kb(a)},1E4)}var Za=!1,O=null,eb=0,Ya=null,Wa=0,Xa=0,jb=0,gb=[],ib={},$a,bb,hb,mb=!1,nb=!1,ob=[];
function pb(){function a(){nb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!qb){qb=!0;try{rb=!0}catch(c){rb=!1,t("warning: no blob constructor, cannot create blobs with mimetypes")}sb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rb?null:t("warning: no BlobBuilder");tb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.nb||"undefined"!==typeof tb||(t("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.nb=!0);f.preloadPlugins.push({canHandle:function(c){return!f.nb&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=null;if(rb)try{k=new Blob([c],{type:ub(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:ub(d)}))}catch(q){pa("Blob constructor present but fails: "+
q+"; falling back to blob builder")}k||(k=new sb,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var p=tb.createObjectURL(k),u=new Image;u.onload=()=>{u.complete||A("Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=u.width;q.height=u.height;q.getContext("2d").drawImage(u,0,0);f.preloadedImages[d]=q;tb.revokeObjectURL(p);e&&e(c)};u.onerror=()=>{t("Image "+p+" could not be decoded");g&&g()};u.src=p}});f.preloadPlugins.push({canHandle:function(c){return!f.Ub&&c.substr(-4)in
{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function k(y){u||(u=!0,f.preloadedAudios[d]=y,e&&e(c))}function p(){u||(u=!0,f.preloadedAudios[d]=new Audio,g&&g())}var u=!1;if(rb){try{var q=new Blob([c],{type:ub(d)})}catch(y){return p()}q=tb.createObjectURL(q);var v=new Audio;v.addEventListener("canplaythrough",function(){k(v)},!1);v.onerror=function(){if(!u){t("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var y="",z=0,h=0,r=0;r<c.length;r++)for(z=
z<<8|c[r],h+=8;6<=h;){var w=z>>h-6&63;h-=6;y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[w]}2==h?(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&3)<<4],y+="=="):4==h&&(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&15)<<2],y+="=");v.src="data:audio/x-"+d.substr(-3)+";base64,"+y;k(v)}};v.src=q;lb(function(){k(v)})}else return p()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
function(c){!nb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function vb(a,b,c,d){if(b&&f.Ya&&a==f.canvas)return f.Ya;var e;if(b){var g={antialias:!1,alpha:!1,jb:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof wb&&(e=xb(a,g)))var p=P[e].Ka}else p=a.getContext("2d");if(!p)return null;c&&(b||"undefined"===typeof Q||A("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Ya=p,b&&yb(e),f.Mb=b,ob.forEach(function(u){u()}),pb());return p}var zb=!1,Ab=void 0,R=void 0;
function Bb(a,b){function c(){mb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Cb,Ab&&d.requestPointerLock(),mb=!0,R?("undefined"!=typeof SDL&&(I[SDL.screen>>2]=J[SDL.screen>>2]|8388608),Db(f.canvas),Eb()):Db(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),R?("undefined"!=typeof SDL&&(I[SDL.screen>>2]=J[SDL.screen>>2]&-8388609),
Db(f.canvas),Eb()):Db(d));if(f.onFullScreen)f.onFullScreen(mb);if(f.onFullscreen)f.onFullscreen(mb)}Ab=a;R=b;"undefined"===typeof Ab&&(Ab=!0);"undefined"===typeof R&&(R=!1);var d=f.canvas;zb||(zb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Cb(){if(!mb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Fb=0;function cb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Fb)Fb=b+1E3/60;else for(;b+2>=Fb;)Fb+=1E3/60;setTimeout(a,Math.max(Fb-b,0))}}
function ub(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Gb=[];function Eb(){var a=f.canvas;Gb.forEach(function(b){b(a.width,a.height)})}
function Db(a,b,c){b&&c?(a.Nb=b,a.ub=c):(b=a.Nb,c=a.ub);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}R?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qb,rb,sb,tb,S=12288,Hb=0,T={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ib;
function Jb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,k){b.drawElementsInstancedANGLE(c,d,e,g,k)})}
function Kb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Lb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function Mb(a){a.Ua=a.getExtension("WEBGL_multi_draw")}
var Nb=1,Ob=[],Pb=[],Qb=[],Rb=[],Sb=[],P=[],Tb=[],Ub={},Vb=4;function U(a){Wb||(Wb=a)}function Xb(a){for(var b=Nb++,c=a.length;c<b;c++)a[c]=null;return b}function xb(a,b){a.hb||(a.hb=a.getContext,a.getContext=function(d,e){e=a.hb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Yb(c,b):0}function Yb(a,b){var c=Xb(P),d={tb:c,attributes:b,version:b.jb,Ka:a};a.canvas&&(a.canvas.ob=d);P[c]=d;("undefined"===typeof b.rb||b.rb)&&Zb(d);return c}
function yb(a){V=P[a];f.Ya=Q=V&&V.Ka}function Zb(a){a||(a=V);if(!a.wb){a.wb=!0;var b=a.Ka;Jb(b);Kb(b);Lb(b);b.qb=b.getExtension("EXT_disjoint_timer_query");Mb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var wb={},Wb,V,$b=[],ac={};
function bc(){if(!cc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in ac)void 0===ac[b]?delete a[b]:a[b]=ac[b];var c=[];for(b in a)c.push(b+"="+a[b]);cc=c}return cc}var cc;
function dc(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ec(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=dc(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function fc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function gc(a){if("/"===a)return"/";a=ec(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function hc(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){A("randomDevice")}}
function ic(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=dc(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var jc=[];function kc(a,b){jc[a]={input:[],output:[],Ma:b};lc(a,mc)}
var mc={open:function(a){var b=jc[a.node.rdev];if(!b)throw new W(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ma.flush(a.tty)},flush:function(a){a.tty.Ma.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ma.ib)throw new W(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Ma.ib(a.tty)}catch(p){throw new W(29);}if(void 0===k&&0===e)throw new W(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ma.$a)throw new W(60);
try{for(var e=0;e<d;e++)a.tty.Ma.$a(a.tty,b[c+e])}catch(g){throw new W(29);}d&&(a.node.timestamp=Date.now());return e}},oc={ib:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nc(b,!0)}return a.input.shift()},$a:function(a,b){null===b||10===b?(t(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(t(C(a.output,0)),a.output=[])}},pc={$a:function(a,b){null===b||10===b?(n(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(n(C(a.output,0)),a.output=[])}},X={Ga:null,Ia:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new W(63);X.Ga||(X.Ga={dir:{node:{Ja:X.Ba.Ja,Ha:X.Ba.Ha,lookup:X.Ba.lookup,Sa:X.Ba.Sa,rename:X.Ba.rename,unlink:X.Ba.unlink,rmdir:X.Ba.rmdir,readdir:X.Ba.readdir,symlink:X.Ba.symlink},stream:{La:X.Da.La}},file:{node:{Ja:X.Ba.Ja,Ha:X.Ba.Ha},stream:{La:X.Da.La,read:X.Da.read,write:X.Da.write,bb:X.Da.bb,kb:X.Da.kb,mb:X.Da.mb}},link:{node:{Ja:X.Ba.Ja,Ha:X.Ba.Ha,readlink:X.Ba.readlink},stream:{}},cb:{node:{Ja:X.Ba.Ja,Ha:X.Ba.Ha},stream:qc}});c=rc(a,b,
c,d);16384===(c.mode&61440)?(c.Ba=X.Ga.dir.node,c.Da=X.Ga.dir.stream,c.Ca={}):32768===(c.mode&61440)?(c.Ba=X.Ga.file.node,c.Da=X.Ga.file.stream,c.Ea=0,c.Ca=null):40960===(c.mode&61440)?(c.Ba=X.Ga.link.node,c.Da=X.Ga.link.stream):8192===(c.mode&61440)&&(c.Ba=X.Ga.cb.node,c.Da=X.Ga.cb.stream);c.timestamp=Date.now();a&&(a.Ca[b]=c,a.timestamp=c.timestamp);return c},Rb:function(a){return a.Ca?a.Ca.subarray?a.Ca.subarray(0,a.Ea):new Uint8Array(a.Ca):new Uint8Array(0)},eb:function(a,b){var c=a.Ca?a.Ca.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ca,a.Ca=new Uint8Array(b),0<a.Ea&&a.Ca.set(c.subarray(0,a.Ea),0))},Ab:function(a,b){if(a.Ea!=b)if(0==b)a.Ca=null,a.Ea=0;else{var c=a.Ca;a.Ca=new Uint8Array(b);c&&a.Ca.set(c.subarray(0,Math.min(b,a.Ea)));a.Ea=b}},Ba:{Ja:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ea:40960===(a.mode&
61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.pb=4096;b.blocks=Math.ceil(b.size/b.pb);return b},Ha:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.Ab(a,b.size)},lookup:function(){throw sc[44];},Sa:function(a,b,c,d){return X.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tc(b,c)}catch(g){}if(d)for(var e in d.Ca)throw new W(55);
}delete a.parent.Ca[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ca[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ca[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=tc(a,b),d;for(d in c.Ca)throw new W(55);delete a.Ca[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ca)a.Ca.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new W(28);
return a.link}},Da:{read:function(a,b,c,d,e){var g=a.node.Ca;if(e>=a.node.Ea)return 0;a=Math.min(a.node.Ea-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ca||a.Ca.subarray)){if(g)return a.Ca=b.subarray(c,c+d),a.Ea=d;if(0===a.Ea&&0===e)return a.Ca=b.slice(c,c+d),a.Ea=d;if(e+d<=a.Ea)return a.Ca.set(b.subarray(c,c+d),e),d}X.eb(a,e+d);if(a.Ca.subarray&&b.subarray)a.Ca.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.Ca[e+g]=b[c+g];a.Ea=Math.max(a.Ea,e+d);return d},La:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ea);if(0>b)throw new W(28);return b},bb:function(a,b,c){X.eb(a.node,b+c);a.node.Ea=Math.max(a.node.Ea,b+c)},kb:function(a,b,c,d,e,g){if(0!==b)throw new W(28);if(32768!==(a.node.mode&61440))throw new W(43);a=a.node.Ca;if(g&2||a.buffer!==wa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;
A();c=void 0;if(!c)throw new W(48);F.set(a,c)}else d=!1,c=a.byteOffset;return{Na:c,Ob:d}},mb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new W(43);if(e&2)return 0;X.Da.write(a,b,0,d,c,!1);return 0}}},uc=null,vc={},wc=[],xc=1,yc=null,zc=!0,W=null,sc={};
function Y(a,b={}){a=ic("/",a);if(!a)return{path:"",node:null};var c={gb:!0,ab:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ab)throw new W(32);a=dc(a.split("/").filter(function(k){return!!k}),!1);var e=uc;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=tc(e,a[d]);c=ec(c+"/"+a[d]);e.Ta&&(!g||g&&b.gb)&&(e=e.Ta.root);if(!g||b.fb)for(g=0;40960===(e.mode&61440);)if(e=Ac(c),c=ic(fc(c),e),e=Y(c,{ab:b.ab}).node,40<g++)throw new W(32);}return{path:c,node:e}}
function Bc(a){for(var b;;){if(a===a.parent)return a=a.Ia.lb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Cc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yc.length}function tc(a,b){var c;if(c=(c=Dc(a,"x"))?c:a.Ba.lookup?0:2)throw new W(c,a);for(c=yc[Cc(a.id,b)];c;c=c.yb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ba.lookup(a,b)}
function rc(a,b,c,d){a=new Ec(a,b,c,d);b=Cc(a.parent.id,a.name);a.yb=yc[b];return yc[b]=a}var Fc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Hc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Dc(a,b){if(zc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ic(a,b){try{return tc(a,b),20}catch(c){}return Dc(a,"wx")}
function Jc(a=0,b=4096){for(;a<=b;a++)if(!wc[a])return a;throw new W(33);}function Kc(a){Lc||(Lc=function(){},Lc.prototype={});var b=new Lc,c;for(c in a)b[c]=a[c];a=b;b=Jc(void 0,void 0);a.fd=b;return wc[b]=a}var qc={open:function(a){a.Da=vc[a.node.rdev].Da;a.Da.open&&a.Da.open(a)},La:function(){throw new W(70);}};function lc(a,b){vc[a]={Da:b}}
function Mc(a,b){var c="/"===b,d=!b;if(c&&uc)throw new W(10);if(!c&&!d){var e=Y(b,{gb:!1});b=e.path;e=e.node;if(e.Ta)throw new W(10);if(16384!==(e.mode&61440))throw new W(54);}b={type:a,Vb:{},lb:b,xb:[]};a=a.Ia(b);a.Ia=b;b.root=a;c?uc=a:e&&(e.Ta=b,e.Ia&&e.Ia.xb.push(b))}function Nc(a,b,c){var d=Y(a,{parent:!0}).node;a=gc(a);if(!a||"."===a||".."===a)throw new W(28);var e=Ic(d,a);if(e)throw new W(e);if(!d.Ba.Sa)throw new W(63);return d.Ba.Sa(d,a,b,c)}function Z(a){return Nc(a,16895,0)}
function Oc(a,b,c){"undefined"===typeof c&&(c=b,b=438);Nc(a,b|8192,c)}function Pc(a,b){if(!ic(a))throw new W(44);var c=Y(b,{parent:!0}).node;if(!c)throw new W(44);b=gc(b);var d=Ic(c,b);if(d)throw new W(d);if(!c.Ba.symlink)throw new W(63);c.Ba.symlink(c,b,a)}function Ac(a){a=Y(a).node;if(!a)throw new W(44);if(!a.Ba.readlink)throw new W(28);return ic(Bc(a.parent),a.Ba.readlink(a))}
function Qc(a,b){if(""===a)throw new W(44);if("string"===typeof b){var c=Fc[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=ec(a);try{e=Y(a,{fb:!(b&131072)}).node}catch(g){}}c=!1;if(b&64)if(e){if(b&128)throw new W(20);}else e=Nc(a,d,0),c=!0;if(!e)throw new W(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new W(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Hc(b)||b&512)?31:Dc(e,Hc(b)):44))throw new W(d);if(b&512){d=e;d="string"===typeof d?Y(d,{fb:!0}).node:d;if(!d.Ba.Ha)throw new W(63);if(16384===(d.mode&61440))throw new W(31);if(32768!==(d.mode&61440))throw new W(28);if(c=Dc(d,"w"))throw new W(c);d.Ba.Ha(d,{size:0,timestamp:Date.now()})}b&=-131713;e=Kc({node:e,path:Bc(e),id:e.id,flags:b,mode:e.mode,seekable:!0,position:0,Da:e.Da,Ba:e.Ba,Lb:[],error:!1});e.Da.open&&e.Da.open(e);!f.logReadFiles||b&1||(Rc||(Rc={}),a in
Rc||(Rc[a]=1))}function Sc(a,b,c){if(null===a.fd)throw new W(8);if(!a.seekable||!a.Da.La)throw new W(70);if(0!=c&&1!=c&&2!=c)throw new W(28);a.position=a.Da.La(a,b,c);a.Lb=[]}function Tc(){W||(W=function(a,b){this.node=b;this.Bb=function(c){this.Ra=c};this.Bb(a);this.message="FS error"},W.prototype=Error(),W.prototype.constructor=W,[44].forEach(function(a){sc[a]=new W(a);sc[a].stack="<generic error, no stack>"}))}var Uc;function Vc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Wc(a,b,c){a=ec("/dev/"+a);var d=Vc(!!b,!!c);Xc||(Xc=64);var e=Xc++<<8|0;lc(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,k,p,u){for(var q=0,v=0;v<u;v++){try{var y=b()}catch(z){throw new W(29);}if(void 0===y&&0===q)throw new W(6);if(null===y||void 0===y)break;q++;k[p+v]=y}q&&(g.node.timestamp=Date.now());return q},write:function(g,k,p,u){for(var q=0;q<u;q++)try{c(k[p+q])}catch(v){throw new W(29);}u&&(g.node.timestamp=Date.now());return q}});
Oc(a,d,e)}var Xc,Yc={},Lc,Rc;function Zc(a){a=wc[a];if(!a)throw new W(8);return a}var $c=[];function ad(a,b,c,d){for(var e=0;e<a;e++){var g=Q[c](),k=g&&Xb(d);g?(g.name=k,d[k]=g):U(1282);I[b+4*e>>2]=k}}
function bd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=Q.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=Q.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:I[b+4*a>>2]=e[a];break;case 2:K[b+4*a>>2]=e[a];break;case 4:F[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){U(1280);n("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:U(1280);n("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=
d;J[b>>2]=c;J[b+4>>2]=(c-J[b>>2])/4294967296;break;case 0:I[b>>2]=d;break;case 2:K[b>>2]=d;break;case 4:F[b>>0]=d?1:0}}else U(1281)}function cd(a){var b=E(a)+1,c=Na(b);D(a,H,c,b);return c}function dd(a,b,c,d,e){a-=5120;a=1==a?H:4==a?I:6==a?K:5==a||28922==a?J:xa;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),k=Vb;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+k-1&-k)>>g)}function ed(a){return 0===a%4&&(0!==a%100||0===a%400)}
function fd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var gd=[31,29,31,30,31,30,31,31,30,31,30,31],hd=[31,28,31,30,31,30,31,31,30,31,30,31];function jd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(ed(a.getFullYear())?gd:hd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function kd(a,b,c,d){function e(h,r,w){for(h="number"===typeof h?h.toString():h||"";h.length<r;)h=w[0]+h;return h}function g(h,r){return e(h,r,"0")}function k(h,r){function w(Gc){return 0>Gc?-1:0<Gc?1:0}var G;0===(G=w(h.getFullYear()-r.getFullYear()))&&0===(G=w(h.getMonth()-r.getMonth()))&&(G=w(h.getDate()-r.getDate()));return G}function p(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function u(h){h=jd(new Date(h.Fa+1900,0,1),h.Xa);var r=new Date(h.getFullYear()+1,0,4),w=p(new Date(h.getFullYear(),0,4));r=p(r);return 0>=k(w,h)?0>=k(r,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var q=I[d+40>>2];d={Jb:I[d>>2],Ib:I[d+4>>2],Va:I[d+8>>2],Pa:I[d+12>>2],Oa:I[d+16>>2],Fa:I[d+20>>2],Wa:I[d+24>>2],Xa:I[d+28>>2],Xb:I[d+32>>2],Hb:I[d+
36>>2],Kb:q?q?C(H,q,void 0):"":""};c=c?C(H,c,void 0):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in q)c=c.replace(new RegExp(v,"g"),q[v]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
z="January February March April May June July August September October November December".split(" ");q={"%a":function(h){return y[h.Wa].substring(0,3)},"%A":function(h){return y[h.Wa]},"%b":function(h){return z[h.Oa].substring(0,3)},"%B":function(h){return z[h.Oa]},"%C":function(h){return g((h.Fa+1900)/100|0,2)},"%d":function(h){return g(h.Pa,2)},"%e":function(h){return e(h.Pa,2," ")},"%g":function(h){return u(h).toString().substring(2)},"%G":function(h){return u(h)},"%H":function(h){return g(h.Va,
2)},"%I":function(h){h=h.Va;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Pa+fd(ed(h.Fa+1900)?gd:hd,h.Oa-1),3)},"%m":function(h){return g(h.Oa+1,2)},"%M":function(h){return g(h.Ib,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Va&&12>h.Va?"AM":"PM"},"%S":function(h){return g(h.Jb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Wa||7},"%U":function(h){var r=new Date(h.Fa+1900,0,1),w=0===r.getDay()?r:jd(r,7-r.getDay());h=new Date(h.Fa+1900,h.Oa,h.Pa);return 0>
k(w,h)?g(Math.ceil((31-w.getDate()+(fd(ed(h.getFullYear())?gd:hd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(w,r)?"01":"00"},"%V":function(h){var r=new Date(h.Fa+1901,0,4),w=p(new Date(h.Fa+1900,0,4));r=p(r);var G=jd(new Date(h.Fa+1900,0,1),h.Xa);return 0>k(G,w)?"53":0>=k(r,G)?"01":g(Math.ceil((w.getFullYear()<h.Fa+1900?h.Xa+32-w.getDate():h.Xa+1-w.getDate())/7),2)},"%w":function(h){return h.Wa},"%W":function(h){var r=new Date(h.Fa,0,1),w=1===r.getDay()?r:jd(r,0===r.getDay()?1:7-r.getDay()+1);h=
new Date(h.Fa+1900,h.Oa,h.Pa);return 0>k(w,h)?g(Math.ceil((31-w.getDate()+(fd(ed(h.getFullYear())?gd:hd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(w,r)?"01":"00"},"%y":function(h){return(h.Fa+1900).toString().substring(2)},"%Y":function(h){return h.Fa+1900},"%z":function(h){h=h.Hb;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Kb},"%%":function(){return"%"}};for(v in q)c.includes(v)&&(c=c.replace(new RegExp(v,"g"),q[v](d)));v=nc(c,
!1);if(v.length>b)return 0;F.set(v,a);return v.length-1}f.requestFullscreen=function(a,b){Bb(a,b)};f.requestAnimationFrame=function(a){cb(a)};f.setCanvasSize=function(a,b,c){Db(f.canvas,a,b);c||Eb()};f.pauseMainLoop=function(){O=null;eb++};f.resumeMainLoop=function(){eb++;var a=Wa,b=Xa,c=Ya;Ya=null;db(c);Va(a,b);O()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return vb(a,b,c,d)};var Q;function Ec(a,b,c,d){a||(a=this);this.parent=a;this.Ia=a.Ia;this.Ta=null;this.id=xc++;this.name=b;this.mode=c;this.Ba={};this.Da={};this.rdev=d}Object.defineProperties(Ec.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Tc();yc=Array(4096);Mc(X,"/");Z("/tmp");Z("/home");Z("/home/web_user");
(function(){Z("/dev");lc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Oc("/dev/null",259);kc(1280,oc);kc(1536,pc);Oc("/dev/tty",1280);Oc("/dev/tty1",1536);var a=hc();Wc("random",a);Wc("urandom",a);Z("/dev/shm");Z("/dev/shm/tmp")})();
(function(){Z("/proc");var a=Z("/proc/self");Z("/proc/self/fd");Mc({Ia:function(){var b=rc(a,"fd",16895,73);b.Ba={lookup:function(c,d){var e=wc[+d];if(!e)throw new W(8);c={parent:null,Ia:{lb:"fake"},Ba:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var ld=0;32>ld;++ld)$c.push(Array(ld));function nc(a,b){var c=Array(E(a)+1);a=D(a,c,0,c.length);b&&(c.length=a);return c}
var md={ra:function(a){return Na(a+16)+16},qa:function(a,b,c){(new Ta(a)).vb(b,c);Ua++;throw a;},a:function(){A("")},E:function(a){if(12448==a)return S=12288,1;S=12300;return 0},D:function(a,b,c,d,e){if(62E3!=a)S=12296,c=0;else{if(b)for(;;){a=I[b>>2];if(12321==a)T.alpha=0<I[b+4>>2];else if(12325==a)T.depth=0<I[b+4>>2];else if(12326==a)T.stencil=0<I[b+4>>2];else if(12337==a)a=I[b+4>>2],T.antialias=0<a;else if(12338==a)a=I[b+4>>2],T.antialias=1==a;else if(12544==a)T.Sb=12547!=I[b+4>>2];else if(12344==
a)break;b+=8}c&&d||e?(e&&(I[e>>2]=1),c&&0<d&&(I[c>>2]=62002),S=12288,c=1):(S=12300,c=0)}return c},C:function(a,b,c,d){if(62E3!=a)return S=12296,0;for(a=1;;){b=I[d>>2];if(12440==b)a=I[d+4>>2];else if(12344==b)break;else return S=12292,0;d+=8}if(2!=a)return S=12293,0;T.jb=a-1;T.Tb=0;Ib=xb(f.canvas,T);if(0!=Ib)return S=12288,yb(Ib),f.Mb=!0,ob.forEach(function(e){e()}),yb(null),62004;S=12297;return 0},l:function(a,b){if(62E3!=a)return S=12296,0;if(62004!=b)return S=12294,0;a=Ib;V===P[a]&&(V=null);"object"===
typeof JSEvents&&JSEvents.Wb(P[a].Ka.canvas);P[a]&&P[a].Ka.canvas&&(P[a].Ka.canvas.ob=void 0);P[a]=null;S=12288;Hb==b&&(Hb=0);return 1},H:function(){S=12288;return 62E3},d:function(){return S},G:function(a,b,c){if(62E3==a)return b&&(I[b>>2]=1),c&&(I[c>>2]=4),S=12288,1;S=12296;return 0},f:function(a,b,c,d){if(62E3!=a)return S=12296,0;if(0!=d&&62004!=d)return S=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return S=12301,0;yb(d?Ib:null);Hb=d;S=12288;return 1},k:function(a){if(62E3!=a)return S=12296,0;Hb=
0;S=12288;return 1},o:function(a,b,c){$b.length=0;var d;for(c>>=2;d=H[b++];)(d=105>d)&&c&1&&c++,$b.push(d?ya[c++>>1]:I[c]),++c;return Oa[a].apply(null,$b)},y:function(a,b,c){H.copyWithin(a,b,b+c)},v:function(){A("OOM")},aa:function(a,b){a=P[a];b=b?C(H,b,void 0):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Jb(Q);"OES_vertex_array_object"==b&&Kb(Q);"WEBGL_draw_buffers"==b&&Lb(Q);"WEBGL_multi_draw"==b&&Mb(Q);return!!a.Ka.getExtension(b)},ba:function(){return V?V.tb:0},A:function(a,
b){var c=0;bc().forEach(function(d,e){var g=b+c;e=I[a+4*e>>2]=g;for(g=0;g<d.length;++g)F[e++>>0]=d.charCodeAt(g);F[e>>0]=0;c+=d.length+1});return 0},B:function(a,b){var c=bc();I[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});I[b>>2]=d;return 0},i:function(a){fb(a)},z:function(a){try{var b=Zc(a);if(null===b.fd)throw new W(8);b.Za&&(b.Za=null);try{b.Da.close&&b.Da.close(b)}catch(c){throw c;}finally{wc[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"===typeof Yc||!(c instanceof W))throw c;
return c.Ra}},w:function(a,b,c,d){try{a:{for(var e=Zc(a),g=a=0;g<c;g++){var k=I[b+(8*g+4)>>2],p=e,u=I[b+8*g>>2],q=k,v=void 0,y=F;if(0>q||0>v)throw new W(28);if(null===p.fd)throw new W(8);if(1===(p.flags&2097155))throw new W(8);if(16384===(p.node.mode&61440))throw new W(31);if(!p.Da.read)throw new W(28);var z="undefined"!==typeof v;if(!z)v=p.position;else if(!p.seekable)throw new W(70);var h=p.Da.read(p,y,u,q,v);z||(p.position+=h);var r=h;if(0>r){var w=-1;break a}a+=r;if(r<k)break}w=a}I[d>>2]=w;return 0}catch(G){if("undefined"===
typeof Yc||!(G instanceof W))throw G;return G.Ra}},t:function(a,b,c,d,e){try{var g=Zc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Sc(g,a,d);Ma=[g.position>>>0,(N=g.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];I[e>>2]=Ma[0];I[e+4>>2]=Ma[1];g.Za&&0===a&&0===d&&(g.Za=null);return 0}catch(k){if("undefined"===typeof Yc||!(k instanceof W))throw k;return k.Ra}},j:function(a,b,c,d){try{a:{for(var e=
Zc(a),g=a=0;g<c;g++){var k=e,p=I[b+8*g>>2],u=I[b+(8*g+4)>>2],q=void 0,v=F;if(0>u||0>q)throw new W(28);if(null===k.fd)throw new W(8);if(0===(k.flags&2097155))throw new W(8);if(16384===(k.node.mode&61440))throw new W(31);if(!k.Da.write)throw new W(28);k.seekable&&k.flags&1024&&Sc(k,0,2);var y="undefined"!==typeof q;if(!y)q=k.position;else if(!k.seekable)throw new W(70);var z=k.Da.write(k,v,p,u,q,void 0);y||(k.position+=z);var h=z;if(0>h){var r=-1;break a}a+=h}r=a}I[d>>2]=r;return 0}catch(w){if("undefined"===
typeof Yc||!(w instanceof W))throw w;return w.Ra}},h:function(a){Q.activeTexture(a)},p:function(a,b){Q.bindBuffer(a,Ob[b])},$:function(a,b){Q.bindFramebuffer(a,Pb[b])},r:function(a,b){Q.bindRenderbuffer(a,Qb[b])},n:function(a,b){Q.bindTexture(a,Rb[b])},e:function(a){Q.bindVertexArray(Sb[a])},ma:function(a,b,c,d){Q.bufferData(a,c?H.subarray(c,c+b):b,d)},la:function(a,b,c,d){Q.bufferSubData(a,b,H.subarray(d,d+c))},_:function(a){return Q.checkFramebufferStatus(a)},ta:function(a,b,c,d){Q.clearColor(a,
b,c,d)},sa:function(a){Q.clearDepth(a)},m:function(a,b,c,d,e,g,k,p,u){Q.compressedTexSubImage2D(a,b,c,d,e,g,k,u?H.subarray(u,u+p):null)},X:function(a,b,c,d,e,g,k,p){Q.copyTexSubImage2D(a,b,c,d,e,g,k,p)},oa:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>2],e=Ob[d];e&&(Q.deleteBuffer(e),e.name=0,Ob[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>2];Q.deleteVertexArray(Sb[d]);Sb[d]=null}},I:function(a){Q.disableVertexAttribArray(a)},Q:function(a,b,c){Q.drawArrays(a,b,c)},fa:function(a,
b,c,d){Q.drawArraysInstanced(a,b,c,d)},Z:function(a,b){for(var c=$c[a],d=0;d<a;d++)c[d]=I[b+4*d>>2];Q.drawBuffers(c)},P:function(a,b,c,d){Q.drawElements(a,b,c,d)},ga:function(a,b,c,d,e){Q.drawElementsInstanced(a,b,c,d,e)},L:function(a){Q.enableVertexAttribArray(a)},F:function(a,b,c,d){Q.framebufferRenderbuffer(a,b,c,Qb[d])},x:function(a,b,c,d,e){Q.framebufferTexture2D(a,b,c,Rb[d],e)},pa:function(a,b){ad(a,b,"createBuffer",Ob)},O:function(a,b){ad(a,b,"createFramebuffer",Pb)},da:function(a,b){for(var c=
0;c<a;c++){var d=Q.qb.createQueryEXT();if(!d){for(U(1282);c<a;)I[b+4*c++>>2]=0;break}var e=Xb(Tb);d.name=e;Tb[e]=d;I[b+4*c>>2]=e}},s:function(a,b){ad(a,b,"createRenderbuffer",Qb)},W:function(a,b){ad(a,b,"createTexture",Rb)},N:function(a,b){ad(a,b,"createVertexArray",Sb)},V:function(a){Q.generateMipmap(a)},na:function(a,b,c){c?I[c>>2]=Q.getBufferParameter(a,b):U(1281)},ca:function(){var a=Q.getError()||Wb;Wb=0;return a},q:function(a,b){bd(a,b,2)},b:function(a,b){bd(a,b,0)},c:function(a){var b=Ub[a];
if(!b){switch(a){case 7939:b=Q.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=cd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||U(1280);b=b&&cd(b);break;case 7938:b=cd("OpenGL ES 2.0 ("+Q.getParameter(7938)+")");break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=cd(b);break;default:U(1280)}Ub[a]=b}return b},
ja:function(a,b,c,d){Q.Ua.multiDrawArraysWEBGL(a,I,b>>2,I,c>>2,d)},ha:function(a,b,c,d,e){Q.Ua.multiDrawArraysInstancedWEBGL(a,I,b>>2,I,c>>2,I,d>>2,e)},ka:function(a,b,c,d,e){Q.Ua.multiDrawElementsWEBGL(a,I,b>>2,c,I,d>>2,e)},ia:function(a,b,c,d,e,g){Q.Ua.multiDrawElementsInstancedWEBGL(a,I,b>>2,c,I,d>>2,I,e>>2,g)},ea:function(a,b){3317==a&&(Vb=b);Q.pixelStorei(a,b)},Y:function(a,b,c,d,e,g,k){(k=dd(g,e,c,d,k))?Q.readPixels(a,b,c,d,e,g,k):U(1280)},ua:function(a,b,c,d){Q.renderbufferStorage(a,b,c,d)},
R:function(a,b,c,d,e,g,k,p,u){Q.texImage2D(a,b,c,d,e,g,k,p,u?dd(p,k,d,e,u):null)},T:function(a,b,c){Q.texParameterf(a,b,c)},S:function(a,b,c){Q.texParameterf(a,b,K[c>>2])},U:function(a,b,c){Q.texParameteri(a,b,c)},g:function(a,b,c,d,e,g,k,p,u){var q=null;u&&(q=dd(p,k,e,g,u));Q.texSubImage2D(a,b,c,d,e,g,k,p,q)},J:function(a,b){Q.vertexAttribDivisor(a,b)},K:function(a,b,c,d,e,g){Q.vertexAttribPointer(a,b,c,!!d,e,g)},u:function(a,b,c,d){return kd(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;ra=f.asm.va;wa=e=ra.buffer;f.HEAP8=F=new Int8Array(e);f.HEAP16=new Int16Array(e);f.HEAP32=I=new Int32Array(e);f.HEAPU8=H=new Uint8Array(e);f.HEAPU16=xa=new Uint16Array(e);f.HEAPU32=J=new Uint32Array(e);f.HEAPF32=K=new Float32Array(e);f.HEAPF64=ya=new Float64Array(e);za=f.asm.ya;Ba.unshift(f.asm.wa);L--;f.monitorRunDependencies&&f.monitorRunDependencies(L);0==L&&(null!==Ga&&(clearInterval(Ga),Ga=null),Ha&&(e=Ha,Ha=null,e()))}function b(e){a(e.instance)}function c(e){return La().then(function(g){return WebAssembly.instantiate(g,
d)}).then(function(g){return g}).then(e,function(g){n("failed to asynchronously prepare wasm: "+g);A(g)})}var d={a:md};L++;f.monitorRunDependencies&&f.monitorRunDependencies(L);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return n("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return x||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||M.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(g){n("wasm streaming compile failed: "+g);n("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.wa).apply(null,arguments)};f._main=function(){return(f._main=f.asm.xa).apply(null,arguments)};var Na=f._malloc=function(){return(Na=f._malloc=f.asm.za).apply(null,arguments)},va=f.stackAlloc=function(){return(va=f.stackAlloc=f.asm.Aa).apply(null,arguments)},nd;
function na(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ha=function od(){nd||pd();nd||(Ha=od)};
function pd(a){function b(){if(!nd&&(nd=!0,f.calledRun=!0,!B)){f.noFSInit||Uc||(Uc=!0,Tc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Wc("stdin",f.stdin):Pc("/dev/tty","/dev/stdin"),f.stdout?Wc("stdout",null,f.stdout):Pc("/dev/tty","/dev/stdout"),f.stderr?Wc("stderr",null,f.stderr):Pc("/dev/tty1","/dev/stderr"),Qc("/dev/stdin",0),Qc("/dev/stdout",1),Qc("/dev/stderr",1));zc=!1;Pa(Ba);Pa(Ca);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(qd){var c=a,d=f._main;c=c||[];var e=c.length+
1,g=va(4*(e+1));I[g>>2]=ua(da);for(var k=1;k<e;k++)I[(g>>2)+k]=ua(c[k-1]);I[(g>>2)+e]=0;try{var p=d(e,g);fb(p)}catch(u){Sa(u)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Da.unshift(c);Pa(Da)}}a=a||ca;if(!(0<L)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Fa();Pa(Aa);0<L||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}
f.run=pd;function fb(a){sa=a;noExitRuntime||0<oa||(Ea=!0);sa=a;if(!(noExitRuntime||0<oa)){if(f.onExit)f.onExit(a);B=!0}ea(a,new na(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var qd=!0;f.noInitialRun&&(qd=!1);pd();
