var f;var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa={},l;for(l in h)h.hasOwnProperty(l)&&(aa[l]=h[l]);h.arguments=[];h.thisProgram="./this.program";h.quit=function(a,b){throw b;};h.preRun=[];h.postRun=[];var ba=!1,n=!1,p=!1,ca=!1;ba="object"===typeof window;n="function"===typeof importScripts;p="object"===typeof process&&"function"===typeof require&&!ba&&!n;ca=!ba&&!p&&!n;var q="";
if(p){q=__dirname+"/";var da,ea;h.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};h.readBinary=function(a){a=h.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(h.thisProgram=process.argv[1].replace(/\\/g,"/"));h.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof u))throw a;});process.on("unhandledRejection",
y);h.quit=function(a){process.exit(a)};h.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(h.read=function(a){return read(a)}),h.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?h.arguments=scriptArgs:"undefined"!=typeof arguments&&(h.arguments=arguments),"function"===typeof quit&&(h.quit=function(a){quit(a)});else if(ba||n)n?
q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",h.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(h.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),h.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},h.setWindowTitle=function(a){document.title=a};var fa=h.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),z=h.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(l in aa)aa.hasOwnProperty(l)&&(h[l]=aa[l]);aa=void 0;function ha(a){var b=A[ia>>2];a=b+a+15&-16;if(a<=ja())A[ia>>2]=a;else return 0;return b}
function ka(a){la||(la={});la[a]||(la[a]=1,z(a))}var la,ma={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&z("no native wasm support detected");var na,C=!1;function assert(a,b){a||y("Assertion failed: "+b)}
function oa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=D(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)A[a>>2]=0;for(b=d+c;a<b;)E[a++>>0]=0;return d}a.subarray||a.slice?F.set(a,d):F.set(new Uint8Array(a),d);return d}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function ra(a){return a?qa(F,a,void 0):""}
function sa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var t=a.charCodeAt(++g);k=65536+((k&1023)<<10)|t&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ua(a){var b=ta(a)+1,c=va(b);sa(a,E,c,b);return c}var buffer,E,F,A,ia=26096,wa=h.TOTAL_MEMORY||16777216;5242880>wa&&z("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+wa+"! (TOTAL_STACK=5242880)");
h.buffer?buffer=h.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(na=new WebAssembly.Memory({initial:wa/65536,maximum:wa/65536}),buffer=na.buffer):buffer=new ArrayBuffer(wa);h.HEAP8=E=new Int8Array(buffer);h.HEAP16=new Int16Array(buffer);h.HEAP32=A=new Int32Array(buffer);h.HEAPU8=F=new Uint8Array(buffer);h.HEAPU16=new Uint16Array(buffer);h.HEAPU32=new Uint32Array(buffer);h.HEAPF32=new Float32Array(buffer);h.HEAPF64=new Float64Array(buffer);A[ia>>2]=5269232;
function xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.na;"number"===typeof c?void 0===b.ra?h.dynCall_v(c):h.dynCall_vi(c,b.ra):c(void 0===b.ra?null:b.ra)}}}var ya=[],za=[],Aa=[],Ba=[],Ca=!1;
function Da(){Ca||(Ca=!0,h.noFSInit||Ea||(Ea=!0,Fa(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Ga("stdin",h.stdin):Ha("/dev/tty","/dev/stdin"),h.stdout?Ga("stdout",null,h.stdout):Ha("/dev/tty","/dev/stdout"),h.stderr?Ga("stderr",null,h.stderr):Ha("/dev/tty1","/dev/stderr"),Ia("/dev/stdin","r"),Ia("/dev/stdout","w"),Ia("/dev/stderr","w")),xa(za))}function Ja(){var a=h.preRun.shift();ya.unshift(a)}var G=0,Ka=null,La=null;
function Ma(){G++;h.monitorRunDependencies&&h.monitorRunDependencies(G)}function Na(){G--;h.monitorRunDependencies&&h.monitorRunDependencies(G);if(0==G&&(null!==Ka&&(clearInterval(Ka),Ka=null),La)){var a=La;La=null;a()}}h.preloadedImages={};h.preloadedAudios={};function Oa(){var a=H;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var H="magnum-al-info.wasm";
if(!Oa()){var Pa=H;H=h.locateFile?h.locateFile(Pa,q):q+Pa}function Qa(){try{if(h.wasmBinary)return new Uint8Array(h.wasmBinary);if(h.readBinary)return h.readBinary(H);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}
function Ra(){return h.wasmBinary||!ba&&!n||"function"!==typeof fetch?new Promise(function(a){a(Qa())}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Qa()})}
function Sa(a){function b(a){h.asm=a.exports;Na()}function c(a){b(a.instance)}function d(a){Ra().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);y(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ma};Ma();if(h.instantiateWasm)try{return h.instantiateWasm(e,b)}catch(g){return z("Module.instantiateWasm callback failed with error: "+g),!1}h.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Oa()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(H,{credentials:"same-origin"}),e).then(c,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");d(c)});return{}}h.asm=function(a,b){b.memory=na;b.table=new WebAssembly.Table({initial:502,maximum:502,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Sa(b)};var Ua=[function(a){a=ra(a);return"undefined"!==typeof process&&a in process.env?oa(Ta(process.env[a])):0}];
za.push({na:function(){Va()}},{na:function(){Wa()}});var K={};
function Xa(a){if(Xa.Yb){var b=A[a>>2];var c=A[b>>2]}else Xa.Yb=!0,K.USER=K.LOGNAME="web_user",K.PATH="/",K.PWD="/",K.HOME="/home/web_user",K.LANG="C.UTF-8",K._=h.thisProgram,c=Ca?D(1024):ha(1024),b=Ca?D(256):ha(256),A[b>>2]=c,A[a>>2]=b;a=[];var d=0,e;for(e in K)if("string"===typeof K[e]){var g=e+"="+K[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=a[e];for(var k=c,t=0;t<d.length;++t)E[k++>>0]=d.charCodeAt(t);E[k>>0]=0;A[b+4*
e>>2]=c;c+=g.length+1}A[b+4*a.length>>2]=0}function Ya(a){h.___errno_location&&(A[h.___errno_location()>>2]=a);return a}function Za(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ab(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function bb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function cb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function eb(){var a=Array.prototype.slice.call(arguments,0);return ab(a.join("/"))}function L(a,b){return ab(a+"/"+b)}
function fb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Za(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var gb=[];function hb(a,b){gb[a]={input:[],output:[],Ba:b};ib(a,jb)}
var jb={open:function(a){var b=gb[a.node.rdev];if(!b)throw new M(N.cb);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ba.flush(a.tty)},flush:function(a){a.tty.Ba.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ba.Hb)throw new M(N.sb);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Ba.Hb(a.tty)}catch(t){throw new M(N.qb);}if(void 0===k&&0===e)throw new M(N.Sb);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ba.mb)throw new M(N.sb);
try{for(var e=0;e<d;e++)a.tty.Ba.mb(a.tty,b[c+e])}catch(g){throw new M(N.qb);}d&&(a.node.timestamp=Date.now());return e}},kb={Hb:function(a){if(!a.input.length){var b=null;if(p){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(e,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ta(b,!0)}return a.input.shift()},mb:function(a,b){null===b||10===b?(fa(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(fa(qa(a.output,0)),a.output=[])}},lb={mb:function(a,b){null===b||10===b?(z(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(z(qa(a.output,0)),a.output=[])}},P={ma:null,ea:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(N.Wb);P.ma||(P.ma={dir:{node:{oa:P.Z.oa,ha:P.Z.ha,lookup:P.Z.lookup,Ha:P.Z.Ha,rename:P.Z.rename,unlink:P.Z.unlink,rmdir:P.Z.rmdir,readdir:P.Z.readdir,symlink:P.Z.symlink},stream:{pa:P.Y.pa}},file:{node:{oa:P.Z.oa,ha:P.Z.ha},stream:{pa:P.Y.pa,read:P.Y.read,write:P.Y.write,wb:P.Y.wb,Kb:P.Y.Kb,Xa:P.Y.Xa}},link:{node:{oa:P.Z.oa,
ha:P.Z.ha,readlink:P.Z.readlink},stream:{}},yb:{node:{oa:P.Z.oa,ha:P.Z.ha},stream:mb}});c=nb(a,b,c,d);16384===(c.mode&61440)?(c.Z=P.ma.dir.node,c.Y=P.ma.dir.stream,c.X={}):32768===(c.mode&61440)?(c.Z=P.ma.file.node,c.Y=P.ma.file.stream,c.$=0,c.X=null):40960===(c.mode&61440)?(c.Z=P.ma.link.node,c.Y=P.ma.link.stream):8192===(c.mode&61440)&&(c.Z=P.ma.yb.node,c.Y=P.ma.yb.stream);c.timestamp=Date.now();a&&(a.X[b]=c);return c},We:function(a){if(a.X&&a.X.subarray){for(var b=[],c=0;c<a.$;++c)b.push(a.X[c]);
return b}return a.X},Xe:function(a){return a.X?a.X.subarray?a.X.subarray(0,a.$):new Uint8Array(a.X):new Uint8Array},Ab:function(a,b){var c=a.X?a.X.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.X,a.X=new Uint8Array(b),0<a.$&&a.X.set(c.subarray(0,a.$),0))},jc:function(a,b){if(a.$!=b)if(0==b)a.X=null,a.$=0;else{if(!a.X||a.X.subarray){var c=a.X;a.X=new Uint8Array(new ArrayBuffer(b));c&&a.X.set(c.subarray(0,Math.min(b,a.$)))}else if(a.X||(a.X=[]),a.X.length>b)a.X.length=
b;else for(;a.X.length<b;)a.X.push(0);a.$=b}},Z:{oa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.$:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.sa=4096;b.blocks=Math.ceil(b.size/b.sa);return b},ha:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&
(a.timestamp=b.timestamp);void 0!==b.size&&P.jc(a,b.size)},lookup:function(){throw ob[N.Ub];},Ha:function(a,b,c,d){return P.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pb(b,c)}catch(g){}if(d)for(var e in d.X)throw new M(N.rb);}delete a.parent.X[a.name];a.name=c;b.X[c]=a;a.parent=b},unlink:function(a,b){delete a.X[b]},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.X)throw new M(N.rb);delete a.X[b]},readdir:function(a){var b=[".",".."],c;for(c in a.X)a.X.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new M(N.va);return a.link}},Y:{read:function(a,b,c,d,e){var g=a.node.X;if(e>=a.node.$)return 0;a=Math.min(a.node.$-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.X||a.X.subarray)){if(g)return a.X=b.subarray(c,c+d),
a.$=d;if(0===a.$&&0===e)return a.X=new Uint8Array(b.subarray(c,c+d)),a.$=d;if(e+d<=a.$)return a.X.set(b.subarray(c,c+d),e),d}P.Ab(a,e+d);if(a.X.subarray&&b.subarray)a.X.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.X[e+g]=b[c+g];a.$=Math.max(a.$,e+d);return d},pa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.$);if(0>b)throw new M(N.va);return b},wb:function(a,b,c){P.Ab(a.node,b+c);a.node.$=Math.max(a.node.$,b+c)},Kb:function(a,b,c,d,e,g,k){if(32768!==(a.node.mode&
61440))throw new M(N.cb);c=a.node.X;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.$)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=D(d);if(!d)throw new M(N.Vb);b.set(c,d)}else a=!1,d=c.byteOffset;return{gf:d,Xb:a}},Xa:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(N.cb);if(e&2)return 0;P.Y.write(a,b,0,d,c,!1);return 0}}},Q={Qa:!1,sc:function(){Q.Qa=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);Q.Cb={1024:a.O_APPEND,
64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},xb:function(a){return Buffer.ia?Buffer.from(a):new Buffer(a)},ea:function(a){assert(p);return Q.createNode(null,"/",Q.Gb(a.kb.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new M(N.va);a=nb(a,b,c);a.Z=Q.Z;a.Y=Q.Y;return a},Gb:function(a){try{var b=fs.lstatSync(a);Q.Qa&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);
}return b.mode},fa:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.ea.kb.root);b.reverse();return eb.apply(null,b)},Zb:function(a){a&=-2656257;var b=0,c;for(c in Q.Cb)a&c&&(b|=Q.Cb[c],a^=c);if(a)throw new M(N.va);return b},Z:{oa:function(a){a=Q.fa(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}Q.Qa&&!b.sa&&(b.sa=4096);Q.Qa&&!b.blocks&&(b.blocks=(b.size+b.sa-1)/b.sa|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,
rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,sa:b.sa,blocks:b.blocks}},ha:function(a,b){var c=Q.fa(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},lookup:function(a,b){var c=L(Q.fa(a),b);c=Q.Gb(c);return Q.createNode(a,b,c)},Ha:function(a,b,c,d){a=Q.createNode(a,b,c,d);b=Q.fa(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;
throw new M(N[e.code]);}return a},rename:function(a,b,c){a=Q.fa(a);b=L(Q.fa(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},unlink:function(a,b){a=L(Q.fa(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},rmdir:function(a,b){a=L(Q.fa(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},readdir:function(a){a=Q.fa(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new M(N[b.code]);}},symlink:function(a,
b,c){a=L(Q.fa(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},readlink:function(a){var b=Q.fa(a);try{return b=fs.readlinkSync(b),b=qb.relative(qb.resolve(a.ea.kb.root),b)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}}},Y:{open:function(a){var b=Q.fa(a.node);try{32768===(a.node.mode&61440)&&(a.Ia=fs.openSync(b,Q.Zb(a.flags)))}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Ia&&fs.closeSync(a.Ia)}catch(b){if(!b.code)throw b;
throw new M(N[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Ia,Q.xb(b.buffer),c,d,e)}catch(g){throw new M(N[g.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Ia,Q.xb(b.buffer),c,d,e)}catch(g){throw new M(N[g.code]);}},pa:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Ia).size}catch(d){throw new M(N[d.code]);}if(0>b)throw new M(N.va);return b}}},rb=null,sb={},R=[],tb=1,ub=null,vb=!0,wb={},M=null,
ob={};function S(a,b){a=fb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Eb:!0,nb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.nb)throw new M(40);a=Za(a.split("/").filter(function(a){return!!a}),!1);var e=rb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=pb(e,a[d]);c=L(c,a[d]);e.Sa&&(!g||g&&b.Eb)&&(e=e.Sa.root);if(!g||b.Db)for(g=0;40960===(e.mode&61440);)if(e=xb(c),c=fb(bb(c),e),e=S(c,{nb:b.nb}).node,40<g++)throw new M(40);}return{path:c,node:e}}
function yb(a){for(var b;;){if(a===a.parent)return a=a.ea.Lb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ub.length}function Ab(a){var b=zb(a.parent.id,a.name);a.ic=ub[b];ub[b]=a}function pb(a,b){var c;if(c=(c=Bb(a,"x"))?c:a.Z.lookup?0:13)throw new M(c,a);for(c=ub[zb(a.id,b)];c;c=c.ic){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Z.lookup(a,b)}
function nb(a,b,c,d){Cb||(Cb=function(a,b,c,d){a||(a=this);this.parent=a;this.ea=a.ea;this.Sa=null;this.id=tb++;this.name=b;this.mode=c;this.Z={};this.Y={};this.rdev=d},Cb.prototype={},Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Cb(a,b,c,d);Ab(a);return a}
var Db={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Eb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(vb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Fb(a,b){try{return pb(a,b),17}catch(c){}return Bb(a,"wx")}
function Gb(){var a=4096;for(var b=0;b<=a;b++)if(!R[b])return b;throw new M(24);}function Hb(a){Ib||(Ib=function(){},Ib.prototype={},Object.defineProperties(Ib.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var b=new Ib,c;for(c in a)b[c]=a[c];a=b;b=Gb();a.fd=b;return R[b]=a}var mb={open:function(a){a.Y=sb[a.node.rdev].Y;a.Y.open&&a.Y.open(a)},pa:function(){throw new M(29);}};function ib(a,b){sb[a]={Y:b}}
function Jb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new M(16);if(!c&&!d){var e=S(b,{Eb:!1});b=e.path;e=e.node;if(e.Sa)throw new M(16);if(16384!==(e.mode&61440))throw new M(20);}b={type:a,kb:{},Lb:b,hc:[]};a=a.ea(b);a.ea=b;b.root=a;c?rb=a:e&&(e.Sa=b,e.ea&&e.ea.hc.push(b))}function Kb(a,b,c){var d=S(a,{parent:!0}).node;a=cb(a);if(!a||"."===a||".."===a)throw new M(22);var e=Fb(d,a);if(e)throw new M(e);if(!d.Z.Ha)throw new M(1);return d.Z.Ha(d,a,b,c)}function T(a){Kb(a,16895,0)}
function Lb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Kb(a,b|8192,c)}function Ha(a,b){if(!fb(a))throw new M(2);var c=S(b,{parent:!0}).node;if(!c)throw new M(2);b=cb(b);var d=Fb(c,b);if(d)throw new M(d);if(!c.Z.symlink)throw new M(1);c.Z.symlink(c,b,a)}function xb(a){a=S(a).node;if(!a)throw new M(2);if(!a.Z.readlink)throw new M(22);return fb(yb(a.parent),a.Z.readlink(a))}
function Ia(a,b){if(""===a)throw new M(2);if("string"===typeof b){var c=Db[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=ab(a);try{e=S(a,{Db:!(b&131072)}).node}catch(k){}}c=!1;if(b&64)if(e){if(b&128)throw new M(17);}else e=Kb(a,d,0),c=!0;if(!e)throw new M(2);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new M(20);if(!c&&(d=e?40960===(e.mode&61440)?40:
16384===(e.mode&61440)&&("r"!==Eb(b)||b&512)?21:Bb(e,Eb(b)):2))throw new M(d);if(b&512){d=e;var g;"string"===typeof d?g=S(d,{Db:!0}).node:g=d;if(!g.Z.ha)throw new M(1);if(16384===(g.mode&61440))throw new M(21);if(32768!==(g.mode&61440))throw new M(22);if(d=Bb(g,"w"))throw new M(d);g.Z.ha(g,{size:0,timestamp:Date.now()})}b&=-641;e=Hb({node:e,path:yb(e),flags:b,seekable:!0,position:0,Y:e.Y,yc:[],error:!1});e.Y.open&&e.Y.open(e);!h.logReadFiles||b&1||(Mb||(Mb={}),a in Mb||(Mb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{wb.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),wb.onOpenFile(a,e))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}}function Nb(a,b,c){if(null===a.fd)throw new M(9);if(!a.seekable||!a.Y.pa)throw new M(29);if(0!=c&&1!=c&&2!=c)throw new M(22);a.position=a.Y.pa(a,b,c);a.yc=[]}
function Fa(){M||(M=function(a,b){this.node=b;this.oc=function(a){this.za=a};this.oc(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},M.prototype=Error(),M.prototype.constructor=M,[2].forEach(function(a){ob[a]=new M(a);ob[a].stack="<generic error, no stack>"}))}var Ea;function Ob(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ga(a,b,c){a=L("/dev",a);var d=Ob(!!b,!!c);Pb||(Pb=64);var e=Pb++<<8|0;ib(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,k=0;k<e;k++){try{var t=b()}catch(J){throw new M(5);}if(void 0===t&&0===g)throw new M(11);if(null===t||void 0===t)break;g++;c[d+k]=t}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(v){throw new M(5);}e&&(a.node.timestamp=Date.now());return g}});
Lb(a,d,e)}
var Pb,Qb={},Cb,Ib,Mb,N={Wb:1,Ub:2,Be:3,td:4,qb:5,sb:6,Ic:7,Ud:8,Tb:9,Yc:10,Sb:11,Le:11,Vb:12,Jc:13,md:14,fe:15,Wc:16,ld:17,Me:18,cb:19,he:20,vd:21,va:22,Pd:23,Hd:24,wa:25,Ie:26,nd:27,be:28,Ae:29,xe:30,Id:31,qe:32,hd:33,ue:34,Yd:42,qd:43,Zc:44,xd:45,yd:46,zd:47,Fd:48,Je:49,Sd:50,wd:51,dd:35,Vd:37,Pc:52,Sc:53,Ne:54,Qd:55,Tc:56,Uc:57,ed:35,Vc:59,de:60,Td:61,Fe:62,ce:63,Zd:64,$d:65,we:66,Wd:67,Mc:68,Ce:69,$c:70,re:71,Kd:72,jd:73,Rc:74,le:76,Qc:77,ve:78,Ad:79,Bd:80,Ed:81,Dd:82,Cd:83,ee:38,rb:39,Ld:36,
Gd:40,me:95,pe:96,cd:104,Rd:105,Nc:97,te:91,je:88,ae:92,ye:108,bd:111,Kc:98,ad:103,Od:101,Md:100,Ge:110,od:112,pd:113,sd:115,Oc:114,gd:89,Jd:90,se:93,ze:94,Lc:99,Nd:102,ud:106,ge:107,He:109,Ke:87,kd:122,De:116,ke:95,Xd:123,rd:84,ne:75,Xc:125,ie:131,oe:130,Ee:86},Rb={},U=0;function V(){U+=4;return A[U-4>>2]}function Sb(){var a=R[V()];if(!a)throw new M(N.Tb);return a}
function Tb(a,b){f.W.Da=a;f.W.$a=b;if(f.W.na)if(0==a)f.W.ta=function(){var a=Math.max(0,f.W.tc+b-Ub())|0;setTimeout(f.W.Ya,a)},f.W.method="timeout";else if(1==a)f.W.ta=function(){f.requestAnimationFrame(f.W.Ya)},f.W.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);n?(void 0===h.setImmediates&&(h.setImmediates=
[]),h.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}f.W.ta=function(){setImmediate(f.W.Ya)};f.W.method="immediate"}}function Ub(){y()}
function Vb(a){var b=f.W.ra;h.noExitRuntime=!0;assert(!f.W.na,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");f.W.na=a;f.W.ra=b;var c="undefined"!==typeof b?function(){h.dynCall_vi(a,b)}:function(){h.dynCall_v(a)};var d=f.W.ya;f.W.Ya=function(){if(!C)if(0<f.W.Ob.length){var a=Date.now(),b=f.W.Ob.shift();b.na(b.ra);if(f.W.ob){var k=f.W.ob,t=0==k%1?k-1:Math.floor(k);
f.W.ob=b.Se?t:(8*k+(t+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");f.W.zc();d<f.W.ya||setTimeout(f.W.Ya,0)}else d<f.W.ya||(f.W.hb=f.W.hb+1|0,1==f.W.Da&&1<f.W.$a&&0!=f.W.hb%f.W.$a?f.W.ta():(0==f.W.Da&&(f.W.tc=Ub()),"timeout"===f.W.method&&h.gb&&(z("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
f.W.method=""),f.W.lc(c),d<f.W.ya||f.W.ta()))}}
f={W:{ta:null,method:"",ya:0,na:null,ra:0,Da:0,$a:0,hb:0,Ob:[],pause:function(){f.W.ta=null;f.W.ya++},resume:function(){f.W.ya++;var a=f.W.Da,b=f.W.$a,c=f.W.na;f.W.na=null;Vb(c);Tb(a,b);f.W.ta()},zc:function(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=f.W.ob,c=f.W.Ve;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}},lc:function(a){if(!(C||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof u)return;b&&"object"===typeof b&&b.stack&&z("exception thrown: "+
[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}},Fa:!1,lb:!1,fc:[],workers:[],cc:function(){function a(){f.lb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!f.dc){f.dc=!0;try{f.Pa=!0}catch(c){f.Pa=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}f.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:f.Pa?null:console.log("warning: no BlobBuilder");f.La="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Nb||"undefined"!==typeof f.La||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Nb=!0);h.preloadPlugins.push({canHandle:function(a){return!h.Nb&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,e,g){var c=null;if(f.Pa)try{c=
new Blob([a],{type:f.ib(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:f.ib(b)}))}catch(w){ka("Blob constructor present but fails: "+w+"; falling back to blob builder")}c||(c=new f.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=f.La.createObjectURL(c),m=new Image;m.onload=function(){assert(m.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=m.width;c.height=m.height;c.getContext("2d").drawImage(m,0,0);h.preloadedImages[b]=
c;f.La.revokeObjectURL(d);e&&e(a)};m.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};m.src=d}});h.preloadPlugins.push({canHandle:function(a){return!h.df&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,g){function c(c){m||(m=!0,h.preloadedAudios[b]=c,e&&e(a))}function d(){m||(m=!0,h.preloadedAudios[b]=new Audio,g&&g())}var m=!1;if(f.Pa){try{var w=new Blob([a],{type:f.ib(b)})}catch(I){return d()}w=f.La.createObjectURL(w);var v=new Audio;v.addEventListener("canplaythrough",
function(){c(v)},!1);v.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,B=0,g=0;g<a.length;g++)for(e=e<<8|a[g],B+=8;6<=B;){var k=e>>B-6&63;B-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[k]}2==B?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==B&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&15)<<2],d+="=");v.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(v)}};v.src=w;f.mc(function(){c(v)},1E4)}else return d()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",function(a){!f.lb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&h.gb&&a==h.canvas)return h.gb;if(b){if(d)for(var e in d);}else var g=a.getContext("2d");if(!g)return null;c&&(b||assert(!0,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),
h.gb=g,b&&(void 0).af(void 0),h.qf=b,f.fc.forEach(function(a){a()}),f.cc());return g},Te:function(){},Fb:!1,Ra:void 0,Ca:void 0,requestFullscreen:function(a,b,c){function d(){f.Fa=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=f.exitFullscreen,f.Ra&&e.requestPointerLock(),f.Fa=!0,f.Ca?f.pc():f.Ka(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),
f.Ca?f.qc():f.Ka(e));if(h.onFullScreen)h.onFullScreen(f.Fa);if(h.onFullscreen)h.onFullscreen(f.Fa)}f.Ra=a;f.Ca=b;f.Rb=c;"undefined"===typeof f.Ra&&(f.Ra=!0);"undefined"===typeof f.Ca&&(f.Ca=!1);"undefined"===typeof f.Rb&&(f.Rb=null);var e=h.canvas;f.Fb||(f.Fb=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");
e.parentNode.insertBefore(g,e);g.appendChild(e);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({sf:c}):g.requestFullscreen()},Pb:function(a,b,c){z("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");
f.Pb=function(a,b,c){return f.requestFullscreen(a,b,c)};return f.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!f.Fa)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},Aa:0,Bb:function(a){var b=Date.now();if(0===f.Aa)f.Aa=b+1E3/60;else for(;b+2>=f.Aa;)f.Aa+=1E3/60;setTimeout(a,Math.max(f.Aa-b,0))},requestAnimationFrame:function(a){"undefined"===typeof window?
f.Bb(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||f.Bb),window.requestAnimationFrame(a))},jf:function(a){return function(){if(!C)return a.apply(null,arguments)}},Ea:!0,Ja:[],ff:function(){f.Ea=!1},hf:function(){f.Ea=!0;if(0<f.Ja.length){var a=f.Ja;f.Ja=[];a.forEach(function(a){a()})}},kf:function(a){return f.requestAnimationFrame(function(){C||
(f.Ea?a():f.Ja.push(a))})},mc:function(a,b){h.noExitRuntime=!0;return setTimeout(function(){C||(f.Ea?a():f.Ja.push(a))},b)},lf:function(a,b){h.noExitRuntime=!0;return setInterval(function(){C||f.Ea&&a()},b)},ib:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},
$b:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},ac:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Ye:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},
Va:0,Wa:0,Ta:0,Ua:0,touches:{},Jb:{},Re:function(a){if(f.lb)"mousemove"!=a.type&&"mozMovementX"in a?f.Ta=f.Ua=0:(f.Ta=f.$b(a),f.Ua=f.ac(a)),f.Va+=f.Ta,f.Wa+=f.Ua;else{var b=h.canvas.getBoundingClientRect(),c=h.canvas.width,d=h.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.nf;if(void 0!==k)if(e=k.pageX-(e+b.left),
g=k.pageY-(g+b.top),e*=c/b.width,g*=d/b.height,b={x:e,y:g},"touchstart"===a.type)f.Jb[k.identifier]=b,f.touches[k.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=f.touches[k.identifier])||(a=b),f.Jb[k.identifier]=a,f.touches[k.identifier]=b}else k=a.pageX-(e+b.left),a=a.pageY-(g+b.top),k*=c/b.width,a*=d/b.height,f.Ta=k-f.Va,f.Ua=a-f.Wa,f.Va=k,f.Wa=a}},Pe:function(a,b,c,d){var e=d?"":"al "+a;h.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');
b(new Uint8Array(c));e&&Na()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ma()},kc:[],pb:function(){var a=h.canvas;f.kc.forEach(function(b){b(a.width,a.height)})},nc:function(a,b,c){f.Ka(h.canvas,a,b);c||f.pb()},vf:0,uf:0,pc:function(){f.Ka(h.canvas);f.pb()},qc:function(){f.Ka(h.canvas);f.pb()},Ka:function(a,b,c){b&&c?(a.Ac=b,a.bc=c):(b=a.Ac,c=a.bc);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/
h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}f.Ca?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=
c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},tf:{},Mb:0,Ze:function(){var a=f.Mb;f.Mb++;return a}};var Wb={Cc:!0,Bc:!0},Xb={Dc:!0,Fc:!0,Gc:!0,Ec:!0,Hc:!0},W=0,X={},Yb={},Zb={},Y={},$b=null,ac=1,bc=[];
function cc(a){if(4113!==a.state){a.state=4116;a.la=a.da.length;a.ga=Number.NEGATIVE_INFINITY;for(var b=a.ka=0;b<a.ja.length;b++)a.ja[b].stop();a.ja.length=0}}
function dc(a){for(var b in a.Za){var c=a.Za[b],d=c.ef;if(d)switch(d.refDistance=c.refDistance,d.maxDistance=c.maxDistance,d.rolloffFactor=c.rolloffFactor,d.panningModel=c.context.Ib?"HRTF":"equalpower",c.context.rc?c.distanceModel:c.context.distanceModel){case 0:d.distanceModel="inverse";d.refDistance=3.40282E38;break;case 53249:case 53250:d.distanceModel="inverse";break;case 53251:case 53252:d.distanceModel="linear";break;case 53253:case 53254:d.distanceModel="exponential"}}}var ec={};
function fc(a){if(0===a)return W=40961,null;a=ec[a];return!a||a.cf?(W=40961,null):a}function ja(){return E.length}function hc(){y("OOM")}function ic(a){if(0===a)return 0;a=ra(a);if(!K.hasOwnProperty(a))return 0;ic.ia&&jc(ic.ia);a=K[a];var b=ta(a)+1,c=D(b);c&&sa(a,E,c,b);ic.ia=c;return ic.ia}function Z(){Z.ia||(Z.ia=[]);Z.ia.push(kc());return Z.ia.length-1}function lc(a){return 0===a%4&&(0!==a%100||0===a%400)}function mc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var nc=[31,29,31,30,31,30,31,31,30,31,30,31],oc=[31,28,31,30,31,30,31,31,30,31,30,31];function pc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(lc(a.getFullYear())?nc:oc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function qc(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return e(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function t(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function m(a){a=pc(new Date(a.ba+1900,0,1),a.bb);var b=t(new Date(a.getFullYear()+1,0,4));return 0>=k(t(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var w=A[d+40>>2];d={wc:A[d>>2],vc:A[d+4>>2],ab:A[d+8>>2],ua:A[d+12>>2],qa:A[d+16>>2],ba:A[d+20>>2],Qb:A[d+24>>2],bb:A[d+28>>2],mf:A[d+32>>2],uc:A[d+36>>2],
xc:w?ra(w):""};c=ra(c);w={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var v in w)c=c.replace(new RegExp(v,"g"),w[v]);var I="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),J="January February March April May June July August September October November December".split(" ");w={"%a":function(a){return I[a.Qb].substring(0,3)},"%A":function(a){return I[a.Qb]},"%b":function(a){return J[a.qa].substring(0,
3)},"%B":function(a){return J[a.qa]},"%C":function(a){return g((a.ba+1900)/100|0,2)},"%d":function(a){return g(a.ua,2)},"%e":function(a){return e(a.ua,2," ")},"%g":function(a){return m(a).toString().substring(2)},"%G":function(a){return m(a)},"%H":function(a){return g(a.ab,2)},"%I":function(a){a=a.ab;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.ua+mc(lc(a.ba+1900)?nc:oc,a.qa-1),3)},"%m":function(a){return g(a.qa+1,2)},"%M":function(a){return g(a.vc,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.ab&&12>a.ab?"AM":"PM"},"%S":function(a){return g(a.wc,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.ba+1900,a.qa+1,a.ua,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.ba+1900,0,1),c=0===b.getDay()?b:pc(b,7-b.getDay());a=new Date(a.ba+1900,a.qa,a.ua);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(mc(lc(a.getFullYear())?nc:oc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=t(new Date(a.ba+1900,0,4)),c=t(new Date(a.ba+
1901,0,4)),d=pc(new Date(a.ba+1900,0,1),a.bb);return 0>k(d,b)?"53":0>=k(c,d)?"01":g(Math.ceil((b.getFullYear()<a.ba+1900?a.bb+32-b.getDate():a.bb+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.ba+1900,a.qa+1,a.ua,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.ba,0,1),c=1===b.getDay()?b:pc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.ba+1900,a.qa,a.ua);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(mc(lc(a.getFullYear())?nc:oc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":
"00"},"%y":function(a){return(a.ba+1900).toString().substring(2)},"%Y":function(a){return a.ba+1900},"%z":function(a){a=a.uc;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.xc},"%%":function(){return"%"}};for(v in w)0<=c.indexOf(v)&&(c=c.replace(new RegExp(v,"g"),w[v](d)));v=Ta(c,!1);if(v.length>b)return 0;E.set(v,a);return v.length-1}Fa();ub=Array(4096);Jb(P,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");ib(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Lb("/dev/null",259);hb(1280,kb);hb(1536,lb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(p)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){y("random_device")});Ga("random",b);Ga("urandom",b);T("/dev/shm");
T("/dev/shm/tmp")})();T("/proc");T("/proc/self");T("/proc/self/fd");Jb({ea:function(){var a=nb("/proc/self","fd",16895,73);a.Z={lookup:function(a,c){var b=R[+c];if(!b)throw new M(9);a={parent:null,ea:{Lb:"fake"},Z:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(p){var fs=require("fs"),qb=require("path");Q.sc()}
h.requestFullScreen=function(a,b,c){z("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");h.requestFullScreen=h.requestFullscreen;f.Pb(a,b,c)};h.requestFullscreen=function(a,b,c){f.requestFullscreen(a,b,c)};h.requestAnimationFrame=function(a){f.requestAnimationFrame(a)};h.setCanvasSize=function(a,b,c){f.nc(a,b,c)};h.pauseMainLoop=function(){f.W.pause()};h.resumeMainLoop=function(){f.W.resume()};h.getUserMedia=function(){f.getUserMedia()};
h.createContext=function(a,b,c,d){return f.createContext(a,b,c,d)};p?Ub=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Ub=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Ub=function(){return performance.now()}:Ub=Date.now;function Ta(a,b){var c=Array(ta(a)+1);a=sa(a,c,0,c.length);b&&(c.length=a);return c}
var uc=h.asm({},{c:y,J:Xa,h:function(a){return D(a)},g:function(a){"uncaught_exception"in rc?rc.tb++:rc.tb=1;throw a;},s:function(){return!!rc.tb},n:function(){},r:function(){Ya(1);return-1},m:Ya,q:function(a,b){U=b;try{var c=Sb();V();var d=V(),e=V(),g=V();Nb(c,d,g);A[e>>2]=c.position;c.jb&&0===d&&0===g&&(c.jb=null);return 0}catch(k){return"undefined"!==typeof Qb&&k instanceof M||y(k),-k.za}},p:function(a,b){U=b;try{var c=Sb(),d=V();a:{var e=V();for(b=a=0;b<e;b++){var g=A[d+(8*b+4)>>2],k=c,t=A[d+
8*b>>2],m=g,w=void 0,v=E;if(0>m||0>w)throw new M(22);if(null===k.fd)throw new M(9);if(1===(k.flags&2097155))throw new M(9);if(16384===(k.node.mode&61440))throw new M(21);if(!k.Y.read)throw new M(22);var I="undefined"!==typeof w;if(!I)w=k.position;else if(!k.seekable)throw new M(29);var J=k.Y.read(k,v,t,m,w);I||(k.position+=J);var B=J;if(0>B){var O=-1;break a}a+=B;if(B<g)break}O=a}return O}catch($a){return"undefined"!==typeof Qb&&$a instanceof M||y($a),-$a.za}},o:function(a,b){U=b;try{var c=Sb(),d=
V();a:{var e=V();for(b=a=0;b<e;b++){var g=c,k=A[d+8*b>>2],t=A[d+(8*b+4)>>2],m=void 0,w=E;if(0>t||0>m)throw new M(22);if(null===g.fd)throw new M(9);if(0===(g.flags&2097155))throw new M(9);if(16384===(g.node.mode&61440))throw new M(21);if(!g.Y.write)throw new M(22);g.flags&1024&&Nb(g,0,2);var v="undefined"!==typeof m;if(!v)m=g.position;else if(!g.seekable)throw new M(29);var I=g.Y.write(g,w,k,t,m,void 0);v||(g.position+=I);try{if(g.path&&wb.onWriteToFile)wb.onWriteToFile(g.path)}catch(O){console.log("FS.trackingDelegate['onWriteToFile']('"+
g.path+"') threw an exception: "+O.message)}var J=I;if(0>J){var B=-1;break a}a+=J}B=a}return B}catch(O){return"undefined"!==typeof Qb&&O instanceof M||y(O),-O.za}},I:function(a,b){U=b;try{var c=Sb(),d=V();switch(d){case 21509:case 21505:return c.tty?0:-N.wa;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-N.wa;case 21519:if(!c.tty)return-N.wa;var e=V();return A[e>>2]=0;case 21520:return c.tty?-N.va:-N.wa;case 21531:a=e=V();if(!c.Y.ec)throw new M(25);return c.Y.ec(c,
d,a);case 21523:return c.tty?0:-N.wa;case 21524:return c.tty?0:-N.wa;default:y("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof Qb&&g instanceof M||y(g),-g.za}},H:function(a,b){U=b;try{var c=Sb();if(null===c.fd)throw new M(9);c.jb&&(c.jb=null);try{c.Y.close&&c.Y.close(c)}catch(d){throw d;}finally{R[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof Qb&&d instanceof M||y(d),-d.za}},G:function(a,b){U=b;try{var c=V(),d=V(),e=Rb[c];if(!e)return 0;if(d===e.$e){var g=R[e.fd],
k=e.flags,t=new Uint8Array(F.subarray(c,c+d));g&&g.Y.Xa&&g.Y.Xa(g,t,0,d,k);Rb[c]=null;e.Xb&&jc(e.bf)}return 0}catch(m){return"undefined"!==typeof Qb&&m instanceof M||y(m),-m.za}},l:function(){},b:function(){h.abort()},j:function(a){if(!$b)return 0;if(Zb[a])return Zb[a];switch(a){case 0:var b="No Error";break;case 40961:b="Invalid Name";break;case 40962:b="Invalid Enum";break;case 40963:b="Invalid Value";break;case 40964:b="Invalid Operation";break;case 40965:b="Out of Memory";break;case 45057:b="Emscripten";
break;case 45058:b="1.1";break;case 45059:b="WebAudio";break;case 45060:b="";for(var c in Xb)b=b.concat(c),b=b.concat(" ");b=b.trim();break;default:return $b.zb=40962,0}b=oa(Ta(b));return Zb[a]=b},F:function(a){if(!(a in X)||0<X[a])return 0;delete X[a];bc.push(a);return 1},E:function(a,b){if(!(a in X))return W=40961,0;var c=null,d=[],e=null;if(b>>=2)for(var g=0,k=0;;){g=A[b++];d.push(g);if(0===g)break;k=A[b++];d.push(k);switch(g){case 4103:c||(c={});c.sampleRate=k;break;case 4112:case 4113:break;
case 6546:switch(k){case 0:e=!1;break;case 1:e=!0;break;case 2:break;default:return W=40964,0}break;case 6550:if(0!==k)return W=40964,0;break;default:return W=40964,0}}g=window.AudioContext||window.webkitAudioContext;b=null;try{b=c?new g(c):new g}catch(w){return W="NotSupportedError"===w.name?40964:40961,0}"undefined"===typeof b.createGain&&(b.createGain=b.createGainNode);c=b.createGain();c.connect(b.destination);var t={deviceId:a,id:0<bc.length?bc.pop():ac++,Qe:d,Oa:b,listener:{position:[0,0,0],
rf:[0,0,0],direction:[0,0,0],pf:[0,0,0]},Za:[],interval:setInterval(function(){var a=t;if(1!==f.W.Da||"visible"==document.visibilityState)for(var b in a.Za){var c=void 0,d=a.Za[b];if((1!==f.W.Da||"visible"==document.visibilityState)&&4114===d.state){var e=d,g=e.context.Oa.currentTime;if(4114===e.state){isFinite(e.ga)||(e.ga=g-e.ka/e.playbackRate,e.ka=0);for(;e.ja.length;){var k=e.ja[0];e.la+=k.vb;k=k.fb+k.ub;if(g<k)break;e.ja.shift();e.ga=k;e.ka=0;e.la++}if(e.la>=e.da.length&&!e.Ga)cc(e);else if(4136===
e.type&&e.Ga)if(k=e.da[0],0===k.length)e.ka=0;else{var r=(g-e.ga)*e.playbackRate;var m=k.aa.Na||0;var x=k.aa.Ma||k.aa.duration;x<=m&&(x=k.aa.duration);r<x?e.ka=r:e.ka=m+(r-m)%(x-m)}else if(e.ja[0])e.ka=(g-e.ja[0].fb)*e.playbackRate;else{if(4136!==e.type&&e.Ga){for(r=k=0;r<e.da.length;r++)m=e.da[r].aa,k+=m?m.duration:0;k/=e.playbackRate;0<k&&(e.ga+=Math.floor((g-e.ga)/k)*k)}for(r=0;r<e.da.length;r++){if(e.la>=e.da.length)if(e.Ga)e.la%=e.da.length;else{cc(e);break}k=e.da[e.la];if(0<k.length){k=e.ga+
k.aa.duration/e.playbackRate;if(g<k){e.ka=(g-e.ga)*e.playbackRate;break}e.ga=k}e.ka=0;e.la++}}}m=g;e=d.ga;g=d.ka;k=d.la;for(x=0;x<d.ja.length;x++)r=d.ja[x],e=r.fb+r.ub,g=0,k+=r.vb+1;c||(c=.1);c=m+c;for(m=0;e<c;){if(k>=d.da.length)if(d.Ga)k%=d.da.length;else break;x=d.da[k%d.da.length];if(0===x.length){if(m++,m===d.da.length)break}else{r=d.context.Oa.createBufferSource();r.buffer=x.aa;r.playbackRate.value=d.playbackRate;if(x.aa.Na||x.aa.Ma)r.loopStart=x.aa.Na,r.loopEnd=x.aa.Ma;if(4136===d.type&&d.Ga){var db=
Number.POSITIVE_INFINITY;r.loop=!0;x.aa.Na&&(r.loopStart=x.aa.Na);x.aa.Ma&&(r.loopEnd=x.aa.Ma)}else db=(x.aa.duration-g)/d.playbackRate;r.Oe=g;r.ub=db;r.vb=m;m=0;r.connect(d.gain);"undefined"!==typeof r.start?(e=Math.max(e,d.context.Oa.currentTime),r.start(e,g)):"undefined"!==typeof r.noteOn&&(e=Math.max(e,d.context.Oa.currentTime),r.noteOn(e));r.fb=e;d.ja.push(r);e+=db}g=0;k++}}}},25),gain:c,distanceModel:53250,speedOfSound:343.3,dopplerFactor:1,rc:!1,Ib:e||!1,eb:0,get zb(){return this.eb},set zb(a){if(0===
this.eb||0===a)this.eb=a}};X[a]++;Y[t.id]=t;if(null!==e)for(var m in Y)d=Y[m],d.deviceId===a&&(d.Ib=e,dc(d));return t.id},D:function(a){var b=Y[a];$b===b?W=40962:(Y[a].interval&&clearInterval(Y[a].interval),X[b.deviceId]--,delete Y[a],bc.push(a))},C:function(){var a=W;W=0;return a},i:function(a,b){if(Yb[b])return Yb[b];switch(b){case 0:var c="No Error";break;case 40961:c="Invalid Device";break;case 40962:c="Invalid Context";break;case 40963:c="Invalid Enum";break;case 40964:c="Invalid Value";break;
case 40965:c="Out of Memory";break;case 4100:if("undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext)c="Emscripten OpenAL";else return 0;break;case 4101:"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?c="Emscripten OpenAL".concat("\x00"):c="\x00";break;case 785:c="Emscripten OpenAL capture";break;case 784:if(0===a)c="Emscripten OpenAL capture".concat("\x00");else{a=fc(a);if(!a)return 0;c=a.Ue}break;case 4102:if(!a)return W=40961,0;c="";for(var d in Wb)c=
c.concat(d),c=c.concat(" ");c=c.trim();break;default:return W=40963,0}c=oa(Ta(c));return Yb[b]=c},B:function(a){if(0===a)return $b=null,0;$b=Y[a];return 1},A:function(a){return a&&"Emscripten OpenAL"!==ra(a)||"undefined"===typeof AudioContext&&"undefined"===typeof webkitAudioContext?0:(a=0<bc.length?bc.pop():ac++,X[a]=0,a)},z:function(a,b){return Ua[a](b)},y:ja,x:function(a,b,c){F.set(F.subarray(b,b+c),a)},w:function(a){hc(a)},k:function(a){sc(a)},f:ic,e:function(a){var b=Z.ia[a];Z.ia.splice(a,1);
tc(b)},d:Z,v:function(){return 0},u:function(a,b,c,d){return qc(a,b,c,d)},t:hc,a:ia},buffer);h.asm=uc;var Wa=h.__GLOBAL__sub_I_iostream_cpp=function(){return h.asm.K.apply(null,arguments)},rc=h.__ZSt18uncaught_exceptionv=function(){return h.asm.L.apply(null,arguments)},Va=h.___emscripten_environ_constructor=function(){return h.asm.M.apply(null,arguments)};h.___errno_location=function(){return h.asm.N.apply(null,arguments)};var jc=h._free=function(){return h.asm.O.apply(null,arguments)};
h._main=function(){return h.asm.P.apply(null,arguments)};var D=h._malloc=function(){return h.asm.Q.apply(null,arguments)},va=h.stackAlloc=function(){return h.asm.T.apply(null,arguments)},tc=h.stackRestore=function(){return h.asm.U.apply(null,arguments)},kc=h.stackSave=function(){return h.asm.V.apply(null,arguments)};h.dynCall_v=function(){return h.asm.R.apply(null,arguments)};h.dynCall_vi=function(){return h.asm.S.apply(null,arguments)};h.asm=uc;
function u(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}u.prototype=Error();u.prototype.constructor=u;La=function vc(){h.calledRun||wc();h.calledRun||(La=vc)};
h.callMain=function(a){a=a||[];Da();var b=a.length+1,c=va(4*(b+1));A[c>>2]=ua(h.thisProgram);for(var d=1;d<b;d++)A[(c>>2)+d]=ua(a[d-1]);A[(c>>2)+b]=0;try{var e=h._main(b,c,0);sc(e,!0)}catch(g){g instanceof u||("SimulateInfiniteLoop"==g?h.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),z("exception thrown: "+a),h.quit(1,g)))}finally{}};
function wc(a){function b(){if(!h.calledRun&&(h.calledRun=!0,!C)){Da();vb=!1;xa(Aa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();h._main&&xc&&h.callMain(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ba.unshift(b)}xa(Ba)}}a=a||h.arguments;if(!(0<G)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ja();xa(ya);0<G||h.calledRun||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}h.run=wc;function sc(a,b){if(!b||!h.noExitRuntime||0!==a){if(!h.noExitRuntime&&(C=!0,h.onExit))h.onExit(a);h.quit(a,new u(a))}}function y(a){if(h.onAbort)h.onAbort(a);void 0!==a?(fa(a),z(a),a=JSON.stringify(a)):a="";C=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}h.abort=y;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var xc=!0;h.noInitialRun&&(xc=!1);h.noExitRuntime=!0;wc();
