var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),n,v=!1,na,la=a=>a.startsWith("file://"),oa,y,A,B,D,pa;
function qa(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);v=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ra;async function sa(a){if(!n)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ra&&n)a=new Uint8Array(n);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ta(a,b){try{var c=await sa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),qa(d)}}async function ua(a){var b=ra;if(!n&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ta(b,a)}
class va{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var wa=a=>{for(;0<a.length;)a.shift()(h)},xa=[],ya=[],za=()=>{var a=h.preRun.shift();ya.push(a)},F=0,G=null,Aa=!0;class Ba{constructor(a){this.ea=a-24}}
var Ca=0,Da=0,Ea=0,H={},Fa=a=>{a instanceof va||"unwind"==a||fa(1,a)},Ga=a=>{na=a;Aa||0<Ea||(h.onExit?.(a),v=!0);fa(a,new va(a))},Ha=a=>{na=a;Ga(a)},Ia=()=>{if(!(Aa||0<Ea))try{var a=na;na=a;Ga(a)}catch(b){Fa(b)}},Ja=a=>{if(!v)try{a(),Ia()}catch(b){Fa(b)}},I=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.codePointAt(f);if(127>=l){if(c>=d)break;b[c++]=l}else if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6;b[c++]=128|l&63}else if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>
12;b[c++]=128|l>>6&63;b[c++]=128|l&63}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63;b[c++]=128|l>>6&63;b[c++]=128|l&63;f++}}b[c]=0;return c-e},J=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},La=a=>{var b=J(a)+1,c=Ka(b);c&&I(a,A,c,b);return c},Sa=(a,b)=>{K=a;Ma=b;if(Na)if(Oa||=!0,0==a)L=function(){setTimeout(M,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)L=function(){Qa(M)};else if(2==a){if("undefined"==
typeof Ra)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ra=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ra=setImmediate;L=function(){Ra(M)}}},ab=a=>{function b(){return c<Ua?(Ia(),!1):!0}Na=a;var c=Ua;Oa=!1;M=function(){if(!v)if(0<Va.length){var d=
Va.shift();d.Va(d.Ka);if(Wa){var e=Wa,f=0==e%1?e-1:Math.floor(e);Wa=d.Ra?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=Wa??0,f=Xa.Ua??0,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(M,0)}else if(b())if(Ya=Ya+1|0,1==K&&1<Ma&&0!=Ya%Ma)L();else{0==K&&(Pa=performance.now());a:if(!v){for(d of Za)if(!1===d())break a;Ja(a);for(e of $a)e()}b()&&L()}}},Oa=!1,L=null,Ua=0,Na=null,K=0,Ma=0,Ya=0,Va=[],Za=[],$a=[],N=0;
function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===N)N=b+1E3/60;else for(;b+2>=N;)N+=1E3/60;setTimeout(a,Math.max(N-b,0))}}
var Xa={},Pa,M,Ra,Wa,bb={Ca:!0,Ba:!0},cb={Da:!0,Fa:!0,Ga:!0,Ea:!0,Ha:!0},O=0,P={},db={},eb={},Q={},R=null,fb=1,S=[],gb=a=>{if(4113!==a.state){a.state=4116;a.N=a.J.length;a.K=Number.NEGATIVE_INFINITY;for(var b=a.M=0;b<a.L.length;b++)a.L[b].stop();a.L.length=0}},hb=a=>{for(var b in a.sources){var c=a.sources[b],d=c.bb;if(d)switch(d.refDistance=c.refDistance,d.maxDistance=c.maxDistance,d.rolloffFactor=c.rolloffFactor,d.panningModel=c.context.ma?"HRTF":"equalpower",c.context.za?c.distanceModel:c.context.distanceModel){case 0:d.distanceModel=
"inverse";d.refDistance=3.40282E38;break;case 53249:case 53250:d.distanceModel="inverse";break;case 53251:case 53252:d.distanceModel="linear";break;case 53253:case 53254:d.distanceModel="exponential"}}},ib={},jb=a=>{if(0===a)return O=40961,null;a=ib[a];return!a||a.$a?(O=40961,null):a},kb=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d?.addEventListener(c,()=>{"suspended"===a.state&&a.resume()},{once:!0})})})},lb="undefined"!=
typeof TextDecoder?new TextDecoder:void 0,T=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&lb)return lb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},mb={},ob=()=>{if(!nb){var a=
{USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in mb)void 0===mb[b]?delete a[b]:a[b]=mb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nb=c}return nb},nb,pb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},qb=a=>{var b="/"===a.charAt(0),
c="/"===a.slice(-1);(a=pb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},rb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},sb=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},tb=a=>{(tb=sb())(a)},ub=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=pb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},vb=[],wb=[];function xb(a,b){wb[a]={input:[],output:[],W:b};yb(a,zb)}
var zb={open(a){var b=wb[a.node.rdev];if(!b)throw new U(43);a.tty=b;a.seekable=!1},close(a){a.tty.W.fsync(a.tty)},fsync(a){a.tty.W.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.W.sa)throw new U(60);for(var e=0,f=0;f<d;f++){try{var l=a.tty.W.sa(a.tty)}catch(q){throw new U(29);}if(void 0===l&&0===e)throw new U(6);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.W.na)throw new U(60);try{for(var e=0;e<d;e++)a.tty.W.na(a.tty,b[c+e])}catch(f){throw new U(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Ab={sa(){a:{if(!vb.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(J(a)+1);a=I(a,b,0,b.length);b.length=a;vb=b}a=vb.shift()}return a},na(a,b){null===
b||10===b?(ma(T(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(T(a.output)),a.output=[])},Xa(){return{Na:25856,Pa:5,Ma:191,Oa:35387,La:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ya(){return 0},Za(){return[24,80]}},Bb={na(a,b){null===b||10===b?(k(T(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(T(a.output)),a.output=[])}},V={P:null,S(){return V.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new U(63);V.P||(V.P={dir:{node:{T:V.F.T,R:V.F.R,lookup:V.F.lookup,ba:V.F.ba,rename:V.F.rename,unlink:V.F.unlink,rmdir:V.F.rmdir,readdir:V.F.readdir,symlink:V.F.symlink},stream:{O:V.G.O}},file:{node:{T:V.F.T,R:V.F.R},stream:{O:V.G.O,read:V.G.read,write:V.G.write,ua:V.G.ua,wa:V.G.wa}},link:{node:{T:V.F.T,R:V.F.R,readlink:V.F.readlink},stream:{}},qa:{node:{T:V.F.T,R:V.F.R},stream:Cb}});c=Db(a,b,c,d);16384===(c.mode&61440)?(c.F=V.P.dir.node,c.G=V.P.dir.stream,c.D={}):
32768===(c.mode&61440)?(c.F=V.P.file.node,c.G=V.P.file.stream,c.H=0,c.D=null):40960===(c.mode&61440)?(c.F=V.P.link.node,c.G=V.P.link.stream):8192===(c.mode&61440)&&(c.F=V.P.qa.node,c.G=V.P.qa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.D[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Wa(a){return a.D?a.D.subarray?a.D.subarray(0,a.H):new Uint8Array(a.D):new Uint8Array(0)},F:{T(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===
(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.H:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},R(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.H!=b&&(0==b?(a.D=null,a.H=0):(c=a.D,a.D=new Uint8Array(b),c&&a.D.set(c.subarray(0,Math.min(b,a.H))),a.H=b)))},lookup(){V.ia||(V.ia=new U(44),V.ia.stack=
"<generic error, no stack>");throw V.ia;},ba(a,b,c,d){return V.createNode(a,b,c,d)},rename(a,b,c){try{var d=Eb(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.D)throw new U(55);e=Fb(d.parent.id,d.name);if(W[e]===d)W[e]=d.V;else for(e=W[e];e;){if(e.V===d){e.V=d.V;break}e=e.V}}delete a.parent.D[a.name];b.D[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.D[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Eb(a,b),d;for(d in c.D)throw new U(55);
delete a.D[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.D)]},symlink(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new U(28);return a.link}},G:{read(a,b,c,d,e){var f=a.node.D;if(e>=a.node.H)return 0;a=Math.min(a.node.H-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.D||a.D.subarray)){if(f)return a.D=
b.subarray(c,c+d),a.H=d;if(0===a.H&&0===e)return a.D=b.slice(c,c+d),a.H=d;if(e+d<=a.H)return a.D.set(b.subarray(c,c+d),e),d}f=e+d;var l=a.D?a.D.length:0;l>=f||(f=Math.max(f,l*(1048576>l?2:1.125)>>>0),0!=l&&(f=Math.max(f,256)),l=a.D,a.D=new Uint8Array(f),0<a.H&&a.D.set(l.subarray(0,a.H),0));if(a.D.subarray&&b.subarray)a.D.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.D[e+f]=b[c+f];a.H=Math.max(a.H,e+d);return d},O(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.H);if(0>
b)throw new U(28);return b},ua(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new U(43);a=a.node.D;if(e&2||!a||a.buffer!==y.buffer){d=!0;qa();e=void 0;if(!e)throw new U(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);y.set(a,e)}}else d=!1,e=a.byteOffset;return{ea:e,Ja:d}},wa(a,b,c,d){V.G.write(a,b,0,d,c,!1);return 0}}},Gb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Hb=null,Ib={},Jb=[],Kb=1,W=null,Lb=!1,Mb=!0,Nb={},U=class{name="ErrnoError";constructor(a){this.X=
a}},Ob=class{Z={};node=null;get flags(){return this.Z.flags}set flags(a){this.Z.flags=a}get position(){return this.Z.position}set position(a){this.Z.position=a}},Pb=class{F={};G={};da=null;constructor(a,b,c,d){a||=this;this.parent=a;this.S=a.S;this.id=Kb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}};
function X(a,b={}){if(!a)throw new U(44);b.ka??(b.ka=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(q=>!!q);for(var d=Hb,e="/",f=0;f<a.length;f++){var l=f===a.length-1;if(l&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=rb(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=qb(e+"/"+a[f]);try{d=Eb(d,a[f])}catch(q){if(44===q?.X&&l&&b.ya)return{path:e};throw q;}!d.da||l&&!b.ka||(d=d.da.root);if(40960===(d.mode&61440)&&(!l||b.ja)){if(!d.F.readlink)throw new U(52);
d=d.F.readlink(d);"/"===d.charAt(0)||(d=rb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new U(32);}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%W.length}function Eb(a,b){var c=16384===(a.mode&61440)?(c=Qb(a,"x"))?c:a.F.lookup?0:2:54;if(c)throw new U(c);for(c=W[Fb(a.id,b)];c;c=c.V){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.F.lookup(a,b)}
function Db(a,b,c,d){a=new Pb(a,b,c,d);b=Fb(a.parent.id,a.name);a.V=W[b];return W[b]=a}function Rb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Qb(a,b){if(Mb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Sb(a,b){if(16384!==(a.mode&61440))return 54;try{return Eb(a,b),20}catch(c){}return Qb(a,"wx")}function Tb(a){a=Jb[a];if(!a)throw new U(8);return a}
function Ub(a,b){var c=null?.G.R,d=c?null:a;c??=a.F.R;if(!c)throw new U(63);c(d,b)}var Cb={open(a){a.G=Ib[a.node.rdev].G;a.G.open?.(a)},O(){throw new U(70);}};function yb(a,b){Ib[a]={G:b}}function Vb(a,b){var c="/"===b;if(c&&Hb)throw new U(10);if(!c&&b){var d=X(b,{ka:!1});b=d.path;d=d.node;if(d.da)throw new U(10);if(16384!==(d.mode&61440))throw new U(54);}b={type:a,ab:{},va:b,xa:[]};a=a.S(b);a.S=b;b.root=a;c?Hb=a:d&&(d.da=b,d.S&&d.S.xa.push(b))}
function Wb(a,b,c){var d=X(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new U(28);if("."===a||".."===a)throw new U(20);var e=Sb(d,a);if(e)throw new U(e);if(!d.F.ba)throw new U(63);return d.F.ba(d,a,b,c)}function Y(a){return Wb(a,16895,0)}function Xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Wb(a,b|8192,c)}
function Yb(a,b){if(!ub(a))throw new U(44);var c=X(b,{parent:!0}).node;if(!c)throw new U(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Sb(c,b);if(d)throw new U(d);if(!c.F.symlink)throw new U(63);c.F.symlink(c,b,a)}
function Zb(a,b){if(""===a)throw new U(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=X(a,{ja:!(b&131072),ya:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new U(20);}else{if(e)throw new U(31);d=Wb(a,c|511,0);f=!0}if(!d)throw new U(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new U(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Rb(b)||b&576)?31:Qb(d,Rb(b)):44))throw new U(e);if(b&512&&!f){e=d;e="string"==typeof e?X(e,{ja:!0}).node:e;if(16384===(e.mode&61440))throw new U(31);if(32768!==(e.mode&61440))throw new U(28);var l=Qb(e,"w");if(l)throw new U(l);Ub(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.S.va;var q=q?"/"!==e[e.length-1]?`${e}/${q}`:e+q:e;break a}q=q?`${e.name}/${q}`:e.name;e=e.parent}q={node:d,path:q,flags:b,seekable:!0,
position:0,G:d.G,Aa:[],error:!1};e=-1;q=Object.assign(new Ob,q);if(-1==e)a:{for(e=0;4096>=e;e++)if(!Jb[e])break a;throw new U(33);}q.fd=e;Jb[e]=q;q.G.open&&q.G.open(q);f&&(c&=511,d="string"==typeof d?X(d,{ja:!0}).node:d,Ub(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Ta:void 0}));!h.logReadFiles||b&1||a in Nb||(Nb[a]=1)}function $b(a,b,c){if(null===a.fd)throw new U(8);if(!a.seekable||!a.G.O)throw new U(70);if(0!=c&&1!=c&&2!=c)throw new U(28);a.position=a.G.O(a,b,c);a.Aa=[]}
function Z(a,b,c){a=qb("/dev/"+a);var d=Gb(!!b,!!c);Z.ta??(Z.ta=64);var e=Z.ta++<<8|0;yb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,l,q,C){for(var m=0,E=0;E<C;E++){try{var z=b()}catch(t){throw new U(29);}if(void 0===z&&0===m)throw new U(6);if(null===z||void 0===z)break;m++;l[q+E]=z}m&&(f.node.atime=Date.now());return m},write(f,l,q,C){for(var m=0;m<C;m++)try{c(l[q+m])}catch(E){throw new U(29);}C&&(f.node.mtime=f.node.ctime=Date.now());return m}});Xb(a,d,e)}var ac={};
h.requestAnimationFrame=Qa;h.pauseMainLoop=function(){L=null;Ua++};h.resumeMainLoop=function(){Ua++;var a=K,b=Ma,c=Na;Na=null;ab(c);Sa(a,b);L()};h.preMainLoop&&Za.push(h.preMainLoop);h.postMainLoop&&$a.push(h.postMainLoop);W=Array(4096);Vb(V,"/");Y("/tmp");Y("/home");Y("/home/web_user");
(function(){Y("/dev");yb(259,{read:()=>0,write:(d,e,f,l)=>l,O:()=>0});Xb("/dev/null",259);xb(1280,Ab);xb(1536,Bb);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(tb(a),b=a.byteLength);return a[--b]};Z("random",c);Z("urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");Vb({S(){var b=Db(a,"fd",16895,73);b.G={O:V.G.O};b.F={lookup(c,d){c=+d;var e=Tb(c);c={parent:null,S:{va:"fake"},F:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(Jb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.noExitRuntime&&(Aa=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(n=h.wasmBinary);h.arguments&&(da=h.arguments);
h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var bc,Ka,cc,dc,ec={e:(a,b,c)=>{var d=new Ba(a);D[d.ea+16>>2]=0;D[d.ea+4>>2]=b;D[d.ea+8>>2]=c;Ca=a;Da++;throw Ca;},t:()=>qa(""),m:()=>{Aa=!1;Ea=0},n:(a,b)=>{H[a]&&(clearTimeout(H[a].id),delete H[a]);if(!b)return 0;var c=setTimeout(()=>{delete H[a];Ja(()=>cc(a,performance.now()))},b);H[a]={id:c,eb:b};return 0},c:a=>{if(eb[a])return eb[a];switch(a){case 0:var b="No Error";break;case 40961:b="Invalid Name";break;case 40962:b="Invalid Enum";break;case 40963:b="Invalid Value";break;case 40964:b="Invalid Operation";
break;case 40965:b="Out of Memory";break;case 45057:b="Emscripten";break;case 45058:b="1.1";break;case 45059:b="WebAudio";break;case 45060:b=Object.keys(cb).join(" ");break;default:return R&&(R.ra=40962),0}b=La(b);return eb[a]=b},f:a=>{if(!(a in P)||0<P[a])return 0;delete P[a];S.push(a);return 1},j:(a,b)=>{if(!(a in P))return O=40961,0;var c=null,d=[],e=null;if(b>>=2)for(var f=0,l=0;;){f=B[b++];d.push(f);if(0===f)break;l=B[b++];d.push(l);switch(f){case 4103:c||={};c.sampleRate=l;break;case 4112:case 4113:break;
case 6546:switch(l){case 0:e=!1;break;case 1:e=!0;break;case 2:break;default:return O=40964,0}break;case 6550:if(0!==l)return O=40964,0;break;default:return O=40964,0}}f=window.AudioContext||window.webkitAudioContext;b=null;try{b=c?new f(c):new f}catch(m){return O="NotSupportedError"===m.name?40964:40961,0}kb(b);"undefined"==typeof b.createGain&&(b.createGain=b.createGainNode);c=b.createGain();c.connect(b.destination);var q={deviceId:a,id:0<S.length?S.pop():fb++,ha:d,U:b,listener:{position:[0,0,0],
gb:[0,0,0],direction:[0,0,0],fb:[0,0,0]},sources:[],interval:setInterval(()=>{var m=q;if(1!==K||"visible"==document.visibilityState)for(var E in m.sources){var z=void 0,t=m.sources[E];if((1!==K||"visible"==document.visibilityState)&&4114===t.state){var g=t,w=g.context.U.currentTime;if(4114===g.state){isFinite(g.K)||(g.K=w-g.M/g.playbackRate,g.M=0);for(;g.L.length;){var r=g.L[0];g.N+=r.pa;r=r.ga+r.oa;if(w<r)break;g.L.shift();g.K=r;g.M=0;g.N++}if(g.N>=g.J.length&&!g.Y)gb(g);else if(4136===g.type&&g.Y)if(r=
g.J[0],0===r.length)g.M=0;else{var p=(w-g.K)*g.playbackRate;var x=r.I.aa||0;var u=r.I.$||r.I.duration;u<=x&&(u=r.I.duration);p<u?g.M=p:g.M=x+(p-x)%(u-x)}else if(g.L[0])g.M=(w-g.L[0].ga)*g.playbackRate;else{if(4136!==g.type&&g.Y){for(p=r=0;p<g.J.length;p++)x=g.J[p].I,r+=x?x.duration:0;r/=g.playbackRate;0<r&&(g.K+=Math.floor((w-g.K)/r)*r)}for(p=0;p<g.J.length;p++){if(g.N>=g.J.length)if(g.Y)g.N%=g.J.length;else{gb(g);break}r=g.J[g.N];if(0<r.length){r=g.K+r.I.duration/g.playbackRate;if(w<r){g.M=(w-g.K)*
g.playbackRate;break}g.K=r}g.M=0;g.N++}}}x=w;g=t.K;w=t.M;r=t.N;for(u=0;u<t.L.length;u++)p=t.L[u],g=p.ga+p.oa,w=0,r+=p.pa+1;z||=.1;z=x+z;for(x=0;g<z;){if(r>=t.J.length)if(t.Y)r%=t.J.length;else break;u=t.J[r%t.J.length];if(0===u.length){if(x++,x===t.J.length)break}else{p=t.context.U.createBufferSource();p.buffer=u.I;p.playbackRate.value=t.playbackRate;if(u.I.aa||u.I.$)p.loopStart=u.I.aa,p.loopEnd=u.I.$;if(4136===t.type&&t.Y){var Ta=Number.POSITIVE_INFINITY;p.loop=!0;u.I.aa&&(p.loopStart=u.I.aa);u.I.$&&
(p.loopEnd=u.I.$)}else Ta=(u.I.duration-w)/t.playbackRate;p.Ia=w;p.oa=Ta;p.pa=x;x=0;p.connect(t.gain);"undefined"!=typeof p.start?(g=Math.max(g,t.context.U.currentTime),p.start(g,w)):"undefined"!=typeof p.noteOn&&(g=Math.max(g,t.context.U.currentTime),p.noteOn(g));p.ga=g;t.L.push(p);g+=Ta}w=0;r++}}}},25),gain:c,distanceModel:53250,speedOfSound:343.3,dopplerFactor:1,za:!1,ma:e||!1,fa:0,get ra(){return this.fa},set ra(m){if(0===this.fa||0===m)this.fa=m}};P[a]++;Q[q.id]=q;if(null!==e)for(var C in Q)d=
Q[C],d.deviceId===a&&(d.ma=e,hb(d));return q.id},g:a=>{var b=Q[a];R===b?O=40962:(Q[a].interval&&clearInterval(Q[a].interval),P[b.deviceId]--,delete Q[a],S.push(a))},i:()=>{var a=O;O=0;return a},a:(a,b,c,d)=>{if(0!==c&&d)switch(b){case 4096:B[d>>2]=1;break;case 4097:B[d>>2]=1;break;case 4098:if(!(a in P)){O=40961;break}if(!R){O=40962;break}B[d>>2]=R.ha.length;break;case 4099:if(!(a in P)){O=40961;break}if(!R){O=40962;break}for(a=0;a<R.ha.length;a++)B[d+4*a>>2]=R.ha[a];break;case 4103:if(!(a in P)){O=
40961;break}if(!R){O=40962;break}B[d>>2]=R.U.sampleRate;break;case 4112:case 4113:if(!(a in P)){O=40961;break}if(!R){O=40962;break}B[d>>2]=2147483647;break;case 6546:case 6547:if(!(a in P)){O=40961;break}b=0;for(var e in Q)c=Q[e],c.deviceId===a&&(b=c.ma?1:0);B[d>>2]=b;break;case 6548:if(!(a in P)){O=40961;break}B[d>>2]=1;break;case 131075:if(!(a in P)){O=40961;break}if(!R){O=40962;break}B[d>>2]=1;case 786:a=jb(a);if(!a)break;B[d>>2]=Math.floor(a.cb/a.U.sampleRate*a.Qa);break;default:O=40963}},b:(a,
b)=>{if(db[b])return db[b];switch(b){case 0:a="No Error";break;case 40961:a="Invalid Device";break;case 40962:a="Invalid Context";break;case 40963:a="Invalid Enum";break;case 40964:a="Invalid Value";break;case 40965:a="Out of Memory";break;case 4100:if("undefined"!=typeof AudioContext||"undefined"!=typeof webkitAudioContext)a="Emscripten OpenAL";else return 0;break;case 4101:a="undefined"!=typeof AudioContext||"undefined"!=typeof webkitAudioContext?"Emscripten OpenAL\x00":"\x00";break;case 785:a=
"Emscripten OpenAL capture";break;case 784:if(0===a)a="Emscripten OpenAL capture\x00";else{a=jb(a);if(!a)return 0;a=a.Sa}break;case 4102:if(!a)return O=40961,0;a=Object.keys(bb).join(" ");break;default:return O=40963,0}a=La(a);return db[b]=a},h:a=>{0===a?R=null:R=Q[a];return 1},k:a=>{var b;if(b=a)b="Emscripten OpenAL"!==(a?T(A,a):"");return b?0:"undefined"!=typeof AudioContext||"undefined"!=typeof webkitAudioContext?(a=0<S.length?S.pop():fb++,P[a]=0,a):0},w:function(a,b){a=a?T(A,a,b):"";if("undefined"!==
typeof process&&a in process.env){a=process.env[a];b=J(a)+1;var c=Ka(b);I(a,A,c,b);return c}return 0},s:()=>{qa("OOM")},u:(a,b)=>{var c=0,d=0,e;for(e of ob()){var f=b+c;D[a+d>>2]=f;c+=I(e,A,f,Infinity)+1;d+=4}return 0},v:(a,b)=>{var c=ob();D[a>>2]=c.length;a=0;for(var d of c)a+=J(d)+1;D[b>>2]=a;return 0},d:Ha,o:function(a){try{var b=Tb(a);if(null===b.fd)throw new U(8);b.la&&(b.la=null);try{b.G.close&&b.G.close(b)}catch(c){throw c;}finally{Jb[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==
typeof ac||"ErrnoError"!==c.name)throw c;return c.X}},r:function(a,b,c,d){try{a:{var e=Tb(a);a=b;for(var f,l=b=0;l<c;l++){var q=D[a>>2],C=D[a+4>>2];a+=8;var m=e,E=q,z=C,t=f,g=y;if(0>z||0>t)throw new U(28);if(null===m.fd)throw new U(8);if(1===(m.flags&2097155))throw new U(8);if(16384===(m.node.mode&61440))throw new U(31);if(!m.G.read)throw new U(28);var w="undefined"!=typeof t;if(!w)t=m.position;else if(!m.seekable)throw new U(70);var r=m.G.read(m,g,E,z,t);w||(m.position+=r);var p=r;if(0>p){var x=
-1;break a}b+=p;if(p<C)break;"undefined"!=typeof f&&(f+=p)}x=b}D[d>>2]=x;return 0}catch(u){if("undefined"==typeof ac||"ErrnoError"!==u.name)throw u;return u.X}},p:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Tb(a);$b(e,b,c);pa[d>>3]=BigInt(e.position);e.la&&0===b&&0===c&&(e.la=null);return 0}catch(f){if("undefined"==typeof ac||"ErrnoError"!==f.name)throw f;return f.X}},q:function(a,b,c,d){try{a:{var e=Tb(a);a=b;for(var f,l=b=0;l<c;l++){var q=
D[a>>2],C=D[a+4>>2];a+=8;var m=e,E=q,z=C,t=f,g=y;if(0>z||0>t)throw new U(28);if(null===m.fd)throw new U(8);if(0===(m.flags&2097155))throw new U(8);if(16384===(m.node.mode&61440))throw new U(31);if(!m.G.write)throw new U(28);m.seekable&&m.flags&1024&&$b(m,0,2);var w="undefined"!=typeof t;if(!w)t=m.position;else if(!m.seekable)throw new U(70);var r=m.G.write(m,g,E,z,t,void 0);w||(m.position+=r);var p=r;if(0>p){var x=-1;break a}b+=p;if(p<C)break;"undefined"!=typeof f&&(f+=p)}x=b}D[d>>2]=x;return 0}catch(u){if("undefined"==
typeof ac||"ErrnoError"!==u.name)throw u;return u.X}},l:Ga};function fc(a=[]){var b=bc;a.unshift(ea);var c=a.length,d=dc(4*(c+1)),e=d;a.forEach(l=>{var q=D,C=e>>2,m=J(l)+1,E=dc(m);I(l,A,E,m);q[C]=E;e+=4});D[e>>2]=0;try{var f=b(c,d);Ha(f,!0)}catch(l){Fa(l)}}
function gc(a=da){function b(){h.calledRun=!0;if(!v){if(!h.noFSInit&&!Lb){var c,d;Lb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Z("stdin",c):Yb("/dev/tty","/dev/stdin");d?Z("stdout",null,d):Yb("/dev/tty","/dev/stdout");e?Z("stderr",null,e):Yb("/dev/tty1","/dev/stderr");Zb("/dev/stdin",0);Zb("/dev/stdout",1);Zb("/dev/stderr",1)}hc.y();Mb=!1;h.onRuntimeInitialized?.();h.noInitialRun||fc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=h.postRun.shift();
xa.push(e)}wa(xa)}}if(0<F)G=gc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)za();wa(ya);0<F?G=gc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var hc;
(async function(){function a(c){hc=c.exports;oa=hc.x;c=oa.buffer;y=new Int8Array(c);new Int16Array(c);A=new Uint8Array(c);new Uint16Array(c);B=new Int32Array(c);D=new Uint32Array(c);new Float32Array(c);new Float64Array(c);pa=new BigInt64Array(c);new BigUint64Array(c);c=hc;h._main=bc=c.z;Ka=c.A;cc=c.B;dc=c.C;F--;h.monitorRunDependencies?.(F);0==F&&G&&(c=G,G=null,c());return hc}F++;h.monitorRunDependencies?.(F);var b={a:ec};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,
e))})});ra??=h.locateFile?h.locateFile("magnum-al-info.wasm",ia):ia+"magnum-al-info.wasm";return a((await ua(b)).instance)})();gc();
