var aa,g;var h,k;var m;m||(m=typeof Module !== 'undefined' ? Module : {});var ba={},n;for(n in m)m.hasOwnProperty(n)&&(ba[n]=m[n]);m.arguments=[];m.thisProgram="./this.program";m.quit=function(a,b){throw b;};m.preRun=[];m.postRun=[];var ca=!1,p=!1,q=!1,da=!1;ca="object"===typeof window;p="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!ca&&!p;da=!ca&&!q&&!p;var t="";
if(q){t=__dirname+"/";var fa,ha;m.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};m.readBinary=function(a){a=m.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(m.thisProgram=process.argv[1].replace(/\\/g,"/"));m.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=m);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",
u);m.quit=function(a){process.exit(a)};m.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(m.read=function(a){return read(a)}),m.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m.arguments=scriptArgs:"undefined"!=typeof arguments&&(m.arguments=arguments),"function"===typeof quit&&(m.quit=function(a){quit(a)});else if(ca||p)p?
t=self.location.href:document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?t.substr(0,t.lastIndexOf("/")+1):"",m.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(m.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),m.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},m.setWindowTitle=function(a){document.title=a};var ja=m.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),w=m.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ja);for(n in ba)ba.hasOwnProperty(n)&&(m[n]=ba[n]);ba=void 0;function ka(a){var b=y[la>>2];a=b+a+15&-16;if(a<=ma())y[la>>2]=a;else return 0;return b}
var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&w("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||u("Assertion failed: "+b)}function qa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=z(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)y[a>>2]=0;for(b=d+c;a<b;)B[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}
var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?sa(C,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var r=a.charCodeAt(++f);l=65536+((l&1023)<<10)|r&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ua(a){var b=ta(a)+1,c=va(b);E(a,B,c,b);return c}var buffer,B,C,wa,xa,y,ya,F,G,la=360640,za=m.TOTAL_MEMORY||16777216;5242880>za&&w("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+za+"! (TOTAL_STACK=5242880)");
m.buffer?buffer=m.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(oa=new WebAssembly.Memory({initial:za/65536,maximum:za/65536}),buffer=oa.buffer):buffer=new ArrayBuffer(za);m.HEAP8=B=new Int8Array(buffer);m.HEAP16=wa=new Int16Array(buffer);m.HEAP32=y=new Int32Array(buffer);m.HEAPU8=C=new Uint8Array(buffer);m.HEAPU16=xa=new Uint16Array(buffer);m.HEAPU32=ya=new Uint32Array(buffer);m.HEAPF32=F=new Float32Array(buffer);m.HEAPF64=G=new Float64Array(buffer);y[la>>2]=5603776;
function Aa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Dc;"number"===typeof c?void 0===b.kd?m.dynCall_v(c):m.dynCall_vi(c,b.kd):c(void 0===b.kd?null:b.kd)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[],Ga=!1;
function Ha(){Ga||(Ga=!0,m.noFSInit||Ia||(Ia=!0,Ja(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?Ka("stdin",m.stdin):La("/dev/tty","/dev/stdin"),m.stdout?Ka("stdout",null,m.stdout):La("/dev/tty","/dev/stdout"),m.stderr?Ka("stderr",null,m.stderr):La("/dev/tty1","/dev/stderr"),Ma("/dev/stdin","r"),Ma("/dev/stdout","w"),Ma("/dev/stderr","w")),Aa(Ca))}function Na(){var a=m.preRun.shift();Ba.unshift(a)}var Oa=Math.abs,Pa=Math.ceil,Qa=Math.floor,Ra=Math.min,H=0,Sa=null,Ta=null;
m.preloadedImages={};m.preloadedAudios={};function Ua(){var a=I;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var I="magnum-text.wasm";if(!Ua()){var Va=I;I=m.locateFile?m.locateFile(Va,t):t+Va}function Wa(){try{if(m.wasmBinary)return new Uint8Array(m.wasmBinary);if(m.readBinary)return m.readBinary(I);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function Xa(){return m.wasmBinary||!ca&&!p||"function"!==typeof fetch?new Promise(function(a){a(Wa())}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}
function Ya(a){function b(a){m.asm=a.exports;H--;m.monitorRunDependencies&&m.monitorRunDependencies(H);0==H&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta&&(a=Ta,Ta=null,a()))}function c(a){b(a.instance)}function d(a){Xa().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){w("failed to asynchronously prepare wasm: "+a);u(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};H++;m.monitorRunDependencies&&m.monitorRunDependencies(H);if(m.instantiateWasm)try{return m.instantiateWasm(e,
b)}catch(f){return w("Module.instantiateWasm callback failed with error: "+f),!1}m.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ua()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(I,{credentials:"same-origin"}),e).then(c,function(a){w("wasm streaming compile failed: "+a);w("falling back to ArrayBuffer instantiation");d(c)});return{}}
m.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:934,maximum:934,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Ya(b)};
var $a=[function(){var a=m.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?qa(Za(a.id)):0},function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?m.dynCall_ii.apply(null,[a].concat(e)):m.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(a){a=D(a);return"undefined"!==typeof process&&a in process.env?qa(Za(process.env[a])):0}];
Ca.push({Dc:function(){ab()}},{Dc:function(){bb()}},{Dc:function(){cb()}},{Dc:function(){db()}},{Dc:function(){eb()}},{Dc:function(){fb()}},{Dc:function(){gb()}},{Dc:function(){hb()}},{Dc:function(){ib()}});var J={};
function jb(a){if(jb.tc){var b=y[a>>2];var c=y[b>>2]}else jb.tc=!0,J.USER=J.LOGNAME="web_user",J.PATH="/",J.PWD="/",J.HOME="/home/web_user",J.LANG="C.UTF-8",J._=m.thisProgram,c=Ga?z(1024):ka(1024),b=Ga?z(256):ka(256),y[b>>2]=c,y[a>>2]=b;a=[];var d=0,e;for(e in J)if("string"===typeof J[e]){var f=e+"="+J[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var l=c,r=0;r<d.length;++r)B[l++>>0]=d.charCodeAt(r);B[l>>0]=0;y[b+4*
e>>2]=c;c+=f.length+1}y[b+4*a.length>>2]=0}function kb(a){m.___errno_location&&(y[m.___errno_location()>>2]=a);return a}function lb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function mb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=lb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function nb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ob(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function pb(){var a=Array.prototype.slice.call(arguments,0);return mb(a.join("/"))}function K(a,b){return mb(a+"/"+b)}
function rb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=lb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var sb=[];function tb(a,b){sb[a]={input:[],output:[],Nc:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.node.rdev];if(!b)throw new L(N.jd);a.tty=b;a.seekable=!1},close:function(a){a.tty.Nc.flush(a.tty)},flush:function(a){a.tty.Nc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Nc.Hd)throw new L(N.vd);for(var e=0,f=0;f<d;f++){try{var l=a.tty.Nc.Hd(a.tty)}catch(r){throw new L(N.td);}if(void 0===l&&0===e)throw new L(N.Pd);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Nc.pd)throw new L(N.vd);
try{for(var e=0;e<d;e++)a.tty.Nc.pd(a.tty,b[c+e])}catch(f){throw new L(N.td);}d&&(a.node.timestamp=Date.now());return e}},wb={Hd:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},pd:function(a,b){null===b||10===b?(ja(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(sa(a.output,0)),a.output=[])}},xb={pd:function(a,b){null===b||10===b?(w(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(w(sa(a.output,0)),a.output=[])}},O={Ac:null,uc:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(N.Td);O.Ac||(O.Ac={dir:{node:{Ec:O.mc.Ec,xc:O.mc.xc,lookup:O.mc.lookup,Tc:O.mc.Tc,rename:O.mc.rename,unlink:O.mc.unlink,rmdir:O.mc.rmdir,readdir:O.mc.readdir,symlink:O.mc.symlink},stream:{Gc:O.lc.Gc}},file:{node:{Ec:O.mc.Ec,xc:O.mc.xc},stream:{Gc:O.lc.Gc,read:O.lc.read,write:O.lc.write,wd:O.lc.wd,Kd:O.lc.Kd,
cd:O.lc.cd}},link:{node:{Ec:O.mc.Ec,xc:O.mc.xc,readlink:O.mc.readlink},stream:{}},yd:{node:{Ec:O.mc.Ec,xc:O.mc.xc},stream:yb}});c=zb(a,b,c,d);16384===(c.mode&61440)?(c.mc=O.Ac.dir.node,c.lc=O.Ac.dir.stream,c.kc={}):32768===(c.mode&61440)?(c.mc=O.Ac.file.node,c.lc=O.Ac.file.stream,c.nc=0,c.kc=null):40960===(c.mode&61440)?(c.mc=O.Ac.link.node,c.lc=O.Ac.link.stream):8192===(c.mode&61440)&&(c.mc=O.Ac.yd.node,c.lc=O.Ac.yd.stream);c.timestamp=Date.now();a&&(a.kc[b]=c);return c},Cg:function(a){if(a.kc&&
a.kc.subarray){for(var b=[],c=0;c<a.nc;++c)b.push(a.kc[c]);return b}return a.kc},Dg:function(a){return a.kc?a.kc.subarray?a.kc.subarray(0,a.nc):new Uint8Array(a.kc):new Uint8Array},Bd:function(a,b){var c=a.kc?a.kc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.kc,a.kc=new Uint8Array(b),0<a.nc&&a.kc.set(c.subarray(0,a.nc),0))},me:function(a,b){if(a.nc!=b)if(0==b)a.kc=null,a.nc=0;else{if(!a.kc||a.kc.subarray){var c=a.kc;a.kc=new Uint8Array(new ArrayBuffer(b));c&&
a.kc.set(c.subarray(0,Math.min(b,a.nc)))}else if(a.kc||(a.kc=[]),a.kc.length>b)a.kc.length=b;else for(;a.kc.length<b;)a.kc.push(0);a.nc=b}},mc:{Ec:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.nc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Jc=4096;b.blocks=Math.ceil(b.size/
b.Jc);return b},xc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.me(a,b.size)},lookup:function(){throw Ab[N.Rd];},Tc:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Bb(b,c)}catch(f){}if(d)for(var e in d.kc)throw new L(N.ud);}delete a.parent.kc[a.name];a.name=c;b.kc[c]=a;a.parent=b},unlink:function(a,b){delete a.kc[b]},rmdir:function(a,b){var c=Bb(a,b),d;for(d in c.kc)throw new L(N.ud);
delete a.kc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.kc)a.kc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(N.wc);return a.link}},lc:{read:function(a,b,c,d,e){var f=a.node.kc;if(e>=a.node.nc)return 0;a=Math.min(a.node.nc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.kc||a.kc.subarray)){if(f)return a.kc=b.subarray(c,c+d),a.nc=d;if(0===a.nc&&0===e)return a.kc=new Uint8Array(b.subarray(c,c+d)),a.nc=d;if(e+d<=a.nc)return a.kc.set(b.subarray(c,c+d),e),d}O.Bd(a,e+d);if(a.kc.subarray&&b.subarray)a.kc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.kc[e+f]=b[c+f];a.nc=Math.max(a.nc,e+d);return d},Gc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.nc);if(0>b)throw new L(N.wc);return b},wd:function(a,
b,c){O.Bd(a.node,b+c);a.node.nc=Math.max(a.node.nc,b+c)},Kd:function(a,b,c,d,e,f,l){if(32768!==(a.node.mode&61440))throw new L(N.jd);c=a.node.kc;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.nc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=z(d);if(!d)throw new L(N.Sd);b.set(c,d)}else a=!1,d=c.byteOffset;return{Jg:d,Vd:a}},cd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(N.jd);if(e&2)return 0;O.lc.write(a,b,0,d,c,!1);return 0}}},P={ad:!1,
oe:function(){P.ad=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.Dd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},xd:function(a){return Buffer.tc?Buffer.from(a):new Buffer(a)},uc:function(a){assert(q);return P.createNode(null,"/",P.Gd(a.od.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(N.wc);a=zb(a,b,c);a.mc=P.mc;a.lc=P.lc;return a},Gd:function(a){try{var b=
fs.lstatSync(a);P.ad&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}return b.mode},vc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.uc.od.root);b.reverse();return pb.apply(null,b)},ae:function(a){a&=-2656257;var b=0,c;for(c in P.Dd)a&c&&(b|=P.Dd[c],a^=c);if(a)throw new L(N.wc);return b},mc:{Ec:function(a){a=P.vc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}P.ad&&!b.Jc&&(b.Jc=4096);P.ad&&!b.blocks&&
(b.blocks=(b.size+b.Jc-1)/b.Jc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Jc:b.Jc,blocks:b.blocks}},xc:function(a,b){var c=P.vc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},lookup:function(a,b){var c=K(P.vc(a),b);c=P.Gd(c);return P.createNode(a,b,c)},Tc:function(a,b,c,d){a=P.createNode(a,
b,c,d);b=P.vc(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new L(N[e.code]);}return a},rename:function(a,b,c){a=P.vc(a);b=K(P.vc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},unlink:function(a,b){a=K(P.vc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}},rmdir:function(a,b){a=K(P.vc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);
}},readdir:function(a){a=P.vc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(N[b.code]);}},symlink:function(a,b,c){a=K(P.vc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},readlink:function(a){var b=P.vc(a);try{return b=fs.readlinkSync(b),b=Cb.relative(Cb.resolve(a.uc.od.root),b)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}}},lc:{open:function(a){var b=P.vc(a.node);try{32768===(a.node.mode&61440)&&(a.Uc=fs.openSync(b,P.ae(a.flags)))}catch(c){if(!c.code)throw c;
throw new L(N[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Uc&&fs.closeSync(a.Uc)}catch(b){if(!b.code)throw b;throw new L(N[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Uc,P.xd(b.buffer),c,d,e)}catch(f){throw new L(N[f.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Uc,P.xd(b.buffer),c,d,e)}catch(f){throw new L(N[f.code]);}},Gc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Uc).size}catch(d){throw new L(N[d.code]);
}if(0>b)throw new L(N.wc);return b}}},Db=null,Eb={},Fb=[],Gb=1,Hb=null,Ib=!0,Jb={},L=null,Ab={};
function Q(a,b){a=rb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ed:!0,qd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.qd)throw new L(40);a=lb(a.split("/").filter(function(a){return!!a}),!1);var e=Db;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Bb(e,a[d]);c=K(c,a[d]);e.bd&&(!f||f&&b.Ed)&&(e=e.bd.root);if(!f||b.ld)for(f=0;40960===(e.mode&61440);)if(e=Kb(c),c=rb(nb(c),e),e=Q(c,{qd:b.qd}).node,40<f++)throw new L(40);}return{path:c,node:e}}
function Lb(a){for(var b;;){if(a===a.parent)return a=a.uc.Ld,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Hb.length}function Nb(a){var b=Mb(a.parent.id,a.name);a.je=Hb[b];Hb[b]=a}function Bb(a,b){var c;if(c=(c=Ob(a,"x"))?c:a.mc.lookup?0:13)throw new L(c,a);for(c=Hb[Mb(a.id,b)];c;c=c.je){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.mc.lookup(a,b)}
function zb(a,b,c,d){Pb||(Pb=function(a,b,c,d){a||(a=this);this.parent=a;this.uc=a.uc;this.bd=null;this.id=Gb++;this.name=b;this.mode=c;this.mc={};this.lc={};this.rdev=d},Pb.prototype={},Object.defineProperties(Pb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Pb(a,b,c,d);Nb(a);return a}
var Qb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Rb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ob(a,b){if(Ib)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Sb(a,b){try{return Bb(a,b),17}catch(c){}return Ob(a,"wx")}
function Tb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Fb[a])return a;throw new L(24);}function Ub(a,b){Vb||(Vb=function(){},Vb.prototype={},Object.defineProperties(Vb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Vb,d;for(d in a)c[d]=a[d];a=c;b=Tb(b);a.fd=b;return Fb[b]=a}var yb={open:function(a){a.lc=Eb[a.node.rdev].lc;a.lc.open&&a.lc.open(a)},Gc:function(){throw new L(29);}};function ub(a,b){Eb[a]={lc:b}}
function Wb(a,b){var c="/"===b,d=!b;if(c&&Db)throw new L(16);if(!c&&!d){var e=Q(b,{Ed:!1});b=e.path;e=e.node;if(e.bd)throw new L(16);if(16384!==(e.mode&61440))throw new L(20);}b={type:a,od:{},Ld:b,ie:[]};a=a.uc(b);a.uc=b;b.root=a;c?Db=a:e&&(e.bd=b,e.uc&&e.uc.ie.push(b))}function Xb(a,b,c){var d=Q(a,{parent:!0}).node;a=ob(a);if(!a||"."===a||".."===a)throw new L(22);var e=Sb(d,a);if(e)throw new L(e);if(!d.mc.Tc)throw new L(1);return d.mc.Tc(d,a,b,c)}function T(a){Xb(a,16895,0)}
function Yb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Xb(a,b|8192,c)}function La(a,b){if(!rb(a))throw new L(2);var c=Q(b,{parent:!0}).node;if(!c)throw new L(2);b=ob(b);var d=Sb(c,b);if(d)throw new L(d);if(!c.mc.symlink)throw new L(1);c.mc.symlink(c,b,a)}function Kb(a){a=Q(a).node;if(!a)throw new L(2);if(!a.mc.readlink)throw new L(22);return rb(Lb(a.parent),a.mc.readlink(a))}
function Ma(a,b,c,d){if(""===a)throw new L(2);if("string"===typeof b){var e=Qb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=mb(a);try{f=Q(a,{ld:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(f){if(b&128)throw new L(17);}else f=Xb(a,c,0),e=!0;if(!f)throw new L(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new L(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Rb(b)||b&512)?21:Ob(f,Rb(b)):2))throw new L(c);if(b&512){c=f;var l;"string"===typeof c?l=Q(c,{ld:!0}).node:l=c;if(!l.mc.xc)throw new L(1);if(16384===(l.mode&61440))throw new L(21);if(32768!==(l.mode&61440))throw new L(22);if(c=Ob(l,"w"))throw new L(c);l.mc.xc(l,{size:0,timestamp:Date.now()})}b&=-641;d=Ub({node:f,path:Lb(f),flags:b,seekable:!0,position:0,lc:f.lc,te:[],error:!1},d);d.lc.open&&d.lc.open(d);!m.logReadFiles||b&1||(Zb||(Zb={}),a in Zb||(Zb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Jb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Jb.onOpenFile(a,f))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function $b(a,b,c){if(null===a.fd)throw new L(9);if(!a.seekable||!a.lc.Gc)throw new L(29);if(0!=c&&1!=c&&2!=c)throw new L(22);a.position=a.lc.Gc(a,b,c);a.te=[]}
function Ja(){L||(L=function(a,b){this.node=b;this.ne=function(a){this.Cc=a};this.ne(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[2].forEach(function(a){Ab[a]=new L(a);Ab[a].stack="<generic error, no stack>"}))}var Ia;function ac(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ka(a,b,c){a=K("/dev",a);var d=ac(!!b,!!c);bc||(bc=64);var e=bc++<<8|0;ub(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,l=0;l<e;l++){try{var r=b()}catch(M){throw new L(5);}if(void 0===r&&0===f)throw new L(11);if(null===r||void 0===r)break;f++;c[d+l]=r}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(A){throw new L(5);}e&&(a.node.timestamp=Date.now());return f}});
Yb(a,d,e)}
var bc,U={},Pb,Vb,Zb,N={Td:1,Rd:2,mg:3,cf:4,td:5,vd:6,ue:7,Ff:8,Qd:9,Je:10,Pd:11,wg:11,Sd:12,Od:13,We:14,Rf:15,He:16,Ve:17,xg:18,jd:19,Tf:20,ef:21,wc:22,Af:23,sf:24,Mc:25,tg:26,Xe:27,Nf:28,lg:29,ig:30,tf:31,bg:32,Se:33,fg:34,Jf:42,$e:43,Ke:44,gf:45,hf:46,jf:47,qf:48,ug:49,Df:50,ff:51,Pe:35,Gf:37,Ae:52,De:53,yg:54,Bf:55,Ee:56,Fe:57,Qe:35,Ge:59,Pf:60,Ef:61,qg:62,Of:63,Kf:64,Lf:65,hg:66,Hf:67,xe:68,ng:69,Le:70,cg:71,vf:72,Te:73,Ce:74,Xf:76,Be:77,gg:78,kf:79,lf:80,pf:81,nf:82,mf:83,Qf:38,ud:39,wf:36,
rf:40,Yf:95,ag:96,Oe:104,Cf:105,ye:97,eg:91,Vf:88,Mf:92,jg:108,Ne:111,ve:98,Me:103,zf:101,xf:100,rg:110,Ye:112,Ze:113,bf:115,ze:114,Re:89,uf:90,dg:93,kg:94,we:99,yf:102,df:106,Sf:107,sg:109,vg:87,Ue:122,og:116,Wf:95,If:123,af:84,Zf:75,Ie:125,Uf:131,$f:130,pg:86},cc={},V=0;function W(){V+=4;return y[V-4>>2]}function dc(){var a=Fb[W()];if(!a)throw new L(N.Qd);return a}var ec=0,fc=0,X=0,hc=0,ic=null,jc=null,kc=!1;function lc(){for(var a=Y.length-1;0<=a;--a)mc(a);Y=[];nc=[]}var nc=[];
function oc(){if(pc&&qc.Oc)for(var a=0;a<nc.length;++a){var b=nc[a];nc.splice(a,1);--a;b.Lg.apply(this,b.zg)}}var pc=0,qc=null,Y=[];function rc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function mc(a){var b=Y[a];b.target.removeEventListener(b.Kc,b.$d,b.Xc);Y.splice(a,1)}
function sc(a){function b(b){++pc;qc=a;oc();a.$c(b);oc();--pc}if(a.Zc)a.$d=b,a.target.addEventListener(a.Kc,b,a.Xc),Y.push(a),kc||(Ea.push(lc),kc=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].Kc==a.Kc&&mc(c--)}var tc={},uc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function vc(a){try{if(!a)return window;"number"===typeof a&&(a=uc[a]||D(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?m.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function wc(a){"number"===typeof a&&(a=D(a));return a&&"#canvas"!==a?"undefined"!==typeof h&&h.dd[a]?h.dd[a]:vc(a):"undefined"!==typeof h&&h.dd.canvas?h.dd.canvas:m.canvas}function ma(){return B.length}function xc(){u("OOM")}
function yc(a,b,c,d,e,f){ec||(ec=z(164));a={target:vc(a),Oc:rc()?!1:!0,Kc:f,Zc:d,$c:function(a){a=a||window.event;var c=ec;E(a.key?a.key:"",C,c+0,32);E(a.code?a.code:"",C,c+32,32);y[c+64>>2]=a.location;y[c+68>>2]=a.ctrlKey;y[c+72>>2]=a.shiftKey;y[c+76>>2]=a.altKey;y[c+80>>2]=a.metaKey;y[c+84>>2]=a.repeat;E(a.locale?a.locale:"",C,c+88,32);E(a.char?a.char:"",C,c+120,32);y[c+152>>2]=a.charCode;y[c+156>>2]=a.keyCode;y[c+160>>2]=a.which;zc(d,e,c,b)&&a.preventDefault()},Xc:c};sc(a)}
function Ac(a,b,c){G[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();y[a+8>>2]=b.screenX;y[a+12>>2]=b.screenY;y[a+16>>2]=b.clientX;y[a+20>>2]=b.clientY;y[a+24>>2]=b.ctrlKey;y[a+28>>2]=b.shiftKey;y[a+32>>2]=b.altKey;y[a+36>>2]=b.metaKey;wa[a+40>>1]=b.button;wa[a+42>>1]=b.buttons;y[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-ic;y[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-jc;if(m.canvas){var d=m.canvas.getBoundingClientRect();
y[a+60>>2]=b.clientX-d.left;y[a+64>>2]=b.clientY-d.top}else y[a+60>>2]=0,y[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},y[a+52>>2]=b.clientX-d.left,y[a+56>>2]=b.clientY-d.top):(y[a+52>>2]=0,y[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(ic=b.screenX,jc=b.screenY)}
function Bc(a,b,c,d,e,f){fc||(fc=z(72));a=vc(a);c={target:a,Oc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Kc:f,Zc:d,$c:function(c){c=c||window.event;Ac(fc,c,a);zc(d,e,fc,b)&&c.preventDefault()},Xc:c};rc()&&"mousedown"==f&&(c.Oc=!1);sc(c)}
function Cc(a,b,c,d){hc||(hc=z(36));a=vc(a);sc({target:a,Oc:!1,Kc:"resize",Zc:d,$c:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=hc;y[l>>2]=c.detail;y[l+4>>2]=document.body.clientWidth;
y[l+8>>2]=document.body.clientHeight;y[l+12>>2]=window.innerWidth;y[l+16>>2]=window.innerHeight;y[l+20>>2]=window.outerWidth;y[l+24>>2]=window.outerHeight;y[l+28>>2]=e[0];y[l+32>>2]=e[1];zc(d,10,l,b)&&c.preventDefault()}},Xc:c})}
function Dc(a,b,c,d,e){function f(c){c=c||window.event;Ac(X,c,a);G[X+72>>3]=c.wheelDeltaX||0;G[X+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);G[X+88>>3]=0;y[X+96>>2]=0;zc(d,9,X,b)&&c.preventDefault()}function l(c){c=c||window.event;var e=X;Ac(e,c,a);G[e+72>>3]=c.deltaX;G[e+80>>3]=c.deltaY;G[e+88>>3]=c.deltaZ;y[e+96>>2]=c.deltaMode;zc(d,9,e,b)&&c.preventDefault()}X||(X=z(104));sc({target:a,Oc:!0,Kc:e,Zc:d,$c:"wheel"==e?l:f,Xc:c})}
function Ec(){if(!h.sc||!h.sc.Fc)return-3;if(!h.sc.Fc.Wd)return-1;if(!h.sc.attributes.Cd)return-3;h.sc.Fc.Wd();return 0}
h={zd:1,Qc:0,Yc:[],Gg:{},rc:[],Fd:[],rd:[],Wc:[],pc:[],yc:[],hd:[],zc:{},sc:null,dd:{},Mg:[],Vc:{},sd:{},Nd:4,ce:function(){h.Jd=new Float32Array(h.Bc);for(var a=0;a<h.Bc;a++)h.Hc[a]=h.Jd.subarray(0,a+1)},oc:function(a){h.Qc||(h.Qc=a)},Pc:function(a){for(var b=h.zd++,c=a.length;c<b;c++)a[c]=null;return b},Bc:256,Jd:null,Hc:[0],be:function(a,b,c,d){a="";for(var e=0;e<b;++e){var f=d?y[d+4*e>>2]:-1;a+=D(y[c+4*e>>2],0>f?void 0:f)}return a},createContext:function(a,b){return(a=a.getContext("webgl",b)||
a.getContext("experimental-webgl",b))&&h.le(a,b)},le:function(a,b){var c=z(8),d={handle:c,attributes:b,version:b.ge,Fc:a};a.canvas&&(a.canvas.Ud=d);h.zc[c]=d;("undefined"===typeof b.Ad||b.Ad)&&h.de(d);return c},he:function(a){h.sc=h.zc[a];m.Ag=k=h.sc&&h.sc.Fc;return!(a&&!k)},getContext:function(a){return h.zc[a]},Zd:function(a){h.sc===h.zc[a]&&(h.sc=null);if("object"===typeof tc)for(var b=h.zc[a].Fc.canvas,c=0;c<Y.length;++c)Y[c].target!=b||mc(c--);h.zc[a]&&h.zc[a].Fc.canvas&&(h.zc[a].Fc.canvas.Ud=
void 0);Fc(h.zc[a]);h.zc[a]=null},de:function(a){a||(a=h.sc);if(!a.ee){a.ee=!0;var b=a.Fc;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.Bg=b.getExtension("EXT_disjoint_timer_query");var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}},ke:function(a){var b=h.rc[a];a=h.Vc[a]={pc:{},nd:0,Rc:-1,Sc:-1};for(var c=a.pc,d=k.getProgramParameter(b,35718),e=0;e<d;++e){var f=k.getActiveUniform(b,e),l=f.name;a.nd=Math.max(a.nd,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var r=k.getUniformLocation(b,l);if(r){var v=h.Pc(h.pc);c[l]=[f.size,v];h.pc[v]=r;for(var x=1;x<f.size;++x)r=k.getUniformLocation(b,
l+"["+x+"]"),v=h.Pc(h.pc),h.pc[v]=r}}}};var Gc=["default","low-power","high-performance"];function Hc(a){return h.he(a)?0:-5}m._emscripten_webgl_make_context_current=Hc;function Ic(a){if(0===a)return 0;a=D(a);if(!J.hasOwnProperty(a))return 0;Ic.tc&&Fc(Ic.tc);a=J[a];var b=ta(a)+1,c=z(b);c&&E(a,B,c,b);Ic.tc=c;return Ic.tc}var Jc=[];function Kc(a,b,c,d){for(var e=0;e<a;e++){var f=k[c](),l=f&&h.Pc(d);f?(f.name=l,d[l]=f):h.oc(1282);y[b+4*e>>2]=l}}
function Lc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&h.oc(1280);return;case 36345:d=0;break;case 34466:var e=k.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=k.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":h.oc(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:h.oc(1280);return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":y[b+4*a>>2]=e[a];break;case "Float":F[b+4*a>>2]=e[a];break;case "Boolean":B[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=e.name|0}catch(f){h.oc(1280);w("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:h.oc(1280);return}switch(c){case "Integer64":aa=
[d>>>0,(g=d,1<=+Oa(g)?0<g?(Ra(+Qa(g/4294967296),4294967295)|0)>>>0:~~+Pa((g-+(~~g>>>0))/4294967296)>>>0:0)];y[b>>2]=aa[0];y[b+4>>2]=aa[1];break;case "Integer":y[b>>2]=d;break;case "Float":F[b>>2]=d;break;case "Boolean":B[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else h.oc(1281)}function Mc(a){var b=ta(a)+1,c=z(b);E(a,C,c,b);return c}var Nc={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Oc={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Pc(a,b,c,d,e){if(b=Nc[b]*Oc[a]){var f=h.Nd;c=e+d*(c*b+f-1&-f);switch(a){case 5121:return C.subarray(e,c);case 5126:return F.subarray(e>>2,c>>2);case 5125:case 34042:return ya.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return xa.subarray(e>>1,c>>1);default:h.oc(1280)}}else h.oc(1280)}function Z(){Z.tc||(Z.tc=[]);Z.tc.push(Qc());return Z.tc.length-1}function Rc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Sc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Tc=[31,29,31,30,31,30,31,31,30,31,30,31],Uc=[31,28,31,30,31,30,31,31,30,31,30,31];function Vc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Rc(a.getFullYear())?Tc:Uc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Wc(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function v(a){a=Vc(new Date(a.qc+1900,0,1),a.gd);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=l(r(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var x=y[d+40>>2];d={re:y[d>>2],qe:y[d+4>>2],ed:y[d+8>>2],Lc:y[d+12>>2],Ic:y[d+16>>2],qc:y[d+20>>2],Md:y[d+24>>2],gd:y[d+28>>2],Ng:y[d+32>>2],pe:y[d+36>>2],
se:x?D(x):""};c=D(c);x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var A in x)c=c.replace(new RegExp(A,"g"),x[A]);var R="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),M="January February March April May June July August September October November December".split(" ");x={"%a":function(a){return R[a.Md].substring(0,3)},"%A":function(a){return R[a.Md]},"%b":function(a){return M[a.Ic].substring(0,
3)},"%B":function(a){return M[a.Ic]},"%C":function(a){return f((a.qc+1900)/100|0,2)},"%d":function(a){return f(a.Lc,2)},"%e":function(a){return e(a.Lc,2," ")},"%g":function(a){return v(a).toString().substring(2)},"%G":function(a){return v(a)},"%H":function(a){return f(a.ed,2)},"%I":function(a){a=a.ed;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Lc+Sc(Rc(a.qc+1900)?Tc:Uc,a.Ic-1),3)},"%m":function(a){return f(a.Ic+1,2)},"%M":function(a){return f(a.qe,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.ed&&12>a.ed?"AM":"PM"},"%S":function(a){return f(a.re,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.qc+1900,a.Ic+1,a.Lc,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.qc+1900,0,1),c=0===b.getDay()?b:Vc(b,7-b.getDay());a=new Date(a.qc+1900,a.Ic,a.Lc);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Sc(Rc(a.getFullYear())?Tc:Uc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.qc+1900,0,4)),c=r(new Date(a.qc+
1901,0,4)),d=Vc(new Date(a.qc+1900,0,1),a.gd);return 0>l(d,b)?"53":0>=l(c,d)?"01":f(Math.ceil((b.getFullYear()<a.qc+1900?a.gd+32-b.getDate():a.gd+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.qc+1900,a.Ic+1,a.Lc,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.qc,0,1),c=1===b.getDay()?b:Vc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.qc+1900,a.Ic,a.Lc);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Sc(Rc(a.getFullYear())?Tc:Uc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":
"00"},"%y":function(a){return(a.qc+1900).toString().substring(2)},"%Y":function(a){return a.qc+1900},"%z":function(a){a=a.pe;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.se},"%%":function(){return"%"}};for(A in x)0<=c.indexOf(A)&&(c=c.replace(new RegExp(A,"g"),x[A](d)));A=Za(c,!1);if(A.length>b)return 0;B.set(A,a);return A.length-1}Ja();Hb=Array(4096);Wb(O,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");ub(259,{read:function(){return 0},write:function(a,b,c,l){return l}});Yb("/dev/null",259);tb(1280,wb);tb(1536,xb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(q)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});Ka("random",b);Ka("urandom",b);T("/dev/shm");
T("/dev/shm/tmp")})();T("/proc");T("/proc/self");T("/proc/self/fd");Wb({uc:function(){var a=zb("/proc/self","fd",16895,73);a.mc={lookup:function(a,c){var b=Fb[+c];if(!b)throw new L(9);a={parent:null,uc:{Ld:"fake"},mc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(q){var fs=require("fs"),Cb=require("path");P.oe()}h.ce();for(var Xc=0;32>Xc;Xc++)Jc.push(Array(Xc));function Za(a,b){var c=Array(ta(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var ad=m.asm({},{c:u,tb:jb,e:function(a){return z(a)},Ja:function(){pa=!0;throw"Pure virtual function called!";},d:function(a){"uncaught_exception"in Yc?Yc.Id++:Yc.Id=1;throw a;},sa:function(){return!!Yc.Id},l:function(){},$:function(){kb(1);return-1},u:kb,t:function(a,b){V=b;try{var c=dc();W();var d=W(),e=W(),f=W();$b(c,d,f);y[e>>2]=c.position;c.md&&0===d&&0===f&&(c.md=null);return 0}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.Cc}},sb:function(a,b){V=b;try{var c=dc(),d=W();a:{var e=
W();for(b=a=0;b<e;b++){var f=y[d+(8*b+4)>>2],l=c,r=y[d+8*b>>2],v=f,x=void 0,A=B;if(0>v||0>x)throw new L(22);if(null===l.fd)throw new L(9);if(1===(l.flags&2097155))throw new L(9);if(16384===(l.node.mode&61440))throw new L(21);if(!l.lc.read)throw new L(22);var R="undefined"!==typeof x;if(!R)x=l.position;else if(!l.seekable)throw new L(29);var M=l.lc.read(l,A,r,v,x);R||(l.position+=M);var ea=M;if(0>ea){var S=-1;break a}a+=ea;if(ea<f)break}S=a}return S}catch(qb){return"undefined"!==typeof U&&qb instanceof
L||u(qb),-qb.Cc}},z:function(a,b){V=b;try{var c=dc(),d=W();a:{var e=W();for(b=a=0;b<e;b++){var f=c,l=y[d+8*b>>2],r=y[d+(8*b+4)>>2],v=void 0,x=B;if(0>r||0>v)throw new L(22);if(null===f.fd)throw new L(9);if(0===(f.flags&2097155))throw new L(9);if(16384===(f.node.mode&61440))throw new L(21);if(!f.lc.write)throw new L(22);f.flags&1024&&$b(f,0,2);var A="undefined"!==typeof v;if(!A)v=f.position;else if(!f.seekable)throw new L(29);var R=f.lc.write(f,x,l,r,v,void 0);A||(f.position+=R);try{if(f.path&&Jb.onWriteToFile)Jb.onWriteToFile(f.path)}catch(S){console.log("FS.trackingDelegate['onWriteToFile']('"+
f.path+"') threw an exception: "+S.message)}var M=R;if(0>M){var ea=-1;break a}a+=M}ea=a}return ea}catch(S){return"undefined"!==typeof U&&S instanceof L||u(S),-S.Cc}},m:function(a,b){V=b;try{var c=dc();switch(W()){case 0:var d=W();return 0>d?-N.wc:Ma(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=W(),c.flags|=d,0;case 12:return d=W(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-N.wc;case 9:return kb(N.wc),-1;default:return-N.wc}}catch(e){return"undefined"!==
typeof U&&e instanceof L||u(e),-e.Cc}},Va:function(a,b){V=b;try{var c=D(W());var d=W();if(d&-8)var e=-N.wc;else{var f=Q(c,{ld:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Ob(f,a)?-N.Od:0}return e}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.Cc}},Ua:function(a,b){V=b;try{var c=D(W()),d=W(),e=W();return Ma(c,d,e).fd}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.Cc}},y:function(a,b){V=b;try{var c=dc(),d=W();switch(d){case 21509:case 21505:return c.tty?
0:-N.Mc;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-N.Mc;case 21519:if(!c.tty)return-N.Mc;var e=W();return y[e>>2]=0;case 21520:return c.tty?-N.wc:-N.Mc;case 21531:a=e=W();if(!c.lc.fe)throw new L(25);return c.lc.fe(c,d,a);case 21523:return c.tty?0:-N.Mc;case 21524:return c.tty?0:-N.Mc;default:u("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.Cc}},x:function(a,b){V=b;try{var c=dc();if(null===c.fd)throw new L(9);c.md&&(c.md=
null);try{c.lc.close&&c.lc.close(c)}catch(d){throw d;}finally{Fb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.Cc}},Ta:function(a,b){V=b;try{var c=W(),d=W(),e=cc[c];if(!e)return 0;if(d===e.Eg){var f=Fb[e.fd],l=e.flags,r=new Uint8Array(C.subarray(c,c+d));f&&f.lc.cd&&f.lc.cd(f,r,0,d,l);cc[c]=null;e.Vd&&Fc(e.Fg)}return 0}catch(v){return"undefined"!==typeof U&&v instanceof L||u(v),-v.Cc}},j:function(){},b:function(){m.abort()},Sa:function(a){return $a[a]()},
Ra:function(a,b){return $a[a](b)},Qa:function(a,b,c){return $a[a](b,c)},Pa:function(a,b,c){a=wc(a);if(!a)return-4;y[b>>2]=a.width;y[c>>2]=a.height},Oa:function(){return window.devicePixelRatio||1},Na:function(a,b,c){a=a?vc(a):m.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),G[b>>3]=a.right-a.left,G[c>>3]=a.bottom-a.top):(G[b>>3]=a.clientWidth,G[c>>3]=a.clientHeight);return 0},Ma:ma,La:function(a,b,c){C.set(C.subarray(b,b+c),a)},Ka:function(a){xc(a)},q:function(a,b,c){a=
wc(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ia:function(a,b,c,d){yc(a,b,c,d,2,"keydown");return 0},Ha:function(a,b,c,d){yc(a,b,c,d,3,"keyup");return 0},Ga:function(a,b,c,d){Bc(a,b,c,d,5,"mousedown");return 0},Fa:function(a,b,c,d){Bc(a,b,c,d,8,"mousemove");return 0},Ea:function(a,b,c,d){Bc(a,b,c,d,6,"mouseup");return 0},Da:function(a,b,c,d){Cc(a,b,c,d);return 0},Ca:function(a,b,c,d){a=vc(a);return"undefined"!==typeof a.onwheel?(Dc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Dc(a,
b,c,d,"mousewheel"),0):-1},Ba:function(){return Ec()},Aa:function(a,b){var c={};b>>=2;c.alpha=!!y[b];c.depth=!!y[b+1];c.stencil=!!y[b+2];c.antialias=!!y[b+3];c.premultipliedAlpha=!!y[b+4];c.preserveDrawingBuffer=!!y[b+5];c.powerPreference=Gc[y[b+6]];c.failIfMajorPerformanceCaveat=!!y[b+7];c.ge=y[b+8];c.Hg=y[b+9];c.Ad=y[b+10];c.Cd=y[b+11];c.Ig=y[b+12];c.Kg=y[b+13];a=wc(a);return!a||c.Cd?0:h.createContext(a,c)},za:function(a){h.sc==a&&(h.sc=0);h.Zd(a)},ya:function(a){a>>=2;for(var b=0;14>b;++b)y[a+
b]=0;y[a]=y[a+1]=y[a+3]=y[a+4]=y[a+8]=y[a+10]=1},xa:Hc,i:function(a){Zc(a)},h:Ic,p:function(a){k.activeTexture(a)},wa:function(a,b){k.attachShader(h.rc[a],h.yc[b])},va:function(a,b,c){k.bindAttribLocation(h.rc[a],b,D(c))},w:function(a,b){k.bindBuffer(a,h.Yc[b])},ua:function(a,b){k.bindFramebuffer(a,h.Fd[b])},ta:function(a,b){k.bindRenderbuffer(a,h.rd[b])},o:function(a,b){k.bindTexture(a,h.Wc[b])},ra:function(a){k.bindVertexArray(h.hd[a])},qa:function(a,b){k.blendEquationSeparate(a,b)},pa:function(a,
b){k.blendFunc(a,b)},oa:function(a,b,c,d){k.bufferData(a,c?C.subarray(c,c+b):b,d)},na:function(a,b,c,d){k.bufferSubData(a,b,C.subarray(d,d+c))},ma:function(a){return k.checkFramebufferStatus(a)},la:function(a){k.clear(a)},ka:function(a,b,c,d){k.clearColor(a,b,c,d)},ja:function(a){k.clearDepth(a)},ia:function(a){k.compileShader(h.yc[a])},v:function(a,b,c,d,e,f,l,r,v){k.compressedTexSubImage2D(a,b,c,d,e,f,l,v?C.subarray(v,v+r):null)},ha:function(a,b,c,d,e,f,l,r){k.copyTexSubImage2D(a,b,c,d,e,f,l,r)},
ga:function(){var a=h.Pc(h.rc),b=k.createProgram();b.name=a;h.rc[a]=b;return a},fa:function(a){var b=h.Pc(h.yc);h.yc[b]=k.createShader(a);return b},ea:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=h.Yc[d];e&&(k.deleteBuffer(e),e.name=0,h.Yc[d]=null,d==h.Xd&&(h.Xd=0),d==h.Yd&&(h.Yd=0))}},da:function(a){if(a){var b=h.rc[a];b?(k.deleteProgram(b),b.name=0,h.rc[a]=null,h.Vc[a]=null):h.oc(1281)}},ca:function(a){if(a){var b=h.yc[a];b?(k.deleteShader(b),h.yc[a]=null):h.oc(1281)}},ba:function(a,b){for(var c=
0;c<a;c++){var d=y[b+4*c>>2],e=h.Wc[d];e&&(k.deleteTexture(e),e.name=0,h.Wc[d]=null)}},aa:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];k.deleteVertexArray(h.hd[d]);h.hd[d]=null}},_:function(a){k.disableVertexAttribArray(a)},Z:function(a,b,c){k.drawArrays(a,b,c)},Y:function(a,b,c,d){k.drawArraysInstanced(a,b,c,d)},X:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];k.drawBuffers(c)},W:function(a,b,c,d){k.drawElements(a,b,c,d)},V:function(a,b,c,d,e){k.drawElementsInstanced(a,b,c,d,
e)},U:function(a){k.enable(a)},T:function(a){k.enableVertexAttribArray(a)},S:function(a,b,c,d){k.framebufferRenderbuffer(a,b,c,h.rd[d])},R:function(a,b,c,d,e){k.framebufferTexture2D(a,b,c,h.Wc[d],e)},Q:function(a,b){Kc(a,b,"createBuffer",h.Yc)},P:function(a,b){Kc(a,b,"createFramebuffer",h.Fd)},O:function(a,b){Kc(a,b,"createRenderbuffer",h.rd)},N:function(a,b){Kc(a,b,"createTexture",h.Wc)},M:function(a,b){Kc(a,b,"createVertexArray",h.hd)},L:function(a){k.generateMipmap(a)},K:function(a,b,c){c?y[c>>
2]=k.getBufferParameter(a,b):h.oc(1281)},J:function(){if(h.Qc){var a=h.Qc;h.Qc=0;return a}return k.getError()},I:function(a,b){Lc(a,b,"Float")},n:function(a,b){Lc(a,b,"Integer")},H:function(a,b,c,d){a=k.getProgramInfoLog(h.rc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},s:function(a,b,c){if(c)if(a>=h.zd)h.oc(1281);else{var d=h.Vc[a];if(d)if(35716==b)a=k.getProgramInfoLog(h.rc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b)y[c>>2]=
d.nd;else if(35722==b){if(-1==d.Rc){a=h.rc[a];var e=k.getProgramParameter(a,35721);for(b=d.Rc=0;b<e;++b)d.Rc=Math.max(d.Rc,k.getActiveAttrib(a,b).name.length+1)}y[c>>2]=d.Rc}else if(35381==b){if(-1==d.Sc)for(a=h.rc[a],e=k.getProgramParameter(a,35382),b=d.Sc=0;b<e;++b)d.Sc=Math.max(d.Sc,k.getActiveUniformBlockName(a,b).length+1);y[c>>2]=d.Sc}else y[c>>2]=k.getProgramParameter(h.rc[a],b);else h.oc(1282)}else h.oc(1281)},G:function(a,b,c,d){a=k.getShaderInfoLog(h.yc[a]);null===a&&(a="(unknown error)");
0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},r:function(a,b,c){c?35716==b?(a=k.getShaderInfoLog(h.yc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1):35720==b?(a=k.getShaderSource(h.yc[a]),y[c>>2]=null===a||0==a.length?0:a.length+1):y[c>>2]=k.getShaderParameter(h.yc[a],b):h.oc(1281)},k:function(a){if(h.sd[a])return h.sd[a];switch(a){case 7939:var b=k.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Mc(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
k.getParameter(a))||h.oc(1280);b=Mc(b);break;case 7938:b=Mc("OpenGL ES 2.0 ("+k.getParameter(k.VERSION)+")");break;case 35724:b=k.getParameter(k.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Mc(b);break;default:return h.oc(1280),0}return h.sd[a]=b},F:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=
h.Vc[a]&&h.Vc[a].pc[b])&&0<=c&&c<a[0]?a[1]+c:-1},E:function(a){k.linkProgram(h.rc[a]);h.ke(a)},D:function(a,b){3317==a&&(h.Nd=b);k.pixelStorei(a,b)},C:function(a,b,c,d,e,f,l){(l=Pc(f,e,c,d,l))?k.readPixels(a,b,c,d,e,f,l):h.oc(1280)},B:function(a,b,c,d){k.renderbufferStorage(a,b,c,d)},rb:function(a,b,c,d){b=h.be(a,b,c,d);k.shaderSource(h.yc[a],b)},qb:function(a,b,c,d,e,f,l,r,v){k.texImage2D(a,b,c,d,e,f,l,r,v?Pc(r,l,d,e,v):null)},pb:function(a,b,c){k.texParameterf(a,b,c)},ob:function(a,b,c){k.texParameterf(a,
b,F[c>>2])},nb:function(a,b,c){k.texParameteri(a,b,c)},A:function(a,b,c,d,e,f,l,r,v){var x=null;v&&(x=Pc(r,l,e,f,v));k.texSubImage2D(a,b,c,d,e,f,l,r,x)},mb:function(a,b,c){if(b<=h.Bc)for(var d=h.Hc[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);k.uniform1fv(h.pc[a],d)},lb:function(a,b,c){k.uniform1iv(h.pc[a],y.subarray(c>>2,c+4*b>>2))},kb:function(a,b,c){if(2*b<=h.Bc)for(var d=h.Hc[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);k.uniform2fv(h.pc[a],
d)},jb:function(a,b,c){k.uniform2iv(h.pc[a],y.subarray(c>>2,c+8*b>>2))},ib:function(a,b,c){if(3*b<=h.Bc)for(var d=h.Hc[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);k.uniform3fv(h.pc[a],d)},hb:function(a,b,c){k.uniform3iv(h.pc[a],y.subarray(c>>2,c+12*b>>2))},gb:function(a,b,c){if(4*b<=h.Bc)for(var d=h.Hc[4*b-1],e=0;e<4*b;e+=4)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2],d[e+3]=F[c+(4*e+12)>>2];else d=F.subarray(c>>
2,c+16*b>>2);k.uniform4fv(h.pc[a],d)},fb:function(a,b,c){k.uniform4iv(h.pc[a],y.subarray(c>>2,c+16*b>>2))},eb:function(a,b,c,d){if(4*b<=h.Bc)for(var e=h.Hc[4*b-1],f=0;f<4*b;f+=4)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);k.uniformMatrix2fv(h.pc[a],!!c,e)},db:function(a,b,c,d){if(9*b<=h.Bc)for(var e=h.Hc[9*b-1],f=0;f<9*b;f+=9)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+
(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);k.uniformMatrix3fv(h.pc[a],!!c,e)},cb:function(a,b,c,d){if(16*b<=h.Bc)for(var e=h.Hc[16*b-1],f=0;f<16*b;f+=16)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2],e[f+9]=F[d+(4*f+36)>>2],e[f+10]=F[d+(4*f+
40)>>2],e[f+11]=F[d+(4*f+44)>>2],e[f+12]=F[d+(4*f+48)>>2],e[f+13]=F[d+(4*f+52)>>2],e[f+14]=F[d+(4*f+56)>>2],e[f+15]=F[d+(4*f+60)>>2];else e=F.subarray(d>>2,d+64*b>>2);k.uniformMatrix4fv(h.pc[a],!!c,e)},bb:function(a){k.useProgram(h.rc[a])},ab:function(a,b){k.vertexAttribDivisor(a,b)},$a:function(a,b,c,d,e,f){k.vertexAttribPointer(a,b,c,!!d,e,f)},_a:function(a,b,c,d){k.viewport(a,b,c,d)},g:function(a){var b=Z.tc[a];Z.tc.splice(a,1);$c(b)},f:Z,Za:function(){u("trap!")},Ya:function(){return 0},Xa:function(a,
b,c,d){return Wc(a,b,c,d)},Wa:xc,a:la},buffer);m.asm=ad;
var db=m.__GLOBAL__sub_I_driverSpecific_cpp=function(){return m.asm.ub.apply(null,arguments)},bb=m.__GLOBAL__sub_I_importStaticPlugin_cpp=function(){return m.asm.vb.apply(null,arguments)},cb=m.__GLOBAL__sub_I_importStaticPlugin_cpp_11=function(){return m.asm.wb.apply(null,arguments)},ib=m.__GLOBAL__sub_I_iostream_cpp=function(){return m.asm.xb.apply(null,arguments)},fb=m.__GLOBAL__sub_I_resource_MagnumFont_cpp=function(){return m.asm.yb.apply(null,arguments)},eb=m.__GLOBAL__sub_I_resource_MagnumShaders_RCS_cpp=
function(){return m.asm.zb.apply(null,arguments)},ab=m.__GLOBAL__sub_I_resource_TextExample_RESOURCES_cpp=function(){return m.asm.Ab.apply(null,arguments)},gb=m.__GLOBAL__sub_I_resource_TgaImporter_cpp=function(){return m.asm.Bb.apply(null,arguments)},Yc=m.__ZSt18uncaught_exceptionv=function(){return m.asm.Cb.apply(null,arguments)},hb=m.___emscripten_environ_constructor=function(){return m.asm.Db.apply(null,arguments)};m.___errno_location=function(){return m.asm.Eb.apply(null,arguments)};
var Fc=m._free=function(){return m.asm.Fb.apply(null,arguments)};m._main=function(){return m.asm.Gb.apply(null,arguments)};var z=m._malloc=function(){return m.asm.Hb.apply(null,arguments)},va=m.stackAlloc=function(){return m.asm.hc.apply(null,arguments)},$c=m.stackRestore=function(){return m.asm.ic.apply(null,arguments)},Qc=m.stackSave=function(){return m.asm.jc.apply(null,arguments)};m.dynCall_ii=function(){return m.asm.Ib.apply(null,arguments)};
m.dynCall_iii=function(){return m.asm.Jb.apply(null,arguments)};var zc=m.dynCall_iiii=function(){return m.asm.Kb.apply(null,arguments)};m.dynCall_iiiii=function(){return m.asm.Lb.apply(null,arguments)};m.dynCall_iiiiid=function(){return m.asm.Mb.apply(null,arguments)};m.dynCall_iiiiii=function(){return m.asm.Nb.apply(null,arguments)};m.dynCall_iiiiiid=function(){return m.asm.Ob.apply(null,arguments)};m.dynCall_iiiiiii=function(){return m.asm.Pb.apply(null,arguments)};
m.dynCall_iiiiiiii=function(){return m.asm.Qb.apply(null,arguments)};m.dynCall_iiiiiiiii=function(){return m.asm.Rb.apply(null,arguments)};m.dynCall_iiiiij=function(){return m.asm.Sb.apply(null,arguments)};m.dynCall_v=function(){return m.asm.Tb.apply(null,arguments)};m.dynCall_vf=function(){return m.asm.Ub.apply(null,arguments)};m.dynCall_vi=function(){return m.asm.Vb.apply(null,arguments)};m.dynCall_vif=function(){return m.asm.Wb.apply(null,arguments)};
m.dynCall_vii=function(){return m.asm.Xb.apply(null,arguments)};m.dynCall_viif=function(){return m.asm.Yb.apply(null,arguments)};m.dynCall_viii=function(){return m.asm.Zb.apply(null,arguments)};m.dynCall_viiif=function(){return m.asm._b.apply(null,arguments)};m.dynCall_viiifi=function(){return m.asm.$b.apply(null,arguments)};m.dynCall_viiii=function(){return m.asm.ac.apply(null,arguments)};m.dynCall_viiiii=function(){return m.asm.bc.apply(null,arguments)};
m.dynCall_viiiiii=function(){return m.asm.cc.apply(null,arguments)};m.dynCall_viiiiiii=function(){return m.asm.dc.apply(null,arguments)};m.dynCall_viiiiiiii=function(){return m.asm.ec.apply(null,arguments)};m.dynCall_viiiiiiiii=function(){return m.asm.fc.apply(null,arguments)};m.dynCall_viijii=function(){return m.asm.gc.apply(null,arguments)};m.asm=ad;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ia.prototype=Error();
ia.prototype.constructor=ia;Ta=function bd(){m.calledRun||cd();m.calledRun||(Ta=bd)};m.callMain=function(a){a=a||[];Ha();var b=a.length+1,c=va(4*(b+1));y[c>>2]=ua(m.thisProgram);for(var d=1;d<b;d++)y[(c>>2)+d]=ua(a[d-1]);y[(c>>2)+b]=0;try{var e=m._main(b,c,0);Zc(e,!0)}catch(f){f instanceof ia||("SimulateInfiniteLoop"==f?m.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),w("exception thrown: "+a),m.quit(1,f)))}finally{}};
function cd(a){function b(){if(!m.calledRun&&(m.calledRun=!0,!pa)){Ha();Ib=!1;Aa(Da);if(m.onRuntimeInitialized)m.onRuntimeInitialized();m._main&&dd&&m.callMain(a);if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();Fa.unshift(b)}Aa(Fa)}}a=a||m.arguments;if(!(0<H)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Na();Aa(Ba);0<H||m.calledRun||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},
1);b()},1)):b())}}m.run=cd;function Zc(a,b){if(!b||!m.noExitRuntime||0!==a){if(!m.noExitRuntime&&(pa=!0,m.onExit))m.onExit(a);m.quit(a,new ia(a))}}function u(a){if(m.onAbort)m.onAbort(a);void 0!==a?(ja(a),w(a),a=JSON.stringify(a)):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}m.abort=u;if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();var dd=!0;m.noInitialRun&&(dd=!1);m.noExitRuntime=!0;cd();
