var aa,ba;var g,k,l;var m;m||(m=typeof Module !== 'undefined' ? Module : {});var ca={},da;for(da in m)m.hasOwnProperty(da)&&(ca[da]=m[da]);m.arguments=[];m.thisProgram="./this.program";m.quit=function(a,b){throw b;};m.preRun=[];m.postRun=[];var ea=!1,fa=!1,ha=!1,ia=!1;ea="object"===typeof window;fa="function"===typeof importScripts;ha="object"===typeof process&&"function"===typeof require&&!ea&&!fa;ia=!ea&&!ha&&!fa;var p="";
if(ha){p=__dirname+"/";var ja,ka;m.read=function(a,b){ja||(ja=require("fs"));ka||(ka=require("path"));a=ka.normalize(a);a=ja.readFileSync(a);return b?a:a.toString()};m.readBinary=function(a){a=m.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(m.thisProgram=process.argv[1].replace(/\\/g,"/"));m.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=m);process.on("uncaughtException",function(a){if(!(a instanceof la))throw a;});process.on("unhandledRejection",
q);m.quit=function(a){process.exit(a)};m.inspect=function(){return"[Emscripten Module object]"}}else if(ia)"undefined"!=typeof read&&(m.read=function(a){return read(a)}),m.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m.arguments=scriptArgs:"undefined"!=typeof arguments&&(m.arguments=arguments),"function"===typeof quit&&(m.quit=function(a){quit(a)});else if(ea||fa)fa?
p=self.location.href:document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",m.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(m.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),m.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},m.setWindowTitle=function(a){document.title=a};var ma=m.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),r=m.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ma);for(da in ca)ca.hasOwnProperty(da)&&(m[da]=ca[da]);ca=void 0;
function na(a){var b=u[ra>>2];a=b+a+15&-16;if(a<=sa())u[ra>>2]=a;else return 0;return b}function ta(a){ua||(ua={});ua[a]||(ua[a]=1,r(a))}var ua,va={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&r("no native wasm support detected");var wa,v=!1;function assert(a,b){a||q("Assertion failed: "+b)}
function xa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=w(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)u[a>>2]=0;for(b=d+c;a<b;)y[a++>>0]=0;return d}a.subarray||a.slice?A.set(a,d):A.set(new Uint8Array(a),d);return d}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function B(a,b){return a?za(A,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ea(a){var b=Da(a)+1,c=Fa(b);D(a,y,c,b);return c}var buffer,y,A,Ga,Ha,u,Ia,F,I,ra=151744,Ja=m.TOTAL_MEMORY||16777216;5242880>Ja&&r("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Ja+"! (TOTAL_STACK=5242880)");
m.buffer?buffer=m.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(wa=new WebAssembly.Memory({initial:Ja/65536,maximum:Ja/65536}),buffer=wa.buffer):buffer=new ArrayBuffer(Ja);m.HEAP8=y=new Int8Array(buffer);m.HEAP16=Ga=new Int16Array(buffer);m.HEAP32=u=new Int32Array(buffer);m.HEAPU8=A=new Uint8Array(buffer);m.HEAPU16=Ha=new Uint16Array(buffer);m.HEAPU32=Ia=new Uint32Array(buffer);m.HEAPF32=F=new Float32Array(buffer);m.HEAPF64=I=new Float64Array(buffer);u[ra>>2]=5394880;
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Oc;"number"===typeof c?void 0===b.nd?m.dynCall_v(c):m.dynCall_vi(c,b.nd):c(void 0===b.nd?null:b.nd)}}}var La=[],Ma=[],Na=[],Oa=[],Pa=[],Qa=!1;
function Ra(){Qa||(Qa=!0,m.noFSInit||Sa||(Sa=!0,Ta(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?Ua("stdin",m.stdin):Va("/dev/tty","/dev/stdin"),m.stdout?Ua("stdout",null,m.stdout):Va("/dev/tty","/dev/stdout"),m.stderr?Ua("stderr",null,m.stderr):Va("/dev/tty1","/dev/stderr"),Wa("/dev/stdin","r"),Wa("/dev/stdout","w"),Wa("/dev/stderr","w")),Ka(Ma))}function Xa(){var a=m.preRun.shift();La.unshift(a)}var Ya=Math.abs,Za=Math.ceil,$a=Math.floor,ab=Math.min,bb=0,cb=null,db=null;
function eb(){bb++;m.monitorRunDependencies&&m.monitorRunDependencies(bb)}function fb(){bb--;m.monitorRunDependencies&&m.monitorRunDependencies(bb);if(0==bb&&(null!==cb&&(clearInterval(cb),cb=null),db)){var a=db;db=null;a()}}m.preloadedImages={};m.preloadedAudios={};function gb(){var a=hb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var hb="magnum-audio.wasm";
if(!gb()){var ib=hb;hb=m.locateFile?m.locateFile(ib,p):p+ib}function jb(){try{if(m.wasmBinary)return new Uint8Array(m.wasmBinary);if(m.readBinary)return m.readBinary(hb);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}
function kb(){return m.wasmBinary||!ea&&!fa||"function"!==typeof fetch?new Promise(function(a){a(jb())}):fetch(hb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+hb+"'";return a.arrayBuffer()}).catch(function(){return jb()})}
function lb(a){function b(a){m.asm=a.exports;fb()}function c(a){b(a.instance)}function d(a){kb().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){r("failed to asynchronously prepare wasm: "+a);q(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:va};eb();if(m.instantiateWasm)try{return m.instantiateWasm(e,b)}catch(f){return r("Module.instantiateWasm callback failed with error: "+f),!1}m.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
gb()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(hb,{credentials:"same-origin"}),e).then(c,function(a){r("wasm streaming compile failed: "+a);r("falling back to ArrayBuffer instantiation");d(c)});return{}}m.asm=function(a,b){b.memory=wa;b.table=new WebAssembly.Table({initial:844,maximum:844,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return lb(b)};
var nb=[function(){var a=m.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?xa(mb(a.id)):0},function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?m.dynCall_ii.apply(null,[a].concat(e)):m.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(a){a=B(a);return"undefined"!==typeof process&&a in process.env?xa(mb(process.env[a])):0}];
Ma.push({Oc:function(){ob()}},{Oc:function(){pb()}},{Oc:function(){qb()}},{Oc:function(){rb()}},{Oc:function(){sb()}},{Oc:function(){tb()}},{Oc:function(){ub()}});var L={};
function vb(a){if(vb.xf){var b=u[a>>2];var c=u[b>>2]}else vb.xf=!0,L.USER=L.LOGNAME="web_user",L.PATH="/",L.PWD="/",L.HOME="/home/web_user",L.LANG="C.UTF-8",L._=m.thisProgram,c=Qa?w(1024):na(1024),b=Qa?w(256):na(256),u[b>>2]=c,u[a>>2]=b;a=[];var d=0,e;for(e in L)if("string"===typeof L[e]){var f=e+"="+L[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var h=c,n=0;n<d.length;++n)y[h++>>0]=d.charCodeAt(n);y[h>>0]=0;u[b+4*
e>>2]=c;c+=f.length+1}u[b+4*a.length>>2]=0}function wb(a){m.___errno_location&&(u[m.___errno_location()>>2]=a);return a}function xb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function yb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=xb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function zb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ab(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Bb(){var a=Array.prototype.slice.call(arguments,0);return yb(a.join("/"))}function Cb(a,b){return yb(a+"/"+b)}
function Db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=xb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Eb=[];function Fb(a,b){Eb[a]={input:[],output:[],vd:b};Gb(a,Hb)}
var Hb={open:function(a){var b=Eb[a.node.rdev];if(!b)throw new M(N.ke);a.tty=b;a.seekable=!1},close:function(a){a.tty.vd.flush(a.tty)},flush:function(a){a.tty.vd.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.vd.Ve)throw new M(N.Ge);for(var e=0,f=0;f<d;f++){try{var h=a.tty.vd.Ve(a.tty)}catch(n){throw new M(N.Ee);}if(void 0===h&&0===e)throw new M(N.pf);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.vd.we)throw new M(N.Ge);
try{for(var e=0;e<d;e++)a.tty.vd.we(a.tty,b[c+e])}catch(f){throw new M(N.Ee);}d&&(a.node.timestamp=Date.now());return e}},Ib={Ve:function(a){if(!a.input.length){var b=null;if(ha){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(h){}}try{d=fs.readSync(e,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b,!0)}return a.input.shift()},we:function(a,b){null===b||10===b?(ma(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ma(za(a.output,0)),a.output=[])}},Jb={we:function(a,b){null===b||10===b?(r(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(r(za(a.output,0)),a.output=[])}},O={$c:null,Sc:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(N.tf);O.$c||(O.$c={dir:{node:{gd:O.Bc.gd,Xc:O.Bc.Xc,lookup:O.Bc.lookup,Hd:O.Bc.Hd,rename:O.Bc.rename,unlink:O.Bc.unlink,rmdir:O.Bc.rmdir,readdir:O.Bc.readdir,symlink:O.Bc.symlink},stream:{kd:O.Ac.kd}},file:{node:{gd:O.Bc.gd,Xc:O.Bc.Xc},stream:{kd:O.Ac.kd,read:O.Ac.read,write:O.Ac.write,Ie:O.Ac.Ie,bf:O.Ac.bf,
de:O.Ac.de}},link:{node:{gd:O.Bc.gd,Xc:O.Bc.Xc,readlink:O.Bc.readlink},stream:{}},Ke:{node:{gd:O.Bc.gd,Xc:O.Bc.Xc},stream:Kb}});c=Lb(a,b,c,d);16384===(c.mode&61440)?(c.Bc=O.$c.dir.node,c.Ac=O.$c.dir.stream,c.yc={}):32768===(c.mode&61440)?(c.Bc=O.$c.file.node,c.Ac=O.$c.file.stream,c.Fc=0,c.yc=null):40960===(c.mode&61440)?(c.Bc=O.$c.link.node,c.Ac=O.$c.link.stream):8192===(c.mode&61440)&&(c.Bc=O.$c.Ke.node,c.Ac=O.$c.Ke.stream);c.timestamp=Date.now();a&&(a.yc[b]=c);return c},Di:function(a){if(a.yc&&
a.yc.subarray){for(var b=[],c=0;c<a.Fc;++c)b.push(a.yc[c]);return b}return a.yc},Ei:function(a){return a.yc?a.yc.subarray?a.yc.subarray(0,a.Fc):new Uint8Array(a.yc):new Uint8Array},Ne:function(a,b){var c=a.yc?a.yc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.yc,a.yc=new Uint8Array(b),0<a.Fc&&a.yc.set(c.subarray(0,a.Fc),0))},Rf:function(a,b){if(a.Fc!=b)if(0==b)a.yc=null,a.Fc=0;else{if(!a.yc||a.yc.subarray){var c=a.yc;a.yc=new Uint8Array(new ArrayBuffer(b));c&&
a.yc.set(c.subarray(0,Math.min(b,a.Fc)))}else if(a.yc||(a.yc=[]),a.yc.length>b)a.yc.length=b;else for(;a.yc.length<b;)a.yc.push(0);a.Fc=b}},Bc:{gd:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Fc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.od=4096;b.blocks=Math.ceil(b.size/
b.od);return b},Xc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Rf(a,b.size)},lookup:function(){throw Mb[N.rf];},Hd:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Nb(b,c)}catch(f){}if(d)for(var e in d.yc)throw new M(N.Fe);}delete a.parent.yc[a.name];a.name=c;b.yc[c]=a;a.parent=b},unlink:function(a,b){delete a.yc[b]},rmdir:function(a,b){var c=Nb(a,b),d;for(d in c.yc)throw new M(N.Fe);
delete a.yc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.yc)a.yc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new M(N.Wc);return a.link}},Ac:{read:function(a,b,c,d,e){var f=a.node.yc;if(e>=a.node.Fc)return 0;a=Math.min(a.node.Fc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.yc||a.yc.subarray)){if(f)return a.yc=b.subarray(c,c+d),a.Fc=d;if(0===a.Fc&&0===e)return a.yc=new Uint8Array(b.subarray(c,c+d)),a.Fc=d;if(e+d<=a.Fc)return a.yc.set(b.subarray(c,c+d),e),d}O.Ne(a,e+d);if(a.yc.subarray&&b.subarray)a.yc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.yc[e+f]=b[c+f];a.Fc=Math.max(a.Fc,e+d);return d},kd:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Fc);if(0>b)throw new M(N.Wc);return b},Ie:function(a,
b,c){O.Ne(a.node,b+c);a.node.Fc=Math.max(a.node.Fc,b+c)},bf:function(a,b,c,d,e,f,h){if(32768!==(a.node.mode&61440))throw new M(N.ke);c=a.node.yc;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.Fc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=w(d);if(!d)throw new M(N.sf);b.set(c,d)}else a=!1,d=c.byteOffset;return{Pi:d,wf:a}},de:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(N.ke);if(e&2)return 0;O.Ac.write(a,b,0,d,c,!1);return 0}}},P={Xd:!1,
Zf:function(){P.Xd=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.Qe={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Je:function(a){return Buffer.ad?Buffer.from(a):new Buffer(a)},Sc:function(a){assert(ha);return P.createNode(null,"/",P.Ue(a.ue.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new M(N.Wc);a=Lb(a,b,c);a.Bc=P.Bc;a.Ac=P.Ac;return a},Ue:function(a){try{var b=
fs.lstatSync(a);P.Xd&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}return b.mode},Tc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Sc.ue.root);b.reverse();return Bb.apply(null,b)},Df:function(a){a&=-2656257;var b=0,c;for(c in P.Qe)a&c&&(b|=P.Qe[c],a^=c);if(a)throw new M(N.Wc);return b},Bc:{gd:function(a){a=P.Tc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}P.Xd&&!b.od&&(b.od=4096);P.Xd&&!b.blocks&&
(b.blocks=(b.size+b.od-1)/b.od|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,od:b.od,blocks:b.blocks}},Xc:function(a,b){var c=P.Tc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},lookup:function(a,b){var c=Cb(P.Tc(a),b);c=P.Ue(c);return P.createNode(a,b,c)},Hd:function(a,b,c,d){a=P.createNode(a,
b,c,d);b=P.Tc(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new M(N[e.code]);}return a},rename:function(a,b,c){a=P.Tc(a);b=Cb(P.Tc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},unlink:function(a,b){a=Cb(P.Tc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}},rmdir:function(a,b){a=Cb(P.Tc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);
}},readdir:function(a){a=P.Tc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new M(N[b.code]);}},symlink:function(a,b,c){a=Cb(P.Tc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new M(N[d.code]);}},readlink:function(a){var b=P.Tc(a);try{return b=fs.readlinkSync(b),b=Ob.relative(Ob.resolve(a.Sc.ue.root),b)}catch(c){if(!c.code)throw c;throw new M(N[c.code]);}}},Ac:{open:function(a){var b=P.Tc(a.node);try{32768===(a.node.mode&61440)&&(a.Id=fs.openSync(b,P.Df(a.flags)))}catch(c){if(!c.code)throw c;
throw new M(N[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Id&&fs.closeSync(a.Id)}catch(b){if(!b.code)throw b;throw new M(N[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Id,P.Je(b.buffer),c,d,e)}catch(f){throw new M(N[f.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Id,P.Je(b.buffer),c,d,e)}catch(f){throw new M(N[f.code]);}},kd:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Id).size}catch(d){throw new M(N[d.code]);
}if(0>b)throw new M(N.Wc);return b}}},Pb=null,Qb={},Rb=[],Sb=1,Tb=null,Ub=!0,Vb={},M=null,Mb={};
function Wb(a,b){a=Db("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Re:!0,xe:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.xe)throw new M(40);a=xb(a.split("/").filter(function(a){return!!a}),!1);var e=Pb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Nb(e,a[d]);c=Cb(c,a[d]);e.Zd&&(!f||f&&b.Re)&&(e=e.Zd.root);if(!f||b.oe)for(f=0;40960===(e.mode&61440);)if(e=Xb(c),c=Db(zb(c),e),e=Wb(c,{xe:b.xe}).node,40<f++)throw new M(40);}return{path:c,node:e}}
function Yb(a){for(var b;;){if(a===a.parent)return a=a.Sc.cf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Tb.length}function $b(a){var b=Zb(a.parent.id,a.name);a.Of=Tb[b];Tb[b]=a}function Nb(a,b){var c;if(c=(c=ac(a,"x"))?c:a.Bc.lookup?0:13)throw new M(c,a);for(c=Tb[Zb(a.id,b)];c;c=c.Of){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Bc.lookup(a,b)}
function Lb(a,b,c,d){bc||(bc=function(a,b,c,d){a||(a=this);this.parent=a;this.Sc=a.Sc;this.Zd=null;this.id=Sb++;this.name=b;this.mode=c;this.Bc={};this.Ac={};this.rdev=d},bc.prototype={},Object.defineProperties(bc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new bc(a,b,c,d);$b(a);return a}
var cc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ac(a,b){if(Ub)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function ec(a,b){try{return Nb(a,b),17}catch(c){}return ac(a,"wx")}
function fc(a){var b=4096;for(a=a||0;a<=b;a++)if(!Rb[a])return a;throw new M(24);}function hc(a,b){ic||(ic=function(){},ic.prototype={},Object.defineProperties(ic.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new ic,d;for(d in a)c[d]=a[d];a=c;b=fc(b);a.fd=b;return Rb[b]=a}var Kb={open:function(a){a.Ac=Qb[a.node.rdev].Ac;a.Ac.open&&a.Ac.open(a)},kd:function(){throw new M(29);}};function Gb(a,b){Qb[a]={Ac:b}}
function jc(a,b){var c="/"===b,d=!b;if(c&&Pb)throw new M(16);if(!c&&!d){var e=Wb(b,{Re:!1});b=e.path;e=e.node;if(e.Zd)throw new M(16);if(16384!==(e.mode&61440))throw new M(20);}b={type:a,ue:{},cf:b,Nf:[]};a=a.Sc(b);a.Sc=b;b.root=a;c?Pb=a:e&&(e.Zd=b,e.Sc&&e.Sc.Nf.push(b))}function kc(a,b,c){var d=Wb(a,{parent:!0}).node;a=Ab(a);if(!a||"."===a||".."===a)throw new M(22);var e=ec(d,a);if(e)throw new M(e);if(!d.Bc.Hd)throw new M(1);return d.Bc.Hd(d,a,b,c)}function lc(a){kc(a,16895,0)}
function mc(a,b,c){"undefined"===typeof c&&(c=b,b=438);kc(a,b|8192,c)}function Va(a,b){if(!Db(a))throw new M(2);var c=Wb(b,{parent:!0}).node;if(!c)throw new M(2);b=Ab(b);var d=ec(c,b);if(d)throw new M(d);if(!c.Bc.symlink)throw new M(1);c.Bc.symlink(c,b,a)}function Xb(a){a=Wb(a).node;if(!a)throw new M(2);if(!a.Bc.readlink)throw new M(22);return Db(Yb(a.parent),a.Bc.readlink(a))}
function Wa(a,b,c,d){if(""===a)throw new M(2);if("string"===typeof b){var e=cc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=yb(a);try{f=Wb(a,{oe:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new M(17);}else f=kc(a,c,0),e=!0;if(!f)throw new M(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new M(20);if(!e&&(c=f?40960===(f.mode&61440)?
40:16384===(f.mode&61440)&&("r"!==dc(b)||b&512)?21:ac(f,dc(b)):2))throw new M(c);if(b&512){c=f;var h;"string"===typeof c?h=Wb(c,{oe:!0}).node:h=c;if(!h.Bc.Xc)throw new M(1);if(16384===(h.mode&61440))throw new M(21);if(32768!==(h.mode&61440))throw new M(22);if(c=ac(h,"w"))throw new M(c);h.Bc.Xc(h,{size:0,timestamp:Date.now()})}b&=-641;d=hc({node:f,path:Yb(f),flags:b,seekable:!0,position:0,Ac:f.Ac,eg:[],error:!1},d);d.Ac.open&&d.Ac.open(d);!m.logReadFiles||b&1||(nc||(nc={}),a in nc||(nc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Vb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Vb.onOpenFile(a,f))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function oc(a,b,c){if(null===a.fd)throw new M(9);if(!a.seekable||!a.Ac.kd)throw new M(29);if(0!=c&&1!=c&&2!=c)throw new M(22);a.position=a.Ac.kd(a,b,c);a.eg=[]}
function Ta(){M||(M=function(a,b){this.node=b;this.Wf=function(a){this.ed=a};this.Wf(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},M.prototype=Error(),M.prototype.constructor=M,[2].forEach(function(a){Mb[a]=new M(a);Mb[a].stack="<generic error, no stack>"}))}var Sa;function pc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ua(a,b,c){a=Cb("/dev",a);var d=pc(!!b,!!c);qc||(qc=64);var e=qc++<<8|0;Gb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,h=0;h<e;h++){try{var n=b()}catch(E){throw new M(5);}if(void 0===n&&0===f)throw new M(11);if(null===n||void 0===n)break;f++;c[d+h]=n}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(z){throw new M(5);}e&&(a.node.timestamp=Date.now());return f}});
mc(a,d,e)}
var qc,rc={},bc,ic,nc,N={tf:1,rf:2,fi:3,Xg:4,Ee:5,Ge:6,og:7,yh:8,qf:9,Dg:10,pf:11,pi:11,sf:12,nf:13,Qg:14,Kh:15,Bg:16,Pg:17,ri:18,ke:19,Mh:20,Zg:21,Wc:22,th:23,lh:24,sd:25,mi:26,Rg:27,Gh:28,ei:29,bi:30,mh:31,Vh:32,Mg:33,Zh:34,Ch:42,Ug:43,Eg:44,ah:45,bh:46,dh:47,jh:48,ni:49,wh:50,$g:51,Jg:35,zh:37,ug:52,xg:53,si:54,uh:55,yg:56,zg:57,Kg:35,Ag:59,Ih:60,xh:61,ji:62,Hh:63,Dh:64,Eh:65,ai:66,Ah:67,rg:68,gi:69,Fg:70,Wh:71,oh:72,Ng:73,wg:74,Qh:76,vg:77,$h:78,eh:79,fh:80,ih:81,hh:82,gh:83,Jh:38,Fe:39,ph:36,
kh:40,Rh:95,Uh:96,Ig:104,vh:105,sg:97,Yh:91,Oh:88,Fh:92,ci:108,Hg:111,pg:98,Gg:103,sh:101,qh:100,ki:110,Sg:112,Tg:113,Wg:115,tg:114,Lg:89,nh:90,Xh:93,di:94,qg:99,rh:102,Yg:106,Lh:107,li:109,oi:87,Og:122,hi:116,Ph:95,Bh:123,Vg:84,Sh:75,Cg:125,Nh:131,Th:130,ii:86},sc={},Q=0;function R(){Q+=4;return u[Q-4>>2]}function tc(){var a=Rb[R()];if(!a)throw new M(N.qf);return a}
function uc(a,b){g.xc.xd=a;g.xc.ge=b;if(g.xc.Oc)if(0==a)g.xc.qd=function(){var a=Math.max(0,g.xc.$f+b-vc())|0;setTimeout(g.xc.fe,a)},g.xc.method="timeout";else if(1==a)g.xc.qd=function(){g.requestAnimationFrame(g.xc.fe)},g.xc.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);fa?(void 0===m.setImmediates&&(m.setImmediates=
[]),m.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}g.xc.qd=function(){setImmediate(g.xc.fe)};g.xc.method="immediate"}}function vc(){q()}
function wc(a){var b=g.xc.nd;m.noExitRuntime=!0;assert(!g.xc.Oc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");g.xc.Oc=a;g.xc.nd=b;var c="undefined"!==typeof b?function(){m.dynCall_vi(a,b)}:function(){m.dynCall_v(a)};var d=g.xc.td;g.xc.fe=function(){if(!v)if(0<g.xc.ff.length){var a=Date.now(),b=g.xc.ff.shift();b.Oc(b.nd);if(g.xc.ye){var h=g.xc.ye,n=0==h%1?
h-1:Math.floor(h);g.xc.ye=b.yi?n:(8*h+(n+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");g.xc.fg();d<g.xc.td||setTimeout(g.xc.fe,0)}else d<g.xc.td||(g.xc.ne=g.xc.ne+1|0,1==g.xc.xd&&1<g.xc.ge&&0!=g.xc.ne%g.xc.ge?g.xc.qd():(0==g.xc.xd&&(g.xc.$f=vc()),"timeout"===g.xc.method&&m.Ud&&(r("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
g.xc.method=""),g.xc.Tf(c),d<g.xc.td||g.xc.qd()))}}
g={xc:{qd:null,method:"",td:0,Oc:null,nd:0,xd:0,ge:0,ne:0,ff:[],pause:function(){g.xc.qd=null;g.xc.td++},resume:function(){g.xc.td++;var a=g.xc.xd,b=g.xc.ge,c=g.xc.Oc;g.xc.Oc=null;wc(c);uc(a,b);g.xc.qd()},fg:function(){if(m.setStatus){var a=m.statusMessage||"Please wait...",b=g.xc.ye,c=g.xc.Ci;b?b<c?m.setStatus(a+" ("+(c-b)+"/"+c+")"):m.setStatus(a):m.setStatus("")}},Tf:function(a){if(!(v||m.preMainLoop&&!1===m.preMainLoop())){try{a()}catch(b){if(b instanceof la)return;b&&"object"===typeof b&&b.stack&&
r("exception thrown: "+[b,b.stack]);throw b;}m.postMainLoop&&m.postMainLoop()}}},Dd:!1,ve:!1,Mf:[],workers:[],se:function(){function a(){g.ve=document.pointerLockElement===m.canvas||document.mozPointerLockElement===m.canvas||document.webkitPointerLockElement===m.canvas||document.msPointerLockElement===m.canvas}m.preloadPlugins||(m.preloadPlugins=[]);if(!g.Kf){g.Kf=!0;try{g.Wd=!0}catch(c){g.Wd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}g.BlobBuilder="undefined"!=
typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:g.Wd?null:console.log("warning: no BlobBuilder");g.Od="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;m.ef||"undefined"!==typeof g.Od||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),m.ef=!0);m.preloadPlugins.push({canHandle:function(a){return!m.ef&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,
e,f){var c=null;if(g.Wd)try{c=new Blob([a],{type:g.pe(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:g.pe(b)}))}catch(x){ta("Blob constructor present but fails: "+x+"; falling back to blob builder")}c||(c=new g.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=g.Od.createObjectURL(c),t=new Image;t.onload=function(){assert(t.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=t.width;c.height=t.height;c.getContext("2d").drawImage(t,
0,0);m.preloadedImages[b]=c;g.Od.revokeObjectURL(d);e&&e(a)};t.onerror=function(){console.log("Image "+d+" could not be decoded");f&&f()};t.src=d}});m.preloadPlugins.push({canHandle:function(a){return!m.Mi&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,f){function c(c){t||(t=!0,m.preloadedAudios[b]=c,e&&e(a))}function d(){t||(t=!0,m.preloadedAudios[b]=new Audio,f&&f())}var t=!1;if(g.Wd){try{var x=new Blob([a],{type:g.pe(b)})}catch(J){return d()}x=g.Od.createObjectURL(x);var z=
new Audio;z.addEventListener("canplaythrough",function(){c(z)},!1);z.onerror=function(){if(!t){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,h=0;h<a.length;h++)for(e=e<<8|a[h],f+=8;6<=f;){var n=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");z.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(z)}};z.src=x;g.Uf(function(){c(z)},1E4)}else return d()}});var b=m.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),m.elementPointerLock&&b.addEventListener("click",function(a){!g.ve&&m.canvas.requestPointerLock&&(m.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&m.Ud&&a==m.canvas)return m.Ud;var e;if(b){var f={antialias:!1,alpha:!1,Xe:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof k&&
(e=k.createContext(a,f)))var n=k.getContext(e).bd}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof l,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),m.Ud=n,b&&k.Ye(e),m.$i=b,g.Mf.forEach(function(a){a()}),g.se());return n},zi:function(){},Te:!1,Yd:void 0,wd:void 0,requestFullscreen:function(a,b,c){function d(){g.Dd=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||
document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=g.exitFullscreen,g.Yd&&e.requestPointerLock(),g.Dd=!0,g.wd?g.Xf():g.Md(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),g.wd?g.Yf():g.Md(e));if(m.onFullScreen)m.onFullScreen(g.Dd);if(m.onFullscreen)m.onFullscreen(g.Dd)}g.Yd=a;g.wd=b;g.lf=c;"undefined"===typeof g.Yd&&(g.Yd=!0);"undefined"===typeof g.wd&&(g.wd=!1);"undefined"===typeof g.lf&&(g.lf=null);var e=m.canvas;g.Te||(g.Te=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?f.requestFullscreen({aj:c}):f.requestFullscreen()},gf:function(a,b,c){r("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");g.gf=function(a,b,c){return g.requestFullscreen(a,b,c)};return g.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!g.Dd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},ud:0,Pe:function(a){var b=
Date.now();if(0===g.ud)g.ud=b+1E3/60;else for(;b+2>=g.ud;)g.ud+=1E3/60;setTimeout(a,Math.max(g.ud-b,0))},requestAnimationFrame:function(a){"undefined"===typeof window?g.Pe(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||g.Pe),window.requestAnimationFrame(a))},Ti:function(a){return function(){if(!v)return a.apply(null,arguments)}},
zd:!0,Kd:[],Ni:function(){g.zd=!1},Si:function(){g.zd=!0;if(0<g.Kd.length){var a=g.Kd;g.Kd=[];a.forEach(function(a){a()})}},Ui:function(a){return g.requestAnimationFrame(function(){v||(g.zd?a():g.Kd.push(a))})},Uf:function(a,b){m.noExitRuntime=!0;return setTimeout(function(){v||(g.zd?a():g.Kd.push(a))},b)},Vi:function(a,b){m.noExitRuntime=!0;return setInterval(function(){v||g.zd&&a()},b)},pe:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",
mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Ef:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},Ff:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Fi:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=
100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},be:0,ce:0,$d:0,ae:0,touches:{},We:{},wi:function(a){if(g.ve)"mousemove"!=a.type&&"mozMovementX"in a?g.$d=g.ae=0:(g.$d=g.Ef(a),g.ae=g.Ff(a)),g.be+=g.$d,g.ce+=g.ae;else{var b=m.canvas.getBoundingClientRect(),c=m.canvas.width,d=m.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==
typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var h=a.Zi;if(void 0!==h)if(e=h.pageX-(e+b.left),f=h.pageY-(f+b.top),e*=c/b.width,f*=d/b.height,b={x:e,y:f},"touchstart"===a.type)g.We[h.identifier]=b,g.touches[h.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=g.touches[h.identifier])||(a=b),g.We[h.identifier]=a,g.touches[h.identifier]=b}else h=a.pageX-(e+b.left),a=a.pageY-(f+b.top),h*=c/b.width,a*=d/b.height,
g.$d=h-g.be,g.ae=a-g.ce,g.be=h,g.ce=a}},ui:function(a,b,c,d){var e=d?"":"al "+a;m.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&fb()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&eb()},Sf:[],De:function(){var a=m.canvas;g.Sf.forEach(function(b){b(a.width,a.height)})},Vf:function(a,b,c){g.Md(m.canvas,a,b);c||g.De()},dj:0,cj:0,Xf:function(){g.Md(m.canvas);g.De()},Yf:function(){g.Md(m.canvas);g.De()},Md:function(a,
b,c){b&&c?(a.gg=b,a.Hf=c):(b=a.gg,c=a.Hf);var d=b,e=c;m.forcedAspectRatio&&0<m.forcedAspectRatio&&(d/e<m.forcedAspectRatio?d=Math.round(e*m.forcedAspectRatio):e=Math.round(d/m.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}g.wd?(a.width!=
d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},bj:{},df:0,Gi:function(){var a=g.df;g.df++;return a}};
var xc={ig:!0,hg:!0},yc={jg:!0,lg:!0,mg:!0,kg:!0,ng:!0},S=0,U={},zc={},Ac={},V={},W=null,X={0:{id:0,Ld:0,Ec:null,frequency:0,jd:2,dd:1,length:0}},Y=[],Bc=1;function Cc(){return 0<Dc.length?Dc.pop():Bc++}var Dc=[];
function Ec(a){var b;if((1!==g.xc.xd||"visible"==document.visibilityState)&&4114===a.state){for(var c=Fc(a),d=a.Nc,e=a.Lc,f=a.Hc,h=0;h<a.Gc.length;h++){var n=a.Gc[h];d=n.Rd+n.yd;e=0;f+=n.He+1}b||(b=.1);b=c+b;for(c=0;d<b;){if(f>=a.Cc.length)if(a.hd)f%=a.Cc.length;else break;h=a.Cc[f%a.Cc.length];if(0===h.length){if(c++,c===a.Cc.length)break}else{n=a.context.Kc.createBufferSource();n.buffer=h.Ec;n.playbackRate.value=a.playbackRate;if(h.Ec.Qd||h.Ec.Pd)n.loopStart=h.Ec.Qd,n.loopEnd=h.Ec.Pd;if(4136===
a.type&&a.hd){var t=Number.POSITIVE_INFINITY;n.loop=!0;h.Ec.Qd&&(n.loopStart=h.Ec.Qd);h.Ec.Pd&&(n.loopEnd=h.Ec.Pd)}else t=(h.Ec.duration-e)/a.playbackRate;n.vf=e;n.yd=t;n.He=c;c=0;n.connect(a.gain);"undefined"!==typeof n.start?(d=Math.max(d,a.context.Kc.currentTime),n.start(d,e)):"undefined"!==typeof n.noteOn&&(d=Math.max(d,a.context.Kc.currentTime),n.noteOn(d));n.Rd=d;a.Gc.push(n);d+=t}e=0;f++}}}
function Fc(a){var b=a.context.Kc.currentTime;if(4114!==a.state)return b;isFinite(a.Nc)||(a.Nc=b-a.Lc/a.playbackRate,a.Lc=0);for(var c;a.Gc.length;){c=a.Gc[0];a.Hc+=c.He;c=c.Rd+c.yd;if(b<c)break;a.Gc.shift();a.Nc=c;a.Lc=0;a.Hc++}if(a.Hc>=a.Cc.length&&!a.hd)Gc(a,4116);else if(4136===a.type&&a.hd)if(c=a.Cc[0],0===c.length)a.Lc=0;else{var d=(b-a.Nc)*a.playbackRate,e=c.Ec.Qd||0,f=c.Ec.Pd||c.Ec.duration;f<=e&&(f=c.Ec.duration);d<f?a.Lc=d:a.Lc=e+(d-e)%(f-e)}else if(a.Gc[0])a.Lc=(b-a.Gc[0].Rd)*a.playbackRate;
else for(4136!==a.type&&a.hd&&(c=Hc(a)/a.playbackRate,0<c&&(a.Nc+=Math.floor((b-a.Nc)/c)*c)),d=0;d<a.Cc.length;d++){if(a.Hc>=a.Cc.length)if(a.hd)a.Hc%=a.Cc.length;else{Gc(a,4116);break}c=a.Cc[a.Hc];if(0<c.length){c=a.Nc+c.Ec.duration/a.playbackRate;if(b<c){a.Lc=(b-a.Nc)*a.playbackRate;break}a.Nc=c}a.Lc=0;a.Hc++}return b}function Ic(a){for(var b=0;b<a.Gc.length;b++)a.Gc[b].stop();a.Gc.length=0}
function Gc(a,b){if(4114===b){if(4114===a.state||4116==a.state)a.Hc=0,a.Lc=0;Ic(a);a.state=4114;a.Nc=Number.NEGATIVE_INFINITY;Ec(a)}else 4115===b?4114===a.state&&(Fc(a),Ic(a),a.state=4115):4116===b?4113!==a.state&&(a.state=4116,a.Hc=a.Cc.length,a.Nc=Number.NEGATIVE_INFINITY,a.Lc=0,Ic(a)):4113===b&&4113!==a.state&&(a.state=4113,a.Hc=0,a.Nc=Number.NEGATIVE_INFINITY,a.Lc=0,Ic(a))}
function Jc(a){if(4144!==a.type){for(var b=X[0],c=0;c<a.Cc.length;c++)if(0!==a.Cc[c].id){b=a.Cc[c];break}1===a.Ae||2===a.Ae&&1===b.dd?a.Dc||(a.Dc=a.context.Kc.createPanner(),Kc(a),Lc(a),a.Dc.connect(a.context.gain),a.gain.disconnect(),a.gain.connect(a.Dc)):a.Dc&&(a.Dc.disconnect(),a.gain.disconnect(),a.gain.connect(a.context.gain),a.Dc=null)}}function Mc(a){for(var b in a.Uc)Kc(a.Uc[b])}
function Kc(a){var b=a.Dc;if(b)switch(b.refDistance=a.refDistance,b.maxDistance=a.maxDistance,b.rolloffFactor=a.rolloffFactor,b.panningModel=a.context.re?"HRTF":"equalpower",a.context.hf?a.distanceModel:a.context.distanceModel){case 0:b.distanceModel="inverse";b.refDistance=3.40282E38;break;case 53249:case 53250:b.distanceModel="inverse";break;case 53251:case 53252:b.distanceModel="linear";break;case 53253:case 53254:b.distanceModel="exponential"}}
function Nc(){var a=W,b=a.Kc.listener;b.positionX?(b.positionX.value=a.listener.position[0],b.positionY.value=a.listener.position[1],b.positionZ.value=a.listener.position[2]):b.setPosition(a.listener.position[0],a.listener.position[1],a.listener.position[2]);b.forwardX?(b.forwardX.value=a.listener.direction[0],b.forwardY.value=a.listener.direction[1],b.forwardZ.value=a.listener.direction[2],b.upX.value=a.listener.Vc[0],b.upY.value=a.listener.Vc[1],b.upZ.value=a.listener.Vc[2]):b.setOrientation(a.listener.direction[0],
a.listener.direction[1],a.listener.direction[2],a.listener.Vc[0],a.listener.Vc[1],a.listener.Vc[2]);for(var c in a.Uc)Lc(a.Uc[c])}
function Lc(a){if(a.Dc){var b=a.Dc,c=a.position[0],d=a.position[1],e=a.position[2],f=a.direction[0],h=a.direction[1],n=a.direction[2],t=a.context.listener,x=t.position[0],z=t.position[1],J=t.position[2];if(a.relative){var E=-t.direction[0],H=-t.direction[1],C=-t.direction[2],K=t.Vc[0],oa=t.Vc[1],pa=t.Vc[2],T=function(a,b,c){a=Math.sqrt(a*a+b*b+c*c);return a<Number.EPSILON?0:1/a},G=T(E,H,C);E*=G;H*=G;C*=G;G=T(K,oa,pa);K*=G;oa*=G;pa*=G;var Aa=oa*C-pa*H,Ba=pa*E-K*C,Ca=K*H-oa*E;G=T(Aa,Ba,Ca);Aa*=G;Ba*=
G;Ca*=G;K=H*Ca-C*Ba;oa=C*Aa-E*Ca;pa=E*Ba-H*Aa;T=f;G=h;var qa=n;f=T*Aa+G*K+qa*E;h=T*Ba+G*oa+qa*H;n=T*Ca+G*pa+qa*C;T=c;G=d;qa=e;c=T*Aa+G*K+qa*E+x;d=T*Ba+G*oa+qa*H+z;e=T*Ca+G*pa+qa*C+J}b.positionX?(b.positionX.value=c,b.positionY.value=d,b.positionZ.value=e):b.setPosition(c,d,e);b.orientationX?(b.orientationX.value=f,b.orientationY.value=h,b.orientationZ.value=n):b.setOrientation(f,h,n);b=a.Bd;f=a.Rc[0];h=a.Rc[1];n=a.Rc[2];E=t.Rc[0];H=t.Rc[1];t=t.Rc[2];c===x&&d===z&&e===J||f===E&&h===H&&n===t?a.Bd=1:
(C=a.context.speedOfSound,K=a.context.dopplerFactor,c=x-c,d=z-d,e=J-e,J=Math.sqrt(c*c+d*d+e*e),a.Bd=(C-K*Math.min((c*E+d*H+e*t)/J,C/K))/(C-K*Math.min((c*f+d*h+e*n)/J,C/K)));a.Bd!==b&&Oc(a)}}function Oc(a){if(4114===a.state){Fc(a);for(var b=1;b<a.Gc.length;b++)a.Gc[b].stop();1<a.Gc.length&&(a.Gc.length=1);if(b=a.Gc[0])b.yd=4136===a.type&&a.hd?Number.POSITIVE_INFINITY:(b.buffer.duration-b.vf)/a.playbackRate,b.playbackRate.value=a.playbackRate,Ec(a)}}
function Hc(a){for(var b=0,c=0;c<a.Cc.length;c++){var d=a.Cc[c].Ec;b+=d?d.duration:0}return b}function Pc(a,b){var c=4114==a.state;c&&Gc(a,4113);if(null!==a.Cc[a.Hc].Ec){for(a.Hc=0;b>a.Cc[a.Hc].Ec.duration;)b-=a.Cc[a.Hc].vi.duration,a.Hc++;a.Lc=b}c&&Gc(a,4114)}
function Qc(a,b){if(W)if(null===b)W.zc=40962;else{var c=W.listener;switch(a){case 4100:if(!Number.isFinite(b[0])||!Number.isFinite(b[1])||!Number.isFinite(b[2])){W.zc=40963;break}c.position[0]=b[0];c.position[1]=b[1];c.position[2]=b[2];Nc();break;case 4102:if(!Number.isFinite(b[0])||!Number.isFinite(b[1])||!Number.isFinite(b[2])){W.zc=40963;break}c.Rc[0]=b[0];c.Rc[1]=b[1];c.Rc[2]=b[2];Nc();break;case 4106:if(!Number.isFinite(b)||0>b){W.zc=40963;break}W.gain.gain.value=b;break;case 4111:if(!(Number.isFinite(b[0])&&
Number.isFinite(b[1])&&Number.isFinite(b[2])&&Number.isFinite(b[3])&&Number.isFinite(b[4])&&Number.isFinite(b[5]))){W.zc=40963;break}c.direction[0]=b[0];c.direction[1]=b[1];c.direction[2]=b[2];c.Vc[0]=b[3];c.Vc[1]=b[4];c.Vc[2]=b[5];Nc();break;default:W.zc=40962}}}
function Rc(a,b,c){if(W)if(a=W.Uc[a])if(null===c)W.zc=40962;else switch(b){case 514:1===c?(a.relative=!0,Lc(a)):0===c?(a.relative=!1,Lc(a)):W.zc=40963;break;case 4097:if(!Number.isFinite(c)){W.zc=40963;break}a.coneInnerAngle=c;a.Dc&&(a.Dc.coneInnerAngle=c%360);break;case 4098:if(!Number.isFinite(c)){W.zc=40963;break}a.coneOuterAngle=c;a.Dc&&(a.Dc.coneOuterAngle=c%360);break;case 4099:if(!Number.isFinite(c)||0>=c){W.zc=40963;break}if(a.pitch===c)break;a.pitch=c;Oc(a);break;case 4100:if(!Number.isFinite(c[0])||
!Number.isFinite(c[1])||!Number.isFinite(c[2])){W.zc=40963;break}a.position[0]=c[0];a.position[1]=c[1];a.position[2]=c[2];Lc(a);break;case 4101:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){W.zc=40963;break}a.direction[0]=c[0];a.direction[1]=c[1];a.direction[2]=c[2];Lc(a);break;case 4102:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){W.zc=40963;break}a.Rc[0]=c[0];a.Rc[1]=c[1];a.Rc[2]=c[2];Lc(a);break;case 4103:if(1===c)a.hd=!0,Fc(a),4136===
a.type&&0<a.Gc.length&&(c=a.Gc[0],c.loop=!0,c.yd=Number.POSITIVE_INFINITY);else if(0===c){a.hd=!1;var d=Fc(a);4136===a.type&&0<a.Gc.length&&(c=a.Gc[0],c.loop=!1,c.yd=a.Cc[0].Ec.duration/a.playbackRate,c.Rd=d-a.Lc/a.playbackRate)}else W.zc=40963;break;case 4105:if(4114===a.state||4115===a.state){W.zc=40964;break}if(0===c){for(d in a.Cc)a.Cc[d].Ld--;a.Cc.length=1;a.Cc[0]=X[0];a.Hc=0;a.type=4144}else{var e=X[c];if(!e){W.zc=40963;break}for(d in a.Cc)a.Cc[d].Ld--;a.Cc.length=0;e.Ld++;a.Cc=[e];a.Hc=0;a.type=
4136}Jc(a);Ec(a);break;case 4106:if(!Number.isFinite(c)||0>c){W.zc=40963;break}a.gain.gain.value=c;break;case 4109:if(!Number.isFinite(c)||0>c||c>Math.min(a.Ze,1)){W.zc=40963;break}a.$e=c;break;case 4110:if(!Number.isFinite(c)||c<Math.max(0,a.$e)||1<c){W.zc=40963;break}a.Ze=c;break;case 4128:if(!Number.isFinite(c)||0>c){W.zc=40963;break}a.refDistance=c;a.Dc&&(a.Dc.refDistance=c);break;case 4129:if(!Number.isFinite(c)||0>c){W.zc=40963;break}a.rolloffFactor=c;a.Dc&&(a.Dc.rolloffFactor=c);break;case 4130:if(!Number.isFinite(c)||
0>c||1<c){W.zc=40963;break}a.coneOuterGain=c;a.Dc&&(a.Dc.coneOuterGain=c);break;case 4131:if(!Number.isFinite(c)||0>c){W.zc=40963;break}a.maxDistance=c;a.Dc&&(a.Dc.maxDistance=c);break;case 4132:if(0>c||c>Hc(a)){W.zc=40963;break}Pc(a,c);break;case 4133:d=Hc(a);if(0<d){for(var f in a.Cc)if(0!==f){e=a.Cc[f].frequency;break}c/=e}if(0>c||c>d){W.zc=40963;break}Pc(a,c);break;case 4134:d=Hc(a);if(0<d){for(f in a.Cc)if(0!==f){e=a.Cc[f];var h=e.frequency*e.jd*e.dd;break}c/=h}if(0>c||c>d){W.zc=40963;break}Pc(a,
c);break;case 4628:if(0!==c&&1!==c&&2!==c){W.zc=40963;break}a.Ae=c;Jc(a);break;case 8201:case 8202:case 8203:W.zc=40964;break;case 53248:switch(c){case 0:case 53249:case 53250:case 53251:case 53252:case 53253:case 53254:a.distanceModel=c;W.hf&&Mc(W);break;default:W.zc=40963}break;default:W.zc=40962}else W.zc=40961}var Sc={};function Tc(a){if(0===a)return S=40961,null;a=Sc[a];return!a||a.Ki?(S=40961,null):a}
function Uc(a,b,c){switch(b){case 514:case 4097:case 4098:case 4103:case 4105:case 4128:case 4129:case 4131:case 4132:case 4133:case 4134:case 4628:case 8201:case 8202:case 53248:Rc(a,b,c);break;default:Rc(a,b,null)}}var Vc=0,Wc=0,Xc=0,Yc=0,Zc=null,$c=null,ad=!1;function bd(){for(var a=Z.length-1;0<=a;--a)cd(a);Z=[];dd=[]}var dd=[];function ed(){if(fd&&gd.Ad)for(var a=0;a<dd.length;++a){var b=dd[a];dd.splice(a,1);--a;b.Wi.apply(this,b.ti)}}var fd=0,gd=null,Z=[];
function hd(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function cd(a){var b=Z[a];b.target.removeEventListener(b.pd,b.Cf,b.Nd);Z.splice(a,1)}function id(a){function b(b){++fd;gd=a;ed();a.Vd(b);ed();--fd}if(a.Td)a.Cf=b,a.target.addEventListener(a.pd,b,a.Nd),Z.push(a),ad||(Oa.push(bd),ad=!0);else for(var c=0;c<Z.length;++c)Z[c].target==a.target&&Z[c].pd==a.pd&&cd(c--)}
var jd={},kd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function ld(a){try{if(!a)return window;"number"===typeof a&&(a=kd[a]||B(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?m.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}
function md(a){"number"===typeof a&&(a=B(a));return a&&"#canvas"!==a?"undefined"!==typeof k&&k.ee[a]?k.ee[a]:ld(a):"undefined"!==typeof k&&k.ee.canvas?k.ee.canvas:m.canvas}function sa(){return y.length}function nd(){q("OOM")}
function od(a,b,c,d,e,f){Vc||(Vc=w(164));a={target:ld(a),Ad:hd()?!1:!0,pd:f,Td:d,Vd:function(a){a=a||window.event;var c=Vc;D(a.key?a.key:"",A,c+0,32);D(a.code?a.code:"",A,c+32,32);u[c+64>>2]=a.location;u[c+68>>2]=a.ctrlKey;u[c+72>>2]=a.shiftKey;u[c+76>>2]=a.altKey;u[c+80>>2]=a.metaKey;u[c+84>>2]=a.repeat;D(a.locale?a.locale:"",A,c+88,32);D(a.char?a.char:"",A,c+120,32);u[c+152>>2]=a.charCode;u[c+156>>2]=a.keyCode;u[c+160>>2]=a.which;pd(d,e,c,b)&&a.preventDefault()},Nd:c};id(a)}
function qd(a,b,c){I[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();u[a+8>>2]=b.screenX;u[a+12>>2]=b.screenY;u[a+16>>2]=b.clientX;u[a+20>>2]=b.clientY;u[a+24>>2]=b.ctrlKey;u[a+28>>2]=b.shiftKey;u[a+32>>2]=b.altKey;u[a+36>>2]=b.metaKey;Ga[a+40>>1]=b.button;Ga[a+42>>1]=b.buttons;u[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Zc;u[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-$c;if(m.canvas){var d=m.canvas.getBoundingClientRect();
u[a+60>>2]=b.clientX-d.left;u[a+64>>2]=b.clientY-d.top}else u[a+60>>2]=0,u[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},u[a+52>>2]=b.clientX-d.left,u[a+56>>2]=b.clientY-d.top):(u[a+52>>2]=0,u[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Zc=b.screenX,$c=b.screenY)}
function rd(a,b,c,d,e,f){Wc||(Wc=w(72));a=ld(a);c={target:a,Ad:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,pd:f,Td:d,Vd:function(c){c=c||window.event;qd(Wc,c,a);pd(d,e,Wc,b)&&c.preventDefault()},Nd:c};hd()&&"mousedown"==f&&(c.Ad=!1);id(c)}
function sd(a,b,c,d){Yc||(Yc=w(36));a=ld(a);id({target:a,Ad:!1,pd:"resize",Td:d,Vd:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],h=Yc;u[h>>2]=c.detail;u[h+4>>2]=document.body.clientWidth;
u[h+8>>2]=document.body.clientHeight;u[h+12>>2]=window.innerWidth;u[h+16>>2]=window.innerHeight;u[h+20>>2]=window.outerWidth;u[h+24>>2]=window.outerHeight;u[h+28>>2]=e[0];u[h+32>>2]=e[1];pd(d,10,h,b)&&c.preventDefault()}},Nd:c})}
function td(a,b,c,d,e){function f(c){c=c||window.event;qd(Xc,c,a);I[Xc+72>>3]=c.wheelDeltaX||0;I[Xc+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);I[Xc+88>>3]=0;u[Xc+96>>2]=0;pd(d,9,Xc,b)&&c.preventDefault()}function h(c){c=c||window.event;var e=Xc;qd(e,c,a);I[e+72>>3]=c.deltaX;I[e+80>>3]=c.deltaY;I[e+88>>3]=c.deltaZ;u[e+96>>2]=c.deltaMode;pd(d,9,e,b)&&c.preventDefault()}Xc||(Xc=w(104));id({target:a,Ad:!0,pd:e,Td:d,Vd:"wheel"==e?h:f,Nd:c})}
function ud(){if(!k.Qc||!k.Qc.bd)return-3;if(!k.Qc.bd.yf)return-1;if(!k.Qc.attributes.Oe)return-3;k.Qc.bd.yf();return 0}
k={Le:1,Ed:0,Sd:[],Ji:{},Pc:[],Se:[],ze:[],Ce:[],Jc:[],Yc:[],je:[],Zc:{},Qc:null,ee:{},Xi:[],Jd:{},Be:{},kf:4,se:function(){k.af=new Float32Array(k.cd);for(var a=0;a<k.cd;a++)k.ld[a]=k.af.subarray(0,a+1)},Ic:function(a){k.Ed||(k.Ed=a)},Cd:function(a){for(var b=k.Le++,c=a.length;c<b;c++)a[c]=null;return b},cd:256,af:null,ld:[0],Gf:function(a,b,c,d){a="";for(var e=0;e<b;++e){var f=d?u[d+4*e>>2]:-1;a+=B(u[c+4*e>>2],0>f?void 0:f)}return a},createContext:function(a,b){return(a=a.getContext("webgl",b)||
a.getContext("experimental-webgl",b))&&k.Qf(a,b)},Qf:function(a,b){var c=w(8),d={handle:c,attributes:b,version:b.Xe,bd:a};a.canvas&&(a.canvas.uf=d);k.Zc[c]=d;("undefined"===typeof b.Me||b.Me)&&k.If(d);return c},Ye:function(a){k.Qc=k.Zc[a];m.Ud=l=k.Qc&&k.Qc.bd;return!(a&&!l)},getContext:function(a){return k.Zc[a]},Bf:function(a){k.Qc===k.Zc[a]&&(k.Qc=null);if("object"===typeof jd)for(var b=k.Zc[a].bd.canvas,c=0;c<Z.length;++c)Z[c].target!=b||cd(c--);k.Zc[a]&&k.Zc[a].bd.canvas&&(k.Zc[a].bd.canvas.uf=
void 0);vd(k.Zc[a]);k.Zc[a]=null},If:function(a){a||(a=k.Qc);if(!a.Jf){a.Jf=!0;var b=a.bd;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.Bi=b.getExtension("EXT_disjoint_timer_query");var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}},Pf:function(a){var b=k.Pc[a];a=k.Jd[a]={Jc:{},te:0,Fd:-1,Gd:-1};for(var c=a.Jc,d=l.getProgramParameter(b,35718),e=0;e<d;++e){var f=l.getActiveUniform(b,e),h=f.name;a.te=Math.max(a.te,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=l.getUniformLocation(b,h);if(n){var t=k.Cd(k.Jc);c[h]=[f.size,t];k.Jc[t]=n;for(var x=1;x<f.size;++x)n=l.getUniformLocation(b,
h+"["+x+"]"),t=k.Cd(k.Jc),k.Jc[t]=n}}}};var wd=["default","low-power","high-performance"];function xd(a){return k.Ye(a)?0:-5}m._emscripten_webgl_make_context_current=xd;function yd(a){if(0===a)return 0;a=B(a);if(!L.hasOwnProperty(a))return 0;yd.ad&&vd(yd.ad);a=L[a];var b=Da(a)+1,c=w(b);c&&D(a,y,c,b);yd.ad=c;return yd.ad}var zd=[];function Ad(a,b,c,d){for(var e=0;e<a;e++){var f=l[c](),h=f&&k.Cd(d);f?(f.name=h,d[h]=f):k.Ic(1282);u[b+4*e>>2]=h}}
function Bd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&k.Ic(1280);return;case 36345:d=0;break;case 34466:var e=l.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=l.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":k.Ic(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:k.Ic(1280);return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":u[b+4*a>>2]=e[a];break;case "Float":F[b+4*a>>2]=e[a];break;case "Boolean":y[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=e.name|0}catch(f){k.Ic(1280);r("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:k.Ic(1280);return}switch(c){case "Integer64":aa=
[d>>>0,(ba=d,1<=+Ya(ba)?0<ba?(ab(+$a(ba/4294967296),4294967295)|0)>>>0:~~+Za((ba-+(~~ba>>>0))/4294967296)>>>0:0)];u[b>>2]=aa[0];u[b+4>>2]=aa[1];break;case "Integer":u[b>>2]=d;break;case "Float":F[b>>2]=d;break;case "Boolean":y[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else k.Ic(1281)}function Cd(a){var b=Da(a)+1,c=w(b);D(a,A,c,b);return c}var Dd={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Ed={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Fd(a,b,c,d,e){if(b=Dd[b]*Ed[a]){var f=k.kf;c=e+d*(c*b+f-1&-f);switch(a){case 5121:return A.subarray(e,c);case 5126:return F.subarray(e>>2,c>>2);case 5125:case 34042:return Ia.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return Ha.subarray(e>>1,c>>1);default:k.Ic(1280)}}else k.Ic(1280)}function Gd(){Gd.ad||(Gd.ad=[]);Gd.ad.push(Hd());return Gd.ad.length-1}function Id(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Jd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Kd=[31,29,31,30,31,30,31,31,30,31,30,31],Ld=[31,28,31,30,31,30,31,31,30,31,30,31];function Md(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Id(a.getFullYear())?Kd:Ld)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Nd(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function t(a){a=Md(new Date(a.Mc+1900,0,1),a.ie);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=h(n(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var x=u[d+40>>2];d={cg:u[d>>2],bg:u[d+4>>2],he:u[d+8>>2],rd:u[d+12>>2],md:u[d+16>>2],Mc:u[d+20>>2],jf:u[d+24>>2],ie:u[d+28>>2],Yi:u[d+32>>2],ag:u[d+36>>2],
dg:x?B(x):""};c=B(c);x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var z in x)c=c.replace(new RegExp(z,"g"),x[z]);var J="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),E="January February March April May June July August September October November December".split(" ");x={"%a":function(a){return J[a.jf].substring(0,3)},"%A":function(a){return J[a.jf]},"%b":function(a){return E[a.md].substring(0,
3)},"%B":function(a){return E[a.md]},"%C":function(a){return f((a.Mc+1900)/100|0,2)},"%d":function(a){return f(a.rd,2)},"%e":function(a){return e(a.rd,2," ")},"%g":function(a){return t(a).toString().substring(2)},"%G":function(a){return t(a)},"%H":function(a){return f(a.he,2)},"%I":function(a){a=a.he;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.rd+Jd(Id(a.Mc+1900)?Kd:Ld,a.md-1),3)},"%m":function(a){return f(a.md+1,2)},"%M":function(a){return f(a.bg,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.he&&12>a.he?"AM":"PM"},"%S":function(a){return f(a.cg,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Mc+1900,a.md+1,a.rd,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Mc+1900,0,1),c=0===b.getDay()?b:Md(b,7-b.getDay());a=new Date(a.Mc+1900,a.md,a.rd);return 0>h(c,a)?f(Math.ceil((31-c.getDate()+(Jd(Id(a.getFullYear())?Kd:Ld,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.Mc+1900,0,4)),c=n(new Date(a.Mc+
1901,0,4)),d=Md(new Date(a.Mc+1900,0,1),a.ie);return 0>h(d,b)?"53":0>=h(c,d)?"01":f(Math.ceil((b.getFullYear()<a.Mc+1900?a.ie+32-b.getDate():a.ie+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Mc+1900,a.md+1,a.rd,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Mc,0,1),c=1===b.getDay()?b:Md(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Mc+1900,a.md,a.rd);return 0>h(c,a)?f(Math.ceil((31-c.getDate()+(Jd(Id(a.getFullYear())?Kd:Ld,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":
"00"},"%y":function(a){return(a.Mc+1900).toString().substring(2)},"%Y":function(a){return a.Mc+1900},"%z":function(a){a=a.ag;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.dg},"%%":function(){return"%"}};for(z in x)0<=c.indexOf(z)&&(c=c.replace(new RegExp(z,"g"),x[z](d)));z=mb(c,!1);if(z.length>b)return 0;y.set(z,a);return z.length-1}Ta();Tb=Array(4096);jc(O,"/");lc("/tmp");lc("/home");lc("/home/web_user");
(function(){lc("/dev");Gb(259,{read:function(){return 0},write:function(a,b,c,h){return h}});mc("/dev/null",259);Fb(1280,Ib);Fb(1536,Jb);mc("/dev/tty",1280);mc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});Ua("random",b);Ua("urandom",b);lc("/dev/shm");
lc("/dev/shm/tmp")})();lc("/proc");lc("/proc/self");lc("/proc/self/fd");jc({Sc:function(){var a=Lb("/proc/self","fd",16895,73);a.Bc={lookup:function(a,c){var b=Rb[+c];if(!b)throw new M(9);a={parent:null,Sc:{cf:"fake"},Bc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(ha){var fs=require("fs"),Ob=require("path");P.Zf()}
m.requestFullScreen=function(a,b,c){r("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");m.requestFullScreen=m.requestFullscreen;g.gf(a,b,c)};m.requestFullscreen=function(a,b,c){g.requestFullscreen(a,b,c)};m.requestAnimationFrame=function(a){g.requestAnimationFrame(a)};m.setCanvasSize=function(a,b,c){g.Vf(a,b,c)};m.pauseMainLoop=function(){g.xc.pause()};m.resumeMainLoop=function(){g.xc.resume()};m.getUserMedia=function(){g.getUserMedia()};
m.createContext=function(a,b,c,d){return g.createContext(a,b,c,d)};ha?vc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?vc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?vc=function(){return performance.now()}:vc=Date.now;k.se();for(var Od=0;32>Od;Od++)zd.push(Array(Od));function mb(a,b){var c=Array(Da(a)+1);a=D(a,c,0,c.length);b&&(c.length=a);return c}
var Sd=m.asm({},{c:q,Kb:vb,e:function(a){return w(a)},Pa:function(){v=!0;throw"Pure virtual function called!";},d:function(a){"uncaught_exception"in Pd?Pd.mf++:Pd.mf=1;throw a;},za:function(){return!!Pd.mf},k:function(){},ia:function(){wb(1);return-1},t:wb,s:function(a,b){Q=b;try{var c=tc();R();var d=R(),e=R(),f=R();oc(c,d,f);u[e>>2]=c.position;c.qe&&0===d&&0===f&&(c.qe=null);return 0}catch(h){return"undefined"!==typeof rc&&h instanceof M||q(h),-h.ed}},Jb:function(a,b){Q=b;try{var c=tc(),d=R();a:{var e=
R();for(b=a=0;b<e;b++){var f=u[d+(8*b+4)>>2],h=c,n=u[d+8*b>>2],t=f,x=void 0,z=y;if(0>t||0>x)throw new M(22);if(null===h.fd)throw new M(9);if(1===(h.flags&2097155))throw new M(9);if(16384===(h.node.mode&61440))throw new M(21);if(!h.Ac.read)throw new M(22);var J="undefined"!==typeof x;if(!J)x=h.position;else if(!h.seekable)throw new M(29);var E=h.Ac.read(h,z,n,t,x);J||(h.position+=E);var H=E;if(0>H){var C=-1;break a}a+=H;if(H<f)break}C=a}return C}catch(K){return"undefined"!==typeof rc&&K instanceof
M||q(K),-K.ed}},G:function(a,b){Q=b;try{var c=tc(),d=R();a:{var e=R();for(b=a=0;b<e;b++){var f=c,h=u[d+8*b>>2],n=u[d+(8*b+4)>>2],t=void 0,x=y;if(0>n||0>t)throw new M(22);if(null===f.fd)throw new M(9);if(0===(f.flags&2097155))throw new M(9);if(16384===(f.node.mode&61440))throw new M(21);if(!f.Ac.write)throw new M(22);f.flags&1024&&oc(f,0,2);var z="undefined"!==typeof t;if(!z)t=f.position;else if(!f.seekable)throw new M(29);var J=f.Ac.write(f,x,h,n,t,void 0);z||(f.position+=J);try{if(f.path&&Vb.onWriteToFile)Vb.onWriteToFile(f.path)}catch(C){console.log("FS.trackingDelegate['onWriteToFile']('"+
f.path+"') threw an exception: "+C.message)}var E=J;if(0>E){var H=-1;break a}a+=E}H=a}return H}catch(C){return"undefined"!==typeof rc&&C instanceof M||q(C),-C.ed}},m:function(a,b){Q=b;try{var c=tc();switch(R()){case 0:var d=R();return 0>d?-N.Wc:Wa(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=R(),c.flags|=d,0;case 12:return d=R(),Ga[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-N.Wc;case 9:return wb(N.Wc),-1;default:return-N.Wc}}catch(e){return"undefined"!==
typeof rc&&e instanceof M||q(e),-e.ed}},jb:function(a,b){Q=b;try{var c=B(R());var d=R();if(d&-8)var e=-N.Wc;else{var f=Wb(c,{oe:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&ac(f,a)?-N.nf:0}return e}catch(h){return"undefined"!==typeof rc&&h instanceof M||q(h),-h.ed}},ab:function(a,b){Q=b;try{var c=B(R()),d=R(),e=R();return Wa(c,d,e).fd}catch(f){return"undefined"!==typeof rc&&f instanceof M||q(f),-f.ed}},D:function(a,b){Q=b;try{var c=tc(),d=R();switch(d){case 21509:case 21505:return c.tty?
0:-N.sd;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-N.sd;case 21519:if(!c.tty)return-N.sd;var e=R();return u[e>>2]=0;case 21520:return c.tty?-N.Wc:-N.sd;case 21531:a=e=R();if(!c.Ac.Lf)throw new M(25);return c.Ac.Lf(c,d,a);case 21523:return c.tty?0:-N.sd;case 21524:return c.tty?0:-N.sd;default:q("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof rc&&f instanceof M||q(f),-f.ed}},C:function(a,b){Q=b;try{var c=tc();if(null===c.fd)throw new M(9);c.qe&&(c.qe=
null);try{c.Ac.close&&c.Ac.close(c)}catch(d){throw d;}finally{Rb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof rc&&d instanceof M||q(d),-d.ed}},Xa:function(a,b){Q=b;try{var c=R(),d=R(),e=sc[c];if(!e)return 0;if(d===e.Hi){var f=Rb[e.fd],h=e.flags,n=new Uint8Array(A.subarray(c,c+d));f&&f.Ac.de&&f.Ac.de(f,n,0,d,h);sc[c]=null;e.wf&&vd(e.Ii)}return 0}catch(t){return"undefined"!==typeof rc&&t instanceof M||q(t),-t.ed}},j:function(){},b:function(){m.abort()},Wa:function(a,b,c,d,e){if(W)if(a=
X[a])if(0>=e)W.zc=40963;else{var f=null;try{switch(b){case 4352:if(0<d){f=W.Kc.createBuffer(1,d,e);for(var h=f.getChannelData(0),n=0;n<d;++n)h[n]=.0078125*A[c++]-1}a.jd=1;a.dd=1;a.length=d;break;case 4353:if(0<d)for(f=W.Kc.createBuffer(1,d>>1,e),h=f.getChannelData(0),c>>=1,n=0;n<d>>1;++n)h[n]=3.0517578125E-5*Ga[c++];a.jd=2;a.dd=1;a.length=d>>1;break;case 4354:if(0<d){f=W.Kc.createBuffer(2,d>>1,e);h=f.getChannelData(0);var t=f.getChannelData(1);for(n=0;n<d>>1;++n)h[n]=.0078125*A[c++]-1,t[n]=.0078125*
A[c++]-1}a.jd=1;a.dd=2;a.length=d>>1;break;case 4355:if(0<d)for(f=W.Kc.createBuffer(2,d>>2,e),h=f.getChannelData(0),t=f.getChannelData(1),c>>=1,n=0;n<d>>2;++n)h[n]=3.0517578125E-5*Ga[c++],t[n]=3.0517578125E-5*Ga[c++];a.jd=2;a.dd=2;a.length=d>>2;break;case 65552:if(0<d)for(f=W.Kc.createBuffer(1,d>>2,e),h=f.getChannelData(0),c>>=2,n=0;n<d>>2;++n)h[n]=F[c++];a.jd=4;a.dd=1;a.length=d>>2;break;case 65553:if(0<d)for(f=W.Kc.createBuffer(2,d>>3,e),h=f.getChannelData(0),t=f.getChannelData(1),c>>=2,n=0;n<d>>
3;++n)h[n]=F[c++],t[n]=F[c++];a.jd=4;a.dd=2;a.length=d>>3;break;default:W.zc=40963;return}a.frequency=e;a.Ec=f}catch(x){W.zc=40963}}else W.zc=40963},Va:function(a,b){if(W){for(var c=0;c<a;++c){var d=u[b+4*c>>2];if(0!==d){if(!X[d]){W.zc=40961;return}if(X[d].Ld){W.zc=40964;return}}}for(c=0;c<a;++c)d=u[b+4*c>>2],0!==d&&(U[X[d].deviceId]--,delete X[d],Dc.push(d))}},Ua:function(a,b){if(W){for(var c=0;c<a;++c){var d=u[b+4*c>>2];if(!W.Uc[d]){W.zc=40961;return}}for(c=0;c<a;++c)d=u[b+4*c>>2],Gc(W.Uc[d],4116),
Uc(d,4105,0),delete W.Uc[d],Dc.push(d)}},Ta:function(a,b){if(W)for(var c=0;c<a;++c){var d={deviceId:W.deviceId,id:Cc(),Ld:0,Ec:null,frequency:0,jd:2,dd:1,length:0};U[d.deviceId]++;X[d.id]=d;u[b+4*c>>2]=d.id}},Sa:function(a,b){if(W)for(var c=0;c<a;++c){var d=W.Kc.createGain();d.connect(W.gain);d={context:W,id:Cc(),type:4144,state:4113,Cc:[X[0]],Gc:[],hd:!1,pitch:1,Bd:1,gain:d,$e:0,Ze:1,Dc:null,Hc:0,Nc:Number.NEGATIVE_INFINITY,Lc:0,relative:!1,refDistance:1,maxDistance:3.40282E38,rolloffFactor:1,position:[0,
0,0],Rc:[0,0,0],direction:[0,0,0],coneOuterGain:0,coneInnerAngle:360,coneOuterAngle:360,distanceModel:53250,Ae:2,get playbackRate(){return this.pitch*this.Bd}};W.Uc[d.id]=d;u[b+4*c>>2]=d.id}},l:function(a){if(!W)return 0;if(Ac[a])return Ac[a];switch(a){case 0:var b="No Error";break;case 40961:b="Invalid Name";break;case 40962:b="Invalid Enum";break;case 40963:b="Invalid Value";break;case 40964:b="Invalid Operation";break;case 40965:b="Out of Memory";break;case 45057:b="Emscripten";break;case 45058:b=
"1.1";break;case 45059:b="WebAudio";break;case 45060:b="";for(var c in yc)b=b.concat(c),b=b.concat(" ");b=b.trim();break;default:return W.zc=40962,0}b=xa(mb(b));return Ac[a]=b},Ra:function(a,b){switch(a){case 4106:Qc(a,b);break;default:Qc(a,null)}},B:function(a,b){if(W)if(b)switch(a){case 4100:case 4102:Y[0]=F[b>>2];Y[1]=F[b+4>>2];Y[2]=F[b+8>>2];Qc(a,Y);break;case 4111:Y[0]=F[b>>2];Y[1]=F[b+4>>2];Y[2]=F[b+8>>2];Y[3]=F[b+12>>2];Y[4]=F[b+16>>2];Y[5]=F[b+20>>2];Qc(a,Y);break;default:Qc(a,null)}else W.zc=
40963},Qa:function(a){W&&((a=W.Uc[a])?Gc(a,4114):W.zc=40961)},A:function(a,b,c){switch(b){case 4097:case 4098:case 4099:case 4106:case 4109:case 4110:case 4128:case 4129:case 4130:case 4131:case 4132:case 4133:case 4134:case 8203:Rc(a,b,c);break;default:Rc(a,b,null)}},z:function(a,b,c){if(W)if(c)switch(b){case 4097:case 4098:case 4099:case 4106:case 4109:case 4110:case 4128:case 4129:case 4130:case 4131:case 4132:case 4133:case 4134:case 8203:Rc(a,b,F[c>>2]);break;case 4100:case 4101:case 4102:Y[0]=
F[c>>2];Y[1]=F[c+4>>2];Y[2]=F[c+8>>2];Rc(a,b,Y);break;default:Rc(a,b,null)}else W.zc=40963},y:Uc,Oa:function(a){if(!(a in U)||0<U[a])return 0;delete U[a];Dc.push(a);return 1},Na:function(a,b){if(!(a in U))return S=40961,0;var c=null,d=[],e=null;if(b>>=2)for(var f=0,h=0;;){f=u[b++];d.push(f);if(0===f)break;h=u[b++];d.push(h);switch(f){case 4103:c||(c={});c.sampleRate=h;break;case 4112:case 4113:break;case 6546:switch(h){case 0:e=!1;break;case 1:e=!0;break;case 2:break;default:return S=40964,0}break;
case 6550:if(0!==h)return S=40964,0;break;default:return S=40964,0}}f=window.AudioContext||window.webkitAudioContext;b=null;try{b=c?new f(c):new f}catch(x){return S="NotSupportedError"===x.name?40964:40961,0}"undefined"===typeof b.createGain&&(b.createGain=b.createGainNode);c=b.createGain();c.connect(b.destination);var n={deviceId:a,id:Cc(),me:d,Kc:b,listener:{position:[0,0,0],Rc:[0,0,0],direction:[0,0,0],Vc:[0,0,0]},Uc:[],interval:setInterval(function(){var a=n;if(1!==g.xc.xd||"visible"==document.visibilityState)for(var b in a.Uc)Ec(a.Uc[b])},
25),gain:c,distanceModel:53250,speedOfSound:343.3,dopplerFactor:1,hf:!1,re:e||!1,le:0,get zc(){return this.le},set zc(a){if(0===this.le||0===a)this.le=a}};U[a]++;V[n.id]=n;if(null!==e)for(var t in V)d=V[t],d.deviceId===a&&(d.re=e,Mc(d));return n.id},Ma:function(a){var b=V[a];W===b?S=40962:(V[a].interval&&clearInterval(V[a].interval),U[b.deviceId]--,delete V[a],Dc.push(a))},La:function(){var a=S;S=0;return a},x:function(a,b,c,d){if(0!==c&&d)switch(b){case 4096:u[d>>2]=1;break;case 4097:u[d>>2]=1;break;
case 4098:if(!a in U){S=40961;break}if(!W){S=40962;break}u[d>>2]=W.me.length;break;case 4099:if(!a in U){S=40961;break}if(!W){S=40962;break}for(a=0;a<W.me.length;a++)u[d+4*a>>2]=W.me[a];break;case 4103:if(!a in U){S=40961;break}if(!W){S=40962;break}u[d>>2]=W.Kc.sampleRate;break;case 4112:case 4113:if(!a in U){S=40961;break}if(!W){S=40962;break}u[d>>2]=2147483647;break;case 6546:case 6547:if(!a in U){S=40961;break}b=0;for(var e in V)c=V[e],c.deviceId===a&&(b=c.re?1:0);u[d>>2]=b;break;case 6548:if(!a in
U){S=40961;break}u[d>>2]=1;break;case 131075:if(!a in U){S=40961;break}if(!W){S=40962;break}u[d>>2]=1;case 786:a=Tc(a);if(!a)break;u[d>>2]=Math.floor(a.Ri/a.Kc.sampleRate*a.xi);break;default:S=40963}},q:function(a,b){if(zc[b])return zc[b];switch(b){case 0:var c="No Error";break;case 40961:c="Invalid Device";break;case 40962:c="Invalid Context";break;case 40963:c="Invalid Enum";break;case 40964:c="Invalid Value";break;case 40965:c="Out of Memory";break;case 4100:if("undefined"!==typeof AudioContext||
"undefined"!==typeof webkitAudioContext)c="Emscripten OpenAL";else return 0;break;case 4101:"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?c="Emscripten OpenAL".concat("\x00"):c="\x00";break;case 785:c="Emscripten OpenAL capture";break;case 784:if(0===a)c="Emscripten OpenAL capture".concat("\x00");else{a=Tc(a);if(!a)return 0;c=a.Ai}break;case 4102:if(!a)return S=40961,0;c="";for(var d in xc)c=c.concat(d),c=c.concat(" ");c=c.trim();break;default:return S=40963,0}c=xa(mb(c));
return zc[b]=c},Ka:function(a){if(0===a)return W=null,0;W=V[a];return 1},Ja:function(a){return a&&"Emscripten OpenAL"!==B(a)||"undefined"===typeof AudioContext&&"undefined"===typeof webkitAudioContext?0:(a=Cc(),U[a]=0,a)},Ia:function(a){return nb[a]()},Ha:function(a,b){return nb[a](b)},Ga:function(a,b,c){return nb[a](b,c)},Fa:function(a,b,c){a=md(a);if(!a)return-4;u[b>>2]=a.width;u[c>>2]=a.height},Ea:function(){return window.devicePixelRatio||1},Da:function(a,b,c){a=a?ld(a):m.canvas;if(!a)return-4;
a.getBoundingClientRect?(a=a.getBoundingClientRect(),I[b>>3]=a.right-a.left,I[c>>3]=a.bottom-a.top):(I[b>>3]=a.clientWidth,I[c>>3]=a.clientHeight);return 0},Ca:sa,Ba:function(a,b,c){A.set(A.subarray(b,b+c),a)},Aa:function(a){nd(a)},w:function(a,b,c){a=md(a);if(!a)return-4;a.width=b;a.height=c;return 0},ya:function(a,b,c,d){od(a,b,c,d,2,"keydown");return 0},xa:function(a,b,c,d){od(a,b,c,d,3,"keyup");return 0},wa:function(a,b,c,d){rd(a,b,c,d,5,"mousedown");return 0},va:function(a,b,c,d){rd(a,b,c,d,
8,"mousemove");return 0},ua:function(a,b,c,d){rd(a,b,c,d,6,"mouseup");return 0},ta:function(a,b,c,d){sd(a,b,c,d);return 0},sa:function(a,b,c,d){a=ld(a);return"undefined"!==typeof a.onwheel?(td(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(td(a,b,c,d,"mousewheel"),0):-1},ra:function(){return ud()},qa:function(a,b){var c={};b>>=2;c.alpha=!!u[b];c.depth=!!u[b+1];c.stencil=!!u[b+2];c.antialias=!!u[b+3];c.premultipliedAlpha=!!u[b+4];c.preserveDrawingBuffer=!!u[b+5];c.powerPreference=wd[u[b+
6]];c.failIfMajorPerformanceCaveat=!!u[b+7];c.Xe=u[b+8];c.Li=u[b+9];c.Me=u[b+10];c.Oe=u[b+11];c.Oi=u[b+12];c.Qi=u[b+13];a=md(a);return!a||c.Oe?0:k.createContext(a,c)},pa:function(a){k.Qc==a&&(k.Qc=0);k.Bf(a)},oa:function(a){a>>=2;for(var b=0;14>b;++b)u[a+b]=0;u[a]=u[a+1]=u[a+3]=u[a+4]=u[a+8]=u[a+10]=1},na:xd,i:function(a){Qd(a)},h:yd,p:function(a){l.activeTexture(a)},ma:function(a,b){l.attachShader(k.Pc[a],k.Yc[b])},la:function(a,b,c){l.bindAttribLocation(k.Pc[a],b,B(c))},v:function(a,b){l.bindBuffer(a,
k.Sd[b])},ka:function(a,b){l.bindFramebuffer(a,k.Se[b])},ja:function(a,b){l.bindRenderbuffer(a,k.ze[b])},o:function(a,b){l.bindTexture(a,k.Ce[b])},ha:function(a){l.bindVertexArray(k.je[a])},ga:function(a,b,c,d){l.bufferData(a,c?A.subarray(c,c+b):b,d)},fa:function(a,b,c,d){l.bufferSubData(a,b,A.subarray(d,d+c))},ea:function(a){return l.checkFramebufferStatus(a)},da:function(a){l.clear(a)},ca:function(a,b,c,d){l.clearColor(a,b,c,d)},ba:function(a){l.clearDepth(a)},aa:function(a){l.compileShader(k.Yc[a])},
u:function(a,b,c,d,e,f,h,n,t){l.compressedTexSubImage2D(a,b,c,d,e,f,h,t?A.subarray(t,t+n):null)},$:function(a,b,c,d,e,f,h,n){l.copyTexSubImage2D(a,b,c,d,e,f,h,n)},_:function(){var a=k.Cd(k.Pc),b=l.createProgram();b.name=a;k.Pc[a]=b;return a},Z:function(a){var b=k.Cd(k.Yc);k.Yc[b]=l.createShader(a);return b},Y:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=k.Sd[d];e&&(l.deleteBuffer(e),e.name=0,k.Sd[d]=null,d==k.zf&&(k.zf=0),d==k.Af&&(k.Af=0))}},X:function(a){if(a){var b=k.Pc[a];b?(l.deleteProgram(b),
b.name=0,k.Pc[a]=null,k.Jd[a]=null):k.Ic(1281)}},W:function(a){if(a){var b=k.Yc[a];b?(l.deleteShader(b),k.Yc[a]=null):k.Ic(1281)}},V:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];l.deleteVertexArray(k.je[d]);k.je[d]=null}},U:function(a){l.disableVertexAttribArray(a)},T:function(a,b,c){l.drawArrays(a,b,c)},S:function(a,b,c,d){l.drawArraysInstanced(a,b,c,d)},R:function(a,b){for(var c=zd[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];l.drawBuffers(c)},Q:function(a,b,c,d){l.drawElements(a,b,c,d)},P:function(a,
b,c,d,e){l.drawElementsInstanced(a,b,c,d,e)},O:function(a){l.enable(a)},N:function(a){l.enableVertexAttribArray(a)},M:function(a,b,c,d){l.framebufferRenderbuffer(a,b,c,k.ze[d])},L:function(a,b,c,d,e){l.framebufferTexture2D(a,b,c,k.Ce[d],e)},K:function(a,b){Ad(a,b,"createBuffer",k.Sd)},J:function(a,b){Ad(a,b,"createFramebuffer",k.Se)},I:function(a,b){Ad(a,b,"createRenderbuffer",k.ze)},Ib:function(a,b){Ad(a,b,"createTexture",k.Ce)},Hb:function(a,b){Ad(a,b,"createVertexArray",k.je)},Gb:function(a){l.generateMipmap(a)},
Fb:function(a,b,c){c?u[c>>2]=l.getBufferParameter(a,b):k.Ic(1281)},Eb:function(){if(k.Ed){var a=k.Ed;k.Ed=0;return a}return l.getError()},Db:function(a,b){Bd(a,b,"Float")},r:function(a,b){Bd(a,b,"Integer")},Cb:function(a,b,c,d){a=l.getProgramInfoLog(k.Pc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=D(a,A,d,b),c&&(u[c>>2]=b)):c&&(u[c>>2]=0)},H:function(a,b,c){if(c)if(a>=k.Le)k.Ic(1281);else{var d=k.Jd[a];if(d)if(35716==b)a=l.getProgramInfoLog(k.Pc[a]),null===a&&(a="(unknown error)"),u[c>>2]=a.length+
1;else if(35719==b)u[c>>2]=d.te;else if(35722==b){if(-1==d.Fd){a=k.Pc[a];var e=l.getProgramParameter(a,35721);for(b=d.Fd=0;b<e;++b)d.Fd=Math.max(d.Fd,l.getActiveAttrib(a,b).name.length+1)}u[c>>2]=d.Fd}else if(35381==b){if(-1==d.Gd)for(a=k.Pc[a],e=l.getProgramParameter(a,35382),b=d.Gd=0;b<e;++b)d.Gd=Math.max(d.Gd,l.getActiveUniformBlockName(a,b).length+1);u[c>>2]=d.Gd}else u[c>>2]=l.getProgramParameter(k.Pc[a],b);else k.Ic(1282)}else k.Ic(1281)},Bb:function(a,b,c,d){a=l.getShaderInfoLog(k.Yc[a]);null===
a&&(a="(unknown error)");0<b&&d?(b=D(a,A,d,b),c&&(u[c>>2]=b)):c&&(u[c>>2]=0)},F:function(a,b,c){c?35716==b?(a=l.getShaderInfoLog(k.Yc[a]),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1):35720==b?(a=l.getShaderSource(k.Yc[a]),u[c>>2]=null===a||0==a.length?0:a.length+1):u[c>>2]=l.getShaderParameter(k.Yc[a],b):k.Ic(1281)},n:function(a){if(k.Be[a])return k.Be[a];switch(a){case 7939:var b=l.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Cd(c.join(" "));break;
case 7936:case 7937:case 37445:case 37446:(b=l.getParameter(a))||k.Ic(1280);b=Cd(b);break;case 7938:b=Cd("OpenGL ES 2.0 ("+l.getParameter(l.VERSION)+")");break;case 35724:b=l.getParameter(l.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Cd(b);break;default:return k.Ic(1280),0}return k.Be[a]=b},Ab:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+
1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=k.Jd[a]&&k.Jd[a].Jc[b])&&0<=c&&c<a[0]?a[1]+c:-1},zb:function(a){l.linkProgram(k.Pc[a]);k.Pf(a)},yb:function(a,b){3317==a&&(k.kf=b);l.pixelStorei(a,b)},xb:function(a,b,c,d,e,f,h){(h=Fd(f,e,c,d,h))?l.readPixels(a,b,c,d,e,f,h):k.Ic(1280)},wb:function(a,b,c,d){l.renderbufferStorage(a,b,c,d)},vb:function(a,b,c,d){b=k.Gf(a,b,c,d);l.shaderSource(k.Yc[a],b)},ub:function(a,b,c,d,e,f,h,n,t){l.texImage2D(a,b,c,d,e,f,h,n,t?Fd(n,h,d,e,t):null)},tb:function(a,
b,c){l.texParameterf(a,b,c)},sb:function(a,b,c){l.texParameterf(a,b,F[c>>2])},rb:function(a,b,c){l.texParameteri(a,b,c)},E:function(a,b,c,d,e,f,h,n,t){var x=null;t&&(x=Fd(n,h,e,f,t));l.texSubImage2D(a,b,c,d,e,f,h,n,x)},qb:function(a,b,c){if(b<=k.cd)for(var d=k.ld[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);l.uniform1fv(k.Jc[a],d)},pb:function(a,b,c){l.uniform1iv(k.Jc[a],u.subarray(c>>2,c+4*b>>2))},ob:function(a,b,c){if(2*b<=k.cd)for(var d=k.ld[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+
4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);l.uniform2fv(k.Jc[a],d)},nb:function(a,b,c){l.uniform2iv(k.Jc[a],u.subarray(c>>2,c+8*b>>2))},mb:function(a,b,c){if(3*b<=k.cd)for(var d=k.ld[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);l.uniform3fv(k.Jc[a],d)},lb:function(a,b,c){l.uniform3iv(k.Jc[a],u.subarray(c>>2,c+12*b>>2))},kb:function(a,b,c){if(4*b<=k.cd)for(var d=k.ld[4*b-1],e=0;e<4*b;e+=4)d[e]=F[c+4*e>>2],
d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2],d[e+3]=F[c+(4*e+12)>>2];else d=F.subarray(c>>2,c+16*b>>2);l.uniform4fv(k.Jc[a],d)},ib:function(a,b,c){l.uniform4iv(k.Jc[a],u.subarray(c>>2,c+16*b>>2))},hb:function(a,b,c,d){if(4*b<=k.cd)for(var e=k.ld[4*b-1],f=0;f<4*b;f+=4)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);l.uniformMatrix2fv(k.Jc[a],!!c,e)},gb:function(a,b,c,d){if(9*b<=k.cd)for(var e=k.ld[9*b-1],f=0;f<9*b;f+=9)e[f]=
F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);l.uniformMatrix3fv(k.Jc[a],!!c,e)},fb:function(a,b,c,d){if(16*b<=k.cd)for(var e=k.ld[16*b-1],f=0;f<16*b;f+=16)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>
2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2],e[f+9]=F[d+(4*f+36)>>2],e[f+10]=F[d+(4*f+40)>>2],e[f+11]=F[d+(4*f+44)>>2],e[f+12]=F[d+(4*f+48)>>2],e[f+13]=F[d+(4*f+52)>>2],e[f+14]=F[d+(4*f+56)>>2],e[f+15]=F[d+(4*f+60)>>2];else e=F.subarray(d>>2,d+64*b>>2);l.uniformMatrix4fv(k.Jc[a],!!c,e)},eb:function(a){l.useProgram(k.Pc[a])},db:function(a,b){l.vertexAttribDivisor(a,b)},cb:function(a,b,c,d,e,f){l.vertexAttribPointer(a,b,c,!!d,e,f)},bb:function(a,b,c,d){l.viewport(a,b,c,d)},g:function(a){var b=
Gd.ad[a];Gd.ad.splice(a,1);Rd(b)},f:Gd,$a:function(){q("trap!")},_a:function(){return 0},Za:function(a,b,c,d){return Nd(a,b,c,d)},Ya:nd,a:ra},buffer);m.asm=Sd;
var qb=m.__GLOBAL__sub_I_driverSpecific_cpp=function(){return m.asm.Lb.apply(null,arguments)},pb=m.__GLOBAL__sub_I_importStaticPlugin_cpp=function(){return m.asm.Mb.apply(null,arguments)},ub=m.__GLOBAL__sub_I_iostream_cpp=function(){return m.asm.Nb.apply(null,arguments)},ob=m.__GLOBAL__sub_I_resource_AudioExample_RESOURCES_cpp=function(){return m.asm.Ob.apply(null,arguments)},rb=m.__GLOBAL__sub_I_resource_MagnumShaders_RCS_cpp=function(){return m.asm.Pb.apply(null,arguments)},sb=m.__GLOBAL__sub_I_resource_StbVorbisAudioImporter_cpp=
function(){return m.asm.Qb.apply(null,arguments)},Pd=m.__ZSt18uncaught_exceptionv=function(){return m.asm.Rb.apply(null,arguments)},tb=m.___emscripten_environ_constructor=function(){return m.asm.Sb.apply(null,arguments)};m.___errno_location=function(){return m.asm.Tb.apply(null,arguments)};var vd=m._free=function(){return m.asm.Ub.apply(null,arguments)};m._main=function(){return m.asm.Vb.apply(null,arguments)};
var w=m._malloc=function(){return m.asm.Wb.apply(null,arguments)},Fa=m.stackAlloc=function(){return m.asm.uc.apply(null,arguments)},Rd=m.stackRestore=function(){return m.asm.vc.apply(null,arguments)},Hd=m.stackSave=function(){return m.asm.wc.apply(null,arguments)};m.dynCall_ii=function(){return m.asm.Xb.apply(null,arguments)};m.dynCall_iii=function(){return m.asm.Yb.apply(null,arguments)};var pd=m.dynCall_iiii=function(){return m.asm.Zb.apply(null,arguments)};
m.dynCall_iiiii=function(){return m.asm._b.apply(null,arguments)};m.dynCall_iiiiid=function(){return m.asm.$b.apply(null,arguments)};m.dynCall_iiiiii=function(){return m.asm.ac.apply(null,arguments)};m.dynCall_iiiiiid=function(){return m.asm.bc.apply(null,arguments)};m.dynCall_iiiiiii=function(){return m.asm.cc.apply(null,arguments)};m.dynCall_iiiiiiii=function(){return m.asm.dc.apply(null,arguments)};m.dynCall_iiiiiiiii=function(){return m.asm.ec.apply(null,arguments)};
m.dynCall_iiiiij=function(){return m.asm.fc.apply(null,arguments)};m.dynCall_v=function(){return m.asm.gc.apply(null,arguments)};m.dynCall_vf=function(){return m.asm.hc.apply(null,arguments)};m.dynCall_vi=function(){return m.asm.ic.apply(null,arguments)};m.dynCall_vif=function(){return m.asm.jc.apply(null,arguments)};m.dynCall_vii=function(){return m.asm.kc.apply(null,arguments)};m.dynCall_viif=function(){return m.asm.lc.apply(null,arguments)};
m.dynCall_viii=function(){return m.asm.mc.apply(null,arguments)};m.dynCall_viiii=function(){return m.asm.nc.apply(null,arguments)};m.dynCall_viiiii=function(){return m.asm.oc.apply(null,arguments)};m.dynCall_viiiiii=function(){return m.asm.pc.apply(null,arguments)};m.dynCall_viiiiiii=function(){return m.asm.qc.apply(null,arguments)};m.dynCall_viiiiiiii=function(){return m.asm.rc.apply(null,arguments)};m.dynCall_viiiiiiiii=function(){return m.asm.sc.apply(null,arguments)};
m.dynCall_viijii=function(){return m.asm.tc.apply(null,arguments)};m.asm=Sd;function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}la.prototype=Error();la.prototype.constructor=la;db=function Td(){m.calledRun||Ud();m.calledRun||(db=Td)};
m.callMain=function(a){a=a||[];Ra();var b=a.length+1,c=Fa(4*(b+1));u[c>>2]=Ea(m.thisProgram);for(var d=1;d<b;d++)u[(c>>2)+d]=Ea(a[d-1]);u[(c>>2)+b]=0;try{var e=m._main(b,c,0);Qd(e,!0)}catch(f){f instanceof la||("SimulateInfiniteLoop"==f?m.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),r("exception thrown: "+a),m.quit(1,f)))}finally{}};
function Ud(a){function b(){if(!m.calledRun&&(m.calledRun=!0,!v)){Ra();Ub=!1;Ka(Na);if(m.onRuntimeInitialized)m.onRuntimeInitialized();m._main&&Vd&&m.callMain(a);if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();Pa.unshift(b)}Ka(Pa)}}a=a||m.arguments;if(!(0<bb)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Xa();Ka(La);0<bb||m.calledRun||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},
1);b()},1)):b())}}m.run=Ud;function Qd(a,b){if(!b||!m.noExitRuntime||0!==a){if(!m.noExitRuntime&&(v=!0,m.onExit))m.onExit(a);m.quit(a,new la(a))}}function q(a){if(m.onAbort)m.onAbort(a);void 0!==a?(ma(a),r(a),a=JSON.stringify(a)):a="";v=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}m.abort=q;if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();var Vd=!0;m.noInitialRun&&(Vd=!1);m.noExitRuntime=!0;Ud();
