var aa,g;var h,k;var m;m||(m=typeof Module !== 'undefined' ? Module : {});var ba={},n;for(n in m)m.hasOwnProperty(n)&&(ba[n]=m[n]);m.arguments=[];m.thisProgram="./this.program";m.quit=function(a,b){throw b;};m.preRun=[];m.postRun=[];var ca=!1,p=!1,q=!1,da=!1;ca="object"===typeof window;p="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!ca&&!p;da=!ca&&!q&&!p;var t="";
if(q){t=__dirname+"/";var fa,ha;m.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};m.readBinary=function(a){a=m.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(m.thisProgram=process.argv[1].replace(/\\/g,"/"));m.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=m);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",
u);m.quit=function(a){process.exit(a)};m.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(m.read=function(a){return read(a)}),m.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m.arguments=scriptArgs:"undefined"!=typeof arguments&&(m.arguments=arguments),"function"===typeof quit&&(m.quit=function(a){quit(a)});else if(ca||p)p?
t=self.location.href:document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?t.substr(0,t.lastIndexOf("/")+1):"",m.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(m.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),m.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},m.setWindowTitle=function(a){document.title=a};var ja=m.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),w=m.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ja);for(n in ba)ba.hasOwnProperty(n)&&(m[n]=ba[n]);ba=void 0;function ka(a){var b=y[la>>2];a=b+a+15&-16;if(a<=ma())y[la>>2]=a;else return 0;return b}
var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&w("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||u("Assertion failed: "+b)}function qa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=z(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)y[a>>2]=0;for(b=d+c;a<b;)B[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}
var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?sa(C,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var r=a.charCodeAt(++f);l=65536+((l&1023)<<10)|r&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ua(a){var b=ta(a)+1,c=va(b);E(a,B,c,b);return c}var buffer,B,C,wa,xa,y,ya,F,G,la=1417312,za=m.TOTAL_MEMORY||16777216;5242880>za&&w("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+za+"! (TOTAL_STACK=5242880)");
m.buffer?buffer=m.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(oa=new WebAssembly.Memory({initial:za/65536,maximum:za/65536}),buffer=oa.buffer):buffer=new ArrayBuffer(za);m.HEAP8=B=new Int8Array(buffer);m.HEAP16=wa=new Int16Array(buffer);m.HEAP32=y=new Int32Array(buffer);m.HEAPU8=C=new Uint8Array(buffer);m.HEAPU16=xa=new Uint16Array(buffer);m.HEAPU32=ya=new Uint32Array(buffer);m.HEAPF32=F=new Float32Array(buffer);m.HEAPF64=G=new Float64Array(buffer);y[la>>2]=6660448;
function Aa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.xc;"number"===typeof c?void 0===b.gd?m.dynCall_v(c):m.dynCall_vi(c,b.gd):c(void 0===b.gd?null:b.gd)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[],Ga=!1;
function Ha(){Ga||(Ga=!0,m.noFSInit||Ia||(Ia=!0,Ja(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?Ka("stdin",m.stdin):La("/dev/tty","/dev/stdin"),m.stdout?Ka("stdout",null,m.stdout):La("/dev/tty","/dev/stdout"),m.stderr?Ka("stderr",null,m.stderr):La("/dev/tty1","/dev/stderr"),Ma("/dev/stdin","r"),Ma("/dev/stdout","w"),Ma("/dev/stderr","w")),Aa(Ca))}function Na(){var a=m.preRun.shift();Ba.unshift(a)}var Oa=Math.abs,Pa=Math.ceil,Qa=Math.floor,Ra=Math.min,H=0,Sa=null,Ta=null;
m.preloadedImages={};m.preloadedAudios={};function Ua(){var a=I;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var I="magnum-viewer.wasm";if(!Ua()){var Va=I;I=m.locateFile?m.locateFile(Va,t):t+Va}function Wa(){try{if(m.wasmBinary)return new Uint8Array(m.wasmBinary);if(m.readBinary)return m.readBinary(I);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function Xa(){return m.wasmBinary||!ca&&!p||"function"!==typeof fetch?new Promise(function(a){a(Wa())}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}
function Ya(a){function b(a){m.asm=a.exports;H--;m.monitorRunDependencies&&m.monitorRunDependencies(H);0==H&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta&&(a=Ta,Ta=null,a()))}function c(a){b(a.instance)}function d(a){Xa().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){w("failed to asynchronously prepare wasm: "+a);u(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};H++;m.monitorRunDependencies&&m.monitorRunDependencies(H);if(m.instantiateWasm)try{return m.instantiateWasm(e,
b)}catch(f){return w("Module.instantiateWasm callback failed with error: "+f),!1}m.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ua()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(I,{credentials:"same-origin"}),e).then(c,function(a){w("wasm streaming compile failed: "+a);w("falling back to ArrayBuffer instantiation");d(c)});return{}}
m.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:924,maximum:924,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Ya(b)};
var $a=[function(){var a=m.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?qa(Za(a.id)):0},function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?m.dynCall_ii.apply(null,[a].concat(e)):m.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(a){a=D(a);return"undefined"!==typeof process&&a in process.env?qa(Za(process.env[a])):0}];
Ca.push({xc:function(){ab()}},{xc:function(){bb()}},{xc:function(){cb()}},{xc:function(){db()}},{xc:function(){eb()}},{xc:function(){fb()}},{xc:function(){gb()}},{xc:function(){hb()}},{xc:function(){ib()}},{xc:function(){jb()}});var J={};
function kb(a){if(kb.qc){var b=y[a>>2];var c=y[b>>2]}else kb.qc=!0,J.USER=J.LOGNAME="web_user",J.PATH="/",J.PWD="/",J.HOME="/home/web_user",J.LANG="C.UTF-8",J._=m.thisProgram,c=Ga?z(1024):ka(1024),b=Ga?z(256):ka(256),y[b>>2]=c,y[a>>2]=b;a=[];var d=0,e;for(e in J)if("string"===typeof J[e]){var f=e+"="+J[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var l=c,r=0;r<d.length;++r)B[l++>>0]=d.charCodeAt(r);B[l>>0]=0;y[b+4*
e>>2]=c;c+=f.length+1}y[b+4*a.length>>2]=0}function lb(a){m.___errno_location&&(y[m.___errno_location()>>2]=a);return a}function mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function pb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function rb(){var a=Array.prototype.slice.call(arguments,0);return nb(a.join("/"))}function K(a,b){return nb(a+"/"+b)}
function sb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var tb=[];function ub(a,b){tb[a]={input:[],output:[],Kc:b};vb(a,wb)}
var wb={open:function(a){var b=tb[a.node.rdev];if(!b)throw new L(N.ed);a.tty=b;a.seekable=!1},close:function(a){a.tty.Kc.flush(a.tty)},flush:function(a){a.tty.Kc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Kc.Ed)throw new L(N.sd);for(var e=0,f=0;f<d;f++){try{var l=a.tty.Kc.Ed(a.tty)}catch(r){throw new L(N.qd);}if(void 0===l&&0===e)throw new L(N.Md);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Kc.md)throw new L(N.sd);
try{for(var e=0;e<d;e++)a.tty.Kc.md(a.tty,b[c+e])}catch(f){throw new L(N.qd);}d&&(a.node.timestamp=Date.now());return e}},xb={Ed:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},md:function(a,b){null===b||10===b?(ja(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(sa(a.output,0)),a.output=[])}},yb={md:function(a,b){null===b||10===b?(w(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(w(sa(a.output,0)),a.output=[])}},O={yc:null,rc:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(N.Qd);O.yc||(O.yc={dir:{node:{Bc:O.jc.Bc,uc:O.jc.uc,lookup:O.jc.lookup,Qc:O.jc.Qc,rename:O.jc.rename,unlink:O.jc.unlink,rmdir:O.jc.rmdir,readdir:O.jc.readdir,symlink:O.jc.symlink},stream:{Dc:O.ic.Dc}},file:{node:{Bc:O.jc.Bc,uc:O.jc.uc},stream:{Dc:O.ic.Dc,read:O.ic.read,write:O.ic.write,td:O.ic.td,Hd:O.ic.Hd,
$c:O.ic.$c}},link:{node:{Bc:O.jc.Bc,uc:O.jc.uc,readlink:O.jc.readlink},stream:{}},vd:{node:{Bc:O.jc.Bc,uc:O.jc.uc},stream:zb}});c=Ab(a,b,c,d);16384===(c.mode&61440)?(c.jc=O.yc.dir.node,c.ic=O.yc.dir.stream,c.hc={}):32768===(c.mode&61440)?(c.jc=O.yc.file.node,c.ic=O.yc.file.stream,c.kc=0,c.hc=null):40960===(c.mode&61440)?(c.jc=O.yc.link.node,c.ic=O.yc.link.stream):8192===(c.mode&61440)&&(c.jc=O.yc.vd.node,c.ic=O.yc.vd.stream);c.timestamp=Date.now();a&&(a.hc[b]=c);return c},zg:function(a){if(a.hc&&
a.hc.subarray){for(var b=[],c=0;c<a.kc;++c)b.push(a.hc[c]);return b}return a.hc},Ag:function(a){return a.hc?a.hc.subarray?a.hc.subarray(0,a.kc):new Uint8Array(a.hc):new Uint8Array},yd:function(a,b){var c=a.hc?a.hc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.hc,a.hc=new Uint8Array(b),0<a.kc&&a.hc.set(c.subarray(0,a.kc),0))},je:function(a,b){if(a.kc!=b)if(0==b)a.hc=null,a.kc=0;else{if(!a.hc||a.hc.subarray){var c=a.hc;a.hc=new Uint8Array(new ArrayBuffer(b));c&&
a.hc.set(c.subarray(0,Math.min(b,a.kc)))}else if(a.hc||(a.hc=[]),a.hc.length>b)a.hc.length=b;else for(;a.hc.length<b;)a.hc.push(0);a.kc=b}},jc:{Bc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.kc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Gc=4096;b.blocks=Math.ceil(b.size/
b.Gc);return b},uc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.je(a,b.size)},lookup:function(){throw Bb[N.Od];},Qc:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Cb(b,c)}catch(f){}if(d)for(var e in d.hc)throw new L(N.rd);}delete a.parent.hc[a.name];a.name=c;b.hc[c]=a;a.parent=b},unlink:function(a,b){delete a.hc[b]},rmdir:function(a,b){var c=Cb(a,b),d;for(d in c.hc)throw new L(N.rd);
delete a.hc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.hc)a.hc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(N.tc);return a.link}},ic:{read:function(a,b,c,d,e){var f=a.node.hc;if(e>=a.node.kc)return 0;a=Math.min(a.node.kc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.hc||a.hc.subarray)){if(f)return a.hc=b.subarray(c,c+d),a.kc=d;if(0===a.kc&&0===e)return a.hc=new Uint8Array(b.subarray(c,c+d)),a.kc=d;if(e+d<=a.kc)return a.hc.set(b.subarray(c,c+d),e),d}O.yd(a,e+d);if(a.hc.subarray&&b.subarray)a.hc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.hc[e+f]=b[c+f];a.kc=Math.max(a.kc,e+d);return d},Dc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kc);if(0>b)throw new L(N.tc);return b},td:function(a,
b,c){O.yd(a.node,b+c);a.node.kc=Math.max(a.node.kc,b+c)},Hd:function(a,b,c,d,e,f,l){if(32768!==(a.node.mode&61440))throw new L(N.ed);c=a.node.hc;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.kc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=z(d);if(!d)throw new L(N.Pd);b.set(c,d)}else a=!1,d=c.byteOffset;return{Gg:d,Sd:a}},$c:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(N.ed);if(e&2)return 0;O.ic.write(a,b,0,d,c,!1);return 0}}},P={Yc:!1,
le:function(){P.Yc=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.Ad={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ud:function(a){return Buffer.qc?Buffer.from(a):new Buffer(a)},rc:function(a){assert(q);return P.createNode(null,"/",P.Dd(a.ld.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(N.tc);a=Ab(a,b,c);a.jc=P.jc;a.ic=P.ic;return a},Dd:function(a){try{var b=
fs.lstatSync(a);P.Yc&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}return b.mode},sc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.rc.ld.root);b.reverse();return rb.apply(null,b)},Yd:function(a){a&=-2656257;var b=0,c;for(c in P.Ad)a&c&&(b|=P.Ad[c],a^=c);if(a)throw new L(N.tc);return b},jc:{Bc:function(a){a=P.sc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}P.Yc&&!b.Gc&&(b.Gc=4096);P.Yc&&!b.blocks&&
(b.blocks=(b.size+b.Gc-1)/b.Gc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Gc:b.Gc,blocks:b.blocks}},uc:function(a,b){var c=P.sc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},lookup:function(a,b){var c=K(P.sc(a),b);c=P.Dd(c);return P.createNode(a,b,c)},Qc:function(a,b,c,d){a=P.createNode(a,
b,c,d);b=P.sc(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new L(N[e.code]);}return a},rename:function(a,b,c){a=P.sc(a);b=K(P.sc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},unlink:function(a,b){a=K(P.sc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}},rmdir:function(a,b){a=K(P.sc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);
}},readdir:function(a){a=P.sc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(N[b.code]);}},symlink:function(a,b,c){a=K(P.sc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},readlink:function(a){var b=P.sc(a);try{return b=fs.readlinkSync(b),b=Db.relative(Db.resolve(a.rc.ld.root),b)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}}},ic:{open:function(a){var b=P.sc(a.node);try{32768===(a.node.mode&61440)&&(a.Rc=fs.openSync(b,P.Yd(a.flags)))}catch(c){if(!c.code)throw c;
throw new L(N[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Rc&&fs.closeSync(a.Rc)}catch(b){if(!b.code)throw b;throw new L(N[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Rc,P.ud(b.buffer),c,d,e)}catch(f){throw new L(N[f.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Rc,P.ud(b.buffer),c,d,e)}catch(f){throw new L(N[f.code]);}},Dc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Rc).size}catch(d){throw new L(N[d.code]);
}if(0>b)throw new L(N.tc);return b}}},Eb=null,Fb={},Gb=[],Hb=1,Ib=null,Jb=!0,Kb={},L=null,Bb={};
function Q(a,b){a=sb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Bd:!0,nd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.nd)throw new L(40);a=mb(a.split("/").filter(function(a){return!!a}),!1);var e=Eb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Cb(e,a[d]);c=K(c,a[d]);e.Zc&&(!f||f&&b.Bd)&&(e=e.Zc.root);if(!f||b.hd)for(f=0;40960===(e.mode&61440);)if(e=Lb(c),c=sb(ob(c),e),e=Q(c,{nd:b.nd}).node,40<f++)throw new L(40);}return{path:c,node:e}}
function Mb(a){for(var b;;){if(a===a.parent)return a=a.rc.Id,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Nb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ib.length}function Ob(a){var b=Nb(a.parent.id,a.name);a.ge=Ib[b];Ib[b]=a}function Cb(a,b){var c;if(c=(c=Pb(a,"x"))?c:a.jc.lookup?0:13)throw new L(c,a);for(c=Ib[Nb(a.id,b)];c;c=c.ge){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.jc.lookup(a,b)}
function Ab(a,b,c,d){Qb||(Qb=function(a,b,c,d){a||(a=this);this.parent=a;this.rc=a.rc;this.Zc=null;this.id=Hb++;this.name=b;this.mode=c;this.jc={};this.ic={};this.rdev=d},Qb.prototype={},Object.defineProperties(Qb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Qb(a,b,c,d);Ob(a);return a}
var Rb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Sb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Pb(a,b){if(Jb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Tb(a,b){try{return Cb(a,b),17}catch(c){}return Pb(a,"wx")}
function Ub(a){var b=4096;for(a=a||0;a<=b;a++)if(!Gb[a])return a;throw new L(24);}function Vb(a,b){Wb||(Wb=function(){},Wb.prototype={},Object.defineProperties(Wb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Wb,d;for(d in a)c[d]=a[d];a=c;b=Ub(b);a.fd=b;return Gb[b]=a}var zb={open:function(a){a.ic=Fb[a.node.rdev].ic;a.ic.open&&a.ic.open(a)},Dc:function(){throw new L(29);}};function vb(a,b){Fb[a]={ic:b}}
function Xb(a,b){var c="/"===b,d=!b;if(c&&Eb)throw new L(16);if(!c&&!d){var e=Q(b,{Bd:!1});b=e.path;e=e.node;if(e.Zc)throw new L(16);if(16384!==(e.mode&61440))throw new L(20);}b={type:a,ld:{},Id:b,fe:[]};a=a.rc(b);a.rc=b;b.root=a;c?Eb=a:e&&(e.Zc=b,e.rc&&e.rc.fe.push(b))}function Yb(a,b,c){var d=Q(a,{parent:!0}).node;a=pb(a);if(!a||"."===a||".."===a)throw new L(22);var e=Tb(d,a);if(e)throw new L(e);if(!d.jc.Qc)throw new L(1);return d.jc.Qc(d,a,b,c)}function T(a){Yb(a,16895,0)}
function Zb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Yb(a,b|8192,c)}function La(a,b){if(!sb(a))throw new L(2);var c=Q(b,{parent:!0}).node;if(!c)throw new L(2);b=pb(b);var d=Tb(c,b);if(d)throw new L(d);if(!c.jc.symlink)throw new L(1);c.jc.symlink(c,b,a)}function Lb(a){a=Q(a).node;if(!a)throw new L(2);if(!a.jc.readlink)throw new L(22);return sb(Mb(a.parent),a.jc.readlink(a))}
function Ma(a,b,c,d){if(""===a)throw new L(2);if("string"===typeof b){var e=Rb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=nb(a);try{f=Q(a,{hd:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(f){if(b&128)throw new L(17);}else f=Yb(a,c,0),e=!0;if(!f)throw new L(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new L(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Sb(b)||b&512)?21:Pb(f,Sb(b)):2))throw new L(c);if(b&512){c=f;var l;"string"===typeof c?l=Q(c,{hd:!0}).node:l=c;if(!l.jc.uc)throw new L(1);if(16384===(l.mode&61440))throw new L(21);if(32768!==(l.mode&61440))throw new L(22);if(c=Pb(l,"w"))throw new L(c);l.jc.uc(l,{size:0,timestamp:Date.now()})}b&=-641;d=Vb({node:f,path:Mb(f),flags:b,seekable:!0,position:0,ic:f.ic,qe:[],error:!1},d);d.ic.open&&d.ic.open(d);!m.logReadFiles||b&1||($b||($b={}),a in $b||($b[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Kb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Kb.onOpenFile(a,f))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function ac(a,b,c){if(null===a.fd)throw new L(9);if(!a.seekable||!a.ic.Dc)throw new L(29);if(0!=c&&1!=c&&2!=c)throw new L(22);a.position=a.ic.Dc(a,b,c);a.qe=[]}
function Ja(){L||(L=function(a,b){this.node=b;this.ke=function(a){this.Ac=a};this.ke(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[2].forEach(function(a){Bb[a]=new L(a);Bb[a].stack="<generic error, no stack>"}))}var Ia;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ka(a,b,c){a=K("/dev",a);var d=bc(!!b,!!c);cc||(cc=64);var e=cc++<<8|0;vb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,l=0;l<e;l++){try{var r=b()}catch(M){throw new L(5);}if(void 0===r&&0===f)throw new L(11);if(null===r||void 0===r)break;f++;c[d+l]=r}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(A){throw new L(5);}e&&(a.node.timestamp=Date.now());return f}});
Zb(a,d,e)}
var cc,U={},Qb,Wb,$b,N={Qd:1,Od:2,jg:3,$e:4,qd:5,sd:6,re:7,Cf:8,Nd:9,Ge:10,Md:11,tg:11,Pd:12,Ld:13,Te:14,Of:15,Ee:16,Se:17,ug:18,ed:19,Qf:20,bf:21,tc:22,xf:23,pf:24,Jc:25,qg:26,Ue:27,Kf:28,ig:29,fg:30,qf:31,Zf:32,Pe:33,cg:34,Gf:42,Xe:43,He:44,df:45,ef:46,ff:47,mf:48,rg:49,Af:50,cf:51,Me:35,Df:37,xe:52,Ae:53,vg:54,yf:55,Be:56,Ce:57,Ne:35,De:59,Mf:60,Bf:61,ng:62,Lf:63,Hf:64,If:65,eg:66,Ef:67,ue:68,kg:69,Ie:70,$f:71,sf:72,Qe:73,ze:74,Uf:76,ye:77,dg:78,gf:79,hf:80,lf:81,kf:82,jf:83,Nf:38,rd:39,tf:36,
nf:40,Vf:95,Yf:96,Le:104,zf:105,ve:97,bg:91,Sf:88,Jf:92,gg:108,Ke:111,se:98,Je:103,wf:101,uf:100,og:110,Ve:112,We:113,Ze:115,we:114,Oe:89,rf:90,ag:93,hg:94,te:99,vf:102,af:106,Pf:107,pg:109,sg:87,Re:122,lg:116,Tf:95,Ff:123,Ye:84,Wf:75,Fe:125,Rf:131,Xf:130,mg:86},dc={},V=0;function W(){V+=4;return y[V-4>>2]}function ec(){var a=Gb[W()];if(!a)throw new L(N.Nd);return a}var fc=0,hc=0,X=0,ic=0,jc=null,kc=null,lc=!1;function mc(){for(var a=Y.length-1;0<=a;--a)nc(a);Y=[];oc=[]}var oc=[];
function pc(){if(qc&&rc.Lc)for(var a=0;a<oc.length;++a){var b=oc[a];oc.splice(a,1);--a;b.Ig.apply(this,b.wg)}}var qc=0,rc=null,Y=[];function sc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function nc(a){var b=Y[a];b.target.removeEventListener(b.Hc,b.Xd,b.Uc);Y.splice(a,1)}
function tc(a){function b(b){++qc;rc=a;pc();a.Xc(b);pc();--qc}if(a.Wc)a.Xd=b,a.target.addEventListener(a.Hc,b,a.Uc),Y.push(a),lc||(Ea.push(mc),lc=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].Hc==a.Hc&&nc(c--)}var uc={},vc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function wc(a){try{if(!a)return window;"number"===typeof a&&(a=vc[a]||D(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?m.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function xc(a){"number"===typeof a&&(a=D(a));return a&&"#canvas"!==a?"undefined"!==typeof h&&h.ad[a]?h.ad[a]:wc(a):"undefined"!==typeof h&&h.ad.canvas?h.ad.canvas:m.canvas}function ma(){return B.length}function yc(){u("OOM")}
function zc(a,b,c,d,e,f){fc||(fc=z(164));a={target:wc(a),Lc:sc()?!1:!0,Hc:f,Wc:d,Xc:function(a){a=a||window.event;var c=fc;E(a.key?a.key:"",C,c+0,32);E(a.code?a.code:"",C,c+32,32);y[c+64>>2]=a.location;y[c+68>>2]=a.ctrlKey;y[c+72>>2]=a.shiftKey;y[c+76>>2]=a.altKey;y[c+80>>2]=a.metaKey;y[c+84>>2]=a.repeat;E(a.locale?a.locale:"",C,c+88,32);E(a.char?a.char:"",C,c+120,32);y[c+152>>2]=a.charCode;y[c+156>>2]=a.keyCode;y[c+160>>2]=a.which;Ac(d,e,c,b)&&a.preventDefault()},Uc:c};tc(a)}
function Bc(a,b,c){G[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();y[a+8>>2]=b.screenX;y[a+12>>2]=b.screenY;y[a+16>>2]=b.clientX;y[a+20>>2]=b.clientY;y[a+24>>2]=b.ctrlKey;y[a+28>>2]=b.shiftKey;y[a+32>>2]=b.altKey;y[a+36>>2]=b.metaKey;wa[a+40>>1]=b.button;wa[a+42>>1]=b.buttons;y[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-jc;y[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-kc;if(m.canvas){var d=m.canvas.getBoundingClientRect();
y[a+60>>2]=b.clientX-d.left;y[a+64>>2]=b.clientY-d.top}else y[a+60>>2]=0,y[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},y[a+52>>2]=b.clientX-d.left,y[a+56>>2]=b.clientY-d.top):(y[a+52>>2]=0,y[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(jc=b.screenX,kc=b.screenY)}
function Cc(a,b,c,d,e,f){hc||(hc=z(72));a=wc(a);c={target:a,Lc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Hc:f,Wc:d,Xc:function(c){c=c||window.event;Bc(hc,c,a);Ac(d,e,hc,b)&&c.preventDefault()},Uc:c};sc()&&"mousedown"==f&&(c.Lc=!1);tc(c)}
function Dc(a,b,c,d){ic||(ic=z(36));a=wc(a);tc({target:a,Lc:!1,Hc:"resize",Wc:d,Xc:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=ic;y[l>>2]=c.detail;y[l+4>>2]=document.body.clientWidth;
y[l+8>>2]=document.body.clientHeight;y[l+12>>2]=window.innerWidth;y[l+16>>2]=window.innerHeight;y[l+20>>2]=window.outerWidth;y[l+24>>2]=window.outerHeight;y[l+28>>2]=e[0];y[l+32>>2]=e[1];Ac(d,10,l,b)&&c.preventDefault()}},Uc:c})}
function Ec(a,b,c,d,e){function f(c){c=c||window.event;Bc(X,c,a);G[X+72>>3]=c.wheelDeltaX||0;G[X+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);G[X+88>>3]=0;y[X+96>>2]=0;Ac(d,9,X,b)&&c.preventDefault()}function l(c){c=c||window.event;var e=X;Bc(e,c,a);G[e+72>>3]=c.deltaX;G[e+80>>3]=c.deltaY;G[e+88>>3]=c.deltaZ;y[e+96>>2]=c.deltaMode;Ac(d,9,e,b)&&c.preventDefault()}X||(X=z(104));tc({target:a,Lc:!0,Hc:e,Wc:d,Xc:"wheel"==e?l:f,Uc:c})}
function Fc(){if(!h.pc||!h.pc.Cc)return-3;if(!h.pc.Cc.Td)return-1;if(!h.pc.attributes.zd)return-3;h.pc.Cc.Td();return 0}
h={wd:1,Nc:0,Vc:[],Dg:{},oc:[],Cd:[],od:[],Tc:[],mc:[],vc:[],dd:[],wc:{},pc:null,ad:{},Jg:[],Sc:{},pd:{},Kd:4,$d:function(){h.Gd=new Float32Array(h.zc);for(var a=0;a<h.zc;a++)h.Ec[a]=h.Gd.subarray(0,a+1)},lc:function(a){h.Nc||(h.Nc=a)},Mc:function(a){for(var b=h.wd++,c=a.length;c<b;c++)a[c]=null;return b},zc:256,Gd:null,Ec:[0],Zd:function(a,b,c,d){a="";for(var e=0;e<b;++e){var f=d?y[d+4*e>>2]:-1;a+=D(y[c+4*e>>2],0>f?void 0:f)}return a},createContext:function(a,b){return(a=a.getContext("webgl",b)||
a.getContext("experimental-webgl",b))&&h.ie(a,b)},ie:function(a,b){var c=z(8),d={handle:c,attributes:b,version:b.de,Cc:a};a.canvas&&(a.canvas.Rd=d);h.wc[c]=d;("undefined"===typeof b.xd||b.xd)&&h.ae(d);return c},ee:function(a){h.pc=h.wc[a];m.xg=k=h.pc&&h.pc.Cc;return!(a&&!k)},getContext:function(a){return h.wc[a]},Wd:function(a){h.pc===h.wc[a]&&(h.pc=null);if("object"===typeof uc)for(var b=h.wc[a].Cc.canvas,c=0;c<Y.length;++c)Y[c].target!=b||nc(c--);h.wc[a]&&h.wc[a].Cc.canvas&&(h.wc[a].Cc.canvas.Rd=
void 0);Gc(h.wc[a]);h.wc[a]=null},ae:function(a){a||(a=h.pc);if(!a.be){a.be=!0;var b=a.Cc;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.yg=b.getExtension("EXT_disjoint_timer_query");var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}},he:function(a){var b=h.oc[a];a=h.Sc[a]={mc:{},kd:0,Oc:-1,Pc:-1};for(var c=a.mc,d=k.getProgramParameter(b,35718),e=0;e<d;++e){var f=k.getActiveUniform(b,e),l=f.name;a.kd=Math.max(a.kd,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var r=k.getUniformLocation(b,l);if(r){var v=h.Mc(h.mc);c[l]=[f.size,v];h.mc[v]=r;for(var x=1;x<f.size;++x)r=k.getUniformLocation(b,
l+"["+x+"]"),v=h.Mc(h.mc),h.mc[v]=r}}}};var Hc=["default","low-power","high-performance"];function Ic(a){return h.ee(a)?0:-5}m._emscripten_webgl_make_context_current=Ic;function Jc(a){if(0===a)return 0;a=D(a);if(!J.hasOwnProperty(a))return 0;Jc.qc&&Gc(Jc.qc);a=J[a];var b=ta(a)+1,c=z(b);c&&E(a,B,c,b);Jc.qc=c;return Jc.qc}var Kc=[];function Lc(a,b,c,d){for(var e=0;e<a;e++){var f=k[c](),l=f&&h.Mc(d);f?(f.name=l,d[l]=f):h.lc(1282);y[b+4*e>>2]=l}}
function Mc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&h.lc(1280);return;case 36345:d=0;break;case 34466:var e=k.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=k.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":h.lc(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:h.lc(1280);return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":y[b+4*a>>2]=e[a];break;case "Float":F[b+4*a>>2]=e[a];break;case "Boolean":B[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=e.name|0}catch(f){h.lc(1280);w("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:h.lc(1280);return}switch(c){case "Integer64":aa=
[d>>>0,(g=d,1<=+Oa(g)?0<g?(Ra(+Qa(g/4294967296),4294967295)|0)>>>0:~~+Pa((g-+(~~g>>>0))/4294967296)>>>0:0)];y[b>>2]=aa[0];y[b+4>>2]=aa[1];break;case "Integer":y[b>>2]=d;break;case "Float":F[b>>2]=d;break;case "Boolean":B[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else h.lc(1281)}function Nc(a){var b=ta(a)+1,c=z(b);E(a,C,c,b);return c}var Oc={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Pc={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Qc(a,b,c,d,e){if(b=Oc[b]*Pc[a]){var f=h.Kd;c=e+d*(c*b+f-1&-f);switch(a){case 5121:return C.subarray(e,c);case 5126:return F.subarray(e>>2,c>>2);case 5125:case 34042:return ya.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return xa.subarray(e>>1,c>>1);default:h.lc(1280)}}else h.lc(1280)}function Z(){Z.qc||(Z.qc=[]);Z.qc.push(Rc());return Z.qc.length-1}function Sc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Tc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Uc=[31,29,31,30,31,30,31,31,30,31,30,31],Vc=[31,28,31,30,31,30,31,31,30,31,30,31];function Wc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Sc(a.getFullYear())?Uc:Vc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Xc(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function v(a){a=Wc(new Date(a.nc+1900,0,1),a.cd);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=l(r(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var x=y[d+40>>2];d={oe:y[d>>2],ne:y[d+4>>2],bd:y[d+8>>2],Ic:y[d+12>>2],Fc:y[d+16>>2],nc:y[d+20>>2],Jd:y[d+24>>2],cd:y[d+28>>2],Kg:y[d+32>>2],me:y[d+36>>2],
pe:x?D(x):""};c=D(c);x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var A in x)c=c.replace(new RegExp(A,"g"),x[A]);var R="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),M="January February March April May June July August September October November December".split(" ");x={"%a":function(a){return R[a.Jd].substring(0,3)},"%A":function(a){return R[a.Jd]},"%b":function(a){return M[a.Fc].substring(0,
3)},"%B":function(a){return M[a.Fc]},"%C":function(a){return f((a.nc+1900)/100|0,2)},"%d":function(a){return f(a.Ic,2)},"%e":function(a){return e(a.Ic,2," ")},"%g":function(a){return v(a).toString().substring(2)},"%G":function(a){return v(a)},"%H":function(a){return f(a.bd,2)},"%I":function(a){a=a.bd;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Ic+Tc(Sc(a.nc+1900)?Uc:Vc,a.Fc-1),3)},"%m":function(a){return f(a.Fc+1,2)},"%M":function(a){return f(a.ne,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.bd&&12>a.bd?"AM":"PM"},"%S":function(a){return f(a.oe,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.nc+1900,a.Fc+1,a.Ic,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.nc+1900,0,1),c=0===b.getDay()?b:Wc(b,7-b.getDay());a=new Date(a.nc+1900,a.Fc,a.Ic);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Tc(Sc(a.getFullYear())?Uc:Vc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.nc+1900,0,4)),c=r(new Date(a.nc+
1901,0,4)),d=Wc(new Date(a.nc+1900,0,1),a.cd);return 0>l(d,b)?"53":0>=l(c,d)?"01":f(Math.ceil((b.getFullYear()<a.nc+1900?a.cd+32-b.getDate():a.cd+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.nc+1900,a.Fc+1,a.Ic,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.nc,0,1),c=1===b.getDay()?b:Wc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.nc+1900,a.Fc,a.Ic);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Tc(Sc(a.getFullYear())?Uc:Vc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":
"00"},"%y":function(a){return(a.nc+1900).toString().substring(2)},"%Y":function(a){return a.nc+1900},"%z":function(a){a=a.me;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.pe},"%%":function(){return"%"}};for(A in x)0<=c.indexOf(A)&&(c=c.replace(new RegExp(A,"g"),x[A](d)));A=Za(c,!1);if(A.length>b)return 0;B.set(A,a);return A.length-1}Ja();Ib=Array(4096);Xb(O,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");vb(259,{read:function(){return 0},write:function(a,b,c,l){return l}});Zb("/dev/null",259);ub(1280,xb);ub(1536,yb);Zb("/dev/tty",1280);Zb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(q)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});Ka("random",b);Ka("urandom",b);T("/dev/shm");
T("/dev/shm/tmp")})();T("/proc");T("/proc/self");T("/proc/self/fd");Xb({rc:function(){var a=Ab("/proc/self","fd",16895,73);a.jc={lookup:function(a,c){var b=Gb[+c];if(!b)throw new L(9);a={parent:null,rc:{Id:"fake"},jc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(q){var fs=require("fs"),Db=require("path");P.le()}h.$d();for(var Yc=0;32>Yc;Yc++)Kc.push(Array(Yc));function Za(a,b){var c=Array(ta(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var bd=m.asm({},{e:u,rb:kb,d:function(a){return z(a)},Ja:function(){pa=!0;throw"Pure virtual function called!";},c:function(a){"uncaught_exception"in Zc?Zc.Fd++:Zc.Fd=1;throw a;},sa:function(){return!!Zc.Fd},k:function(){},$:function(){lb(1);return-1},u:lb,s:function(a,b){V=b;try{var c=ec();W();var d=W(),e=W(),f=W();ac(c,d,f);y[e>>2]=c.position;c.jd&&0===d&&0===f&&(c.jd=null);return 0}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.Ac}},qb:function(a,b){V=b;try{var c=ec(),d=W();a:{var e=
W();for(b=a=0;b<e;b++){var f=y[d+(8*b+4)>>2],l=c,r=y[d+8*b>>2],v=f,x=void 0,A=B;if(0>v||0>x)throw new L(22);if(null===l.fd)throw new L(9);if(1===(l.flags&2097155))throw new L(9);if(16384===(l.node.mode&61440))throw new L(21);if(!l.ic.read)throw new L(22);var R="undefined"!==typeof x;if(!R)x=l.position;else if(!l.seekable)throw new L(29);var M=l.ic.read(l,A,r,v,x);R||(l.position+=M);var ea=M;if(0>ea){var S=-1;break a}a+=ea;if(ea<f)break}S=a}return S}catch(qb){return"undefined"!==typeof U&&qb instanceof
L||u(qb),-qb.Ac}},A:function(a,b){V=b;try{var c=ec(),d=W();a:{var e=W();for(b=a=0;b<e;b++){var f=c,l=y[d+8*b>>2],r=y[d+(8*b+4)>>2],v=void 0,x=B;if(0>r||0>v)throw new L(22);if(null===f.fd)throw new L(9);if(0===(f.flags&2097155))throw new L(9);if(16384===(f.node.mode&61440))throw new L(21);if(!f.ic.write)throw new L(22);f.flags&1024&&ac(f,0,2);var A="undefined"!==typeof v;if(!A)v=f.position;else if(!f.seekable)throw new L(29);var R=f.ic.write(f,x,l,r,v,void 0);A||(f.position+=R);try{if(f.path&&Kb.onWriteToFile)Kb.onWriteToFile(f.path)}catch(S){console.log("FS.trackingDelegate['onWriteToFile']('"+
f.path+"') threw an exception: "+S.message)}var M=R;if(0>M){var ea=-1;break a}a+=M}ea=a}return ea}catch(S){return"undefined"!==typeof U&&S instanceof L||u(S),-S.Ac}},m:function(a,b){V=b;try{var c=ec();switch(W()){case 0:var d=W();return 0>d?-N.tc:Ma(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=W(),c.flags|=d,0;case 12:return d=W(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-N.tc;case 9:return lb(N.tc),-1;default:return-N.tc}}catch(e){return"undefined"!==
typeof U&&e instanceof L||u(e),-e.Ac}},Va:function(a,b){V=b;try{var c=D(W());var d=W();if(d&-8)var e=-N.tc;else{var f=Q(c,{hd:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Pb(f,a)?-N.Ld:0}return e}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.Ac}},Ua:function(a,b){V=b;try{var c=D(W()),d=W(),e=W();return Ma(c,d,e).fd}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.Ac}},z:function(a,b){V=b;try{var c=ec(),d=W();switch(d){case 21509:case 21505:return c.tty?
0:-N.Jc;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-N.Jc;case 21519:if(!c.tty)return-N.Jc;var e=W();return y[e>>2]=0;case 21520:return c.tty?-N.tc:-N.Jc;case 21531:a=e=W();if(!c.ic.ce)throw new L(25);return c.ic.ce(c,d,a);case 21523:return c.tty?0:-N.Jc;case 21524:return c.tty?0:-N.Jc;default:u("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.Ac}},y:function(a,b){V=b;try{var c=ec();if(null===c.fd)throw new L(9);c.jd&&(c.jd=
null);try{c.ic.close&&c.ic.close(c)}catch(d){throw d;}finally{Gb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.Ac}},Ta:function(a,b){V=b;try{var c=W(),d=W(),e=dc[c];if(!e)return 0;if(d===e.Bg){var f=Gb[e.fd],l=e.flags,r=new Uint8Array(C.subarray(c,c+d));f&&f.ic.$c&&f.ic.$c(f,r,0,d,l);dc[c]=null;e.Sd&&Gc(e.Cg)}return 0}catch(v){return"undefined"!==typeof U&&v instanceof L||u(v),-v.Ac}},i:function(){},b:function(){m.abort()},Sa:function(a){return $a[a]()},
Ra:function(a,b){return $a[a](b)},Qa:function(a,b,c){return $a[a](b,c)},Pa:function(a,b,c){a=xc(a);if(!a)return-4;y[b>>2]=a.width;y[c>>2]=a.height},Oa:function(){return window.devicePixelRatio||1},Na:function(a,b,c){a=a?wc(a):m.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),G[b>>3]=a.right-a.left,G[c>>3]=a.bottom-a.top):(G[b>>3]=a.clientWidth,G[c>>3]=a.clientHeight);return 0},Ma:ma,La:function(a,b,c){C.set(C.subarray(b,b+c),a)},Ka:function(a){yc(a)},q:function(a,b,c){a=
xc(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ia:function(a,b,c,d){zc(a,b,c,d,2,"keydown");return 0},Ha:function(a,b,c,d){zc(a,b,c,d,3,"keyup");return 0},Ga:function(a,b,c,d){Cc(a,b,c,d,5,"mousedown");return 0},Fa:function(a,b,c,d){Cc(a,b,c,d,8,"mousemove");return 0},Ea:function(a,b,c,d){Cc(a,b,c,d,6,"mouseup");return 0},Da:function(a,b,c,d){Dc(a,b,c,d);return 0},Ca:function(a,b,c,d){a=wc(a);return"undefined"!==typeof a.onwheel?(Ec(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Ec(a,
b,c,d,"mousewheel"),0):-1},Ba:function(){return Fc()},Aa:function(a,b){var c={};b>>=2;c.alpha=!!y[b];c.depth=!!y[b+1];c.stencil=!!y[b+2];c.antialias=!!y[b+3];c.premultipliedAlpha=!!y[b+4];c.preserveDrawingBuffer=!!y[b+5];c.powerPreference=Hc[y[b+6]];c.failIfMajorPerformanceCaveat=!!y[b+7];c.de=y[b+8];c.Eg=y[b+9];c.xd=y[b+10];c.zd=y[b+11];c.Fg=y[b+12];c.Hg=y[b+13];a=xc(a);return!a||c.zd?0:h.createContext(a,c)},za:function(a){h.pc==a&&(h.pc=0);h.Wd(a)},ya:function(a){a>>=2;for(var b=0;14>b;++b)y[a+
b]=0;y[a]=y[a+1]=y[a+3]=y[a+4]=y[a+8]=y[a+10]=1},xa:Ic,l:function(a){$c(a)},h:Jc,p:function(a){k.activeTexture(a)},wa:function(a,b){k.attachShader(h.oc[a],h.vc[b])},va:function(a,b,c){k.bindAttribLocation(h.oc[a],b,D(c))},x:function(a,b){k.bindBuffer(a,h.Vc[b])},ua:function(a,b){k.bindFramebuffer(a,h.Cd[b])},ta:function(a,b){k.bindRenderbuffer(a,h.od[b])},o:function(a,b){k.bindTexture(a,h.Tc[b])},ra:function(a){k.bindVertexArray(h.dd[a])},qa:function(a,b,c,d){k.bufferData(a,c?C.subarray(c,c+b):b,
d)},pa:function(a,b,c,d){k.bufferSubData(a,b,C.subarray(d,d+c))},oa:function(a){return k.checkFramebufferStatus(a)},na:function(a){k.clear(a)},ma:function(a,b,c,d){k.clearColor(a,b,c,d)},la:function(a){k.clearDepth(a)},ka:function(a){k.compileShader(h.vc[a])},w:function(a,b,c,d,e,f,l,r,v){k.compressedTexSubImage2D(a,b,c,d,e,f,l,v?C.subarray(v,v+r):null)},ja:function(a,b,c,d,e,f,l,r){k.copyTexSubImage2D(a,b,c,d,e,f,l,r)},ia:function(){var a=h.Mc(h.oc),b=k.createProgram();b.name=a;h.oc[a]=b;return a},
ha:function(a){var b=h.Mc(h.vc);h.vc[b]=k.createShader(a);return b},ga:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=h.Vc[d];e&&(k.deleteBuffer(e),e.name=0,h.Vc[d]=null,d==h.Ud&&(h.Ud=0),d==h.Vd&&(h.Vd=0))}},fa:function(a){if(a){var b=h.oc[a];b?(k.deleteProgram(b),b.name=0,h.oc[a]=null,h.Sc[a]=null):h.lc(1281)}},ea:function(a){if(a){var b=h.vc[a];b?(k.deleteShader(b),h.vc[a]=null):h.lc(1281)}},da:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=h.Tc[d];e&&(k.deleteTexture(e),e.name=
0,h.Tc[d]=null)}},ca:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];k.deleteVertexArray(h.dd[d]);h.dd[d]=null}},ba:function(a){k.disableVertexAttribArray(a)},aa:function(a,b,c){k.drawArrays(a,b,c)},_:function(a,b,c,d){k.drawArraysInstanced(a,b,c,d)},Z:function(a,b){for(var c=Kc[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];k.drawBuffers(c)},Y:function(a,b,c,d){k.drawElements(a,b,c,d)},X:function(a,b,c,d,e){k.drawElementsInstanced(a,b,c,d,e)},v:function(a){k.enable(a)},W:function(a){k.enableVertexAttribArray(a)},
V:function(a,b,c,d){k.framebufferRenderbuffer(a,b,c,h.od[d])},U:function(a,b,c,d,e){k.framebufferTexture2D(a,b,c,h.Tc[d],e)},T:function(a,b){Lc(a,b,"createBuffer",h.Vc)},S:function(a,b){Lc(a,b,"createFramebuffer",h.Cd)},R:function(a,b){Lc(a,b,"createRenderbuffer",h.od)},Q:function(a,b){Lc(a,b,"createTexture",h.Tc)},P:function(a,b){Lc(a,b,"createVertexArray",h.dd)},O:function(a){k.generateMipmap(a)},N:function(a,b,c){c?y[c>>2]=k.getBufferParameter(a,b):h.lc(1281)},M:function(){if(h.Nc){var a=h.Nc;
h.Nc=0;return a}return k.getError()},L:function(a,b){Mc(a,b,"Float")},n:function(a,b){Mc(a,b,"Integer")},K:function(a,b,c,d){a=k.getProgramInfoLog(h.oc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},t:function(a,b,c){if(c)if(a>=h.wd)h.lc(1281);else{var d=h.Sc[a];if(d)if(35716==b)a=k.getProgramInfoLog(h.oc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b)y[c>>2]=d.kd;else if(35722==b){if(-1==d.Oc){a=h.oc[a];var e=k.getProgramParameter(a,
35721);for(b=d.Oc=0;b<e;++b)d.Oc=Math.max(d.Oc,k.getActiveAttrib(a,b).name.length+1)}y[c>>2]=d.Oc}else if(35381==b){if(-1==d.Pc)for(a=h.oc[a],e=k.getProgramParameter(a,35382),b=d.Pc=0;b<e;++b)d.Pc=Math.max(d.Pc,k.getActiveUniformBlockName(a,b).length+1);y[c>>2]=d.Pc}else y[c>>2]=k.getProgramParameter(h.oc[a],b);else h.lc(1282)}else h.lc(1281)},J:function(a,b,c,d){a=k.getShaderInfoLog(h.vc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},r:function(a,b,c){c?
35716==b?(a=k.getShaderInfoLog(h.vc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1):35720==b?(a=k.getShaderSource(h.vc[a]),y[c>>2]=null===a||0==a.length?0:a.length+1):y[c>>2]=k.getShaderParameter(h.vc[a],b):h.lc(1281)},j:function(a){if(h.pd[a])return h.pd[a];switch(a){case 7939:var b=k.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Nc(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=k.getParameter(a))||h.lc(1280);b=Nc(b);break;case 7938:b=
Nc("OpenGL ES 2.0 ("+k.getParameter(k.VERSION)+")");break;case 35724:b=k.getParameter(k.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Nc(b);break;default:return h.lc(1280),0}return h.pd[a]=b},I:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=h.Sc[a]&&h.Sc[a].mc[b])&&0<=c&&c<a[0]?a[1]+c:-1},
H:function(a){k.linkProgram(h.oc[a]);h.he(a)},G:function(a,b){3317==a&&(h.Kd=b);k.pixelStorei(a,b)},F:function(a,b,c,d,e,f,l){(l=Qc(f,e,c,d,l))?k.readPixels(a,b,c,d,e,f,l):h.lc(1280)},E:function(a,b,c,d){k.renderbufferStorage(a,b,c,d)},D:function(a,b,c,d){b=h.Zd(a,b,c,d);k.shaderSource(h.vc[a],b)},C:function(a,b,c,d,e,f,l,r,v){k.texImage2D(a,b,c,d,e,f,l,r,v?Qc(r,l,d,e,v):null)},pb:function(a,b,c){k.texParameterf(a,b,c)},ob:function(a,b,c){k.texParameterf(a,b,F[c>>2])},nb:function(a,b,c){k.texParameteri(a,
b,c)},B:function(a,b,c,d,e,f,l,r,v){var x=null;v&&(x=Qc(r,l,e,f,v));k.texSubImage2D(a,b,c,d,e,f,l,r,x)},mb:function(a,b,c){if(b<=h.zc)for(var d=h.Ec[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);k.uniform1fv(h.mc[a],d)},lb:function(a,b,c){k.uniform1iv(h.mc[a],y.subarray(c>>2,c+4*b>>2))},kb:function(a,b,c){if(2*b<=h.zc)for(var d=h.Ec[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);k.uniform2fv(h.mc[a],d)},jb:function(a,b,c){k.uniform2iv(h.mc[a],
y.subarray(c>>2,c+8*b>>2))},ib:function(a,b,c){if(3*b<=h.zc)for(var d=h.Ec[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);k.uniform3fv(h.mc[a],d)},hb:function(a,b,c){k.uniform3iv(h.mc[a],y.subarray(c>>2,c+12*b>>2))},gb:function(a,b,c){if(4*b<=h.zc)for(var d=h.Ec[4*b-1],e=0;e<4*b;e+=4)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2],d[e+3]=F[c+(4*e+12)>>2];else d=F.subarray(c>>2,c+16*b>>2);k.uniform4fv(h.mc[a],d)},
fb:function(a,b,c){k.uniform4iv(h.mc[a],y.subarray(c>>2,c+16*b>>2))},eb:function(a,b,c,d){if(4*b<=h.zc)for(var e=h.Ec[4*b-1],f=0;f<4*b;f+=4)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);k.uniformMatrix2fv(h.mc[a],!!c,e)},db:function(a,b,c,d){if(9*b<=h.zc)for(var e=h.Ec[9*b-1],f=0;f<9*b;f+=9)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],
e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);k.uniformMatrix3fv(h.mc[a],!!c,e)},cb:function(a,b,c,d){if(16*b<=h.zc)for(var e=h.Ec[16*b-1],f=0;f<16*b;f+=16)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2],e[f+9]=F[d+(4*f+36)>>2],e[f+10]=F[d+(4*f+40)>>2],e[f+11]=F[d+(4*f+44)>>2],e[f+
12]=F[d+(4*f+48)>>2],e[f+13]=F[d+(4*f+52)>>2],e[f+14]=F[d+(4*f+56)>>2],e[f+15]=F[d+(4*f+60)>>2];else e=F.subarray(d>>2,d+64*b>>2);k.uniformMatrix4fv(h.mc[a],!!c,e)},bb:function(a){k.useProgram(h.oc[a])},ab:function(a,b){k.vertexAttribDivisor(a,b)},$a:function(a,b,c,d,e,f){k.vertexAttribPointer(a,b,c,!!d,e,f)},_a:function(a,b,c,d){k.viewport(a,b,c,d)},g:function(a){var b=Z.qc[a];Z.qc.splice(a,1);ad(b)},f:Z,Za:function(){u("trap!")},Ya:function(){return 0},Xa:function(a,b,c,d){return Xc(a,b,c,d)},Wa:yc,
a:la},buffer);m.asm=bd;
var fb=m.__GLOBAL__sub_I_OpenGexImporter_cpp=function(){return m.asm.sb.apply(null,arguments)},db=m.__GLOBAL__sub_I_driverSpecific_cpp=function(){return m.asm.tb.apply(null,arguments)},bb=m.__GLOBAL__sub_I_importStaticPlugin_cpp=function(){return m.asm.ub.apply(null,arguments)},cb=m.__GLOBAL__sub_I_importStaticPlugin_cpp_21=function(){return m.asm.vb.apply(null,arguments)},jb=m.__GLOBAL__sub_I_iostream_cpp=function(){return m.asm.wb.apply(null,arguments)},hb=m.__GLOBAL__sub_I_resource_AnyImageImporter_cpp=function(){return m.asm.xb.apply(null,
arguments)},eb=m.__GLOBAL__sub_I_resource_MagnumShaders_RCS_cpp=function(){return m.asm.yb.apply(null,arguments)},gb=m.__GLOBAL__sub_I_resource_OpenGexImporter_cpp=function(){return m.asm.zb.apply(null,arguments)},ab=m.__GLOBAL__sub_I_resource_Viewer_RESOURCES_cpp=function(){return m.asm.Ab.apply(null,arguments)},Zc=m.__ZSt18uncaught_exceptionv=function(){return m.asm.Bb.apply(null,arguments)},ib=m.___emscripten_environ_constructor=function(){return m.asm.Cb.apply(null,arguments)};
m.___errno_location=function(){return m.asm.Db.apply(null,arguments)};var Gc=m._free=function(){return m.asm.Eb.apply(null,arguments)};m._main=function(){return m.asm.Fb.apply(null,arguments)};var z=m._malloc=function(){return m.asm.Gb.apply(null,arguments)},va=m.stackAlloc=function(){return m.asm.ec.apply(null,arguments)},ad=m.stackRestore=function(){return m.asm.fc.apply(null,arguments)},Rc=m.stackSave=function(){return m.asm.gc.apply(null,arguments)};
m.dynCall_ii=function(){return m.asm.Hb.apply(null,arguments)};m.dynCall_iii=function(){return m.asm.Ib.apply(null,arguments)};var Ac=m.dynCall_iiii=function(){return m.asm.Jb.apply(null,arguments)};m.dynCall_iiiii=function(){return m.asm.Kb.apply(null,arguments)};m.dynCall_iiiiid=function(){return m.asm.Lb.apply(null,arguments)};m.dynCall_iiiiii=function(){return m.asm.Mb.apply(null,arguments)};m.dynCall_iiiiiid=function(){return m.asm.Nb.apply(null,arguments)};
m.dynCall_iiiiiii=function(){return m.asm.Ob.apply(null,arguments)};m.dynCall_iiiiiiii=function(){return m.asm.Pb.apply(null,arguments)};m.dynCall_iiiiiiiii=function(){return m.asm.Qb.apply(null,arguments)};m.dynCall_iiiiij=function(){return m.asm.Rb.apply(null,arguments)};m.dynCall_v=function(){return m.asm.Sb.apply(null,arguments)};m.dynCall_vf=function(){return m.asm.Tb.apply(null,arguments)};m.dynCall_vi=function(){return m.asm.Ub.apply(null,arguments)};
m.dynCall_vif=function(){return m.asm.Vb.apply(null,arguments)};m.dynCall_vii=function(){return m.asm.Wb.apply(null,arguments)};m.dynCall_viif=function(){return m.asm.Xb.apply(null,arguments)};m.dynCall_viii=function(){return m.asm.Yb.apply(null,arguments)};m.dynCall_viiii=function(){return m.asm.Zb.apply(null,arguments)};m.dynCall_viiiii=function(){return m.asm._b.apply(null,arguments)};m.dynCall_viiiiii=function(){return m.asm.$b.apply(null,arguments)};
m.dynCall_viiiiiii=function(){return m.asm.ac.apply(null,arguments)};m.dynCall_viiiiiiii=function(){return m.asm.bc.apply(null,arguments)};m.dynCall_viiiiiiiii=function(){return m.asm.cc.apply(null,arguments)};m.dynCall_viijii=function(){return m.asm.dc.apply(null,arguments)};m.asm=bd;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ia.prototype=Error();ia.prototype.constructor=ia;Ta=function cd(){m.calledRun||dd();m.calledRun||(Ta=cd)};
m.callMain=function(a){a=a||[];Ha();var b=a.length+1,c=va(4*(b+1));y[c>>2]=ua(m.thisProgram);for(var d=1;d<b;d++)y[(c>>2)+d]=ua(a[d-1]);y[(c>>2)+b]=0;try{var e=m._main(b,c,0);$c(e,!0)}catch(f){f instanceof ia||("SimulateInfiniteLoop"==f?m.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),w("exception thrown: "+a),m.quit(1,f)))}finally{}};
function dd(a){function b(){if(!m.calledRun&&(m.calledRun=!0,!pa)){Ha();Jb=!1;Aa(Da);if(m.onRuntimeInitialized)m.onRuntimeInitialized();m._main&&ed&&m.callMain(a);if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();Fa.unshift(b)}Aa(Fa)}}a=a||m.arguments;if(!(0<H)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Na();Aa(Ba);0<H||m.calledRun||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},
1);b()},1)):b())}}m.run=dd;function $c(a,b){if(!b||!m.noExitRuntime||0!==a){if(!m.noExitRuntime&&(pa=!0,m.onExit))m.onExit(a);m.quit(a,new ia(a))}}function u(a){if(m.onAbort)m.onAbort(a);void 0!==a?(ja(a),w(a),a=JSON.stringify(a)):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}m.abort=u;if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();var ed=!0;m.noInitialRun&&(ed=!1);m.noExitRuntime=!0;dd();
