var aa,g;var h,k;var m;m||(m=typeof Module !== 'undefined' ? Module : {});var ba={},n;for(n in m)m.hasOwnProperty(n)&&(ba[n]=m[n]);m.arguments=[];m.thisProgram="./this.program";m.quit=function(a,b){throw b;};m.preRun=[];m.postRun=[];var ca=!1,p=!1,q=!1,da=!1;ca="object"===typeof window;p="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!ca&&!p;da=!ca&&!q&&!p;var t="";
if(q){t=__dirname+"/";var fa,ha;m.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};m.readBinary=function(a){a=m.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(m.thisProgram=process.argv[1].replace(/\\/g,"/"));m.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=m);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",
u);m.quit=function(a){process.exit(a)};m.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(m.read=function(a){return read(a)}),m.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?m.arguments=scriptArgs:"undefined"!=typeof arguments&&(m.arguments=arguments),"function"===typeof quit&&(m.quit=function(a){quit(a)});else if(ca||p)p?
t=self.location.href:document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?t.substr(0,t.lastIndexOf("/")+1):"",m.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(m.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),m.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},m.setWindowTitle=function(a){document.title=a};var ja=m.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),w=m.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ja);for(n in ba)ba.hasOwnProperty(n)&&(m[n]=ba[n]);ba=void 0;function ka(a){var b=y[la>>2];a=b+a+15&-16;if(a<=ma())y[la>>2]=a;else return 0;return b}
var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&w("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||u("Assertion failed: "+b)}function qa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=z(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)y[a>>2]=0;for(b=d+c;a<b;)B[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}
var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?sa(C,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var r=a.charCodeAt(++f);l=65536+((l&1023)<<10)|r&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ua(a){var b=ta(a)+1,c=va(b);E(a,B,c,b);return c}var buffer,B,C,wa,xa,y,ya,F,G,la=91072,za=m.TOTAL_MEMORY||16777216;5242880>za&&w("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+za+"! (TOTAL_STACK=5242880)");
m.buffer?buffer=m.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(oa=new WebAssembly.Memory({initial:za/65536,maximum:za/65536}),buffer=oa.buffer):buffer=new ArrayBuffer(za);m.HEAP8=B=new Int8Array(buffer);m.HEAP16=wa=new Int16Array(buffer);m.HEAP32=y=new Int32Array(buffer);m.HEAPU8=C=new Uint8Array(buffer);m.HEAPU16=xa=new Uint16Array(buffer);m.HEAPU32=ya=new Uint32Array(buffer);m.HEAPF32=F=new Float32Array(buffer);m.HEAPF64=G=new Float64Array(buffer);y[la>>2]=5334208;
function Aa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Hc;"number"===typeof c?void 0===b.cd?m.dynCall_v(c):m.dynCall_vi(c,b.cd):c(void 0===b.cd?null:b.cd)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[],Ga=!1;
function Ha(){Ga||(Ga=!0,m.noFSInit||Ia||(Ia=!0,Ja(),m.stdin=m.stdin,m.stdout=m.stdout,m.stderr=m.stderr,m.stdin?Ka("stdin",m.stdin):La("/dev/tty","/dev/stdin"),m.stdout?Ka("stdout",null,m.stdout):La("/dev/tty","/dev/stdout"),m.stderr?Ka("stderr",null,m.stderr):La("/dev/tty1","/dev/stderr"),Ma("/dev/stdin","r"),Ma("/dev/stdout","w"),Ma("/dev/stderr","w")),Aa(Ca))}function Na(){var a=m.preRun.shift();Ba.unshift(a)}
var Oa=Math.abs,Pa=Math.cos,Qa=Math.sin,Ra=Math.ceil,Sa=Math.floor,Ta=Math.min,H=0,Ua=null,Va=null;m.preloadedImages={};m.preloadedAudios={};function Wa(){var a=I;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var I="magnum-box2d.wasm";if(!Wa()){var Xa=I;I=m.locateFile?m.locateFile(Xa,t):t+Xa}
function Ya(){try{if(m.wasmBinary)return new Uint8Array(m.wasmBinary);if(m.readBinary)return m.readBinary(I);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}function Za(){return m.wasmBinary||!ca&&!p||"function"!==typeof fetch?new Promise(function(a){a(Ya())}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Ya()})}
function $a(a){function b(a){m.asm=a.exports;H--;m.monitorRunDependencies&&m.monitorRunDependencies(H);0==H&&(null!==Ua&&(clearInterval(Ua),Ua=null),Va&&(a=Va,Va=null,a()))}function c(a){b(a.instance)}function d(a){Za().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){w("failed to asynchronously prepare wasm: "+a);u(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};H++;m.monitorRunDependencies&&m.monitorRunDependencies(H);if(m.instantiateWasm)try{return m.instantiateWasm(e,
b)}catch(f){return w("Module.instantiateWasm callback failed with error: "+f),!1}m.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Wa()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(I,{credentials:"same-origin"}),e).then(c,function(a){w("wasm streaming compile failed: "+a);w("falling back to ArrayBuffer instantiation");d(c)});return{}}
m.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:876,maximum:876,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return $a(b)};
var bb=[function(){var a=m.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?qa(ab(a.id)):0},function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?m.dynCall_ii.apply(null,[a].concat(e)):m.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},function(a){a=D(a);return"undefined"!==typeof process&&a in process.env?qa(ab(process.env[a])):0}];
Ca.push({Hc:function(){cb()}},{Hc:function(){db()}},{Hc:function(){eb()}},{Hc:function(){fb()}},{Hc:function(){gb()}},{Hc:function(){hb()}});var J={};
function ib(a){if(ib.oc){var b=y[a>>2];var c=y[b>>2]}else ib.oc=!0,J.USER=J.LOGNAME="web_user",J.PATH="/",J.PWD="/",J.HOME="/home/web_user",J.LANG="C.UTF-8",J._=m.thisProgram,c=Ga?z(1024):ka(1024),b=Ga?z(256):ka(256),y[b>>2]=c,y[a>>2]=b;a=[];var d=0,e;for(e in J)if("string"===typeof J[e]){var f=e+"="+J[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var l=c,r=0;r<d.length;++r)B[l++>>0]=d.charCodeAt(r);B[l>>0]=0;y[b+4*
e>>2]=c;c+=f.length+1}y[b+4*a.length>>2]=0}function jb(a){m.___errno_location&&(y[m.___errno_location()>>2]=a);return a}function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function lb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function mb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function nb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function ob(){var a=Array.prototype.slice.call(arguments,0);return lb(a.join("/"))}function K(a,b){return lb(a+"/"+b)}
function pb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var rb=[];function sb(a,b){rb[a]={input:[],output:[],Ic:b};tb(a,ub)}
var ub={open:function(a){var b=rb[a.node.rdev];if(!b)throw new L(N.bd);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ic.flush(a.tty)},flush:function(a){a.tty.Ic.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ic.Dd)throw new L(N.qd);for(var e=0,f=0;f<d;f++){try{var l=a.tty.Ic.Dd(a.tty)}catch(r){throw new L(N.od);}if(void 0===l&&0===e)throw new L(N.Kd);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ic.jd)throw new L(N.qd);
try{for(var e=0;e<d;e++)a.tty.Ic.jd(a.tty,b[c+e])}catch(f){throw new L(N.od);}d&&(a.node.timestamp=Date.now());return e}},vb={Dd:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ab(b,!0)}return a.input.shift()},jd:function(a,b){null===b||10===b?(ja(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(sa(a.output,0)),a.output=[])}},wb={jd:function(a,b){null===b||10===b?(w(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(w(sa(a.output,0)),a.output=[])}},O={vc:null,pc:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(N.Od);O.vc||(O.vc={dir:{node:{yc:O.hc.yc,sc:O.hc.sc,lookup:O.hc.lookup,Oc:O.hc.Oc,rename:O.hc.rename,unlink:O.hc.unlink,rmdir:O.hc.rmdir,readdir:O.hc.readdir,symlink:O.hc.symlink},stream:{Ac:O.fc.Ac}},file:{node:{yc:O.hc.yc,sc:O.hc.sc},stream:{Ac:O.fc.Ac,read:O.fc.read,write:O.fc.write,rd:O.fc.rd,Fd:O.fc.Fd,
Xc:O.fc.Xc}},link:{node:{yc:O.hc.yc,sc:O.hc.sc,readlink:O.hc.readlink},stream:{}},td:{node:{yc:O.hc.yc,sc:O.hc.sc},stream:xb}});c=yb(a,b,c,d);16384===(c.mode&61440)?(c.hc=O.vc.dir.node,c.fc=O.vc.dir.stream,c.ec={}):32768===(c.mode&61440)?(c.hc=O.vc.file.node,c.fc=O.vc.file.stream,c.ic=0,c.ec=null):40960===(c.mode&61440)?(c.hc=O.vc.link.node,c.fc=O.vc.link.stream):8192===(c.mode&61440)&&(c.hc=O.vc.td.node,c.fc=O.vc.td.stream);c.timestamp=Date.now();a&&(a.ec[b]=c);return c},xg:function(a){if(a.ec&&
a.ec.subarray){for(var b=[],c=0;c<a.ic;++c)b.push(a.ec[c]);return b}return a.ec},yg:function(a){return a.ec?a.ec.subarray?a.ec.subarray(0,a.ic):new Uint8Array(a.ec):new Uint8Array},wd:function(a,b){var c=a.ec?a.ec.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.ec,a.ec=new Uint8Array(b),0<a.ic&&a.ec.set(c.subarray(0,a.ic),0))},he:function(a,b){if(a.ic!=b)if(0==b)a.ec=null,a.ic=0;else{if(!a.ec||a.ec.subarray){var c=a.ec;a.ec=new Uint8Array(new ArrayBuffer(b));c&&
a.ec.set(c.subarray(0,Math.min(b,a.ic)))}else if(a.ec||(a.ec=[]),a.ec.length>b)a.ec.length=b;else for(;a.ec.length<b;)a.ec.push(0);a.ic=b}},hc:{yc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ic:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Dc=4096;b.blocks=Math.ceil(b.size/
b.Dc);return b},sc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.he(a,b.size)},lookup:function(){throw zb[N.Md];},Oc:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Ab(b,c)}catch(f){}if(d)for(var e in d.ec)throw new L(N.pd);}delete a.parent.ec[a.name];a.name=c;b.ec[c]=a;a.parent=b},unlink:function(a,b){delete a.ec[b]},rmdir:function(a,b){var c=Ab(a,b),d;for(d in c.ec)throw new L(N.pd);
delete a.ec[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ec)a.ec.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(N.rc);return a.link}},fc:{read:function(a,b,c,d,e){var f=a.node.ec;if(e>=a.node.ic)return 0;a=Math.min(a.node.ic-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.ec||a.ec.subarray)){if(f)return a.ec=b.subarray(c,c+d),a.ic=d;if(0===a.ic&&0===e)return a.ec=new Uint8Array(b.subarray(c,c+d)),a.ic=d;if(e+d<=a.ic)return a.ec.set(b.subarray(c,c+d),e),d}O.wd(a,e+d);if(a.ec.subarray&&b.subarray)a.ec.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ec[e+f]=b[c+f];a.ic=Math.max(a.ic,e+d);return d},Ac:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ic);if(0>b)throw new L(N.rc);return b},rd:function(a,
b,c){O.wd(a.node,b+c);a.node.ic=Math.max(a.node.ic,b+c)},Fd:function(a,b,c,d,e,f,l){if(32768!==(a.node.mode&61440))throw new L(N.bd);c=a.node.ec;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.ic)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=z(d);if(!d)throw new L(N.Nd);b.set(c,d)}else a=!1,d=c.byteOffset;return{Eg:d,Qd:a}},Xc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(N.bd);if(e&2)return 0;O.fc.write(a,b,0,d,c,!1);return 0}}},P={Vc:!1,
je:function(){P.Vc=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.zd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},sd:function(a){return Buffer.oc?Buffer.from(a):new Buffer(a)},pc:function(a){assert(q);return P.createNode(null,"/",P.Cd(a.hd.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(N.rc);a=yb(a,b,c);a.hc=P.hc;a.fc=P.fc;return a},Cd:function(a){try{var b=
fs.lstatSync(a);P.Vc&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}return b.mode},qc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.pc.hd.root);b.reverse();return ob.apply(null,b)},Wd:function(a){a&=-2656257;var b=0,c;for(c in P.zd)a&c&&(b|=P.zd[c],a^=c);if(a)throw new L(N.rc);return b},hc:{yc:function(a){a=P.qc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}P.Vc&&!b.Dc&&(b.Dc=4096);P.Vc&&!b.blocks&&
(b.blocks=(b.size+b.Dc-1)/b.Dc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Dc:b.Dc,blocks:b.blocks}},sc:function(a,b){var c=P.qc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},lookup:function(a,b){var c=K(P.qc(a),b);c=P.Cd(c);return P.createNode(a,b,c)},Oc:function(a,b,c,d){a=P.createNode(a,
b,c,d);b=P.qc(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new L(N[e.code]);}return a},rename:function(a,b,c){a=P.qc(a);b=K(P.qc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},unlink:function(a,b){a=K(P.qc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}},rmdir:function(a,b){a=K(P.qc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);
}},readdir:function(a){a=P.qc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(N[b.code]);}},symlink:function(a,b,c){a=K(P.qc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(N[d.code]);}},readlink:function(a){var b=P.qc(a);try{return b=fs.readlinkSync(b),b=Bb.relative(Bb.resolve(a.pc.hd.root),b)}catch(c){if(!c.code)throw c;throw new L(N[c.code]);}}},fc:{open:function(a){var b=P.qc(a.node);try{32768===(a.node.mode&61440)&&(a.Pc=fs.openSync(b,P.Wd(a.flags)))}catch(c){if(!c.code)throw c;
throw new L(N[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Pc&&fs.closeSync(a.Pc)}catch(b){if(!b.code)throw b;throw new L(N[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Pc,P.sd(b.buffer),c,d,e)}catch(f){throw new L(N[f.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Pc,P.sd(b.buffer),c,d,e)}catch(f){throw new L(N[f.code]);}},Ac:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Pc).size}catch(d){throw new L(N[d.code]);
}if(0>b)throw new L(N.rc);return b}}},Cb=null,Db={},Eb=[],Fb=1,Gb=null,Hb=!0,Ib={},L=null,zb={};
function Q(a,b){a=pb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ad:!0,kd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.kd)throw new L(40);a=kb(a.split("/").filter(function(a){return!!a}),!1);var e=Cb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Ab(e,a[d]);c=K(c,a[d]);e.Wc&&(!f||f&&b.Ad)&&(e=e.Wc.root);if(!f||b.dd)for(f=0;40960===(e.mode&61440);)if(e=Jb(c),c=pb(mb(c),e),e=Q(c,{kd:b.kd}).node,40<f++)throw new L(40);}return{path:c,node:e}}
function Kb(a){for(var b;;){if(a===a.parent)return a=a.pc.Gd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Mb(a){var b=Lb(a.parent.id,a.name);a.ee=Gb[b];Gb[b]=a}function Ab(a,b){var c;if(c=(c=Nb(a,"x"))?c:a.hc.lookup?0:13)throw new L(c,a);for(c=Gb[Lb(a.id,b)];c;c=c.ee){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.hc.lookup(a,b)}
function yb(a,b,c,d){Ob||(Ob=function(a,b,c,d){a||(a=this);this.parent=a;this.pc=a.pc;this.Wc=null;this.id=Fb++;this.name=b;this.mode=c;this.hc={};this.fc={};this.rdev=d},Ob.prototype={},Object.defineProperties(Ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Ob(a,b,c,d);Mb(a);return a}
var Pb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Qb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Nb(a,b){if(Hb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Rb(a,b){try{return Ab(a,b),17}catch(c){}return Nb(a,"wx")}
function Sb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Eb[a])return a;throw new L(24);}function Tb(a,b){Ub||(Ub=function(){},Ub.prototype={},Object.defineProperties(Ub.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Ub,d;for(d in a)c[d]=a[d];a=c;b=Sb(b);a.fd=b;return Eb[b]=a}var xb={open:function(a){a.fc=Db[a.node.rdev].fc;a.fc.open&&a.fc.open(a)},Ac:function(){throw new L(29);}};function tb(a,b){Db[a]={fc:b}}
function Vb(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new L(16);if(!c&&!d){var e=Q(b,{Ad:!1});b=e.path;e=e.node;if(e.Wc)throw new L(16);if(16384!==(e.mode&61440))throw new L(20);}b={type:a,hd:{},Gd:b,de:[]};a=a.pc(b);a.pc=b;b.root=a;c?Cb=a:e&&(e.Wc=b,e.pc&&e.pc.de.push(b))}function Wb(a,b,c){var d=Q(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new L(22);var e=Rb(d,a);if(e)throw new L(e);if(!d.hc.Oc)throw new L(1);return d.hc.Oc(d,a,b,c)}function T(a){Wb(a,16895,0)}
function Xb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Wb(a,b|8192,c)}function La(a,b){if(!pb(a))throw new L(2);var c=Q(b,{parent:!0}).node;if(!c)throw new L(2);b=nb(b);var d=Rb(c,b);if(d)throw new L(d);if(!c.hc.symlink)throw new L(1);c.hc.symlink(c,b,a)}function Jb(a){a=Q(a).node;if(!a)throw new L(2);if(!a.hc.readlink)throw new L(22);return pb(Kb(a.parent),a.hc.readlink(a))}
function Ma(a,b,c,d){if(""===a)throw new L(2);if("string"===typeof b){var e=Pb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=lb(a);try{f=Q(a,{dd:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(f){if(b&128)throw new L(17);}else f=Wb(a,c,0),e=!0;if(!f)throw new L(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new L(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Qb(b)||b&512)?21:Nb(f,Qb(b)):2))throw new L(c);if(b&512){c=f;var l;"string"===typeof c?l=Q(c,{dd:!0}).node:l=c;if(!l.hc.sc)throw new L(1);if(16384===(l.mode&61440))throw new L(21);if(32768!==(l.mode&61440))throw new L(22);if(c=Nb(l,"w"))throw new L(c);l.hc.sc(l,{size:0,timestamp:Date.now()})}b&=-641;d=Tb({node:f,path:Kb(f),flags:b,seekable:!0,position:0,fc:f.fc,oe:[],error:!1},d);d.fc.open&&d.fc.open(d);!m.logReadFiles||b&1||(Yb||(Yb={}),a in Yb||(Yb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Ib.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Ib.onOpenFile(a,f))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function Zb(a,b,c){if(null===a.fd)throw new L(9);if(!a.seekable||!a.fc.Ac)throw new L(29);if(0!=c&&1!=c&&2!=c)throw new L(22);a.position=a.fc.Ac(a,b,c);a.oe=[]}
function Ja(){L||(L=function(a,b){this.node=b;this.ie=function(a){this.xc=a};this.ie(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[2].forEach(function(a){zb[a]=new L(a);zb[a].stack="<generic error, no stack>"}))}var Ia;function $b(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ka(a,b,c){a=K("/dev",a);var d=$b(!!b,!!c);ac||(ac=64);var e=ac++<<8|0;tb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,l=0;l<e;l++){try{var r=b()}catch(M){throw new L(5);}if(void 0===r&&0===f)throw new L(11);if(null===r||void 0===r)break;f++;c[d+l]=r}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(A){throw new L(5);}e&&(a.node.timestamp=Date.now());return f}});
Xb(a,d,e)}
var ac,U={},Ob,Ub,Yb,N={Od:1,Md:2,hg:3,Ye:4,od:5,qd:6,pe:7,Af:8,Ld:9,Ee:10,Kd:11,rg:11,Nd:12,Jd:13,Re:14,Mf:15,Ce:16,Qe:17,sg:18,bd:19,Of:20,$e:21,rc:22,vf:23,mf:24,Gc:25,og:26,Se:27,If:28,gg:29,dg:30,nf:31,Xf:32,Ne:33,ag:34,Ef:42,Ve:43,Fe:44,bf:45,cf:46,df:47,kf:48,pg:49,yf:50,af:51,Ke:35,Bf:37,ve:52,ye:53,tg:54,wf:55,ze:56,Ae:57,Le:35,Be:59,Kf:60,zf:61,lg:62,Jf:63,Ff:64,Gf:65,cg:66,Cf:67,se:68,ig:69,Ge:70,Yf:71,qf:72,Oe:73,xe:74,Sf:76,we:77,bg:78,ef:79,ff:80,jf:81,hf:82,gf:83,Lf:38,pd:39,rf:36,
lf:40,Tf:95,Wf:96,Je:104,xf:105,te:97,$f:91,Qf:88,Hf:92,eg:108,Ie:111,qe:98,He:103,uf:101,sf:100,mg:110,Te:112,Ue:113,Xe:115,ue:114,Me:89,pf:90,Zf:93,fg:94,re:99,tf:102,Ze:106,Nf:107,ng:109,qg:87,Pe:122,jg:116,Rf:95,Df:123,We:84,Uf:75,De:125,Pf:131,Vf:130,kg:86},bc={},V=0;function W(){V+=4;return y[V-4>>2]}function cc(){var a=Eb[W()];if(!a)throw new L(N.Ld);return a}var dc=0,ec=0,X=0,fc=0,hc=null,ic=null,jc=!1;function kc(){for(var a=Y.length-1;0<=a;--a)lc(a);Y=[];mc=[]}var mc=[];
function nc(){if(oc&&pc.Jc)for(var a=0;a<mc.length;++a){var b=mc[a];mc.splice(a,1);--a;b.Gg.apply(this,b.ug)}}var oc=0,pc=null,Y=[];function qc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function lc(a){var b=Y[a];b.target.removeEventListener(b.Ec,b.Vd,b.Rc);Y.splice(a,1)}
function rc(a){function b(b){++oc;pc=a;nc();a.Uc(b);nc();--oc}if(a.Tc)a.Vd=b,a.target.addEventListener(a.Ec,b,a.Rc),Y.push(a),jc||(Ea.push(kc),jc=!0);else for(var c=0;c<Y.length;++c)Y[c].target==a.target&&Y[c].Ec==a.Ec&&lc(c--)}var sc={},tc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function uc(a){try{if(!a)return window;"number"===typeof a&&(a=tc[a]||D(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?m.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function vc(a){"number"===typeof a&&(a=D(a));return a&&"#canvas"!==a?"undefined"!==typeof h&&h.Yc[a]?h.Yc[a]:uc(a):"undefined"!==typeof h&&h.Yc.canvas?h.Yc.canvas:m.canvas}function ma(){return B.length}function wc(){u("OOM")}
function xc(a,b,c,d,e,f){dc||(dc=z(164));a={target:uc(a),Jc:qc()?!1:!0,Ec:f,Tc:d,Uc:function(a){a=a||window.event;var c=dc;E(a.key?a.key:"",C,c+0,32);E(a.code?a.code:"",C,c+32,32);y[c+64>>2]=a.location;y[c+68>>2]=a.ctrlKey;y[c+72>>2]=a.shiftKey;y[c+76>>2]=a.altKey;y[c+80>>2]=a.metaKey;y[c+84>>2]=a.repeat;E(a.locale?a.locale:"",C,c+88,32);E(a.char?a.char:"",C,c+120,32);y[c+152>>2]=a.charCode;y[c+156>>2]=a.keyCode;y[c+160>>2]=a.which;yc(d,e,c,b)&&a.preventDefault()},Rc:c};rc(a)}
function zc(a,b,c){G[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();y[a+8>>2]=b.screenX;y[a+12>>2]=b.screenY;y[a+16>>2]=b.clientX;y[a+20>>2]=b.clientY;y[a+24>>2]=b.ctrlKey;y[a+28>>2]=b.shiftKey;y[a+32>>2]=b.altKey;y[a+36>>2]=b.metaKey;wa[a+40>>1]=b.button;wa[a+42>>1]=b.buttons;y[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-hc;y[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-ic;if(m.canvas){var d=m.canvas.getBoundingClientRect();
y[a+60>>2]=b.clientX-d.left;y[a+64>>2]=b.clientY-d.top}else y[a+60>>2]=0,y[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},y[a+52>>2]=b.clientX-d.left,y[a+56>>2]=b.clientY-d.top):(y[a+52>>2]=0,y[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(hc=b.screenX,ic=b.screenY)}
function Ac(a,b,c,d,e,f){ec||(ec=z(72));a=uc(a);c={target:a,Jc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ec:f,Tc:d,Uc:function(c){c=c||window.event;zc(ec,c,a);yc(d,e,ec,b)&&c.preventDefault()},Rc:c};qc()&&"mousedown"==f&&(c.Jc=!1);rc(c)}
function Bc(a,b,c,d){fc||(fc=z(36));a=uc(a);rc({target:a,Jc:!1,Ec:"resize",Tc:d,Uc:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=fc;y[l>>2]=c.detail;y[l+4>>2]=document.body.clientWidth;
y[l+8>>2]=document.body.clientHeight;y[l+12>>2]=window.innerWidth;y[l+16>>2]=window.innerHeight;y[l+20>>2]=window.outerWidth;y[l+24>>2]=window.outerHeight;y[l+28>>2]=e[0];y[l+32>>2]=e[1];yc(d,10,l,b)&&c.preventDefault()}},Rc:c})}
function Cc(a,b,c,d,e){function f(c){c=c||window.event;zc(X,c,a);G[X+72>>3]=c.wheelDeltaX||0;G[X+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);G[X+88>>3]=0;y[X+96>>2]=0;yc(d,9,X,b)&&c.preventDefault()}function l(c){c=c||window.event;var e=X;zc(e,c,a);G[e+72>>3]=c.deltaX;G[e+80>>3]=c.deltaY;G[e+88>>3]=c.deltaZ;y[e+96>>2]=c.deltaMode;yc(d,9,e,b)&&c.preventDefault()}X||(X=z(104));rc({target:a,Jc:!0,Ec:e,Tc:d,Uc:"wheel"==e?l:f,Rc:c})}
function Dc(){if(!h.nc||!h.nc.zc)return-3;if(!h.nc.zc.Rd)return-1;if(!h.nc.attributes.xd)return-3;h.nc.zc.Rd();return 0}
h={ud:1,Lc:0,Sc:[],Bg:{},mc:[],Bd:[],ld:[],nd:[],kc:[],tc:[],ad:[],uc:{},nc:null,Yc:{},Hg:[],Qc:{},md:{},Id:4,Yd:function(){h.Ed=new Float32Array(h.wc);for(var a=0;a<h.wc;a++)h.Bc[a]=h.Ed.subarray(0,a+1)},jc:function(a){h.Lc||(h.Lc=a)},Kc:function(a){for(var b=h.ud++,c=a.length;c<b;c++)a[c]=null;return b},wc:256,Ed:null,Bc:[0],Xd:function(a,b,c,d){a="";for(var e=0;e<b;++e){var f=d?y[d+4*e>>2]:-1;a+=D(y[c+4*e>>2],0>f?void 0:f)}return a},createContext:function(a,b){return(a=a.getContext("webgl",b)||
a.getContext("experimental-webgl",b))&&h.ge(a,b)},ge:function(a,b){var c=z(8),d={handle:c,attributes:b,version:b.be,zc:a};a.canvas&&(a.canvas.Pd=d);h.uc[c]=d;("undefined"===typeof b.vd||b.vd)&&h.Zd(d);return c},ce:function(a){h.nc=h.uc[a];m.vg=k=h.nc&&h.nc.zc;return!(a&&!k)},getContext:function(a){return h.uc[a]},Ud:function(a){h.nc===h.uc[a]&&(h.nc=null);if("object"===typeof sc)for(var b=h.uc[a].zc.canvas,c=0;c<Y.length;++c)Y[c].target!=b||lc(c--);h.uc[a]&&h.uc[a].zc.canvas&&(h.uc[a].zc.canvas.Pd=
void 0);Ec(h.uc[a]);h.uc[a]=null},Zd:function(a){a||(a=h.nc);if(!a.$d){a.$d=!0;var b=a.zc;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,f){c.drawElementsInstancedANGLE(a,b,d,e,f)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.wg=b.getExtension("EXT_disjoint_timer_query");var f="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=f.indexOf(a)&&b.getExtension(a)})}},fe:function(a){var b=h.mc[a];a=h.Qc[a]={kc:{},gd:0,Mc:-1,Nc:-1};for(var c=a.kc,d=k.getProgramParameter(b,35718),e=0;e<d;++e){var f=k.getActiveUniform(b,e),l=f.name;a.gd=Math.max(a.gd,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var r=k.getUniformLocation(b,l);if(r){var v=h.Kc(h.kc);c[l]=[f.size,v];h.kc[v]=r;for(var x=1;x<f.size;++x)r=k.getUniformLocation(b,
l+"["+x+"]"),v=h.Kc(h.kc),h.kc[v]=r}}}};var Fc=["default","low-power","high-performance"];function Gc(a){return h.ce(a)?0:-5}m._emscripten_webgl_make_context_current=Gc;function Hc(a){if(0===a)return 0;a=D(a);if(!J.hasOwnProperty(a))return 0;Hc.oc&&Ec(Hc.oc);a=J[a];var b=ta(a)+1,c=z(b);c&&E(a,B,c,b);Hc.oc=c;return Hc.oc}var Ic=[];function Jc(a,b,c,d){for(var e=0;e<a;e++){var f=k[c](),l=f&&h.Kc(d);f?(f.name=l,d[l]=f):h.jc(1282);y[b+4*e>>2]=l}}
function Kc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:"Integer"!==c&&"Integer64"!==c&&h.jc(1280);return;case 36345:d=0;break;case 34466:var e=k.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=k.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":h.jc(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:h.jc(1280);return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case "Integer":y[b+4*a>>2]=e[a];break;case "Float":F[b+4*a>>2]=e[a];break;case "Boolean":B[b+a>>0]=e[a]?1:0;break;default:throw"internal glGet error, bad type: "+c;}return}try{d=e.name|0}catch(f){h.jc(1280);w("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:h.jc(1280);return}switch(c){case "Integer64":aa=
[d>>>0,(g=d,1<=+Oa(g)?0<g?(Ta(+Sa(g/4294967296),4294967295)|0)>>>0:~~+Ra((g-+(~~g>>>0))/4294967296)>>>0:0)];y[b>>2]=aa[0];y[b+4>>2]=aa[1];break;case "Integer":y[b>>2]=d;break;case "Float":F[b>>2]=d;break;case "Boolean":B[b>>0]=d?1:0;break;default:throw"internal glGet error, bad type: "+c;}}else h.jc(1281)}function Lc(a){var b=ta(a)+1,c=z(b);E(a,C,c,b);return c}var Mc={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},Nc={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};
function Oc(a,b,c,d,e){if(b=Mc[b]*Nc[a]){var f=h.Id;c=e+d*(c*b+f-1&-f);switch(a){case 5121:return C.subarray(e,c);case 5126:return F.subarray(e>>2,c>>2);case 5125:case 34042:return ya.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return xa.subarray(e>>1,c>>1);default:h.jc(1280)}}else h.jc(1280)}function Z(){Z.oc||(Z.oc=[]);Z.oc.push(Pc());return Z.oc.length-1}function Qc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Rc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Sc=[31,29,31,30,31,30,31,31,30,31,30,31],Tc=[31,28,31,30,31,30,31,31,30,31,30,31];function Uc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Qc(a.getFullYear())?Sc:Tc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Vc(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function v(a){a=Uc(new Date(a.lc+1900,0,1),a.$c);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=l(r(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var x=y[d+40>>2];d={me:y[d>>2],le:y[d+4>>2],Zc:y[d+8>>2],Fc:y[d+12>>2],Cc:y[d+16>>2],lc:y[d+20>>2],Hd:y[d+24>>2],$c:y[d+28>>2],Ig:y[d+32>>2],ke:y[d+36>>2],
ne:x?D(x):""};c=D(c);x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var A in x)c=c.replace(new RegExp(A,"g"),x[A]);var R="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),M="January February March April May June July August September October November December".split(" ");x={"%a":function(a){return R[a.Hd].substring(0,3)},"%A":function(a){return R[a.Hd]},"%b":function(a){return M[a.Cc].substring(0,
3)},"%B":function(a){return M[a.Cc]},"%C":function(a){return f((a.lc+1900)/100|0,2)},"%d":function(a){return f(a.Fc,2)},"%e":function(a){return e(a.Fc,2," ")},"%g":function(a){return v(a).toString().substring(2)},"%G":function(a){return v(a)},"%H":function(a){return f(a.Zc,2)},"%I":function(a){a=a.Zc;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Fc+Rc(Qc(a.lc+1900)?Sc:Tc,a.Cc-1),3)},"%m":function(a){return f(a.Cc+1,2)},"%M":function(a){return f(a.le,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.Zc&&12>a.Zc?"AM":"PM"},"%S":function(a){return f(a.me,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.lc+1900,a.Cc+1,a.Fc,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.lc+1900,0,1),c=0===b.getDay()?b:Uc(b,7-b.getDay());a=new Date(a.lc+1900,a.Cc,a.Fc);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Rc(Qc(a.getFullYear())?Sc:Tc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.lc+1900,0,4)),c=r(new Date(a.lc+
1901,0,4)),d=Uc(new Date(a.lc+1900,0,1),a.$c);return 0>l(d,b)?"53":0>=l(c,d)?"01":f(Math.ceil((b.getFullYear()<a.lc+1900?a.$c+32-b.getDate():a.$c+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.lc+1900,a.Cc+1,a.Fc,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.lc,0,1),c=1===b.getDay()?b:Uc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.lc+1900,a.Cc,a.Fc);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Rc(Qc(a.getFullYear())?Sc:Tc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":
"00"},"%y":function(a){return(a.lc+1900).toString().substring(2)},"%Y":function(a){return a.lc+1900},"%z":function(a){a=a.ke;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.ne},"%%":function(){return"%"}};for(A in x)0<=c.indexOf(A)&&(c=c.replace(new RegExp(A,"g"),x[A](d)));A=ab(c,!1);if(A.length>b)return 0;B.set(A,a);return A.length-1}Ja();Gb=Array(4096);Vb(O,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");tb(259,{read:function(){return 0},write:function(a,b,c,l){return l}});Xb("/dev/null",259);sb(1280,vb);sb(1536,wb);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(q)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});Ka("random",b);Ka("urandom",b);T("/dev/shm");
T("/dev/shm/tmp")})();T("/proc");T("/proc/self");T("/proc/self/fd");Vb({pc:function(){var a=yb("/proc/self","fd",16895,73);a.hc={lookup:function(a,c){var b=Eb[+c];if(!b)throw new L(9);a={parent:null,pc:{Gd:"fake"},hc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(q){var fs=require("fs"),Bb=require("path");P.je()}h.Yd();for(var Wc=0;32>Wc;Wc++)Ic.push(Array(Wc));function ab(a,b){var c=Array(ta(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var $c=m.asm({},{d:u,c:function(a,b,c,d){u("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},Ta:ib,f:function(a){return z(a)},Aa:function(){pa=!0;throw"Pure virtual function called!";},e:function(a){"uncaught_exception"in Xc?Xc.yd++:Xc.yd=1;throw a;},ka:function(){return!!Xc.yd},l:function(){},S:function(){jb(1);return-1},r:jb,B:function(a,b){V=b;try{var c=cc();W();var d=W(),e=W(),f=W();Zb(c,d,f);y[e>>2]=c.position;c.ed&&0===d&&0===f&&(c.ed=null);return 0}catch(l){return"undefined"!==
typeof U&&l instanceof L||u(l),-l.xc}},jb:function(a,b){V=b;try{var c=cc(),d=W();a:{var e=W();for(b=a=0;b<e;b++){var f=y[d+(8*b+4)>>2],l=c,r=y[d+8*b>>2],v=f,x=void 0,A=B;if(0>v||0>x)throw new L(22);if(null===l.fd)throw new L(9);if(1===(l.flags&2097155))throw new L(9);if(16384===(l.node.mode&61440))throw new L(21);if(!l.fc.read)throw new L(22);var R="undefined"!==typeof x;if(!R)x=l.position;else if(!l.seekable)throw new L(29);var M=l.fc.read(l,A,r,v,x);R||(l.position+=M);var ea=M;if(0>ea){var S=-1;
break a}a+=ea;if(ea<f)break}S=a}return S}catch(qb){return"undefined"!==typeof U&&qb instanceof L||u(qb),-qb.xc}},z:function(a,b){V=b;try{var c=cc(),d=W();a:{var e=W();for(b=a=0;b<e;b++){var f=c,l=y[d+8*b>>2],r=y[d+(8*b+4)>>2],v=void 0,x=B;if(0>r||0>v)throw new L(22);if(null===f.fd)throw new L(9);if(0===(f.flags&2097155))throw new L(9);if(16384===(f.node.mode&61440))throw new L(21);if(!f.fc.write)throw new L(22);f.flags&1024&&Zb(f,0,2);var A="undefined"!==typeof v;if(!A)v=f.position;else if(!f.seekable)throw new L(29);
var R=f.fc.write(f,x,l,r,v,void 0);A||(f.position+=R);try{if(f.path&&Ib.onWriteToFile)Ib.onWriteToFile(f.path)}catch(S){console.log("FS.trackingDelegate['onWriteToFile']('"+f.path+"') threw an exception: "+S.message)}var M=R;if(0>M){var ea=-1;break a}a+=M}ea=a}return ea}catch(S){return"undefined"!==typeof U&&S instanceof L||u(S),-S.xc}},m:function(a,b){V=b;try{var c=cc();switch(W()){case 0:var d=W();return 0>d?-N.rc:Ma(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=
W(),c.flags|=d,0;case 12:return d=W(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-N.rc;case 9:return jb(N.rc),-1;default:return-N.rc}}catch(e){return"undefined"!==typeof U&&e instanceof L||u(e),-e.xc}},Wa:function(a,b){V=b;try{var c=D(W());var d=W();if(d&-8)var e=-N.rc;else{var f=Q(c,{dd:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Nb(f,a)?-N.Jd:0}return e}catch(l){return"undefined"!==typeof U&&l instanceof L||u(l),-l.xc}},Va:function(a,b){V=b;try{var c=D(W()),d=
W(),e=W();return Ma(c,d,e).fd}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.xc}},y:function(a,b){V=b;try{var c=cc(),d=W();switch(d){case 21509:case 21505:return c.tty?0:-N.Gc;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-N.Gc;case 21519:if(!c.tty)return-N.Gc;var e=W();return y[e>>2]=0;case 21520:return c.tty?-N.rc:-N.Gc;case 21531:a=e=W();if(!c.fc.ae)throw new L(25);return c.fc.ae(c,d,a);case 21523:return c.tty?0:-N.Gc;case 21524:return c.tty?0:
-N.Gc;default:u("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.xc}},x:function(a,b){V=b;try{var c=cc();if(null===c.fd)throw new L(9);c.ed&&(c.ed=null);try{c.fc.close&&c.fc.close(c)}catch(d){throw d;}finally{Eb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.xc}},Ua:function(a,b){V=b;try{var c=W(),d=W(),e=bc[c];if(!e)return 0;if(d===e.zg){var f=Eb[e.fd],l=e.flags,r=new Uint8Array(C.subarray(c,c+d));f&&f.fc.Xc&&f.fc.Xc(f,
r,0,d,l);bc[c]=null;e.Qd&&Ec(e.Ag)}return 0}catch(v){return"undefined"!==typeof U&&v instanceof L||u(v),-v.xc}},j:function(){},b:function(){m.abort()},Sa:function(a){return bb[a]()},Ra:function(a,b){return bb[a](b)},Qa:function(a,b,c){return bb[a](b,c)},Pa:function(a,b,c){a=vc(a);if(!a)return-4;y[b>>2]=a.width;y[c>>2]=a.height},Oa:function(){return window.devicePixelRatio||1},Na:function(a,b,c){a=a?uc(a):m.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),G[b>>3]=a.right-
a.left,G[c>>3]=a.bottom-a.top):(G[b>>3]=a.clientWidth,G[c>>3]=a.clientHeight);return 0},Ma:ma,La:function(a,b,c){C.set(C.subarray(b,b+c),a)},Ka:function(a){wc(a)},w:function(a,b,c){a=vc(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ja:function(a,b,c,d){xc(a,b,c,d,2,"keydown");return 0},Ia:function(a,b,c,d){xc(a,b,c,d,3,"keyup");return 0},Ha:function(a,b,c,d){Ac(a,b,c,d,5,"mousedown");return 0},Ga:function(a,b,c,d){Ac(a,b,c,d,8,"mousemove");return 0},Fa:function(a,b,c,d){Ac(a,b,c,d,6,"mouseup");
return 0},Ea:function(a,b,c,d){Bc(a,b,c,d);return 0},Da:function(a,b,c,d){a=uc(a);return"undefined"!==typeof a.onwheel?(Cc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Cc(a,b,c,d,"mousewheel"),0):-1},Ca:function(){return Dc()},Ba:function(a,b){var c={};b>>=2;c.alpha=!!y[b];c.depth=!!y[b+1];c.stencil=!!y[b+2];c.antialias=!!y[b+3];c.premultipliedAlpha=!!y[b+4];c.preserveDrawingBuffer=!!y[b+5];c.powerPreference=Fc[y[b+6]];c.failIfMajorPerformanceCaveat=!!y[b+7];c.be=y[b+8];c.Cg=y[b+9];c.vd=
y[b+10];c.xd=y[b+11];c.Dg=y[b+12];c.Fg=y[b+13];a=vc(a);return!a||c.xd?0:h.createContext(a,c)},za:function(a){h.nc==a&&(h.nc=0);h.Ud(a)},ya:function(a){a>>=2;for(var b=0;14>b;++b)y[a+b]=0;y[a]=y[a+1]=y[a+3]=y[a+4]=y[a+8]=y[a+10]=1},xa:Gc,v:function(a){Yc(a)},i:Hc,p:function(a){k.activeTexture(a)},wa:function(a,b){k.attachShader(h.mc[a],h.tc[b])},va:function(a,b,c){k.bindAttribLocation(h.mc[a],b,D(c))},u:function(a,b){k.bindBuffer(a,h.Sc[b])},ua:function(a,b){k.bindFramebuffer(a,h.Bd[b])},ta:function(a,
b){k.bindRenderbuffer(a,h.ld[b])},o:function(a,b){k.bindTexture(a,h.nd[b])},sa:function(a){k.bindVertexArray(h.ad[a])},ra:function(a,b,c,d){k.bufferData(a,c?C.subarray(c,c+b):b,d)},qa:function(a,b,c,d){k.bufferSubData(a,b,C.subarray(d,d+c))},pa:function(a){return k.checkFramebufferStatus(a)},oa:function(a){k.clear(a)},na:function(a,b,c,d){k.clearColor(a,b,c,d)},ma:function(a){k.clearDepth(a)},la:function(a){k.compileShader(h.tc[a])},t:function(a,b,c,d,e,f,l,r,v){k.compressedTexSubImage2D(a,b,c,d,
e,f,l,v?C.subarray(v,v+r):null)},ja:function(a,b,c,d,e,f,l,r){k.copyTexSubImage2D(a,b,c,d,e,f,l,r)},ia:function(){var a=h.Kc(h.mc),b=k.createProgram();b.name=a;h.mc[a]=b;return a},ha:function(a){var b=h.Kc(h.tc);h.tc[b]=k.createShader(a);return b},ga:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=h.Sc[d];e&&(k.deleteBuffer(e),e.name=0,h.Sc[d]=null,d==h.Sd&&(h.Sd=0),d==h.Td&&(h.Td=0))}},fa:function(a){if(a){var b=h.mc[a];b?(k.deleteProgram(b),b.name=0,h.mc[a]=null,h.Qc[a]=null):h.jc(1281)}},
ea:function(a){if(a){var b=h.tc[a];b?(k.deleteShader(b),h.tc[a]=null):h.jc(1281)}},da:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];k.deleteVertexArray(h.ad[d]);h.ad[d]=null}},ca:function(a){k.disableVertexAttribArray(a)},ba:function(a,b,c){k.drawArrays(a,b,c)},aa:function(a,b,c,d){k.drawArraysInstanced(a,b,c,d)},$:function(a,b){for(var c=Ic[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];k.drawBuffers(c)},_:function(a,b,c,d){k.drawElements(a,b,c,d)},Z:function(a,b,c,d,e){k.drawElementsInstanced(a,b,c,d,e)},
Y:function(a){k.enableVertexAttribArray(a)},X:function(a,b,c,d){k.framebufferRenderbuffer(a,b,c,h.ld[d])},W:function(a,b,c,d,e){k.framebufferTexture2D(a,b,c,h.nd[d],e)},V:function(a,b){Jc(a,b,"createBuffer",h.Sc)},U:function(a,b){Jc(a,b,"createFramebuffer",h.Bd)},T:function(a,b){Jc(a,b,"createRenderbuffer",h.ld)},R:function(a,b){Jc(a,b,"createTexture",h.nd)},Q:function(a,b){Jc(a,b,"createVertexArray",h.ad)},P:function(a){k.generateMipmap(a)},O:function(a,b,c){c?y[c>>2]=k.getBufferParameter(a,b):h.jc(1281)},
N:function(){if(h.Lc){var a=h.Lc;h.Lc=0;return a}return k.getError()},M:function(a,b){Kc(a,b,"Float")},n:function(a,b){Kc(a,b,"Integer")},L:function(a,b,c,d){a=k.getProgramInfoLog(h.mc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},s:function(a,b,c){if(c)if(a>=h.ud)h.jc(1281);else{var d=h.Qc[a];if(d)if(35716==b)a=k.getProgramInfoLog(h.mc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b)y[c>>2]=d.gd;else if(35722==b){if(-1==d.Mc){a=h.mc[a];
var e=k.getProgramParameter(a,35721);for(b=d.Mc=0;b<e;++b)d.Mc=Math.max(d.Mc,k.getActiveAttrib(a,b).name.length+1)}y[c>>2]=d.Mc}else if(35381==b){if(-1==d.Nc)for(a=h.mc[a],e=k.getProgramParameter(a,35382),b=d.Nc=0;b<e;++b)d.Nc=Math.max(d.Nc,k.getActiveUniformBlockName(a,b).length+1);y[c>>2]=d.Nc}else y[c>>2]=k.getProgramParameter(h.mc[a],b);else h.jc(1282)}else h.jc(1281)},K:function(a,b,c,d){a=k.getShaderInfoLog(h.tc[a]);null===a&&(a="(unknown error)");0<b&&d?(b=E(a,C,d,b),c&&(y[c>>2]=b)):c&&(y[c>>
2]=0)},q:function(a,b,c){c?35716==b?(a=k.getShaderInfoLog(h.tc[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1):35720==b?(a=k.getShaderSource(h.tc[a]),y[c>>2]=null===a||0==a.length?0:a.length+1):y[c>>2]=k.getShaderParameter(h.tc[a],b):h.jc(1281)},k:function(a){if(h.md[a])return h.md[a];switch(a){case 7939:var b=k.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Lc(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=k.getParameter(a))||h.jc(1280);
b=Lc(b);break;case 7938:b=Lc("OpenGL ES 2.0 ("+k.getParameter(k.VERSION)+")");break;case 35724:b=k.getParameter(k.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Lc(b);break;default:return h.jc(1280),0}return h.md[a]=b},J:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=h.Qc[a]&&h.Qc[a].kc[b])&&
0<=c&&c<a[0]?a[1]+c:-1},I:function(a){k.linkProgram(h.mc[a]);h.fe(a)},H:function(a,b){3317==a&&(h.Id=b);k.pixelStorei(a,b)},G:function(a,b,c,d,e,f,l){(l=Oc(f,e,c,d,l))?k.readPixels(a,b,c,d,e,f,l):h.jc(1280)},F:function(a,b,c,d){k.renderbufferStorage(a,b,c,d)},E:function(a,b,c,d){b=h.Xd(a,b,c,d);k.shaderSource(h.tc[a],b)},D:function(a,b,c,d,e,f,l,r,v){k.texImage2D(a,b,c,d,e,f,l,r,v?Oc(r,l,d,e,v):null)},C:function(a,b,c){k.texParameterf(a,b,c)},sb:function(a,b,c){k.texParameterf(a,b,F[c>>2])},rb:function(a,
b,c){k.texParameteri(a,b,c)},A:function(a,b,c,d,e,f,l,r,v){var x=null;v&&(x=Oc(r,l,e,f,v));k.texSubImage2D(a,b,c,d,e,f,l,r,x)},qb:function(a,b,c){if(b<=h.wc)for(var d=h.Bc[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);k.uniform1fv(h.kc[a],d)},pb:function(a,b,c){k.uniform1iv(h.kc[a],y.subarray(c>>2,c+4*b>>2))},ob:function(a,b,c){if(2*b<=h.wc)for(var d=h.Bc[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);k.uniform2fv(h.kc[a],d)},nb:function(a,
b,c){k.uniform2iv(h.kc[a],y.subarray(c>>2,c+8*b>>2))},mb:function(a,b,c){if(3*b<=h.wc)for(var d=h.Bc[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);k.uniform3fv(h.kc[a],d)},lb:function(a,b,c){k.uniform3iv(h.kc[a],y.subarray(c>>2,c+12*b>>2))},kb:function(a,b,c){if(4*b<=h.wc)for(var d=h.Bc[4*b-1],e=0;e<4*b;e+=4)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2],d[e+3]=F[c+(4*e+12)>>2];else d=F.subarray(c>>2,c+16*b>>
2);k.uniform4fv(h.kc[a],d)},ib:function(a,b,c){k.uniform4iv(h.kc[a],y.subarray(c>>2,c+16*b>>2))},hb:function(a,b,c,d){if(4*b<=h.wc)for(var e=h.Bc[4*b-1],f=0;f<4*b;f+=4)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);k.uniformMatrix2fv(h.kc[a],!!c,e)},gb:function(a,b,c,d){if(9*b<=h.wc)for(var e=h.Bc[9*b-1],f=0;f<9*b;f+=9)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>
2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);k.uniformMatrix3fv(h.kc[a],!!c,e)},fb:function(a,b,c,d){if(16*b<=h.wc)for(var e=h.Bc[16*b-1],f=0;f<16*b;f+=16)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2],e[f+9]=F[d+(4*f+36)>>2],e[f+10]=F[d+(4*f+40)>>2],e[f+
11]=F[d+(4*f+44)>>2],e[f+12]=F[d+(4*f+48)>>2],e[f+13]=F[d+(4*f+52)>>2],e[f+14]=F[d+(4*f+56)>>2],e[f+15]=F[d+(4*f+60)>>2];else e=F.subarray(d>>2,d+64*b>>2);k.uniformMatrix4fv(h.kc[a],!!c,e)},eb:function(a){k.useProgram(h.mc[a])},db:function(a,b){k.vertexAttribDivisor(a,b)},cb:function(a,b,c,d,e,f){k.vertexAttribPointer(a,b,c,!!d,e,f)},bb:function(a,b,c,d){k.viewport(a,b,c,d)},ab:Pa,$a:Qa,h:function(a){var b=Z.oc[a];Z.oc.splice(a,1);Zc(b)},g:Z,_a:function(){u("trap!")},Za:function(){return 0},Ya:function(a,
b,c,d){return Vc(a,b,c,d)},Xa:wc,a:la},buffer);m.asm=$c;
var eb=m.__GLOBAL__sub_I_b2ContactManager_cpp=function(){return m.asm.tb.apply(null,arguments)},fb=m.__GLOBAL__sub_I_b2Math_cpp=function(){return m.asm.ub.apply(null,arguments)},cb=m.__GLOBAL__sub_I_driverSpecific_cpp=function(){return m.asm.vb.apply(null,arguments)},hb=m.__GLOBAL__sub_I_iostream_cpp=function(){return m.asm.wb.apply(null,arguments)},db=m.__GLOBAL__sub_I_resource_MagnumShaders_RCS_cpp=function(){return m.asm.xb.apply(null,arguments)},Xc=m.__ZSt18uncaught_exceptionv=function(){return m.asm.yb.apply(null,
arguments)},gb=m.___emscripten_environ_constructor=function(){return m.asm.zb.apply(null,arguments)};m.___errno_location=function(){return m.asm.Ab.apply(null,arguments)};var Ec=m._free=function(){return m.asm.Bb.apply(null,arguments)};m._main=function(){return m.asm.Cb.apply(null,arguments)};
var z=m._malloc=function(){return m.asm.Db.apply(null,arguments)},va=m.stackAlloc=function(){return m.asm.bc.apply(null,arguments)},Zc=m.stackRestore=function(){return m.asm.cc.apply(null,arguments)},Pc=m.stackSave=function(){return m.asm.dc.apply(null,arguments)};m.dynCall_ii=function(){return m.asm.Eb.apply(null,arguments)};m.dynCall_iii=function(){return m.asm.Fb.apply(null,arguments)};var yc=m.dynCall_iiii=function(){return m.asm.Gb.apply(null,arguments)};
m.dynCall_iiiii=function(){return m.asm.Hb.apply(null,arguments)};m.dynCall_iiiiid=function(){return m.asm.Ib.apply(null,arguments)};m.dynCall_iiiiii=function(){return m.asm.Jb.apply(null,arguments)};m.dynCall_iiiiiid=function(){return m.asm.Kb.apply(null,arguments)};m.dynCall_iiiiiii=function(){return m.asm.Lb.apply(null,arguments)};m.dynCall_iiiiiiii=function(){return m.asm.Mb.apply(null,arguments)};m.dynCall_iiiiiiiii=function(){return m.asm.Nb.apply(null,arguments)};
m.dynCall_iiiiij=function(){return m.asm.Ob.apply(null,arguments)};m.dynCall_v=function(){return m.asm.Pb.apply(null,arguments)};m.dynCall_vf=function(){return m.asm.Qb.apply(null,arguments)};m.dynCall_vi=function(){return m.asm.Rb.apply(null,arguments)};m.dynCall_vif=function(){return m.asm.Sb.apply(null,arguments)};m.dynCall_vii=function(){return m.asm.Tb.apply(null,arguments)};m.dynCall_viif=function(){return m.asm.Ub.apply(null,arguments)};
m.dynCall_viii=function(){return m.asm.Vb.apply(null,arguments)};m.dynCall_viiii=function(){return m.asm.Wb.apply(null,arguments)};m.dynCall_viiiii=function(){return m.asm.Xb.apply(null,arguments)};m.dynCall_viiiiii=function(){return m.asm.Yb.apply(null,arguments)};m.dynCall_viiiiiii=function(){return m.asm.Zb.apply(null,arguments)};m.dynCall_viiiiiiii=function(){return m.asm._b.apply(null,arguments)};m.dynCall_viiiiiiiii=function(){return m.asm.$b.apply(null,arguments)};
m.dynCall_viijii=function(){return m.asm.ac.apply(null,arguments)};m.asm=$c;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ia.prototype=Error();ia.prototype.constructor=ia;Va=function ad(){m.calledRun||bd();m.calledRun||(Va=ad)};
m.callMain=function(a){a=a||[];Ha();var b=a.length+1,c=va(4*(b+1));y[c>>2]=ua(m.thisProgram);for(var d=1;d<b;d++)y[(c>>2)+d]=ua(a[d-1]);y[(c>>2)+b]=0;try{var e=m._main(b,c,0);Yc(e,!0)}catch(f){f instanceof ia||("SimulateInfiniteLoop"==f?m.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),w("exception thrown: "+a),m.quit(1,f)))}finally{}};
function bd(a){function b(){if(!m.calledRun&&(m.calledRun=!0,!pa)){Ha();Hb=!1;Aa(Da);if(m.onRuntimeInitialized)m.onRuntimeInitialized();m._main&&cd&&m.callMain(a);if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();Fa.unshift(b)}Aa(Fa)}}a=a||m.arguments;if(!(0<H)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Na();Aa(Ba);0<H||m.calledRun||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},
1);b()},1)):b())}}m.run=bd;function Yc(a,b){if(!b||!m.noExitRuntime||0!==a){if(!m.noExitRuntime&&(pa=!0,m.onExit))m.onExit(a);m.quit(a,new ia(a))}}function u(a){if(m.onAbort)m.onAbort(a);void 0!==a?(ja(a),w(a),a=JSON.stringify(a)):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}m.abort=u;if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();var cd=!0;m.noInitialRun&&(cd=!1);m.noExitRuntime=!0;bd();
